export const chunk6 = [
  {
    id: 26,
    level: "N4",
    title: "Travel & Tourism",
    description: "Vocabulary for traveling in Japan",
    words: [
      { japanese: "旅行", romaji: "ryokou", english: "Travel", examples: [{ jp: "日本 旅行。", en: "Japan trip.", romaji: "Nihon ryokou." }, { jp: "旅行 鞄。", en: "Travel bag.", romaji: "Ryokou kaban." }] },
      { japanese: "観光", romaji: "kankou", english: "Sightseeing", examples: [{ jp: "観光 客。", en: "Tourist.", romaji: "Kankou kyaku." }, { jp: "観光 バス。", en: "Sightseeing bus.", romaji: "Kankou basu." }] },
      { japanese: "ホテル", romaji: "hoteru", english: "Hotel", examples: [{ jp: "ホテルを 予約する。", en: "Book hotel.", romaji: "Hoteru wo yoyaku suru." }, { jp: "きれいな ホテル。", en: "Clean hotel.", romaji: "Kirei na hoteru." }] },
      { japanese: "予約", romaji: "yoyaku", english: "Reservation", examples: [{ jp: "予約が あります。", en: "I have a reservation.", romaji: "Yoyaku ga arimasu." }, { jp: "電話で 予約する。", en: "Book by phone.", romaji: "Denwa de yoyaku suru." }] },
      { japanese: "パスポート", romaji: "pasupooto", english: "Passport", examples: [{ jp: "パスポートを 見せる。", en: "Show passport.", romaji: "Pasupooto wo miseru." }, { jp: "パスポートを 取る。", en: "Get passport.", romaji: "Pasupooto wo toru." }] },
      { japanese: "切符", romaji: "kippu", english: "Ticket", examples: [{ jp: "切符を 買う。", en: "Buy ticket.", romaji: "Kippu wo kau." }, { jp: "往復 切符。", en: "Round trip ticket.", romaji: "Oufuku kippu." }] },
      { japanese: "荷物", romaji: "nimotsu", english: "Luggage", examples: [{ jp: "荷物を 預ける。", en: "Check luggage.", romaji: "Nimotsu wo azukeru." }, { jp: "手 荷物。", en: "Hand luggage.", romaji: "Te nimotsu." }] },
      { japanese: "地図", romaji: "chizu", english: "Map", examples: [{ jp: "地図を 見る。", en: "Look at map.", romaji: "Chizu wo miru." }, { jp: "スマホの 地図。", en: "Phone map.", romaji: "Sumaho no chizu." }] },
      { japanese: "案内", romaji: "annai", english: "Guide/Information", examples: [{ jp: "町を 案内する。", en: "Guide the town.", romaji: "Machi wo annai suru." }, { jp: "案内所。", en: "Info center.", romaji: "Annaijo." }] },
      { japanese: "お土産", romaji: "omiyage", english: "Souvenir", examples: [{ jp: "お土産を 買う。", en: "Buy souvenir.", romaji: "Omiyage wo kau." }, { jp: "綺麗な お土産。", en: "Beautiful souvenir.", romaji: "Kirei na omiyage." }] },
      { japanese: "温泉", romaji: "onsen", english: "Hot spring", examples: [{ jp: "温泉に 入る。", en: "Enter onsen.", romaji: "Onsen ni hairu." }, { jp: "有名な 温泉。", en: "Famous onsen.", romaji: "Yuumei na onsen." }] },
      { japanese: "旅館", romaji: "ryokan", english: "Japanese inn", examples: [{ jp: "旅館に 泊まる。", en: "Stay at ryokan.", romaji: "Ryokan ni tomaru." }, { jp: "古い 旅館。", en: "Old ryokan.", romaji: "Furui ryokan." }] },
      { japanese: "写真", romaji: "shashin", english: "Photo", examples: [{ jp: "写真を 撮る。", en: "Take photo.", romaji: "Shashin wo toru." }, { jp: "記念 写真。", en: "Commemorative photo.", romaji: "Kinen shashin." }] },
      { japanese: "出発", romaji: "shuppatsu", english: "Departure", examples: [{ jp: "出発 時間。", en: "Departure time.", romaji: "Shuppatsu jikan." }, { jp: "駅を 出発する。", en: "Depart station.", romaji: "Eki wo shuppatsu suru." }] },
      { japanese: "到着", romaji: "touchaku", english: "Arrival", examples: [{ jp: "到着 時間。", en: "Arrival time.", romaji: "Touchaku jikan." }, { jp: "空港に 到着する。", en: "Arrive at airport.", romaji: "Kuukou ni touchaku suru." }] },
      { japanese: "乗り換え", romaji: "norikae", english: "Transfer", examples: [{ jp: "電車を 乗り換える。", en: "Transfer trains.", romaji: "Densha wo norikaeru." }, { jp: "乗り換え 案内。", en: "Transfer guide.", romaji: "Norikae annai." }] },
      { japanese: "ガイド", romaji: "gaido", english: "Guide", examples: [{ jp: "バス ガイド。", en: "Bus guide.", romaji: "Basu gaido." }, { jp: "ガイド ブック。", en: "Guide book.", romaji: "Gaido bukku." }] },
      { japanese: "美術館", romaji: "bijutsukan", english: "Art museum", examples: [{ jp: "美術館へ 行く。", en: "Go to art museum.", romaji: "Bijutsukan e iku." }, { jp: "美術館の チケット。", en: "Museum ticket.", romaji: "Bijutsukan no chiketto." }] },
      { japanese: "博物館", romaji: "hakubutsukan", english: "Museum", examples: [{ jp: "歴史 博物館。", en: "History museum.", romaji: "Rekishi hakubutsukan." }, { jp: "博物館を 見る。", en: "See museum.", romaji: "Hakubutsukan wo miru." }] },
      { japanese: "お寺", romaji: "otera", english: "Temple", examples: [{ jp: "京都の お寺。", en: "Kyoto temple.", romaji: "Kyouto no otera." }, { jp: "静かな お寺。", en: "Quiet temple.", romaji: "Shizuka na otera." }] },
      { japanese: "神社", romaji: "jinja", english: "Shrine", examples: [{ jp: "神社で 祈る。", en: "Pray at shrine.", romaji: "Jinja de inoru." }, { jp: "神社の お祭り。", en: "Shrine festival.", romaji: "Jinja no omatsuri." }] },
      { japanese: "祭り", romaji: "matsuri", english: "Festival", examples: [{ jp: "夏 祭り。", en: "Summer festival.", romaji: "Natsu matsuri." }, { jp: "祭りに行く。", en: "Go to festival.", romaji: "Matsuri ni iku." }] },
      { japanese: "新幹線", romaji: "shinkansen", english: "Bullet train", examples: [{ jp: "新幹線に 乗る。", en: "Ride Shinkansen.", romaji: "Shinkansen ni noru." }, { jp: "速い 新幹線。", en: "Fast bullet train.", romaji: "Hayai shinkansen." }] },
      { japanese: "特急", romaji: "tokkyuu", english: "Express train", examples: [{ jp: "特急 電車。", en: "Express train.", romaji: "Tokkyuu densha." }, { jp: "特急券。", en: "Express ticket.", romaji: "Tokkyuuken." }] },
      { japanese: "急行", romaji: "kyuukou", english: "Rapid train", examples: [{ jp: "急行に 乗る。", en: "Ride rapid.", romaji: "Kyuukou ni noru." }, { jp: "次は 急行。", en: "Next is rapid.", romaji: "Tsugi wa kyuukou." }] },
      { japanese: "各駅停車", romaji: "kakuekiteisha", english: "Local train", examples: [{ jp: "各駅停車で 行く。", en: "Go by local.", romaji: "Kakuekiteisha de iku." }, { jp: "遅い 各駅停車。", en: "Slow local train.", romaji: "Osoi kakuekiteisha." }] },
      { japanese: "満室", romaji: "manshitsu", english: "Full room/No vacancy", examples: [{ jp: "ホテルは 満室です。", en: "Hotel is full.", romaji: "Hoteru wa manshitsu desu." }, { jp: "満室で 泊まれない。", en: "Can't stay, full.", romaji: "Manshitsu de tomarenai." }] },
      { japanese: "空室", romaji: "kuushitsu", english: "Vacant room", examples: [{ jp: "空室 ありますか。", en: "Any vacant rooms?", romaji: "Kuushitsu arimasu ka." }, { jp: "空室 案内。", en: "Vacancy info.", romaji: "Kuushitsu annai." }] },
      { japanese: "景色", romaji: "keshiki", english: "Scenery", examples: [{ jp: "きれいな 景色。", en: "Beautiful scenery.", romaji: "Kirei na keshiki." }, { jp: "山の 景色。", en: "Mountain scenery.", romaji: "Yama no keshiki." }] },
      { japanese: "体験", romaji: "taiken", english: "Experience", examples: [{ jp: "文化 体験。", en: "Cultural experience.", romaji: "Bunka taiken." }, { jp: "着物 験。", en: "Kimono experience.", romaji: "Kimono taiken." }] }
    ]
  },
  {
    id: 27,
    level: "N4",
    title: "Culture & Tradition",
    description: "Japanese cultural terms and traditions",
    words: [
      { japanese: "文化", romaji: "bunka", english: "Culture", examples: [{ jp: "日本の 文化。", en: "Japanese culture.", romaji: "Nihon no bunka." }, { jp: "異 文化。", en: "Different culture.", romaji: "I bunka." }] },
      { japanese: "伝統", romaji: "dentou", english: "Tradition", examples: [{ jp: "古い 伝統。", en: "Old tradition.", romaji: "Furui dentou." }, { jp: "伝統的。", en: "Traditional.", romaji: "Dentouteki." }] },
      { japanese: "着物", romaji: "kimono", english: "Kimono", examples: [{ jp: "着物を 着る。", en: "Wear kimono.", romaji: "Kimono wo kiru." }, { jp: "美しい 着物。", en: "Beautiful kimono.", romaji: "Utsukushii kimono." }] },
      { japanese: "浴衣", romaji: "yukata", english: "Yukata", examples: [{ jp: "夏は 浴衣。", en: "Yukata in summer.", romaji: "Natsu wa yukata." }, { jp: "温泉 浴衣。", en: "Hot spring yukata.", romaji: "Onsen yukata." }] },
      { japanese: "お茶", romaji: "ocha", english: "Tea ceremony/Tea", examples: [{ jp: "お茶を 点てる。", en: "Make tea (ceremony).", romaji: "Ocha wo tateru." }, { jp: "茶道。", en: "Tea ceremony.", romaji: "Sadou." }] },
      { japanese: "生け花", romaji: "ikebana", english: "Flower arrangement", examples: [{ jp: "生け花を 習う。", en: "Learn ikebana.", romaji: "Ikebana wo narau." }, { jp: "きれいな 生け花。", en: "Beautiful flower arrangement.", romaji: "Kirei na ikebana." }] },
      { japanese: "書道", romaji: "shodou", english: "Calligraphy", examples: [{ jp: "書道の 練習。", en: "Calligraphy practice.", romaji: "Shodou no renshuu." }, { jp: "筆で 書く。", en: "Write with brush.", romaji: "Fude de kaku." }] },
      { japanese: "歌舞伎", romaji: "kabuki", english: "Kabuki", examples: [{ jp: "歌舞伎を 見る。", en: "Watch Kabuki.", romaji: "Kabuki wo miru." }, { jp: "歌舞伎役者。", en: "Kabuki actor.", romaji: "Kabukiyakusha." }] },
      { japanese: "相撲", romaji: "sumou", english: "Sumo", examples: [{ jp: "相撲を 見る。", en: "Watch Sumo.", romaji: "Sumou wo miru." }, { jp: "お相撲さん。", en: "Sumo wrestler.", romaji: "Osumousan." }] },
      { japanese: "柔道", romaji: "juudou", english: "Judo", examples: [{ jp: "柔道を する。", en: "Do Judo.", romaji: "Juudou wo suru." }, { jp: "柔道の 試合。", en: "Judo match.", romaji: "Juudou no shiai." }] },
      { japanese: "剣道", romaji: "kendou", english: "Kendo", examples: [{ jp: "剣道の 練習。", en: "Kendo practice.", romaji: "Kendou no renshuu." }, { jp: "竹刀。", en: "Bamboo sword.", romaji: "Shinai." }] },
      { japanese: "忍者", romaji: "ninja", english: "Ninja", examples: [{ jp: "忍者 村。", en: "Ninja village.", romaji: "Ninja mura." }, { jp: "忍者が 好き。", en: "Like ninjas.", romaji: "Ninja ga suki." }] },
      { japanese: "侍", romaji: "samurai", english: "Samurai", examples: [{ jp: "侍の 刀。", en: "Samurai sword.", romaji: "Samurai no katana." }, { jp: "ラスト サムライ。", en: "Last Samurai.", romaji: "Rasuto samurai." }] },
      { japanese: "お正月", romaji: "oshougatsu", english: "New Year", examples: [{ jp: "お正月 休み。", en: "New Year holiday.", romaji: "Oshougatsu yasumi." }, { jp: "お正月 料理。", en: "New Year food.", romaji: "Oshougatsu ryouri." }] },
      { japanese: "盆踊り", romaji: "bonodori", english: "Bon dance", examples: [{ jp: "盆踊りを 踊る。", en: "Dance Bon dance.", romaji: "Bonodori wo odoru." }, { jp: "夏 祭り。", en: "Summer festival.", romaji: "Natsu matsuri." }] },
      { japanese: "花火", romaji: "hanabi", english: "Fireworks", examples: [{ jp: "花火 大会。", en: "Fireworks display.", romaji: "Hanabi taikai." }, { jp: "きれいな 花火。", en: "Beautiful fireworks.", romaji: "Kirei na hanabi." }] },
      { japanese: "桜", romaji: "sakura", english: "Cherry blossom", examples: [{ jp: "桜が 咲く。", en: "Sakura blooms.", romaji: "Sakura ga saku." }, { jp: "桜吹雪。", en: "Cherry blossom blizzard.", romaji: "Sakurafubuki." }] },
      { japanese: "布団", romaji: "futon", english: "Futon", examples: [{ jp: "布団で 寝る。", en: "Sleep on futon.", romaji: "Futon de neru." }, { jp: "布団を 敷く。", en: "Lay out futon.", romaji: "Futon wo shiku." }] },
      { japanese: "畳", romaji: "tatami", english: "Tatami mat", examples: [{ jp: "畳の 部屋。", en: "Tatami room.", romaji: "Tatami no heya." }, { jp: "新しい 畳。", en: "New tatami.", romaji: "Atarashii tatami." }] },
      { japanese: "障子", romaji: "shouji", english: "Shoji screen", examples: [{ jp: "障子を 開ける。", en: "Open shoji.", romaji: "Shouji wo akeru." }, { jp: "障子の 穴。", en: "Hole in shoji.", romaji: "Shouji no ana." }] },
      { japanese: "座布団", romaji: "zabuton", english: "Cushion", examples: [{ jp: "座布団に 座る。", en: "Sit on cushion.", romaji: "Zabuton ni suwaru." }, { jp: "座布団を どうぞ。", en: "Please have a cushion.", romaji: "Zabuton wo douzo." }] },
      { japanese: "箸", romaji: "hashi", english: "Chopsticks", examples: [{ jp: "箸を 使う。", en: "Use chopsticks.", romaji: "Hashi wo tsukau." }, { jp: "箸置き。", en: "Chopstick rest.", romaji: "Hashioki." }] },
      { japanese: "おにぎり", romaji: "onigiri", english: "Rice ball", examples: [{ jp: "おにぎりを 食べる。", en: "Eat onigiri.", romaji: "Onigiri wo taberu." }, { jp: "梅 おにぎり。", en: "Plum onigiri.", romaji: "Ume onigiri." }] },
      { japanese: "弁当", romaji: "bentou", english: "Bento/Box lunch", examples: [{ jp: "お弁当を 作る。", en: "Make bento.", romaji: "Obentou wo tsukuru." }, { jp: "駅弁。", en: "Station bento.", romaji: "Ekiben." }] },
      { japanese: "味噌汁", romaji: "misoshiru", english: "Miso soup", examples: [{ jp: "味噌汁を 飲む。", en: "Drink miso soup.", romaji: "Misoshiru wo nomu." }, { jp: "朝は 味噌汁。", en: "Miso soup in morning.", romaji: "Asa wa misoshiru." }] },
      { japanese: "納豆", romaji: "nattou", english: "Natto", examples: [{ jp: "納豆は 嫌い。", en: "Hate natto.", romaji: "Nattou wa kirai." }, { jp: "納豆 ご飯。", en: "Natto rice.", romaji: "Nattou gohan." }] },
      { japanese: "敬語", romaji: "keigo", english: "Honorifics", examples: [{ jp: "敬語を 使う。", en: "Use keigo.", romaji: "Keigo wo tsukau." }, { jp: "正しい 敬語。", en: "Correct keigo.", romaji: "Tadashii keigo." }] },
      { japanese: "お辞儀", romaji: "ojigi", english: "Bow", examples: [{ jp: "丁寧な お辞儀。", en: "Polite bow.", romaji: "Teinei na ojigi." }, { jp: "お辞儀を する。", en: "To bow.", romaji: "Ojigi wo suru." }] },
      { japanese: "玄関", romaji: "genkan", english: "Entrance", examples: [{ jp: "玄関で 靴を脱ぐ。", en: "Take shoes off at genkan.", romaji: "Genkan de kutsu wo nugu." }, { jp: "広い 玄関。", en: "Spacious entrance.", romaji: "Hiroi genkan." }] },
      { japanese: "神様", romaji: "kamisama", english: "God", examples: [{ jp: "神様に 祈る。", en: "Pray to god.", romaji: "Kamisama ni inoru." }, { jp: "神様。", en: "God.", romaji: "Kamisama." }] }
    ]
  },
  {
    id: 28,
    level: "N4",
    title: "Adverbs & Connectors",
    description: "Words that connect ideas and modify verbs",
    words: [
      { japanese: "はい", romaji: "hai", english: "Yes", examples: [{ jp: "はい、そうです。", en: "Yes, that's right.", romaji: "Hai, sou desu." }, { jp: "はい、元気です。", en: "Yes, I am fine.", romaji: "Hai, genki desu." }] },
      { japanese: "いいえ", romaji: "iie", english: "No", examples: [{ jp: "いいえ、違います。", en: "No, that's wrong.", romaji: "Iie, chigaimasu." }, { jp: "いいえ、だめです。", en: "No, it's not allowed.", romaji: "Iie, dame desu." }] },
      { japanese: "そして", romaji: "soshite", english: "And then", examples: [{ jp: "食べて、そして 寝た。", en: "Ate, and then slept.", romaji: "Tabete, soshite neta." }, { jp: "きれいで、そして 安い。", en: "Beautiful, and cheap.", romaji: "Kirei de, soshite yasui." }] },
      { japanese: "でも", romaji: "demo", english: "But", examples: [{ jp: "でも、高いです。", en: "But it's expensive.", romaji: "Demo, takai desu." }, { jp: "好き、でも 嫌い。", en: "Like, but dislike.", romaji: "Suki, demo kirai." }] },
      { japanese: "しかし", romaji: "shikashi", english: "However", examples: [{ jp: "しかし、問題がある。", en: "However, there is a problem.", romaji: "Shikashi, mondai ga aru." }, { jp: "天気はいい、しかし寒い。", en: "Weather is good, however cold.", romaji: "Tenki wa ii, shikashi samui." }] },
      { japanese: "だから", romaji: "dakara", english: "Therefore/So", examples: [{ jp: "だから言ったでしょ。", en: "That's why I told you.", romaji: "Dakara itta desho." }, { jp: "雨だ、だから行かない。", en: "It's rain, so I won't go.", romaji: "Ame da, dakara ikanai." }] },
      { japanese: "また", romaji: "mata", english: "Again/Also", examples: [{ jp: "また明日。", en: "See you tomorrow (Again tomorrow).", romaji: "Mata ashita." }, { jp: "また来てください。", en: "Please come again.", romaji: "Mata kite kudasai." }] },
      { japanese: "もっと", romaji: "motto", english: "More", examples: [{ jp: "もっと 食べる。", en: "Eat more.", romaji: "Motto taberu." }, { jp: "もっと ゆっくり。", en: "More slowly.", romaji: "Motto yukkuri." }] },
      { japanese: "いつも", romaji: "itsumo", english: "Always", examples: [{ jp: "いつも ありがとう。", en: "Always thank you.", romaji: "Itsumo arigatou." }, { jp: "いつも 元気。", en: "Always energetic.", romaji: "Itsumo genki." }] },
      { japanese: "たぶん", romaji: "tabun", english: "Probably", examples: [{ jp: "たぶん 大丈夫。", en: "Probably okay.", romaji: "Tabun daijoubu." }, { jp: "たぶん 明日。", en: "Probably tomorrow.", romaji: "Tabun ashita." }] },
      { japanese: "とても", romaji: "totemo", english: "Very", examples: [{ jp: "とても 美味しい。", en: "Very delicious.", romaji: "Totemo oishii." }, { jp: "とても 寒い。", en: "Very cold.", romaji: "Totemo samui." }] },
      { japanese: "よく", romaji: "yoku", english: "Often/Well", examples: [{ jp: "よく 分かる。", en: "Understand well.", romaji: "Yoku wakaru." }, { jp: "よく 来ます。", en: "Come often.", romaji: "Yoku kimasu." }] },
      { japanese: "だいたい", romaji: "daitai", english: "Mostly/Roughly", examples: [{ jp: "だいたい 分かった。", en: "Mostly understood.", romaji: "Daitai wakatta." }, { jp: "だいたい 同じ。", en: "Roughly the same.", romaji: "Daitai onaji." }] },
      { japanese: "少し", romaji: "sukoshi", english: "A little", examples: [{ jp: "少し 待って。", en: "Wait a little.", romaji: "Sukoshi matte." }, { jp: "少し 食べる。", en: "Eat a little.", romaji: "Sukoshi taberu." }] },
      { japanese: "ちょっと", romaji: "chotto", english: "A little (casual)", examples: [{ jp: "ちょっと 待って。", en: "Wait a sec.", romaji: "Chotto matte." }, { jp: "ちょっと 難しい。", en: "A bit difficult.", romaji: "Chotto muzukashii." }] },
      { japanese: "もう", romaji: "mou", english: "Already/Anymore", examples: [{ jp: "もう 帰る。", en: "Go home already.", romaji: "Mou kaeru." }, { jp: "もう ない。", en: "Not anymore.", romaji: "Mou nai." }] },
      { japanese: "まだ", romaji: "mada", english: "Not yet/Still", examples: [{ jp: "まだ です。", en: "Not yet.", romaji: "Mada desu." }, { jp: "まだ 食べる。", en: "Still eating.", romaji: "Mada taberu." }] },
      { japanese: "すぐ", romaji: "sugu", english: "Immediately", examples: [{ jp: "すぐ 行く。", en: "Go immediately.", romaji: "Sugu iku." }, { jp: "すぐ 終わる。", en: "Finish soon.", romaji: "Sugu owaru." }] },
      { japanese: "ゆっくり", romaji: "yukkuri", english: "Slowly", examples: [{ jp: "ゆっくり 話す。", en: "Speak slowly.", romaji: "Yukkuri hanasu." }, { jp: "ゆっくり 休んで。", en: "Rest well.", romaji: "Yukkuri yasunde." }] },
      { japanese: "実は", romaji: "jitsuwa", english: "Actually", examples: [{ jp: "実は 好きです。", en: "Actually I like it.", romaji: "Jitsuwa suki desu." }, { jp: "実は そうなんです。", en: "Actually that's right.", romaji: "Jitsuwa sou nan desu." }] },
      { japanese: "本当に", romaji: "hontouni", english: "Really", examples: [{ jp: "本当に ありがとう。", en: "Really thank you.", romaji: "Hontouni arigatou." }, { jp: "本当に 寒い。", en: "Really cold.", romaji: "Hontouni samui." }] },
      { japanese: "一番", romaji: "ichiban", english: "Number one/Most", examples: [{ jp: "一番 好き。", en: "Like most.", romaji: "Ichiban suki." }, { jp: "一番 早い。", en: "Fastest.", romaji: "Ichiban hayai." }] },
      { japanese: "初めて", romaji: "hajimete", english: "For the first time", examples: [{ jp: "初めて 見た。", en: "Saw for first time.", romaji: "Hajimete mita." }, { jp: "初めてです。", en: "It's my first time.", romaji: "Hajimete desu." }] },
      { japanese: "一緒に", romaji: "isshoni", english: "Together", examples: [{ jp: "一緒に 行く。", en: "Go together.", romaji: "Isshoni iku." }, { jp: "一緒に 食べる。", en: "Eat together.", romaji: "Isshoni taberu." }] },
      { japanese: "一人で", romaji: "hitoride", english: "Alone", examples: [{ jp: "一人で 行く。", en: "Go alone.", romaji: "Hitoride iku." }, { jp: "一人で できる。", en: "Can do alone.", romaji: "Hitoride dekiru." }] },
      { japanese: "他の", romaji: "hoka no", english: "Other", examples: [{ jp: "他の 人。", en: "Other person.", romaji: "Hoka no hito." }, { jp: "他の 物。", en: "Other thing.", romaji: "Hoka no mono." }] },
      { japanese: "同じ", romaji: "onaji", english: "Same", examples: [{ jp: "同じ 色。", en: "Same color.", romaji: "Onaji iro." }, { jp: "私も 同じ。", en: "Same for me.", romaji: "Watashi mo onaji." }] },
      { japanese: "全然", romaji: "zenzen", english: "Not at all (with neg)", examples: [{ jp: "全然 分からない。", en: "Don't understand at all.", romaji: "Zenzen wakaranai." }, { jp: "全然 大丈夫。", en: "Totally fine (slang).", romaji: "Zenzen daijoubu." }] },
      { japanese: "だんだん", romaji: "dandan", english: "Gradually", examples: [{ jp: "だんだん 寒くなる。", en: "Gradually getting cold.", romaji: "Dandan samuku naru." }, { jp: "だんだん 分かる。", en: "Gradually understand.", romaji: "Dandan wakaru." }] },
      { japanese: "もし", romaji: "moshi", english: "If", examples: [{ jp: "もし よかったら。", en: "If it's okay.", romaji: "Moshi yokattara." }, { jp: "もし明日雨なら。", en: "If it rains tomorrow.", romaji: "Moshi ashita ame nara." }] }
    ]
  },
  {
    id: 29,
    level: "N4",
    title: "Emergency & Safety",
    description: "Important words for emergencies and help",
    words: [
      { japanese: "助けて", romaji: "tasukete", english: "Help!", examples: [{ jp: "誰か 助けて。", en: "Someone help!", romaji: "Dareka tasukete." }, { jp: "助けて ください。", en: "Please help.", romaji: "Tasukete kudasai." }] },
      { japanese: "危ない", romaji: "abunai", english: "Dangerous", examples: [{ jp: "危ない ですよ。", en: "It's dangerous.", romaji: "Abunai desu yo." }, { jp: "ここは 危ない。", en: "Dangerous here.", romaji: "Koko wa abunai." }] },
      { japanese: "止まれ", romaji: "tomare", english: "Stop (Command)", examples: [{ jp: "ここで 止まれ。", en: "Stop here.", romaji: "Koko de tomare." }, { jp: "止まれの 標識。", en: "Stop sign.", romaji: "Tomare no hyoushiki." }] },
      { japanese: "火事", romaji: "kaji", english: "Fire", examples: [{ jp: "火事だ！", en: "Fire!", romaji: "Kaji da!" }, { jp: "火事の 電話。", en: "Fire call.", romaji: "Kaji no denwa." }] },
      { japanese: "救急車", romaji: "kyuukyuusha", english: "Ambulance", examples: [{ jp: "救急車を 呼ぶ。", en: "Call ambulance.", romaji: "Kyuukyuusha wo yobu." }, { jp: "救急車が 来た。", en: "Ambulance came.", romaji: "Kyuukyuusha ga kita." }] },
      { japanese: "警察", romaji: "keisatsu", english: "Police", examples: [{ jp: "警察へ 行く。", en: "Go to police.", romaji: "Keisatsu e iku." }, { jp: "警察です。", en: "This is police.", romaji: "Keisatsu desu." }] },
      { japanese: "泥棒", romaji: "dorobou", english: "Thief", examples: [{ jp: "泥棒がいる。", en: "There is a thief.", romaji: "Dorobou ga iru." }, { jp: "泥棒猫。", en: "Thief cat.", romaji: "Dorobou neko." }] },
      { japanese: "事故", romaji: "jiko", english: "Accident", examples: [{ jp: "事故を 見た。", en: "Saw an accident.", romaji: "Jiko wo mita." }, { jp: "交通事故。", en: "Traffic accident.", romaji: "Koutsuu jiko." }] },
      { japanese: "地震", romaji: "jishin", english: "Earthquake", examples: [{ jp: "地震が怖い。", en: "Scared of earthquake.", romaji: "Jishin ga kowai." }, { jp: "大きい 地震。", en: "Big earthquake.", romaji: "Ookii jishin." }] },
      { japanese: "逃げる", romaji: "nigeru", english: "To run away/escape", examples: [{ jp: "早く 逃げて。", en: "Run away fast.", romaji: "Hayaku nigete." }, { jp: "逃げるが勝ち。", en: "Running is winning.", romaji: "Nigeru ga kachi." }] },
      { japanese: "迷子", romaji: "maigo", english: "Lost child", examples: [{ jp: "迷子に なる。", en: "Get lost.", romaji: "Maigo ni naru." }, { jp: "迷子の センター。", en: "Lost child center.", romaji: "Maigo no sentaa." }] },
      { japanese: "痛い", romaji: "itai", english: "Pain/Ouch", examples: [{ jp: "足が 痛い。", en: "Leg hurts.", romaji: "Ashi ga itai." }, { jp: "痛いです。", en: "It hurts.", romaji: "Itai desu." }] },
      { japanese: "薬", romaji: "kusuri", english: "Medicine", examples: [{ jp: "薬を ください。", en: "Medicine please.", romaji: "Kusuri wo kudasai." }, { jp: "頭痛 薬。", en: "Headache med.", romaji: "Zutsuu yaku." }] },
      { japanese: "病院", romaji: "byouin", english: "Hospital", examples: [{ jp: "病院は どこ？", en: "Where is hospital?", romaji: "Byouin wa doko?" }, { jp: "病院へ 行きたい。", en: "Want to go to hospital.", romaji: "Byouin e ikitai." }] },
      { japanese: "禁止", romaji: "kinshi", english: "Prohibited", examples: [{ jp: "立ち入り 禁止。", en: "No entry.", romaji: "Tachiiri kinshi." }, { jp: "駐車 禁止。", en: "No parking.", romaji: "Chuusha kinshi." }] },
      { japanese: "注意", romaji: "chuui", english: "Caution", examples: [{ jp: "足元 注意。", en: "Watch your step.", romaji: "Ashimoto chuui." }, { jp: "注意 して。", en: "Be careful.", romaji: "Chuui shite." }] },
      { japanese: "非常口", romaji: "hijouguchi", english: "Emergency Exit", examples: [{ jp: "非常口は あそこ。", en: "Exit is there.", romaji: "Hijouguchi wa asoko." }, { jp: "非常口 マーク。", en: "Exit mark.", romaji: "Hijouguchi maaku." }] },
      { japanese: "故障", romaji: "koshou", english: "Out of order/Breakdown", examples: [{ jp: "エレベーター 故障。", en: "Elevator broken.", romaji: "Erebeetaa koshou." }, { jp: "故障中です。", en: "Currently out of order.", romaji: "Koshouchuu desu." }] },
      { japanese: "落とす", romaji: "otosu", english: "To drop", examples: [{ jp: "財布を 落とした。", en: "Dropped wallet.", romaji: "Saifu wo otoshita." }, { jp: "スピードを 落とす。", en: "Drop speed.", romaji: "Supiido wo otosu." }] },
      { japanese: "盗まれる", romaji: "nusumareru", english: "To be stolen", examples: [{ jp: "鞄を 盗まれた。", en: "Bag was stolen.", romaji: "Kaban wo nusumareta." }, { jp: "自転車を 盗まれる。", en: "Bike stolen.", romaji: "Jitensha wo nusumareru." }] },
      { japanese: "触る", romaji: "sawaru", english: "To touch", examples: [{ jp: "触らないで。", en: "Don't touch.", romaji: "Sawaranaide." }, { jp: "触るな危険。", en: "Danger do not touch.", romaji: "Sawaruna kiken." }] },
      { japanese: "押す", romaji: "osu", english: "To push", examples: [{ jp: "非常ボタンを 押す。", en: "Push emergency button.", romaji: "Hijou botan wo osu." }, { jp: "強く 押す。", en: "Push hard.", romaji: "Tsuyoku osu." }] },
      { japanese: "引く", romaji: "hiku", english: "To pull", examples: [{ jp: "引く。", en: "Pull (on door).", romaji: "Hiku." }, { jp: "手を 引く。", en: "Pull hand.", romaji: "Te wo hiku." }] },
      { japanese: "警察官", romaji: "keisatsukan", english: "Police officer", examples: [{ jp: "警察官に 聞く。", en: "Ask officer.", romaji: "Keisatsukan ni kiku." }, { jp: "親切な 警察官。", en: "Kind officer.", romaji: "Shinsetsu na keisatsukan." }] },
      { japanese: "交番", romaji: "kouban", english: "Police box", examples: [{ jp: "交番は どこ？", en: "Where is police box?", romaji: "Kouban wa doko?" }, { jp: "駅前の 交番。", en: "Station police box.", romaji: "Ekimae no kouban." }] },
      { japanese: "携帯", romaji: "keitai", english: "Mobile phone", examples: [{ jp: "携帯を 貸してください。", en: "Lend me phone please.", romaji: "Keitai wo kashite kudasai." }, { jp: "携帯が 繋がらない。", en: "Phone not connecting.", romaji: "Keitai ga tsunagaranai." }] },
      { japanese: "住所", romaji: "juusho", english: "Address", examples: [{ jp: "住所を 書く。", en: "Write address.", romaji: "Juusho wo kaku." }, { jp: "ここの 住所。", en: "Address here.", romaji: "Koko no juusho." }] },
      { japanese: "名前", romaji: "namae", english: "Name", examples: [{ jp: "名前を 言う。", en: "Say name.", romaji: "Namae wo iu." }, { jp: "お名前は？", en: "Your name?", romaji: "Onamae wa?" }] },
      { japanese: "大使館", romaji: "taishikan", english: "Embassy", examples: [{ jp: "日本 大使館。", en: "Japan Embassy.", romaji: "Nihon taishikan." }, { jp: "大使館に 連絡する。", en: "Contact embassy.", romaji: "Taishikan ni renraku suru." }] },
      { japanese: "大丈夫", romaji: "daijoubu", english: "Okay", examples: [{ jp: "大丈夫ですか。", en: "Are you okay?", romaji: "Daijoubu desu ka." }, { jp: "私は 大丈夫。", en: "I am fine.", romaji: "Watashi wa daijoubu." }] }
    ]
  },
  {
    id: 30,
    level: "N4",
    title: "Common Phrases",
    description: "Useful daily expressions and set phrases",
    words: [
      { japanese: "ありがとう", romaji: "arigatou", english: "Thank you", examples: [{ jp: "ありがとう ございます。", en: "Thank you very much.", romaji: "Arigatou gozaimasu." }, { jp: "いつも ありがとう。", en: "Always thank you.", romaji: "Itsumo arigatou." }] },
      { japanese: "すみません", romaji: "sumimasen", english: "Excuse me/Sorry", examples: [{ jp: "すみません、通してください。", en: "Excuse me, let me pass.", romaji: "Sumimasen, tooshite kudasai." }, { jp: "遅れて すみません。", en: "Sorry for being late.", romaji: "Okurete sumimasen." }] },
      { japanese: "ごめんなさい", romaji: "gomennasai", english: "I'm sorry", examples: [{ jp: "本当に ごめんなさい。", en: "I'm really sorry.", romaji: "Hontouni gomennasai." }, { jp: "ごめんなさいね。", en: "Sorry (casual).", romaji: "Gomennasai ne." }] },
      { japanese: "お願いします", romaji: "onegaishimasu", english: "Please", examples: [{ jp: "これを お願いします。", en: "This one please.", romaji: "Kore wo onegaishimasu." }, { jp: "よろしく お願いします。", en: "Nice to meet you/Please treat me well.", romaji: "Yoroshiku onegaishimasu." }] },
      { japanese: "はい", romaji: "hai", english: "Yes", examples: [{ jp: "はい、そうです。", en: "Yes, that's right.", romaji: "Hai, sou desu." }, { jp: "はい、分かりました。", en: "Yes, I understand.", romaji: "Hai, wakarimashita." }] },
      { japanese: "いいえ", romaji: "iie", english: "No", examples: [{ jp: "いいえ、違います。", en: "No, that's wrong.", romaji: "Iie, chigaimasu." }, { jp: "いいえ、結構です。", en: "No, thank you.", romaji: "Iie, kekkou desu." }] },
      { japanese: "おはよう", romaji: "ohayou", english: "Good morning", examples: [{ jp: "おはよう ございます。", en: "Good morning (polite).", romaji: "Ohayou gozaimasu." }, { jp: "みんな おはよう。", en: "Morning everyone.", romaji: "Minna ohayou." }] },
      { japanese: "こんにちは", romaji: "konnichiwa", english: "Hello", examples: [{ jp: "こんにちは、元気？", en: "Hello, how are you?", romaji: "Konnichiwa, genki?" }, { jp: "先生 こんにちは。", en: "Hello teacher.", romaji: "Sensei konnichiwa." }] },
      { japanese: "こんばんは", romaji: "konbanwa", english: "Good evening", examples: [{ jp: "こんばんは皆さん。", en: "Good evening everyone.", romaji: "Konbanwa minasan." }, { jp: "今晩は 寒い。", en: "Evening is cold.", romaji: "Konban wa samui." }] },
      { japanese: "おやすみ", romaji: "oyasumi", english: "Good night", examples: [{ jp: "おやすみ なさい。", en: "Good night (polite).", romaji: "Oyasuminasai." }, { jp: "そろそろ おやすみ。", en: "Good night soon.", romaji: "Sorosoro oyasumi." }] },
      { japanese: "さようなら", romaji: "sayounara", english: "Goodbye", examples: [{ jp: "さようなら、また。", en: "Goodbye, see you.", romaji: "Sayounara, mata." }, { jp: "先生、さようなら。", en: "Goodbye teacher.", romaji: "Sensei, sayounara." }] },
      { japanese: "行ってきます", romaji: "ittekimasu", english: "I'm leaving", examples: [{ jp: "学校に 行ってきます。", en: "Leaving for school.", romaji: "Gakkou ni ittekimasu." }, { jp: "行ってきます。", en: "I'm off.", romaji: "Ittekimasu." }] },
      { japanese: "行ってらっしゃい", romaji: "itterasshai", english: "Have a good trip", examples: [{ jp: "気をつけて 行ってらっしゃい。", en: "Be careful, see you.", romaji: "Ki wo tsukete itterasshai." }, { jp: "行ってらっしゃい。", en: "See you later (to person leaving).", romaji: "Itterasshai." }] },
      { japanese: "ただいま", romaji: "tadaima", english: "I'm home", examples: [{ jp: "ただいま戻りました。", en: "I'm back.", romaji: "Tadaima modorimashita." }, { jp: "ただいま。", en: "I'm home.", romaji: "Tadaima." }] },
      { japanese: "おかえり", romaji: "okaeri", english: "Welcome back", examples: [{ jp: "おかえり なさい。", en: "Welcome back (polite).", romaji: "Okaeri nasai." }, { jp: "おかえり。", en: "Welcome back.", romaji: "Okaeri." }] },
      { japanese: "いただきます", romaji: "itadakimasu", english: "Bon appétit", examples: [{ jp: "では、いただきます。", en: "Well then, let's eat.", romaji: "Dewa, itadakimasu." }, { jp: "お弁当、いただきます。", en: "I'll have the bento.", romaji: "Obentou, itadakimasu." }] },
      { japanese: "ごちそうさま", romaji: "gochisousama", english: "Thank you for the meal", examples: [{ jp: "ごちそうさま でした。", en: "Thanks for the meal (polite).", romaji: "Gochisousama deshita." }, { jp: "ああ、ごちそうさま。", en: "Ah, that was good.", romaji: "Aa, gochisousama." }] },
      { japanese: "初めまして", romaji: "hajimemashite", english: "Nice to meet you", examples: [{ jp: "初めまして、田中です。", en: "Nice to meet you, I'm Tanaka.", romaji: "Hajimemashite, Tanaka desu." }, { jp: "どうぞ よろしく。", en: "Pleased to meet you.", romaji: "Douzo yoroshiku." }] },
      { japanese: "お大事に", romaji: "odaijini", english: "Get well soon", examples: [{ jp: "どうぞ お大事に。", en: "Please take care.", romaji: "Douzo odaijini." }, { jp: "お大事に してください。", en: "Please get well.", romaji: "Odaijini shite kudasai." }] },
      { japanese: "久しぶり", romaji: "hisashiburi", english: "Long time no see", examples: [{ jp: "お久しぶり です。", en: "It's been a long time.", romaji: "Ohisashiburi desu." }, { jp: "久しぶり だね。", en: "Long time, huh.", romaji: "Hisashiburi da ne." }] },
      { japanese: "もしもし", romaji: "moshimoshi", english: "Hello (phone)", examples: [{ jp: "もしもし、田中です。", en: "Hello, this is Tanaka.", romaji: "Moshimoshi, Tanaka desu." }, { jp: "もしもし、聞こえますか。", en: "Hello, can you hear me?", romaji: "Moshimoshi, kikoemasu ka." }] },
      { japanese: "乾杯", romaji: "kanpai", english: "Cheers", examples: [{ jp: "ビールで 乾杯。", en: "Cheers with beer.", romaji: "Biiru de kanpai." }, { jp: "乾杯しましょう。", en: "Let's toast.", romaji: "Kanpai shimashou." }] },
      { japanese: "残念", romaji: "zannen", english: "Regrettable/Pity", examples: [{ jp: "それは 残念です。", en: "That is a pity.", romaji: "Sore wa zannen desu." }, { jp: "残念ながら。", en: "Unfortunately.", romaji: "Zannennagara." }] },
      { japanese: "おめでとう", romaji: "omedetou", english: "Congratulations", examples: [{ jp: "誕生日 おめでとう。", en: "Happy Birthday.", romaji: "Tanjoubi omedetou." }, { jp: "合格 おめでとう。", en: "Congrats on passing.", romaji: "Goukaku omedetou." }] },
      { japanese: "すごい", romaji: "sugoi", english: "Amazing/Wow", examples: [{ jp: "それは すごい。", en: "That is amazing.", romaji: "Sore wa sugoi." }, { jp: "すごい 人ですね。", en: "Amazing person.", romaji: "Sugoi hito desu ne." }] },
      { japanese: "なるほど", romaji: "naruhodo", english: "I see/Indeed", examples: [{ jp: "なるほど、分かりました。", en: "I see, I understood.", romaji: "Naruhodo, wakarimashita." }, { jp: "なるほどね。", en: "I see (casual).", romaji: "Naruhodo ne." }] },
      { japanese: "ちょっと", romaji: "chotto", english: "A little/Excuse me", examples: [{ jp: "ちょっと すみません。", en: "Excuse me a moment.", romaji: "Chotto sumimasen." }, { jp: "それは ちょっと...", en: "That's a bit... (refusal).", romaji: "Sore wa chotto..." }] },
      { japanese: "どういたしまして", romaji: "douitashimashite", english: "You're welcome", examples: [{ jp: "いいえ、どういたしまして。", en: "No, you're welcome.", romaji: "Iie, douitashimashite." }, { jp: "はい、どういたしまして。", en: "Sure, you're welcome.", romaji: "Hai, douitashimashite." }] },
      { japanese: "失礼します", romaji: "shitsureishimasu", english: "Excuse me (entering/leaving)", examples: [{ jp: "先に 失礼します。", en: "Excuse me, I'm leaving first.", romaji: "Saki ni shitsureishimasu." }, { jp: "失礼します。", en: "Excuse me (entering).", romaji: "Shitsureishimasu." }] },
      { japanese: "お疲れ様", romaji: "otsukaresama", english: "Good work/Thanks", examples: [{ jp: "お疲れ様 でした。", en: "Good work today.", romaji: "Otsukaresama deshita." }, { jp: "お疲れ！", en: "Good job (casual).", romaji: "Otsukare!" }] }
    ]
  }
];
