export const chunk10 = [
  {
    id: 46,
    level: "N4",
    title: "Daily Life: Manners & Rules",
    description: "Vocabulary for behaving in public and social rules",
    words: [
      { japanese: "マナー", romaji: "manaa", english: "Manners", examples: [{ jp: "マナーを 守る。", en: "Observe manners.", romaji: "Manaa wo mamoru." }, { jp: "食事の マナー。", en: "Table manners.", romaji: "Shokuji no manaa." }] },
      { japanese: "規則", romaji: "kisoku", english: "Rule/Regulation", examples: [{ jp: "規則を 守る。", en: "Follow rules.", romaji: "Kisoku wo mamoru." }, { jp: "校則。", en: "School rules.", romaji: "Kousoku." }] },
      { japanese: "法律", romaji: "houritsu", english: "Law", examples: [{ jp: "法律を 守る。", en: "Obey the law.", romaji: "Houritsu wo mamoru." }, { jp: "新しい 法律。", en: "New law.", romaji: "Atarashii houritsu." }] },
      { japanese: "禁止する", romaji: "kinshisuru", english: "To forbid/prohibit", examples: [{ jp: "タバコを 禁止する。", en: "Prohibit smoking.", romaji: "Tabako wo kinshisuru." }, { jp: "立入 禁止。", en: "Keep out.", romaji: "Tachiiri kinshi." }] },
      { japanese: "許可する", romaji: "kyokasuru", english: "To permit", examples: [{ jp: "外出を 許可する。", en: "Permit going out.", romaji: "Gaishutsu wo kyokasuru." }, { jp: "許可を 得る。", en: "Get permission.", romaji: "Kyoka wo eru." }] },
      { japanese: "違反する", romaji: "ihansuru", english: "To violate", examples: [{ jp: "スピード 違反。", en: "Speeding violation.", romaji: "Supiido ihan." }, { jp: "ルールに 違反する。", en: "Violate the rules.", romaji: "Ruuru ni ihansuru." }] },
      { japanese: "注意する", romaji: "chuuisuru", english: "To warn/be careful", examples: [{ jp: "先生が 注意する。", en: "Teacher warns.", romaji: "Sensei ga chuuisuru." }, { jp: "騒音に 注意。", en: "Beware of noise.", romaji: "Souon ni chuui." }] },
      { japanese: "迷惑", romaji: "meiwaku", english: "Nuisance/Trouble", examples: [{ jp: "迷惑を かける。", en: "Cause trouble.", romaji: "Meiwaku wo kakeru." }, { jp: "近所 迷惑。", en: "Neighborhood nuisance.", romaji: "Kinjo meiwaku." }] },
      { japanese: "遠慮する", romaji: "enryosuru", english: "To hold back/decline", examples: [{ jp: "遠慮しないで 食べて。", en: "Eat without holding back.", romaji: "Enryoshinaide tabete." }, { jp: "喫煙は 遠慮ください。", en: "Please refrain from smoking.", romaji: "Kitsuen wa enryo kudasai." }] },
      { japanese: "優先する", romaji: "yuusensuru", english: "To prioritize", examples: [{ jp: "仕事を 優先する。", en: "Prioritize work.", romaji: "Shigoto wo yuusensuru." }, { jp: "優先 席。", en: "Priority seat.", romaji: "Yuusenseki." }] },
      { japanese: "順番", romaji: "junban", english: "Order/Turn", examples: [{ jp: "順番を 待つ。", en: "Wait for one's turn.", romaji: "Junban wo matsu." }, { jp: "順番に 並ぶ。", en: "Line up in order.", romaji: "Junban ni narabu." }] },
      { japanese: "並ぶ", romaji: "narabu", english: "To line up", examples: [{ jp: "列に 並ぶ。", en: "Line up in a row.", romaji: "Retsu ni narabu." }, { jp: "店が 並んでいる。", en: "Shops are lined up.", romaji: "Mise ga narandeiru." }] },
      { japanese: "割り込む", romaji: "warikomu", english: "To cut in line", examples: [{ jp: "列に 割り込まないで。", en: "Don't cut in line.", romaji: "Retsu ni warikomanaide." }, { jp: "話に 割り込む。", en: "Interrupt a conversation.", romaji: "Hanashi ni warikomu." }] },
      { japanese: "公共の", romaji: "koukyou no", english: "Public", examples: [{ jp: "公共 施設。", en: "Public facility.", romaji: "Koukyou shisetsu." }, { jp: "公共 交通機関。", en: "Public transport.", romaji: "Koukyou koutsuu kikan." }] },
      { japanese: "専用の", romaji: "senyou no", english: "Exclusive/Private", examples: [{ jp: "女性 専用車。", en: "Women-only car.", romaji: "Josei senyousha." }, { jp: "自分 専用の机。", en: "One's private desk.", romaji: "Jibun senyou no tsukue." }] },
      { japanese: "自由な", romaji: "jiyuuna", english: "Free/Liberal", examples: [{ jp: "自由な 時間。", en: "Free time.", romaji: "Jiyuuna jikan." }, { jp: "自由 行動。", en: "Free movement/action.", romaji: "Jiyuu koudou." }] },
      { japanese: "不自由な", romaji: "fujiyuuna", english: "Inconvenient/Restricted", examples: [{ jp: "足が 不自由だ。", en: "Have difficulty walking.", romaji: "Ashi ga fujiyuu da." }, { jp: "不自由な 生活。", en: "Restricted life.", romaji: "Fujiyuuna seikatsu." }] },
      { japanese: "義務", romaji: "gimu", english: "Duty/Obligation", examples: [{ jp: "国民の 義務。", en: "Citizen's duty.", romaji: "Kokumin no gimu." }, { jp: "義務を 果たす。", en: "Fulfill an obligation.", romaji: "Gimu wo hatasu." }] },
      { japanese: "権利", romaji: "kenri", english: "Right/Privilege", examples: [{ jp: "選ぶ 権利が ある。", en: "Have the right to choose.", romaji: "Erabu kenri ga aru." }, { jp: "人権。", en: "Human rights.", romaji: "Jinken." }] },
      { japanese: "責任", romaji: "sekinin", english: "Responsibility", examples: [{ jp: "責任を 取る。", en: "Take responsibility.", romaji: "Sekinin wo toru." }, { jp: "重大な 責任。", en: "Great responsibility.", romaji: "Juudaina sekinin." }] },
      { japanese: "誠実な", romaji: "seijitsuna", english: "Sincere/Honest", examples: [{ jp: "誠実な 人柄。", en: "Sincere personality.", romaji: "Seijitsuna hitogara." }, { jp: "誠実に 答える。", en: "Answer sincerely.", romaji: "Seijitsu ni kotaeru." }] },
      { japanese: "勝手な", romaji: "kattena", english: "Selfish/Arbitrary", examples: [{ jp: "勝手な ことを言うな。", en: "Don't say selfish things.", romaji: "Kattena koto wo iu na." }, { jp: "勝手に する。", en: "Do as one pleases.", romaji: "Katte ni suru." }] },
      { japanese: "公平な", romaji: "kouheina", english: "Fair/Just", examples: [{ jp: "公平な 判断。", en: "Fair judgment.", romaji: "Kouheina handan." }, { jp: "不公平だ。", en: "That's unfair.", romaji: "Fukouhei da." }] },
      { japanese: "差別する", romaji: "sabetsusuru", english: "To discriminate", examples: [{ jp: "差別を なくす。", en: "Eliminate discrimination.", romaji: "Sabetsh wo nakusu." }, { jp: "性 差別。", en: "Sex discrimination.", romaji: "Sei sabetsu." }] },
      { japanese: "平等", romaji: "byoudou", english: "Equality", examples: [{ jp: "男女 平等。", en: "Gender equality.", romaji: "Danjou byoudou." }, { jp: "平等に 扱う。", en: "Treat equally.", romaji: "Byoudou ni atukau." }] },
      { japanese: "マナーモード", romaji: "manaamoodo", english: "Silent mode", examples: [{ jp: "マナーモードに 設定。", en: "Set to silent mode.", romaji: "Manaamoodo ni settei." }, { jp: "マナーモードを 切る。", en: "Turn off silent mode.", romaji: "Manaamoodo wo kiru." }] },
      { japanese: "禁煙", romaji: "kinen", english: "No smoking", examples: [{ jp: "ここは 禁煙です。", en: "It's non-smoking here.", romaji: "Koko wa kinen desu." }, { jp: "禁煙 席。", en: "Non-smoking seat.", romaji: "Kinenseki." }] },
      { japanese: "ゴミ箱", romaji: "gomibako", english: "Trash can/Bin", examples: [{ jp: "ゴミ箱は あちらです。", en: "Trash bin is over there.", romaji: "Gomibako wa achira desu." }, { jp: "ゴミを 捨てる。", en: "Throw away trash.", romaji: "Gomi wo suteru." }] },
      { japanese: "リサイクル", romaji: "risaikuru", english: "Recycling", examples: [{ jp: "リサイクルに 出す。", en: "Put out for recycling.", romaji: "Risaikuru ni dasu." }, { jp: "資源の リサイクル。", en: "Resource recycling.", romaji: "Shigen no risaikuru." }] },
      { japanese: "エチケット", romaji: "etiketto", english: "Etiquette", examples: [{ jp: "咳 エチケット。", en: "Cough etiquette.", romaji: "Seki etiketto." }, { jp: "基本の エチケット。", en: "Basic etiquette.", romaji: "Kihon no etiketto." }] }
    ]
  },
  {
    id: 47,
    level: "N4",
    title: "Technology & Future",
    description: "Vocabulary for science, AI, and innovations",
    words: [
      { japanese: "技術", romaji: "gijutsu", english: "Technology/Skill", examples: [{ jp: "最新の 技術。", en: "Latest tech.", romaji: "Saishin no gijutsu." }, { jp: "技術が 進歩する。", en: "Tech advances.", romaji: "Gijutsu ga shinposuru." }] },
      { japanese: "科学", romaji: "kagaku", english: "Science", examples: [{ jp: "科学の 力。", en: "Power of science.", romaji: "Kagaku no chikara." }, { jp: "科学者。", en: "Scientist.", romaji: "Kagakusha." }] },
      { japanese: "開発する", romaji: "kaihatsusuru", english: "To develop", examples: [{ jp: "新薬を 開発する。", en: "Develop a new drug.", romaji: "Shin'yaku wo kaihatsusuru." }, { jp: "ソフトの 開発。", en: "Software dev.", romaji: "Sofuto no kaihatsu." }] },
      { japanese: "進歩する", romaji: "shinposuru", english: "To progress/advance", examples: [{ jp: "医学が 進歩した。", en: "Medicine advanced.", romaji: "Igaku ga shinposhita." }, { jp: "日進月歩。", en: "Steady progress.", romaji: "Nisshingeppo." }] },
      { japanese: "発明する", romaji: "hatsumeisuru", english: "To invent", examples: [{ jp: "電話を 発明した人。", en: "The person who invented phone.", romaji: "Denwa wo hatsumeishita hito." }, { jp: "新 発明。", en: "New invention.", romaji: "Shin hatsumei." }] },
      { japanese: "発見する", romaji: "hakkensuru", english: "To discover", examples: [{ jp: "新しい 星を発見した。", en: "Discovered a new star.", romaji: "Atarashii hoshi wo hakkenshite." }, { jp: "大 発見。", en: "Great discovery.", romaji: "Dai hakken." }] },
      { japanese: "ロボット", romaji: "robotto", english: "Robot", examples: [{ jp: "お掃除 ロボット。", en: "Cleaning robot.", romaji: "Osouji robotto." }, { jp: "ロボット 産業。", en: "Robot industry.", romaji: "Robotto sangyou." }] },
      { japanese: "人工知能", romaji: "jinkouchinou", english: "Artificial Intelligence (AI)", examples: [{ jp: "人工知能を 使う。", en: "Use AI.", romaji: "Jinkouchinou wo tsukau." }, { jp: "ＡＩ 搭載。", en: "Equipped with AI.", romaji: "AI tousai." }] },
      { japanese: "デジタル", romaji: "dejitaru", english: "Digital", examples: [{ jp: "デジタル 時計。", en: "Digital watch.", romaji: "Dejitaru tokei." }, { jp: "デジタル化。", en: "Digitization.", romaji: "Dejitaruka." }] },
      { japanese: "インターネット", romaji: "intaanetto", english: "Internet", examples: [{ jp: "インターネットに 繋ぐ。", en: "Connect to internet.", romaji: "Intaanetto ni tsunagu." }, { jp: "ネット 社会。", en: "Networked society.", romaji: "Netto shakai." }] },
      { japanese: "情報", romaji: "jouhou", english: "Information", examples: [{ jp: "情報の 管理。", en: "Info management.", romaji: "Jouhou no kanri." }, { jp: "情報 漏洩。", en: "Info leak.", romaji: "Jouhou rouei." }] },
      { japanese: "通信", romaji: "tsuushin", english: "Communication/Signal", examples: [{ jp: "通信が 途切れる。", en: "Signal cuts out.", romaji: "Tsuushin ga togireru." }, { jp: "データ 通信。", en: "Data communication.", romaji: "Deeta tsuushin." }] },
      { japanese: "衛星", romaji: "eisei", english: "Satellite", examples: [{ jp: "人口 衛星。", en: "Artificial satellite.", romaji: "Jinkou eisei." }, { jp: "衛星 放送。", en: "Satellite broadcast.", romaji: "Eisei housou." }] },
      { japanese: "環境", romaji: "kankyou", english: "Environment", examples: [{ jp: "環境に 優しい。", en: "Eco-friendly.", romaji: "Kankyou ni yasashii." }, { jp: "地球 環境。", en: "Global environment.", romaji: "Chikyuu kankyou." }] },
      { japanese: "エネルギー", romaji: "enerugii", english: "Energy", examples: [{ jp: "太陽 エネルギー。", en: "Solar energy.", romaji: "Taiyou enerugii." }, { jp: "エネルギーを 節約する。", en: "Save energy.", romaji: "Enerugii wo setsuyakusuru." }] },
      { japanese: "資源", romaji: "shigen", english: "Resources", examples: [{ jp: "限られた 資源。", en: "Limited resources.", romaji: "Kagirareta shigen." }, { jp: "資源ごみ。", en: "Recyclable waste.", romaji: "Shigengomi." }] },
      { japanese: "実験する", romaji: "jikkensuru", english: "To experiment", examples: [{ jp: "理科の 実験。", en: "Science experiment.", romaji: "Rika no jikken." }, { jp: "実験 成功。", en: "Experiment successful.", romaji: "Jikken seikou." }] },
      { japanese: "研究する", romaji: "kenkyuusuru", english: "To research", examples: [{ jp: "癌を 研究する。", en: "Research cancer.", romaji: "Gan wo kenkyuusuru." }, { jp: "研究者。", en: "Researcher.", romaji: "Kenkyuusha." }] },
      { japanese: "調査する", romaji: "chousasuru", english: "To investigate/survey", examples: [{ jp: "アンケートで 調査する。", en: "Survey with questionnaire.", romaji: "Ankeeto de chousasuru." }, { jp: "原因 調査。", en: "Investigation into cause.", romaji: "Gen'in chousa." }] },
      { japanese: "分析する", romaji: "bunsekisuru", english: "To analyze", examples: [{ jp: "データを 分析する。", en: "Analyze data.", romaji: "Deeta wo bunsekisuru." }, { jp: "分析 結果。", en: "Analysis results.", romaji: "Bunseki kekka." }] },
      { japanese: "理論", romaji: "riron", english: "Theory", examples: [{ jp: "新しい 理論。", en: "New theory.", romaji: "Atarashii riron." }, { jp: "理論 的だ。", en: "It's theoretical/logical.", romaji: "Riron teki da." }] },
      { japanese: "事実", romaji: "jijitsu", english: "Fact", examples: [{ jp: "事実を 認める。", en: "Acknowledge the fact.", romaji: "Jijitsu wo mitomeru." }, { jp: "衝撃の 事実。", en: "Shocking fact.", romaji: "Shougeki no jijitsu." }] },
      { japanese: "証拠", romaji: "shouko", english: "Evidence/Proof", examples: [{ jp: "証拠が ない。", en: "No evidence.", romaji: "Shouko ga nai." }, { jp: "決定的な 証拠。", en: "Decisive proof.", romaji: "Ketteiteki na shouko." }] },
      { japanese: "未来", romaji: "mirai", english: "Future", examples: [{ jp: "明るい 未来。", en: "Bright future.", romaji: "Akarui mirai." }, { jp: "未来 都市。", en: "City of the future.", romaji: "Mirai toshi." }] },
      { japanese: "可能性", romaji: "kanousei", english: "Possibility", examples: [{ jp: "可能性が ある。", en: "There's a possibility.", romaji: "Kanousei ga aru." }, { jp: "無限の 可能性。", en: "Infinite possibility.", romaji: "Mugen no kanousei." }] },
      { japanese: "変化", romaji: "henka", english: "Change", examples: [{ jp: "時代の 変化。", en: "Changes of times.", romaji: "Jidai no henka." }, { jp: "変化に 気づく。", en: "Notice a change.", romaji: "Henka ni kizuku." }] },
      { japanese: "予測する", romaji: "yosokusuru", english: "To predict", examples: [{ jp: "未来を 予測する。", en: "Predict the future.", romaji: "Mirai wo yosokusuru." }, { jp: "予測 不能。", en: "Unpredictable.", romaji: "Yosoku funou." }] },
      { japanese: "現実", romaji: "genjitsu", english: "Reality", examples: [{ jp: "現実に なる。", en: "Become a reality.", romaji: "Genjitsu ni naru." }, { jp: "厳しい 現実。", en: "Harsh reality.", romaji: "Kibishii genjitsu." }] },
      { japanese: "夢", romaji: "yume", english: "Dream", examples: [{ jp: "夢を 叶える。", en: "Fulfill a dream.", romaji: "Yume wo kanaeru." }, { jp: "夢のような 話。", en: "Dream-like story.", romaji: "Yume no youna hanashi." }] },
      { japanese: "世界", romaji: "sekai", english: "World", examples: [{ jp: "世界 平和。", en: "World peace.", romaji: "Sekai heiwa." }, { jp: "世界 旅行。", en: "World trip.", romaji: "Sekai ryokou." }] }
    ]
  },
  {
    id: 48,
    level: "N4",
    title: "Honored Labels & Family",
    description: "Terms for family relations and social status",
    words: [
      { japanese: "祖父", romaji: "sofu", english: "Grandfather (Own)", examples: [{ jp: "祖父に 会う。", en: "Meet my grandfather.", romaji: "Sofu ni au." }, { jp: "私の 祖父。", en: "My grandfather.", romaji: "Watashi no sofu." }] },
      { japanese: "祖母", romaji: "sobo", english: "Grandmother (Own)", examples: [{ jp: "祖母の 手料理。", en: "Grandma's cooking.", romaji: "Sobo no te ryourit." }, { jp: "優しい 祖母。", en: "Kind grandmother.", romaji: "Yasashii sobo." }] },
      { japanese: "おじいさん", romaji: "ojiisan", english: "Grandfather (Other/Polite)", examples: [{ jp: "元気な おじいさん。", en: "Healthy old man.", romaji: "Genkina ojiisan." }, { jp: "田中さんの おじいさん。", en: "Tanaka's grandfather.", romaji: "Tanaka-san no ojiisan." }] },
      { japanese: "おばあさん", romaji: "obaasan", english: "Grandmother (Other/Polite)", examples: [{ jp: "おばあさんの 知恵。", en: "Old lady's wisdom.", romaji: "Obaasan no chie." }, { jp: "佐藤さんの おばあさん。", en: "Sato's grandmother.", romaji: "Satou-san no obaasan." }] },
      { japanese: "おじ", romaji: "oji", english: "Uncle (Own)", examples: [{ jp: "おじと 釣る。", en: "Fish with uncle.", romaji: "Oji to tsuru." }, { jp: "私の おじ。", en: "My uncle.", romaji: "Watashi no oji." }] },
      { japanese: "おば", romaji: "oba", english: "Aunt (Own)", examples: [{ jp: "おばの 家。", en: "Aunt's house.", romaji: "Oba no ie." }, { jp: "私の おば。", en: "My aunt.", romaji: "Watashi no oba." }] },
      { japanese: "おじさん", romaji: "ojisan", english: "Uncle (Other/Polite)", examples: [{ jp: "近所の おじさん。", en: "Uncle next door.", romaji: "Kinjo no ojisan." }, { jp: "おじさんに 挨拶。", en: "Greet the uncle.", romaji: "Ojisan ni aisatsu." }] },
      { japanese: "おばさん", romaji: "obasan", english: "Aunt (Other/Polite)", examples: [{ jp: "おばさんの 鞄。", en: "Aunt's bag.", romaji: "Obasan no kaban." }, { jp: "おばさんに 頼む。", en: "Ask the aunt.", romaji: "Obasan ni tanomu." }] },
      { japanese: "息子", romaji: "musuko", english: "Son (Own)", examples: [{ jp: "私の 息子。", en: "My son.", romaji: "Watashi no musuko." }, { jp: "一人 息子。", en: "Only son.", romaji: "Hitori musuko." }] },
      { japanese: "娘", romaji: "musume", english: "Daughter (Own)", examples: [{ jp: "私の 娘。", en: "My daughter.", romaji: "Watashi no musume." }, { jp: "可愛い 娘。", en: "Cute daughter.", romaji: "Kawai musume." }] },
      { japanese: "息子さん", romaji: "musukosan", english: "Son (Other)", examples: [{ jp: "ご 息子さん。", en: "Your son (very polite).", romaji: "Go musukosan." }, { jp: "佐藤さんの 息子さん。", en: "Sato's son.", romaji: "Satou-san no musukosan." }] },
      { japanese: "娘さん", romaji: "musumesan", english: "Daughter (Other)", examples: [{ jp: "ご 娘さん。", en: "Your daughter (very polite).", romaji: "Go musumesan." }, { jp: "田中さんの 娘さん。", en: "Tanaka's daughter.", romaji: "Tanaka-san no musumesan." }] },
      { japanese: "夫", romaji: "otto", english: "Husband (Own)", examples: [{ jp: "私の 夫。", en: "My husband.", romaji: "Watashi no otto." }, { jp: "夫と 食事。", en: "Dinner with husband.", romaji: "Otto to shokuji." }] },
      { japanese: "妻", romaji: "tsuma", english: "Wife (Own)", examples: [{ jp: "私の 妻。", en: "My wife.", romaji: "Watashi no tsuma." }, { jp: "妻に 贈る。", en: "Gift for my wife.", romaji: "Tsuma ni okuru." }] },
      { japanese: "主人", romaji: "shujin", english: "Husband (Own/Polite)", examples: [{ jp: "うちの 主人。", en: "My husband.", romaji: "Uchi no shujin." }, { jp: "主人に 聞く。", en: "Ask my husband.", romaji: "Shujin ni kiku." }] },
      { japanese: "家内", romaji: "kanai", english: "Wife (Own/Polite)", examples: [{ jp: "うちの 家内。", en: "My wife.", romaji: "Uchi no kanai." }, { jp: "家内と 旅行。", en: "Trip with my wife.", romaji: "Kanai to ryokou." }] },
      { japanese: "ご主人", romaji: "goshujin", english: "Husband (Other)", examples: [{ jp: "ご主人は いらっしゃいますか。", en: "Is your husband here?", romaji: "Goshujin wa irasshaimasu ka." }, { jp: "佐藤さんの ご主人。", en: "Sato's husband.", romaji: "Satou-san no goshujin." }] },
      { japanese: "奥さん", romaji: "okusan", english: "Wife (Other)", examples: [{ jp: "奥さんは 美人だ。", en: "Your wife is beautiful.", romaji: "Okusan wa bijin da." }, { jp: "田中さんの 奥さん。", en: "Tanaka's wife.", romaji: "Tanaka-san no okusan." }] },
      { japanese: "関係", romaji: "kankei", english: "Relationship", examples: [{ jp: "良好な 関係。", en: "Good relationship.", romaji: "Ryoukou na kankei." }, { jp: "仕事の 関係。", en: "Work relation.", romaji: "Shigoto no kankei." }] },
      { japanese: "親戚", romaji: "shinseki", english: "Relative", examples: [{ jp: "親戚の 集まり。", en: "Gathering of relatives.", romaji: "Shinseki no atsumari." }, { jp: "遠い 親戚。", en: "Distant relative.", romaji: "Tooi shinseki." }] },
      { japanese: "孫", romaji: "mago", english: "Grandchild", examples: [{ jp: "孫が 生まれた。", en: "Grandchild was born.", romaji: "Mago ga umareta." }, { jp: "可愛い 孫。", en: "Cute grandchild.", romaji: "Kawai mago." }] },
      { japanese: "甥", romaji: "oi", english: "Nephew", examples: [{ jp: "私の 甥。", en: "My nephew.", romaji: "Watashi no oi." }, { jp: "甥と 遊ぶ。", en: "Play with nephew.", romaji: "Oi to asobu." }] },
      { japanese: "姪", romaji: "mei", english: "Niece", examples: [{ jp: "私の 姪。", en: "My niece.", romaji: "Watashi no mei." }, { jp: "姪の 誕生日。", en: "Niece's birthday.", romaji: "Mei no tanjoubi." }] },
      { japanese: "独身", romaji: "dokushin", english: "Single/Unmarried", examples: [{ jp: "今は 独身です。", en: "I am single now.", romaji: "Ima wa dokushin desu." }, { jp: "独身 貴族。", en: "Single person living luxuriously.", romaji: "Dokushin kizoku." }] },
      { japanese: "結婚する", romaji: "kekkon suru", english: "To get married", examples: [{ jp: "去年 結婚した。", en: "Married last year.", romaji: "Kyonen kekkonshita." }, { jp: "結婚 式。", en: "Wedding ceremony.", romaji: "Kekkon shiki." }] },
      { japanese: "離婚する", romaji: "rikon suru", english: "To get divorced", examples: [{ jp: "三年前、離婚した。", en: "Divorced 3 years ago.", romaji: "Sannen mae, rikonshita." }, { jp: "離婚 歴。", en: "Divorce history.", romaji: "Rikonreki." }] },
      { japanese: "育てる", romaji: "sodateru", english: "To raise/rear", examples: [{ jp: "子供を 育てる。", en: "Raise a child.", romaji: "Kodomo wo sodateru." }, { jp: "花を 育てる。", en: "Grow flowers.", romaji: "Hana wo sodateru." }] },
      { japanese: "育つ", romaji: "sodatsu", english: "To grow up", examples: [{ jp: "田舎で 育った。", en: "Grew up in countryside.", romaji: "Inaka de sodatta." }, { jp: "すくすく 育つ。", en: "Grow quickly/healthily.", romaji: "Sukusuku sodatsu." }] },
      { japanese: "似ている", romaji: "niteiru", english: "To resemble", examples: [{ jp: "母親に 似ている。", en: "Resemble mother.", romaji: "Haha oya ni niteiru." }, { jp: "よく 似た二人。", en: "Two who look alike.", romaji: "Yoku nita futari." }] },
      { japanese: "可愛がる", romaji: "kawaigaru", english: "To dote on", examples: [{ jp: "犬を 可愛がる。", en: "Dote on a dog.", romaji: "Inu wo kawaigaru." }, { jp: "後輩を 可愛がる。", en: "Be fond of juniors.", romaji: "Kouhai wo kawaigaru." }] }
    ]
  },
  {
    id: 49,
    level: "N4",
    title: "Activities & Pastimes",
    description: "Vocabulary for leisure, social visits, and hobbies",
    words: [
      { japanese: "散歩する", romaji: "sanposuru", english: "To take a walk", examples: [{ jp: "公園を 散歩する。", en: "Walk in the park.", romaji: "Kouen wo sanposuru." }, { jp: "朝の 散歩。", en: "Morning walk.", romaji: "Asa no sanpo." }] },
      { japanese: "遊びに 行く", romaji: "asobi ni iku", english: "To go to play/visit", examples: [{ jp: "友達の家に 遊びに行く。", en: "Go visit friend's house.", romaji: "Tomodachi no ie ni asobi ni iku." }, { jp: "週末 遊びに行く。", en: "Go out on weekend.", romaji: "Shuumatsu asobi ni iku." }] },
      { japanese: "招待する", romaji: "shoutai suru", english: "To invite", examples: [{ jp: "披露宴に 招待する。", en: "Invite to reception.", romaji: "Hirouen ni shoutai suru." }, { jp: "招待 状。", en: "Invitation card.", romaji: "Shoutaijou." }] },
      { japanese: "誘う", romaji: "sasou", english: "To invite/ask out", examples: [{ jp: "食事に 誘う。", en: "Invite for a meal.", romaji: "Shokuji ni sasou." }, { jp: "ドライブに 誘う。", en: "Ask out for a drive.", romaji: "Doraibu ni sasou." }] },
      { japanese: "集まる", romaji: "atsumaru", english: "To gather (intransitive)", examples: [{ jp: "広場に 人が集まる。", en: "People gather at plaza.", romaji: "Hiroba ni hito ga atsumaru." }, { jp: "お金が 集まる。", en: "Money gets collected/gathered.", romaji: "Okane ga atsumaru." }] },
      { japanese: "集める", romaji: "atsumeru", english: "To collect (transitive)", examples: [{ jp: "切手を 集める。", en: "Collect stamps.", romaji: "Kitte wo atsumeru." }, { jp: "意見を 集める。", en: "Gather opinions.", romaji: "Iken wo atsumeru." }] },
      { japanese: "別れる", romaji: "wakareru", english: "To part/separate", examples: [{ jp: "駅で 別れる。", en: "Part at the station.", romaji: "Eki de wakareru." }, { jp: "恋人と 別れる。", en: "Break up with partner.", romaji: "Koibito to wakareru." }] },
      { japanese: "出会う", romaji: "deau", english: "To meet by chance", examples: [{ jp: "偶然 道で出会った。", en: "Met on street by chance.", romaji: "Guuzen michi de deatta." }, { jp: "素敵な 出会い。", en: "Wonderful encounter.", romaji: "Sutekina deai." }] },
      { japanese: "喜ぶ", romaji: "yorokobu", english: "To be glad/happy", examples: [{ jp: "合格を 喜ぶ。", en: "Be happy about passing.", romaji: "Goukaku wo yorokobu." }, { jp: "プレゼントを 喜ぶ。", en: "Be glad with the gift.", romaji: "Purezento wo yorokobu." }] },
      { japanese: "楽しむ", romaji: "tanoshimu", english: "To enjoy", examples: [{ jp: "休暇を 楽しむ。", en: "Enjoy vacation.", romaji: "Kyuuka wo tanoshimu." }, { jp: "音楽を 楽しむ。", en: "Enjoy music.", romaji: "Ongaku wo tanoshimu." }] },
      { japanese: "褒める", romaji: "homeru", english: "To praise", examples: [{ jp: "子供を 褒める。", en: "Praise the child.", romaji: "Kodomo wo homeru." }, { jp: "出来を 褒める。", en: "Praise the performance/work.", romaji: "Deki wo homeru." }] },
      { japanese: "叱る", romaji: "shikaru", english: "To scold", examples: [{ jp: "嘘をついて 叱られた。", en: "Was scolded for lying.", romaji: "Uso wo tsuite shikarareta." }, { jp: "厳しく 叱る。", en: "Scold strictly.", romaji: "Kibishiku shikaru." }] },
      { japanese: "応援する", romaji: "ouensuru", english: "To support/cheer", examples: [{ jp: "チームを 応援する。", en: "Support the team.", romaji: "Chiimu wo ouensuru." }, { jp: "応援 メッセージ。", en: "Support message.", romaji: "Ouen messeeji." }] },
      { japanese: "手伝う", romaji: "tetsudau", english: "To help/assist", examples: [{ jp: "引っ越しを 手伝う。", en: "Help with moving.", romaji: "Hikkoshi wo tetsudau." }, { jp: "手伝いましょうか。", en: "Shall I help you?", romaji: "Tetsudaimashou ka." }] },
      { japanese: "頼む", romaji: "tanomu", english: "To ask/request", examples: [{ jp: "仕事を 頼む。", en: "Request a job.", romaji: "Shigoto wo tanomu." }, { jp: "一つ 頼みがある。", en: "I have a favor.", romaji: "Hitotsu tanomi ga aru." }] },
      { japanese: "断る", romaji: "kotowaru", english: "To refuse/decline", examples: [{ jp: "誘いを 断る。", en: "Decline an invite.", romaji: "Sasoi wo kotowaru." }, { jp: "丁寧に 断る。", en: "Refuse politely.", romaji: "Teinei ni kotowaru." }] },
      { japanese: "協力する", romaji: "kyouryokusuru", english: "To cooperate", examples: [{ jp: "みんなで 協力する。", en: "Everyone cooperate.", romaji: "Minna de kyouryokusuru." }, { jp: "国際 協力。", en: "International cooperation.", romaji: "Kokusai kyouryoku." }] },
      { japanese: "相談する", romaji: "soudansuru", english: "To consult/discuss", examples: [{ jp: "悩みを 相談する。", en: "Discuss worries.", romaji: "Nayami wo soudansuru." }, { jp: "相談に 乗る。", en: "Give advice/Listen.", romaji: "Soudan ni noru." }] },
      { japanese: "報告する", romaji: "houkokusuru", english: "To report", examples: [{ jp: "嘘なく 報告する。", en: "Report without lies.", romaji: "Uso naku houkokusuru." }, { jp: "定期 報告。", en: "Regular report.", romaji: "Teiki houkoku." }] },
      { japanese: "連絡する", romaji: "renrakusuru", english: "To contact", examples: [{ jp: "後で 連絡します。", en: "I'll contact later.", romaji: "Ato de renrakushimasu." }, { jp: "緊急 連絡先。", en: "Emergency contact.", romaji: "Kinkyuu renrakusaki." }] },
      { japanese: "喧嘩する", romaji: "kenkasuru", english: "To fight/quarrel", examples: [{ jp: "兄弟で 喧嘩する。", en: "Fight with siblings.", romaji: "Kyoudai de kenkasuru." }, { jp: "絶交する。", en: "Break off friendship.", romaji: "Zekkou suru." }] },
      { japanese: "謝る", romaji: "ayamaru", english: "To apologize", examples: [{ jp: "遅刻を 謝る。", en: "Apologize for being late.", romaji: "Chikoku wo ayamaru." }, { jp: "謝って 済む話じゃない。", en: "Apologizing alone won't fix it.", romaji: "Ayamatte sumu hanashijanai." }] },
      { japanese: "許す", romaji: "yurusuhu", english: "To forgive", examples: [{ jp: "間違いを 許す。", en: "Forgive a mistake.", romaji: "Machigai wo yurusu." }, { jp: "許して ください。", en: "Please forgive me.", romaji: "Yurushite kudasai." }] },
      { japanese: "感謝する", romaji: "kanshasuru", english: "To be grateful", examples: [{ jp: "親切に 感謝する。", en: "Grateful for kindness.", romaji: "Shinsetsu ni kanshasuru." }, { jp: "感謝状。", en: "Letter of thanks.", romaji: "Kanshajou." }] },
      { japanese: "信じる", romaji: "shinjiru", english: "To believe/trust", examples: [{ jp: "自分を 信じる。", en: "Believe in yourself.", romaji: "Jibun wo shinjiru." }, { jp: "神を 信じる。", en: "Believe in God.", romaji: "Kami wo shinjiru." }] },
      { japanese: "疑う", romaji: "utagau", english: "To doubt", examples: [{ jp: "目を 疑う。", en: "Doubt one's eyes.", romaji: "Me wo utagau." }, { jp: "犯人と 疑う。", en: "Suspect as the culprit.", romaji: "Hannin to utagau." }] },
      { japanese: "期待する", romaji: "kitaisuru", english: "To expect/look forward", examples: [{ jp: "将来を 期待する。", en: "Expect (great things) in future.", romaji: "Shourai wo kitaisuru." }, { jp: "期待して 待つ。", en: "Wait with expectation.", romaji: "Kitaishite matsu." }] },
      { japanese: "がっかりする", romaji: "gakkarisuru", english: "To be disappointed", examples: [{ jp: "結果に がっかりした。", en: "Disappointed at result.", romaji: "Kekka ni gakkarishita." }, { jp: "がっかり させないで。", en: "Don't disappoint me.", romaji: "Gakkari sasenaide." }] },
      { japanese: "驚く", romaji: "odoroku", english: "To be surprised", examples: [{ jp: "急な来客に驚く。", en: "Surprised by sudden guest.", romaji: "Kyuuna raikyaku ni odoroku." }, { jp: "驚くほど きれいだ。", en: "Surprisingly beautiful.", romaji: "Odorokuhodo kirei da." }] },
      { japanese: "感動する", romaji: "kandousuru", english: "To be moved", examples: [{ jp: "美しい景色に感動した。", en: "Moved by beautiful view.", romaji: "Utsukushii keshiki ni kandoushita." }, { jp: "感動の 再会。", en: "Touching reunion.", romaji: "Kandou no saikai." }] }
    ]
  },
  {
    id: 50,
    level: "N4",
    title: "Abstract Concepts & Quality",
    description: "Vocabulary for ideas, degrees, and characteristics",
    words: [
      { japanese: "考え", romaji: "kangae", english: "Trend/Thought", examples: [{ jp: "良い 考えだ。", en: "Good idea.", romaji: "Ii kangae da." }, { jp: "自分の 考え。", en: "One's own thought.", romaji: "Jibun no kangae." }] },
      { japanese: "意見", romaji: "iken", english: "Opinion", examples: [{ jp: "反対の 意見。", en: "Opposing opinion.", romaji: "Hantai no iken." }, { jp: "意見を 交換する。", en: "Exchange opinions.", romaji: "Iken wo koukansuru." }] },
      { japanese: "理由", romaji: "riyuu", english: "Reason", examples: [{ jp: "正当な 理由。", en: "Justifiable reason.", romaji: "Seitouna riyuu." }, { jp: "理由が わからない。", en: "Don't know the reason.", romaji: "Riyuu ga wakaranai." }] },
      { japanese: "意味", romaji: "imi", english: "Meaning", examples: [{ jp: "言葉の 意味。", en: "Meaning of the word.", romaji: "Kotoba no imi." }, { jp: "意味が 通じる。", en: "The meaning gets across.", romaji: "Imi ga tsuujiru." }] },
      { japanese: "目的", romaji: "mokuteki", english: "Purpose/Goal", examples: [{ jp: "来日の 目的。", en: "Purpose of visit to Japan.", romaji: "Rainichi no mokuteki." }, { jp: "目的を 達成する。", en: "Achieve a goal.", romaji: "Mokuteki wo tasseisuru." }] },
      { japanese: "結果", romaji: "kekka", english: "Result", examples: [{ jp: "試験の 結果。", en: "Exam results.", romaji: "Shiken no kekka." }, { jp: "良い 結果。", en: "Good result.", romaji: "Ii kekka." }] },
      { japanese: "原因", romaji: "gen'in", english: "Cause", examples: [{ jp: "事故の 原因。", en: "Cause of accident.", romaji: "Jiko no gen'in." }, { jp: "原因は 何？", en: "What is the cause?", romaji: "Gen'in wa nani?" }] },
      { japanese: "方法", romaji: "houhou", english: "Method/Way", examples: [{ jp: "解決の 方法。", en: "Method of solution.", romaji: "Kaiketsu no houhou." }, { jp: "色々な 方法。", en: "Various ways.", romaji: "Iroirona houhou." }] },
      { japanese: "技術", romaji: "gijutsu", english: "Technique/Skill", examples: [{ jp: "優れた 技術。", en: "Excellent technique.", romaji: "Sugureta gijutsu." }, { jp: "技術を 磨く。", en: "Polish one's skill.", romaji: "Gijutsu wo migaku." }] },
      { japanese: "種類", romaji: "shurui", english: "Kind/Sort", examples: [{ jp: "色々な 種類。", en: "Various kinds.", romaji: "Iroirona shurui." }, { jp: "新 種類。", en: "New species/type.", romaji: "Shin shurui." }] },
      { japanese: "程度", romaji: "teido", english: "Degree/Extent", examples: [{ jp: "どの 程度ですか。", en: "To what extent?", romaji: "Dono teido desu ka." }, { jp: "ある 程度の時間。", en: "Some degree of time.", romaji: "Aru teido no jikan." }] },
      { japanese: "平均", romaji: "heikun", english: "Average", examples: [{ jp: "テストの 平均点。", en: "Avg score of test.", romaji: "Tesuto no heikunten." }, { jp: "平均 寿命。", en: "Average life span.", romaji: "Heikun jumyou." }] },
      { japanese: "普通", romaji: "futsuu", english: "Normal/Ordinary", examples: [{ jp: "普通の 生活。", en: "Ordinary life.", romaji: "Futsuu no seikatsu." }, { jp: "普通は こうだ。", en: "Usually it's like this.", romaji: "Futsuu wa kou da." }] },
      { japanese: "特別", romaji: "tokubetsu", english: "Special", examples: [{ jp: "特別な 日。", en: "Special day.", romaji: "Tokubetsuna hi." }, { jp: "特別に 許可する。", en: "Specially permit.", romaji: "Tokubetsu ni kyokasuru." }] },
      { japanese: "当然", romaji: "touzen", english: "Of course/Natural", examples: [{ jp: "当然の 結果だ。", en: "It's a natural result.", romaji: "Touzen no kekka da." }, { jp: "当然 わかっている。", en: "Of course I know.", romaji: "Touzen wakatteiru." }] },
      { japanese: "意外な", romaji: "igaina", english: "Unexpected", examples: [{ jp: "意外な 答え。", en: "Unexpected answer.", romaji: "Igaina kotae." }, { jp: "意外と 面白かった。", en: "It was unexpectedly fun.", romaji: "Igaito omoshirokatta." }] },
      { japanese: "不思議な", romaji: "fushigina", english: "Mysterious", examples: [{ jp: "不思議な 体験。", en: "Mysterious experience.", romaji: "Fushigina taiken." }, { jp: "不思議に 思う。", en: "To wonder/feel strange.", romaji: "Fushigi ni omou." }] },
      { japanese: "適当な", romaji: "tekitouna", english: "Appropriate", examples: [{ jp: "適当な サイズ。", en: "Appropriate size.", romaji: "Tekitouna saizu." }, { jp: "適当に 扱う。", en: "Treat carelessly/randomly.", romaji: "Tekitou ni atsukau." }] },
      { japanese: "十分な", romaji: "juubunna", english: "Sufficient", examples: [{ jp: "十分な 食事。", en: "Sufficient meal.", romaji: "Juubunna shokuji." }, { jp: "もう 十分だ。", en: "That's enough already.", romaji: "Mou juubun da." }] },
      { japanese: "不十分な", romaji: "fujuubunna", english: "Insufficient", examples: [{ jp: "説明が 不十分だ。", en: "Explanation is insufficient.", romaji: "Setsumei ga fujuubun da." }, { jp: "不十分な 準備。", en: "Insufficient prep.", romaji: "Fujuubunna junbi." }] },
      { japanese: "重要", romaji: "juuyou", english: "Important", examples: [{ jp: "重要な 書類。", en: "Important document.", romaji: "Juuyouna shorui." }, { jp: "最も 重要だ。", en: "It is most important.", romaji: "Mottmomo juuyou da." }] },
      { japanese: "必要", romaji: "hitsuyou", english: "Necessary", examples: [{ jp: "必要な お金。", en: "Necessary money.", romaji: "Hitsuyouna okane." }, { jp: "必要に 迫られる。", en: "Be forced by necessity.", romaji: "Hitsuyou ni semarareru." }] },
      { japanese: "不必要", romaji: "fuhitsuyou", english: "Unnecessary", examples: [{ jp: "不必要な 出費。", en: "Unnecessary expense.", romaji: "Fuhitsuyouna shuppi." }, { jp: "不必要だ。", en: "It's unnecessary.", romaji: "Fuhitsuyou da." }] },
      { japanese: "価値", romaji: "kachi", english: "Value/Worth", examples: [{ jp: "価値が ある。", en: "It has value.", romaji: "Kachi ga aru." }, { jp: "価値観の 違い。", en: "Difference in values.", romaji: "Kachikan no chigai." }] },
      { japanese: "有効", romaji: "yuukou", english: "Valid/Effective", examples: [{ jp: "有効な 手段。", en: "Effective means.", romaji: "Yuukouna shudan." }, { jp: "期限内は 有効。", en: "Valid within the limit.", romaji: "Kigennai wa yuukou." }] },
      { japanese: "無効", romaji: "mukou", english: "Invalid/Ineffective", examples: [{ jp: "チケットが 無効だ。", en: "Ticket is invalid.", romaji: "Tiketto ga mukou da." }, { jp: "無効に する。", en: "Make invalid/Cancel.", romaji: "Mukou ni suru." }] },
      { japanese: "関係", romaji: "kankei", english: "Relation/Connection", examples: [{ jp: "無 関係。", en: "Unrelated.", romaji: "Mu kankei." }, { jp: "関係を 断つ。", en: "Cut ties.", romaji: "Kankei wo tatsu." }] },
      { japanese: "反対", romaji: "hantai", english: "Opposite/Oppose", examples: [{ jp: "反対の 向き。", en: "Opposite direction.", romaji: "Hantai no muki." }, { jp: "計画に 反対だ。", en: "Against the plan.", romaji: "Keikaku ni hantai da." }] },
      { japanese: "同じ", romaji: "onaji", english: "Same", examples: [{ jp: "同じ デザイン。", en: "Same design.", romaji: "Onaji dezain." }, { jp: "みんな 同じだ。", en: "All are the same.", romaji: "Minna onaji da." }] },
      { japanese: "違う", romaji: "chigau", english: "Different/Wrong", examples: [{ jp: "意見が 違う。", en: "Opinions differ.", romaji: "Iken ga chigau." }, { jp: "それは 違う。", en: "That is wrong.", romaji: "Sore wa chigau." }] }
    ]
  }
];
