export const chunk8 = [
  {
    id: 36,
    level: "N4",
    title: "Social Media & Digital Life",
    description: "Vocabulary for modern communication and internet",
    words: [
      { japanese: "投稿する", romaji: "toukou suru", english: "To post", examples: [{ jp: "写真を 投稿する。", en: "Post a photo.", romaji: "Shashin wo toukou suru." }, { jp: "ＳＮＳに 投稿。", en: "Post on SNS.", romaji: "SNS ni toukou." }] },
      { japanese: "共有する", romaji: "kyouyuu suru", english: "To share", examples: [{ jp: "情報を 共有する。", en: "Share information.", romaji: "Jouhou wo kyouyuu suru." }, { jp: "ファイルを 共有。", en: "Share a file.", romaji: "Fairu wo kyouyuu." }] },
      { japanese: "検索する", romaji: "kensaku suru", english: "To search (online)", examples: [{ jp: "言葉を 検索する。", en: "Search for a word.", romaji: "Kotoba wo kensaku suru." }, { jp: "ネットで 検索。", en: "Search on the net.", romaji: "Netto de kensaku." }] },
      { japanese: "保存する", romaji: "hozon suru", english: "To save", examples: [{ jp: "データを 保存する。", en: "Save the data.", romaji: "Deeta wo hozon suru." }, { jp: "名前を 付けて保存。", en: "Save as...", romaji: "Namae wo tsukete hozon." }] },
      { japanese: "削除する", romaji: "sakujo suru", english: "To delete", examples: [{ jp: "メールを 削除する。", en: "Delete the email.", romaji: "Meeru wo sakujo suru." }, { jp: "アカウント 削除。", en: "Account deletion.", romaji: "Akaunto sakujo." }] },
      { japanese: "更新する", romaji: "koushin suru", english: "To update", examples: [{ jp: "ブログを 更新する。", en: "Update the blog.", romaji: "Burogu wo koushin suru." }, { jp: "アプリの 更新。", en: "App update.", romaji: "Apuri no koushin." }] },
      { japanese: "拡散する", romaji: "kakusan suru", english: "To go viral/spread", examples: [{ jp: "動画が 拡散した。", en: "The video went viral.", romaji: "Douga ga kakusanshita." }, { jp: "情報の 拡散。", en: "Spread of information.", romaji: "Jouhou no kakusan." }] },
      { japanese: "いいね", romaji: "iine", english: "Like (on SNS)", examples: [{ jp: "いいねを 押す。", en: "Press like.", romaji: "Iine wo osu." }, { jp: "いいねが 多い。", en: "Many likes.", romaji: "Iine ga ooi." }] },
      { japanese: "フォロワー", romaji: "forowaa", english: "Follower", examples: [{ jp: "フォロワーを 増やす。", en: "Increase followers.", romaji: "Forowaa wo fuyasu." }, { jp: "人気の フォロワー。", en: "Popular follower.", romaji: "Ninkina forowaa." }] },
      { japanese: "動画", romaji: "douga", english: "Video (online)", examples: [{ jp: "動画を 見る。", en: "Watch a video.", romaji: "Douga wo miru." }, { jp: "短い 動画。", en: "Short video.", romaji: "Mijikai douga." }] },
      { japanese: "画像", romaji: "gazou", english: "Image", examples: [{ jp: "画像を 送る。", en: "Send an image.", romaji: "Gazou wo okuru." }, { jp: "きれいな 画像。", en: "Clean image.", romaji: "Kireina gazou." }] },
      { japanese: "通知", romaji: "tsuuchi", english: "Notification", examples: [{ jp: "通知が 来る。", en: "Get a notification.", romaji: "Tsuuchi ga kuru." }, { jp: "通知を 切る。", en: "Turn off notifications.", romaji: "Tsuuchi wo kiru." }] },
      { japanese: "設定", romaji: "settei", english: "Settings", examples: [{ jp: "設定を 変える。", en: "Change settings.", romaji: "Settei wo kaeru." }, { jp: "初期 設定。", en: "Default settings.", romaji: "Shoki settei." }] },
      { japanese: "画面", romaji: "gamen", english: "Screen", examples: [{ jp: "画面が 割れた。", en: "Screen cracked.", romaji: "Gamen ga wareta." }, { jp: "明るい 画面。", en: "Bright screen.", romaji: "Akarui gamen." }] },
      { japanese: "電池", romaji: "denchi", english: "Battery", examples: [{ jp: "電池が なくなる。", en: "Battery dies.", romaji: "Denchi ga nakunaru." }, { jp: "電池の 持ち。", en: "Battery life.", romaji: "Denchi no mochi." }] },
      { japanese: "充電", romaji: "juuden", english: "Charging", examples: [{ jp: "充電器を 借りる。", en: "Borrow a charger.", romaji: "Juudenki wo kariru." }, { jp: "充電中。", en: "Charging.", romaji: "Juudenchuu." }] },
      { japanese: "電波", romaji: "denpa", english: "Reception/Signal", examples: [{ jp: "電波が 悪い。", en: "Bad signal.", romaji: "Denpa ga warui." }, { jp: "電波を 探す。", en: "Look for signal.", romaji: "Denpa wo sagasu." }] },
      { japanese: "Wi-Fi", romaji: "waifai", english: "Wi-Fi", examples: [{ jp: "Wi-Fiを 繋ぐ。", en: "Connect to Wi-Fi.", romaji: "Waifai wo tsunagu." }, { jp: "無料 Wi-Fi。", en: "Free Wi-Fi.", romaji: "Muryou waifai." }] },
      { japanese: "繋ぐ", romaji: "tsunagu", english: "To connect", examples: [{ jp: "ネットに 繋ぐ。", en: "Connect to the net.", romaji: "Netto ni tsunagu." }, { jp: "手を 繋ぐ。", en: "Hold hands.", romaji: "Te wo tsunagu." }] },
      { japanese: "繋がる", romaji: "tsunagaru", english: "To be connected", examples: [{ jp: "電話が 繋がらない。", en: "Phone doesn't connect.", romaji: "Denwa ga tsunagaranai." }, { jp: "ネットが 繋がる。", en: "Net is connected.", romaji: "Netto ga tsunagaru." }] },
      { japanese: "送る", romaji: "okuru", english: "To send", examples: [{ jp: "メールを 送る。", en: "Send mail.", romaji: "Meeru wo okuru." }, { jp: "荷物を 送る。", en: "Send a package.", romaji: "Nimotsu wo okuru." }] },
      { japanese: "届く", romaji: "todoku", english: "To reach/arrive", examples: [{ jp: "荷物が 届いた。", en: "Package arrived.", romaji: "Nimotsu ga todoita." }, { jp: "手が 届く。", en: "Reach with hands.", romaji: "Te ga todoku." }] },
      { japanese: "便利な", romaji: "benrina", english: "Convenient", examples: [{ jp: "便利な アプリ。", en: "Convenient app.", romaji: "Benrina apuri." }, { jp: "とても 便利だ。", en: "Very convenient.", romaji: "Totemo benri da." }] },
      { japanese: "操作する", romaji: "sousa suru", english: "To operate", examples: [{ jp: "機械を 操作する。", en: "Operate a machine.", romaji: "Kikai wo sousa suru." }, { jp: "スマホを 操作。", en: "Operate a smartphone.", romaji: "Sumaho no sousa." }] },
      { japanese: "機能", romaji: "kinou", english: "Function/Feature", examples: [{ jp: "新しい 機能。", en: "New feature.", romaji: "Atarashii kinou." }, { jp: "便利な 機能。", en: "Convenient function.", romaji: "Benrina kinou." }] },
      { japanese: "故障する", romaji: "koshou suru", english: "To break down", examples: [{ jp: "パソコンが 故障した。", en: "PC broke down.", romaji: "Pasokon ga koshoushita." }, { jp: "故障中。", en: "Out of order.", romaji: "Koshouchuu." }] },
      { japanese: "修理する", romaji: "shuuri suru", english: "To repair", examples: [{ jp: "時計を 修理する。", en: "Repair a watch.", romaji: "Shuuri suru." }, { jp: "修理に 出す。", en: "Send for repair.", romaji: "Shuuri ni dasu." }] },
      { japanese: "部品", romaji: "buhin", english: "Parts", examples: [{ jp: "車の 部品。", en: "Car parts.", romaji: "Kuruma no buhin." }, { jp: "部品を 交換する。", en: "Replace parts.", romaji: "Buhin wo koukan suru." }] },
      { japanese: "画面", romaji: "gamen", english: "Screen", examples: [{ jp: "大きな 画面。", en: "Large screen.", romaji: "Ookina gamen." }, { jp: "パソコンの 画面。", en: "PC screen.", romaji: "Pasokon no gamen." }] },
      { japanese: "キーボード", romaji: "kiiboodo", english: "Keyboard", examples: [{ jp: "キーボードで 打つ。", en: "Type on keyboard.", romaji: "Kiiboodo de utsu." }, { jp: "新しい キーボード。", en: "New keyboard.", romaji: "Atarashii kiiboodo." }] }
    ]
  },
  {
    id: 37,
    level: "N4",
    title: "Weather & Disasters",
    description: "Vocabulary for natural phenomena and emergencies",
    words: [
      { japanese: "天気予報", romaji: "tenkiyohou", english: "Weather forecast", examples: [{ jp: "天気予報を チェックする。", en: "Check the forecast.", romaji: "Tenkiyohou wo chekkusuru." }, { jp: "明日の 天気予報。", en: "Tomorrow's forecast.", romaji: "Ashita no tenkiyohou." }] },
      { japanese: "晴れる", romaji: "hareru", english: "To clear up", examples: [{ jp: "午後は 晴れる。", en: "Will clear up in afternoon.", romaji: "Gogo wa hareru." }, { jp: "晴れた 空。", en: "Clear sky.", romaji: "Hareta sora." }] },
      { japanese: "曇る", romaji: "kumoru", english: "To get cloudy", examples: [{ jp: "急に 曇ってきた。", en: "Suddenly got cloudy.", romaji: "Kyuu ni kumotte kita." }, { jp: "曇り空。", en: "Cloudy sky.", romaji: "Kumorizora." }] },
      { japanese: "降る", romaji: "furu", english: "To fall (rain/snow)", examples: [{ jp: "雨が 降る。", en: "It rains.", romaji: "Ame ga furu." }, { jp: "雪が 降る。", en: "It snows.", romaji: "Yuki ga furu." }] },
      { japanese: "止む", romaji: "yamu", english: "To stop (rain/snow)", examples: [{ jp: "雨が 止んだ。", en: "Rain stopped.", romaji: "Ame ga yanda." }, { jp: "早く 止んでほしい。", en: "Want it to stop soon.", romaji: "Hayaku yande hoshii." }] },
      { japanese: "風", romaji: "kaze", english: "Wind", examples: [{ jp: "風が 強い。", en: "Wind is strong.", romaji: "Kaze ga tsuyoi." }, { jp: "そよ風。", en: "Breeze.", romaji: "Soyokaze." }] },
      { japanese: "台風", romaji: "taifuu", english: "Typhoon", examples: [{ jp: "台風が 来る。", en: "Typhoon is coming.", romaji: "Taifuu ga kuru." }, { jp: "台風の 被害。", en: "Typhoon damage.", romaji: "Taifuu no higai." }] },
      { japanese: "雷", romaji: "kaminari", english: "Thunder", examples: [{ jp: "雷が 鳴る。", en: "Thunder rolls.", romaji: "Kaminari ga naru." }, { jp: "雷が 怖い。", en: "Scared of thunder.", romaji: "Kaminari ga kowai." }] },
      { japanese: "地震", romaji: "jishin", english: "Earthquake", examples: [{ jp: "大きい 地震。", en: "Big earthquake.", romaji: "Ookii jishin." }, { jp: "地震に 備える。", en: "Prepare for earthquakes.", romaji: "Jishin ni sonaeru." }] },
      { japanese: "津波", romaji: "tsunami", english: "Tsunami", examples: [{ jp: "津波の 警告。", en: "Tsunami warning.", romaji: "Tsunami no keikoku." }, { jp: "怖い 津波。", en: "Scary tsunami.", romaji: "Kowai tsunami." }] },
      { japanese: "洪水", romaji: "kouzui", english: "Flood", examples: [{ jp: "洪水が 起きる。", en: "Flood occurs.", romaji: "Kouzui ga okiru." }, { jp: "洪水に 注意。", en: "Beware of floods.", romaji: "Kouzui ni chuui." }] },
      { japanese: "災害", romaji: "saigai", english: "Disaster", examples: [{ jp: "自然 災害。", en: "Natural disaster.", romaji: "Shizen saigai." }, { jp: "災害に 遭う。", en: "Encounter a disaster.", romaji: "Saigai ni au." }] },
      { japanese: "火事", romaji: "kaji", english: "Fire", examples: [{ jp: "近所で 火事。", en: "Fire in neighborhood.", romaji: "Kinjo de kaji." }, { jp: "火事に 気をつける。", en: "Careful of fire.", romaji: "Kaji ni ki wo tsukeru." }] },
      { japanese: "非常口", romaji: "hijouguchi", english: "Emergency exit", examples: [{ jp: "非常口は あそこ。", en: "Exit is over there.", romaji: "Hijouguchi wa asoko." }, { jp: "非常口の サイン。", en: "Exit sign.", romaji: "Hijouguchi no sain." }] },
      { japanese: "避難する", romaji: "hinansuru", english: "To evacuate", examples: [{ jp: "近くの学校に避難する。", en: "Evacuate to nearby school.", romaji: "Chikaku no gakkou ni hinansuru." }, { jp: "避難 訓練。", en: "Evacuation drill.", romaji: "Hinan kunren." }] },
      { japanese: "注意する", romaji: "chuuisuru", english: "To be careful", examples: [{ jp: "車に 注意する。", en: "Careful of cars.", romaji: "Kuruma ni chuuisuru." }, { jp: "注意 してください。", en: "Please be careful.", romaji: "Chuui shite kudasai." }] },
      { japanese: "温度", romaji: "ondou", english: "Temperature", examples: [{ jp: "温度が 上がる。", en: "Temp rises.", romaji: "Ondou ga agaru." }, { jp: "適切な 温度。", en: "Appropriate temp.", romaji: "Tekisetsu na ondou." }] },
      { japanese: "湿度", romaji: "shitsudo", english: "Humidity", examples: [{ jp: "湿度が 高い。", en: "Humidity is high.", romaji: "Shitsudo ga takai." }, { jp: "湿度を 下げる。", en: "Lower humidity.", romaji: "Shitsudo wo sageru." }] },
      { japanese: "蒸し暑い", romaji: "mushiatsui", english: "Humid/Sultry", examples: [{ jp: "今日は 蒸し暑い。", en: "Hot and humid today.", romaji: "Kyou wa mushiatsui." }, { jp: "日本の夏は蒸し暑い。", en: "Japan's summer is humid.", romaji: "Nihon no natsu wa mushiatsui." }] },
      { japanese: "乾燥する", romaji: "kansousuru", english: "To get dry", examples: [{ jp: "冬は 乾燥する。", en: "It gets dry in winter.", romaji: "Fuyu wa kansousuru." }, { jp: "空気が 乾燥している。", en: "The air is dry.", romaji: "Kuuki ga kansou shiteiru." }] },
      { japanese: "零下", romaji: "reika", english: "Below zero", examples: [{ jp: "零下 十度。", en: "10 degrees below zero.", romaji: "Reika juudo." }, { jp: "零下の 寒さ。", en: "Below-zero cold.", romaji: "Reika no samusa." }] },
      { japanese: "氷", romaji: "koori", english: "Ice", examples: [{ jp: "氷が 張る。", en: "Ice forms.", romaji: "Koori ga haru." }, { jp: "冷たい 氷。", en: "Cold ice.", romaji: "Tsumetai koori." }] },
      { japanese: "溶ける", romaji: "tokeru", english: "To melt", examples: [{ jp: "雪が 溶ける。", en: "Snow melts.", romaji: "Yuki ga tokeru." }, { jp: "アイスが 溶ける。", en: "Ice cream melts.", romaji: "Aisu ga tokeru." }] },
      { japanese: "吹く", romaji: "fuku", english: "To blow", examples: [{ jp: "北風が 吹く。", en: "North wind blows.", romaji: "Kitakaze ga fuku." }, { jp: "口笛を 吹く。", en: "Whistle.", romaji: "Kuchibue wo fuku." }] },
      { japanese: "季節", romaji: "kisetsu", english: "Season", examples: [{ jp: "好きな 季節。", en: "Favorite season.", romaji: "Suki na kisetsu." }, { jp: "雨の 季節。", en: "Rainy season.", romaji: "Ame no kisetsu." }] },
      { japanese: "梅雨", romaji: "tsuyu", english: "Rainy season", examples: [{ jp: "梅雨が 始まる。", en: "Rainy season starts.", romaji: "Tsuyu ga hajimaru." }, { jp: "梅雨 明け。", en: "End of rainy season.", romaji: "Tsuyu ake." }] },
      { japanese: "空", romaji: "sora", english: "Sky", examples: [{ jp: "夕焼けの 空。", en: "Sunset sky.", romaji: "Yuuyake no sora." }, { jp: "夜空。", en: "Night sky.", romaji: "Yozora." }] },
      { japanese: "星", romaji: "hoshi", english: "Star", examples: [{ jp: "流れ星。", en: "Shooting star.", romaji: "Nagareboshi." }, { jp: "星が きれいだ。", en: "Stars are beautiful.", romaji: "Hoshi ga kirei da." }] },
      { japanese: "太陽", romaji: "taiyou", english: "Sun", examples: [{ jp: "太陽が 眩しい。", en: "Sun is dazzling.", romaji: "Taiyou ga mabushii." }, { jp: "太陽の 光。", en: "Sunlight.", romaji: "Taiyou no hikari." }] },
      { japanese: "地球", romaji: "chikyuu", english: "Earth", examples: [{ jp: "地球を 守る。", en: "Protect the earth.", romaji: "Chikyuu wo mamoru." }, { jp: "青い 地球。", en: "Blue earth.", romaji: "Aoi chikyuu." }] }
    ]
  },
  {
    id: 38,
    level: "N4",
    title: "Transport & Commute",
    description: "Vocabulary for travel and daily commuting",
    words: [
      { japanese: "交通", romaji: "koutsuu", english: "Traffic/Transport", examples: [{ jp: "交通が 便利だ。", en: "Transport is convenient.", romaji: "Koutsuu ga benri da." }, { jp: "交通 手段。", en: "Means of transport.", romaji: "Koutsuu shudan." }] },
      { japanese: "通勤する", romaji: "tsuukinsuru", english: "To commute to work", examples: [{ jp: "電車で 通勤する。", en: "Commute by train.", romaji: "Densha de tsuukinsuru." }, { jp: "一時間 通勤。", en: "1 hour commute.", romaji: "Ichijikan tsuukin." }] },
      { japanese: "通学する", romaji: "tsuugakusuru", english: "To commute to school", examples: [{ jp: "自転車で 通学する。", en: "Commute by bike.", romaji: "Jitensha de tsuugakusuru." }, { jp: "通学路。", en: "School route.", romaji: "Tsuugakuro." }] },
      { japanese: "乗り換える", romaji: "norikaeru", english: "To transfer", examples: [{ jp: "新宿で 乗り換える。", en: "Transfer at Shinjuku.", romaji: "Shinjuku de norikaeru." }, { jp: "バスに 乗り換える。", en: "Change to a bus.", romaji: "Basu ni norikaeru." }] },
      { japanese: "降りる", romaji: "oriru", english: "To get off", examples: [{ jp: "駅で 降りる。", en: "Get off at station.", romaji: "Eki de oriru." }, { jp: "階段を 降りる。", en: "Go down stairs.", romaji: "Kaidan wo oriru." }] },
      { japanese: "乗る", romaji: "noru", english: "To ride/get on", examples: [{ jp: "タクシーに 乗る。", en: "Take a taxi.", romaji: "Takushii ni noru." }, { jp: "波に 乗る。", en: "Ride the wave.", romaji: "Nami ni noru." }] },
      { japanese: "間に合う", romaji: "maniau", english: "To be in time", examples: [{ jp: "電車に 間に合う。", en: "Make the train.", romaji: "Densha ni maniau." }, { jp: "五時に 間に合う。", en: "Be in time for 5:00.", romaji: "Goji ni maniau." }] },
      { japanese: "遅れる", romaji: "okureru", english: "To be late", examples: [{ jp: "バスが 遅れた。", en: "Bus was late.", romaji: "Basu ga okureta." }, { jp: "時間に 遅れる。", en: "Be late for time.", romaji: "Jikan ni okureru." }] },
      { japanese: "急ぐ", romaji: "isogu", english: "To hurry", examples: [{ jp: "駅まで 急ぐ。", en: "Hurry to station.", romaji: "Eki made isogu." }, { jp: "急いで ください。", en: "Please hurry.", romaji: "Isoide kudasai." }] },
      { japanese: "運転する", romaji: "untensuru", english: "To drive", examples: [{ jp: "車を 運転する。", en: "Drive a car.", romaji: "Kuruma wo untensuru." }, { jp: "安全 運転。", en: "Safe driving.", romaji: "Anzen unten." }] },
      { japanese: "渋滞する", romaji: "juutaishuru", english: "To be congested", examples: [{ jp: "道が 渋滞している。", en: "Road is jammed.", romaji: "Michi ga juutaishiteiru." }, { jp: "交通 渋滞。", en: "Traffic jam.", romaji: "Koutsuu juutai." }] },
      { japanese: "事故", romaji: "jiko", english: "Accident", examples: [{ jp: "交通事故。", en: "Traffic accident.", romaji: "Koutsuu jiko." }, { jp: "事故に 気をつける。", en: "Watch out for accidents.", romaji: "Jiko ni ki wo tsukeru." }] },
      { japanese: "料金", romaji: "ryoukin", english: "Fare/Fee", examples: [{ jp: "電車の 料金。", en: "Train fare.", romaji: "Densha no ryoukin." }, { jp: "料金を 払う。", en: "Pay the fee.", romaji: "Ryoukin wo harau." }] },
      { japanese: "片道", romaji: "katamichi", english: "One-way", examples: [{ jp: "片道 切符。", en: "One-way ticket.", romaji: "Katamichi kippu." }, { jp: "片道 一時間。", en: "1 hr one-way.", romaji: "Katamichi ichijikan." }] },
      { japanese: "往復", romaji: "oufuku", english: "Round trip", examples: [{ jp: "往復で 買う。", en: "Buy round trip.", romaji: "Oufuku de kau." }, { jp: "学校と家の往復。", en: "Back and forth between school and home.", romaji: "Gakkou to ie no oufuku." }] },
      { japanese: "特急", romaji: "tokkyuu", english: "Limited express", examples: [{ jp: "特急に 乗る。", en: "Take limited express.", romaji: "Tokkyuu ni noru." }, { jp: "特急 券。", en: "Express ticket.", romaji: "Tokkyuuken." }] },
      { japanese: "急行", romaji: "kyuukou", english: "Express", examples: [{ jp: "急行 電車。", en: "Express train.", romaji: "Kyuukou densha." }, { jp: "次は 急行。", en: "Next is express.", romaji: "Tsugi wa kyuukou." }] },
      { japanese: "普通", romaji: "futsuu", english: "Local/Regular", examples: [{ jp: "普通 列車。", en: "Local train.", romaji: "Futsuu ressha." }, { jp: "普通に 行く。", en: "Go normally.", romaji: "Futsuu ni iku." }] },
      { japanese: "時刻表", romaji: "jikokuhyou", english: "Timetable", examples: [{ jp: "時刻表を 見る。", en: "Check timetable.", romaji: "Jikokuhyou wo miru." }, { jp: "バスの 時刻表。", en: "Bus timetable.", romaji: "Basu no jikokuhyou." }] },
      { japanese: "定期券", romaji: "teikiken", english: "Commuter pass", examples: [{ jp: "定期券を 買う。", en: "Buy a pass.", romaji: "Teikiken wo kau." }, { jp: "六ヶ月の 定期。", en: "6-month pass.", romaji: "Rokkagetsu no teiki." }] },
      { japanese: "出口", romaji: "deguchi", english: "Exit", examples: [{ jp: "北口の 出口。", en: "North exit.", romaji: "Kitaguchi no deguchi." }, { jp: "出口は どこ？", en: "Where is the exit?", romaji: "Deguchi wa doko?" }] },
      { japanese: "入り口", romaji: "iriguchi", english: "Entrance", examples: [{ jp: "入り口で 待つ。", en: "Wait at entrance.", romaji: "Iriguchi de matsu." }, { jp: "地下の 入り口。", en: "Subway entrance.", romaji: "Chika no iriguchi." }] },
      { japanese: "ホーム", romaji: "hoomu", english: "Platform", examples: [{ jp: "ホームで 待つ。", en: "Wait on platform.", romaji: "Hoomu de matsu." }, { jp: "一番 ホーム。", en: "Platform 1.", romaji: "Ichiban hoomu." }] },
      { japanese: "切符", romaji: "kippu", english: "Ticket", examples: [{ jp: "切符を 失くした。", en: "Lost the ticket.", romaji: "Kippu wo nakushita." }, { jp: "切符 売り場。", en: "Ticket counter.", romaji: "Kippu uriba." }] },
      { japanese: "踏切", romaji: "fumikiri", english: "Railroad crossing", examples: [{ jp: "踏切を 渡る。", en: "Cross the track.", romaji: "Fumikiri wo wataru." }, { jp: "踏切が 鳴る。", en: "Gate alarm goes off.", romaji: "Fumikiri ga naru." }] },
      { japanese: "通過する", romaji: "tsuuka suru", english: "To pass through", examples: [{ jp: "駅を 通過する。", en: "Pass through station.", romaji: "Eki wo tsuuka suru." }, { jp: "台風が 通過した。", en: "Typhoon passed.", romaji: "Taifuu ga tsuukashita." }] },
      { japanese: "停車する", romaji: "teisha suru", english: "To stop (vehicle)", examples: [{ jp: "バスが 停車する。", en: "Bus stops.", romaji: "Basu ga teisha suru." }, { jp: "一時 停車。", en: "Temporary stop.", romaji: "Ichiji teisha." }] },
      { japanese: "出発する", romaji: "shuppatsu suru", english: "To depart", examples: [{ jp: "十時に 出発する。", en: "Depart at 10.", romaji: "Juuji ni shuppatsu suru." }, { jp: "出発 おめでとう。", en: "Congrats on departure.", romaji: "Shuppatsu omedetou." }] },
      { japanese: "到着する", romaji: "touchaku suru", english: "To arrive", examples: [{ jp: "空港に 到着する。", en: "Arrive at airport.", romaji: "Kuukou ni touchaku suru." }, { jp: "到着 時間。", en: "Arrival time.", romaji: "Touchaku jikan." }] },
      { japanese: "予約する", romaji: "yoyaku suru", english: "To book", examples: [{ jp: "タクシーを 予約する。", en: "Book a taxi.", romaji: "Takushii wo yoyaku suru." }, { jp: "席を 予約。", en: "Reserve a seat.", romaji: "Seki no yoyaku." }] }
    ]
  },
  {
    id: 39,
    level: "N4",
    title: "Lifestyle & Daily Life",
    description: "Vocabulary for habits, life, and personal care",
    words: [
      { japanese: "生活", romaji: "seikatsu", english: "Life/Lifestyle", examples: [{ jp: "日本の 生活。", en: "Life in Japan.", romaji: "Nihon no seikatsu." }, { jp: "生活を 送る。", en: "Lead a life.", romaji: "Seikatsu wo okuru." }] },
      { japanese: "習慣", romaji: "shuukan", english: "Habit/Custom", examples: [{ jp: "毎朝の 習慣。", en: "Morning habit.", romaji: "Maiasa no shuukan." }, { jp: "日本の 習慣。", en: "Japanese custom.", romaji: "Nihon no shuukan." }] },
      { japanese: "経験", romaji: "keiken", english: "Experience", examples: [{ jp: "良い 経験。", en: "Good experience.", romaji: "Ii keiken." }, { jp: "経験が ある。", en: "Have experience.", romaji: "Keiken ga aru." }] },
      { japanese: "準備", romaji: "junbi", english: "Preparation", examples: [{ jp: "食事の 準備。", en: "Meal prep.", romaji: "Shokuji no junbi." }, { jp: "準備 万端。", en: "All set.", romaji: "Junbi bantan." }] },
      { japanese: "片付ける", romaji: "katazukeru", english: "To tidy up", examples: [{ jp: "机を 片付ける。", en: "Tidy the desk.", romaji: "Tsukue wo katazukeru." }, { jp: "後で 片付ける。", en: "Tidy up later.", romaji: "Ato de katazukeru." }] },
      { japanese: "掃除", romaji: "souji", english: "Cleaning", examples: [{ jp: "部屋の 掃除。", en: "Room cleaning.", romaji: "Heya no souji." }, { jp: "大 掃除。", en: "Grand cleaning.", romaji: "Oo souji." }] },
      { japanese: "洗濯", romaji: "sentaku", english: "Laundry", examples: [{ jp: "洗濯を する。", en: "Do laundry.", romaji: "Sentaku wo suru." }, { jp: "洗濯 物。", en: "Laundry items.", romaji: "Sentaku mono." }] },
      { japanese: "料理", romaji: "ryouri", english: "Cooking", examples: [{ jp: "料理が 上手だ。", en: "Good at cooking.", romaji: "Ryouri ga jouzu da." }, { jp: "家庭 料理。", en: "Home cooking.", romaji: "Katei ryouri." }] },
      { japanese: "買い物", romaji: "kaimono", english: "Shopping", examples: [{ jp: "買い物に 行く。", en: "Go shopping.", romaji: "Kaimono ni iku." }, { jp: "特売で 買い物。", en: "Shop at a sale.", romaji: "Tokubai de kaimono." }] },
      { japanese: "散歩", romaji: "sanpo", english: "Walk/Stroll", examples: [{ jp: "朝の 散歩。", en: "Morning walk.", romaji: "Asa no sanpo." }, { jp: "犬の 散歩。", en: "Dog walk.", romaji: "Inu no sanpo." }] },
      { japanese: "趣味", romaji: "shumi", english: "Hobby", examples: [{ jp: "無 趣味。", en: "No hobbies.", romaji: "Mu shumi." }, { jp: "共通の 趣味。", en: "Common hobby.", romaji: "Kyuutuu no shumi." }] },
      { japanese: "読書", romaji: "dokusho", english: "Reading", examples: [{ jp: "読書を 楽しむ。", en: "Enjoy reading.", romaji: "Dokusho wo tanoshimu." }, { jp: "秋は 読書。", en: "Autumn is for reading.", romaji: "Aki wa dokusho." }] },
      { japanese: "旅行", romaji: "ryokou", english: "Trip/Travel", examples: [{ jp: "一人 旅。", en: "Solo trip.", romaji: "Hitori tabi." }, { jp: "新婚 旅行。", en: "Honeymoon.", romaji: "Shinkon ryokou." }] },
      { japanese: "遊び", romaji: "asobi", english: "Play/Entertainment", examples: [{ jp: "遊びに 来る。", en: "Come to play.", romaji: "Asobi ni kuru." }, { jp: "水 遊び。", en: "Playing with water.", romaji: "Mizu asobi." }] },
      { japanese: "昼寝", romaji: "hirune", english: "Nap", examples: [{ jp: "昼寝を する。", en: "Take a nap.", romaji: "Hirune wo suru." }, { jp: "気持ちいい 昼寝。", en: "Pleasant nap.", romaji: "Kimochi ii hirune." }] },
      { japanese: "食事", romaji: "shokuji", english: "Meal", examples: [{ jp: "三食の 食事。", en: "3 meals a day.", romaji: "Sanshoku no shokuji." }, { jp: "外食。", en: "Eating out.", romaji: "Gaishoku." }] },
      { japanese: "外食", romaji: "gaishoku", english: "Eating out", examples: [{ jp: "たまに 外食する。", en: "Occasionally eat out.", romaji: "Tamani gaishoku suru." }, { jp: "外食が 多い。", en: "Eat out a lot.", romaji: "Gaishoku ga ooi." }] },
      { japanese: "お風呂", romaji: "ofuro", english: "Bath", examples: [{ jp: "お風呂に 入る。", en: "Take a bath.", romaji: "Ofuro ni hairu." }, { jp: "お風呂場。", en: "Bathroom.", romaji: "Ofuro ba." }] },
      { japanese: "石鹸", romaji: "sekken", english: "Soap", examples: [{ jp: "石鹸で 洗う。", en: "Wash with soap.", romaji: "Sekken de arau." }, { jp: "いい 匂いの石鹸。", en: "Good smelling soap.", romaji: "Ii nioi no sekken." }] },
      { japanese: "シャンプー", romaji: "shanpuu", english: "Shampoo", examples: [{ jp: "シャンプーを 買う。", en: "Buy shampoo.", romaji: "Shanpuu wo kau." }, { jp: "リンスと シャンプー。", en: "Conditioner and shampoo.", romaji: "Rinsu to shanpuu." }] },
      { japanese: "タオル", romaji: "taoru", english: "Towel", examples: [{ jp: "タオルで 拭く。", en: "Wipe with a towel.", romaji: "Taoru de fuku." }, { jp: "バスタオル。", en: "Bath towel.", romaji: "Basutaoru." }] },
      { japanese: "歯磨き", romaji: "hamigaki", english: "Brushing teeth", examples: [{ jp: "歯磨きを する。", en: "Brush teeth.", romaji: "Hamigaki wo suru." }, { jp: "歯磨き 粉。", en: "Toothpaste.", romaji: "Hamigakiko." }] },
      { japanese: "鏡", romaji: "kagami", english: "Mirror", examples: [{ jp: "鏡を 見る。", en: "Look in the mirror.", romaji: "Kagami wo miru." }, { jp: "手 鏡。", en: "Hand mirror.", romaji: "Te kagami." }] },
      { japanese: "化粧", romaji: "keshou", english: "Makeup", examples: [{ jp: "お化粧を する。", en: "Apply makeup.", romaji: "O keshou wo suru." }, { jp: "化粧室。", en: "Restroom (makeup room).", romaji: "Keshoushitsu." }] },
      { japanese: "髭剃り", romaji: "higesori", english: "Shaving", examples: [{ jp: "髭を 剃る。", en: "Shave a beard.", romaji: "Hige wo soru." }, { jp: "電気 髭剃り。", en: "Electric razor.", romaji: "Denki higesori." }] },
      { japanese: "美容院", romaji: "byouin", english: "Beauty salon", examples: [{ jp: "美容院へ 行く。", en: "Go to the salon.", romaji: "Byouin e iku." }, { jp: "美容師。", en: "Beautician.", romaji: "Byoushi." }] },
      { japanese: "理髪店", romaji: "rihatsuten", english: "Barber shop", examples: [{ jp: "床屋へ 行く。", en: "Go to the barber (casual).", romaji: "Tokoya e iku." }, { jp: "理髪店を 探す。", en: "Look for a barber.", romaji: "Rihatsuten wo sagasu." }] },
      { japanese: "服", romaji: "fuku", english: "Clothes", examples: [{ jp: "服を 選ぶ。", en: "Choose clothes.", romaji: "Fuku wo erabu." }, { jp: "服を 着る。", en: "Wear clothes.", romaji: "Fuku wo kiru." }] },
      { japanese: "着替える", romaji: "kigaeru", english: "To change clothes", examples: [{ jp: "パジャマに 着替える。", en: "Change into PJs.", romaji: "Pajama ni kigaeru." }, { jp: "早く 着替えて。", en: "Change quickly.", romaji: "Hayaku kigaete." }] },
      { japanese: "脱ぐ", romaji: "nugu", english: "To take off (clothes)", examples: [{ jp: "靴を 脱ぐ。", en: "Take off shoes.", romaji: "Kutsu wo nugu." }, { jp: "上着を 脱ぐ。", en: "Take off jacket.", romaji: "Uwagi wo nugu." }] }
    ]
  },
  {
    id: 40,
    level: "N4",
    title: "Education & Learning",
    description: "School life, subjects, and study vocabulary",
    words: [
      { japanese: "教育", romaji: "kyouiku", english: "Education", examples: [{ jp: "英才 教育。", en: "Gifted education.", romaji: "Eisai kyouiku." }, { jp: "義務 教育。", en: "Compulsory education.", romaji: "Gimu kyouiku." }] },
      { japanese: "学校", romaji: "gakkou", english: "School", examples: [{ jp: "名門 学校。", en: "Prestigious school.", romaji: "Meimon gakkou." }, { jp: "学校を 休む。", en: "Absent from school.", romaji: "Gakkou wo yasumu." }] },
      { japanese: "大学", romaji: "daigaku", english: "University", examples: [{ jp: "国立 大学。", en: "National university.", romaji: "Kokuritsu daigaku." }, { jp: "大学に 合格する。", en: "Pass university exam.", romaji: "Daigaku ni goukakusuru." }] },
      { japanese: "専門学校", romaji: "senmongakkou", english: "Vocational school", examples: [{ jp: "料理の 専門学校。", en: "Vocational cooking school.", romaji: "Ryouri no senmongakkou." }, { jp: "専門学校に 通う。", en: "Attend vocational school.", romaji: "Senmongakkou ni kayou." }] },
      { japanese: "学部", romaji: "gakubu", english: "Faculty/Department", examples: [{ jp: "法 学部。", en: "Faculty of law.", romaji: "Hou gakubu." }, { jp: "文学部。", en: "Faculty of literature.", romaji: "Bungakubu." }] },
      { japanese: "専門", romaji: "senmon", english: "Major/Specialty", examples: [{ jp: "専門は 経済です。", en: "My major is economics.", romaji: "Senmon wa keizai desu." }, { jp: "専門 知識。", en: "Specialized knowledge.", romaji: "Senmon chishiki." }] },
      { japanese: "教授", romaji: "kyouju", english: "Professor", examples: [{ jp: "大学の 教授。", en: "Uni professor.", romaji: "Daigaku no kyouju." }, { jp: "有名な 教授。", en: "Famous professor.", romaji: "Yuumeina kyouju." }] },
      { japanese: "学生", romaji: "gakusei", english: "Student", examples: [{ jp: "留学生。", en: "Intl student.", romaji: "Ryuugakusei." }, { jp: "真面目な 学生。", en: "Serious student.", romaji: "Majimena gakusei." }] },
      { japanese: "講義", romaji: "kougi", english: "Lecture", examples: [{ jp: "講義を 聞く。", en: "Listen to a lecture.", romaji: "Kougi wo kiku." }, { jp: "面白い 講義。", en: "Interesting lecture.", romaji: "Omoshiroi kougi." }] },
      { japanese: "授業", romaji: "jugyou", english: "Class", examples: [{ jp: "授業に 遅れる。", en: "Be late for class.", romaji: "Jugyou ni okureru." }, { jp: "楽しい 授業。", en: "Fun class.", romaji: "Tanoshii jugyou." }] },
      { japanese: "教科書", romaji: "kyoukasho", english: "Textbook", examples: [{ jp: "教科書を 開ける。", en: "Open the textbook.", romaji: "Kyoukasho wo akeru." }, { jp: "新しい 教科書。", en: "New textbook.", romaji: "Atarashii kyoukasho." }] },
      { japanese: "試験", romaji: "shiken", english: "Exam", examples: [{ jp: "試験に 落ちる。", en: "Fail an exam.", romaji: "Shiken ni ochiru." }, { jp: "試験を 受ける。", en: "Take an exam.", romaji: "Shiken wo ukeru." }] },
      { japanese: "成績", romaji: "seiseki", english: "Grades", examples: [{ jp: "成績が 良い。", en: "Good grades.", romaji: "Seiseki ga ii." }, { jp: "成績を 上げる。", en: "Improve grades.", romaji: "Seiseki wo ageru." }] },
      { japanese: "合格する", romaji: "goukakusuru", english: "To pass", examples: [{ jp: "試験に 合格した。", en: "Passed the exam.", romaji: "Shiken ni goukakushita." }, { jp: "合格 おめでとう。", en: "Congrats on passing.", romaji: "Goukaku omedetou." }] },
      { japanese: "不合格", romaji: "fugoukaku", english: "Failure (exam)", examples: [{ jp: "不合格に なる。", en: "Fail (the exam).", romaji: "Fugoukaku ni naru." }, { jp: "不合格の 通知。", en: "Failure notification.", romaji: "Fugoukaku no tsuuchi." }] },
      { japanese: "宿題", romaji: "shukudai", english: "Homework", examples: [{ jp: "宿題を 忘れる。", en: "Forget homework.", romaji: "Shukudai wo wasureru." }, { jp: "宿題が 多い。", en: "Lots of homework.", romaji: "Shukudai ga ooi." }] },
      { japanese: "図書館", romaji: "toshokan", english: "Library", examples: [{ jp: "図書館で 借りる。", en: "Borrow from library.", romaji: "Toshokan de kariru." }, { jp: "近くの 図書館。", en: "Nearby library.", romaji: "Chikaku no toshokan." }] },
      { japanese: "勉強する", romaji: "benkyousuru", english: "To study", examples: [{ jp: "一生懸命 勉強する。", en: "Study hard.", romaji: "Isshoukenmei benkyousuru." }, { jp: "一緒に 勉強しよう。", en: "Let's study together.", romaji: "Isshoni benkyou shiyou." }] },
      { japanese: "予習する", romaji: "yoshuusuru", english: "To prepare (lessons)", examples: [{ jp: "予習を 欠かさない。", en: "Never skip preparation.", romaji: "Yoshuu wo kakasanai." }, { jp: "明日の 予習。", en: "Prep for tomorrow.", romaji: "Ashita no yoshuu." }] },
      { japanese: "復習する", romaji: "fukushuushuru", english: "To review", examples: [{ jp: "習ったことを復習する。", en: "Review what was learned.", romaji: "Naratta koto wo fukushuushuru." }, { jp: "復習が 大切だ。", en: "Review is important.", romaji: "Fukushuu ga taisetsu da." }] },
      { japanese: "奨学金", romaji: "shougakukin", english: "Scholarship", examples: [{ jp: "奨学金を もらう。", en: "Get a scholarship.", romaji: "Shougakukin wo morau." }, { jp: "奨学金 制度。", en: "Scholarship system.", romaji: "Shougakukin seido." }] },
      { japanese: "入学", romaji: "nyuugaku", english: "Enrollment", examples: [{ jp: "入学 式。", en: "Entrance ceremony.", romaji: "Nyuugaku shiki." }, { jp: "入学 おめでとう。", en: "Congrats on enrollment.", romaji: "Nyuugaku omedetou." }] },
      { japanese: "卒業", romaji: "sotsugyou", english: "Graduation", examples: [{ jp: "大学を 卒業する。", en: "Graduate from uni.", romaji: "Daigaku wo sotsugyousuru." }, { jp: "卒業 証書。", en: "Diploma.", romaji: "Sotsugyou shousho." }] },
      { japanese: "歴史", romaji: "rekishi", english: "History", examples: [{ jp: "日本の 歴史。", en: "Japanese history.", romaji: "Nihon no rekishi." }, { jp: "歴史的な 建物。", en: "Historical building.", romaji: "Rekishitekina tatemono." }] },
      { japanese: "地理", romaji: "chiri", english: "Geography", examples: [{ jp: "世界の 地理。", en: "World geography.", romaji: "Sekai no chiri." }, { jp: "地理に 詳しい。", en: "Know geography well.", romaji: "Chiri ni kuwashii." }] },
      { japanese: "数学", romaji: "suugaku", english: "Math", examples: [{ jp: "数学が 苦手だ。", en: "Bad at math.", romaji: "Suugaku ga nigate da." }, { jp: "難しい 数学。", en: "Difficult math.", romaji: "Muzukashii suugaku." }] },
      { japanese: "理科", romaji: "rika", english: "Science", examples: [{ jp: "理科の 実験。", en: "Science experiment.", romaji: "Rika no jikken." }, { jp: "理科が 好き。", en: "Like science.", romaji: "Rika ga suki." }] },
      { japanese: "芸術", romaji: "geijutsu", english: "Art/Fine arts", examples: [{ jp: "現代 芸術。", en: "Modern art.", romaji: "Gendai geijutsu." }, { jp: "芸術家。", en: "Artist.", romaji: "Geijutsuka." }] },
      { japanese: "文学", romaji: "bungaku", english: "Literature", examples: [{ jp: "日本 文学。", en: "Japanese literature.", romaji: "Nihon bungaku." }, { jp: "古典 文学。", en: "Classic literature.", romaji: "Koten bungaku." }] },
      { japanese: "知識", romaji: "chishiki", english: "Knowledge", examples: [{ jp: "知識を 深める。", en: "Deepen knowledge.", romaji: "Chishiki wo fukameru." }, { jp: "豊富な 知識。", en: "Abundant knowledge.", romaji: "Houfuna chishiki." }] }
    ]
  }
];
