export const chunk7 = [
  {
    id: 31,
    level: "N4",
    title: "Cooking & Kitchen",
    description: "Verbs and nouns for cooking and kitchen items",
    words: [
      { japanese: "台所", romaji: "daidokoro", english: "Kitchen", examples: [{ jp: "台所で 料理する。", en: "Cook in the kitchen.", romaji: "Daidokoro de ryourisuru." }, { jp: "広い 台所。", en: "Spacious kitchen.", romaji: "Hiroi daidokoro." }] },
      { japanese: "包丁", romaji: "houchou", english: "Kitchen knife", examples: [{ jp: "包丁を 使う。", en: "Use a knife.", romaji: "Houchou wo tsukau." }, { jp: "包丁で 切る。", en: "Cut with a knife.", romaji: "Houchou de kiru." }] },
      { japanese: "鍋", romaji: "nabe", english: "Pot/Pan", examples: [{ jp: "鍋で 水を沸かす。", en: "Boil water in a pot.", romaji: "Nabe de mizu wo wakasu." }, { jp: "土鍋。", en: "Earthenware pot.", romaji: "Donabe." }] },
      { japanese: "フライパン", romaji: "furaipan", english: "Frying pan", examples: [{ jp: "フライパンで 炒める。", en: "Fry in a frying pan.", romaji: "Furaipan de itameru." }, { jp: "新しい フライパン。", en: "New frying pan.", romaji: "Atarashii furaipan." }] },
      { japanese: "冷蔵庫", romaji: "reizouko", english: "Refrigerator", examples: [{ jp: "冷蔵庫に 入れる。", en: "Put in the fridge.", romaji: "Reizouko ni ireru." }, { jp: "冷蔵庫を 整理する。", en: "Organize the fridge.", romaji: "Reizouko wo seirisuru." }] },
      { japanese: "焼く", romaji: "yaku", english: "To bake/grill", examples: [{ jp: "肉を 焼く。", en: "Grill meat.", romaji: "Niku wo yaku." }, { jp: "パンを 焼く。", en: "Bake bread.", romaji: "Pan wo yaku." }] },
      { japanese: "煮る", romaji: "niru", english: "To boil/stew", examples: [{ jp: "野菜を 煮る。", en: "Stew vegetables.", romaji: "Yasai wo niru." }, { jp: "魚を 煮る。", en: "Boil fish.", romaji: "Sakana wo niru." }] },
      { japanese: "炒める", romaji: "itameru", english: "To stir-fry", examples: [{ jp: "卵を 炒める。", en: "Scramble eggs.", romaji: "Tamago wo itameru." }, { jp: "強火で 炒める。", en: "Fry on high heat.", romaji: "Tsuyobi de itameru." }] },
      { japanese: "茹でる", romaji: "yuderu", english: "To boil (water)", examples: [{ jp: "パスタを 茹でる。", en: "Boil pasta.", romaji: "Pasuta wo yuderu." }, { jp: "卵を 茹でる。", en: "Boil an egg.", romaji: "Tamago wo yuderu." }] },
      { japanese: "切る", romaji: "kiru", english: "To cut", examples: [{ jp: "細かく 切る。", en: "Cut finely.", romaji: "Komakaku kiru." }, { jp: "一口サイズに 切る。", en: "Cut into bite sizes.", romaji: "Hitokuchisaizu ni kiru." }] },
      { japanese: "混ぜる", romaji: "mazeru", english: "To mix", examples: [{ jp: "よく 混ぜる。", en: "Mix well.", romaji: "Yoku mazeru." }, { jp: "砂糖を 混ぜる。", en: "Mix in sugar.", romaji: "Satou wo mazeru." }] },
      { japanese: "味見する", romaji: "ajimisuru", english: "To taste", examples: [{ jp: "味見して ください。", en: "Please taste it.", romaji: "Ajimishite kudasai." }, { jp: "味見に 行く。", en: "Go to taste-test.", romaji: "Ajimi ni iku." }] },
      { japanese: "調味料", romaji: "choumiryou", english: "Seasoning", examples: [{ jp: "調味料を 入れる。", en: "Add seasoning.", romaji: "Choumiryou wo ireru." }, { jp: "色々な 調味料。", en: "Various seasonings.", romaji: "Iroirona choumiryou." }] },
      { japanese: "塩", romaji: "shio", english: "Salt", examples: [{ jp: "塩を 少々。", en: "A pinch of salt.", romaji: "Shio wo shoushou." }, { jp: "塩辛い。", en: "Salty.", romaji: "Shiokarai." }] },
      { japanese: "砂糖", romaji: "satou", english: "Sugar", examples: [{ jp: "砂糖を 控える。", en: "Cut down on sugar.", romaji: "Satou wo hikaeru." }, { jp: "甘い 砂糖。", en: "Sweet sugar.", romaji: "Amai satou." }] },
      { japanese: "醤油", romaji: "shouyu", english: "Soy sauce", examples: [{ jp: "醤油を かける。", en: "Pour soy sauce.", romaji: "Shouyu wo kakeru." }, { jp: "醤油の 匂い。", en: "Smell of soy sauce.", romaji: "Shouyu no nioi." }] },
      { japanese: "味噌", romaji: "miso", english: "Miso", examples: [{ jp: "味噌汁を 作る。", en: "Make miso soup.", romaji: "Misoshiru wo tsukuru." }, { jp: "赤味噌。", en: "Red miso.", romaji: "Akamiso." }] },
      { japanese: "胡椒", romaji: "koshou", english: "Pepper", examples: [{ jp: "胡椒を 振る。", en: "Sprinkle pepper.", romaji: "Koshou wo furu." }, { jp: "塩 胡椒。", en: "Salt and pepper.", romaji: "Shio koshou." }] },
      { japanese: "皿", romaji: "sara", english: "Plate/Dish", examples: [{ jp: "皿を 並べる。", en: "Line up plates.", romaji: "Sara wo naraberu." }, { jp: "皿を 洗う。", en: "Wash dishes.", romaji: "Sara wo arau." }] },
      { japanese: "茶碗", romaji: "chawan", english: "Rice bowl", examples: [{ jp: "茶碗に ご飯。", en: "Rice in a bowl.", romaji: "Chawan ni gohan." }, { jp: "割れた 茶碗。", en: "Broken bowl.", romaji: "Wareta chawan." }] },
      { japanese: "箸", romaji: "hashi", english: "Chopsticks", examples: [{ jp: "箸を 使う。", en: "Use chopsticks.", romaji: "Hashi wo tsukau." }, { jp: "箸置き。", en: "Chopstick rest.", romaji: "Hashioki." }] },
      { japanese: "コップ", romaji: "koppu", english: "Cup/Glass", examples: [{ jp: "コップに 注ぐ。", en: "Pour into a cup.", romaji: "Koppu ni sosogu." }, { jp: "プラスチックの コップ。", en: "Plastic cup.", romaji: "Purasuchikku no koppu." }] },
      { japanese: "沸かす", romaji: "wakasu", english: "To boil (liquid)", examples: [{ jp: "お湯を 沸かす。", en: "Boil water.", romaji: "Oyu wo wakasu." }, { jp: "風呂を 沸かす。", en: "Prepare the bath.", romaji: "Furo wo wakasu." }] },
      { japanese: "片付ける", romaji: "katazukeru", english: "To tidy up", examples: [{ jp: "台所を 片付ける。", en: "Tidy up the kitchen.", romaji: "Daikodoro wo katazukeru." }, { jp: "部屋を 片付ける。", en: "Organize the room.", romaji: "Heya wo katazukeru." }] },
      { japanese: "温める", romaji: "atatameru", english: "To warm up", examples: [{ jp: "電子レンジで 温める。", en: "Warm in microwave.", romaji: "Denshirenji de atatameru." }, { jp: "スープを 温める。", en: "Warm the soup.", romaji: "Suupu wo atatameru." }] },
      { japanese: "冷やす", romaji: "hiyasu", english: "To cool down", examples: [{ jp: "ビールを 冷やす。", en: "Chill beer.", romaji: "Biiru wo hiyasu." }, { jp: "頭を 冷やす。", en: "Cool off (one's head).", romaji: "Atama wo hiyasu." }] },
      { japanese: "剥く", romaji: "muku", english: "To peel", examples: [{ jp: "皮を 剥く。", en: "Peel the skin.", romaji: "Kawa wo muku." }, { jp: "りんごの 皮を剥く。", en: "Peel an apple.", romaji: "Ringo no kawa wo muku." }] },
      { japanese: "量る", romaji: "hakaru", english: "To measure", examples: [{ jp: "重さを 量る。", en: "Measure weight.", romaji: "Omosa wo hakaru." }, { jp: "水二百ミリ 量る。", en: "Measure 200ml water.", romaji: "Mizu nihyakumiri hakaru." }] },
      { japanese: "手伝う", romaji: "tetsudau", english: "To help", examples: [{ jp: "夕食を 手伝う。", en: "Help with dinner.", romaji: "Yuushoku wo tetsudau." }, { jp: "母を 手伝う。", en: "Help my mother.", romaji: "Haha wo tetsudau." }] },
      { japanese: "エプロン", romaji: "epuron", english: "Apron", examples: [{ jp: "エプロンを する。", en: "Put on an apron.", romaji: "Epuron wo suru." }, { jp: "料理用 エプロン。", en: "Cooking apron.", romaji: "Ryouriyou epuron." }] }
    ]
  },
  {
    id: 32,
    level: "N4",
    title: "Office & Meetings",
    description: "Business and workplace vocabulary",
    words: [
      { japanese: "会議", romaji: "kaigi", english: "Meeting/Conference", examples: [{ jp: "会議に 出席する。", en: "Attend a meeting.", romaji: "Kaigi ni shusseki suru." }, { jp: "会議を 始める。", en: "Start the meeting.", romaji: "Kaigi wo hajimeru." }] },
      { japanese: "資料", romaji: "shiryou", english: "Documents/Materials", examples: [{ jp: "資料を 作る。", en: "Prepare documents.", romaji: "Shiryou wo tsukuru." }, { jp: "会議の 資料。", en: "Meeting materials.", romaji: "Kaigi no shiryou." }] },
      { japanese: "連絡", romaji: "renraku", english: "Contact/Communication", examples: [{ jp: "後で 連絡する。", en: "Contact later.", romaji: "Ato de renraku suru." }, { jp: "連絡を 待つ。", en: "Wait for contact.", romaji: "Renraku wo matsu." }] },
      { japanese: "報告", romaji: "houkoku", english: "Report", examples: [{ jp: "結果を 報告する。", en: "Report the results.", romaji: "Kekka wo houkoku suru." }, { jp: "報告書。", en: "Report paper.", romaji: "Houkokusho." }] },
      { japanese: "相談", romaji: "soudan", english: "Consultation/Discussion", examples: [{ jp: "上司に 相談する。", en: "Consult with a boss.", romaji: "Joushi ni soudan suru." }, { jp: "何でも 相談して。", en: "Discuss anything.", romaji: "Nandemo soudanshite." }] },
      { japanese: "予定", romaji: "yotei", english: "Schedule/Plan", examples: [{ jp: "予定を 立てる。", en: "Make a schedule.", romaji: "Yotei wo tateru." }, { jp: "明日の 予定。", en: "Tomorrow's schedule.", romaji: "Ashita no yotei." }] },
      { japanese: "準備", romaji: "junbi", english: "Preparation", examples: [{ jp: "旅行の 準備。", en: "Trip prep.", romaji: "Ryokou no junbi." }, { jp: "準備が できた。", en: "Prep is done.", romaji: "Junbi ga dekita." }] },
      { japanese: "意見", romaji: "iken", english: "Opinion", examples: [{ jp: "意見を 言う。", en: "Give an opinion.", romaji: "Iken wo iu." }, { jp: "反対の 意見。", en: "Opposing opinion.", romaji: "Hantai no iken." }] },
      { japanese: "賛成", romaji: "sansei", english: "Agreement", examples: [{ jp: "意見に 賛成する。", en: "Agree with an opinion.", romaji: "Iken ni sansei suru." }, { jp: "みんな 賛成。", en: "Everyone agrees.", romaji: "Minna sansei." }] },
      { japanese: "反対", romaji: "hantai", english: "Opposition", examples: [{ jp: "計画に 反対する。", en: "Oppose the plan.", romaji: "Keikaku ni hantai suru." }, { jp: "反対 側。", en: "Opposite side.", romaji: "Hantai gawa." }] },
      { japanese: "決定", romaji: "kettei", english: "Decision", examples: [{ jp: "方針を 決定する。", en: "Decide the policy.", romaji: "Houshin wo kettei suru." }, { jp: "最終 決定。", en: "Final decision.", romaji: "Saishuukettei." }] },
      { japanese: "出席", romaji: "shusseki", english: "Attendance", examples: [{ jp: "パーティーに 出席する。", en: "Attend the party.", romaji: "Paatii ni shusseki suru." }, { jp: "欠席する。", en: "Be absent.", romaji: "Kesseki suru." }] },
      { japanese: "欠席", romaji: "kesseki", english: "Absence", examples: [{ jp: "会議を 欠席する。", en: "Miss the meeting.", romaji: "Kaigi wo kesseki suru." }, { jp: "理由あって欠席。", en: "Absent with reason.", romaji: "Riyuuatte kesseki." }] },
      { japanese: "場所", romaji: "basho", english: "Place/Location", examples: [{ jp: "会議の 場所。", en: "Meeting place.", romaji: "Kaigi no basho." }, { jp: "良い 場所を 見つけた。", en: "Found a good spot.", romaji: "Ii basho wo mitsuketa." }] },
      { japanese: "事務所", romaji: "jimusho", english: "Office", examples: [{ jp: "新しい 事務所。", en: "New office.", romaji: "Atarashii jimusho." }, { jp: "事務所に 来て。", en: "Come to the office.", romaji: "Jimusho ni kite." }] },
      { japanese: "受付", romaji: "uketsuke", english: "Reception", examples: [{ jp: "受付に 聞く。", en: "Ask at reception.", romaji: "Uketsuke ni kiku." }, { jp: "ホテルの 受付。", en: "Hotel reception.", romaji: "Hoteru no uketsuke." }] },
      { japanese: "名刺", romaji: "meishi", english: "Business card", examples: [{ jp: "名刺を 渡す。", en: "Hand over a card.", romaji: "Meishi wo watasu." }, { jp: "名刺入れ。", en: "Card case.", romaji: "Meishiire." }] },
      { japanese: "電話", romaji: "denwa", english: "Telephone", examples: [{ jp: "電話を かける。", en: "Make a call.", romaji: "Denwa wo kakeru." }, { jp: "電話を 切る。", en: "Hang up.", romaji: "Denwa wo kiru." }] },
      { japanese: "コピー", romaji: "kopii", english: "Copy", examples: [{ jp: "コピーを とる。", en: "Make a copy.", romaji: "Kopii wo toru." }, { jp: "コピー機。", en: "Copier.", romaji: "Kopiiki." }] },
      { japanese: "パソコン", romaji: "pasokon", english: "Computer/PC", examples: [{ jp: "パソコンが 壊れた。", en: "PC is broken.", romaji: "Pasokon ga kowareta." }, { jp: "ノート パソコン。", en: "Laptop.", romaji: "Nooto pasokon." }] },
      { japanese: "メール", romaji: "meeru", english: "Email", examples: [{ jp: "メールを 送る。", en: "Send an email.", romaji: "Meeru wo okuru." }, { jp: "返信 メール。", en: "Reply email.", romaji: "Henshin meeru." }] },
      { japanese: "挨拶", romaji: "aisatsu", english: "Greeting", examples: [{ jp: "朝の 挨拶。", en: "Morning greeting.", romaji: "Asa no aisatsu." }, { jp: "挨拶する。", en: "To greet.", romaji: "Aisatsu suru." }] },
      { japanese: "上司", romaji: "joushi", english: "Superior/Boss", examples: [{ jp: "厳しい 上司。", en: "Strict boss.", romaji: "Kibishii joushi." }, { jp: "上司と 飲む。", en: "Drink with boss.", romaji: "Joushi to nomu." }] },
      { japanese: "部下", romaji: "buka", english: "Subordinate", examples: [{ jp: "部下に 教える。", en: "Teach a subordinate.", romaji: "Buka ni oshieru." }, { jp: "頼りになる 部下。", en: "Reliable subordinate.", romaji: "Tayori ni naru buka." }] },
      { japanese: "同僚", romaji: "douryou", english: "Colleague", examples: [{ jp: "同僚と 相談する。", en: "Discuss with colleague.", romaji: "Douryou to soudan suru." }, { jp: "良い 同僚。", en: "Good colleague.", romaji: "Ii douryou." }] },
      { japanese: "給料", romaji: "kyuuryou", english: "Salary", examples: [{ jp: "給料が 上がった。", en: "Salary went up.", romaji: "Kyuuryou ga agatta." }, { jp: "給料日。", en: "Payday.", romaji: "Kyuuryoubi." }] },
      { japanese: "残業", romaji: "zangyou", english: "Overtime", examples: [{ jp: "残業が 多い。", en: "Lots of overtime.", romaji: "Zangyou ga ooi." }, { jp: "残業する。", en: "Work overtime.", romaji: "Zangyou suru." }] },
      { japanese: "出張", romaji: "shucchou", english: "Business trip", examples: [{ jp: "来週から 出張。", en: "Business trip from next week.", romaji: "Raishuu kara shucchou." }, { jp: "出張先。", en: "Trip destination.", romaji: "Shucchousaki." }] },
      { japanese: "辞める", romaji: "yameru", english: "To quit/stop", examples: [{ jp: "会社を 辞める。", en: "Quit the company.", romaji: "Kaisha wo yameru." }, { jp: "タバコを 辞める。", en: "Quit smoking.", romaji: "Tabako wo yameru." }] },
      { japanese: "働く", romaji: "hataraku", english: "To work", examples: [{ jp: "一生懸命 働く。", en: "Work hard.", romaji: "Isshoukenmei hataraku." }, { jp: "工場で 働く。", en: "Work at a factory.", romaji: "Koujou de hataraku." }] }
    ]
  },
  {
    id: 33,
    level: "N4",
    title: "Emotions & States",
    description: "Describing feelings and physical/mental states",
    words: [
      { japanese: "驚く", romaji: "odoroku", english: "To be surprised", examples: [{ jp: "ニュースに 驚く。", en: "Surprised at news.", romaji: "Nyuusu ni odoroku." }, { jp: "驚いた 顔。", en: "Surprised face.", romaji: "Odoroita kao." }] },
      { japanese: "笑う", romaji: "warau", english: "To laugh/smile", examples: [{ jp: "大声で 笑う。", en: "Laugh loudly.", romaji: "Oogoe de warau." }, { jp: "彼女は いつも笑っている。", en: "She is always smiling.", romaji: "Kanojo wa itsumo waratteiru." }] },
      { japanese: "泣く", romaji: "naku", english: "To cry", examples: [{ jp: "子供が 泣く。", en: "Child cries.", romaji: "Kodomo ga naku." }, { jp: "嬉しくて 泣く。", en: "Cry from happiness.", romaji: "Ureshikute naku." }] },
      { japanese: "怒る", romaji: "okoru", english: "To get angry", examples: [{ jp: "先生が 怒る。", en: "Teacher gets angry.", romaji: "Sensei ga okoru." }, { jp: "怒らないで。", en: "Don't be angry.", romaji: "Okoranaide." }] },
      { japanese: "困る", romaji: "komaru", english: "To be troubled", examples: [{ jp: "お金に 困る。", en: "Be troubled for money.", romaji: "Okane ni komaru." }, { jp: "困った 時は連絡して。", en: "Contact when in trouble.", romaji: "Komatta toki wa renraku shite." }] },
      { japanese: "心配する", romaji: "shinpairuru", english: "To worry", examples: [{ jp: "家族を 心配する。", en: "Worry about family.", romaji: "Kazoku wo shinpai suru." }, { jp: "心配 しないで。", en: "Don't worry.", romaji: "Shinpai shinaide." }] },
      { japanese: "安心する", romaji: "anshinsuru", english: "To be relieved", examples: [{ jp: "声を聞いて安心した。", en: "Relieved to hear the voice.", romaji: "Koe wo kiite anshinshita." }, { jp: "安心 してください。", en: "Please be at ease.", romaji: "Anshin shite kudasai." }] },
      { japanese: "がっかりする", romaji: "gakkarisuru", english: "To be disappointed", examples: [{ jp: "テストに 落ちてがっかりした。", en: "Disappointed at failing the test.", romaji: "Tesuto ni ochite gakkarishita." }, { jp: "がっかりさせないで。", en: "Don't disappoint me.", romaji: "Gakkari sasenaide." }] },
      { japanese: "緊張する", romaji: "kinjousuru", english: "To be nervous", examples: [{ jp: "スピーチで 緊張した。", en: "Nervous at the speech.", romaji: "Supiichi de kinjoushita." }, { jp: "緊張しないで。", en: "Don't be nervous.", romaji: "Kinjoushinaide." }] },
      { japanese: "恥ずかしい", romaji: "hazukashii", english: "Embarrassed/Shy", examples: [{ jp: "間違いが 恥ずかしい。", en: "Embarrassed by a mistake.", romaji: "Machigai ga hazukashii." }, { jp: "恥ずかし がり屋。", en: "Shy person.", romaji: "Hazukashigariya." }] },
      { japanese: "羨ましい", romaji: "urayamashii", english: "Envious/Jealous", examples: [{ jp: "君が 羨ましい。", en: "I'm envious of you.", romaji: "Kimi ga urayamashii." }, { jp: "羨ましい 旅行。", en: "Envious trip.", romaji: "Urayamashii ryokou." }] },
      { japanese: "悲しい", romaji: "kanashii", english: "Sad", examples: [{ jp: "悲しい ニュース。", en: "Sad news.", romaji: "Kanashii nyuusu." }, { jp: "悲しそうな 顔。", en: "Sad-looking face.", romaji: "Kanashisouna kao." }] },
      { japanese: "嬉しい", romaji: "ureshii", english: "Happy/Glad", examples: [{ jp: "会えて 嬉しい。", en: "Glad to meet you.", romaji: "Aete ureshii." }, { jp: "嬉しい お知らせ。", en: "Happy announcement.", romaji: "Ureshii oshirase." }] },
      { japanese: "楽しい", romaji: "tanoshii", english: "Fun/Enjoyable", examples: [{ jp: "楽しい 時間。", en: "Fun time.", romaji: "Tanoshii jikan." }, { jp: "毎日が 楽しい。", en: "Every day is fun.", romaji: "Mainichi ga tanoshii." }] },
      { japanese: "寂しい", romaji: "sabishii", english: "Lonely", examples: [{ jp: "一人で 寂しい。", en: "Lonely alone.", romaji: "Hitori de sabishii." }, { jp: "寂しい 夜。", en: "Lonely night.", romaji: "Sabishii yoru." }] },
      { japanese: "懐かしい", romaji: "natsukashii", english: "Nostalgic", examples: [{ jp: "懐かしい 写真。", en: "Nostalgic photo.", romaji: "Natsukashii shashin." }, { jp: "懐かしい 味がする。", en: "Tastes nostalgic.", romaji: "Natsukashii aji ga suru." }] },
      { japanese: "厳しい", romaji: "kibishii", english: "Strict/Severe", examples: [{ jp: "厳しい 父親。", en: "Strict father.", romaji: "Kibishii chichioya." }, { jp: "厳しい 寒さ。", en: "Severe cold.", romaji: "Kibishii samusa." }] },
      { japanese: "優しい", romaji: "yasashii", english: "Gentle/Kind", examples: [{ jp: "優しい 先生。", en: "Kind teacher.", romaji: "Yasashii sensei." }, { jp: "優しく してください。", en: "Please be kind.", romaji: "Yasashiku shite kudasai." }] },
      { japanese: "怖い", romaji: "kowai", english: "Scary", examples: [{ jp: "お化けが 怖い。", en: "Scared of ghosts.", romaji: "Obake ga kowai." }, { jp: "怖い 映画。", en: "Scary movie.", romaji: "Kowai eiga." }] },
      { japanese: "可笑しい", romaji: "okashii", english: "Strange/Funny", examples: [{ jp: "その話は 可笑しい。", en: "That story is funny/strange.", romaji: "Sono hanashi wa okashii." }, { jp: "可笑しな 格好。", en: "Strange outfit.", romaji: "Okashina kakkou." }] },
      { japanese: "幸せ", romaji: "shiawase", english: "Happiness/Happy", examples: [{ jp: "幸せに なる。", en: "Become happy.", romaji: "Shiawase ni naru." }, { jp: "幸せな 家庭。", en: "Happy home.", romaji: "Shiawase na katei." }] },
      { japanese: "残念", romaji: "zannen", english: "Pity/Regrettable", examples: [{ jp: "それは 残念です。", en: "That's a pity.", romaji: "Sore wa zannen desu." }, { jp: "残念ながら 欠席。", en: "Unfortunately absent.", romaji: "Zannennagara kesseki." }] },
      { japanese: "無理", romaji: "muri", english: "Impossible/Too much", examples: [{ jp: "無理を するな。", en: "Don't overdo it.", romaji: "Muri wo suruna." }, { jp: "それは 無理だ。", en: "That's impossible.", romaji: "Sore wa muri da." }] },
      { japanese: "不思議", romaji: "fushigi", english: "Mysterious/Wonder", examples: [{ jp: "不思議な 話。", en: "Mysterious story.", romaji: "Fushigina hanashi." }, { jp: "不思議に 思う。", en: "Think it's strange.", romaji: "Fushigi ni omou." }] },
      { japanese: "真面目", romaji: "majime", english: "Serious/Diligent", examples: [{ jp: "真面目な 学生。", en: "Serious student.", romaji: "Majimena gakusei." }, { jp: "真面目に 働く。", en: "Work seriously.", romaji: "Majime ni hataraku." }] },
      { japanese: "適当", romaji: "tekitou", english: "Suitable/Random", examples: [{ jp: "適当な 理由。", en: "Suitable reason.", romaji: "Tekitouna riyuu." }, { jp: "適当に する。", en: "Do it randomly/carelessly.", romaji: "Tekitou ni suru." }] },
      { japanese: "丁寧", romaji: "teinei", english: "Polite/Careful", examples: [{ jp: "丁寧な 挨拶。", en: "Polite greeting.", romaji: "Teineina aisatsu." }, { jp: "丁寧に 書く。", en: "Write carefully.", romaji: "Teinei ni kaku." }] },
      { japanese: "複雑", romaji: "fukuzatsu", english: "Complex", examples: [{ jp: "複雑な 問題。", en: "Complex problem.", romaji: "Fukuzatsuna mondai." }, { jp: "話が 複雑だ。", en: "Story is complex.", romaji: "Hanashi ga fukuzatsu da." }] },
      { japanese: "単純", romaji: "tanjun", english: "Simple/Naive", examples: [{ jp: "単純な 計算。", en: "Simple calculation.", romaji: "Tanjunna keisan." }, { jp: "単純な 人。", en: "Simple-minded person.", romaji: "Tanjunna hito." }] },
      { japanese: "楽", romaji: "raku", english: "Easy/Comfortable", examples: [{ jp: "楽な 仕事。", en: "Easy job.", romaji: "Rakuna shigoto." }, { jp: "楽に して。", en: "Make yourself comfortable.", romaji: "Raku ni shite." }] }
    ]
  },
  {
    id: 34,
    level: "N4",
    title: "Health & Body",
    description: "Vocabulary for physical condition and health",
    words: [
      { japanese: "健康", romaji: "kenkou", english: "Health", examples: [{ jp: "健康が 第一。", en: "Health is first.", romaji: "Kenkou ga daiichi." }, { jp: "健康 診断。", en: "Health checkup.", romaji: "Kenkou shindan." }] },
      { japanese: "病院", romaji: "byouin", english: "Hospital", examples: [{ jp: "病院に 入院する。", en: "Be hospitalized.", romaji: "Byouin ni nyuuin suru." }, { jp: "大学 病院。", en: "University hospital.", romaji: "Daigaku byouin." }] },
      { japanese: "医者", romaji: "isha", english: "Doctor", examples: [{ jp: "医者に みてもらう。", en: "See a doctor.", romaji: "Isha ni mitemorau." }, { jp: "名医。", en: "Famous doctor.", romaji: "Meii." }] },
      { japanese: "看護師", romaji: "kangoshi", english: "Nurse", examples: [{ jp: "看護師に なる。", en: "Become a nurse.", romaji: "Kangoshi ni naru." }, { jp: "優しい 看護師。", en: "Kind nurse.", romaji: "Yasashii kangoshi." }] },
      { japanese: "薬", romaji: "kusuri", english: "Medicine", examples: [{ jp: "薬を 飲む。", en: "Take medicine.", romaji: "Kusuri wo nomu." }, { jp: "風邪 薬。", en: "Cold medicine.", romaji: "Kaze gusuri." }] },
      { japanese: "病気", romaji: "byouki", english: "Illness", examples: [{ jp: "病気に 勝つ。", en: "Beat the illness.", romaji: "Byouki ni katsu." }, { jp: "重い 病気。", en: "Serious illness.", romaji: "Omoi byouki." }] },
      { japanese: "風邪", romaji: "kaze", english: "Cold (illness)", examples: [{ jp: "風邪を 引いた。", en: "Caught a cold.", romaji: "Kaze wo hiita." }, { jp: "ひどい 風邪。", en: "Terrible cold.", romaji: "Hidoi kaze." }] },
      { japanese: "咳", romaji: "seki", english: "Cough", examples: [{ jp: "咳が 出る。", en: "Have a cough.", romaji: "Seki ga deru." }, { jp: "咳を する。", en: "To cough.", romaji: "Seki wo suru." }] },
      { japanese: "鼻水", romaji: "hanamizu", english: "Runny nose", examples: [{ jp: "鼻水が 止まらない。", en: "Can't stop runny nose.", romaji: "Hanamizu ga tomaranai." }, { jp: "ティッシュで 拭く。", en: "Wipe with tissue.", romaji: "Tisshu de fuku." }] },
      { japanese: "喉", romaji: "nodo", english: "Throat", examples: [{ jp: "喉が 痛い。", en: "Sore throat.", romaji: "Nodo ga itai." }, { jp: "喉が 渇いた。", en: "Thirsty.", romaji: "Nodo ga kawaita." }] },
      { japanese: "頭痛", romaji: "zutsuu", english: "Headache", examples: [{ jp: "頭痛が する。", en: "Have a headache.", romaji: "Zutsuu ga suru." }, { jp: "頭痛 薬。", en: "Headache med.", romaji: "Zutsuu yaku." }] },
      { japanese: "腹通", romaji: "fukutsuu", english: "Stomachache", examples: [{ jp: "お腹が 痛い。", en: "Stomach hurts.", romaji: "Onaka ga itai." }, { jp: "食べすぎで 腹痛。", en: "Stomachache from overeating.", romaji: "Tabesugi de fukutsuu." }] },
      { japanese: "怪我", romaji: "kega", english: "Injury", examples: [{ jp: "怪我を する。", en: "Get injured.", romaji: "Kega wo suru." }, { jp: "ひどい 怪我。", en: "Bad injury.", romaji: "Hidoi kega." }] },
      { japanese: "骨折", romaji: "kossetsu", english: "Bone fracture", examples: [{ jp: "足を 骨折した。", en: "Broke a leg.", romaji: "Ashi wo kossetsu shita." }, { jp: "骨折で 入院。", en: "Hospitalized for fracture.", romaji: "Kossetsu de nyuuin." }] },
      { japanese: "入院", romaji: "nyuuin", english: "Hospitalization", examples: [{ jp: "明日から 入院。", en: "Hospitalized from tomorrow.", romaji: "Ashita kara nyuuin." }, { jp: "入院 費。", en: "Hospital bill.", romaji: "Nyuuinhi." }] },
      { japanese: "退院", romaji: "taiin", english: "Discharge from hospital", examples: [{ jp: "今日 退院した。", en: "Discharged today.", romaji: "Kyou taiin shita." }, { jp: "退院 おめでとう。", en: "Congrats on discharge.", romaji: "Taiin omedetou." }] },
      { japanese: "診察", romaji: "shinsatsu", english: "Medical examination", examples: [{ jp: "診察を 受ける。", en: "Get examined.", romaji: "Shinsatsu wo ukeru." }, { jp: "診察 室。", en: "Examining room.", romaji: "Shinsatsu shitsu." }] },
      { japanese: "注射", romaji: "chuusha", english: "Injection", examples: [{ jp: "注射が 嫌い。", en: "Hate injections.", romaji: "Chuusha ga kirai." }, { jp: "注射を する。", en: "Give an injection.", romaji: "Chuusha wo suru." }] },
      { japanese: "体温", romaji: "taion", english: "Body temperature", examples: [{ jp: "体温を 測る。", en: "Measure temp.", romaji: "Taion wo hakaru." }, { jp: "高い 体温。", en: "High body temp.", romaji: "Takai taion." }] },
      { japanese: "血", romaji: "chi", english: "Blood", examples: [{ jp: "血が 出る。", en: "Bleeding.", romaji: "Chi ga deru." }, { jp: "血液 型。", en: "Blood type.", romaji: "Ketsuekigata." }] },
      { japanese: "筋肉", romaji: "kinniku", english: "Muscle", examples: [{ jp: "筋肉 痛。", en: "Muscle pain.", romaji: "Kinnikutsuu." }, { jp: "筋肉を 鍛える。", en: "Train muscles.", romaji: "Kinniku wo kitaeru." }] },
      { japanese: "骨", romaji: "hone", english: "Bone", examples: [{ jp: "骨が 折れる。", en: "Bone breaks.", romaji: "Hone ga oreru." }, { jp: "魚の 骨。", en: "Fish bone.", romaji: "Sakana no hone." }] },
      { japanese: "心臓", romaji: "shinzou", english: "Heart", examples: [{ jp: "心臓の 音。", en: "Heartbeat sound.", romaji: "Shinzou no oto." }, { jp: "心臓 病。", en: "Heart disease.", romaji: "Shinzoubyou." }] },
      { japanese: "胃", romaji: "i", english: "Stomach (organ)", examples: [{ jp: "胃が 痛い。", en: "Stomach hurts.", romaji: "I ga itai." }, { jp: "胃薬を 飲む。", en: "Take stomach med.", romaji: "Igusuri wo nomu." }] },
      { japanese: "肌", romaji: "hada", english: "Skin", examples: [{ jp: "肌が 荒れる。", en: "Rough skin.", romaji: "Hada ga areru." }, { jp: "きれいな 肌。", en: "Beautiful skin.", romaji: "Kireina hada." }] },
      { japanese: "ダイエット", romaji: "daietto", english: "Diet", examples: [{ jp: "ダイエットを 始める。", en: "Start a diet.", romaji: "Daietto wo hajimeru." }, { jp: "無理な ダイエット。", en: "Extreme diet.", romaji: "Murina daietto." }] },
      { japanese: "運動", romaji: "undou", english: "Exercise", examples: [{ jp: "毎日 運動する。", en: "Exercise daily.", romaji: "Mainichi undou suru." }, { jp: "運動会。", en: "Sports day.", romaji: "Undoukai." }] },
      { japanese: "睡眠", romaji: "suimin", english: "Sleep", examples: [{ jp: "睡眠 不足。", en: "Lack of sleep.", romaji: "Suimin busoku." }, { jp: "十分な 睡眠。", en: "Enough sleep.", romaji: "Juubunna suimin." }] },
      { japanese: "無理", romaji: "muri", english: "Overwork/Impossible", examples: [{ jp: "無理を するな。", en: "Don't push yourself too hard.", romaji: "Muri wo suruna." }, { jp: "無理は 体に悪い。", en: "Overwork is bad for health.", romaji: "Muri wa karada ni warui." }] },
      { japanese: "治る", romaji: "naoru", english: "To be cured", examples: [{ jp: "病気が 治った。", en: "Illness is cured.", romaji: "Byouki ga naotta." }, { jp: "早く 治ってね。", en: "Get well soon.", romaji: "Hayaku naotte ne." }] }
    ]
  },
  {
    id: 35,
    level: "N4",
    title: "City & Living",
    description: "Town life, facilities, and urban vocabulary",
    words: [
      { japanese: "都市", romaji: "toshi", english: "City/Metropolis", examples: [{ jp: "大 都市。", en: "Large city.", romaji: "Dai toshi." }, { jp: "都市 開発。", en: "Urban development.", romaji: "Toshi kaihatsu." }] },
      { japanese: "近所", romaji: "kinjo", english: "Neighborhood", examples: [{ jp: "近所を 散歩する。", en: "Walk in the neighborhood.", romaji: "Kinjo wo sanpo suru." }, { jp: "近所の 人。", en: "Neighbor.", romaji: "Kinjo no hito." }] },
      { japanese: "役所", romaji: "yakusho", english: "Public office/City hall", examples: [{ jp: "役所へ 行く。", en: "Go to city hall.", romaji: "Yakusho e iku." }, { jp: "市役所。", en: "City office.", romaji: "Shiyakusho." }] },
      { japanese: "交番", romaji: "kouban", english: "Police box", examples: [{ jp: "交番で 聞く。", en: "Ask at the police box.", romaji: "Kouban de kiku." }, { jp: "駅前の 交番。", en: "Police box in front of station.", romaji: "Ekimae no kouban." }] },
      { japanese: "郵便局", romaji: "yuubinkyoku", english: "Post office", examples: [{ jp: "郵便局で 切手を買う。", en: "Buy stamps at post office.", romaji: "Yuubinkyoku de kitte wo kau." }, { jp: "近くの 郵便局。", en: "Nearby post office.", romaji: "Chikaku no yuubinkyoku." }] },
      { japanese: "銀行", romaji: "ginkou", english: "Bank", examples: [{ jp: "銀行で お金を下ろす。", en: "Withdraw money at bank.", romaji: "Ginkou de okane wo orosu." }, { jp: "銀行 口座。", en: "Bank account.", romaji: "Ginkou kouza." }] },
      { japanese: "図書館", romaji: "toshokan", english: "Library", examples: [{ jp: "図書館で 勉強する。", en: "Study at the library.", romaji: "Toshokan de benkyou suru." }, { jp: "静かな 図書館。", en: "Quiet library.", romaji: "Shizukana toshokan." }] },
      { japanese: "公園", romaji: "kouen", english: "Park", examples: [{ jp: "公園で 遊ぶ。", en: "Play in the park.", romaji: "Kouen de asobu." }, { jp: "広い 公園。", en: "Large park.", romaji: "Hiroi kouen." }] },
      { japanese: "商店街", romaji: "shoutengai", english: "Shopping street", examples: [{ jp: "賑やかな 商店街。", en: "Lively shopping street.", romaji: "Nigiyakana shoutengai." }, { jp: "商店街で 買い物。", en: "Shopping at the arcade.", romaji: "Shoutengai de kaimono." }] },
      { japanese: "映画館", romaji: "eigakan", english: "Movie theater", examples: [{ jp: "映画館で 映画を見る。", en: "Watch a movie at the theater.", romaji: "Eigakan de eiga wo miru." }, { jp: "映画館の チケット。", en: "Theater ticket.", romaji: "Eigakan no chiketto." }] },
      { japanese: "美術館", romaji: "bijutsukan", english: "Art museum", examples: [{ jp: "美術館に 行く。", en: "Go to an art museum.", romaji: "Bijutsukan ni iku." }, { jp: "有名な 美術館。", en: "Famous art museum.", romaji: "Yuumeina bijutsukan." }] },
      { japanese: "駐車場", romaji: "chuushajou", english: "Parking lot", examples: [{ jp: "駐車場に 車を停める。", en: "Park a car in the lot.", romaji: "Chuushajou ni kuruma wo tomeru." }, { jp: "有料 駐車場。", en: "Paid parking.", romaji: "Yuuryou chuushajou." }] },
      { japanese: "交差点", romaji: "kousaten", english: "Intersection", examples: [{ jp: "交差点を 右に曲がる。", en: "Turn right at intersection.", romaji: "Kousaten wo migi ni magaru." }, { jp: "危ない 交差点。", en: "Dangerous intersection.", romaji: "Abunai kousaten." }] },
      { japanese: "信号", romaji: "shingou", english: "Traffic light", examples: [{ jp: "信号が 赤になる。", en: "Light turns red.", romaji: "Shingou ga aka ni naru." }, { jp: "信号を 守る。", en: "Obey traffic lights.", romaji: "Shingou wo mamoru." }] },
      { japanese: "道", romaji: "michi", english: "Road/Way", examples: [{ jp: "道に 迷う。", en: "Get lost.", romaji: "Michi ni mayou." }, { jp: "細い 道。", en: "Narrow road.", romaji: "Hosoi michi." }] },
      { japanese: "角", romaji: "kado", english: "Corner", examples: [{ jp: "あの 角の 店。", en: "That shop at the corner.", romaji: "Ano kado no mise." }, { jp: "角を 曲がる。", en: "Turn the corner.", romaji: "Kado wo magaru." }] },
      { japanese: "歩道", romaji: "hodou", english: "Sidewalk", examples: [{ jp: "歩道を 歩く。", en: "Walk on the sidewalk.", romaji: "Hodou wo aruku." }, { jp: "広い 歩道。", en: "Wide sidewalk.", romaji: "Hiroi hodou." }] },
      { japanese: "橋", romaji: "hashi", english: "Bridge", examples: [{ jp: "橋を 渡る。", en: "Cross the bridge.", romaji: "Hashi wo wataru." }, { jp: "長い 橋。", en: "Long bridge.", romaji: "Nagai hashi." }] },
      { japanese: "建物", romaji: "tatemono", english: "Building", examples: [{ jp: "高い 建物。", en: "Tall building.", romaji: "Takai tatemono." }, { jp: "建物の 入り口。", en: "Building entrance.", romaji: "Tatemono no iriguchi." }] },
      { japanese: "マンション", romaji: "manshon", english: "Apartment/Condo", examples: [{ jp: "新しい マンション。", en: "New apartment.", romaji: "Atarashii manshon." }, { jp: "マンションに 住む。", en: "Live in a condo.", romaji: "Manshon ni sumu." }] },
      { japanese: "アパート", romaji: "apaato", english: "Apartment", examples: [{ jp: "古い アパート。", en: "Old apartment.", romaji: "Furui apaato." }, { jp: "一人暮らしの アパート。", en: "Apt for living alone.", romaji: "Hitorigurashi no apaato." }] },
      { japanese: "引っ越し", romaji: "hikkoshi", english: "Moving", examples: [{ jp: "引っ越しを する。", en: "To move (home).", romaji: "Hikkoshi wo suru." }, { jp: "引っ越しの 準備。", en: "Move preparation.", romaji: "Hikkoshi no junbi." }] },
      { japanese: "隣", romaji: "tonari", english: "Next door/Nearby", examples: [{ jp: "隣の 家。", en: "House next door.", romaji: "Tonari no ie." }, { jp: "隣に 座る。", en: "Sit next to.", romaji: "Tonari ni suwaru." }] },
      { japanese: "場所", romaji: "basho", english: "Location", examples: [{ jp: "良い 場所。", en: "Good location.", romaji: "Ii basho." }, { jp: "場所を 教える。", en: "Tell the location.", romaji: "Basho wo oshieru." }] },
      { japanese: "治安", romaji: "chian", english: "Public safety", examples: [{ jp: "治安が 良い。", en: "Safe (neighborhood).", romaji: "Chian ga ii." }, { jp: "治安が 悪い。", en: "Unsafe.", romaji: "Chian ga warui." }] },
      { japanese: "便利", romaji: "benri", english: "Convenient", examples: [{ jp: "駅に近くて便利。", en: "Conveniently near station.", romaji: "Eki ni chikakute benri." }, { jp: "便利な 街。", en: "Convenient town.", romaji: "Benrina machi." }] },
      { japanese: "不便", romaji: "fuben", english: "Inconvenient", examples: [{ jp: "交通が 不便。", en: "Inconvenient transport.", romaji: "Koutsuu ga fuben." }, { jp: "不便な 所。", en: "Inconvenient place.", romaji: "Fubenna tokoro." }] },
      { japanese: "家賃", romaji: "yachin", english: "Rent", examples: [{ jp: "家賃を 払う。", en: "Pay rent.", romaji: "Yachin wo harau." }, { jp: "高い 家賃。", en: "High rent.", romaji: "Takai yachin." }] },
      { japanese: "管理費", romaji: "kanrihi", english: "Management fee", examples: [{ jp: "管理費が かかる。", en: "Mgmt fee is required.", romaji: "Kanrihi ga kakaru." }, { jp: "月々の 管理費。", en: "Monthly mgmt fee.", romaji: "Tsukizuki no kanrihi." }] },
      { japanese: "鍵", romaji: "kagi", english: "Key", examples: [{ jp: "鍵を かける。", en: "Lock the key.", romaji: "Kagi wo kakeru." }, { jp: "鍵を 忘れた。", en: "Forgot the key.", romaji: "Kagi wo wasureta." }] }
    ]
  }
];
