export const chunk4 = [
  {
    id: 16,
    title: "Verbs: Daily Life",
    description: "Essential verbs for daily routines and activities",
    words: [
      { japanese: "起きる", romaji: "okiru", english: "To wake up", examples: [{ jp: "朝 六時に 起きる。", en: "Wake up at 6 AM.", romaji: "Asa rokuji ni okiru." }, { jp: "早く 起きる。", en: "Wake up early.", romaji: "Hayaku okiru." }] },
      { japanese: "寝る", romaji: "neru", english: "To sleep", examples: [{ jp: "夜 十時に 寝る。", en: "Sleep at 10 PM.", romaji: "Yoru juuji ni neru." }, { jp: "よく 寝る。", en: "Sleep well.", romaji: "Yoku neru." }] },
      { japanese: "食べる", romaji: "taberu", english: "To eat", examples: [{ jp: "ご飯を 食べる。", en: "Eat a meal.", romaji: "Gohan wo taberu." }, { jp: "朝ごはん。", en: "Breakfast.", romaji: "Asagohan." }] },
      { japanese: "飲む", romaji: "nomu", english: "To drink", examples: [{ jp: "水を 飲む。", en: "Drink water.", romaji: "Mizu wo nomu." }, { jp: "お酒を 飲む。", en: "Drink alcohol.", romaji: "Osake wo nomu." }] },
      { japanese: "洗う", romaji: "arau", english: "To wash", examples: [{ jp: "顔を 洗う。", en: "Wash face.", romaji: "Kao wo arau." }, { jp: "皿を 洗う。", en: "Wash dishes.", romaji: "Sara wo arau." }] },
      { japanese: "磨く", romaji: "migaku", english: "To brush/polish", examples: [{ jp: "歯を 磨く。", en: "Brush teeth.", romaji: "Ha wo migaku." }, { jp: "靴を 磨く。", en: "Polish shoes.", romaji: "Kutsu wo migaku." }] },
      { japanese: "浴びる", romaji: "abiru", english: "To bathe/shower", examples: [{ jp: "シャワーを 浴びる。", en: "Take a shower.", romaji: "Shawaa wo abiru." }, { jp: "日光を 浴びる。", en: "Bathe in sunlight.", romaji: "Nikkou wo abiru." }] },
      { japanese: "着替える", romaji: "kigaeru", english: "To change clothes", examples: [{ jp: "服を 着替える。", en: "Change clothes.", romaji: "Fuku wo kigaeru." }, { jp: "パジャマに 着替える。", en: "Change into PJs.", romaji: "Pajama ni kigaeru." }] },
      { japanese: "出る", romaji: "deru", english: "To exit/leave", examples: [{ jp: "家を 出る。", en: "Leave home.", romaji: "Ie wo deru." }, { jp: "外に 出る。", en: "Go outside.", romaji: "Soto ni deru." }] },
      { japanese: "入る", romaji: "hairu", english: "To enter", examples: [{ jp: "部屋に 入る。", en: "Enter room.", romaji: "Heya ni hairu." }, { jp: "お風呂に 入る。", en: "Take bath.", romaji: "Ofuro ni hairu." }] },
      { japanese: "帰る", romaji: "kaeru", english: "To return home", examples: [{ jp: "家に 帰る。", en: "Go home.", romaji: "Ie ni kaeru." }, { jp: "国へ 帰る。", en: "Return to country.", romaji: "Kuni e kaeru." }] },
      { japanese: "行く", romaji: "iku", english: "To go", examples: [{ jp: "学校へ 行く。", en: "Go to school.", romaji: "Gakkou e iku." }, { jp: "旅行に 行く。", en: "Go on a trip.", romaji: "Ryokou ni iku." }] },
      { japanese: "来る", romaji: "kuru", english: "To come", examples: [{ jp: "友達が 来る。", en: "Friend comes.", romaji: "Tomodachi ga kuru." }, { jp: "日本へ 来た。", en: "Came to Japan.", romaji: "Nihon e kita." }] },
      { japanese: "する", romaji: "suru", english: "To do", examples: [{ jp: "勉強を する。", en: "Do study.", romaji: "Benkyou wo suru." }, { jp: "スポーツを する。", en: "Do sports.", romaji: "Supootsu wo suru." }] },
      { japanese: "ある", romaji: "aru", english: "To exist (inanimate)", examples: [{ jp: "本が ある。", en: "There is a book.", romaji: "Hon ga aru." }, { jp: "お金が ある。", en: "Have money.", romaji: "Okane ga aru." }] },
      { japanese: "いる", romaji: "iru", english: "To exist (animate)", examples: [{ jp: "猫が いる。", en: "There is a cat.", romaji: "Neko ga iru." }, { jp: "子供が いる。", en: "Have children.", romaji: "Kodomo ga iru." }] },
      { japanese: "待つ", romaji: "matsu", english: "To wait", examples: [{ jp: "バスを 待つ。", en: "Wait for bus.", romaji: "Basu wo matsu." }, { jp: "ちょっと 待って。", en: "Wait a moment.", romaji: "Chotto matte." }] },
      { japanese: "休む", romaji: "yasumu", english: "To rest", examples: [{ jp: "少し 休む。", en: "Rest a bit.", romaji: "Sukoshi yasumu." }, { jp: "学校を 休む。", en: "Absent from school.", romaji: "Gakkou wo yasumu." }] },
      { japanese: "遊ぶ", romaji: "asobu", english: "To play/hang out", examples: [{ jp: "公園で 遊ぶ。", en: "Play in park.", romaji: "Kouen de asobu." }, { jp: "友達と 遊ぶ。", en: "Hang out with friend.", romaji: "Tomodachi to asobu." }] },
      { japanese: "泳ぐ", romaji: "oyogu", english: "To swim", examples: [{ jp: "海で 泳ぐ。", en: "Swim in sea.", romaji: "Umi de oyogu." }, { jp: "速く 泳ぐ。", en: "Swim fast.", romaji: "Hayaku oyogu." }] },
      { japanese: "急ぐ", romaji: "isogu", english: "To hurry", examples: [{ jp: "駅へ 急ぐ。", en: "Hurry to station.", romaji: "Eki e isogu." }, { jp: "急いで ください。", en: "Please hurry.", romaji: "Isoide kudasai." }] },
      { japanese: "住む", romaji: "sumu", english: "To live", examples: [{ jp: "東京に 住む。", en: "Live in Tokyo.", romaji: "Toukyou ni sumu." }, { jp: "アパートに 住む。", en: "Live in apt.", romaji: "Apaato ni sumu." }] },
      { japanese: "とる", romaji: "toru", english: "To take", examples: [{ jp: "写真を とる。", en: "Take photo.", romaji: "Shashin wo toru." }, { jp: "塩を とる。", en: "Pass salt.", romaji: "Shio wo toru." }] },
      { japanese: "置く", romaji: "oku", english: "To put/place", examples: [{ jp: "本を 置く。", en: "Put down book.", romaji: "Hon wo oku." }, { jp: "ここに 置いて。", en: "Put it here.", romaji: "Koko ni oite." }] },
      { japanese: "拾う", romaji: "hirou", english: "To pick up", examples: [{ jp: "ゴミを 拾う。", en: "Pick up trash.", romaji: "Gomi wo hirou." }, { jp: "財布を 拾う。", en: "Pick up wallet.", romaji: "Saifu wo hirou." }] },
      { japanese: "捨てる", romaji: "suteru", english: "To throw away", examples: [{ jp: "ゴミを 捨てる。", en: "Throw trash.", romaji: "Gomi wo suteru." }, { jp: "捨てないで。", en: "Don't throw away.", romaji: "Sutenaide." }] },
      { japanese: "吸う", romaji: "suu", english: "To smoke/inhale", examples: [{ jp: "たばこを 吸う。", en: "Smoke tobacco.", romaji: "Tabako wo suu." }, { jp: "空気を 吸う。", en: "Inhale air.", romaji: "Kuuki wo suu." }] },
      { japanese: "吐く", romaji: "haku", english: "To exhale/vomit", examples: [{ jp: "息を 吐く。", en: "Exhale breath.", romaji: "Iki wo haku." }, { jp: "気分が悪くて吐く。", en: "Feel sick and vomit.", romaji: "Kibungawarukute haku." }] },
      { japanese: "散歩する", romaji: "sanposuru", english: "To take a walk", examples: [{ jp: "公園を 散歩する。", en: "Stroll in park.", romaji: "Kouen wo sanposuru." }, { jp: "犬と 散歩する。", en: "Walk with dog.", romaji: "Inu to sanposuru." }] },
      { japanese: "洗濯する", romaji: "sentakusuru", english: "To do laundry", examples: [{ jp: "服を 洗濯する。", en: "Wash clothes.", romaji: "Fuku wo sentakusuru." }, { jp: "毎日 洗濯する。", en: "Do laundry daily.", romaji: "Mainichi sentakusuru." }] }
    ]
  },
  {
    id: 17,
    title: "Verbs: Actions",
    description: "Verbs involving objects and states",
    words: [
      { japanese: "開ける", romaji: "akeru", english: "To open", examples: [{ jp: "ドアを 開ける。", en: "Open door.", romaji: "Doa wo akeru." }, { jp: "窓を 開ける。", en: "Open window.", romaji: "Mado wo akeru." }] },
      { japanese: "閉める", romaji: "shimeru", english: "To close", examples: [{ jp: "ドアを 閉める。", en: "Close door.", romaji: "Doa wo shimeru." }, { jp: "店を 閉める。", en: "Close shop.", romaji: "Mise wo shimeru." }] },
      { japanese: "つく", romaji: "tsuku", english: "To turn on/arrive", examples: [{ jp: "電気が つく。", en: "Light turns on.", romaji: "Denki ga tsuku." }, { jp: "駅に 着く。", en: "Arrive at station.", romaji: "Eki ni tsuku." }] },
      { japanese: "消す", romaji: "kesu", english: "To turn off/erase", examples: [{ jp: "電気を 消す。", en: "Turn off light.", romaji: "Denki wo kesu." }, { jp: "字を 消す。", en: "Erase characters.", romaji: "Ji wo kesu." }] },
      { japanese: "座る", romaji: "suwaru", english: "To sit", examples: [{ jp: "椅子に 座る。", en: "Sit on chair.", romaji: "Isu ni suwaru." }, { jp: "どうぞ 座って。", en: "Please sit.", romaji: "Douzo suwatte." }] },
      { japanese: "立つ", romaji: "tatsu", english: "To stand", examples: [{ jp: "席を 立つ。", en: "Leave seat (stand up).", romaji: "Seki wo tatsu." }, { jp: "前に 立つ。", en: "Stand in front.", romaji: "Mae ni tatsu." }] },
      { japanese: "使う", romaji: "tsukau", english: "To use", examples: [{ jp: "箸を 使う。", en: "Use chopsticks.", romaji: "Hashi wo tsukau." }, { jp: "お金を 使う。", en: "Use money.", romaji: "Okane wo tsukau." }] },
      { japanese: "作る", romaji: "tsukuru", english: "To make", examples: [{ jp: "料理を 作る。", en: "Cook.", romaji: "Ryouri wo tsukuru." }, { jp: "友達を 作る。", en: "Make friends.", romaji: "Tomodachi wo tsukuru." }] },
      { japanese: "直す", romaji: "naosu", english: "To fix/repair", examples: [{ jp: "時計を 直す。", en: "Fix watch.", romaji: "Tokei wo naosu." }, { jp: "間違いを 直す。", en: "Correct mistake.", romaji: "Machigai wo naosu." }] },
      { japanese: "壊す", romaji: "kowasu", english: "To break", examples: [{ jp: "おもちゃを 壊す。", en: "Break toy.", romaji: "Omocha wo kowasu." }, { jp: "体を 壊す。", en: "Ruin health.", romaji: "Karada wo kowasu." }] },
      { japanese: "切る", romaji: "kiru", english: "To cut", examples: [{ jp: "紙を 切る。", en: "Cut paper.", romaji: "Kami wo kiru." }, { jp: "電話を 切る。", en: "Hang up phone.", romaji: "Denwa wo kiru." }] },
      { japanese: "貼る", romaji: "haru", english: "To stick/paste", examples: [{ jp: "切手を 貼る。", en: "Stick stamp.", romaji: "Kitte wo haru." }, { jp: "ポスターを 貼る。", en: "Put up poster.", romaji: "Posutaa wo haru." }] },
      { japanese: "押す", romaji: "osu", english: "To push", examples: [{ jp: "ボタンを 押す。", en: "Push button.", romaji: "Botan wo osu." }, { jp: "背中を 押す。", en: "Push back (support).", romaji: "Senaka wo osu." }] },
      { japanese: "引く", romaji: "hiku", english: "To pull", examples: [{ jp: "ドアを 引く。", en: "Pull door.", romaji: "Doa wo hiku." }, { jp: "風邪を 引く。", en: "Catch cold.", romaji: "Kaze wo hiku." }] },
      { japanese: "持つ", romaji: "motsu", english: "To hold/have", examples: [{ jp: "荷物を 持つ。", en: "Hold luggage.", romaji: "Nimotsu wo motsu." }, { jp: "車を 持つ。", en: "Own a car.", romaji: "Kuruma wo motsu." }] },
      { japanese: "運ぶ", romaji: "hakobu", english: "To carry/transport", examples: [{ jp: "荷物を 運ぶ。", en: "Carry luggage.", romaji: "Nimotsu wo hakobu." }, { jp: "足を 運ぶ。", en: "Visit (idiom).", romaji: "Ashi wo hakobu." }] },
      { japanese: "集める", romaji: "atsumeru", english: "To collect", examples: [{ jp: "切手を 集める。", en: "Collect stamps.", romaji: "Kitte wo atsumeru." }, { jp: "人を 集める。", en: "Gather people.", romaji: "Hito wo atsumeru." }] },
      { japanese: "探す", romaji: "sagasu", english: "To search", examples: [{ jp: "鍵を 探す。", en: "Look for key.", romaji: "Kagi wo sagasu." }, { jp: "職を 探す。", en: "Look for job.", romaji: "Shoku wo sagasu." }] },
      { japanese: "失くす", romaji: "nakusu", english: "To lose", examples: [{ jp: "財布を 失くす。", en: "Lose wallet.", romaji: "Saifu wo nakusu." }, { jp: "自信を 失くす。", en: "Lose confidence.", romaji: "Jishin wo nakusu." }] },
      { japanese: "見つける", romaji: "mitsukeru", english: "To find", examples: [{ jp: "良い店を 見つける。", en: "Find good shop.", romaji: "Ii mise wo mitsukeru." }, { jp: "答えを 見つける。", en: "Find answer.", romaji: "Kotae wo mitsukeru." }] },
      { japanese: "知る", romaji: "shiru", english: "To know", examples: [{ jp: "あの人を 知っている。", en: "Know that person.", romaji: "Ano hito wo shitteiru." }, { jp: "秘密を 知る。", en: "Know secret.", romaji: "Himitsu wo shiru." }] },
      { japanese: "分かる", romaji: "wakaru", english: "To understand", examples: [{ jp: "日本語が 分かる。", en: "Understand Japanese.", romaji: "Nihongo ga wakaru." }, { jp: "意味が 分からない。", en: "Don't understand meaning.", romaji: "Imi ga wakaranai." }] },
      { japanese: "考える", romaji: "kangaeru", english: "To think", examples: [{ jp: "よく 考える。", en: "Think hard.", romaji: "Yoku kangaeru." }, { jp: "将来を 考える。", en: "Think about future.", romaji: "Shourai wo kangaeru." }] },
      { japanese: "忘れる", romaji: "wasureru", english: "To forget", examples: [{ jp: "宿題を 忘れる。", en: "Forget homework.", romaji: "Shukudai wo wasureru." }, { jp: "名前を 忘れた。", en: "Forgot name.", romaji: "Namae wo wasureta." }] },
      { japanese: "思い出す", romaji: "omoidasu", english: "To remember/recall", examples: [{ jp: "昔を 思い出す。", en: "Recall old days.", romaji: "Mukashi wo omoidasu." }, { jp: "急に 思い出した。", en: "Suddenly remembered.", romaji: "Kyuu ni omoidashita." }] },
      { japanese: "始める", romaji: "hajimeru", english: "To begin (transitive)", examples: [{ jp: "授業を 始める。", en: "Start class.", romaji: "Jugyou wo hajimeru." }, { jp: "食べ 始める。", en: "Start eating.", romaji: "Tabe hajimeru." }] },
      { japanese: "終わる", romaji: "owaru", english: "To end", examples: [{ jp: "冬が 終わる。", en: "Winter ends.", romaji: "Fuyu ga owaru." }, { jp: "宿題が 終わった。", en: "Homework finished.", romaji: "Shukudai ga owatta." }] },
      { japanese: "頼む", romaji: "tanomu", english: "To request/ask", examples: [{ jp: "水を 頼む。", en: "Ask for water.", romaji: "Mizu wo tanomu." }, { jp: "友達に 頼む。", en: "Ask a friend.", romaji: "Tomodachi ni tanomu." }] },
      { japanese: "並ぶ", romaji: "narabu", english: "To line up", examples: [{ jp: "列に 並ぶ。", en: "Stand in line.", romaji: "Retsu ni narabu." }, { jp: "店に 並ぶ。", en: "Display in shop.", romaji: "Mise ni narabu." }] },
      { japanese: "渡す", romaji: "watasu", english: "To hand over", examples: [{ jp: "塩を 渡す。", en: "Pass salt.", romaji: "Shio wo watasu." }, { jp: "手紙を 渡す。", en: "Hand over letter.", romaji: "Tegami wo watasu." }] }
    ]
  },
  {
    id: 18,
    title: "Verbs: Communication",
    description: "Speaking, listening, and interacting",
    words: [
      { japanese: "話す", romaji: "hanasu", english: "To speak", examples: [{ jp: "日本語を 話す。", en: "Speak Japanese.", romaji: "Nihongo wo hanasu." }, { jp: "友達と 話す。", en: "Talk with friend.", romaji: "Tomodachi to hanasu." }] },
      { japanese: "聞く", romaji: "kiku", english: "To listen/ask", examples: [{ jp: "音楽を 聞く。", en: "Listen to music.", romaji: "Ongaku wo kiku." }, { jp: "先生に 聞く。", en: "Ask teacher.", romaji: "Sensei ni kiku." }] },
      { japanese: "言う", romaji: "iu", english: "To say", examples: [{ jp: "ありがとうと 言う。", en: "Say thank you.", romaji: "Arigatou to iu." }, { jp: "何も 言わない。", en: "Say nothing.", romaji: "Nani mo iwanai." }] },
      { japanese: "読む", romaji: "yomu", english: "To read", examples: [{ jp: "本を 読む。", en: "Read book.", romaji: "Hon wo yomu." }, { jp: "空気を 読む。", en: "Read the room.", romaji: "Kuuki wo yomu." }] },
      { japanese: "書く", romaji: "kaku", english: "To write", examples: [{ jp: "手紙を 書く。", en: "Write letter.", romaji: "Tegami wo kaku." }, { jp: "名前を 書く。", en: "Write name.", romaji: "Namae wo kaku." }] },
      { japanese: "見る", romaji: "miru", english: "To see/watch", examples: [{ jp: "映画を 見る。", en: "Watch movie.", romaji: "Eiga wo miru." }, { jp: "夢を 見る。", en: "Dream.", romaji: "Yume wo miru." }] },
      { japanese: "見せる", romaji: "miseru", english: "To show", examples: [{ jp: "パスポートを 見せる。", en: "Show passport.", romaji: "Pasupooto wo miseru." }, { jp: "写真を 見せる。", en: "Show photo.", romaji: "Shashin wo miseru." }] },
      { japanese: "教える", romaji: "oshieru", english: "To teach/tell", examples: [{ jp: "英語を 教える。", en: "Teach English.", romaji: "Eigo wo oshieru." }, { jp: "道を 教える。", en: "Tell the way.", romaji: "Michi wo oshieru." }] },
      { japanese: "習う", romaji: "narau", english: "To learn", examples: [{ jp: "ピアノを 習う。", en: "Learn piano.", romaji: "Piano wo narau." }, { jp: "先生に 習う。", en: "Learn from teacher.", romaji: "Sensei ni narau." }] },
      { japanese: "会う", romaji: "au", english: "To meet", examples: [{ jp: "友達に 会う。", en: "Meet friend.", romaji: "Tomodachi ni au." }, { jp: "昨日 会った。", en: "Met yesterday.", romaji: "Kinou atta." }] },
      { japanese: "電話する", romaji: "denwasuru", english: "To call", examples: [{ jp: "母に 電話する。", en: "Call mother.", romaji: "Haha ni denwasuru." }, { jp: "後で 電話する。", en: "Call later.", romaji: "Ato de denwasuru." }] },
      { japanese: "質問する", romaji: "shitsumonsuru", english: "To question", examples: [{ jp: "先生に 質問する。", en: "Ask teacher question.", romaji: "Sensei ni shitsumonsuru." }, { jp: "分からないことを質問する。", en: "Ask what you don't know.", romaji: "Wakaranai koto wo shitsumonsuru." }] },
      { japanese: "答える", romaji: "kotaeru", english: "To answer", examples: [{ jp: "質問に 答える。", en: "Answer question.", romaji: "Shitsumon ni kotaeru." }, { jp: "正しく 答える。", en: "Answer correctly.", romaji: "Tadashiku kotaeru." }] },
      { japanese: "呼ぶ", romaji: "yobu", english: "To call/invite", examples: [{ jp: "タクシーを 呼ぶ。", en: "Call taxi.", romaji: "Takushii wo yobu." }, { jp: "友達を 呼ぶ。", en: "Invite friend.", romaji: "Tomodachi wo yobu." }] },
      { japanese: "歌う", romaji: "utau", english: "To sing", examples: [{ jp: "歌を 歌う。", en: "Sing song.", romaji: "Uta wo utau." }, { jp: "カラオケで 歌う。", en: "Sing at karaoke.", romaji: "Karaoke de utau." }] },
      { japanese: "騒ぐ", romaji: "sawagu", english: "To make noise", examples: [{ jp: "教室で 騒ぐ。", en: "Make noise in class.", romaji: "Kyoushitsu de sawagu." }, { jp: "騒がないで。", en: "Don't make noise.", romaji: "Sawaganaide." }] },
      { japanese: "泣く", romaji: "naku", english: "To cry", examples: [{ jp: "子供が 泣く。", en: "Child cries.", romaji: "Kodomo ga naku." }, { jp: "映画で 泣く。", en: "Cry at movie.", romaji: "Eiga de naku." }] },
      { japanese: "笑う", romaji: "warau", english: "To laugh", examples: [{ jp: "大声で 笑う。", en: "Laugh loudly.", romaji: "Oogoe de warau." }, { jp: "ニコニコ 笑う。", en: "Smile.", romaji: "Nikoniko warau." }] },
      { japanese: "怒る", romaji: "okoru", english: "To get angry", examples: [{ jp: "父が 怒る。", en: "Father gets angry.", romaji: "Chichi ga okoru." }, { jp: "先生に 怒られる。", en: "Scolded by teacher.", romaji: "Sensei ni okorareru." }] },
      { japanese: "褒める", romaji: "homeru", english: "To praise", examples: [{ jp: "生徒を 褒める。", en: "Praise student.", romaji: "Seito wo homeru." }, { jp: "上司に 褒められる。", en: "Praised by boss.", romaji: "Joushi ni homerareru." }] },
      { japanese: "断る", romaji: "kotowaru", english: "To refuse", examples: [{ jp: "誘いを 断る。", en: "Refuse invitation.", romaji: "Sasoi wo kotowaru." }, { jp: "きっぱり 断る。", en: "Refuse flatly.", romaji: "Kippari kotowaru." }] },
      { japanese: "謝る", romaji: "ayamaru", english: "To apologize", examples: [{ jp: "すぐに 謝る。", en: "Apologize immediately.", romaji: "Sugu ni ayamaru." }, { jp: "誠心誠意 謝る。", en: "Apologize sincerely.", romaji: "Seishin seii ayamaru." }] },
      { japanese: "願う", romaji: "negau", english: "To wish/hope", examples: [{ jp: "成功を 願う。", en: "Wish for success.", romaji: "Seikou wo negau." }, { jp: "平和を 願う。", en: "Wish for peace.", romaji: "Heiwa wo negau." }] },
      { japanese: "祈る", romaji: "inoru", english: "To pray", examples: [{ jp: "神に 祈る。", en: "Pray to God.", romaji: "Kami ni inoru." }, { jp: "回復を 祈る。", en: "Pray for recovery.", romaji: "Kaifuku wo inoru." }] },
      { japanese: "信じる", romaji: "shinjiru", english: "To believe", examples: [{ jp: "自分を 信じる。", en: "Believe in oneself.", romaji: "Jibun wo shinjiru." }, { jp: "信じられない。", en: "Unbelievable.", romaji: "Shinjirarenai." }] },
      { japanese: "調べる", romaji: "shiraberu", english: "To investigate", examples: [{ jp: "辞書で 調べる。", en: "Check dictionary.", romaji: "Jisho de shiraberu." }, { jp: "原因を 調べる。", en: "Investigate cause.", romaji: "Genin wo shiraberu." }] },
      { japanese: "比べる", romaji: "kuraberu", english: "To compare", examples: [{ jp: "値段を 比べる。", en: "Compare prices.", romaji: "Nedan wo kuraberu." }, { jp: "背を 比べる。", en: "Compare height.", romaji: "Se wo kuraberu." }] },
      { japanese: "迎える", romaji: "mukaeru", english: "To welcome/greet", examples: [{ jp: "客を 迎える。", en: "Welcome guest.", romaji: "Kyaku wo mukaeru." }, { jp: "新年を 迎える。", en: "Welcome New Year.", romaji: "Shinnen wo mukaeru." }] },
      { japanese: "送る", romaji: "okuru", english: "To send/see off", examples: [{ jp: "駅まで 送る。", en: "See off to station.", romaji: "Eki made okuru." }, { jp: "生活を 送る。", en: "Lead a life.", romaji: "Seikatsu wo okuru." }] },
      { japanese: "挨拶する", romaji: "aisatsusuru", english: "To greet", examples: [{ jp: "元気に 挨拶する。", en: "Greet cheerfully.", romaji: "Genki ni aisatsusuru." }, { jp: "みんなに 挨拶する。", en: "Greet everyone.", romaji: "Minna ni aisatsusuru." }] }
    ]
  },
  {
    id: 19,
    title: "Verbs: Giving & Having",
    description: "Transactions and possession",
    words: [
      { japanese: "あげる", romaji: "ageru", english: "To give", examples: [{ jp: "花を あげる。", en: "Give flowers.", romaji: "Hana wo ageru." }, { jp: "プレゼントを あげる。", en: "Give a present.", romaji: "Purezento wo ageru." }] },
      { japanese: "もらう", romaji: "morau", english: "To receive", examples: [{ jp: "本を もらう。", en: "Receive book.", romaji: "Hon wo morau." }, { jp: "給料を もらう。", en: "Receive salary.", romaji: "Kyuuryou wo morau." }] },
      { japanese: "くれる", romaji: "kureru", english: "To give (to me)", examples: [{ jp: "姉が くれた。", en: "Sister gave me.", romaji: "Ane ga kureta." }, { jp: "電話を くれる。", en: "Give me a call.", romaji: "Denwa wo kureru." }] },
      { japanese: "貸す", romaji: "kasu", english: "To lend", examples: [{ jp: "お金を 貸す。", en: "Lend money.", romaji: "Okane wo kasu." }, { jp: "ペンを 貸して。", en: "Lend me a pen.", romaji: "Pen wo kashite." }] },
      { japanese: "借りる", romaji: "kariru", english: "To borrow", examples: [{ jp: "本を 借りる。", en: "Borrow book.", romaji: "Hon wo kariru." }, { jp: "トイレを 借りる。", en: "Use (borrow) toilet.", romaji: "Toire wo kariru." }] },
      { japanese: "買う", romaji: "kau", english: "To buy", examples: [{ jp: "服を 買う。", en: "Buy clothes.", romaji: "Fuku wo kau." }, { jp: "安く 買う。", en: "Buy cheap.", romaji: "Yasuku kau." }] },
      { japanese: "売る", romaji: "uru", english: "To sell", examples: [{ jp: "車を 売る。", en: "Sell car.", romaji: "Kuruma wo uru." }, { jp: "家を 売る。", en: "Sell house.", romaji: "Ie wo uru." }] },
      { japanese: "払う", romaji: "harau", english: "To pay", examples: [{ jp: "お金を 払う。", en: "Pay money.", romaji: "Okane wo harau." }, { jp: "カードで 払う。", en: "Pay by card.", romaji: "Kaado de harau." }] },
      { japanese: "返す", romaji: "kaesu", english: "To return", examples: [{ jp: "本を 返す。", en: "Return book.", romaji: "Hon wo kaesu." }, { jp: "恩を 返す。", en: "Repay favor.", romaji: "On wo kaesu." }] },
      { japanese: "要る", romaji: "iru", english: "To need", examples: [{ jp: "ビザが 要る。", en: "Visa is needed.", romaji: "Biza ga iru." }, { jp: "要らない。", en: "Don't need.", romaji: "Iranai." }] },
      { japanese: "ある", romaji: "aru", english: "To have/exist", examples: [{ jp: "時間が ある。", en: "Have time.", romaji: "Jikan ga aru." }, { jp: "約束が ある。", en: "Have appointment.", romaji: "Yakusoku ga aru." }] },
      { japanese: "貯める", romaji: "tameru", english: "To save (money)", examples: [{ jp: "お金を 貯める。", en: "Save money.", romaji: "Okane wo tameru." }, { jp: "水を 貯める。", en: "Save/store water.", romaji: "Mizu wo tameru." }] },
      { japanese: "選ぶ", romaji: "erabu", english: "To choose", examples: [{ jp: "好きなのを 選ぶ。", en: "Choose what you like.", romaji: "Suki na no wo erabu." }, { jp: "道を選ぶ。", en: "Choose path.", romaji: "Michi wo erabu." }] },
      { japanese: "決める", romaji: "kimeru", english: "To decide", examples: [{ jp: "日時を 決める。", en: "Decide date/time.", romaji: "Nichiji wo kimeru." }, { jp: "心を 決める。", en: "Make up mind.", romaji: "Kokoro wo kimeru." }] },
      { japanese: "変える", romaji: "kaeru", english: "To change", examples: [{ jp: "予定を 変える。", en: "Change plans.", romaji: "Yotei wo kaeru." }, { jp: "髪型を 変える。", en: "Change hairstyle.", romaji: "Kamigata wo kaeru." }] },
      { japanese: "変わる", romaji: "kawaru", english: "To change (intransitive)", examples: [{ jp: "信号が 変わる。", en: "Light changes.", romaji: "Shingou ga kawaru." }, { jp: "季節が 変わる。", en: "Season changes.", romaji: "Kisetsu ga kawaru." }] },
      { japanese: "届ける", romaji: "todokeru", english: "To deliver", examples: [{ jp: "荷物を 届ける。", en: "Deliver package.", romaji: "Nimotsu wo todokeru." }, { jp: "警察に 届ける。", en: "Report to police.", romaji: "Keisatsu ni todokeru." }] },
      { japanese: "届く", romaji: "todoku", english: "To reach/arrive", examples: [{ jp: "手紙が 届く。", en: "Letter arrives.", romaji: "Tegami ga todoku." }, { jp: "手が 届く。", en: "Hand reaches.", romaji: "Te ga todoku." }] },
      { japanese: "並べる", romaji: "naraberu", english: "To line up (transitive)", examples: [{ jp: "椅子を 並べる。", en: "Line up chairs.", romaji: "Isu wo naraberu." }, { jp: "商品を 並べる。", en: "Display goods.", romaji: "Shouhin wo naraberu." }] },
      { japanese: "手に入れる", romaji: "teniireru", english: "To obtain", examples: [{ jp: "情報を 手に入れる。", en: "Get info.", romaji: "Jouhou wo teniireru." }, { jp: "チャンスを 手に入れる。", en: "Get chance.", romaji: "Chansu wo teniireru." }] },
      { japanese: "失う", romaji: "ushinau", english: "To lose", examples: [{ jp: "職を 失う。", en: "Lose job.", romaji: "Shoku wo ushinau." }, { jp: "機会を 失う。", en: "Lose opportunity.", romaji: "Kikai wo ushinau." }] },
      { japanese: "勝つ", romaji: "katsu", english: "To win", examples: [{ jp: "試合に 勝つ。", en: "Win match.", romaji: "Shiai ni katsu." }, { jp: "自分に 勝つ。", en: "Overcome oneself.", romaji: "Jibun ni katsu." }] },
      { japanese: "負ける", romaji: "makeru", english: "To lose (game)", examples: [{ jp: "試合に 負ける。", en: "Lose match.", romaji: "Shiai ni makeru." }, { jp: "誘惑に 負ける。", en: "Give in to temptation.", romaji: "Yuuwaku ni makeru." }] },
      { japanese: "頑張る", romaji: "ganbaru", english: "To do one's best", examples: [{ jp: "毎日 頑張る。", en: "Try hard every day.", romaji: "Mainichi ganbaru." }, { jp: "頑張ってください。", en: "Good luck.", romaji: "Ganbatte kudasai." }] },
      { japanese: "役に立つ", romaji: "yakunitatsu", english: "To be useful", examples: [{ jp: "この本は 役に立つ。", en: "This book is useful.", romaji: "Kono hon wa yakunitatsu." }, { jp: "仕事の 役に立つ。", en: "Useful for work.", romaji: "Shigoto no yakunitatsu." }] },
      { japanese: "増やす", romaji: "fuyasu", english: "To increase", examples: [{ jp: "貯金を 増やす。", en: "Increase savings.", romaji: "Chokin wo fuyasu." }, { jp: "体重を 増やす。", en: "Gain weight.", romaji: "Taijuu wo fuyasu." }] },
      { japanese: "減らす", romaji: "herasu", english: "To decrease", examples: [{ jp: "ゴミを 減らす。", en: "Reduce waste.", romaji: "Gomi wo herasu." }, { jp: "体重を 減らす。", en: "Lose weight.", romaji: "Taijuu wo herasu." }] },
      { japanese: "下げる", romaji: "sageru", english: "To lower", examples: [{ jp: "頭を 下げる。", en: "Bow head.", romaji: "Atama wo sageru." }, { jp: "値段を 下げる。", en: "Lower price.", romaji: "Nedan wo sageru." }] },
      { japanese: "上げる", romaji: "ageru", english: "To raise", examples: [{ jp: "手を 上げる。", en: "Raise hand.", romaji: "Te wo ageru." }, { jp: "給料を 上げる。", en: "Raise salary.", romaji: "Kyuuryou wo ageru." }] },
      { japanese: "預ける", romaji: "azukeru", english: "To deposit", examples: [{ jp: "銀行に 預ける。", en: "Deposit in bank.", romaji: "Ginkou ni azukeru." }, { jp: "子供を 預ける。", en: "Leave child in care.", romaji: "Kodomo wo azukeru." }] }
    ]
  },
  {
    id: 20,
    title: "Adjectives: Condition",
    description: "Describing state, difficulty, and feelings",
    words: [
      { japanese: "良い", romaji: "ii / yoi", english: "Good", examples: [{ jp: "天気が 良い。", en: "Weather is good.", romaji: "Tenki ga ii." }, { jp: "頭が 良い。", en: "Smart.", romaji: "Atama ga ii." }] },
      { japanese: "悪い", romaji: "warui", english: "Bad", examples: [{ jp: "気分が 悪い。", en: "Feel sick.", romaji: "Kibun ga warui." }, { jp: "性格が 悪い。", en: "Bad personality.", romaji: "Seikaku ga warui." }] },
      { japanese: "大きい", romaji: "ookii", english: "Big", examples: [{ jp: "大きい 声。", en: "Loud voice.", romaji: "Ookii koe." }, { jp: "態度が 大きい。", en: "Arrogant.", romaji: "Taido ga ookii." }] },
      { japanese: "小さい", romaji: "chiisai", english: "Small", examples: [{ jp: "小さい 村。", en: "Small village.", romaji: "Chiisai mura." }, { jp: "気が 小さい。", en: "Timid.", romaji: "Ki ga chiisai." }] },
      { japanese: "新しい", romaji: "atarashii", english: "New", examples: [{ jp: "新しい 車。", en: "New car.", romaji: "Atarashii kuruma." }, { jp: "新しい 友達。", en: "New friend.", romaji: "Atarashii tomodachi." }] },
      { japanese: "古い", romaji: "furui", english: "Old", examples: [{ jp: "古い 本。", en: "Old book.", romaji: "Furui hon." }, { jp: "考えが 古い。", en: "Old-fashioned idea.", romaji: "Kangae ga furui." }] },
      { japanese: "難しい", romaji: "muzukashii", english: "Difficult", examples: [{ jp: "試験は 難しい。", en: "Exam is hard.", romaji: "Shiken wa muzukashii." }, { jp: "難しい 顔。", en: "Troubled face.", romaji: "Muzukashii kao." }] },
      { japanese: "易しい", romaji: "yasashii", english: "Easy", examples: [{ jp: "易しい 問題。", en: "Easy problem.", romaji: "Yasashii mondai." }, { jp: "易しい 日本語。", en: "Easy Japanese.", romaji: "Yasashii Nihongo." }] },
      { japanese: "高い", romaji: "takai", english: "High/Expensive", examples: [{ jp: "背が 高い。", en: "Tall.", romaji: "Se ga takai." }, { jp: "値段が 高い。", en: "Price is high.", romaji: "Nedan ga takai." }] },
      { japanese: "安い", romaji: "yasui", english: "Cheap", examples: [{ jp: "安い 服。", en: "Cheap clothes.", romaji: "Yasui fuku." }, { jp: "給料が 安い。", en: "Salary is low.", romaji: "Kyuuryou ga yasui." }] },
      { japanese: "低い", romaji: "hikui", english: "Low", examples: [{ jp: "背が 低い。", en: "Short (height).", romaji: "Se ga hikui." }, { jp: "声が 低い。", en: "Low voice.", romaji: "Koe ga hikui." }] },
      { japanese: "面白い", romaji: "omoshiroi", english: "Interesting/Funny", examples: [{ jp: "面白い 映画。", en: "Funny movie.", romaji: "Omoshiroi eiga." }, { jp: "面白い 人。", en: "Interesting person.", romaji: "Omoshiroi hito." }] },
      { japanese: "つまらない", romaji: "tsumaranai", english: "Boring", examples: [{ jp: "つまらない 話。", en: "Boring story.", romaji: "Tsumaranai hanashi." }, { jp: "つまらない 物ですが。", en: "It's nothing special (gift).", romaji: "Tsumaranai mono desu ga." }] },
      { japanese: "忙しい", romaji: "isogashii", english: "Busy", examples: [{ jp: "毎日 忙しい。", en: "Busy every day.", romaji: "Mainichi isogashii." }, { jp: "忙しい 朝。", en: "Busy morning.", romaji: "Isogashii asa." }] },
      { japanese: "暇", romaji: "hima", english: "Free", examples: [{ jp: "暇な 時。", en: "Free time.", romaji: "Hima na toki." }, { jp: "暇つぶし。", en: "Killing time.", romaji: "Himatsubushi." }] },
      { japanese: "大好き", romaji: "daisuki", english: "Love/Like a lot", examples: [{ jp: "猫が 大好き。", en: "Love cats.", romaji: "Neko ga daisuki." }, { jp: "大好きな 歌。", en: "Favorite song.", romaji: "Daisuki na uta." }] },
      { japanese: "嫌い", romaji: "kirai", english: "Hate/Dislike", examples: [{ jp: "嘘が 嫌い。", en: "Hate lies.", romaji: "Uso ga kirai." }, { jp: "嫌いな 食べ物。", en: "Disliked food.", romaji: "Kirai na tabemono." }] },
      { japanese: "得意", romaji: "tokui", english: "Good at", examples: [{ jp: "料理が 得意。", en: "Good at cooking.", romaji: "Ryouri ga tokui." }, { jp: "得意な 科目。", en: "Subject I'm good at.", romaji: "Tokui na kamoku." }] },
      { japanese: "苦手", romaji: "nigate", english: "Bad at/Dislike", examples: [{ jp: "運動が 苦手。", en: "Bad at sports.", romaji: "Undou ga nigate." }, { jp: "苦手な 人。", en: "Person I can't deal with.", romaji: "Nigate na hito." }] },
      { japanese: "きれい", romaji: "kirei", english: "Beautiful/Clean", examples: [{ jp: "きれいな 花。", en: "Beautiful flower.", romaji: "Kirei na hana." }, { jp: "部屋を きれいに。", en: "Clean the room.", romaji: "Heya wo kirei ni." }] },
      { japanese: "汚い", romaji: "kitanai", english: "Dirty", examples: [{ jp: "手が 汚い。", en: "Hands are dirty.", romaji: "Te ga kitanai." }, { jp: "字が 汚い。", en: "Messy handwriting.", romaji: "Ji ga kitanai." }] },
      { japanese: "静か", romaji: "shizuka", english: "Quiet", examples: [{ jp: "静かな 夜。", en: "Quiet night.", romaji: "Shizuka na yoru." }, { jp: "静かに して。", en: "Be quiet.", romaji: "Shizuka ni shite." }] },
      { japanese: "賑やか", romaji: "nigiyaka", english: "Lively", examples: [{ jp: "賑やかな 町。", en: "Lively town.", romaji: "Nigiyaka na machi." }, { jp: "パーティーは 賑やか。", en: "Party is lively.", romaji: "Paatii wa nigiyaka." }] },
      { japanese: "親切", romaji: "shinsetsu", english: "Kind", examples: [{ jp: "親切な 人。", en: "Kind person.", romaji: "Shinsetsu na hito." }, { jp: "親切に する。", en: "Be kind.", romaji: "Shinsetsu ni suru." }] },
      { japanese: "便利", romaji: "benri", english: "Convenient", examples: [{ jp: "便利な 店。", en: "Convenient shop.", romaji: "Benri na mise." }, { jp: "交通が 便利。", en: "Convenient transport.", romaji: "Koutsuu ga benri." }] },
      { japanese: "不便", romaji: "fuben", english: "Inconvenient", examples: [{ jp: "不便な 所。", en: "Inconvenient place.", romaji: "Fuben na tokoro." }, { jp: "足が 不便。", en: "Has trouble walking.", romaji: "Ashi ga fuben." }] },
      { japanese: "元気", romaji: "genki", english: "Healthy/Cheerful", examples: [{ jp: "元気な 子供。", en: "Energetic child.", romaji: "Genki na kodomo." }, { jp: "お元気ですか。", en: "How are you?", romaji: "Ogenki desu ka." }] },
      { japanese: "有名", romaji: "yuumei", english: "Famous", examples: [{ jp: "有名な 俳優。", en: "Famous actor.", romaji: "Yuumei na haiyuu." }, { jp: "ここは 有名です。", en: "This place is famous.", romaji: "Koko wa yuumei desu." }] },
      { japanese: "大切", romaji: "taisetsu", english: "Important/Precious", examples: [{ jp: "大切な 友達。", en: "Precious friend.", romaji: "Taisetsu na tomodachi." }, { jp: "大切に する。", en: "Cherish.", romaji: "Taisetsu ni suru." }] },
      { japanese: "大丈夫", romaji: "daijoubu", english: "Okay/Alright", examples: [{ jp: "大丈夫ですか。", en: "Are you okay?", romaji: "Daijoubu desu ka." }, { jp: "時間は 大丈夫。", en: "Time is okay.", romaji: "Jikan wa daijoubu." }] }
    ]
  }
];
