export const chunk9 = [
  {
    id: 41,
    level: "N4",
    title: "Verbs: State & Change",
    description: "Verbs describing transitions and physical states",
    words: [
      { japanese: "変わる", romaji: "kawaru", english: "To change (intransitive)", examples: [{ jp: "信号が 変わる。", en: "The light changes.", romaji: "Shingou ga kawaru." }, { jp: "予定が 変わった。", en: "Schedule changed.", romaji: "Yotei ga kawatta." }] },
      { japanese: "変える", romaji: "kaeru", english: "To change (transitive)", examples: [{ jp: "服を 変える。", en: "Change clothes.", romaji: "Fuku wo kaeru." }, { jp: "気分を 変える。", en: "Change one's mood.", romaji: "Kibun wo kaeru." }] },
      { japanese: "動く", romaji: "ugoku", english: "To move (intransitive)", examples: [{ jp: "機械が 動いている。", en: "Machine is moving.", romaji: "Kikai ga ugoiteiru." }, { jp: "体が 動かない。", en: "Body won't move.", romaji: "Karada ga ugokanai." }] },
      { japanese: "動かす", romaji: "ugokasu", english: "To move (transitive)", examples: [{ jp: "机を 動かす。", en: "Move the desk.", romaji: "Tsukue wo ugokasu." }, { jp: "心を 動かす。", en: "Move one's heart (touch).", romaji: "Kokoro wo ugokasu." }] },
      { japanese: "止まる", romaji: "tomaru", english: "To stop (intransitive)", examples: [{ jp: "時計が 止まった。", en: "Watch stopped.", romaji: "Tokei ga tomatta." }, { jp: "車が 止まる。", en: "Car stops.", romaji: "Kuruma ga tomaru." }] },
      { japanese: "止める", romaji: "tomeru", english: "To stop (transitive)", examples: [{ jp: "タクシーを 止める。", en: "Stop a taxi.", romaji: "Takushii wo tomeru." }, { jp: "タバコを 止める。", en: "Stop smoking.", romaji: "Tabako wo tomeru." }] },
      { japanese: "上がる", romaji: "agaru", english: "To go up (intransitive)", examples: [{ jp: "階段を 上がる。", en: "Go up stairs.", romaji: "Kaidan wo agaru." }, { jp: "成績が 上がった。", en: "Grades went up.", romaji: "Seiseki ga agatta." }] },
      { japanese: "上げる", romaji: "ageru", english: "To raise (transitive)", examples: [{ jp: "手を 上げる。", en: "Raise a hand.", romaji: "Te wo ageru." }, { jp: "声を 上げる。", en: "Raise one's voice.", romaji: "Koe wo ageru." }] },
      { japanese: "下がる", romaji: "sagaru", english: "To go down (intransitive)", examples: [{ jp: "熱が 下がった。", en: "Fever went down.", romaji: "Netsu ga sagatta." }, { jp: "物価が 下がる。", en: "Prices drop.", romaji: "Bukka ga sagaru." }] },
      { japanese: "下げる", romaji: "sageru", english: "To lower (transitive)", examples: [{ jp: "頭を 下げる。", en: "Lower one's head.", romaji: "Atama wo sageru." }, { jp: "値段を 下げる。", en: "Lower the price.", romaji: "Nedan wo sageru." }] },
      { japanese: "閉まる", romaji: "shimaru", english: "To be closed (intransitive)", examples: [{ jp: "ドアが 閉まる。", en: "Door closes.", romaji: "Doa ga shimaru." }, { jp: "店が 閉まっている。", en: "Shop is closed.", romaji: "Mise ga shimatteiru." }] },
      { japanese: "閉める", romaji: "shimeru", english: "To close (transitive)", examples: [{ jp: "窓を 閉める。", en: "Close the window.", romaji: "Mado wo shimeru." }, { jp: "カーテンを 閉める。", en: "Close the curtains.", romaji: "Kaaten wo shimeru." }] },
      { japanese: "開く", romaji: "aku", english: "To be open (intransitive)", examples: [{ jp: "店が 開いた。", en: "The shop opened.", romaji: "Mise ga aita." }, { jp: "穴が 開く。", en: "A hole opens.", romaji: "Ana ga aku." }] },
      { japanese: "開ける", romaji: "akeru", english: "To open (transitive)", examples: [{ jp: "鍵を 開ける。", en: "Open the lock.", romaji: "Kagi wo akeru." }, { jp: "口を 開ける。", en: "Open one's mouth.", romaji: "Kuchi wo akeru." }] },
      { japanese: "消える", romaji: "kieru", english: "To go out/disappear", examples: [{ jp: "電気が 消えた。", en: "Electricity went out.", romaji: "Denki ga kieta." }, { jp: "姿が 消える。", en: "Appearance disappears.", romaji: "Sugata ga kieru." }] },
      { japanese: "消す", romaji: "kesu", english: "To turn off/erase", examples: [{ jp: "火を 消す。", en: "Extinguish fire.", romaji: "Hi wo kesu." }, { jp: "消しゴムで 消す。", en: "Erase with eraser.", romaji: "Keshigomu de kesu." }] },
      { japanese: "点く", romaji: "tsuku", english: "To be turned on", examples: [{ jp: "電気が 点いた。", en: "Light turned on.", romaji: "Denki ga tsuita." }, { jp: "火が 点く。", en: "Fire ignites.", romaji: "Hi ga tsuku." }] },
      { japanese: "点ける", romaji: "tsukeru", english: "To turn on", examples: [{ jp: "テレビを 点ける。", en: "Turn on the TV.", romaji: "Terebi wo tsukeru." }, { jp: "タバコに 火を点ける。", en: "Light a cigarette.", romaji: "Tabako ni hi wo tsukeru." }] },
      { japanese: "壊れる", romaji: "kowareru", english: "To be broken", examples: [{ jp: "おもちゃが 壊れた。", en: "The toy is broken.", romaji: "Omocha ga kowareta." }, { jp: "壊れた 時計。", en: "Broken watch.", romaji: "Kowareta tokei." }] },
      { japanese: "壊す", romaji: "kowasu", english: "To break", examples: [{ jp: "壁を 壊す。", en: "Break the wall.", romaji: "Kabe wo kowasu." }, { jp: "お腹を 壊す。", en: "Upset one's stomach.", romaji: "Onaka wo kowasu." }] },
      { japanese: "汚れる", romaji: "yogoreru", english: "To get dirty", examples: [{ jp: "服が 汚れた。", en: "Clothes got dirty.", romaji: "Fuku ga yogoreta." }, { jp: "汚れた 水。", en: "Dirty water.", romaji: "Yogoreta mizu." }] },
      { japanese: "汚す", romaji: "yogosu", english: "To make dirty", examples: [{ jp: "靴を 汚す。", en: "Dirty the shoes.", romaji: "Kutsu wo yogosu." }, { jp: "手を 汚さないで。", en: "Don't get your hands dirty.", romaji: "Te wo yogosanaide." }] },
      { japanese: "落ちる", romaji: "ochiru", english: "To fall down", examples: [{ jp: "試験に 落ちる。", en: "Fail (fall) the test.", romaji: "Shiken ni ochiru." }, { jp: "財布が 落ちた。", en: "Wallet fell.", romaji: "Saifu ga ochita." }] },
      { japanese: "落とす", romaji: "otosu", english: "To drop", examples: [{ jp: "グラスを 落とす。", en: "Drop a glass.", romaji: "Gurasu wo otosu." }, { jp: "スピードを 落とす。", en: "Drop (lower) speed.", romaji: "Supiido wo otosu." }] },
      { japanese: "割れる", romaji: "wareru", english: "To crack/shatter", examples: [{ jp: "窓ガラスが 割れた。", en: "Window glass shattered.", romaji: "Madogarasu ga wareta." }, { jp: "卵が 割れる。", en: "Egg cracks.", romaji: "Tamago ga wareru." }] },
      { japanese: "割る", romaji: "waru", english: "To break/divide", examples: [{ jp: "お皿を 割る。", en: "Break a plate.", romaji: "Osara wo waru." }, { jp: "十を 二で割る。", en: "Divide 10 by 2.", romaji: "Juu wo ni de waru." }] },
      { japanese: "破れる", romaji: "yabureru", english: "To be torn", examples: [{ jp: "紙が 破れた。", en: "Paper is torn.", romaji: "Kami ga yabureta." }, { jp: "服が 破れる。", en: "Clothes get torn.", romaji: "Fuku ga yabureru." }] },
      { japanese: "破る", romaji: "yaburu", english: "To tear/break", examples: [{ jp: "約束を 破る。", en: "Break a promise.", romaji: "Yakusoku wo yaburu." }, { jp: "紙を 破る。", en: "Tear the paper.", romaji: "Kami wo yaburu." }] },
      { japanese: "濡れる", romaji: "nureru", english: "To get wet", examples: [{ jp: "雨で 濡れた。", en: "Got wet in the rain.", romaji: "Ame de nureta." }, { jp: "濡れた タオル。", en: "Wet towel.", romaji: "Nureta taoru." }] },
      { japanese: "渇く", romaji: "kawaku", english: "To get dry/thirsty", examples: [{ jp: "喉が 渇いた。", en: "Thirsty.", romaji: "Nodo ga kawaita." }, { jp: "洗濯物が 渇く。", en: "Laundry dries.", romaji: "Sentakumono ga kawaku." }] }
    ]
  },
  {
    id: 42,
    level: "N4",
    title: "Nature & Environment",
    description: "Plants, animals, and earth terms",
    words: [
      { japanese: "自然", romaji: "shizen", english: "Nature", examples: [{ jp: "自然を 守る。", en: "Protect nature.", romaji: "Shizen wo mamoru." }, { jp: "自然 豊かな場所。", en: "Nature-rich place.", romaji: "Shizen yutakana basho." }] },
      { japanese: "森林", romaji: "shinrin", english: "Forest/Woods", examples: [{ jp: "深い 森林。", en: "Deep forest.", romaji: "Fukai shinrin." }, { jp: "森林 浴。", en: "Forest bathing.", romaji: "Shinrinyoku." }] },
      { japanese: "植物", romaji: "shokubutsu", english: "Plants/Vegetation", examples: [{ jp: "植物に 水をやる。", en: "Water the plants.", romaji: "Shokubutsu ni mizu wo yaru." }, { jp: "珍しい 植物。", en: "Rare plant.", romaji: "Mezurashii shokubutsu." }] },
      { japanese: "動物", romaji: "doubutsu", english: "Animals", examples: [{ jp: "動物 園。", en: "Zoo.", romaji: "Doubutsuen." }, { jp: "可愛い 動物。", en: "Cute animal.", romaji: "Kawai doubutsu." }] },
      { japanese: "虫", romaji: "mushi", english: "Insect", examples: [{ jp: "虫の 音。", en: "Sound of insects.", romaji: "Mushi no ne." }, { jp: "虫が 苦手だ。", en: "Bad with bugs.", romaji: "Mushi ga nigate da." }] },
      { japanese: "鳥", romaji: "tori", english: "Bird", examples: [{ jp: "鳥の ように飛ぶ。", en: "Fly like a bird.", romaji: "Tori no youni tobu." }, { jp: "渡り鳥。", en: "Migratory bird.", romaji: "Wataridori." }] },
      { japanese: "魚", romaji: "sakana", english: "Fish", examples: [{ jp: "魚を 釣る。", en: "Catch fish.", romaji: "Sakana wo tsuru." }, { jp: "熱帯魚。", en: "Tropical fish.", romaji: "Nettaigyo." }] },
      { japanese: "海", romaji: "umi", english: "Sea/Ocean", examples: [{ jp: "海で 泳ぐ。", en: "Swim in the sea.", romaji: "Umi de oyogu." }, { jp: "青い 海。", en: "Blue ocean.", romaji: "Aoi umi." }] },
      { japanese: "川", romaji: "kawa", english: "River", examples: [{ jp: "川の 流れ。", en: "River flow.", romaji: "Kawa no nagare." }, { jp: "川に 落ちる。", en: "Fall in the river.", romaji: "Kawa ni ochiru." }] },
      { japanese: "山", romaji: "yama", english: "Mountain", examples: [{ jp: "山に 登る。", en: "Climb a mountain.", romaji: "Yama ni noboru." }, { jp: "高い 山。", en: "High mountain.", romaji: "Takai yama." }] },
      { japanese: "島", romaji: "shima", english: "Island", examples: [{ jp: "無人 島。", en: "Deserted island.", romaji: "Mujintou." }, { jp: "美しい 島。", en: "Beautiful island.", romaji: "Utsukushii shima." }] },
      { japanese: "海岸", romaji: "kaigan", english: "Coast/Seaside", examples: [{ jp: "海岸を 散歩する。", en: "Walk on the coast.", romaji: "Kaigan wo sanposuru." }, { jp: "海岸 線。", en: "Coastline.", romaji: "Kaigansen." }] },
      { japanese: "砂浜", romaji: "sunahama", english: "Sandy beach", examples: [{ jp: "砂浜で 遊ぶ。", en: "Play on the beach.", romaji: "Sunahama de asobu." }, { jp: "白い 砂浜。", en: "White sandy beach.", romaji: "Shiroi sunahama." }] },
      { japanese: "環境", romaji: "kankyou", english: "Environment", examples: [{ jp: "環境を 考える。", en: "Think of environment.", romaji: "Kankyou wo kangaeru." }, { jp: "社会 環境。", en: "Social environment.", romaji: "Shakai kankyou." }] },
      { japanese: "汚染", romaji: "osen", english: "Pollution", examples: [{ jp: "大気 汚染。", en: "Air pollution.", romaji: "Taiki osen." }, { jp: "環境 汚染。", en: "Env. pollution.", romaji: "Kankyou osen." }] },
      { japanese: "空気", romaji: "kuuki", english: "Air/Atmosphere", examples: [{ jp: "空気が おいしい。", en: "Air is fresh.", romaji: "Kuuki ga oishii." }, { jp: "空気 公害。", en: "Air pollution.", romaji: "Kuuki kougai." }] },
      { japanese: "太陽", romaji: "taiyou", english: "Sun", examples: [{ jp: "太陽の 光。", en: "Sunlight.", romaji: "Taiyou no hikari." }, { jp: "太陽系。", en: "Solar system.", romaji: "Taiyoukei." }] },
      { japanese: "地球", romaji: "chikyuu", english: "Earth", examples: [{ jp: "大切な 地球。", en: "Precious Earth.", romaji: "Taisetsuna chikyuu." }, { jp: "地球 温暖化。", en: "Global warming.", romaji: "Chikyuu ondanka." }] },
      { japanese: "緑", romaji: "midori", english: "Green/Greenery", examples: [{ jp: "公園の 緑。", en: "Park greenery.", romaji: "Kouen no midori." }, { jp: "緑が 多い。", en: "Lots of greenery.", romaji: "Midori ga ooi." }] },
      { japanese: "花", romaji: "hana", english: "Flower", examples: [{ jp: "花が 咲く。", en: "Flowers bloom.", romaji: "Hana ga saku." }, { jp: "花瓶に 飾る。", en: "Display in vase.", romaji: "Kabin ni kazaru." }] },
      { japanese: "木", romaji: "ki", english: "Tree", examples: [{ jp: "大きな 木。", en: "Big tree.", romaji: "Ookina ki." }, { jp: "木を 植える。", en: "Plant a tree.", romaji: "Ki wo ueru." }] },
      { japanese: "草", romaji: "kusa", english: "Grass/Weeds", examples: [{ jp: "草を 滑る。", en: "Slide on grass.", romaji: "Kusa wo suberu." }, { jp: "雑草。", en: "Weeds.", romaji: "Zassou." }] },
      { japanese: "庭", romaji: "niwa", english: "Garden/Yard", examples: [{ jp: "庭に 出る。", en: "Go into the garden.", romaji: "Niwa ni deru." }, { jp: "家の 庭。", en: "House garden.", romaji: "Ie no niwa." }] },
      { japanese: "景色", romaji: "keshiki", english: "Scenery/View", examples: [{ jp: "高い所からの景色。", en: "View from a high place.", romaji: "Takai tokoro kara no keshiki." }, { jp: "きれいな 景色。", en: "Beautiful view.", romaji: "Kireina keshiki." }] },
      { japanese: "宇宙", romaji: "uchuu", english: "Universe/Space", examples: [{ jp: "広い 宇宙。", en: "Vast universe.", romaji: "Hiroi uchuu." }, { jp: "宇宙 飛行士。", en: "Astronaut.", romaji: "Uchuu hikoushi." }] },
      { japanese: "資源", romaji: "shigen", english: "Resources", examples: [{ jp: "天然 資源。", en: "Natural resources.", romaji: "Tennen shigen." }, { jp: "資源を 節約する。", en: "Save resources.", romaji: "Shigen wo setsuyaku suru." }] },
      { japanese: "ゴミ", romaji: "gomi", english: "Trash/Garbage", examples: [{ jp: "ゴミを 捨てる。", en: "Throw away trash.", romaji: "Gomi wo suteru." }, { jp: "燃えない ゴミ。", en: "Non-burnable trash.", romaji: "Moenai gomi." }] },
      { japanese: "捨てる", romaji: "suteru", english: "To throw away", examples: [{ jp: "古い服を捨てる。", en: "Throw away old clothes.", romaji: "Furui fuku wo suteru." }, { jp: "ゴミ箱に 捨てる。", en: "Throw in the bin.", romaji: "Gomibako ni suteru." }] },
      { japanese: "拾う", romaji: "hirou", english: "To pick up", examples: [{ jp: "財布を 拾う。", en: "Pick up a wallet.", romaji: "Saifu wo hirou." }, { jp: "ゴミを 拾う。", en: "Pick up trash.", romaji: "Gomi wo hirou." }] },
      { japanese: " recycle ", romaji: "risaikuru", english: "Recycle", examples: [{ jp: "リサイクルする。", en: "To recycle.", romaji: "Risaikuru suru." }, { jp: "リサイクル ショップ。", en: "Second-hand shop.", romaji: "Risaikuru shoppu." }] }
    ]
  },
  {
    id: 43,
    level: "N4",
    title: "News & Media",
    description: "Vocabulary for information, journalism, and broadcasting",
    words: [
      { japanese: "ニュース", romaji: "nyuusu", english: "News", examples: [{ jp: "最新の ニュース。", en: "Latest news.", romaji: "Saishin no nyuusu." }, { jp: "ニュースを 聞く。", en: "Hear the news.", romaji: "Nyuusu wo kiku." }] },
      { japanese: "事件", romaji: "jiken", english: "Incident/Case", examples: [{ jp: "大変な 事件。", en: "Serious incident.", romaji: "Taihenna jiken." }, { jp: "事件の 犯人。", en: "Culprit of the case.", romaji: "Jiken no hannin." }] },
      { japanese: "事故", romaji: "jiko", english: "Accident", examples: [{ jp: "事故が 起きる。", en: "Accident happens.", romaji: "Jiko ga okiru." }, { jp: "不慮の 事故。", en: "Unexpected accident.", romaji: "Furyo no jiko." }] },
      { japanese: "政治", romaji: "seiji", english: "Politics", examples: [{ jp: "日本の 政治。", en: "Japanese politics.", romaji: "Nihon no seiji." }, { jp: "政治に 詳しい。", en: "Knowledgable in politics.", romaji: "Seiji ni kuwashii." }] },
      { japanese: "経済", romaji: "keizai", english: "Economy", examples: [{ jp: "世界の 経済。", en: "World economy.", romaji: "Sekai no keizai." }, { jp: "不 経済。", en: "Uneconomical.", romaji: "Fu keizai." }] },
      { japanese: "社会", romaji: "shakai", english: "Society", examples: [{ jp: "現代 社会。", en: "Modern society.", romaji: "Gendai shakai." }, { jp: "社会 問題。", en: "Social issues.", romaji: "Shakai mondai." }] },
      { japanese: "文化", romaji: "bunka", english: "Culture", examples: [{ jp: "異 文化。", en: "Different culture.", romaji: "I bunka." }, { jp: "伝統 文化。", en: "Traditional culture.", romaji: "Dentou bunka." }] },
      { japanese: "情報", romaji: "jouhou", english: "Information", examples: [{ jp: "情報を 集める。", en: "Gather information.", romaji: "Jouhou wo atsumeru." }, { jp: "個人 情報。", en: "Personal info.", romaji: "Kojin jouhou." }] },
      { japanese: "放送する", romaji: "housousuru", english: "To broadcast", examples: [{ jp: "テレビで 放送する。", en: "Broadcast on TV.", romaji: "Terebi de housousuru." }, { jp: "実況 放送。", en: "Live broadcast.", romaji: "Jikkyou housou." }] },
      { japanese: "記事", romaji: "kiji", english: "Article", examples: [{ jp: "新聞の 記事。", en: "Newspaper article.", romaji: "Shinbun no kiji." }, { jp: "面白い 記事。", en: "Interesting article.", romaji: "Omoshiroi kiji." }] },
      { japanese: "番組", romaji: "bangumi", english: "Program (TV/Radio)", examples: [{ jp: "好きな 番組。", en: "Favorite program.", romaji: "Suki na bangumi." }, { jp: "テレビ 番組。", en: "TV show.", romaji: "Terebi bangumi." }] },
      { japanese: "新聞", romaji: "shinbun", english: "Newspaper", examples: [{ jp: "新聞を 読む。", en: "Read the paper.", romaji: "Shinbun wo yomu." }, { jp: "英字 新聞。", en: "English newspaper.", romaji: "Eiji shinbun." }] },
      { japanese: "雑誌", romaji: "zasshi", english: "Magazine", examples: [{ jp: "流行の 雑誌。", en: "Trendy magazine.", romaji: "Ryuukou no zasshi." }, { jp: "雑誌の 特集。", en: "Magazine feature.", romaji: "Zasshi no tokushuu." }] },
      { japanese: "記者", romaji: "kisha", english: "Reporter/Journalist", examples: [{ jp: "新聞 記者。", en: "Newspaper reporter.", romaji: "Shinbun kisha." }, { jp: "記者 会見。", en: "Press conference.", romaji: "Kisha kaiken." }] },
      { japanese: "動画", romaji: "douga", english: "Video", examples: [{ jp: "動画 サイト。", en: "Video site.", romaji: "Douga saito." }, { jp: "動画を 撮る。", en: "Film a video.", romaji: "Douga wo toru." }] },
      { japanese: "音楽", romaji: "ongaku", english: "Music", examples: [{ jp: "クラシック 音楽。", en: "Classic music.", romaji: "Kurashikku ongaku." }, { jp: "音楽を 聴く。", en: "Listen to music.", romaji: "Ongaku wo kiku." }] },
      { japanese: "映画", romaji: "eiga", english: "Movie", examples: [{ jp: "映画を 見に行く。", en: "Go to see a movie.", romaji: "Eiga wo mi ni iku." }, { jp: "映画 監督。", en: "Film director.", romaji: "Eiga kantoku." }] },
      { japanese: "流行する", romaji: "ryuukousuru", english: "To be in fashion", examples: [{ jp: "歌が 流行している。", en: "The song is popular.", romaji: "Uta ga ryuukou shiteiru." }, { jp: "流行りに 乗る。", en: "Follow the trend.", romaji: "Hayari ni noru." }] },
      { japanese: "話題", romaji: "wadai", english: "Topic/Subject", examples: [{ jp: "最新の 話題。", en: "Latest topic.", romaji: "Saishin no wadai." }, { jp: "話題に なる。", en: "Become a topic.", romaji: "Wadai ni naru." }] },
      { japanese: "噂", romaji: "uwasa", english: "Rumor", examples: [{ jp: "変な 噂。", en: "Strange rumor.", romaji: "Hen na uwasa." }, { jp: "噂を 聞いた。", en: "Heard a rumor.", romaji: "Uwasa wo kiita." }] },
      { japanese: "発表する", romaji: "happyou suru", english: "To announce/present", examples: [{ jp: "結果を 発表する。", en: "Announce results.", romaji: "Kekka wo happyou suru." }, { jp: "自己 紹介の発表。", en: "Intro presentation.", romaji: "Jikoshoukai no happyou." }] },
      { japanese: "広告", romaji: "koukoku", english: "Advertisement", examples: [{ jp: "テレビの 広告。", en: "TV ad.", romaji: "Terebi no koukoku." }, { jp: "広告を 出す。", en: "Put out an ad.", romaji: "Koukoku wo dasu." }] },
      { japanese: "中継", romaji: "chuukei", english: "Relay/Live coverage", examples: [{ jp: "スポーツ 中継。", en: "Sports coverage.", romaji: "Supootsu chuukei." }, { jp: "生 中継。", en: "Live relay.", romaji: "Nama chuukei." }] },
      { japanese: "編集する", romaji: "henshuu suru", english: "To edit", examples: [{ jp: "動画を 編集する。", en: "Edit a video.", romaji: "Douga wo henshuu suru." }, { jp: "本を 編集する。", en: "Edit a book.", romaji: "Hon wo henshuu suru." }] },
      { japanese: "公開する", romaji: "koukai suru", english: "To release/publicize", examples: [{ jp: "映画が 公開された。", en: "The movie was released.", romaji: "Eiga ga koukaisareda." }, { jp: "情報の 公開。", en: "Disclosure of info.", romaji: "Jouhou no koukai." }] },
      { japanese: "真実", romaji: "shinjitsu", english: "Truth", examples: [{ jp: "真実を 知りたい。", en: "Want to know truth.", romaji: "Shinjitsu wo shiritai." }, { jp: "意外な 真実。", en: "Unexpected truth.", romaji: "Igainas shinjitsu." }] },
      { japanese: "嘘", romaji: "uso", english: "Lie", examples: [{ jp: "嘘を つく。", en: "Tell a lie.", romaji: "Uso wo tsuku." }, { jp: "真っ赤な 嘘。", en: "Downright lie.", romaji: "Makka na uso." }] },
      { japanese: "意見", romaji: "iken", english: "Opinion", examples: [{ jp: "個人の 意見。", en: "Personal opinion.", romaji: "Kojin no iken." }, { jp: "貴重な 意見。", en: "Valuable opinion.", romaji: "Kichouna iken." }] },
      { japanese: "批判する", romaji: "hihan suru", english: "To criticize", examples: [{ jp: "政府を 批判する。", en: "Criticize gov.", romaji: "Seifu wo hihan suru." }, { jp: "厳しい 批判。", en: "Strict criticism.", romaji: "Kibishii hihan." }] },
      { japanese: "支持する", romaji: "shiji suru", english: "To support", examples: [{ jp: "計画を 支持する。", en: "Support the plan.", romaji: "Keikaku wo shiji suru." }, { jp: "国民の 支持。", en: "Public support.", romaji: "Kokumin no shiji." }] }
    ]
  },
  {
    id: 44,
    level: "N4",
    title: "Travel & Hospitality",
    description: "Words for staying at hotels and being a guest",
    words: [
      { japanese: "予約", romaji: "yoyaku", english: "Reservation", examples: [{ jp: "ホテルの 予約。", en: "Hotel booking.", romaji: "Hoteru no yoyaku." }, { jp: "予約を キャンセルする。", en: "Cancel booking.", romaji: "Yoyaku wo kyanserusuru." }] },
      { japanese: "宿泊する", romaji: "shukuhakusuru", english: "To stay overnight", examples: [{ jp: "旅館に 宿泊する。", en: "Stay at a ryokan.", romaji: "Ryokan ni shukuhakusuru." }, { jp: "宿泊 施設。", en: "Lodging facility.", romaji: "Shukuhaku shisetsu." }] },
      { japanese: "案内する", romaji: "annaisuru", english: "To guide/show around", examples: [{ jp: "町を 案内する。", en: "Show the town around.", romaji: "Machi wo annaisuru." }, { jp: "案内係。", en: "Guide staff.", romaji: "Annaigakari." }] },
      { japanese: "確認する", romaji: "kakuninsuru", english: "To confirm", examples: [{ jp: "内容を 確認する。", en: "Confirm contents.", romaji: "Naiyou wo kakuninsuru." }, { jp: "最終 確認。", en: "Final check.", romaji: "Saishuu kakunin." }] },
      { japanese: "準備する", romaji: "junbisuru", english: "To prepare", examples: [{ jp: "夕食の 準備。", en: "Dinner prep.", romaji: "Yuushoku no junbi." }, { jp: "準備が できた。", en: "Preparation is ready.", romaji: "Junbi ga dekita." }] },
      { japanese: "相談する", romaji: "soudansuru", english: "To consult", examples: [{ jp: "旅行を 相談する。", en: "Discuss the trip.", romaji: "Ryokou wo soudansuru." }, { jp: "家族に 相談。", en: "Consult family.", romaji: "Kazoku ni soudan." }] },
      { japanese: "世話", romaji: "sewa", english: "Care/Help", examples: [{ jp: "お世話に なりました。", en: "Thank you for the care.", romaji: "Osewa ni narimashita." }, { jp: "犬の 世話。", en: "Dog care.", romaji: "Inu no sewa." }] },
      { japanese: "客", romaji: "kyaku", english: "Guest/Customer", examples: [{ jp: "大事な お客。", en: "Important guest.", romaji: "Daijin kyaku." }, { jp: "お客様を 迎える。", en: "Welcome the guest.", romaji: "Okyakusama wo mukaeru." }] },
      { japanese: "迎え", romaji: "mukae", english: "Picking up/Meeting", examples: [{ jp: "駅まで 迎えに行く。", en: "Go to pick up at station.", romaji: "Eki made mukae ni iku." }, { jp: "お出迎え。", en: "Meeting (someone arriving).", romaji: "Odemukae." }] },
      { japanese: "送る", romaji: "okuru", english: "To see off/Send", examples: [{ jp: "友達を 駅まで送る。", en: "See friend off at station.", romaji: "Tomodachi wo eki made okuru." }, { jp: "空港まで 送る。", en: "Drive to airport.", romaji: "Kuukou made okuru." }] },
      { japanese: "土産", romaji: "miyage", english: "Souvenir/Present", examples: [{ jp: "お土産を 買う。", en: "Buy a souvenir.", romaji: "Omiyage wo kau." }, { jp: "旅の お土産。", en: "Trip souvenir.", romaji: "Tabi no omiyage." }] },
      { japanese: "景色", romaji: "keshiki", english: "Scenery", examples: [{ jp: "窓からの 景色。", en: "View from the window.", romaji: "Mado kara no keshiki." }, { jp: "絶景。", en: "Superb view.", romaji: "Zekkei." }] },
      { japanese: "温泉", romaji: "onsen", english: "Hot spring", examples: [{ jp: "温泉に 入る。", en: "Enter a hot spring.", romaji: "Onsen ni hairu." }, { jp: "露天 風呂。", en: "Open-air bath.", romaji: "Roten buro." }] },
      { japanese: "旅館", romaji: "ryokan", english: "Japanese inn", examples: [{ jp: "古い 旅館。", en: "Old inn.", romaji: "Furui ryokan." }, { jp: "旅館の 食事。", en: "Inn meal.", romaji: "Ryokan no shokuji." }] },
      { japanese: "観光", romaji: "kankou", english: "Sightseeing", examples: [{ jp: "京都を 観光する。", en: "Sightsee in Kyoto.", romaji: "Kyoto wo kankousuru." }, { jp: "観光客。", en: "Tourist.", romaji: "Kankoukyaku." }] },
      { japanese: "パンフレット", romaji: "panfuretto", english: "Pamphlet", examples: [{ jp: "案内 パンフレット。", en: "Guide pamphlet.", romaji: "Annai panfuretto." }, { jp: "パンフレットを 見る。", en: "Look at the brochure.", romaji: "Panfuretto wo miru." }] },
      { japanese: "地図", romaji: "chizu", english: "Map", examples: [{ jp: "地図を 広げる。", en: "Spread a map.", romaji: "Chizu wo hirogeru." }, { jp: "Google マップ。", en: "Google Maps.", romaji: "Google mappu." }] },
      { japanese: "案内所", romaji: "annaijo", english: "Info desk/Guide office", examples: [{ jp: "観光 案内所。", en: "Tourist info center.", romaji: "Kankou annaijo." }, { jp: "案内所で 聞く。", en: "Ask at info desk.", romaji: "Annaijo de kiku." }] },
      { japanese: "両替", romaji: "ryougae", english: "Money exchange", examples: [{ jp: "円を ドルに両替する。", en: "Exchange Yen to USD.", romaji: "En wo doru ni ryougae suru." }, { jp: "両替 所。", en: "Exchange counter.", romaji: "Ryougaejo." }] },
      { japanese: "パスポート", romaji: "pasupooto", english: "Passport", examples: [{ jp: "パスポートを 出す。", en: "Show passport.", romaji: "Pasupooto wo dasu." }, { jp: "パスポートの 期限。", en: "Passport expiry.", romaji: "Pasupooto no kigen." }] },
      { japanese: "ビザ", romaji: "biza", english: "Visa", examples: [{ jp: "ビザを 申請する。", en: "Apply for a visa.", romaji: "Biza wo shinsei suru." }, { jp: "観光 ビザ。", en: "Tourist visa.", romaji: "Kankou biza." }] },
      { japanese: "空港", romaji: "kuukou", english: "Airport", examples: [{ jp: "空港で 待機する。", en: "Wait at airport.", romaji: "Kuukou de taiki suru." }, { jp: "成田 空港。", en: "Narita Airport.", romaji: "Narita kuukou." }] },
      { japanese: "飛行機", romaji: "hikouki", english: "Airplane", examples: [{ jp: "飛行機に 乗る。", en: "Board a plane.", romaji: "Hikouki ni noru." }, { jp: "国際線。", en: "Intl flight.", romaji: "Kokusaisen." }] },
      { japanese: "遅延する", romaji: "chien suru", english: "To be delayed", examples: [{ jp: "飛行機が 遅延した。", en: "Plane was delayed.", romaji: "Hikouki ga chienshita." }, { jp: "大幅な 遅延。", en: "Major delay.", romaji: "Oohabana chien." }] },
      { japanese: "欠航する", romaji: "kekkou suru", english: "To be cancelled (flight)", examples: [{ jp: "嵐で 欠航になった。", en: "Cancelled due to storm.", romaji: "Arashi de kekkou ni natta." }, { jp: "欠航の 通知。", en: "Cancellation notice.", romaji: "Kekkou no tsuuchi." }] },
      { japanese: "搭乗する", romaji: "toujou suru", english: "To board", examples: [{ jp: "搭乗 手続き。", en: "Boarding procedure.", romaji: "Toujou tetsuzuki." }, { jp: "搭乗 ゲート。", en: "Boarding gate.", romaji: "Toujou geeto." }] },
      { japanese: "荷物", romaji: "nimotsu", english: "Luggage/Baggage", examples: [{ jp: "重い 荷物。", en: "Heavy luggage.", romaji: "Omoi nimotsu." }, { jp: "荷物を 預ける。", en: "Check in luggage.", romaji: "Nimotsu wo azukeru." }] },
      { japanese: "預ける", romaji: "azukeru", english: "To leave/deposit", examples: [{ jp: "銀行にお金を預ける。", en: "Deposit money in bank.", romaji: "Ginkou ni okane wo azukeru." }, { jp: "ホテルに 荷物を預ける。", en: "Leave luggage at hotel.", romaji: "Hoteru ni nimotsu wo azukeru." }] },
      { japanese: "受け取る", romaji: "uketoru", english: "To receive/pick up", examples: [{ jp: "荷物を 受け取る。", en: "Pick up luggage.", romaji: "Nimotsu wo uketoru." }, { jp: "領収書を 受け取る。", en: "Receive receipt.", romaji: "Ryoushuusho wo uketoru." }] },
      { japanese: "感謝する", romaji: "kansha suru", english: "To be grateful", examples: [{ jp: "おもてなしに 感謝する。", en: "Grateful for hospitality.", romaji: "Omotenashi ni kansha suru." }, { jp: "感謝の 気持ち。", en: "Feeling of gratitude.", romaji: "Kansha no kimochi." }] }
    ]
  },
  {
    id: 45,
    level: "N4",
    title: "Culture & Activities",
    description: "Vocabulary for cultural experiences and events",
    words: [
      { japanese: "お祭り", romaji: "omatsuri", english: "Festival", examples: [{ jp: "夏 祭り。", en: "Summer festival.", romaji: "Natsu matsuri." }, { jp: "お祭りに 行く。", en: "Go to a festival.", romaji: "Omatsuri ni iku." }] },
      { japanese: "盆踊り", romaji: "bon'odori", english: "Bon dance", examples: [{ jp: "盆踊りを 踊る。", en: "Dance the Bon dance.", romaji: "Bon'odori wo odoru." }, { jp: "地元の 盆踊り。", en: "Local Bon dance.", romaji: "Jimoto no bon'odori." }] },
      { japanese: "神社", romaji: "jinja", english: "Shrine", examples: [{ jp: "神社で お参りする。", en: "Visit a shrine.", romaji: "Jinja de omairi suru." }, { jp: "有名な 神社。", en: "Famous shrine.", romaji: "Yuumeina jinja." }] },
      { japanese: "お寺", romaji: "otera", english: "Temple", examples: [{ jp: "お寺を 見学する。", en: "Visit a temple.", romaji: "Otera wo kengaku suru." }, { jp: "古い お寺。", en: "Old temple.", romaji: "Furui otera." }] },
      { japanese: "参拝する", romaji: "sanpai suru", english: "To worship (visit shrine/temple)", examples: [{ jp: "浅草寺に 参拝する。", en: "Visit Sensoji Temple.", romaji: "Sensouji ni sanpai suru." }, { jp: "参拝客。", en: "Worshipper/Visitor.", romaji: "Sanpaikyaku." }] },
      { japanese: "着物", romaji: "kimono", english: "Kimono", examples: [{ jp: "着物を 着る。", en: "Wear a kimono.", romaji: "Kimono wo kiru." }, { jp: "着物 姿。", en: "Kimono appearance.", romaji: "Kimono sugata." }] },
      { japanese: "茶道", romaji: "sadou", english: "Tea ceremony", examples: [{ jp: "茶道を 習う。", en: "Learn tea ceremony.", romaji: "Sadou wo narau." }, { jp: "茶道の 先生。", en: "Tea ceremony teacher.", romaji: "Sadou no sensei." }] },
      { japanese: "華道", romaji: "kadou", english: "Flower arrangement", examples: [{ jp: "華道を 嗜む。", en: "Enjoy flower arrangement.", romaji: "Kadou wo tashinamu." }, { jp: "生け花。", en: "Ikebana.", romaji: "Ikebana." }] },
      { japanese: "書道", romaji: "shodou", english: "Calligraphy", examples: [{ jp: "書道の 練習。", en: "Calligraphy practice.", romaji: "Shodou no renshuu." }, { jp: "美しい 書道。", en: "Beautiful calligraphy.", romaji: "Utsukushii shodou." }] },
      { japanese: "空手", romaji: "karate", english: "Karate", examples: [{ jp: "空手を 習う。", en: "Learn Karate.", romaji: "Karate wo narau." }, { jp: "黒帯。", en: "Black belt.", romaji: "Kuroobi." }] },
      { japanese: "柔道", romaji: "juudou", english: "Judo", examples: [{ jp: "柔道部。", en: "Judo club.", romaji: "Juudoubu." }, { jp: "柔道の 試合。", en: "Judo match.", romaji: "Juudou no shiai." }] },
      { japanese: "温泉", romaji: "onsen", english: "Hot spring", examples: [{ jp: "有名な 温泉地。", en: "Famous onsen spot.", romaji: "Yuumeina onsenchi." }, { jp: "温泉に 浸かる。", en: "Soak in hot spring.", romaji: "Onsen ni tsukaru." }] },
      { japanese: "花見", romaji: "hanami", english: "Cherry blossom viewing", examples: [{ jp: "公園で 花見をする。", en: "Have a hanami in park.", romaji: "Kouen de hanami wo suru." }, { jp: "花見の 季節。", en: "Hanami season.", romaji: "Hanami no kisetsu." }] },
      { japanese: "紅葉", romaji: "kouyou", english: "Autumn leaves", examples: [{ jp: "紅葉を 見に行く。", en: "Go see autumn colors.", romaji: "Kouyou wo mi ni iku." }, { jp: "山が 紅葉している。", en: "Mountain is colored.", romaji: "Yama ga kouyou shiteiru." }] },
      { japanese: "漫画", romaji: "manga", english: "Manga", examples: [{ jp: "漫画を 読む。", en: "Read manga.", romaji: "Manga wo yomu." }, { jp: "日本の 漫画。", en: "Japanese manga.", romaji: "Nihon no manga." }] },
      { japanese: "アニメ", romaji: "anime", english: "Anime", examples: [{ jp: "アニメが 好きだ。", en: "Like anime.", romaji: "Anime ga suki da." }, { jp: "アニメ 映画。", en: "Anime movie.", romaji: "Anime eiga." }] },
      { japanese: "伝統", romaji: "dentou", english: "Tradition", examples: [{ jp: "日本の 伝統。", en: "Japanese tradition.", romaji: "Nihon no dentou." }, { jp: "伝統 的な家。", en: "Traditional house.", romaji: "Dentouteki na ie." }] },
      { japanese: "歴史", romaji: "rekishi", english: "History", examples: [{ jp: "古い 歴史。", en: "Long history.", romaji: "Furui rekishi." }, { jp: "歴史を 学ぶ。", en: "Learn history.", romaji: "Rekishi wo manabu." }] },
      { japanese: "習慣", romaji: "shuukan", english: "Custom/Habit", examples: [{ jp: "良い 習慣。", en: "Good habit.", romaji: "Ii shuukan." }, { jp: "生活 習慣。", en: "Lifestyle habits.", romaji: "Seikatsu shuukan." }] },
      { japanese: "経験する", romaji: "keikensuru", english: "To experience", examples: [{ jp: "色々なことを経験する。", en: "Experience various things.", romaji: "Iroirona koto wo keikensuru." }, { jp: "初めての 経験。", en: "First experience.", romaji: "Hajimete no keiken." }] },
      { japanese: "参加する", romaji: "sankasuru", english: "To participate", examples: [{ jp: "大会に 参加する。", en: "Enter a contest.", romaji: "Taikai ni sankasuru." }, { jp: "参加者。", en: "Participant.", romaji: "Sankasha." }] },
      { japanese: "企画する", romaji: "kikakusuru", english: "To plan/organize", examples: [{ jp: "イベントを 企画する。", en: "Plan an event.", romaji: "Ibento wo kikakusuru." }, { jp: "新 企画。", en: "New project/plan.", romaji: "Shin kikaku." }] },
      { japanese: "交流する", romaji: "kouryousuru", english: "To exchange/interact", examples: [{ jp: "海外の学生と交流する。", en: "Interact with intl students.", romaji: "Kaigai no gakusei to kouryousuru." }, { jp: "交流会。", en: "Exchange meeting.", romaji: "Kouryukai." }] },
      { japanese: "感動する", romaji: "kandousuru", english: "To be moved/touched", examples: [{ jp: "映画に 感動した。", en: "Moved by the movie.", romaji: "Eiga ni kandoushita." }, { jp: "感動的な 話。", en: "Touching story.", romaji: "Kandouteki na hanashi." }] },
      { japanese: "楽しむ", romaji: "tanoshimu", english: "To enjoy", examples: [{ jp: "休暇を 楽しむ。", en: "Enjoy vacation.", romaji: "Kyuuka wo tanoshimu." }, { jp: "楽しんで ください。", en: "Please enjoy.", romaji: "Tanoshinde kudasai." }] },
      { japanese: "興味", romaji: "kyoumi", english: "Interest", examples: [{ jp: "興味が ある。", en: "Have interest.", romaji: "Kyoumi ga aru." }, { jp: "無 興味。", en: "Indifferent/Uninterested.", romaji: "Mu kyoumi." }] },
      { japanese: "理解する", romaji: "rikaisuru", english: "To understand", examples: [{ jp: "文化を 理解する。", en: "Understand culture.", romaji: "Bunka wo rikaisuru." }, { jp: "深い 理解。", en: "Deep understanding.", romaji: "Fukai rikai." }] },
      { japanese: "尊重する", romaji: "sonchousuru", english: "To respect", examples: [{ jp: "意見を 尊重する。", en: "Respect opinions.", romaji: "Iken wo sonchousuru." }, { jp: "尊重 し合う。", en: "Respect each other.", romaji: "Sonchou shiau." }] },
      { japanese: "守る", romaji: "mamoru", english: "To protect/obey", examples: [{ jp: "伝統を 守る。", en: "Protect tradition.", romaji: "Dentou wo mamoru." }, { jp: "約束を 守る。", en: "Keep a promise.", romaji: "Yakusoku wo mamoru." }] },
      { japanese: "伝える", romaji: "tsutaeru", english: "To convey/tell", examples: [{ jp: "想いを 伝える。", en: "Convey feelings.", romaji: "Omoi wo tsutaeru." }, { jp: "次の世代に伝える。", en: "Tell next generation.", romaji: "Tsugi no sedai ni tsutaeru." }] }
    ]
  }
];
