export const chunk5 = [
  {
    id: 21,
    title: "Shopping & Money",
    description: "Buying things, prices, and payment",
    words: [
      { japanese: "買い物", romaji: "kaimono", english: "Shopping", examples: [{ jp: "買い物に 行く。", en: "Go shopping.", romaji: "Kaimono ni iku." }, { jp: "買い物が 好き。", en: "Like shopping.", romaji: "Kaimono ga suki." }] },
      { japanese: "お金", romaji: "okane", english: "Money", examples: [{ jp: "お金を 払う。", en: "Pay money.", romaji: "Okane wo harau." }, { jp: "お金が ない。", en: "No money.", romaji: "Okane ga nai." }] },
      { japanese: "値段", romaji: "nedan", english: "Price", examples: [{ jp: "値段を 見る。", en: "Check price.", romaji: "Nedan wo miru." }, { jp: "値段が 高い。", en: "Price is high.", romaji: "Nedan ga takai." }] },
      { japanese: "安い", romaji: "yasui", english: "Cheap", examples: [{ jp: "安く 買う。", en: "Buy cheaply.", romaji: "Yasuku kau." }, { jp: "とても 安い。", en: "Very cheap.", romaji: "Totemo yasui." }] },
      { japanese: "高い", romaji: "takai", english: "Expensive", examples: [{ jp: "高すぎる。", en: "Too expensive.", romaji: "Takasugiru." }, { jp: "高い 時計。", en: "Expensive watch.", romaji: "Takai tokei." }] },
      { japanese: "現金", romaji: "genkin", english: "Cash", examples: [{ jp: "現金で 払う。", en: "Pay with cash.", romaji: "Genkin de harau." }, { jp: "現金払い。", en: "Cash payment.", romaji: "Genkinbarai." }] },
      { japanese: "カード", romaji: "kaado", english: "Credit card", examples: [{ jp: "カードは 使えますか。", en: "Can I use card?", romaji: "Kaado wa tsukaemasu ka." }, { jp: "カードで 買う。", en: "Buy with card.", romaji: "Kaado de kau." }] },
      { japanese: "お釣り", romaji: "otsuri", english: "Change", examples: [{ jp: "お釣りを もらう。", en: "Get change.", romaji: "Otsuri wo morau." }, { jp: "お釣りです。", en: "Here is your change.", romaji: "Otsuri desu." }] },
      { japanese: "レシート", romaji: "reshiito", english: "Receipt", examples: [{ jp: "レシートを ください。", en: "Receipt please.", romaji: "Reshiito wo kudasai." }, { jp: "レシートを 捨てる。", en: "Throw away receipt.", romaji: "Reshiito wo suteru." }] },
      { japanese: "財布", romaji: "saifu", english: "Wallet", examples: [{ jp: "財布を 忘れた。", en: "Forgot wallet.", romaji: "Saifu wo wasureta." }, { jp: "新しい 財布。", en: "New wallet.", romaji: "Atarashii saifu." }] },
      { japanese: "袋", romaji: "fukuro", english: "Bag", examples: [{ jp: "袋に 入れる。", en: "Put into bag.", romaji: "Fukuro ni ireru." }, { jp: "マイバッグ。", en: "Reusable bag.", romaji: "Maibaggu." }] },
      { japanese: "売り場", romaji: "uriba", english: "Sales counter", examples: [{ jp: "靴 売り場。", en: "Shoe section.", romaji: "Kutsu uriba." }, { jp: "食品 売り場。", en: "Food section.", romaji: "Shokuhin uriba." }] },
      { japanese: "消費税", romaji: "shouhizei", english: "Consumption tax", examples: [{ jp: "消費税込み。", en: "Tax included.", romaji: "Shouhizeikomi." }, { jp: "税抜き。", en: "Tax excluded.", romaji: "Zeinuki." }] },
      { japanese: "割引", romaji: "waribiki", english: "Discount", examples: [{ jp: "学生 割引。", en: "Student discount.", romaji: "Gakusei waribiki." }, { jp: "一割 引き。", en: "10% off.", romaji: "Ichiwari biki." }] },
      { japanese: "セール", romaji: "seeru", english: "Sale", examples: [{ jp: "セール中。", en: "On sale.", romaji: "Seeruchuu." }, { jp: "冬の セール。", en: "Winter sale.", romaji: "Fuyu no seeru." }] },
      { japanese: "無料", romaji: "muryou", english: "Free (no cost)", examples: [{ jp: "無料です。", en: "It is free.", romaji: "Muryou desu." }, { jp: "送料無料。", en: "Free shipping.", romaji: "Souryoumuryou." }] },
      { japanese: "有料", romaji: "yuuryou", english: "Paid / Fee-based", examples: [{ jp: "有料 サービス。", en: "Paid service.", romaji: "Yuuryou saabisu." }, { jp: "袋は 有料です。", en: "Bags cost money.", romaji: "Fukuro wa yuuryou desu." }] },
      { japanese: "サイズ", romaji: "saizu", english: "Size", examples: [{ jp: "サイズが 合わない。", en: "Size doesn't fit.", romaji: "Saizu ga awanai." }, { jp: "大きい サイズ。", en: "Large size.", romaji: "Ookii saizu." }] },
      { japanese: "試着", romaji: "shichaku", english: "Trying on", examples: [{ jp: "試着してもいいですか。", en: "Can I try this on?", romaji: "Shichaku shitemo ii desu ka." }, { jp: "試着室。", en: "Fitting room.", romaji: "Shichakushitsu." }] },
      { japanese: "選ぶ", romaji: "erabu", english: "To choose", examples: [{ jp: "プレゼントを 選ぶ。", en: "Choose present.", romaji: "Purezento wo erabu." }, { jp: "どれを 選ぶ？", en: "Which do you pick?", romaji: "Dore wo erabu?" }] },
      { japanese: "探す", romaji: "sagasu", english: "To look for", examples: [{ jp: "お土産を 探す。", en: "Look for souvenir.", romaji: "Omiyage wo sagasu." }, { jp: "何を探していますか。", en: "What are you looking for?", romaji: "Nani wo sagashiteimasu ka." }] },
      { japanese: "店員", romaji: "tenin", english: "Shop assistant", examples: [{ jp: "店員に 聞く。", en: "Ask clerk.", romaji: "Tenin ni kiku." }, { jp: "親切な 店員。", en: "Kind clerk.", romaji: "Shinsetsu na tenin." }] },
      { japanese: "客", romaji: "kyaku", english: "Customer/Guest", examples: [{ jp: "客が 多い。", en: "Many customers.", romaji: "Kyaku ga ooi." }, { jp: "お客様。", en: "Guest (polite).", romaji: "Okyakusama." }] },
      { japanese: "注文", romaji: "chuumon", english: "Order", examples: [{ jp: "注文を 取る。", en: "Take order.", romaji: "Chuumon wo toru." }, { jp: "ネット 注文。", en: "Online order.", romaji: "Netto chuumon." }] },
      { japanese: "品物", romaji: "shinamono", english: "Goods/Items", examples: [{ jp: "品物を 見る。", en: "Look at goods.", romaji: "Shinamono wo miru." }, { jp: "良い 品物。", en: "Good item.", romaji: "Ii shinamono." }] },
      { japanese: "包む", romaji: "tsutsumu", english: "To wrap", examples: [{ jp: "きれい に包む。", en: "Wrap beautifully.", romaji: "Kirei ni tsutsumu." }, { jp: "プレゼント用に包む。", en: "Wrap for gift.", romaji: "Purezentoyou ni tsutsumu." }] },
      { japanese: "返品", romaji: "henpin", english: "Return (goods)", examples: [{ jp: "返品 できますか。", en: "Can I return this?", romaji: "Henpin dekimasu ka." }, { jp: "返品不可。", en: "No returns.", romaji: "Henpinfuka." }] },
      { japanese: "交換", romaji: "koukan", english: "Exchange", examples: [{ jp: "サイズを 交換する。", en: "Exchange size.", romaji: "Saizu wo koukan suru." }, { jp: "名刺 交換。", en: "Business card exchange.", romaji: "Meishi koukan." }] },
      { japanese: "レジ", romaji: "reji", english: "Cash register", examples: [{ jp: "レジに 並ぶ。", en: "Line up at register.", romaji: "Reji ni narabu." }, { jp: "コンビニの レジ。", en: "Convenience store register.", romaji: "Konbini no reji." }] },
      { japanese: "ATM", romaji: "eetiiemu", english: "ATM", examples: [{ jp: "ATMで 下ろす。", en: "Withdraw at ATM.", romaji: "ATM de orosu." }, { jp: "銀行の ATM。", en: "Bank ATM.", romaji: "Ginkou no ATM." }] }
    ]
  },
  {
    id: 22,
    title: "Hobbies & Leisure",
    description: "Sports, arts, music, and free time",
    words: [
      { japanese: "趣味", romaji: "shumi", english: "Hobby", examples: [{ jp: "趣味は 何ですか。", en: "What is your hobby?", romaji: "Shumi wa nan desu ka." }, { jp: "趣味は 読書です。", en: "Hobby is reading.", romaji: "Shumi wa dokusho desu." }] },
      { japanese: "スポーツ", romaji: "supootsu", english: "Sports", examples: [{ jp: "スポーツを する。", en: "Play sports.", romaji: "Supootsu wo suru." }, { jp: "スポーツ選手。", en: "Athlete.", romaji: "Supootsu senshu." }] },
      { japanese: "サッカー", romaji: "sakkaa", english: "Soccer", examples: [{ jp: "サッカーを 見る。", en: "Watch soccer.", romaji: "Sakkaa wo miru." }, { jp: "サッカー場。", en: "Soccer field.", romaji: "Sakkaa jou." }] },
      { japanese: "野球", romaji: "yakyuu", english: "Baseball", examples: [{ jp: "野球 観戦。", en: "Watching baseball.", romaji: "Yakyuu kansen." }, { jp: "プロ 野球。", en: "Pro baseball.", romaji: "Puro yakyuu." }] },
      { japanese: "テニス", romaji: "tenisu", english: "Tennis", examples: [{ jp: "テニス コート。", en: "Tennis court.", romaji: "Tenisu kooto." }, { jp: "テニスを する。", en: "Play tennis.", romaji: "Tenisu wo suru." }] },
      { japanese: "水泳", romaji: "suiei", english: "Swimming", examples: [{ jp: "水泳が 得意。", en: "Good at swimming.", romaji: "Suiei ga tokui." }, { jp: "水泳 大会。", en: "Swimming meet.", romaji: "Suiei taikai." }] },
      { japanese: "映画", romaji: "eiga", english: "Movie", examples: [{ jp: "映画を 見に行く。", en: "Go to see movie.", romaji: "Eiga wo mi ni iku." }, { jp: "面白い 映画。", en: "Funny movie.", romaji: "Omoshiroi eiga." }] },
      { japanese: "音楽", romaji: "ongaku", english: "Music", examples: [{ jp: "音楽を 聞く。", en: "Listen to music.", romaji: "Ongaku wo kiku." }, { jp: "音楽家。", en: "Musician.", romaji: "Ongakuka." }] },
      { japanese: "歌", romaji: "uta", english: "Song", examples: [{ jp: "歌を 歌う。", en: "Sing song.", romaji: "Uta wo utau." }, { jp: "流行の 歌。", en: "Popular song.", romaji: "Ryuukou no uta." }] },
      { japanese: "カラオケ", romaji: "karaoke", english: "Karaoke", examples: [{ jp: "カラオケに 行く。", en: "Go to karaoke.", romaji: "Karaoke ni iku." }, { jp: "カラオケで 歌う。", en: "Sing at karaoke.", romaji: "Karaoke de utau." }] },
      { japanese: "読書", romaji: "dokusho", english: "Reading", examples: [{ jp: "読書が 好き。", en: "Like reading.", romaji: "Dokusho ga suki." }, { jp: "読書 感想文。", en: "Book report.", romaji: "Dokusho kansoubun." }] },
      { japanese: "絵", romaji: "e", english: "Picture/Drawing", examples: [{ jp: "絵を 描く。", en: "Draw a picture.", romaji: "E wo kaku." }, { jp: "きれいな 絵。", en: "Beautiful picture.", romaji: "Kirei na e." }] },
      { japanese: "写真", romaji: "shashin", english: "Photo", examples: [{ jp: "写真を 撮る。", en: "Take photo.", romaji: "Shashin wo toru." }, { jp: "写真家。", en: "Photographer.", romaji: "Shashinka." }] },
      { japanese: "旅行", romaji: "ryokou", english: "Travel", examples: [{ jp: "海外 旅行。", en: "Overseas travel.", romaji: "Kaigai ryokou." }, { jp: "一人 旅。", en: "Solo travel.", romaji: "Hitori tabi." }] },
      { japanese: "料理", romaji: "ryouri", english: "Cooking", examples: [{ jp: "料理を 作る。", en: "Cook food.", romaji: "Ryouri wo tsukuru." }, { jp: "得意 料理。", en: "Specialty dish.", romaji: "Tokui ryouri." }] },
      { japanese: "釣り", romaji: "tsuri", english: "Fishing", examples: [{ jp: "釣りに 行く。", en: "Go fishing.", romaji: "Tsuri ni iku." }, { jp: "魚 釣り。", en: "Fish catching.", romaji: "Sakana tsuri." }] },
      { japanese: "ゲーム", romaji: "geemu", english: "Game", examples: [{ jp: "ゲームを する。", en: "Play a game.", romaji: "Geemu wo suru." }, { jp: "テレビ ゲーム。", en: "Video game.", romaji: "Terebi geemu." }] },
      { japanese: "散歩", romaji: "sanpo", english: "Walk/Stroll", examples: [{ jp: "朝の 散歩。", en: "Morning walk.", romaji: "Asa no sanpo." }, { jp: "散歩 コース。", en: "Walking route.", romaji: "Sanpo koosu." }] },
      { japanese: "ピアノ", romaji: "piano", english: "Piano", examples: [{ jp: "ピアノを 弾く。", en: "Play piano.", romaji: "Piano wo hiku." }, { jp: "ピアノ 教室。", en: "Piano class.", romaji: "Piano kyoushitsu." }] },
      { japanese: "ギター", romaji: "gitaa", english: "Guitar", examples: [{ jp: "ギターを 弾く。", en: "Play guitar.", romaji: "Gitaa wo hiku." }, { jp: "ギター ケース。", en: "Guitar case.", romaji: "Gitaa keesu." }] },
      { japanese: "ダンス", romaji: "dansu", english: "Dance", examples: [{ jp: "ダンスを 習う。", en: "Learn dance.", romaji: "Dansu wo narau." }, { jp: "ダンス パーティー。", en: "Dance party.", romaji: "Dansu paatii." }] },
      { japanese: "切手", romaji: "kitte", english: "Stamp collecting/Stamp", examples: [{ jp: "切手を 集める。", en: "Collect stamps.", romaji: "Kitte wo atsumeru." }, { jp: "記念 切手。", en: "Commemorative stamp.", romaji: "Kinen kitte." }] },
      { japanese: "漫画", romaji: "manga", english: "Comics/Manga", examples: [{ jp: "漫画を 読む。", en: "Read manga.", romaji: "Manga wo yomu." }, { jp: "漫画家。", en: "Manga artist.", romaji: "Mangaka." }] },
      { japanese: "アニメ", romaji: "anime", english: "Anime", examples: [{ jp: "アニメを 見る。", en: "Watch anime.", romaji: "Anime wo miru." }, { jp: "日本のアニメ。", en: "Japanese anime.", romaji: "Nihon no anime." }] },
      { japanese: "コンサート", romaji: "konsaato", english: "Concert", examples: [{ jp: "コンサートに 行く。", en: "Go to concert.", romaji: "Konsaato ni iku." }, { jp: "ライブ。", en: "Live show.", romaji: "Raibu." }] },
      { japanese: "美術館", romaji: "bijutsukan", english: "Art museum", examples: [{ jp: "美術館巡り。", en: "Visiting museums.", romaji: "Bijutsukan meguri." }, { jp: "美術館で見る。", en: "See in museum.", romaji: "Bijutsukan de miru." }] },
      { japanese: "博物館", romaji: "hakubutsukan", english: "Museum", examples: [{ jp: "歴史 博物館。", en: "History museum.", romaji: "Rekishi hakubutsukan." }, { jp: "博物館へ 行く。", en: "Go to museum.", romaji: "Hakubutsukan e iku." }] },
      { japanese: "登山", romaji: "tozan", english: "Mountain climbing", examples: [{ jp: "富士都山。", en: "Climbing Mt Fuji.", romaji: "Fujitozan." }, { jp: "趣味は 登山。", en: "Hobby is climbing.", romaji: "Shumi wa tozan." }] },
      { japanese: "花見", romaji: "hanami", english: "Flower viewing", examples: [{ jp: "花見を する。", en: "Do hanami.", romaji: "Hanami wo suru." }, { jp: "花見 弁当。", en: "Hanami bento.", romaji: "Hanami bentou." }] },
      { japanese: "泳ぐ", romaji: "oyogu", english: "To swim", examples: [{ jp: "プールで 泳ぐ。", en: "Swim in pool.", romaji: "Puuru de oyogu." }, { jp: "海で 泳ぐ。", en: "Swim in sea.", romaji: "Umi de oyogu." }] }
    ]
  },
  {
    id: 23,
    title: "Health & Feelings",
    description: "Physical condition, illness, and emotions",
    words: [
      { japanese: "元気", romaji: "genki", english: "Healthy/Energetic", examples: [{ jp: "元気ですか。", en: "How are you?", romaji: "Genki desu ka." }, { jp: "元気な 声。", en: "Energetic voice.", romaji: "Genki na koe." }] },
      { japanese: "病気", romaji: "byouki", english: "Illness", examples: [{ jp: "病気に なる。", en: "Get sick.", romaji: "Byouki ni naru." }, { jp: "病気が 治る。", en: "Illness cures.", romaji: "Byouki ga naoru." }] },
      { japanese: "風邪", romaji: "kaze", english: "Cold", examples: [{ jp: "風邪を 引く。", en: "Catch a cold.", romaji: "Kaze wo hiku." }, { jp: "風邪薬。", en: "Cold medicine.", romaji: "Kazegusuri." }] },
      { japanese: "熱", romaji: "netsu", english: "Fever", examples: [{ jp: "熱が ある。", en: "Have a fever.", romaji: "Netsu ga aru." }, { jp: "熱が 下がる。", en: "Fever goes down.", romaji: "Netsu ga sagaru." }] },
      { japanese: "痛い", romaji: "itai", english: "Painful", examples: [{ jp: "頭が 痛い。", en: "Headache.", romaji: "Atama ga itai." }, { jp: "心が 痛い。", en: "Heartache.", romaji: "Kokoro ga itai." }] },
      { japanese: "大丈夫", romaji: "daijoubu", english: "Fine/Okay", examples: [{ jp: "大丈夫ですか。", en: "Are you okay?", romaji: "Daijoubu desu ka." }, { jp: "全然 大丈夫。", en: "Totally fine.", romaji: "Zenzen daijoubu." }] },
      { japanese: "薬", romaji: "kusuri", english: "Medicine", examples: [{ jp: "薬を 飲む。", en: "Take medicine.", romaji: "Kusuri wo nomu." }, { jp: "薬屋。", en: "Pharmacy.", romaji: "Kusuriya." }] },
      { japanese: "病院", romaji: "byouin", english: "Hospital", examples: [{ jp: "病院へ 行く。", en: "Go to hospital.", romaji: "Byouin e iku." }, { jp: "大きい 病院。", en: "Big hospital.", romaji: "Ookii byouin." }] },
      { japanese: "医者", romaji: "isha", english: "Doctor", examples: [{ jp: "医者の 先生。", en: "Doctor.", romaji: "Isha no sensei." }, { jp: "歯医者。", en: "Dentist.", romaji: "Haisha." }] },
      { japanese: "休む", romaji: "yasumu", english: "To rest", examples: [{ jp: "ゆっくり 休む。", en: "Rest well.", romaji: "Yukkuri yasumu." }, { jp: "会社を 休む。", en: "Absent from work.", romaji: "Kaisha wo yasumu." }] },
      { japanese: "疲れる", romaji: "tsukareru", english: "To be tired", examples: [{ jp: "疲 れました。", en: "I'm tired.", romaji: "Tsukaremashita." }, { jp: "目が 疲れる。", en: "Eyes tired.", romaji: "Me ga tsukareru." }] },
      { japanese: "眠い", romaji: "nemui", english: "Sleepy", examples: [{ jp: "とても 眠い。", en: "Very sleepy.", romaji: "Totemo nemui." }, { jp: "眠い顔。", en: "Sleepy face.", romaji: "Nemui kao." }] },
      { japanese: "嬉しい", romaji: "ureshii", english: "Happy", examples: [{ jp: "会えて 嬉しい。", en: "Happy to meet.", romaji: "Aete ureshii." }, { jp: "嬉しい ニュース。", en: "Happy news.", romaji: "Ureshii nyuusu." }] },
      { japanese: "悲しい", romaji: "kanashii", english: "Sad", examples: [{ jp: "悲しい 話。", en: "Sad story.", romaji: "Kanashii hanashi." }, { jp: "悲しくて 泣く。", en: "Cry from sadness.", romaji: "Kanashikute naku." }] },
      { japanese: "楽しい", romaji: "tanoshii", english: "Fun/Enjoyable", examples: [{ jp: "楽しい 旅行。", en: "Fun trip.", romaji: "Tanoshii ryokou." }, { jp: "毎日が 楽しい。", en: "Every day is fun.", romaji: "Mainichi ga tanoshii." }] },
      { japanese: "寂しい", romaji: "sabishii", english: "Lonely", examples: [{ jp: "一人は 寂しい。", en: "Alone is lonely.", romaji: "Hitori wa sabishii." }, { jp: "寂しい 夜。", en: "Lonely night.", romaji: "Sabishii yoru." }] },
      { japanese: "好き", romaji: "suki", english: "Like", examples: [{ jp: "日本が 好き。", en: "Like Japan.", romaji: "Nihon ga suki." }, { jp: "好きな 人。", en: "Person I like.", romaji: "Suki na hito." }] },
      { japanese: "嫌い", romaji: "kirai", english: "Dislike", examples: [{ jp: "納豆が 嫌い。", en: "Dislike natto.", romaji: "Nattou ga kirai." }, { jp: "嫌いじゃ ない。", en: "Don't dislike.", romaji: "Kirai ja nai." }] },
      { japanese: "欲しい", romaji: "hoshii", english: "Want", examples: [{ jp: "水が 欲しい。", en: "Want water.", romaji: "Mizu ga hoshii." }, { jp: "これが 欲しい。", en: "Want this.", romaji: "Kore ga hoshii." }] },
      { japanese: "怖い", romaji: "kowai", english: "Scary", examples: [{ jp: "幽霊が 怖い。", en: "Ghosts are scary.", romaji: "Yuurei ga kowai." }, { jp: "怖い 顔。", en: "Scary face.", romaji: "Kowai kao." }] },
      { japanese: "危ない", romaji: "abunai", english: "Dangerous", examples: [{ jp: "そこは 危ない。", en: "It's dangerous there.", romaji: "Soko wa abunai." }, { jp: "危ない！", en: "Look out!", romaji: "Abunai!" }] },
      { japanese: "驚く", romaji: "odoroku", english: "To be surprised", examples: [{ jp: "ニュースに 驚く。", en: "Surprised at news.", romaji: "Nyuusu ni odoroku." }, { jp: "驚いた 顔。", en: "Surprised face.", romaji: "Odoroita kao." }] },
      { japanese: "困る", romaji: "komaru", english: "To be troubled", examples: [{ jp: "お金に 困る。", en: "Troubled for money.", romaji: "Okane ni komaru." }, { jp: "返事に 困る。", en: "Troubled for answer.", romaji: "Henji ni komaru." }] },
      { japanese: "心配", romaji: "shinpai", english: "Worry", examples: [{ jp: "心配 しないで。", en: "Don't worry.", romaji: "Shinpai shinaide." }, { jp: "親に 心配かける。", en: "Worry parents.", romaji: "Oya ni shinpaikakeru." }] },
      { japanese: "安心", romaji: "anshin", english: "Relief", examples: [{ jp: "安心 した。", en: "Relieved.", romaji: "Anshin shita." }, { jp: "安心 できる。", en: "Can relax.", romaji: "Anshin dekiru." }] },
      { japanese: "気持ち", romaji: "kimochi", english: "Feeling", examples: [{ jp: "気持ちが いい。", en: "Feels good.", romaji: "Kimochi ga ii." }, { jp: "気持ち 悪い。", en: "Feels bad/Gross.", romaji: "Kimochi warui." }] },
      { japanese: "気分", romaji: "kibun", english: "Mood/Feeling", examples: [{ jp: "気分転換。", en: "Change of pace.", romaji: "Kibuntenkan." }, { jp: "気分が すぐれない。", en: "Not feeling well.", romaji: "Kibun ga sugurenai." }] },
      { japanese: "泣く", romaji: "naku", english: "To cry", examples: [{ jp: "大声で 泣く。", en: "Cry loudly.", romaji: "Oogoe de naku." }, { jp: "泣かないで。", en: "Don't cry.", romaji: "Nakanaide." }] },
      { japanese: "笑う", romaji: "warau", english: "To laugh", examples: [{ jp: "みんなで 笑う。", en: "Laugh together.", romaji: "Minna de warau." }, { jp: "笑う 門には福来たる。", en: "Fortune comes to laughing gate.", romaji: "Warau kado ni wa fuku kitaru." }] },
      { japanese: "怒る", romaji: "okoru", english: "To get angry", examples: [{ jp: "激しく 怒る。", en: "Get furiously angry.", romaji: "Hageshiku okoru." }, { jp: "怒った？", en: "Are you angry?", romaji: "Okotta?" }] }
    ]
  },
  {
    id: 24,
    title: "Directions & Position",
    description: "Location words and giving directions",
    words: [
      { japanese: "上", romaji: "ue", english: "Up/Above", examples: [{ jp: "机の 上。", en: "On the desk.", romaji: "Tsukue no ue." }, { jp: "上を 見る。", en: "Look up.", romaji: "Uue wo miru." }] },
      { japanese: "下", romaji: "shita", english: "Down/Below", examples: [{ jp: "椅子の 下。", en: "Under the chair.", romaji: "Isu no shita." }, { jp: "下を 向く。", en: "Look down.", romaji: "Shita wo muku." }] },
      { japanese: "前", romaji: "mae", english: "Front/Before", examples: [{ jp: "駅の 前。", en: "In front of station.", romaji: "Eki no mae." }, { jp: "寝る 前。", en: "Before sleeping.", romaji: "Neru mae." }] },
      { japanese: "後ろ", romaji: "ushiro", english: "Back/Behind", examples: [{ jp: "ドアの 後ろ。", en: "Behind door.", romaji: "Doa no ushiro." }, { jp: "後ろを 向く。", en: "Turn around.", romaji: "Ushiro wo muku." }] },
      { japanese: "右", romaji: "migi", english: "Right", examples: [{ jp: "右に 曲がる。", en: "Turn right.", romaji: "Migi ni magaru." }, { jp: "右手。", en: "Right hand.", romaji: "Migite." }] },
      { japanese: "左", romaji: "hidari", english: "Left", examples: [{ jp: "左に ある。", en: "It's on the left.", romaji: "Hidari ni aru." }, { jp: "左足。", en: "Left foot.", romaji: "Hidariashi." }] },
      { japanese: "中", romaji: "naka", english: "Inside/Middle", examples: [{ jp: "箱の 中。", en: "Inside box.", romaji: "Hako no naka." }, { jp: "部屋の 中。", en: "In the room.", romaji: "Heya no naka." }] },
      { japanese: "外", romaji: "soto", english: "Outside", examples: [{ jp: "天気がいいから外に出る。", en: "Go out cause weather is good.", romaji: "Tenkigaiikara soto ni deru." }, { jp: "外で遊ぶ。", en: "Play outside.", romaji: "Soto de asobu." }] },
      { japanese: "隣", romaji: "tonari", english: "Next to", examples: [{ jp: "隣の 人。", en: "Person next to me.", romaji: "Tonari no hito." }, { jp: "隣の 家。", en: "Next door house.", romaji: "Tonari no ie." }] },
      { japanese: "近く", romaji: "chikaku", english: "Near", examples: [{ jp: "駅の 近く。", en: "Near station.", romaji: "Eki no chikaku." }, { jp: "近くに ありますか。", en: "Is it nearby?", romaji: "Chikaku ni arimasu ka." }] },
      { japanese: "遠く", romaji: "tooku", english: "Far", examples: [{ jp: "遠くへ 行きたい。", en: "Want to go far.", romaji: "Tooku e ikitai." }, { jp: "遠くの 山。", en: "Distant mountain.", romaji: "Tooku no yama." }] },
      { japanese: "間", romaji: "aida", english: "Between", examples: [{ jp: "AとBの 間。", en: "Between A and B.", romaji: "A to B no aida." }, { jp: "長い 間。", en: "Long time.", romaji: "Nagai aida." }] },
      { japanese: "向こう", romaji: "mukou", english: "Over there/Opposite", examples: [{ jp: "川の 向こう。", en: "Across the river.", romaji: "Kawa no mukou." }, { jp: "向こうに 見える。", en: "Visible over there.", romaji: "Mukou ni mieru." }] },
      { japanese: "北", romaji: "kita", english: "North", examples: [{ jp: "北か ら来る。", en: "Come from north.", romaji: "Kita kara kuru." }, { jp: "北口。", en: "North exit.", romaji: "Kitaguchi." }] },
      { japanese: "南", romaji: "minami", english: "South", examples: [{ jp: "南の 島。", en: "Southern island.", romaji: "Minami no shima." }, { jp: "南向き。", en: "South facing.", romaji: "Minamimuki." }] },
      { japanese: "東", romaji: "higashi", english: "East", examples: [{ jp: "太陽は 東から。", en: "Sun from east.", romaji: "Taiyou wa higashi kara." }, { jp: "東口。", en: "East exit.", romaji: "Higashiguchi." }] },
      { japanese: "西", romaji: "nishi", english: "West", examples: [{ jp: "西の 空。", en: "Western sky.", romaji: "Nishi no sora." }, { jp: "関西。", en: "Kansai (West Japan).", romaji: "Kansai." }] },
      { japanese: "側", romaji: "gawa", english: "Side", examples: [{ jp: "右 側。", en: "Right side.", romaji: "Migigawa." }, { jp: "向こう 側。", en: "Other side.", romaji: "Mukougawa." }] },
      { japanese: "周り", romaji: "mawari", english: "Around", examples: [{ jp: "駅の 周り。", en: "Around station.", romaji: "Eki no mawari." }, { jp: "池の 周り。", en: "Around pond.", romaji: "Ike no mawari." }] },
      { japanese: "真ん中", romaji: "mannaka", english: "Center", examples: [{ jp: "道の 真ん中。", en: "Middle of road.", romaji: "Michi no mannaka." }, { jp: "部屋の 真ん中。", en: "Center of room.", romaji: "Heya no mannaka." }] },
      { japanese: "角", romaji: "kado", english: "Corner", examples: [{ jp: "あの 角。", en: "That corner.", romaji: "Ano kado." }, { jp: "角を 曲がる。", en: "Turn corner.", romaji: "Kado wo magaru." }] },
      { japanese: "まっすぐ", romaji: "massugu", english: "Straight", examples: [{ jp: "まっすぐ 行く。", en: "Go straight.", romaji: "Massugu iku." }, { jp: "まっすぐな 道。", en: "Straight road.", romaji: "Massugu na michi." }] },
      { japanese: "横", romaji: "yoko", english: "Side/Horizontal", examples: [{ jp: "横に なる。", en: "Lie down.", romaji: "Yoko ni naru." }, { jp: "私の 横。", en: "My side.", romaji: "Watashi no yoko." }] },
      { japanese: "隅", romaji: "sumi", english: "Corner (interior)", examples: [{ jp: "部屋の 隅。", en: "Corner of room.", romaji: "Heya no sumi." }, { jp: "隅に 置く。", en: "Put in corner.", romaji: "Sumi ni oku." }] },
      { japanese: "手前", romaji: "temae", english: "This side/Before", examples: [{ jp: "駅の 手前。", en: "Just before station.", romaji: "Eki no temae." }, { jp: "手前に 引く。", en: "Pull towards you.", romaji: "Temae ni hiku." }] },
      { japanese: "突き当たり", romaji: "tsukiatari", english: "End of the street", examples: [{ jp: "突き当たりを 右。", en: "Right at T-junction.", romaji: "Tsukiatari wo migi." }, { jp: "廊下の 突き当たり。", en: "End of hall.", romaji: "Rouka no tsukiatari." }] },
      { japanese: "地図", romaji: "chizu", english: "Map", examples: [{ jp: "地図を 書く。", en: "Draw map.", romaji: "Chizu wo kaku." }, { jp: "地図を 見る。", en: "Look at map.", romaji: "Chizu wo miru." }] },
      { japanese: "入り口", romaji: "iriguchi", english: "Entrance", examples: [{ jp: "正面 入り口。", en: "Front entrance.", romaji: "Shoumen iriguchi." }, { jp: "入り口は どこ？", en: "Where is entrance?", romaji: "Iriguchi wa doko?" }] },
      { japanese: "出口", romaji: "deguchi", english: "Exit", examples: [{ jp: "非常 出口。", en: "Emergency exit.", romaji: "Hijou deguchi." }, { jp: "出口を 出る。", en: "Go out exit.", romaji: "Deguchi wo deru." }] },
      { japanese: "階", romaji: "kai", english: "Floor", examples: [{ jp: "二階。", en: "2nd floor.", romaji: "Nikai." }, { jp: "何階 ですか。", en: "Which floor?", romaji: "Nankai desu ka." }] }
    ]
  },
  {
    id: 25,
    title: "Technology & Tools",
    description: "Modern devices, internet, and utilities",
    words: [
      { japanese: "パソコン", romaji: "pasokon", english: "Computer (PC)", examples: [{ jp: "パソコンを 使う。", en: "Use PC.", romaji: "Pasokon wo tsukau." }, { jp: "パソコン 教室。", en: "PC class.", romaji: "Pasokon kyoushitsu." }] },
      { japanese: "スマホ", romaji: "sumaho", english: "Smartphone", examples: [{ jp: "スマホを 見る。", en: "Look at smartphone.", romaji: "Sumaho wo miru." }, { jp: "スマホ ケース。", en: "Phone case.", romaji: "Sumaho keesu." }] },
      { japanese: "インターネット", romaji: "intaanetto", english: "Internet", examples: [{ jp: "インターネットで 調べる。", en: "Search on internet.", romaji: "Intaanetto de shiraberu." }, { jp: "ネット。", en: "Net (short).", romaji: "Netto." }] },
      { japanese: "メール", romaji: "meeru", english: "E-mail", examples: [{ jp: "メールを 送る。", en: "Send email.", romaji: "Meeru wo okuru." }, { jp: "メール アドレス。", en: "Email address.", romaji: "Meeru adoresu." }] },
      { japanese: "カメラ", romaji: "kamera", english: "Camera", examples: [{ jp: "カメラで 撮る。", en: "Take with camera.", romaji: "Kamera de toru." }, { jp: "デジタル カメラ。", en: "Digital camera.", romaji: "Dejitaru kamera." }] },
      { japanese: "テレビ", romaji: "terebi", english: "Television", examples: [{ jp: "テレビ 番組。", en: "TV program.", romaji: "Terebi bangumi." }, { jp: "テレビを 消す。", en: "Turn off TV.", romaji: "Terebi wo kesu." }] },
      { japanese: "ラジオ", romaji: "rajio", english: "Radio", examples: [{ jp: "ラジオを 聞く。", en: "Listen to radio.", romaji: "Rajio wo kiku." }, { jp: "ラジオ ニュース。", en: "Radio news.", romaji: "Rajio nyuusu." }] },
      { japanese: "時計", romaji: "tokei", english: "Clock/Watch", examples: [{ jp: "時計を 見る。", en: "Check time.", romaji: "Tokei wo miru." }, { jp: "腕時計。", en: "Wristwatch.", romaji: "Udedokei." }] },
      { japanese: "電池", romaji: "denchi", english: "Battery", examples: [{ jp: "電池が 切れる。", en: "Battery runs out.", romaji: "Denchi ga kireru." }, { jp: "新しい 電池。", en: "New battery.", romaji: "Atarashii denchi." }] },
      { japanese: "電気", romaji: "denki", english: "Electricity/Light", examples: [{ jp: "電気を つける。", en: "Turn on light.", romaji: "Denki wo tsukeru." }, { jp: "電気代。", en: "Electric bill.", romaji: "Denkidai." }] },
      { japanese: "冷蔵庫", romaji: "reizouko", english: "Refrigerator", examples: [{ jp: "冷蔵庫に 入れる。", en: "Put in fridge.", romaji: "Reizouko ni ireru." }, { jp: "冷蔵庫が 壊れた。", en: "Fridge broke.", romaji: "Reizouko ga kowareta." }] },
      { japanese: "洗濯機", romaji: "sentakuki", english: "Washing machine", examples: [{ jp: "洗濯機を 回す。", en: "Run washer.", romaji: "Sentakuki wo mawasu." }, { jp: "全自動 洗濯機。", en: "Automatic washer.", romaji: "Zenjidou sentakuki." }] },
      { japanese: "掃除機", romaji: "soujiki", english: "Vacuum cleaner", examples: [{ jp: "掃除機を かける。", en: "Vacuum.", romaji: "Soujiki wo kakeru." }, { jp: "ロボット 掃除機。", en: "Robot vacuum.", romaji: "Robotto soujiki." }] },
      { japanese: "電子レンジ", romaji: "denshirenji", english: "Microwave", examples: [{ jp: "レンジで 温める。", en: "Warm in microwave.", romaji: "Renji de atatameru." }, { jp: "レンジ。", en: "Microwave (short).", romaji: "Renji." }] },
      { japanese: "エアコン", romaji: "eakon", english: "Air conditioner", examples: [{ jp: "エアコンを つける。", en: "Turn on AC.", romaji: "Eakon wo tsukeru." }, { jp: "エアコンが 寒い。", en: "AC is cold.", romaji: "Eakon ga samui." }] },
      { japanese: "リモコン", romaji: "rimokon", english: "Remote control", examples: [{ jp: "リモコンは どこ？", en: "Where is remote?", romaji: "Rimokon wa doko?" }, { jp: "テレビの リモコン。", en: "TV remote.", romaji: "Terebi no rimokon." }] },
      { japanese: "スイッチ", romaji: "suicchi", english: "Switch", examples: [{ jp: "スイッチを 入れる。", en: "Turn on switch.", romaji: "Suicchi wo ireru." }, { jp: "電源 スイッチ。", en: "Power switch.", romaji: "Dengen suicchi." }] },
      { japanese: "ボタン", romaji: "botan", english: "Button", examples: [{ jp: "ボタンを 押す。", en: "Push button.", romaji: "Botan wo osu." }, { jp: "再生 ボタン。", en: "Play button.", romaji: "Saisei botan." }] },
      { japanese: "画面", romaji: "gamen", english: "Screen", examples: [{ jp: "画面が 大きい。", en: "Screen is big.", romaji: "Gamen ga ookii." }, { jp: "スマホの 画面。", en: "Phone screen.", romaji: "Sumaho no gamen." }] },
      { japanese: "充電", romaji: "juuden", english: "Charging", examples: [{ jp: "充電器。", en: "Charger.", romaji: "Juudenki." }, { jp: "充電が ない。", en: "No charge/battery.", romaji: "Juuden ga nai." }] },
      { japanese: "アプリ", romaji: "apuri", english: "Application (App)", examples: [{ jp: "便利な アプリ。", en: "Useful app.", romaji: "Benri na apuri." }, { jp: "ゲーム アプリ。", en: "Game app.", romaji: "Geemu apuri." }] },
      { japanese: "パスワード", romaji: "pasuwaado", english: "Password", examples: [{ jp: "パスワードを 入れる。", en: "Enter password.", romaji: "Pasuwaado wo ireru." }, { jp: "パスワード 変更。", en: "Change password.", romaji: "Pasuwaado henkou." }] },
      { japanese: "コピー", romaji: "kopii", english: "Copy", examples: [{ jp: "コピーを する。", en: "Make copy.", romaji: "Kopii wo suru." }, { jp: "コピー機。", en: "Copier.", romaji: "Kopiiki." }] },
      { japanese: "ファックス", romaji: "fakkusu", english: "Fax", examples: [{ jp: "ファックスを 送る。", en: "Send fax.", romaji: "Fakkusu wo okuru." }, { jp: "ファックス 番号。", en: "Fax number.", romaji: "Fakkusu bangou." }] },
      { japanese: "ビデオ", romaji: "bideo", english: "Video", examples: [{ jp: "ビデオを 撮る。", en: "Record video.", romaji: "Bideo wo toru." }, { jp: "ビデオ通話。", en: "Video call.", romaji: "Bideo tsuuwa." }] },
      { japanese: "マイク", romaji: "maiku", english: "Microphone", examples: [{ jp: "マイクを 持つ。", en: "Hold mic.", romaji: "Maiku wo motsu." }, { jp: "マイク テスト。", en: "Mic test.", romaji: "Maiku tesuto." }] },
      { japanese: "イヤホン", romaji: "iyahon", english: "Earphones", examples: [{ jp: "イヤホンで 聞く。", en: "Listen with earphone.", romaji: "Iyahon de kiku." }, { jp: "イヤホンを つける。", en: "Put on earphones.", romaji: "Iyahon wo tsukeru." }] },
      { japanese: "ニュース", romaji: "nyuusu", english: "News", examples: [{ jp: "ニュースを 見る。", en: "Watch news.", romaji: "Nyuusu wo miru." }, { jp: "良い ニュース。", en: "Good news.", romaji: "Ii nyuusu." }] },
      { japanese: "データ", romaji: "deeta", english: "Data", examples: [{ jp: "データを 保存する。", en: "Save data.", romaji: "Deeta wo hozon suru." }, { jp: "データが 消えた。", en: "Data vanished.", romaji: "Deeta ga kieta." }] },
      { japanese: "ファイル", romaji: "fairu", english: "File", examples: [{ jp: "ファイルを 開く。", en: "Open file.", romaji: "Fairu wo hiraku." }, { jp: "クリア ファイル。", en: "Clear folder.", romaji: "Kuria fairu." }] }
    ]
  }
];
