export const chunk2 = [
  {
    id: 6,
    level: "N5",
    title: "Home & Objects",
    description: "Furniture, appliances, and common household items",
    words: [
      { japanese: "家", romaji: "ie / uchi", english: "House/Home", examples: [{ jp: "広い 家。", en: "Spacious house.", romaji: "Hiroi ie." }, { jp: "家に帰る。", en: "Go home.", romaji: "Uchi ni kaeru." }] },
      { japanese: "部屋", romaji: "heya", english: "Room", examples: [{ jp: "私の 部屋。", en: "My room.", romaji: "Watashi no heya." }, { jp: "部屋を 掃除する。", en: "Clean the room.", romaji: "Heya wo souji suru." }] },
      { japanese: "鍵", romaji: "kagi", english: "Key", examples: [{ jp: "鍵を かける。", en: "Lock the door.", romaji: "Kagi wo kakeru." }, { jp: "鍵を 無くした。", en: "Lost the key.", romaji: "Kagi wo nakushita." }] },
      { japanese: "窓", romaji: "mado", english: "Window", examples: [{ jp: "窓を 開ける。", en: "Open the window.", romaji: "Mado wo akeru." }, { jp: "窓側。", en: "Window side.", romaji: "Madogawa." }] },
      { japanese: "ドア", romaji: "doa", english: "Door", examples: [{ jp: "ドアを 閉める。", en: "Close the door.", romaji: "Doa wo shimeru." }, { jp: "ドアが 開く。", en: "Door opens.", romaji: "Doa ga aku." }] },
      { japanese: "机", romaji: "tsukue", english: "Desk", examples: [{ jp: "机の 上。", en: "On the desk.", romaji: "Tsukue no ue." }, { jp: "勉強机。", en: "Study desk.", romaji: "Benkyouzukue." }] },
      { japanese: "椅子", romaji: "isu", english: "Chair", examples: [{ jp: "椅子に 座る。", en: "Sit on chair.", romaji: "Isu ni suwaru." }, { jp: "固い 椅子。", en: "Hard chair.", romaji: "Katai isu." }] },
      { japanese: "テーブル", romaji: "teeburu", english: "Table", examples: [{ jp: "テーブルを 拭く。", en: "Wipe the table.", romaji: "Teeburu wo fuku." }, { jp: "丸い テーブル。", en: "Round table.", romaji: "Marui teeburu." }] },
      { japanese: "テレビ", romaji: "terebi", english: "TV", examples: [{ jp: "テレビを 見る。", en: "Watch TV.", romaji: "Terebi wo miru." }, { jp: "テレビ番組。", en: "TV program.", romaji: "Terebi bangumi." }] },
      { japanese: "ラジオ", romaji: "rajio", english: "Radio", examples: [{ jp: "ラジオを 聞く。", en: "Listen to radio.", romaji: "Rajio wo kiku." }, { jp: "ラジオ 体操。", en: "Radio calisthenics.", romaji: "Rajio taisou." }] },
      { japanese: "電話", romaji: "denwa", english: "Phone", examples: [{ jp: "電話を かける。", en: "Make a phone call.", romaji: "Denwa wo kakeru." }, { jp: "電話番。", en: "Phone duty.", romaji: "Denwaban." }] },
      { japanese: "携帯", romaji: "keitai", english: "Mobile phone", examples: [{ jp: "携帯を 忘れた。", en: "Forgot mobile phone.", romaji: "Keitai wo wasureta." }, { jp: "携帯 メール。", en: "Mobile mail.", romaji: "Keitai meeru." }] },
      { japanese: "パソコン", romaji: "pasokon", english: "PC/Computer", examples: [{ jp: "パソコンを 使う。", en: "Use PC.", romaji: "Pasokon wo tsukau." }, { jp: "パソコン 教室。", en: "PC class.", romaji: "Pasokon kyoushitsu." }] },
      { japanese: "電気", romaji: "denki", english: "Electricity/Light", examples: [{ jp: "電気を つける。", en: "Turn on light.", romaji: "Denki wo tsukeru." }, { jp: "電気を 消す。", en: "Turn off light.", romaji: "Denki wo kesu." }] },
      { japanese: "エアコン", romaji: "eakon", english: "Air conditioner", examples: [{ jp: "エアコンを つける。", en: "Turn on AC.", romaji: "Eakon wo tsukeru." }, { jp: "エアコンが ない。", en: "No AC.", romaji: "Eakon ga nai." }] },
      { japanese: "冷蔵庫", romaji: "reizouko", english: "Refrigerator", examples: [{ jp: "冷蔵庫に 入れる。", en: "Put into fridge.", romaji: "Reizouko ni ireru." }, { jp: "冷蔵庫が 空っぽ。", en: "Fridge is empty.", romaji: "Reizouko ga karappo." }] },
      { japanese: "時計", romaji: "tokei", english: "Clock", examples: [{ jp: "時計が 止まる。", en: "Clock stops.", romaji: "Tokei ga tomaru." }, { jp: "目覚まし時計。", en: "Alarm clock.", romaji: "Mezamashidokei." }] },
      { japanese: "ベッド", romaji: "beddo", english: "Bed", examples: [{ jp: "ベッドで 寝る。", en: "Sleep in bed.", romaji: "Beddo de neru." }, { jp: "ベッドメイキング。", en: "Bed making.", romaji: "Beddomeikingu." }] },
      { japanese: "布団", romaji: "futon", english: "Futon", examples: [{ jp: "布団を 敷く。", en: "Lay out futon.", romaji: "Futon wo shiku." }, { jp: "布団を 干す。", en: "Air the futon.", romaji: "Futon wo hosu." }] },
      { japanese: "本棚", romaji: "hondana", english: "Bookshelf", examples: [{ jp: "本棚に 並べる。", en: "Line up on bookshelf.", romaji: "Hondana ni naraberu." }, { jp: "本棚の 整理。", en: "Organize bookshelf.", romaji: "Hondana no seiri." }] },
      { japanese: "箱", romaji: "hako", english: "Box", examples: [{ jp: "箱を 開ける。", en: "Open box.", romaji: "Hako wo akeru." }, { jp: "段ボール箱。", en: "Cardboard box.", romaji: "Danbourubako." }] },
      { japanese: "ゴミ箱", romaji: "gomibako", english: "Trash can", examples: [{ jp: "ゴミ箱に 捨てる。", en: "Throw in trash can.", romaji: "Gomibako ni suteru." }, { jp: "ゴミ箱を 空にする。", en: "Empty trash can.", romaji: "Gomibako wo kara ni suru." }] },
      { japanese: "鏡", romaji: "kagami", english: "Mirror", examples: [{ jp: "鏡を 見る。", en: "Look in mirror.", romaji: "Kagami wo miru." }, { jp: "鏡に映る。", en: "Reflected in mirror.", romaji: "Kagami ni utsuru." }] },
      { japanese: "お風呂", romaji: "ofuro", english: "Bath", examples: [{ jp: "お風呂に 入る。", en: "Take bath.", romaji: "Ofuro ni hairu." }, { jp: "お風呂を 沸かす。", en: "Heat bath.", romaji: "Ofuro wo wakasu." }] },
      { japanese: "トイレ", romaji: "toire", english: "Toilet", examples: [{ jp: "トイレへ 行く。", en: "Go to toilet.", romaji: "Toire e iku." }, { jp: "トイレ掃除。", en: "Cleaning toilet.", romaji: "Toiresouji." }] },
      { japanese: "台所", romaji: "daidokoro", english: "Kitchen", examples: [{ jp: "台所で 料理する。", en: "Cook in kitchen.", romaji: "Daidokoro de ryouri suru." }, { jp: "広い 台所。", en: "Spacious kitchen.", romaji: "Hiroi daidokoro." }] },
      { japanese: "玄関", romaji: "genkan", english: "Entrance", examples: [{ jp: "玄関で 靴を脱ぐ。", en: "Take off shoes at entrance.", romaji: "Genkan de kutsu wo nugu." }, { jp: "玄関の チャイム。", en: "Doorbell.", romaji: "Genkan no chaimu." }] },
      { japanese: "庭", romaji: "niwa", english: "Garden", examples: [{ jp: "庭に 花がある。", en: "Flowers in garden.", romaji: "Niwa ni hana ga aru." }, { jp: "庭の手入れ。", en: "Gardening.", romaji: "Niwa no teire." }] },
      { japanese: "傘", romaji: "kasa", english: "Umbrella", examples: [{ jp: "傘を さす。", en: "Open umbrella.", romaji: "Kasa wo sasu." }, { jp: "傘を 忘れた。", en: "Forgot umbrella.", romaji: "Kasa wo wasureta." }] },
      { japanese: "鞄", romaji: "kaban", english: "Bag", examples: [{ jp: "鞄を 持つ。", en: "Hold bag.", romaji: "Kaban wo motsu." }, { jp: "重い 鞄。", en: "Heavy bag.", romaji: "Omoi kaban." }] }
    ]
  },
  {
    id: 7,
    level: "N5",
    title: "Colors & Shapes",
    description: "Colors, simple shapes, and descriptive words",
    words: [
      { japanese: "色", romaji: "iro", english: "Color", examples: [{ jp: "好きな 色。", en: "Favorite color.", romaji: "Suki na iro." }, { jp: "色々な 色。", en: "Various colors.", romaji: "Iroiro na iro." }] },
      { japanese: "赤", romaji: "aka", english: "Red", examples: [{ jp: "赤い りんご。", en: "Red apple.", romaji: "Akai ringo." }, { jp: "顔が 赤い。", en: "Face is red.", romaji: "Kao ga akai." }] },
      { japanese: "青", romaji: "ao", english: "Blue", examples: [{ jp: "青い 空。", en: "Blue sky.", romaji: "Aoi sora." }, { jp: "青信号。", en: "Green light (traffic).", romaji: "Aoshingou." }] },
      { japanese: "白", romaji: "shiro", english: "White", examples: [{ jp: "白い 雪。", en: "White snow.", romaji: "Shiroi yuki." }, { jp: "白い シャツ。", en: "White shirt.", romaji: "Shiroi shatsu." }] },
      { japanese: "黒", romaji: "kuro", english: "Black", examples: [{ jp: "黒い 猫。", en: "Black cat.", romaji: "Kuroi neko." }, { jp: "黒髪。", en: "Black hair.", romaji: "Kurokami." }] },
      { japanese: "黄色", romaji: "kiiro", english: "Yellow", examples: [{ jp: "黄色い 花。", en: "Yellow flower.", romaji: "Kiiroi hana." }, { jp: "黄色い 声。", en: "Shrill voice.", romaji: "Kiiroi koe." }] },
      { japanese: "緑", romaji: "midori", english: "Green", examples: [{ jp: "緑が 多い。", en: "Lots of greenery.", romaji: "Midori ga ooi." }, { jp: "緑色の 車。", en: "Green car.", romaji: "Midori iro no kuruma." }] },
      { japanese: "茶色", romaji: "chairo", english: "Brown", examples: [{ jp: "茶色の 靴。", en: "Brown shoes.", romaji: "Chairo no kutsu." }, { jp: "茶色に染める。", en: "Dye brown.", romaji: "Chairo ni someru." }] },
      { japanese: "ピンク", romaji: "pinku", english: "Pink", examples: [{ jp: "ピンクの ドレス。", en: "Pink dress.", romaji: "Pinku no doresu." }, { jp: "ピンク色の 空。", en: "Pink sky.", romaji: "Pinku iro no sora." }] },
      { japanese: "オレンジ", romaji: "orenji", english: "Orange", examples: [{ jp: "オレンジ色の シャツ。", en: "Orange shirt.", romaji: "Orenji iro no shatsu." }, { jp: "オレンジ。", en: "Orange.", romaji: "Orenji." }] },
      { japanese: "紫", romaji: "murasaki", english: "Purple", examples: [{ jp: "紫の 花。", en: "Purple flower.", romaji: "Murasaki no hana." }, { jp: "紫式部。", en: "Murasaki Shikibu.", romaji: "Murasaki Shikibu." }] },
      { japanese: "金", romaji: "kin", english: "Gold", examples: [{ jp: "金の 指輪。", en: "Gold ring.", romaji: "Kin no yubiwa." }, { jp: "金メダル。", en: "Gold medal.", romaji: "Kin medaru." }] },
      { japanese: "銀", romaji: "gin", english: "Silver", examples: [{ jp: "銀の スプーン。", en: "Silver spoon.", romaji: "Gin no supuun." }, { jp: "銀世界。", en: "Snowscape.", romaji: "Ginsekai." }] },
      { japanese: "灰色", romaji: "haiiro", english: "Grey", examples: [{ jp: "灰色の 空。", en: "Grey sky.", romaji: "Haiiro no sora." }, { jp: "鼠色。", en: "Mouse color (grey).", romaji: "Nezumiiro." }] },
      { japanese: "明るい", romaji: "akarui", english: "Bright", examples: [{ jp: "明るい 部屋。", en: "Bright room.", romaji: "Akarui heya." }, { jp: "明るい 性格。", en: "Cheerful personality.", romaji: "Akarui seikaku." }] },
      { japanese: "暗い", romaji: "kurai", english: "Dark", examples: [{ jp: "暗い 道。", en: "Dark road.", romaji: "Kurai michi." }, { jp: "顔色が 暗い。", en: "Gloomy expression.", romaji: "Kaoiro ga kurai." }] },
      { japanese: "丸い", romaji: "marui", english: "Round", examples: [{ jp: "丸い 顔。", en: "Round face.", romaji: "Marui kao." }, { jp: "地球は 丸い。", en: "Earth is round.", romaji: "Chikyuu wa marui." }] },
      { japanese: "四角い", romaji: "shikakui", english: "Square", examples: [{ jp: "四角い 箱。", en: "Square box.", romaji: "Shikakui hako." }, { jp: "四角い 部屋。", en: "Square room.", romaji: "Shikakui heya." }] },
      { japanese: "長い", romaji: "nagai", english: "Long", examples: [{ jp: "髪が 長い。", en: "Long hair.", romaji: "Kami ga nagai." }, { jp: "長い 話。", en: "Long story.", romaji: "Nagai hanashi." }] },
      { japanese: "短い", romaji: "mijikai", english: "Short", examples: [{ jp: "スカートが 短い。", en: "Skirt is short.", romaji: "Sukaato ga mijikai." }, { jp: "人生は 短い。", en: "Life is short.", romaji: "Jinsei wa mijikai." }] },
      { japanese: "大きい", romaji: "ookii", english: "Big", examples: [{ jp: "大きい 家。", en: "Big house.", romaji: "Ookii ie." }, { jp: "声が 大きい。", en: "Voice is loud.", romaji: "Koe ga ookii." }] },
      { japanese: "小さい", romaji: "chiisai", english: "Small", examples: [{ jp: "小さい 手。", en: "Small hand.", romaji: "Chiisai te." }, { jp: "小さい 頃。", en: "When I was little.", romaji: "Chiisai koro." }] },
      { japanese: "太い", romaji: "futoi", english: "Thick/Fat", examples: [{ jp: "太い 木。", en: "Thick tree.", romaji: "Futoi ki." }, { jp: "太い 線。", en: "Thick line.", romaji: "Futoi sen." }] },
      { japanese: "細い", romaji: "hosoi", english: "Thin/Slender", examples: [{ jp: "細い 道。", en: "Narrow road.", romaji: "Hosoi michi." }, { jp: "脚が 細い。", en: "Legs are thin.", romaji: "Ashi ga hosoi." }] },
      { japanese: "広い", romaji: "hiroi", english: "Wide/Spacious", examples: [{ jp: "広い 海。", en: "Wide ocean.", romaji: "Hiroi umi." }, { jp: "心が 広い。", en: "Generous heart.", romaji: "Kokoro ga hiroi." }] },
      { japanese: "狭い", romaji: "semai", english: "Narrow", examples: [{ jp: "狭い 部屋。", en: "Cramped room.", romaji: "Semai heya." }, { jp: "世間は 狭い。", en: "It's a small world.", romaji: "Seken wa semai." }] },
      { japanese: "同じ", romaji: "onaji", english: "Same", examples: [{ jp: "同じ 服。", en: "Same clothes.", romaji: "Onaji fuku." }, { jp: "私も 同じです。", en: "Me too.", romaji: "Watashi mo onaji desu." }] },
      { japanese: "違う", romaji: "chigau", english: "Different/Wrong", examples: [{ jp: "色が 違う。", en: "Color is different.", romaji: "Iro ga chigau." }, { jp: "それは 違う。", en: "That is wrong.", romaji: "Sore wa chigau." }] },
      { japanese: "形", romaji: "katachi", english: "Shape", examples: [{ jp: "変な 形。", en: "Strange shape.", romaji: "Hen na katachi." }, { jp: "形を 整える。", en: "Fix the shape.", romaji: "Katachi wo totonoeru." }] },
      { japanese: "三角", romaji: "sankaku", english: "Triangle", examples: [{ jp: "三角定規。", en: "Triangular ruler.", romaji: "Sankaku jougi." }, { jp: "おにぎりは 三角。", en: "Rice ball is triangular.", romaji: "Onigiri wa sankaku." }] }
    ]
  },
  {
    id: 8,
    level: "N5",
    title: "Body & Health",
    description: "Body parts and health conditions",
    words: [
      { japanese: "体", romaji: "karada", english: "Body", examples: [{ jp: "体を 動かす。", en: "Move body.", romaji: "Karada wo ugokasu." }, { jp: "体に いい。", en: "Good for body.", romaji: "Karada ni ii." }] },
      { japanese: "頭", romaji: "atama", english: "Head", examples: [{ jp: "頭が 痛い。", en: "Headache.", romaji: "Atama ga itai." }, { jp: "頭がいい。", en: "Smart.", romaji: "Atama ga ii." }] },
      { japanese: "髪", romaji: "kami", english: "Hair", examples: [{ jp: "髪を 切る。", en: "Cut hair.", romaji: "Kami wo kiru." }, { jp: "長い 髪。", en: "Long hair.", romaji: "Nagai kami." }] },
      { japanese: "顔", romaji: "kao", english: "Face", examples: [{ jp: "顔を 洗う。", en: "Wash face.", romaji: "Kao wo arau." }, { jp: "広い 顔。", en: "Wide face (well known).", romaji: "Hiroi kao." }] },
      { japanese: "目", romaji: "me", english: "Eye", examples: [{ jp: "目が 悪い。", en: "Bad eyesight.", romaji: "Me ga warui." }, { jp: "目薬。", en: "Eye drops.", romaji: "Megusuri." }] },
      { japanese: "耳", romaji: "mimi", english: "Ear", examples: [{ jp: "耳が 遠い。", en: "Hard of hearing.", romaji: "Mimi ga tooi." }, { jp: "耳を 澄ます。", en: "Listen carefully.", romaji: "Mimi wo sumasu." }] },
      { japanese: "鼻", romaji: "hana", english: "Nose", examples: [{ jp: "鼻水が 出る。", en: "Runny nose.", romaji: "Hanamizu ga deru." }, { jp: "鼻が高い。", en: "Proud.", romaji: "Hana ga takai." }] },
      { japanese: "口", romaji: "kuchi", english: "Mouth", examples: [{ jp: "口を 開ける。", en: "Open mouth.", romaji: "Kuchi wo akeru." }, { jp: "口数が 多い。", en: "Talkative.", romaji: "Kuchikazu ga ooi." }] },
      { japanese: "歯", romaji: "ha", english: "Tooth", examples: [{ jp: "歯を 磨く。", en: "Brush teeth.", romaji: "Ha wo migaku." }, { jp: "歯医者。", en: "Dentist.", romaji: "Haisha." }] },
      { japanese: "首", romaji: "kubi", english: "Neck", examples: [{ jp: "首が 痛い。", en: "Neck hurts.", romaji: "Kubi ga itai." }, { jp: "首になる。", en: "Be fired.", romaji: "Kubi ni naru." }] },
      { japanese: "手", romaji: "te", english: "Hand", examples: [{ jp: "手を 洗う。", en: "Wash hands.", romaji: "Te wo arau." }, { jp: "手を つなぐ。", en: "Hold hands.", romaji: "Te wo tsunagu." }] },
      { japanese: "足", romaji: "ashi", english: "Leg/Foot", examples: [{ jp: "足が 長い。", en: "Long legs.", romaji: "Ashi ga nagai." }, { jp: "足が 速い。", en: "Fast runner.", romaji: "Ashi ga hayai." }] },
      { japanese: "指", romaji: "yubi", english: "Finger", examples: [{ jp: "指を 切る。", en: "Cut finger.", romaji: "Yubi wo kiru." }, { jp: "指輪。", en: "Ring.", romaji: "Yubiwa." }] },
      { japanese: "背", romaji: "se", english: "Height/Back", examples: [{ jp: "背が 高い。", en: "Tall.", romaji: "Se ga takai." }, { jp: "背中。", en: "Back (body part).", romaji: "Senaka." }] },
      { japanese: "お腹", romaji: "onaka", english: "Stomach", examples: [{ jp: "お腹が 空いた。", en: "Hungry.", romaji: "Onaka ga suita." }, { jp: "お腹が 痛い。", en: "Stomachache.", romaji: "Onaka ga itai." }] },
      { japanese: "喉", romaji: "nodo", english: "Throat", examples: [{ jp: "喉が 渇いた。", en: "Thirsty.", romaji: "Nodo ga kawaita." }, { jp: "喉飴。", en: "Throat lozenge.", romaji: "Nodoame." }] },
      { japanese: "胸", romaji: "mune", english: "Chest", examples: [{ jp: "胸が 苦しい。", en: "Chest hurts/painful.", romaji: "Mune ga kurushii." }, { jp: "胸を 張る。", en: "Puff out chest (proud).", romaji: "Mune wo haru." }] },
      { japanese: "風邪", romaji: "kaze", english: "Cold (illness)", examples: [{ jp: "風邪を 引く。", en: "Catch a cold.", romaji: "Kaze wo hiku." }, { jp: "風邪薬。", en: "Cold medicine.", romaji: "Kazegusuri." }] },
      { japanese: "熱", romaji: "netsu", english: "Fever/Heat", examples: [{ jp: "熱が ある。", en: "Have a fever.", romaji: "Netsu ga aru." }, { jp: "熱を 測る。", en: "Measure fever.", romaji: "Netsu wo hakaru." }] },
      { japanese: "病気", romaji: "byouki", english: "Illness", examples: [{ jp: "病気に なる。", en: "Get sick.", romaji: "Byouki ni naru." }, { jp: "重い 病気。", en: "Serious illness.", romaji: "Omoi byouki." }] },
      { japanese: "病院", romaji: "byouin", english: "Hospital", examples: [{ jp: "病院へ 行く。", en: "Go to hospital.", romaji: "Byouin e iku." }, { jp: "大きい 病院。", en: "Big hospital.", romaji: "Ookii byouin." }] },
      { japanese: "医者", romaji: "isha", english: "Doctor", examples: [{ jp: "医者に 見てもらう。", en: "See a doctor.", romaji: "Isha ni mitemorau." }, { jp: "医者の 卵。", en: "Med student.", romaji: "Isha no tamago." }] },
      { japanese: "薬", romaji: "kusuri", english: "Medicine", examples: [{ jp: "薬を 飲む。", en: "Take medicine.", romaji: "Kusuri wo nomu." }, { jp: "薬屋。", en: "Pharmacy.", romaji: "Kusuriya." }] },
      { japanese: "痛い", romaji: "itai", english: "Painful", examples: [{ jp: "ここが 痛い。", en: "It hurts here.", romaji: "Koko ga itai." }, { jp: "お腹が 痛い。", en: "Stomachache.", romaji: "Onaka ga itai." }] },
      { japanese: "声", romaji: "koe", english: "Voice", examples: [{ jp: "大きい 声。", en: "Loud voice.", romaji: "Ookii koe." }, { jp: "いい 声。", en: "Nice voice.", romaji: "Ii koe." }] },
      { japanese: "心", romaji: "kokoro", english: "Heart/Mind", examples: [{ jp: "心が 広い。", en: "Generous.", romaji: "Kokoro ga hiroi." }, { jp: "心を 込めて。", en: "Wholeheartedly.", romaji: "Kokoro wo komete." }] },
      { japanese: "肩", romaji: "kata", english: "Shoulder", examples: [{ jp: "肩が 凝る。", en: "Stiff shoulders.", romaji: "Kata ga koru." }, { jp: "肩を たたく。", en: "Tap shoulder.", romaji: "Kata wo tataku." }] },
      { japanese: "腰", romaji: "koshi", english: "Waist/Lower Back", examples: [{ jp: "腰が 痛い。", en: "Backache.", romaji: "Koshi ga itai." }, { jp: "腰を かける。", en: "Sit down.", romaji: "Koshi wo kakeru." }] },
      { japanese: "膝", romaji: "hiza", english: "Knee", examples: [{ jp: "膝を 曲げる。", en: "Bend knees.", romaji: "Hiza wo mageru." }, { jp: "膝枕。", en: "Lap pillow.", romaji: "Hizamakura." }] },
      { japanese: "血", romaji: "chi", english: "Blood", examples: [{ jp: "血が 出る。", en: "Bleed.", romaji: "Chi ga deru." }, { jp: "血液型。", en: "Blood type.", romaji: "Ketsuekigata." }] }
    ]
  },
  {
    id: 9,
    level: "N5",
    title: "Clothing & Accessories",
    description: "Clothes, shoes, and wearing verbs",
    words: [
      { japanese: "服", romaji: "fuku", english: "Clothes", examples: [{ jp: "服を 着る。", en: "Put on clothes.", romaji: "Fuku wo kiru." }, { jp: "服を 買う。", en: "Buy clothes.", romaji: "Fuku wo kau." }] },
      { japanese: "着る", romaji: "kiru", english: "To wear (upper body)", examples: [{ jp: "シャツを 着る。", en: "Wear a shirt.", romaji: "Shatsu wo kiru." }, { jp: "ドレスを 着る。", en: "Wear a dress.", romaji: "Doresu wo kiru." }] },
      { japanese: "脱ぐ", romaji: "nugu", english: "To take off", examples: [{ jp: "靴を 脱ぐ。", en: "Take off shoes.", romaji: "Kutsu wo nugu." }, { jp: "コートを 脱ぐ。", en: "Take off coat.", romaji: "Kooto wo nugu." }] },
      { japanese: "履く", romaji: "haku", english: "To wear (lower body)", examples: [{ jp: "ズボンを 履く。", en: "Wear pants.", romaji: "Zubon wo haku." }, { jp: "靴を 履く。", en: "Wear shoes.", romaji: "Kutsu wo haku." }] },
      { japanese: "被る", romaji: "kaburu", english: "To wear (head)", examples: [{ jp: "帽子を 被る。", en: "Wear a hat.", romaji: "Boushi wo kaburu." }, { jp: "水を 被る。", en: "Pour water on self.", romaji: "Mizu wo kaburu." }] },
      { japanese: "かける", romaji: "kakeru", english: "To wear (glasses)", examples: [{ jp: "眼鏡を かける。", en: "Put on glasses.", romaji: "Megane wo kakeru." }, { jp: "サングラスを かける。", en: "Put on sunglasses.", romaji: "Sangurasu wo kakeru." }] },
      { japanese: "する", romaji: "suru", english: "To wear (accessories)", examples: [{ jp: "ネクタイを する。", en: "Wear a tie.", romaji: "Nekutai wo suru." }, { jp: "時計を する。", en: "Wear a watch.", romaji: "Tokei wo suru." }] },
      { japanese: "シャツ", romaji: "shatsu", english: "Shirt", examples: [{ jp: "白い シャツ。", en: "White shirt.", romaji: "Shiroi shatsu." }, { jp: "Tシャツ。", en: "T-shirt.", romaji: "Tiishatsu." }] },
      { japanese: "コート", romaji: "kooto", english: "Coat", examples: [{ jp: "温かい コート。", en: "Warm coat.", romaji: "Atatakai kooto." }, { jp: "レインコート。", en: "Raincoat.", romaji: "Reinkooto." }] },
      { japanese: "セーター", romaji: "seetaa", english: "Sweater", examples: [{ jp: "セーターを 編む。", en: "Knit a sweater.", romaji: "Seetaa wo amu." }, { jp: "ウールの セーター。", en: "Wool sweater.", romaji: "Uuru no seetaa." }] },
      { japanese: "ズボン", romaji: "zubon", english: "Pants/Trousers", examples: [{ jp: "長い ズボン。", en: "Long pants.", romaji: "Nagai zubon." }, { jp: "ズボンの ポケット。", en: "Pants pocket.", romaji: "Zubon no poketto." }] },
      { japanese: "スカート", romaji: "sukaato", english: "Skirt", examples: [{ jp: "スカートを 履く。", en: "Wear a skirt.", romaji: "Sukaato wo haku." }, { jp: "短い スカート。", en: "Short skirt.", romaji: "Mijikai sukaato." }] },
      { japanese: "靴", romaji: "kutsu", english: "Shoes", examples: [{ jp: "靴を 磨く。", en: "Polish shoes.", romaji: "Kutsu wo migaku." }, { jp: "新しい 靴。", en: "New shoes.", romaji: "Atarashii kutsu." }] },
      { japanese: "靴下", romaji: "kutsushita", english: "Socks", examples: [{ jp: "靴下を 履く。", en: "Wear socks.", romaji: "Kutsushita wo haku." }, { jp: "穴の空いた 靴下。", en: "Socks with holes.", romaji: "Ana no aita kutsushita." }] },
      { japanese: "帽子", romaji: "boushi", english: "Hat/Cap", examples: [{ jp: "帽子を 脱ぐ。", en: "Take off hat.", romaji: "Boushi wo nugu." }, { jp: "赤い 帽子。", en: "Red hat.", romaji: "Akai boushi." }] },
      { japanese: "眼鏡", romaji: "megane", english: "Glasses", examples: [{ jp: "眼鏡を 探す。", en: "Look for glasses.", romaji: "Megane wo sagasu." }, { jp: "眼鏡ケース。", en: "Glasses case.", romaji: "Megane keesu." }] },
      { japanese: "ネクタイ", romaji: "nekutai", english: "Necktie", examples: [{ jp: "ネクタイを 締める。", en: "Tie a necktie.", romaji: "Nekutai wo shimeru." }, { jp: "派手な ネクタイ。", en: "Flashy tie.", romaji: "Hade na nekutai." }] },
      { japanese: "ポケット", romaji: "poketto", english: "Pocket", examples: [{ jp: "ポケットに 入れる。", en: "Put in pocket.", romaji: "Poketto ni ireru." }, { jp: "ポケットマネー。", en: "Pocket money.", romaji: "Pokettomanee." }] },
      { japanese: "ボタン", romaji: "botan", english: "Button", examples: [{ jp: "ボタンを 留める。", en: "Fasten button.", romaji: "Botan wo tomeru." }, { jp: "ボタンが 取れた。", en: "Button came off.", romaji: "Botan ga toreta." }] },
      { japanese: "財布", romaji: "saifu", english: "Wallet", examples: [{ jp: "財布を 落とした。", en: "Dropped wallet.", romaji: "Saifu wo otoshita." }, { jp: "財布の 中身。", en: "Contents of wallet.", romaji: "Saifu no nakami." }] },
      { japanese: "洗濯", romaji: "sentaku", english: "Laundry", examples: [{ jp: "洗濯する。", en: "Do laundry.", romaji: "Sentaku suru." }, { jp: "洗濯機。", en: "Washing machine.", romaji: "Sentakuki." }] },
      { japanese: "スーツ", romaji: "suutsu", english: "Suit", examples: [{ jp: "スーツを 着る。", en: "Wear a suit.", romaji: "Suutsu wo kiru." }, { jp: "スーツケース。", en: "Suitcase.", romaji: "Suutsukeesu." }] },
      { japanese: "ドレス", romaji: "doresu", english: "Dress", examples: [{ jp: "パーティ ドレス。", en: "Party dress.", romaji: "Paati doresu." }, { jp: "ウェディング ドレス。", en: "Wedding dress.", romaji: "Wedingu doresu." }] },
      { japanese: "着物", romaji: "kimono", english: "Kimono", examples: [{ jp: "着物を 着る。", en: "Wear kimono.", romaji: "Kimono wo kiru." }, { jp: "着物 姿。", en: "In kimono.", romaji: "Kimono sugata." }] },
      { japanese: "浴衣", romaji: "yukata", english: "Yukata", examples: [{ jp: "夏は 浴衣。", en: "Yukata in summer.", romaji: "Natsu wa yukata." }, { jp: "浴衣で つまずく。", en: "Trip in yukata.", romaji: "Yukata de tsumazuku." }] },
      { japanese: "スリッパ", romaji: "surippa", english: "Slippers", examples: [{ jp: "スリッパに 履き替える。", en: "Change into slippers.", romaji: "Surippa ni hakikaeru." }, { jp: "トイレの スリッパ。", en: "Toilet slippers.", romaji: "Toire no surippa." }] },
      { japanese: "手袋", romaji: "tebukuro", english: "Gloves", examples: [{ jp: "手袋を する。", en: "Wear gloves.", romaji: "Tebukuro wo suru." }, { jp: "ゴム 手袋。", en: "Rubber gloves.", romaji: "Gomu tebukuro." }] },
      { japanese: "指輪", romaji: "yubiwa", english: "Ring", examples: [{ jp: "指輪を はめる。", en: "Put on ring.", romaji: "Yubiwa wo hameru." }, { jp: "結婚 指輪。", en: "Wedding ring.", romaji: "Kekkon yubiwa." }] },
      { japanese: "傘", romaji: "kasa", english: "Umbrella", examples: [{ jp: "傘を 忘れないで。", en: "Don't forget umbrella.", romaji: "Kasa wo wasurenaide." }, { jp: "折りたたみ傘。", en: "Folding umbrella.", romaji: "Oritatamigasa." }] },
      { japanese: "ベルト", romaji: "beruto", english: "Belt", examples: [{ jp: "ベルトを 締める。", en: "Tighten belt.", romaji: "Beruto wo shimeru." }, { jp: "シートベルト。", en: "Seatbelt.", romaji: "Shiitoberuto." }] }
    ]
  },
  {
    id: 10,
    level: "N5",
    title: "Places & City",
    description: "Common locations in the city and navigation",
    words: [
      { japanese: "学校", romaji: "gakkou", english: "School", examples: [{ jp: "学校へ 行く。", en: "Go to school.", romaji: "Gakkou e iku." }, { jp: "小学校。", en: "Elementary school.", romaji: "Shougakkou." }] },
      { japanese: "会社", romaji: "kaisha", english: "Company", examples: [{ jp: "会社で 働く。", en: "Work at company.", romaji: "Kaisha de hataraku." }, { jp: "会社員。", en: "Office worker.", romaji: "Kaishain." }] },
      { japanese: "駅", romaji: "eki", english: "Station", examples: [{ jp: "駅で 会う。", en: "Meet at station.", romaji: "Eki de au." }, { jp: "駅前。", en: "In front of station.", romaji: "Ekimae." }] },
      { japanese: "店", romaji: "mise", english: "Shop", examples: [{ jp: "店を 開ける。", en: "Open shop.", romaji: "Mise wo akeru." }, { jp: "店員。", en: "Shop clerk.", romaji: "Tenin." }] },
      { japanese: "銀行", romaji: "ginkou", english: "Bank", examples: [{ jp: "銀行で お金を下ろす。", en: "Withdraw money at bank.", romaji: "Ginkou de okane wo orosu." }, { jp: "銀行員。", en: "Banker.", romaji: "Ginkouin." }] },
      { japanese: "郵便局", romaji: "yuubinkyoku", english: "Post office", examples: [{ jp: "郵便局へ 行く。", en: "Go to post office.", romaji: "Yuubinkyoku e iku." }, { jp: "近くの 郵便局。", en: "Nearby post office.", romaji: "Chikaku no yuubinkyoku." }] },
      { japanese: "図書館", romaji: "toshokan", english: "Library", examples: [{ jp: "図書館で 勉強する。", en: "Study at library.", romaji: "Toshokan de benkyou suru." }, { jp: "図書館の 本。", en: "Library book.", romaji: "Toshokan no hon." }] },
      { japanese: "公園", romaji: "kouen", english: "Park", examples: [{ jp: "公園で 遊ぶ。", en: "Play in park.", romaji: "Kouen de asobu." }, { jp: "広い 公園。", en: "Big park.", romaji: "Hiroi kouen." }] },
      { japanese: "交番", romaji: "kouban", english: "Police box", examples: [{ jp: "交番で 道を聞く。", en: "Ask way at police box.", romaji: "Kouban de michi wo kiku." }, { jp: "駅前の 交番。", en: "Station police box.", romaji: "Ekimae no kouban." }] },
      { japanese: "入口", romaji: "iriguchi", english: "Entrance", examples: [{ jp: "入口は こちら。", en: "Entrance is here.", romaji: "Iriguchi wa kochira." }, { jp: "建物の 入口。", en: "Building entrance.", romaji: "Tatemono no iriguchi." }] },
      { japanese: "出口", romaji: "deguchi", english: "Exit", examples: [{ jp: "出口は どこですか。", en: "Where is the exit?", romaji: "Deguchi wa doko desu ka." }, { jp: "非常口。", en: "Emergency exit.", romaji: "Hijouguchi." }] },
      { japanese: "トイレ", romaji: "toire", english: "Toilet", examples: [{ jp: "トイレは あそこ。", en: "Toilet is there.", romaji: "Toire wa asoko." }, { jp: "公衆トイレ。", en: "Public toilet.", romaji: "Koushuu toire." }] },
      { japanese: "道", romaji: "michi", english: "Road/Way", examples: [{ jp: "道を 歩く。", en: "Walk on road.", romaji: "Michi wo aruku." }, { jp: "近道。", en: "Shortcut.", romaji: "Chikamichi." }] },
      { japanese: "交差点", romaji: "kousaten", english: "Intersection", examples: [{ jp: "交差点を 渡る。", en: "Cross intersection.", romaji: "Kousaten wo wataru." }, { jp: "次の 交差点。", en: "Next intersection.", romaji: "Tsugi no kousaten." }] },
      { japanese: "信号", romaji: "shingou", english: "Traffic light", examples: [{ jp: "信号を 待つ。", en: "Wait for signal.", romaji: "Shingou wo matsu." }, { jp: "信号無視。", en: "Ignoring signal.", romaji: "Shingoumushi." }] },
      { japanese: "角", romaji: "kado", english: "Corner", examples: [{ jp: "角を 曲がる。", en: "Turn the corner.", romaji: "Kado wo magaru." }, { jp: "曲がり角。", en: "Street corner.", romaji: "Magarikado." }] },
      { japanese: "ホテル", romaji: "hoteru", english: "Hotel", examples: [{ jp: "ホテルに 泊まる。", en: "Stay at hotel.", romaji: "Hoteru ni tomaru." }, { jp: "高級 ホテル。", en: "Luxury hotel.", romaji: "Koukyuu hoteru." }] },
      { japanese: "デパート", romaji: "depaato", english: "Department store", examples: [{ jp: "デパートで 買い物。", en: "Shop at dept store.", romaji: "Depaato de kaimono." }, { jp: "地下の 食品売り場。", en: "Basement food floor.", romaji: "Chika no shokuhinuriba." }] },
      { japanese: "アパート", romaji: "apaato", english: "Apartment", examples: [{ jp: "アパートを 探す。", en: "Look for apartment.", romaji: "Apaato wo sagasu." }, { jp: "安い アパート。", en: "Cheap apartment.", romaji: "Yasui apaato." }] },
      { japanese: "コンビニ", romaji: "konbini", english: "Convenience store", examples: [{ jp: "コンビニへ 行く。", en: "Go to Konbini.", romaji: "Konbini e iku." }, { jp: "便利な コンビニ。", en: "Convenient store.", romaji: "Benri na konbini." }] },
      { japanese: "プール", romaji: "puuru", english: "Pool", examples: [{ jp: "プールで 泳ぐ。", en: "Swim in pool.", romaji: "Puuru de oyogu." }, { jp: "市民 プール。", en: "Municipal pool.", romaji: "Shimin puuru." }] },
      { japanese: "映画館", romaji: "eigakan", english: "Movie theater", examples: [{ jp: "映画館で 見る。", en: "Watch at cinema.", romaji: "Eigakan de miru." }, { jp: "映画館へ 行こう。", en: "Let's go to cinema.", romaji: "Eigakan e ikou." }] },
      { japanese: "大使館", romaji: "taishikan", english: "Embassy", examples: [{ jp: "日本 大使館。", en: "Japanese Embassy.", romaji: "Nihon taishikan." }, { jp: "ビザの 申請。", en: "Visa application.", romaji: "Biza no shinsei." }] },
      { japanese: "警察", romaji: "keisatsu", english: "Police", examples: [{ jp: "警察を 呼ぶ。", en: "Call police.", romaji: "Keisatsu wo yobu." }, { jp: "警察官。", en: "Police officer.", romaji: "Keisatsukan." }] },
      { japanese: "建物", romaji: "tatemono", english: "Building", examples: [{ jp: "高い 建物。", en: "Tall building.", romaji: "Takai tatemono." }, { jp: "古い 建物。", en: "Old building.", romaji: "Furui tatemono." }] },
      { japanese: "エレベーター", romaji: "erebeetaa", english: "Elevator", examples: [{ jp: "エレベーターに乗る。", en: "Ride elevator.", romaji: "Erebeetaa ni noru." }, { jp: "故障中。", en: "Out of order.", romaji: "Koshouchuu." }] },
      { japanese: "階段", romaji: "kaidan", english: "Stairs", examples: [{ jp: "階段を 上がる。", en: "Go up stairs.", romaji: "Kaidan wo agaru." }, { jp: "急な 階段。", en: "Steep stairs.", romaji: "Kyuu na kaidan." }] },
      { japanese: "部屋", romaji: "heya", english: "Room", examples: [{ jp: "私の 部屋。", en: "My room.", romaji: "Watashi no heya." }, { jp: "部屋代。", en: "Room rent.", romaji: "Heyadai." }] },
      { japanese: "教室", romaji: "kyoushitsu", english: "Classroom", examples: [{ jp: "教室に入る。", en: "Enter classroom.", romaji: "Kyoushitsu ni hairu." }, { jp: "日本語 教室。", en: "Japanese class.", romaji: "Nihongo kyoushitsu." }] },
      { japanese: "食堂", romaji: "shokudou", english: "Cafeteria/Canteen", examples: [{ jp: "社員 食堂。", en: "Employee canteen.", romaji: "Shain shokudou." }, { jp: "食堂で 食べる。", en: "Eat at cafeteria.", romaji: "Shokudou de taberu." }] }
    ]
  }
];
