export const chunk12 = [
  {
    id: 56,
    level: "N3",
    title: "Health & Medical Care",
    description: "Advanced vocabulary for symptoms, treatment, and medical exams",
    words: [
      { japanese: "診察", romaji: "shinsatsu", english: "Medical examination", examples: [{ jp: "診察を 受ける。", en: "Get examined.", romaji: "Shinsatstsu wo ukeru." }, { jp: "診察室は あちらです。", en: "The examination room is over there.", romaji: "Shinsatsushitsu wa achira desu." }] },
      { japanese: "治療", romaji: "chiryou", english: "Treatment", examples: [{ jp: "歯の 治療。", en: "Dental treatment.", romaji: "Ha no chiryou." }, { jp: "治療に 専念する。", en: "Devote oneself to treatment.", romaji: "Chiryou ni sennen suru." }] },
      { japanese: "回復", romaji: "kaifuku", english: "Recovery", examples: [{ jp: "健康が 回復する。", en: "Recover health.", romaji: "Kenkou ga kaifuku suru." }, { jp: "急速な 回復。", en: "Rapid recovery.", romaji: "Kyuusokuna kaifuku." }] },
      { japanese: "症状", romaji: "shoujou", english: "Symptom", examples: [{ jp: "風邪の 症状。", en: "Symptoms of a cold.", romaji: "Kaze no shoujou." }, { jp: "症状が 悪化する。", en: "Symptoms get worse.", romaji: "Shoujou ga akkasuru." }] },
      { japanese: "予防", romaji: "yobou", english: "Prevention", examples: [{ jp: "病気を 予防する。", en: "Prevent diseases.", romaji: "Byouki wo yobou suru." }, { jp: "予防 接種。", en: "Vaccination.", romaji: "Yobou sesshu." }] },
      { japanese: "栄養", romaji: "eiyou", english: "Nutrition", examples: [{ jp: "栄養を 摂る。", en: "Get nutrition.", romaji: "Eiyou wo toru." }, { jp: "栄養 バランス。", en: "Nutritional balance.", romaji: "Eiyou balansusu." }] },
      { japanese: "消化", romaji: "shouka", english: "Digestion", examples: [{ jp: "消化に 良い食べ物。", en: "Food that is easy to digest.", romaji: "Shouka ni yoi tabemono." }, { jp: "情報の 消化。", en: "Digestion/assimilation of info.", romaji: "Jouhou no shouka." }] },
      { japanese: "呼吸", romaji: "kokyuu", english: "Breathing", examples: [{ jp: "深 呼吸をする。", en: "Take a deep breath.", romaji: "Shin kokyuu wo suru." }, { jp: "呼吸が 荒い。", en: "Breathing heavily.", romaji: "Kokyuu ga arai." }] },
      { japanese: "脈拍", romaji: "myakuhaku", english: "Pulse", examples: [{ jp: "脈拍を 測る。", en: "Measure the pulse.", romaji: "Myakuhaku wo hakaru." }, { jp: "脈拍が 速い。", en: "The pulse is fast.", romaji: "Myakuhaku ga hayai." }] },
      { japanese: "血圧", romaji: "ketsuatsu", english: "Blood pressure", examples: [{ jp: "血圧が 上がる。", en: "Blood pressure rises.", romaji: "Ketsuatsu ga agaru." }, { jp: "高 血圧。", en: "High blood pressure.", romaji: "Kou ketsuatsu." }] },
      { japanese: "体温", romaji: "taion", english: "Body temperature", examples: [{ jp: "体温を 計る。", en: "Measure body temp.", romaji: "Taion wo hakaru." }, { jp: "平 熱。", en: "Normal body temperature.", romaji: "Heinetsu." }] },
      { japanese: "下痢", romaji: "geri", english: "Diarrhea", examples: [{ jp: "ひどい 下痢。", en: "Terrible diarrhea.", romaji: "Hidoi geri." }, { jp: "お腹を 下す。", en: "Have loose bowels.", romaji: "Onaka wo kudasu." }] },
      { japanese: "便秘", romaji: "benpi", english: "Constipation", examples: [{ jp: "便秘に 悩む。", en: "Suffer from constipation.", romaji: "Benpi ni nayamu." }, { jp: "食物繊維を 摂る。", en: "Get dietary fiber.", romaji: "Shokumotsu sen'i wo toru." }] },
      { japanese: "嘔吐", romaji: "outo", english: "Vomiting", examples: [{ jp: "吐き気が する。", en: "Feel nauseous.", romaji: "Hakike ga suru." }, { jp: "激しい 嘔吐。", en: "Severe vomiting.", romaji: "Hashii outo." }] },
      { japanese: "外科", romaji: "geka", english: "Surgery (Dept)", examples: [{ jp: "外科に 行く。", en: "Go to surgery department.", romaji: "Geka ni iku." }, { jp: "外科医。", en: "Surgeon.", romaji: "Gekai." }] },
      { japanese: "内科", romaji: "naika", english: "Internal medicine", examples: [{ jp: "内科の 診察。", en: "Internal med exam.", romaji: "Naika no shinsatsu." }, { jp: "内科 医院。", en: "Internal medicine clinic.", romaji: "Naika iin." }] },
      { japanese: "処方箋", romaji: "shohousen", english: "Prescription", examples: [{ jp: "処方箋を もらう。", en: "Get a prescription.", romaji: "Shohousen wo morau." }, { jp: "薬局で 薬を買う。", en: "Buy drugs at pharmacy.", romaji: "Yakkyoku de kusuri wo kau." }] },
      { japanese: "副作用", romaji: "fukusayou", english: "Side effect", examples: [{ jp: "副作用が 怖い。", en: "Side effects are scary.", romaji: "Fukusayou ga kowai." }, { jp: "薬の 副作用。", en: "Side effect of medicine.", romaji: "Kusuri no fukusayou." }] },
      { japanese: "入院", romaji: "nyuuin", english: "Hospitalization", examples: [{ jp: "検査のため 入院する。", en: "Hospitalized for tests.", romaji: "Kensa no tame nyuuin suru." }, { jp: "入院 生活。", en: "Hospital life.", romaji: "Nyuuin seikatsu." }] },
      { japanese: "退院", romaji: "taiin", english: "Discharge from hospital", examples: [{ jp: "今日 退院する。", en: "Be discharged today.", romaji: "Kyou taiin suru." }, { jp: "全快 祝い。", en: "Party to celebrate recovery.", romaji: "Zenkai iwai." }] },
      { japanese: "看護", romaji: "kango", english: "Nursing", examples: [{ jp: "母を 看護する。", en: "Nurse my mother.", romaji: "Haha wo kango suru." }, { jp: "看護師。", en: "Nurse.", romaji: "Kangoshi." }] },
      { japanese: "お見舞い", romaji: "omimai", english: "Visiting a sick person", examples: [{ jp: "友達の お見舞いに行く。", en: "Go visit sick friend.", romaji: "Tomodachi no omimai ni iku." }, { jp: "お見舞いの 品。", en: "Get-well gift.", romaji: "Omimai no shina." }] },
      { japanese: "気絶", romaji: "kizetsu", english: "Faint/Unconsciousness", examples: [{ jp: "驚きで 気絶した。", en: "Fainted from surprise.", romaji: "Odoroki de kizetsushita." }, { jp: "気絶寸前だ。", en: "On the verge of fainting.", romaji: "Kizetsu sunzen da." }] },
      { japanese: "救急車", romaji: "kyuukyuusha", english: "Ambulance", examples: [{ jp: "救急車を 呼ぶ。", en: "Call an ambulance.", romaji: "Kyuukyuusha wo yobu." }, { jp: "救急 搬送。", en: "Emergency hospital transport.", romaji: "Kyuukyuu hansou." }] },
      { japanese: "手術", romaji: "shujutsu", english: "Operation/Surgery", examples: [{ jp: "手術を する。", en: "Have surgery.", romaji: "Shujutsu wo suru." }, { jp: "手術 成功。", en: "Surgery successful.", romaji: "Shujutsu seikou." }] },
      { japanese: "麻酔", romaji: "masui", english: "Anesthesia", examples: [{ jp: "麻酔が かかる。", en: "Anesthesia takes effect.", romaji: "Masui ga kakaru." }, { jp: "麻酔を かける。", en: "Administer anesthesia.", romaji: "Masui wo kakeru." }] },
      { japanese: "傷口", romaji: "kizuguchi", english: "Wound", examples: [{ jp: "傷口が 痛む。", en: "The wound hurts.", romaji: "Kizuguchi ga itamu." }, { jp: "傷口を 洗う。", en: "Wash the wound.", romaji: "Kizuguchi wo arau." }] },
      { japanese: "消毒", romaji: "shoudoku", english: "Disinfection/Sterilization", examples: [{ jp: "傷を 消毒する。", en: "Disinfect a wound.", romaji: "Kizu wo shoudoku suru." }, { jp: "手の 消毒。", en: "Hand disinfection.", romaji: "Te no shoudoku." }] },
      { japanese: "安静", romaji: "ansei", english: "Quiet/Rest", examples: [{ jp: "絶対 安静。", en: "Absolute rest.", romaji: "Zettai ansei." }, { jp: "安静に している。", en: "Staying quiet/resting.", romaji: "Ansei ni shiteiru." }] },
      { japanese: "診察券", romaji: "shinsatsuken", english: "Patient registration card", examples: [{ jp: "診察券を 出す。", en: "Show the registration card.", romaji: "Shinsatsuken wo dasu." }, { jp: "診察券を 失くした。", en: "Lost the medical card.", romaji: "Shinsatsuken wo nakushita." }] }
    ]
  },
  {
    id: 57,
    level: "N3",
    title: "Travel & Culture",
    description: "Vocabulary for deep travel experiences and cultural aspects",
    words: [
      { japanese: "観光", romaji: "kankou", english: "Sightseeing", examples: [{ jp: "京都を 観光する。", en: "Sightsee in Kyoto.", romaji: "Kyouto wo kankou suru." }, { jp: "観光客。", en: "Tourist.", romaji: "Kankoukyaku." }] },
      { japanese: "遺産", romaji: "isan", english: "Heritage/Legacy", examples: [{ jp: "世界 遺産。", en: "World Heritage.", romaji: "Sekai isan." }, { jp: "文化 遺産。", en: "Cultural heritage.", romaji: "Bunka isan." }] },
      { japanese: "名所", romaji: "meisho", english: "Famous spot", examples: [{ jp: "観光 名所を巡る。", en: "Visit famous tourist spots.", romaji: "Kankou meisho wo meguru." }, { jp: "桜の 名所。", en: "Spot famous for sakura.", romaji: "Sakura no meisho." }] },
      { japanese: "伝統", romaji: "dentou", english: "Tradition", examples: [{ jp: "伝統を 守る。", en: "Protect tradition.", romaji: "Dentou wo mamoru." }, { jp: "日本の 伝統文化。", en: "Japanese traditional culture.", romaji: "Nihon no dentou-bunka." }] },
      { japanese: "文化", romaji: "bunka", english: "Culture", examples: [{ jp: "異 文化に触れる。", en: "Touch/experience different cultures.", romaji: "I-bunka ni fureru." }, { jp: "文化の 違い。", en: "Cultural difference.", romaji: "Bunka no chigai." }] },
      { japanese: "歴史", romaji: "rekishi", english: "History", examples: [{ jp: "歴史を 勉強する。", en: "Study history.", romaji: "Rekishi wo benkyou suru." }, { jp: "歴史的な 建物。", en: "Historical building.", romaji: "Rekishiteki na tatemono." }] },
      { japanese: "交流", romaji: "kouryuu", english: "Interaction/Exchange", examples: [{ jp: "国際 交流。", en: "International exchange.", romaji: "Kokusai kouryuu." }, { jp: "学生同士の 交流。", en: "Interaction between students.", romaji: "Gakusei doushi no kouryuu." }] },
      { japanese: "案内", romaji: "annai", english: "Guide", examples: [{ jp: "町を 案内する。", en: "Guide someone around the town.", romaji: "Machi wo annaisuru." }, { jp: "案内所。", en: "Information office.", romaji: "Annaijo." }] },
      { japanese: "滞在", romaji: "taizai", english: "Stay/Sojourn", examples: [{ jp: "ホテルに 滞在する。", en: "Stay at a hotel.", romaji: "Hoteru ni taizai suru." }, { jp: "短期 滞在。", en: "Short stay.", romaji: "Tanki taizai." }] },
      { japanese: "宿泊", romaji: "shukuhaku", english: "Lodging", examples: [{ jp: "宿泊 施設を予約する。", en: "Book lodging facilities.", romaji: "Shukuhaku shisetsu wo yoyaku suru." }, { jp: "一晩 宿泊する。", en: "Stay for one night.", romaji: "Hitoban shukuhaku suru." }] },
      { japanese: "予備", romaji: "yobi", english: "Spare/Preliminary", examples: [{ jp: "予備の お金をもつ。", en: "Have spare money.", romaji: "Yobi no okane wo motsu." }, { jp: "予備 知識。", en: "Preliminary knowledge.", romaji: "Yobi chishiki." }] },
      { japanese: "準備", romaji: "junbi", english: "Preparation", examples: [{ jp: "旅行の 準備。", en: "Trip preparation.", romaji: "Ryokou no junbi." }, { jp: "準備が 整う。", en: "Preparation is complete.", romaji: "Junbi ga totonou." }] },
      { japanese: "手配", romaji: "tehai", english: "Arrangement", examples: [{ jp: "チケットを 手配する。", en: "Arrange/order tickets.", romaji: "Tiketto wo tehai suru." }, { jp: "ホテルの 手配。", en: "Arranging hotel.", romaji: "Hoteru no tehai." }] },
      { japanese: "予約", romaji: "yoyaku", english: "Reservation", examples: [{ jp: "ディナーを 予約する。", en: "Book dinner.", romaji: "Dinaa wo yoyaku suru." }, { jp: "予約が いっぱいだ。", en: "Fully booked.", romaji: "Yoyaku ga ippaida." }] },
      { japanese: "確認", romaji: "kakunin", english: "Confirmation", examples: [{ jp: "予約を 確認する。", en: "Confirm the booking.", romaji: "Yoyaku wo kakunin suru." }, { jp: "内容の 確認。", en: "Checking content.", romaji: "Naiyou no kakunin." }] },
      { japanese: "招待", romaji: "shoutai", english: "Invitation", examples: [{ jp: "パーティーに 招待する。", en: "Invite to a party.", romaji: "Paatii ni shoutai suru." }, { jp: "招待状を 送る。", en: "Send an invitation.", romaji: "Shoutaijou wo okuru." }] },
      { japanese: "土産", romaji: "miyage", english: "Souvenir", examples: [{ jp: "実家に お土産を買う。", en: "Buy souvenirs for parents' home.", romaji: "Jikka ni omiyage wo kau." }, { jp: "名産 品。", en: "Local specialty.", romaji: "Meisanhin." }] },
      { japanese: "特産", romaji: "tokusan", english: "Specialty", examples: [{ jp: "土地の 特産物。", en: "Local specialty products.", romaji: "Tochi no tokusanbutsu." }, { jp: "有名な 特産品。", en: "Famous specialty.", romaji: "Yuumeina tokusanhin." }] },
      { japanese: "芸術", romaji: "geijutsu", english: "Art", examples: [{ jp: "芸術を 鑑賞する。", en: "Appreciate art.", romaji: "Geijutsu wo kanshou suru." }, { jp: "芸術家。", en: "Artist.", romaji: "Geijutsuka." }] },
      { japanese: "鑑賞", romaji: "kanshou", english: "Appreciation (Art/Music)", examples: [{ jp: "絵画を 鑑賞する。", en: "Appreciate paintings.", romaji: "Kaiga wo kanshou suru." }, { jp: "映画 鑑賞。", en: "Movie appreciation.", romaji: "Eiga kanshou." }] },
      { japanese: "建築", romaji: "kenchiku", english: "Architecture", examples: [{ jp: "有名な 建築家。", en: "Famous architect.", romaji: "Yuumeina kenchikuka." }, { jp: "近代 建築。", en: "Modern architecture.", romaji: "Kindai kenchiku." }] },
      { japanese: "宗教", romaji: "shuukyou", english: "Religion", examples: [{ jp: "世界の 宗教。", en: "World religions.", romaji: "Sekai no shuukyou." }, { jp: "宗教 観。", en: "Religious views.", romaji: "Shuukyou-kan." }] },
      { japanese: "信仰", romaji: "shinkou", english: "Faith/Belief", examples: [{ jp: "信仰心が 厚い。", en: "Deeply religious.", romaji: "Shinkoushin ga atsui." }, { jp: "自由な 信仰。", en: "Freedom of faith.", romaji: "Jiyuuna shinkou." }] },
      { japanese: "儀式", romaji: "gishiki", english: "Ceremony/Ritual", examples: [{ jp: "伝統的な 儀式。", en: "Traditional ceremony.", romaji: "Dentouteki na gishiki." }, { jp: "成人の 儀式。", en: "Coming-of-age ritual.", romaji: "Seijin no gishiki." }] },
      { japanese: "慣習", romaji: "kanshuu", english: "Custom", examples: [{ jp: "土地の 慣習。", en: "Local custom.", romaji: "Tochi no kanshuu." }, { jp: "古い 慣習を破る。", en: "Break old customs.", romaji: "Furui kanshuu wo yaburu." }] },
      { japanese: "習慣", romaji: "shuukan", english: "Habit", examples: [{ jp: "毎日の 習慣。", en: "Daily habit.", romaji: "Mainichi no shuukan." }, { jp: "日本の 習慣。", en: "Japanese custom.", romaji: "Nihon no shuukan." }] },
      { japanese: "礼儀", romaji: "reigi", english: "Etiquette/Courtesy", examples: [{ jp: "礼儀 正しい。", en: "Polite/Proper manners.", romaji: "Reigi tadashii." }, { jp: "礼儀を 重んじる。", en: "Value etiquette.", romaji: "Reigi wo omonjiru." }] },
      { japanese: "作法", romaji: "sahou", english: "Manners/Proper way", examples: [{ jp: "茶道の 作法。", en: "Tea ceremony etiquette.", romaji: "Sadou no sahou." }, { jp: "食事の 作法。", en: "Dining manners.", romaji: "Shokuji no sahou." }] },
      { japanese: "敬語", romaji: "keigo", english: "Honorific language", examples: [{ jp: "敬語を 使う。", en: "Use honorifics.", romaji: "Keigo wo tsukau." }, { jp: "難しい 敬語。", en: "Difficult keigo.", romaji: "Muzukashii keigo." }] },
      { japanese: "方言", romaji: "hougen", english: "Dialect", examples: [{ jp: "関西の方言。", en: "Kansai dialect.", romaji: "Kansai no hougen." }, { jp: "方言で 話す。", en: "Speak in dialect.", romaji: "Hougen de hanasu." }] }
    ]
  },
  {
    id: 58,
    level: "N3",
    title: "Household & Living",
    description: "Advanced vocabulary for home activities and housing",
    words: [
      { japanese: "家具", romaji: "kagu", english: "Furniture", examples: [{ jp: "新しい 家具を買う。", en: "Buy new furniture.", romaji: "Atarashii kagu wo kau." }, { jp: "高級 家具。", en: "High-end furniture.", romaji: "Koukyuu kagu." }] },
      { japanese: "家電", romaji: "kaden", english: "Appliances", examples: [{ jp: "最新の 家電製品。", en: "Latest consumer electronics.", romaji: "Saishin no kaden seihin." }, { jp: "省エネ 家電。", en: "Energy-saving appliances.", romaji: "Shouene kaden." }] },
      { japanese: "照明", romaji: "shoumei", english: "Lighting", examples: [{ jp: "明るい 照明。", en: "Bright lighting.", romaji: "Akarui shoumei." }, { jp: "間接 照明。", en: "Indirect lighting.", romaji: "Kansetsu shoumei." }] },
      { japanese: "台所", romaji: "daidokoro", english: "Kitchen", examples: [{ jp: "台所で 料理する。", en: "Cook in the kitchen.", romaji: "Daidokoro de ryouri suru." }, { jp: "台所 用品。", en: "Kitchen utensils.", romaji: "Daidokoro youhin." }] },
      { japanese: "蛇口", romaji: "jaguchi", english: "Faucet/Tap", examples: [{ jp: "蛇口を ひねる。", en: "Turn the tap.", romaji: "Jaguchi wo hineru." }, { jp: "水が 漏れる。", en: "Water leaks.", romaji: "Mizu ga moreru." }] },
      { japanese: "洗剤", romaji: "senzai", english: "Detergent", examples: [{ jp: "食器用 洗剤。", en: "Dish soap.", romaji: "Shokki-you senzai." }, { jp: "洗濯 洗剤。", en: "Laundry detergent.", romaji: "Sentaku senzai." }] },
      { japanese: "洗濯物", romaji: "sentakumono", english: "Laundry", examples: [{ jp: "洗濯物を 干す。", en: "Hang out the laundry.", romaji: "Sentakumono wo hosu." }, { jp: "洗濯物が 乾く。", en: "Laundry dries.", romaji: "Sentakumono ga kawaku." }] },
      { japanese: "掃除機", romaji: "soujiki", english: "Vacuum cleaner", examples: [{ jp: "掃除機を かける。", en: "To vacuum.", romaji: "Soujiki wo kakeru." }, { jp: "コードレス 掃除機。", en: "Cordless vacuum.", romaji: "Koodoresu soujiki." }] },
      { japanese: "整理", romaji: "seiri", english: "Organization/Tidying", examples: [{ jp: "部屋を 整理する。", en: "Organize the room.", romaji: "Heya wo seiri suru." }, { jp: "情報の 整理。", en: "Organizing information.", romaji: "Jouhou no seiri." }] },
      { japanese: "整頓", romaji: "seiton", english: "Sorting/Order", examples: [{ jp: "整理 整頓。", en: "Organizing and order.", romaji: "Seiri seiton." }, { jp: "おもちゃを 整頓する。", en: "Put toys in order.", romaji: "Omocha wo seiton suru." }] },
      { japanese: "物置", romaji: "monooki", english: "Storage room/Shed", examples: [{ jp: "物置に しまう。", en: "Put away in storage.", romaji: "Monooki ni shimau." }, { jp: "庭の 物置。", en: "Shed in the garden.", romaji: "Niwa no monooki." }] },
      { japanese: "押入れ", romaji: "oshiire", english: "Japanese closet", examples: [{ jp: "布団を 押入れに入れる。", en: "Put futon in closet.", romaji: "Futon wo oshiire ni ireru." }, { jp: "押入れを 整理する。", en: "Organize the closet.", romaji: "Oshiire wo seiri suru." }] },
      { japanese: "布団", romaji: "futon", english: "Futon", examples: [{ jp: "布団を 敷く。", en: "Spread the futon.", romaji: "Futon wo shiku." }, { jp: "羽毛 布団。", en: "Down futon.", romaji: "Umou futon." }] },
      { japanese: "毛布", romaji: "moufu", english: "Blanket", examples: [{ jp: "温かい 毛布。", en: "Warm blanket.", romaji: "Atatakai moufu." }, { jp: "毛布を かける。", en: "Put on a blanket.", romaji: "Moufu wo kakeru." }] },
      { japanese: "枕", romaji: "makura", english: "Pillow", examples: [{ jp: "枕を 高くする。", en: "Make the pillow high.", romaji: "Makura wo takaku suru." }, { jp: "マイ 枕。", en: "My personal pillow.", romaji: "Mai makura." }] },
      { japanese: "敷金", romaji: "shikikin", english: "Security deposit", examples: [{ jp: "敷金を 払う。", en: "Pay security deposit.", romaji: "Shikikin wo harau." }, { jp: "敷金 返還。", en: "Refund of deposit.", romaji: "Shikikin henkan." }] },
      { japanese: "礼金", romaji: "reikin", english: "Key money (Gratuity)", examples: [{ jp: "礼金 ゼロのアパート。", en: "Apt with no key money.", romaji: "Reikin zero no apaato." }, { jp: "礼金を 納める。", en: "Pay key money.", romaji: "Reikin wo osameru." }] },
      { japanese: "家賃", romaji: "yachin", english: "Rent", examples: [{ jp: "家賃を 滞納する。", en: "Fail to pay rent.", romaji: "Yachin wo tainou suru." }, { jp: "安い 家賃。", en: "Cheap rent.", romaji: "Yasui yachin." }] },
      { japanese: "管理費", romaji: "kanrihi", english: "Management fee", examples: [{ jp: "管理費が 含まれる。", en: "Management fee is included.", romaji: "Kanrihi ga fukumareru." }, { jp: "共益 費。", en: "Common service fee.", romaji: "Kyouekihi." }] },
      { japanese: "間取り", romaji: "madori", english: "Layout (of a house)", examples: [{ jp: "理想の 間取り。", en: "Ideal layout.", romaji: "Risou no madori." }, { jp: "３ＬＤＫの マンション。", en: "3LDK apartment.", romaji: "San-eru-dee-kee no manshon." }] },
      { japanese: "築年数", romaji: "chikunensuu", english: "Age of building", examples: [{ jp: "築年数が 浅い。", en: "Building is new.", romaji: "Chikunensuu ga asai." }, { jp: "築 二十年の家。", en: "20-year-old house.", romaji: "Chiku nijunnen no ie." }] },
      { japanese: "防犯", romaji: "bouhan", english: "Crime prevention", examples: [{ jp: "防犯 カメラ。", en: "Security camera.", romaji: "Bouhan kamera." }, { jp: "防犯に 努める。", en: "Strive for security.", romaji: "Bouhan ni tsutomeru." }] },
      { japanese: "断熱", romaji: "dannetsu", english: "Insulation", examples: [{ jp: "断熱材を 入れる。", en: "Install insulation.", romaji: "Dannetsuzai wo ireru." }, { jp: "断熱 効果。", en: "Insulation effect.", romaji: "Dannetsu kouka." }] },
      { japanese: "結露", romaji: "ketsuro", english: "Condensation", examples: [{ jp: "窓の 結露を拭く。", en: "Wipe window condensation.", romaji: "Mado no ketsuro wo fuku." }, { jp: "結露 対策。", en: "Condensation measures.", romaji: "Ketsuro taisaku." }] },
      { japanese: "換気", romaji: "kanki", english: "Ventilation", examples: [{ jp: "部屋を 換気する。", en: "Ventilate the room.", romaji: "Heya wo kanki suru." }, { jp: "換気扇を 回す。", en: "Turn on the ventilation fan.", romaji: "Kankisen wo mawasu." }] },
      { japanese: "日当たり", romaji: "hiatari", english: "Exposure to sun", examples: [{ jp: "日当たりが 良い。", en: "Good sunlight.", romaji: "Hiatari ga yoi." }, { jp: "南向きの 部屋。", en: "South-facing room.", romaji: "Minami muki no heya." }] },
      { japanese: "騒音", romaji: "souon", english: "Noise", examples: [{ jp: "騒音に 悩まされる。", en: "Be bothered by noise.", romaji: "Souon ni nayamasareru." }, { jp: "騒音 対策。", en: "Noise counter-measures.", romaji: "Souon taisaku." }] },
      { japanese: "近所付き合い", romaji: "kinjotsukiai", english: "Neighborly relations", examples: [{ jp: "近所付き合いが 大事だ。", en: "Neighborly relations are important.", romaji: "Kinjo tsukiai ga daiji da." }, { jp: "挨拶を 欠かさない。", en: "Don't miss a greeting.", romaji: "Aisatsu wo kakasanai." }] },
      { japanese: "ゴミ出し", romaji: "gomidashi", english: "Taking out trash", examples: [{ jp: "ゴミ出しの 日。", en: "Trash collection day.", romaji: "Gomidashi no hi." }, { jp: "ルールを 守る。", en: "Obey the rules.", romaji: "Ruuru wo mamoru." }] },
      { japanese: "快適", romaji: "kaiteki", english: "Comfortable", examples: [{ jp: "快適な 生活。", en: "Comfortable life.", romaji: "Kaiteki na seikatsu." }, { jp: "住み心地が 良い。", en: "Comfortable to live in.", romaji: "Sumigokochi ga yoi." }] }
    ]
  },
  {
    id: 59,
    level: "N3",
    title: "Hobbies & Leisure",
    description: "Vocabulary for high-level interests, sports, and pastimes",
    words: [
      { japanese: "趣味", romaji: "shumi", english: "Hobby", examples: [{ jp: "多 趣味だ。", en: "Have many hobbies.", romaji: "Ta shumi da." }, { jp: "趣味に 没頭する。", en: "Be immersed in a hobby.", romaji: "Shumi ni bottou suru." }] },
      { japanese: "興味", romaji: "kyoumi", english: "Interest", examples: [{ jp: "興味を 持つ。", en: "Develop interest.", romaji: "Kyoumi wo motsu." }, { jp: "無 興味だ。", en: "Have no interest.", romaji: "Mu kyoumi da." }] },
      { japanese: "娯楽", romaji: "goraku", english: "Entertainment/Pastime", examples: [{ jp: "庶民の 娯楽。", en: "Poplular pastime.", romaji: "Shomin no goraku." }, { jp: "娯楽 施設。", en: "Entertainment facility.", romaji: "Goraku shisetsu." }] },
      { japanese: "鑑賞", romaji: "kanshou", english: "Appreciation", examples: [{ jp: "音楽 鑑賞。", en: "Music appreciation.", romaji: "Ongaku kanshou." }, { jp: "芸術を 鑑賞する。", en: "Appreciate art.", romaji: "Geijutsu wo kanshou suru." }] },
      { japanese: "読書", romaji: "dokusho", english: "Reading", examples: [{ jp: "秋は 読書の季節だ。", en: "Fall is the season for reading.", romaji: "Aki wa dokusho no kisetsu da." }, { jp: "読書家。", en: "Avid reader.", romaji: "Dokushoka." }] },
      { japanese: "演奏", romaji: "ensou", english: "Musical performance", examples: [{ jp: "ピアノを 演奏する。", en: "Perform piano.", romaji: "Piano wo ensou suru." }, { jp: "生 演奏。", en: "Live performance.", romaji: "Nama ensou." }] },
      { japanese: "合唱", romaji: "gasshou", english: "Chorus/Choir", examples: [{ jp: "合唱 コンクール。", en: "Chorus contest.", romaji: "Gasshou konkuuru." }, { jp: "みんなで 合唱する。", en: "Sing in a chorus together.", romaji: "Minna de gasshou suru." }] },
      { japanese: "描く", romaji: "kaku", english: "To draw/paint/describe", examples: [{ jp: "絵を 描く。", en: "Draw a picture.", romaji: "E wo kaku." }, { jp: "夢を 描く。", en: "Picture a dream.", romaji: "Yume wo kaku." }] },
      { japanese: "陶芸", romaji: "tougei", english: "Ceramics/Pottery", examples: [{ jp: "陶芸に 挑戦する。", en: "Try pottery.", romaji: "Tougei ni chousen suru." }, { jp: "陶芸 教室。", en: "Pottery class.", romaji: "Tougei kyoushitsu." }] },
      { japanese: "園芸", romaji: "engei", english: "Gardening", examples: [{ jp: "園芸が 趣味だ。", en: "Gardening is my hobby.", romaji: "Engei ga shumi da." }, { jp: "家庭 菜園。", en: "Home garden.", romaji: "Katei saien." }] },
      { japanese: "釣り", romaji: "tsuri", english: "Fishing", examples: [{ jp: "釣りに 行く。", en: "Go fishing.", romaji: "Tsuri ni iku." }, { jp: "釣り 竿。", en: "Fishing rod.", romaji: "Tsurizao." }] },
      { japanese: "登山", romaji: "tozan", english: "Mountain climbing", examples: [{ jp: "登山を 楽しむ。", en: "Enjoy mountain climbing.", romaji: "Tozan wo tanoshimu." }, { jp: "富士 登山。", en: "Climbing Mt. Fuji.", romaji: "Fuji tozan." }] },
      { japanese: "運動", romaji: "undou", english: "Exercise/Movement", examples: [{ jp: "毎日の 運動。", en: "Daily exercise.", romaji: "Mainichi no undou." }, { jp: "準備 運動。", en: "Warm-up exercise.", romaji: "Junbi undou." }] },
      { japanese: "競技", romaji: "kyougi", english: "Competition/Game", examples: [{ jp: "競技が 始まる。", en: "The competition starts.", romaji: "Kyougi ga hajimaru." }, { jp: "競技場。", en: "Stadium/Arena.", romaji: "Kyougijou." }] },
      { japanese: "応援", romaji: "ouen", english: "Support/Cheering", examples: [{ jp: "チームを 応援する。", en: "Support the team.", romaji: "Chiimu wo ouen suru." }, { jp: "応援団。", en: "Cheering squad.", romaji: "Ouendan." }] },
      { japanese: "観戦", romaji: "kansen", english: "Watching a game", examples: [{ jp: "野球を 観戦する。", en: "Watch a baseball game.", romaji: "Yakyuu wo kansen suru." }, { jp: "テレビ 観戦。", en: "Watching on TV.", romaji: "Terebi kansen." }] },
      { japanese: "活躍", romaji: "katsuyaku", english: "Active role/Success", examples: [{ jp: "世界で 活躍する。", en: "Succeed worldwide.", romaji: "Sekai de katsuyaku suru." }, { jp: "目覚ましい 活躍。", en: "Remarkable activity/success.", romaji: "Mezamashii katsuyaku." }] },
      { japanese: "特技", romaji: "tokugi", english: "Special skill", examples: [{ jp: "特技を 披露する。", en: "Show off a special skill.", romaji: "Tokugi wo hirou suru." }, { jp: "私の 特技は歌です。", en: "My skill is singing.", romaji: "Watashi no tokugi wa uta desu." }] },
      { japanese: "上達", romaji: "joutatsu", english: "Improvement", examples: [{ jp: "日本語が 上達する。", en: "Japanese improves.", romaji: "Nihongo ga joutatsu suru." }, { jp: "上達が 早い。", en: "Quick to improve.", romaji: "Joutatsu ga hayai." }] },
      { japanese: "披露", romaji: "hirou", english: "Announcement/Showing", examples: [{ jp: "技を 披露する。", en: "Show a technique.", romaji: "Waza wo hirou suru." }, { jp: "結婚 披露宴。", en: "Wedding reception.", romaji: "Kekkon hirouen." }] },
      { japanese: "本格的", romaji: "honkakuteki", english: "Genuine/Full-scale", examples: [{ jp: "本格的な 練習。", en: "Full-scale practice.", romaji: "Honkakuteki na renshuu." }, { jp: "プロ 並みだ。", en: "It's professional level.", romaji: "Pro nami da." }] },
      { japanese: "没頭", romaji: "bottou", english: "Immerse/Be absorbed", examples: [{ jp: "研究に 没頭する。", en: "Be absorbed in research.", romaji: "Kenkyuu ni bottou suru." }, { jp: "時間を 忘れる。", en: "Forget time.", romaji: "Jikan wo wasureru." }] },
      { japanese: "挑戦", romaji: "chousen", english: "Challenge", examples: [{ jp: "新しいことに挑戦する。", en: "Challenge new things.", romaji: "Atarashii koto ni chousen suru." }, { jp: "挑戦者。", en: "Challenger.", romaji: "Chousensha." }] },
      { japanese: "勝敗", romaji: "shouhai", english: "Victory or defeat", examples: [{ jp: "勝敗が 決まる。", en: "Victory/defeat is decided.", romaji: "Shouhai ga kimaru." }, { jp: "勝敗に こだわらない。", en: "Don't care about winning or losing.", romaji: "Shouhai ni kodawaranai." }] },
      { japanese: "記録", romaji: "kiroku", english: "Record", examples: [{ jp: "世界 記録を更新する。", en: "Break a world record.", romaji: "Sekai kiroku wo koushin suru." }, { jp: "新 記録。", en: "New record.", romaji: "Shin kiroku." }] },
      { japanese: "達成", romaji: "tassei", english: "Achievement", examples: [{ jp: "目標を 達成する。", en: "Achieve a goal.", romaji: "Mokuteyou wo tassei suru." }, { jp: "達成感が ある。", en: "Have a sense of achievement.", romaji: "Tasseikan ga aru." }] },
      { japanese: "余暇", romaji: "yoka", english: "Leisure time", examples: [{ jp: "余暇を 活用する。", en: "Utilize leisure time.", romaji: "Yoka wo katsuyou suru." }, { jp: "有意義な 余暇。", en: "Meaningful leisure.", romaji: "Yuui-gijna yoka." }] },
      { japanese: "交流", romaji: "kouryuu", english: "Interaction/Meetup", examples: [{ jp: "趣味を 通じた交流。", en: "Interaction through hobbies.", romaji: "Shumi wo tsuujita kouryuu." }, { jp: "オフ 会。", en: "Offline meeting/meetup.", romaji: "Ofukau." }] },
      { japanese: "発散", romaji: "hassan", english: "Release/Emission", examples: [{ jp: "ストレスを 発散する。", en: "Release stress.", romaji: "Sutoresu wo hassan suru." }, { jp: "熱を 発散する。", en: "Emit heat.", romaji: "Netsu wo hassan suru." }] },
      { japanese: "充実", romaji: "juujitsu", english: "Fulfillment", examples: [{ jp: "充実した 毎日。", en: "Fulfilling daily life.", romaji: "Juujitsu shita mainichi." }, { jp: "内容の 充実。", en: "Substantial content.", romaji: "Naiyou no juujitsu." }] }
    ]
  },
  {
    id: 60,
    level: "N3",
    title: "City & Infrastructure",
    description: "Vocabulary for urban planning, facilities, and public life",
    words: [
      { japanese: "都市", romaji: "toshi", english: "City", examples: [{ jp: "大 都市圏。", en: "Metropolitan area.", romaji: "Dai toshiken." }, { jp: "都市 開発。", en: "Urban development.", romaji: "Toshi kaihatsu." }] },
      { japanese: "人口", romaji: "jinkou", english: "Population", examples: [{ jp: "人口が 密集する。", en: "Population is dense.", romaji: "Jinkou ga misshuu suru." }, { jp: "人口 減少。", en: "Population decline.", romaji: "Jinkou genshou." }] },
      { japanese: "密集", romaji: "misshuu", english: "Denseness/Crowd", examples: [{ jp: "住宅が 密集している。", en: "Houses are crowded together.", romaji: "Juutaku ga misshuu shiteiru." }, { jp: "三密を 避ける。", en: "Avoid the 'Three Cs' (dense crowds).", romaji: "Sanmitsu wo sakeru." }] },
      { japanese: "過疎", romaji: "kaso", english: "Depopulation", examples: [{ jp: "地方の 過疎化。", en: "Depopulation of rural areas.", romaji: "Chihou no kasoka." }, { jp: "過疎 地域。", en: "Depopulated area.", romaji: "Kaso chiiki." }] },
      { japanese: "施設", romaji: "shisetsu", english: "Facility", examples: [{ jp: "公共 施設。", en: "Public facility.", romaji: "Koukyou shisetsu." }, { jp: "医療 施設。", en: "Medical facility.", romaji: "Iryou shisetsu." }] },
      { japanese: "整備", romaji: "seibi", english: "Maintenance/Provision", examples: [{ jp: "インフラを 整備する。", en: "Prepare/maintain infrastructure.", romaji: "Infura wo seibi suru." }, { jp: "整備された 公園。", en: "Well-maintained park.", romaji: "Seibi sareta kouen." }] },
      { japanese: "インフラ", romaji: "infura", english: "Infrastructure", examples: [{ jp: "生活 インフラ。", en: "Living infrastructure.", romaji: "Seikatsu infura." }, { jp: "インフラ 整備。", en: "Building/maintaining infra.", romaji: "Infura seibi." }] },
      { japanese: "交通", romaji: "koutsuu", english: "Traffic/Transport", examples: [{ jp: "交通の 便が良い。", en: "Transportation is convenient.", romaji: "Koutsuu no bin ga yoi." }, { jp: "交通 網。", en: "Transport network.", romaji: "Koutsuumou." }] },
      { japanese: "渋滞", romaji: "juutai", english: "Congestion", examples: [{ jp: "通勤 ラッシュの渋滞。", en: "Traffic jam during commute rush.", romaji: "Tsuukin rasshu no juutai." }, { jp: "道が 渋滞する。", en: "Road gets jammed.", romaji: "Michi ga juutai suru." }] },
      { japanese: "騒音", romaji: "souon", english: "Noise", examples: [{ jp: "騒音 被害。", en: "Damage from noise.", romaji: "Souon higai." }, { jp: "騒音 公害。", en: "Noise pollution.", romaji: "Souon kougai." }] },
      { japanese: "住宅", romaji: "juutaku", english: "Housing", examples: [{ jp: "新築 住宅。", en: "Newly built housing.", romaji: "Shinchiku juutaku." }, { jp: "住宅 街。", en: "Residential area.", romaji: "Juutakugai." }] },
      { japanese: "団地", romaji: "danchi", english: "Apartment complex", examples: [{ jp: "大規模な 団地。", en: "Large-scale complex.", romaji: "Daikibo na danchi." }, { jp: "都営 団地。", en: "Metropolitan public housing.", romaji: "Toei danchi." }] },
      { japanese: "境界", romaji: "kyoukai", english: "Boundary", examples: [{ jp: "土地の 境界。", en: "Land boundary.", romaji: "Tochi no kyoukai." }, { jp: "境界線を 引く。", en: "Draw a boundary line.", romaji: "Kyoukaisen wo hiku." }] },
      { japanese: "役所", romaji: "yakusho", english: "Public office", examples: [{ jp: "役所に 届け出る。", en: "Report to public office.", romaji: "Yakusho ni todokederu." }, { jp: "市役所。", en: "City hall.", romaji: "Shiyakusho." }] },
      { japanese: "交番", romaji: "kouban", english: "Police box", examples: [{ jp: "道を聞きに交番へ行く。", en: "Go to police box to ask way.", romaji: "Michi wo kiki ni kouban e iku." }, { jp: "駅前の 交番。", en: "Police box in front of station.", romaji: "Ekimae no kouban." }] },
      { japanese: "郵便局", romaji: "yuubinkyoku", english: "Post office", examples: [{ jp: "郵便局で 荷物を出す。", en: "Send package at post office.", romaji: "Yuubinkyoku de nimotsu wo dasu." }, { jp: "郵便 サービス。", en: "Postal service.", romaji: "Yuubin saabisu." }] },
      { japanese: "銀行", romaji: "ginkou", english: "Bank", examples: [{ jp: "銀行 口座を作る。", en: "Make a bank account.", romaji: "Ginkou kouza wo tsukuru." }, { jp: "銀行 振込。", en: "Bank transfer.", romaji: "Ginkou furikomi." }] },
      { japanese: "商店街", romaji: "shoutengai", english: "Shopping arcade", examples: [{ jp: "活気のある商店街。", en: "Lively shopping street.", romaji: "Kakki no aru shoutengai." }, { jp: "地元の 商店街。", en: "Local shopping arcade.", romaji: "Jimoto no shoutengai." }] },
      { japanese: "再開発", romaji: "saikaihatsu", english: "Redevelopment", examples: [{ jp: "駅前の 再開発計画。", en: "Redev. plan for station area.", romaji: "Ekimae no saikaihatsu keikaku." }, { jp: "街の 再開発。", en: "Redevelopment of the town.", romaji: "Machi no saikaihatsu." }] },
      { japanese: "治安", romaji: "chian", english: "Public safety", examples: [{ jp: "治安が 良い。", en: "Safe (neighborhood).", romaji: "Chian ga yoi." }, { jp: "治安の 悪化。", en: "Worsening of safety.", romaji: "Chian no akka." }] },
      { japanese: "便利", romaji: "benri", english: "Convenient", examples: [{ jp: "駅に近くて便利だ。", en: "Convenient being near station.", romaji: "Eki ni chikakute benri da." }, { jp: "利便性。", en: "Convenience.", romaji: "Ribensei." }] },
      { japanese: "活性化", romaji: "kasseika", english: "Vitalization/Activation", examples: [{ jp: "地域の 活性化。", en: "Vitalization of the region.", romaji: "Chiiki no kasseika." }, { jp: "経済の 活性化。", en: "Economic activation.", romaji: "Keizai no kasseika." }] },
      { japanese: "地域", romaji: "chiiki", english: "Region/Area", examples: [{ jp: "地域 社会。", en: "Local society.", romaji: "Chiiki shakai." }, { jp: "特定の 地域。", en: "Specific region.", romaji: "Tokutei na chiiki." }] },
      { japanese: "振興", romaji: "shinkou", english: "Promotion (Indus., etc.)", examples: [{ jp: "観光 振興。", en: "Promotion of tourism.", romaji: "Kankou shinkou." }, { jp: "産業を 振興する。", en: "Promote an industry.", romaji: "Sangyou wo shinkou suru." }] },
      { japanese: "中心", romaji: "chuushin", english: "Center", examples: [{ jp: "街の 中心部。", en: "The town center.", romaji: "Machi no chuushinbu." }, { jp: "中心 人物。", en: "Central figure.", romaji: "Chuushin jinbutsu." }] },
      { japanese: "周辺", romaji: "shuuhen", english: "Surroundings", examples: [{ jp: "駅の 周辺。", en: "Station surroundings.", romaji: "Eki no shuuhen." }, { jp: "周辺 環境。", en: "Surrounding environment.", romaji: "Shuuhen kankyou." }] },
      { japanese: "広場", romaji: "hiroba", english: "Plaza/Square", examples: [{ jp: "憩いの 広場。", en: "A square for relaxation.", romaji: "Ikoi no hiroba." }, { jp: "駅前 広場。", en: "Station plaza.", romaji: "Ekimae hiroba." }] },
      { japanese: "緑地", romaji: "ryokuchi", english: "Green space", examples: [{ jp: "都市 縁地。", en: "Urban green space.", romaji: "Toshi ryokuchi." }, { jp: "緑地 帯。", en: "Green belt.", romaji: "Ryokuchitai." }] },
      { japanese: "標識", romaji: "hyoushiki", english: "Sign/Marker", examples: [{ jp: "交通 標識。", en: "Traffic sign.", romaji: "Koutsuu hyoushiki." }, { jp: "案内 標識。", en: "Guide sign.", romaji: "Annai hyoushiki." }] },
      { japanese: "防犯", romaji: "bouhan", english: "Crime prevention", examples: [{ jp: "防犯 灯。", en: "Security light.", romaji: "Bouhan tou." }, { jp: "地域の 防犯対策。", en: "Local crime prevention.", romaji: "Chiiki no bouhan taisaku." }] }
    ]
  }
];
