export const chunk13 = [
  {
    id: 61,
    level: "N3",
    title: "Business & Workplace",
    description: "Advanced vocabulary for office culture and professional interactions",
    words: [
      { japanese: "出張", romaji: "shutchou", english: "Business trip", examples: [{ jp: "来週 アメリカへ出張する。", en: "Go on a business trip to America next week.", romaji: "Raishuu amerika e shutchou suru." }, { jp: "出張 報告書。", en: "Business trip report.", romaji: "Shutchou houkokusho." }] },
      { japanese: "残業", romaji: "zangyou", english: "Overtime work", examples: [{ jp: "残業が 続く。", en: "Overtime continues.", romaji: "Zangyou ga tsuzuku." }, { jp: "残業 代。", en: "Overtime pay.", romaji: "Zangyou dai." }] },
      { japanese: "有給休暇", romaji: "yuukyuu kyuuka", english: "Paid leave", examples: [{ jp: "有給休暇を 取る。", en: "Take paid leave.", romaji: "Yuukyuu kyuuka wo toru." }, { jp: "有給の 消化。", en: "Using up paid leave.", romaji: "Yuukyuu no shouka." }] },
      { japanese: "昇進", romaji: "shoushin", english: "Promotion", examples: [{ jp: "課長に 昇進する。", en: "Promoted to section manager.", romaji: "Kachou ni shoushin suru." }, { jp: "昇進 祝い。", en: "Promotion celebration.", romaji: "Shoushin iwai." }] },
      { japanese: "転職", romaji: "tenshoku", english: "Change of job", examples: [{ jp: "キャリアアップのため転職する。", en: "Change jobs for career advancement.", romaji: "Kyaria-appu no tame tenshoku suru." }, { jp: "転職 サイト。", en: "Job search site.", romaji: "Tenshoku saito." }] },
      { japanese: "退職", romaji: "taishoku", english: "Retirement/Quitting", examples: [{ jp: "定年で 退職する。", en: "Retire at age limit.", romaji: "Teinen de taishoku suru." }, { jp: "退職金。", en: "Retirement allowance.", romaji: "Taishokukin." }] },
      { japanese: "面接", romaji: "mensetsu", english: "Interview", examples: [{ jp: "採用 面接。", en: "Employment interview.", romaji: "Saiyou mensetsu." }, { jp: "面接官。", en: "Interviewer.", romaji: "Mensetsukan." }] },
      { japanese: "採用", romaji: "saiyou", english: "Employment/Adoption", examples: [{ jp: "新卒を 採用する。", en: "Employ new graduates.", romaji: "Shinsotsu wo saiyou suru." }, { jp: "案を 採用する。", en: "Adopt a plan.", romaji: "An wo saiyou suru." }] },
      { japanese: "研修", romaji: "kenshuu", english: "Training", examples: [{ jp: "新入社員 研修。", en: "New employee training.", romaji: "Shinnyuushain kenshuu." }, { jp: "研修を 受ける。", en: "Undergo training.", romaji: "Kenshuu wo ukeru." }] },
      { japanese: "待遇", romaji: "taiguu", english: "Treatment/Compensation", examples: [{ jp: "待遇を 改善する。", en: "Improve working conditions.", romaji: "Taiguu wo kaizen suru." }, { jp: "好 待遇。", en: "Good treatment/pay.", romaji: "Kou taiguu." }] },
      { japanese: "給与", romaji: "kyuuyo", english: "Salary/Pay", examples: [{ jp: "給与 明細。", en: "Pay slip.", romaji: "Kyuuyo meisai." }, { jp: "月額 給与。", en: "Monthly salary.", romaji: "Getsugaku kyuuyo." }] },
      { japanese: "福利厚生", romaji: "fukuri kousei", english: "Welfare benefits", examples: [{ jp: "福利厚生が 充実している。", en: "Benefits are substantial.", romaji: "Fukuri kousei ga juujitsu shiteiru." }, { jp: "厚生 年金。", en: "Welfare pension.", romaji: "Kousei nenkin." }] },
      { japanese: "効率", romaji: "kouritsu", english: "Efficiency", examples: [{ jp: "業務の 効率化。", en: "Efficiency of business ops.", romaji: "Gyoumu no kouritsuka." }, { jp: "効率的に 働く。", en: "Work efficiently.", romaji: "Kouritsuteki ni hataraku." }] },
      { japanese: "業務", romaji: "gyoumu", english: "Business/Duties", examples: [{ jp: "通常 業務。", en: "Normal business duties.", romaji: "Tsuujou gyoumu." }, { jp: "業務 提携。", en: "Business alliance.", romaji: "Gyoumu teikei." }] },
      { japanese: "担当", romaji: "tantou", english: "Being in charge", examples: [{ jp: "受付を 担当する。", en: "Be in charge of reception.", romaji: "Uketsuke wo tantou suru." }, { jp: "担当者。", en: "Person in charge.", romaji: "Tantousha." }] },
      { japanese: "責任", romaji: "sekinin", english: "Responsibility", examples: [{ jp: "責任を 負う。", en: "Take responsibility.", romaji: "Sekinin wo ou." }, { jp: "責任 重大だ。", en: "Great responsibility.", romaji: "Sekinin juudai da." }] },
      { japanese: "交渉", romaji: "koushou", english: "Negotiation", examples: [{ jp: "条件を 交渉する。", en: "Negotiate terms.", romaji: "Jouken wo koushou suru." }, { jp: "交渉 決裂。", en: "Negotiations breakdown.", romaji: "Koushou ketsuretsu." }] },
      { japanese: "契約", romaji: "keiyaku", english: "Contract", examples: [{ jp: "契約を 結ぶ。", en: "Sign a contract.", romaji: "Keiyaku wo musubu." }, { jp: "契約書。", en: "Written contract.", romaji: "Keiyakusho." }] },
      { japanese: "会議", romaji: "kaigi", english: "Meeting", examples: [{ jp: "会議に 出席する。", en: "Attend a meeting.", romaji: "Kaigi ni shussekisuru." }, { jp: "会議の 司会。", en: "Chairperson of a meeting.", romaji: "Kaigi no shikai." }] },
      { japanese: "資料", romaji: "shiryou", english: "Materials/Data", examples: [{ jp: "会議用の 資料。", en: "Materials for meeting.", romaji: "Kaigiyou no shiryou." }, { jp: "資料を 配布する。", en: "Distribute materials.", romaji: "Shiryou wo haifu suru." }] },
      { japanese: "報告", romaji: "houkoku", english: "Report", examples: [{ jp: "結果を 報告する。", en: "Report the results.", romaji: "Kekka wo houkoku suru." }, { jp: "定期 報告。", en: "Regular report.", romaji: "Teiki houkoku." }] },
      { japanese: "連絡", romaji: "renraku", english: "Contact", examples: [{ jp: "密に 連絡を取り合う。", en: "Keep in close contact.", romaji: "Mitsu ni renraku wo toriau." }, { jp: "連絡 事項。", en: "Items for contact/notice.", romaji: "Renraku jikou." }] },
      { japanese: "相談", romaji: "soudan", english: "Consultation", examples: [{ jp: "先輩に 相談する。", en: "Consult with senior.", romaji: "Senpai ni soudan suru." }, { jp: "個別 相談。", en: "Individual consultation.", romaji: "Kobetsu soudan." }] },
      { japanese: "協力", romaji: "kyouryoku", english: "Cooperation", examples: [{ jp: "お互いに 協力する。", en: "Cooperate with each other.", romaji: "Otagai ni kyouryoku suru." }, { jp: "協力 体制。", en: "Cooperative system.", romaji: "Kyouryoku taisei." }] },
      { japanese: "尊敬", romaji: "sonkei", english: "Respect", examples: [{ jp: "上司を 尊敬する。", en: "Respect the boss.", romaji: "Juushi wo sonkei suru." }, { jp: "尊敬の 念。", en: "Feeling of respect.", romaji: "Sonkei no nen." }] },
      { japanese: "謙遜", romaji: "kenson", english: "Modesty/Humble", examples: [{ jp: "謙遜して 言う。", en: "Say humbly.", romaji: "Kenson shite iu." }, { jp: "謙遜な 態度。", en: "Humble attitude.", romaji: "Kenson na taido." }] },
      { japanese: "失礼", romaji: "shitsurei", english: "Rude/Impudence", examples: [{ jp: "失礼な 態度。", en: "Rude attitude.", romaji: "Shitsurei na taido." }, { jp: "お先に 失礼します。", en: "Pardon me for leaving first.", romaji: "Osaki ni shitsureishimasu." }] },
      { japanese: "挨拶", romaji: "aisatsu", english: "Greeting", examples: [{ jp: "朝の 挨拶。", en: "Morning greeting.", romaji: "Asa no aisatsu." }, { jp: "挨拶 回り。", en: "Making the rounds of greetings.", romaji: "Aisatsu mawari." }] },
      { japanese: "礼儀", romaji: "reigi", english: "Etiquette", examples: [{ jp: "ビジネス 礼儀。", en: "Business etiquette.", romaji: "Bijinesu reigi." }, { jp: "礼儀を 守る。", en: "Observe etiquette.", romaji: "Reigi wo mamoru." }] },
      { japanese: "名刺", romaji: "meishi", english: "Business card", examples: [{ jp: "名刺を 交換する。", en: "Exchange business cards.", romaji: "Meishi wo koukan suru." }, { jp: "名刺 入れ。", en: "Business card case.", romaji: "Meishi ire." }] }
    ]
  },
  {
    id: 62,
    level: "N3",
    title: "Education & Learning",
    description: "Vocabulary for school life, exams, and academic achievements",
    words: [
      { japanese: "科目", romaji: "kamoku", english: "Subject", examples: [{ jp: "好きな 科目。", en: "Favorite subject.", romaji: "Sukina kamoku." }, { jp: "必修 科目。", en: "Required subject.", romaji: "Hisshuu kamoku." }] },
      { japanese: "授業", romaji: "jugyou", english: "Class/Lesson", examples: [{ jp: "授業に 遅れる。", en: "Late for class.", romaji: "Jugyou ni okureru." }, { jp: "授業料。", en: "Tuition fee.", romaji: "Jugyouryou." }] },
      { japanese: "講義", romaji: "kougi", english: "Lecture", examples: [{ jp: "大学の 講義。", en: "University lecture.", romaji: "Daigaku no kougi." }, { jp: "講義を 聴く。", en: "Listen to a lecture.", romaji: "Kougi wo kiku." }] },
      { japanese: "合格", romaji: "goukaku", english: "Passing (Exam)", examples: [{ jp: "試験に 合格した。", en: "Passed the exam.", romaji: "Shiken ni goukaku shita." }, { jp: "合格 通知。", en: "Notification of passing.", romaji: "Goukaku tsuuchi." }] },
      { japanese: "不合格", romaji: "fugoukaku", english: "Failure (Exam)", examples: [{ jp: "残念ながら不合格だ。", en: "Unfortunately, I failed.", romaji: "Zannennagara fugoukaku da." }, { jp: "不合格を 恐れる。", en: "Fear failing.", romaji: "Fugoukaku wo osoreru." }] },
      { japanese: "進学", romaji: "shingaku", english: "Advancement to higher school", examples: [{ jp: "大学に 進学する。", en: "Go to university.", romaji: "Daigaku ni shingaku suru." }, { jp: "進学 相談。", en: "Consultation on advancement.", romaji: "Shingaku soudan." }] },
      { japanese: "留学", romaji: "ryuugaku", english: "Study abroad", examples: [{ jp: "日本に 留学する。", en: "Study abroad in Japan.", romaji: "Nihon ni ryuugaku suru." }, { jp: "留学生。", en: "Foreign student.", romaji: "Ryuugakusei." }] },
      { japanese: "成績", romaji: "seiseki", english: "Grades", examples: [{ jp: "成績が 上がる。", en: "Grades go up.", romaji: "Seiseki ga agaru." }, { jp: "素晴らしい 成績。", en: "Wonderful grades.", romaji: "Subarashii seiseki." }] },
      { japanese: "評価", romaji: "hyouka", english: "Evaluation", examples: [{ jp: "正当な 評価。", en: "Fair evaluation.", romaji: "Seitouna hyouka." }, { jp: "評価を 受ける。", en: "Be evaluated.", romaji: "Hyouka wo ukeru." }] },
      { japanese: "暗記", romaji: "anki", english: "Memorization", examples: [{ jp: "単語を 暗記する。", en: "Memorize words.", romaji: "Tango wo anki suru." }, { jp: "暗記力。", en: "Power of memory.", romaji: "Ankiryoku." }] },
      { japanese: "理解", romaji: "rikai", english: "Understanding", examples: [{ jp: "内容を 理解する。", en: "Understand the content.", romaji: "Naiyou wo rikai suru." }, { jp: "理解が 深まる。", en: "Understanding deepens.", romaji: "Rikai ga fukamaru." }] },
      { japanese: "知識", romaji: "chishiki", english: "Knowledge", examples: [{ jp: "知識を 吸収する。", en: "Absorb knowledge.", romaji: "Chishiki wo kyuushuu suru." }, { jp: "豊富な 知識。", en: "Abundant knowledge.", romaji: "Houfu na chishiki." }] },
      { japanese: "経験", romaji: "keiken", english: "Experience", examples: [{ jp: "貴重な 経験。", en: "Precious experience.", romaji: "Kichou na keiken." }, { jp: "経験を 積む。", en: "Gain experience.", romaji: "Keiken wo tsumu." }] },
      { japanese: "実力", romaji: "jitsuryoku", english: "Actual ability", examples: [{ jp: "実力を 発揮する。", en: "Show one's true ability.", romaji: "Jitsuryoku wo hakki suru." }, { jp: "実力 テスト。", en: "Ability test.", romaji: "Jitsuryoku tesuto." }] },
      { japanese: "才能", romaji: "sainou", english: "Talent", examples: [{ jp: "才能が ある。", en: "Have talent.", romaji: "Sainou ga aru." }, { jp: "潜在 才能。", en: "Potential talent.", romaji: "Senzai sainou." }] },
      { japanese: "努力", romaji: "doryoku", english: "Effort", examples: [{ jp: "努力を 重ねる。", en: "Keep making effort.", romaji: "Doryoku wo kasaneru." }, { jp: "努力家。", en: "Hard worker.", romaji: "Doryokuka." }] },
      { japanese: "義務", romaji: "gimu", english: "Obligation/Duty", examples: [{ jp: "義務 教育。", en: "Compulsory education.", romaji: "Gimu kyouiku." }, { jp: "教育の 義務。", en: "Duty of education.", romaji: "Kyouiku no gimu." }] },
      { japanese: "制度", romaji: "seido", english: "System", examples: [{ jp: "新しい 教育制度。", en: "New education system.", romaji: "Atarashii kyouiku seido." }, { jp: "制度の 改革。", en: "Reform of the system.", romaji: "Seido no kaikaku." }] },
      { japanese: "専門", romaji: "senmon", english: "Specialty", examples: [{ jp: "専門 知識。", en: "Specialized knowledge.", romaji: "Senmon chishiki." }, { jp: "専門 学校。", en: "Vocational school.", romaji: "Senmon gakkou." }] },
      { japanese: "研究", romaji: "kenkyuu", english: "Research", examples: [{ jp: "物理を 研究する。", en: "Research physics.", romaji: "Butsuri wo kenkyuu suru." }, { jp: "研究者。", en: "Researcher.", romaji: "Kenkyuusha." }] },
      { japanese: "課題", romaji: "kadai", english: "Task/Assignment", examples: [{ jp: "今日の 課題。", en: "Today's task.", romaji: "Kyou no kadai." }, { jp: "課題を 提出する。", en: "Submit an assignment.", romaji: "Kadai wo teishutsu suru." }] },
      { japanese: "提出", romaji: "teishutsu", english: "Submission", examples: [{ jp: "レポートを 提出する。", en: "Submit a report.", romaji: "Repooto wo teishutsu suru." }, { jp: "提出 期限。", en: "Submission deadline.", romaji: "Teishutsu kigen." }] },
      { japanese: "範囲", romaji: "han'ei", english: "Scope/Range", examples: [{ jp: "テストの 範囲。", en: "Scope of the test.", romaji: "Tesuto no han'ei." }, { jp: "広 範囲。", en: "Wide range.", romaji: "Kou han'ei." }] },
      { japanese: "集中", romaji: "shuuchuu", english: "Concentration", examples: [{ jp: "勉強に 集中する。", en: "Concentrate on studying.", romaji: "Benkyou ni shuuchuu suru." }, { jp: "集中力。", en: "Concentration power.", romaji: "Shuuchuuryoku." }] },
      { japanese: "克服", romaji: "kokufuku", english: "Coping/Overcoming", examples: [{ jp: "弱点を 克服する。", en: "Overcome weaknesses.", romaji: "Jakuten wo kokufuku suru." }, { jp: "恐怖を 克服。", en: "Conquering fear.", romaji: "Kyoufu wo kokufuku." }] },
      { japanese: "上達", romaji: "joutatsu", english: "Improvement", examples: [{ jp: "上達が 早い。", en: "Improvement is fast.", romaji: "Joutatsu ga hayai." }, { jp: "スキルを 上達させる。", en: "Improve skills.", romaji: "Sukiru wo joutatsu saseru." }] },
      { japanese: "目標", romaji: "mokuhyou", english: "Goal/Objective", examples: [{ jp: "目標を 立てる。", en: "Set a goal.", romaji: "Mokuhyou wo tateru." }, { jp: "目標へ 向かう。", en: "Head towards goal.", romaji: "Mokuhyou e mukau." }] },
      { japanese: "達成", romaji: "tassei", english: "Achievement", examples: [{ jp: "念願を 達成する。", en: "Achieve one's desire.", romaji: "Nengan wo tassei suru." }, { jp: "達成 可能だ。", en: "It is achievable.", romaji: "Tassei kanou da." }] },
      { japanese: "塾", romaji: "juku", english: "Cram school", examples: [{ jp: "塾に 通う。", en: "Attend cram school.", romaji: "Juku ni kayou." }, { jp: "進学 塾。", en: "Prep school.", romaji: "Shingaku juku." }] },
      { japanese: "受験", romaji: "juken", english: "Taking an exam", examples: [{ jp: "大学を 受験する。", en: "Take university entrance exam.", romaji: "Daigaku wo juken suru." }, { jp: "受験生。", en: "Exam candidate.", romaji: "Jukensei." }] }
    ]
  },
  {
    id: 63,
    level: "N3",
    title: "Justice & Ethics",
    description: "Vocabulary for laws, rights, and moral concepts",
    words: [
      { japanese: "法律", romaji: "houritsu", english: "Law", examples: [{ jp: "法律に 詳しい。", en: "Familiar with laws.", romaji: "Houritsu ni kuwashii." }, { jp: "法律を 遵守する。", en: "Obey the law.", romaji: "Houritsu wo junshu suru." }] },
      { japanese: "裁判", romaji: "saiban", english: "Trial/Judgment", examples: [{ jp: "裁判を 受ける。", en: "Go to trial.", romaji: "Saiban wo ukeru." }, { jp: "裁判所。", en: "Court.", romaji: "Saibansho." }] },
      { japanese: "犯人", romaji: "hannin", english: "Culprit/Criminal", examples: [{ jp: "犯人を 捕まえる。", en: "Catch the culprit.", romaji: "Hannin wo tsukamaeru." }, { jp: "真 犯人。", en: "The real culprit.", romaji: "Shin hannin." }] },
      { japanese: "事件", romaji: "jiken", english: "Incident/Case", examples: [{ jp: "重大な 事件。", en: "Serious incident.", romaji: "Juudai na jiken." }, { jp: "事件を 解決する。", en: "Solve the case.", romaji: "Jiken wo kaiketsu suru." }] },
      { japanese: "捜査", romaji: "sousa", english: "Investigation", examples: [{ jp: "警察が 捜査する。", en: "Police investigate.", romaji: "Keisatsu ga sousa suru." }, { jp: "捜査 網。", en: "Investigative net.", romaji: "Sousa mou." }] },
      { japanese: "逮捕", romaji: "taiho", english: "Arrest", examples: [{ jp: "容疑者を 逮捕する。", en: "Arrest a suspect.", romaji: "Yougisha wo taihosuru." }, { jp: "逮捕 状。", en: "Arrest warrant.", romaji: "Taiho jou." }] },
      { japanese: "証拠", romaji: "shouko", english: "Evidence", examples: [{ jp: "決定的な 証拠。", en: "Decisive evidence.", romaji: "Ketteiteki na shouko." }, { jp: "証拠 不十分。", en: "Insufficient evidence.", romaji: "Shouko fujuubun." }] },
      { japanese: "容疑", romaji: "yougi", english: "Suspicion", examples: [{ jp: "容疑が かかる。", en: "Be under suspicion.", romaji: "Yougi ga kakaru." }, { jp: "容疑者。", en: "Suspect.", romaji: "Yougisha." }] },
      { japanese: "権利", romaji: "kenri", english: "Right", examples: [{ jp: "正当な 権利。", en: "Justifiable right.", romaji: "Seitouna kenri." }, { jp: "人権を 守る。", en: "Protect human rights.", romaji: "Jinken wo mamoru." }] },
      { japanese: "義務", romaji: "gimu", english: "Duty/Obligation", examples: [{ jp: "国民の 義務。", en: "Duty of the citizens.", romaji: "Kokumin no gimu." }, { jp: "義務を 果たす。", en: "Fulfill an obligation.", romaji: "Gimu wo hatasu." }] },
      { japanese: "責任", romaji: "sekinin", english: "Responsibility", examples: [{ jp: "自分の 責任だ。", en: "It's my responsibility.", romaji: "Jibun no sekinin da." }, { jp: "責任感。", en: "Sense of responsibility.", romaji: "Sekininkan." }] },
      { japanese: "罰金", romaji: "bakkin", english: "Fine", examples: [{ jp: "罰金を 払う。", en: "Pay a fine.", romaji: "Bakkin wo harau." }, { jp: "高額な 罰金。", en: "Large fine.", romaji: "Kougaku na bakkin." }] },
      { japanese: "平価", romaji: "heika", english: "Par/Equality", examples: [{ jp: "平等な 社会。", en: "Equal society.", romaji: "Byoudou na shakai." }, { jp: "男女 平等。", en: "Gender equality.", romaji: "Danjou byoudou." }] },
      { japanese: "差別", romaji: "sabetsu", english: "Discrimination", examples: [{ jp: "差別を なくす。", en: "Eliminate discrimination.", romaji: "Sabetshu wo nakusu." }, { jp: "不当な 差別。", en: "Unfair discrimination.", romaji: "Futou na sabetsu." }] },
      { japanese: "平和", romaji: "heiwa", english: "Peace", examples: [{ jp: "世界 平和。", en: "World peace.", romaji: "Sekai heiwa." }, { jp: "平和的に 解決する。", en: "Solve peacefully.", romaji: "Heiwateki ni kaiketsu suru." }] },
      { japanese: "道徳", romaji: "doutoku", english: "Morals", examples: [{ jp: "道徳を 守る。", en: "Follow morals.", romaji: "Doutoku wo mamoru." }, { jp: "道徳 教育。", en: "Moral education.", romaji: "Doutoku kyouiku." }] },
      { japanese: "倫理", romaji: "rinri", english: "Ethics", examples: [{ jp: "職業 倫理。", en: "Professional ethics.", romaji: "Shokugyou rinri." }, { jp: "倫理的に 問題がある。", en: "Ethically problematic.", romaji: "Rinriteki ni mondai ga aru." }] },
      { japanese: "正直", romaji: "shoujiki", english: "Honest", examples: [{ jp: "正直に 言う。", en: "Say honestly.", romaji: "Shoujiki ni iu." }, { jp: "正直な 人。", en: "Honest person.", romaji: "Shoujiki na hito." }] },
      { japanese: "裏切り", romaji: "uragiri", english: "Betrayal", examples: [{ jp: "友人の 裏切り。", en: "Friend's betrayal.", romaji: "Yuujin no uragiri." }, { jp: "信じて 裏切られた。", en: "Trusted and was betrayed.", romaji: "Shinjite uragirareta." }] },
      { japanese: "信頼", romaji: "shinrai", english: "Trust", examples: [{ jp: "お互いに 信頼する。", en: "Trust each other.", romaji: "Otagai ni shinrai suru." }, { jp: "信頼を 築く。", en: "Build trust.", romaji: "Shinrai wo kizuku." }] },
      { japanese: "違反", romaji: "ihan", english: "Violation", examples: [{ jp: "ルール 違反。", en: "Rule violation.", romaji: "Ruuru ihan." }, { jp: "信号 違反。", en: "Signal violation.", romaji: "Shingou ihan." }] },
      { japanese: "禁止", romaji: "kinshi", english: "Prohibition", examples: [{ jp: "立入 禁止。", en: "Keep out.", romaji: "Tachiiri kinshi." }, { jp: "飲酒 運転の禁止。", en: "Prohibition of drunk driving.", romaji: "Inshu unten no kinshi." }] },
      { japanese: "許可", romaji: "kyoka", english: "Permission", examples: [{ jp: "許可を 求める。", en: "Request permission.", romaji: "Kyoka wo motomeru." }, { jp: "許可が 下りる。", en: "Permission is granted.", romaji: "Kyoka ga oriru." }] },
      { japanese: "正義", romaji: "seigi", english: "Justice", examples: [{ jp: "正義感が 強い。", en: "Strong sense of justice.", romaji: "Seigikan ga tsuyoi." }, { jp: "正義の 味方。", en: "Ally of justice.", romaji: "Seigi no mikata." }] },
      { japanese: "犯罪", romaji: "hanzai", english: "Crime", examples: [{ jp: "犯罪を 減らす。", en: "Reduce crime.", romaji: "Hanzai wo herasu." }, { jp: "犯罪 心理。", en: "Criminal psychology.", romaji: "Hanzai shinri." }] },
      { japanese: "被害", romaji: "higai", english: "Damage/Victimization", examples: [{ jp: "被害を 受ける。", en: "Suffer damage/be victimized.", romaji: "Higai wo ukeru." }, { jp: "被害者。", en: "Victim.", romaji: "Higaisha." }] },
      { japanese: "弁護士", romaji: "bengoshi", english: "Lawyer", examples: [{ jp: "弁護士に 相談する。", en: "Consult a lawyer.", romaji: "Bengoshi ni soudan suru." }, { jp: "弁護 費用。", en: "Legal fees.", romaji: "Bengo hiyou." }] },
      { japanese: "証言", romaji: "shougen", english: "Testimony", examples: [{ jp: "目撃者の 証言。", en: "Eyewitness testimony.", romaji: "Mokugekisha no shougen." }, { jp: "真実を 証言する。", en: "Testify the truth.", romaji: "Shinjitsu wo shougen suru." }] },
      { japanese: "告訴", romaji: "kokuso", english: "Accusation/Charge", examples: [{ jp: "彼を 告訴する。", en: "Charge him.", romaji: "Kare wo kokuso suru." }, { jp: "法的 措置。", en: "Legal action.", romaji: "Houteki sochi." }] },
      { japanese: "救済", romaji: "kyuusai", english: "Relief/Redemption", examples: [{ jp: "被害者の 救済。", en: "Relief of victims.", romaji: "Higaisha no kyuusai." }, { jp: "法的 救済。", en: "Legal remedy.", romaji: "Houteki kyuusai." }] }
    ]
  },
  {
    id: 64,
    level: "N3",
    title: "Economy & Money",
    description: "Vocabulary for financial matters and economic trends",
    words: [
      { japanese: "経済", romaji: "keizai", english: "Economy", examples: [{ jp: "日本の 経済。", en: "Japanese economy.", romaji: "Nihon no keizai." }, { jp: "経済学。", en: "Economics.", romaji: "Keizaigaku." }] },
      { japanese: "景気", romaji: "keiki", english: "Business climate", examples: [{ jp: "景気が 良い。", en: "Business is good.", romaji: "Keiki ga yoi." }, { jp: "景気が 後退する。", en: "Economy recedes.", romaji: "Keiki ga koutai suru." }] },
      { japanese: "所得", romaji: "shotoku", english: "Income", examples: [{ jp: "平均 所得。", en: "Average income.", romaji: "Heikun shotoku." }, { jp: "所得 税を払う。", en: "Pay income tax.", romaji: "Shotoku zei wo harau." }] },
      { japanese: "物価", romaji: "bukka", english: "Prices (of goods)", examples: [{ jp: "物価が 上がる。", en: "Prices rise.", romaji: "Bukka ga agaru." }, { jp: "物価 安定。", en: "Price stability.", romaji: "Bukka antei." }] },
      { japanese: "消費", romaji: "shouhi", english: "Consumption", examples: [{ jp: "消費者の ニーズ。", en: "Consumer needs.", romaji: "Shouhisha no niizu." }, { jp: "エネルギーの 消費。", en: "Energy consumption.", romaji: "Enerugii no shouhi." }] },
      { japanese: "需要", romaji: "juyou", english: "Demand", examples: [{ jp: "需要と 供給。", en: "Demand and supply.", romaji: "Juyou to kyoukyuu." }, { jp: "需要が 高まる。", en: "Demand increases.", romaji: "Juyou ga takamaru." }] },
      { japanese: "供給", romaji: "kyoukyuu", english: "Supply", examples: [{ jp: "食料を 供給する。", en: "Supply food.", romaji: "Shokuryou wo kyoukyuu suru." }, { jp: "供給 不足。", en: "Supply shortage.", romaji: "Kyoukyuu fuzoku." }] },
      { japanese: "貿易", romaji: "boueki", english: "Trade", examples: [{ jp: "自由 貿易。", en: "Free trade.", romaji: "Jiyuu boueki." }, { jp: "輸出と 輸入。", en: "Export and import.", romaji: "Yushutsu to yunyuu." }] },
      { japanese: "輸入", romaji: "yunyuu", english: "Import", examples: [{ jp: "日本は資源を輸入する。", en: "Japan imports resources.", romaji: "Nihon wa shigen wo yunyuu suru." }, { jp: "輸入 品。", en: "Imported goods.", romaji: "Yunyuu hin." }] },
      { japanese: "輸出", romaji: "yushutsu", english: "Export", examples: [{ jp: "車を 輸出する。", en: "Export cars.", romaji: "Kuruma wo yushutsu suru." }, { jp: "輸出 額。", en: "Export value.", romaji: "Yushutsu gaku." }] },
      { japanese: "市場", romaji: "ichiba/shijou", english: "Market", examples: [{ jp: "国内 向け市場。", en: "Market for domestic use.", romaji: "Kokunai muke shijou." }, { jp: "市場 調査。", en: "Market research.", romaji: "Shijou chousa." }] },
      { japanese: "金融", romaji: "kin'yuu", english: "Finance", examples: [{ jp: "金融 機関。", en: "Financial institution.", romaji: "Kin'yuu kikan." }, { jp: "国際 金融。", en: "International finance.", romaji: "Kokusai kin'yuu." }] },
      { japanese: "銀行", romaji: "ginkou", english: "Bank", examples: [{ jp: "銀行 口座。", en: "Bank account.", romaji: "Ginkou kouza." }, { jp: "中央 銀行。", en: "Central bank.", romaji: "Chuuou ginkou." }] },
      { japanese: "借金", romaji: "shakkin", english: "Debt", examples: [{ jp: "借金を 返す。", en: "Pay back debt.", romaji: "Shakkin wo kaesu." }, { jp: "多額の 借金。", en: "Large amount of debt.", romaji: "Tagaku no shakkin." }] },
      { japanese: "投資", romaji: "toushi", english: "Investment", examples: [{ jp: "株に 投資する。", en: "Invest in stocks.", romaji: "Kabu ni toushi suru." }, { jp: "自己 投資。", en: "Self-investment.", romaji: "Jiko toushi." }] },
      { japanese: "利益", romaji: "rieki", english: "Profit", examples: [{ jp: "利益を 出す。", en: "Make a profit.", romaji: "Rieki wo dasu." }, { jp: "不当な 利益。", en: "Unfair profit.", romaji: "Futou na rieki." }] },
      { japanese: "赤字", romaji: "akaji", english: "Deficit/Red ink", examples: [{ jp: "今月は 赤字だ。", en: "We're in the red this month.", romaji: "Kongetsu wa akaji da." }, { jp: "貿易 赤字。", en: "Trade deficit.", romaji: "Boueki akaji." }] },
      { japanese: "黒字", romaji: "kuroji", english: "Surplus/Black ink", examples: [{ jp: "ようやく 黒字になった。", en: "Finally we're in the black.", romaji: "Youyaku kuroji ni natta." }, { jp: "大幅な 黒字。", en: "Large surplus.", romaji: "Oohaba na kuroji." }] },
      { japanese: "コスト", romaji: "kosuto", english: "Cost", examples: [{ jp: "コストを 削減する。", en: "Reduce costs.", romaji: "Kosuto wo sakugen suru." }, { jp: "高 コスト。", en: "High cost.", romaji: "Kou kosuto." }] },
      { japanese: "予算", romaji: "yosan", english: "Budget", examples: [{ jp: "予算が 足りない。", en: "Budget is insufficient.", romaji: "Yosan ga tarinai." }, { jp: "予算を 組む。", en: "Formulate a budget.", romaji: "Yosan wo kumu." }] },
      { japanese: "支払い", romaji: "shiharai", english: "Payment", examples: [{ jp: "カードで 支払う。", en: "Pay by card.", romaji: "Kaado de shiharau." }, { jp: "支払 期限。", en: "Payment deadline.", romaji: "Shiharai kigen." }] },
      { japanese: "勘定", romaji: "kanjou", english: "Bill/Calculation", examples: [{ jp: "お勘定を お願いします。", en: "Check, please.", romaji: "O-kanjou wo onegai shimasu." }, { jp: "勘定に 入れる。", en: "Include in calculation.", romaji: "Kanjou ni ireru." }] },
      { japanese: "請求", romaji: "seikyuu", english: "Claim/Bill", examples: [{ jp: "料金を 請求する。", en: "Bill for the fee.", romaji: "Ryoukin wo seikyuu suru." }, { jp: "請求書。", en: "Invoice/Bill.", romaji: "Seikyuusho." }] },
      { japanese: "領収書", romaji: "ryoushuusho", english: "Receipt", examples: [{ jp: "領収書を もらう。", en: "Get a receipt.", romaji: "Ryoushuusho wo morau." }, { jp: "領収書の 宛名。", en: "Name on the receipt.", romaji: "Ryoushuusho no atena." }] },
      { japanese: "税金", romaji: "zeikin", english: "Tax", examples: [{ jp: "税金を 納める。", en: "Pay taxes.", romaji: "Zeikin wo osameru." }, { jp: "消費 税。", en: "Consumption tax.", romaji: "Shouhizei." }] },
      { japanese: "保険", romaji: "hoken", english: "Insurance", examples: [{ jp: "健康 保険に加入する。", en: "Join health insurance.", romaji: "Kenkou hoken ni kanyuu suru." }, { jp: "保険 金。", en: "Insurance money.", romaji: "Hoken kin." }] },
      { japanese: "年金", romaji: "nenkin", english: "Pension", examples: [{ jp: "年金で 生活する。", en: "Live on a pension.", romaji: "Nenkin de seikatsu suru." }, { jp: "国民 年金。", en: "National pension.", romaji: "Kokumin nenkin." }] },
      { japanese: "格差", romaji: "kakusa", english: "Gap/Disparity", examples: [{ jp: "収入の 格差。", en: "Income disparity.", romaji: "Shuunyuu no kakusa." }, { jp: "格差を 是正する。", en: "Correct the disparity.", romaji: "Kakusa wo zesei suru." }] },
      { japanese: "資源", romaji: "shigen", english: "Resources", examples: [{ jp: "資源が 乏しい。", en: "Resource poor.", romaji: "Shigen ga toboshii." }, { jp: "人的 資源。", en: "Human resources.", romaji: "Jinteki shigen." }] },
      { japanese: "将来", romaji: "shourai", english: "Future", examples: [{ jp: "将来の 備え。", en: "Preparation for future.", romaji: "Shourai no sonae." }, { jp: "暗い 将来。", en: "Dark future.", romaji: "Kurai shourai." }] }
    ]
  },
  {
    id: 65,
    level: "N3",
    title: "Global Issues & Safety",
    description: "Vocabulary for international affairs and disaster prevention",
    words: [
      { japanese: "国際", romaji: "kokusai", english: "International", examples: [{ jp: "国際 連合。", en: "United Nations.", romaji: "Kokusai rengou." }, { jp: "国際的な 視野。", en: "International perspective.", romaji: "Kokusaiteki na shiya." }] },
      { japanese: "支援", romaji: "shien", english: "Support/Aid", examples: [{ jp: "人道 支援。", en: "Humanitarian aid.", romaji: "Jindou shien." }, { jp: "支援を 求める。", en: "Request support.", romaji: "Shien wo motomeru." }] },
      { japanese: "協力", romaji: "kyouryoku", english: "Cooperation", examples: [{ jp: "国際 協力。", en: "International cooperation.", romaji: "Kokusai kyouryoku." }, { jp: "協力 体制。", en: "Cooperative system.", romaji: "Kyouryoku taisei." }] },
      { japanese: "紛争", romaji: "funsou", english: "Conflict/Dispute", examples: [{ jp: "領土 紛争。", en: "Territorial dispute.", romaji: "Ryoudou funsou." }, { jp: "紛争を 解決する。", en: "Resolve a conflict.", romaji: "Funsou wo kaiketsu suru." }] },
      { japanese: "戦争", romaji: "sensou", english: "War", examples: [{ jp: "戦争が 起こる。", en: "War breaks out.", romaji: "Sensou ga okoru." }, { jp: "戦争 反対。", en: "Against war.", romaji: "Sensou hantai." }] },
      { japanese: "平和", romaji: "heiwa", english: "Peace", examples: [{ jp: "平和を 祈る。", en: "Pray for peace.", romaji: "Heiwa wo inoru." }, { jp: "世界 平和。", en: "World peace.", romaji: "Sekai heiwa." }] },
      { japanese: "貧困", romaji: "hinkon", english: "Poverty", examples: [{ jp: "貧困からの 脱出。", en: "Escape from poverty.", romaji: "Hinkon kara no dasshutsu." }, { jp: "貧困 問題。", en: "Poverty issue.", romaji: "Hinkon mondai." }] },
      { japanese: "差別", romaji: "sabetsu", english: "Discrimination", examples: [{ jp: "人種 差別。", en: "Racial discrimination.", romaji: "Jinshu sabetsu." }, { jp: "差別を 禁じる。", en: "Forbid discrimination.", romaji: "Sabetsu wo kinjiru." }] },
      { japanese: "対策", romaji: "taisaku", english: "Countermeasure", examples: [{ jp: "災害 対策。", en: "Disaster measures.", romaji: "Saigai taisaku." }, { jp: "万全の 対策。", en: "Thorough measures.", romaji: "Banzen no taisaku." }] },
      { japanese: "災害", romaji: "saigai", english: "Disaster", examples: [{ jp: "自然 災害。", en: "Natural disaster.", romaji: "Shizen saigai." }, { jp: "災害に 備える。", en: "Prepare for disasters.", romaji: "Saigai ni sonaeru." }] },
      { japanese: "地震", romaji: "jishin", english: "Earthquake", examples: [{ jp: "大きな 地震。", en: "Large earthquake.", romaji: "Ookina jishin." }, { jp: "地震 速報。", en: "Earthquake early warning.", romaji: "Jishin sokuhou." }] },
      { japanese: "津波", romaji: "tsunami", english: "Tsunami", examples: [{ jp: "津波 警報。", en: "Tsunami warning.", romaji: "Tsunami keihou." }, { jp: "津波が 押し寄せる。", en: "Tsunami approaches/surges.", romaji: "Tsunami ga oshiyoseru." }] },
      { japanese: "台風", romaji: "taifuu", english: "Typhoon", examples: [{ jp: "台風が 上陸する。", en: "Typhoon makes landfall.", romaji: "Taifuu ga jouriku suru." }, { jp: "台風の 被害。", en: "Typhoon damage.", romaji: "Taifuu no higai." }] },
      { japanese: "洪水", romaji: "kouzui", english: "Flood", examples: [{ jp: "大 洪水。", en: "Major flood.", romaji: "Oo kouzui." }, { jp: "洪水に 警戒する。", en: "Be alert for floods.", romaji: "Kouzui ni keikai suru." }] },
      { japanese: "避難", romaji: "hinan", english: "Evacuation", examples: [{ jp: "安全な場所へ避難する。", en: "Evacuate to safe place.", romaji: "Anzen na basho e hinan suru." }, { jp: "避難所。", en: "Evacuation shelter.", romaji: "Hinanjyo." }] },
      { japanese: "訓練", romaji: "kunren", english: "Training/Drill", examples: [{ jp: "避難 訓練をする。", en: "Perform evacuation drill.", romaji: "Hinan kunren wo suru." }, { jp: "厳しい 訓練。", en: "Strict training.", romaji: "Kibishii kunren." }] },
      { japanese: "警報", romaji: "keihou", english: "Warning/Alarm", examples: [{ jp: "大雨 警報。", en: "Heavy rain warning.", romaji: "Ooame keihou." }, { jp: "警報を 発令する。", en: "Issue an alarm/warning.", romaji: "Keihou wo hatsurei suru." }] },
      { japanese: "注意報", romaji: "chuuihou", english: "Advisory", examples: [{ jp: "強風 注意報。", en: "Strong wind advisory.", romaji: "Kyoufu chuuihou." }, { jp: "大雪 注意報。", en: "Heavy snow advisory.", romaji: "Ooyuki chuuihou." }] },
      { japanese: "救助", romaji: "kyuujo", english: "Rescue", examples: [{ jp: "救助を 待つ。", en: "Wait for rescue.", romaji: "Kyuujo wo matsu." }, { jp: "人命 救助。", en: "Saving a life.", romaji: "Jinmei kyuujo." }] },
      { japanese: "復旧", romaji: "fukkyuu", english: "Restoration", examples: [{ jp: "電気の 復旧。", en: "Restoration of electricity.", romaji: "Denki no fukkyuu." }, { jp: "早期の 復旧を目指す。", en: "Aim for early restoration.", romaji: "Souki no fukkyuu wo mezasu." }] },
      { japanese: "状況", romaji: "joukyou", english: "Situation", examples: [{ jp: "現在の 状況。", en: "Current situation.", romaji: "Genzai no joukyou." }, { jp: "深刻な 状況だ。", en: "It's a serious situation.", romaji: "Shinkoku na joukyou da." }] },
      { japanese: "安全", romaji: "anzen", english: "Safety", examples: [{ jp: "安全を 確認する。", en: "Check for safety.", romaji: "Anzen wo kakunin suru." }, { jp: "安全 第一。", en: "Safety first.", romaji: "Anzen daiichi." }] },
      { japanese: "危険", romaji: "kiken", english: "Danger", examples: [{ jp: "危険を 察知する。", en: "Sense danger.", romaji: "Kiken wo satchi suru." }, { jp: "生命の 危険。", en: "Danger to life.", romaji: "Seimei no kiken." }] },
      { japanese: "備蓄", romaji: "bichiku", english: "Stockpile/Reserve", examples: [{ jp: "食料を 備蓄する。", en: "Stockpile food.", romaji: "Shokuryou wo bichiku suru." }, { jp: "備蓄 品。", en: "Emergency supplies.", romaji: "Bichiku hin." }] },
      { japanese: "知識", romaji: "chishiki", english: "Knowledge", examples: [{ jp: "正しい 知識をもつ。", en: "Have correct knowledge.", romaji: "Tadashii chishiki wo motsu." }, { jp: "防災 知識。", en: "Disaster prevention knowledge.", romaji: "Bousai chishiki." }] },
      { japanese: "自衛", romaji: "jiei", english: "Self-defense", examples: [{ jp: "自衛隊。", en: "Self-defense forces.", romaji: "Jieitai." }, { jp: "自衛の 手段。", en: "Means of self-defense.", romaji: "Jiei no shudan." }] },
      { japanese: "被害", romaji: "higai", english: "Damage", examples: [{ jp: "最小限の 被害。", en: "Minimal damage.", romaji: "Saishougen no higai." }, { jp: "広大な 被害。", en: "Vast damage.", romaji: "Koudai na higai." }] },
      { japanese: "ボランティア", romaji: "borantia", english: "Volunteer", examples: [{ jp: "ボランティアに 参加する。", en: "Join volunteering.", romaji: "Borantia ni sanka suru." }, { jp: "災害 ボランティア。", en: "Disaster relief volunteer.", romaji: "Saigai borantia." }] },
      { japanese: "寄付", romaji: "kifu", english: "Donation", examples: [{ jp: "お金を 寄付する。", en: "Donate money.", romaji: "Okane wo kifu suru." }, { jp: "寄付金。", en: "Donation money.", romaji: "Kifukin." }] },
      { japanese: "責任", romaji: "sekinin", english: "Responsibility", examples: [{ jp: "社会的な 責任。", en: "Social responsibility.", romaji: "Shakaiteki na sekinin." }, { jp: "責任を 果たす。", en: "Fulfill one's responsibility.", romaji: "Sekinin wo hatasu." }] }
    ]
  }
];
