export const chunk3 = [
  {
    id: 11,
    title: "Transport & Travel",
    description: "Vehicles, travel verbs, and related terms",
    words: [
      { japanese: "車", romaji: "kuruma", english: "Car", examples: [{ jp: "車を 運転する。", en: "Drive a car.", romaji: "Kuruma wo unten suru." }, { jp: "新しい 車。", en: "New car.", romaji: "Atarashii kuruma." }] },
      { japanese: "バス", romaji: "basu", english: "Bus", examples: [{ jp: "バスに 乗る。", en: "Ride a bus.", romaji: "Basu ni noru." }, { jp: "バス停。", en: "Bus stop.", romaji: "Basutei." }] },
      { japanese: "電車", romaji: "densha", english: "Train", examples: [{ jp: "電車で 行く。", en: "Go by train.", romaji: "Densha de iku." }, { jp: "満員 電車。", en: "Crowded train.", romaji: "Manin densha." }] },
      { japanese: "地下鉄", romaji: "chikatetsu", english: "Subway", examples: [{ jp: "地下鉄の 駅。", en: "Subway station.", romaji: "Chikatetsu no eki." }, { jp: "地下鉄に 乗る。", en: "Ride subway.", romaji: "Chikatetsu ni noru." }] },
      { japanese: "新幹線", romaji: "shinkansen", english: "Bullet train", examples: [{ jp: "新幹線は 速い。", en: "Shinkansen is fast.", romaji: "Shinkansen wa hayai." }, { jp: "新幹線の 切符。", en: "Shinkansen ticket.", romaji: "Shinkansen no kippu." }] },
      { japanese: "自転車", romaji: "jitensha", english: "Bicycle", examples: [{ jp: "自転車に 乗る。", en: "Ride a bicycle.", romaji: "Jitensha ni noru." }, { jp: "自転車 通学。", en: "Commuting by bike.", romaji: "Jitensha tsuugaku." }] },
      { japanese: "飛行機", romaji: "hikouki", english: "Airplane", examples: [{ jp: "飛行機で 飛ぶ。", en: "Fly by plane.", romaji: "Hikouki de tobu." }, { jp: "飛行機雲。", en: "Contrail.", romaji: "Hikoukigumo." }] },
      { japanese: "船", romaji: "fune", english: "Ship/Boat", examples: [{ jp: "船に 乗る。", en: "Ride a ship.", romaji: "Fune ni noru." }, { jp: "船旅。", en: "Ship journey.", romaji: "Funatabi." }] },
      { japanese: "タクシー", romaji: "takushii", english: "Taxi", examples: [{ jp: "タクシーを 呼ぶ。", en: "Call a taxi.", romaji: "Takushii wo yobu." }, { jp: "タクシー乗り場。", en: "Taxi stand.", romaji: "Takushii noriba." }] },
      { japanese: "駅", romaji: "eki", english: "Station", examples: [{ jp: "駅へ 向かう。", en: "Head to station.", romaji: "Eki e mukau." }, { jp: "最寄り駅。", en: "Nearest station.", romaji: "Moyorieki." }] },
      { japanese: "切符", romaji: "kippu", english: "Ticket", examples: [{ jp: "切符を 買う。", en: "Buy a ticket.", romaji: "Kippu wo kau." }, { jp: "片道 切符。", en: "One-way ticket.", romaji: "Katamichi kippu." }] },
      { japanese: "乗り場", romaji: "noriba", english: "Platform/Stop", examples: [{ jp: "バス 乗り場。", en: "Bus stop.", romaji: "Basu noriba." }, { jp: "タクシー 乗り場。", en: "Taxi stand.", romaji: "Takushii noriba." }] },
      { japanese: "改札口", romaji: "kaisatsuguchi", english: "Ticket gate", examples: [{ jp: "改札口を 通る。", en: "Pass ticket gate.", romaji: "Kaisatsuguchi wo tooru." }, { jp: "改札で 会う。", en: "Meet at gate.", romaji: "Kaisatsu de au." }] },
      { japanese: "ホーム", romaji: "hoomu", english: "Platform", examples: [{ jp: "ホームで 待つ。", en: "Wait at platform.", romaji: "Hoomu de matsu." }, { jp: "一番 ホーム。", en: "Platform 1.", romaji: "Ichiban hoomu." }] },
      { japanese: "空港", romaji: "kuukou", english: "Airport", examples: [{ jp: "空港へ 行く。", en: "Go to airport.", romaji: "Kuukou e iku." }, { jp: "国際 空港。", en: "International airport.", romaji: "Kokusai kuukou." }] },
      { japanese: "旅行", romaji: "ryokou", english: "Travel/Trip", examples: [{ jp: "旅行が 好き。", en: "Like traveling.", romaji: "Ryokou ga suki." }, { jp: "海外 旅行。", en: "Overseas trip.", romaji: "Kaigai ryokou." }] },
      { japanese: "荷物", romaji: "nimotsu", english: "Luggage", examples: [{ jp: "荷物を 持つ。", en: "Hold luggage.", romaji: "Nimotsu wo motsu." }, { jp: "重い 荷物。", en: "Heavy luggage.", romaji: "Omoi nimotsu." }] },
      { japanese: "地図", romaji: "chizu", english: "Map", examples: [{ jp: "地図を 見る。", en: "Look at map.", romaji: "Chizu wo miru." }, { jp: "地図を 書く。", en: "Draw a map.", romaji: "Chizu wo kaku." }] },
      { japanese: "道", romaji: "michi", english: "Road", examples: [{ jp: "道を 教える。", en: "Show the way.", romaji: "Michi wo oshieru." }, { jp: "道に 迷う。", en: "Get lost.", romaji: "Michi ni mayou." }] },
      { japanese: "近い", romaji: "chikai", english: "Near", examples: [{ jp: "駅に近い。", en: "Near the station.", romaji: "Eki ni chikai." }, { jp: "近い 未来。", en: "Near future.", romaji: "Chikai mirai." }] },
      { japanese: "遠い", romaji: "tooi", english: "Far", examples: [{ jp: "学校が 遠い。", en: "School is far.", romaji: "Gakkou ga tooi." }, { jp: "遠い 国。", en: "Distant country.", romaji: "Tooi kuni." }] },
      { japanese: "速い", romaji: "hayai", english: "Fast", examples: [{ jp: "足が 速い。", en: "Fast runner.", romaji: "Ashi ga hayai." }, { jp: "速く 走る。", en: "Run fast.", romaji: "Hayaku hashiru." }] },
      { japanese: "遅い", romaji: "osoi", english: "Slow/Late", examples: [{ jp: "車が 遅い。", en: "Car is slow.", romaji: "Kuruma ga osoi." }, { jp: "遅くなる。", en: "Become late.", romaji: "Osoku naru." }] },
      { japanese: "乗る", romaji: "noru", english: "To ride", examples: [{ jp: "電車に 乗る。", en: "Ride train.", romaji: "Densha ni noru." }, { jp: "波に 乗る。", en: "Ride the wave.", romaji: "Nami ni noru." }] },
      { japanese: "降りる", romaji: "oriru", english: "To get off", examples: [{ jp: "駅で 降りる。", en: "Get off at station.", romaji: "Eki de oriru." }, { jp: "階段を 降りる。", en: "Go down stairs.", romaji: "Kaidan wo oriru." }] },
      { japanese: "歩く", romaji: "aruku", english: "To walk", examples: [{ jp: "駅まで 歩く。", en: "Walk to station.", romaji: "Eki made aruku." }, { jp: "よく 歩く。", en: "Walk a lot.", romaji: "Yoku aruku." }] },
      { japanese: "走る", romaji: "hashiru", english: "To run", examples: [{ jp: "廊下を 走るな。", en: "Don't run in hall.", romaji: "Rouka wo hashiruna." }, { jp: "速く 走る。", en: "Run fast.", romaji: "Hayaku hashiru." }] },
      { japanese: "飛ぶ", romaji: "tobu", english: "To fly", examples: [{ jp: "鳥が 飛ぶ。", en: "Bird flies.", romaji: "Tori ga tobu." }, { jp: "空を 飛ぶ。", en: "Fly in sky.", romaji: "Sora wo tobu." }] },
      { japanese: "止まる", romaji: "tomaru", english: "To stop", examples: [{ jp: "車が 止まる。", en: "Car stops.", romaji: "Kuruma ga tomaru." }, { jp: "止まって ください。", en: "Please stop.", romaji: "Tomatte kudasai." }] },
      { japanese: "曲がる", romaji: "magaru", english: "To turn", examples: [{ jp: "右へ 曲がる。", en: "Turn right.", romaji: "Migi e magaru." }, { jp: "角を 曲がる。", en: "Turn corner.", romaji: "Kado wo magaru." }] }
    ]
  },
  {
    id: 12,
    title: "School & Education",
    description: "Classroom objects, subjects, and study terms",
    words: [
      { japanese: "先生", romaji: "sensei", english: "Teacher", examples: [{ jp: "日本語の 先生。", en: "Japanese teacher.", romaji: "Nihongo no sensei." }, { jp: "先生、質問です。", en: "Teacher, question.", romaji: "Sensei, shitsumon desu." }] },
      { japanese: "学生", romaji: "gakusei", english: "Student", examples: [{ jp: "私は 学生です。", en: "I am a student.", romaji: "Watashi wa gakusei desu." }, { jp: "大学生。", en: "University student.", romaji: "Daigakusei." }] },
      { japanese: "留学生", romaji: "ryuugakusei", english: "International student", examples: [{ jp: "留学生と 話す。", en: "Talk with exchange student.", romaji: "Ryuugakusei to hanasu." }, { jp: "留学生 寮。", en: "Intl student dorm.", romaji: "Ryuugakusei ryou." }] },
      { japanese: "学校", romaji: "gakkou", english: "School", examples: [{ jp: "学校へ 行く。", en: "Go to school.", romaji: "Gakkou e iku." }, { jp: "学校の 友達。", en: "School friend.", romaji: "Gakkou no tomodachi." }] },
      { japanese: "勉強", romaji: "benkyou", english: "Study", examples: [{ jp: "毎日 勉強する。", en: "Study every day.", romaji: "Mainichi benkyou suru." }, { jp: "勉強机。", en: "Study desk.", romaji: "Benkyouzukue." }] },
      { japanese: "授業", romaji: "jugyou", english: "Class/Lesson", examples: [{ jp: "授業が 始まる。", en: "Class starts.", romaji: "Jugyou ga hajimaru." }, { jp: "楽しい 授業。", en: "Fun class.", romaji: "Tanoshii jugyou." }] },
      { japanese: "宿題", romaji: "shukudai", english: "Homework", examples: [{ jp: "宿題を する。", en: "Do homework.", romaji: "Shukudai wo suru." }, { jp: "宿題を 忘れた。", en: "Forgot homework.", romaji: "Shukudai wo wasureta." }] },
      { japanese: "テスト", romaji: "tesuto", english: "Test", examples: [{ jp: "テストを 受ける。", en: "Take a test.", romaji: "Tesuto wo ukeru." }, { jp: "難しい テスト。", en: "Difficult test.", romaji: "Muzukashii tesuto." }] },
      { japanese: "試験", romaji: "shiken", english: "Exam", examples: [{ jp: "試験 勉強。", en: "Exam study.", romaji: "Shiken benkyou." }, { jp: "入学 試験。", en: "Entrance exam.", romaji: "Nyuugaku shiken." }] },
      { japanese: "教室", romaji: "kyoushitsu", english: "Classroom", examples: [{ jp: "教室の 掃除。", en: "Cleaning classroom.", romaji: "Kyoushitsu no souji." }, { jp: "広い 教室。", en: "Spacious classroom.", romaji: "Hiroi kyoushitsu." }] },
      { japanese: "本", romaji: "hon", english: "Book", examples: [{ jp: "本を 読む。", en: "Read a book.", romaji: "Hon wo yomu." }, { jp: "面白い 本。", en: "Interesting book.", romaji: "Omoshiroi hon." }] },
      { japanese: "辞書", romaji: "jisho", english: "Dictionary", examples: [{ jp: "辞書で 調べる。", en: "Look up in dictionary.", romaji: "Jisho de shiraberu." }, { jp: "電子 辞書。", en: "Electronic dictionary.", romaji: "Denshi jisho." }] },
      { japanese: "ノート", romaji: "nooto", english: "Notebook", examples: [{ jp: "ノートに 書く。", en: "Write in notebook.", romaji: "Nooto ni kaku." }, { jp: "ノートを 貸して。", en: "Lend me notebook.", romaji: "Nooto wo kashite." }] },
      { japanese: "鉛筆", romaji: "enpitsu", english: "Pencil", examples: [{ jp: "鉛筆で 書く。", en: "Write with pencil.", romaji: "Enpitsu de kaku." }, { jp: "鉛筆削り。", en: "Pencil sharpener.", romaji: "Enpitsukezuri." }] },
      { japanese: "消しゴム", romaji: "keshigomu", english: "Eraser", examples: [{ jp: "消しゴムで 消す。", en: "Erase with eraser.", romaji: "Keshigomu de kesu." }, { jp: "消しゴムを 買う。", en: "Buy eraser.", romaji: "Keshigomu wo kau." }] },
      { japanese: "ペン", romaji: "pen", english: "Pen", examples: [{ jp: "赤 ペン。", en: "Red pen.", romaji: "Aka pen." }, { jp: "ペンを 貸して。", en: "Lend me a pen.", romaji: "Pen wo kashite." }] },
      { japanese: "紙", romaji: "kami", english: "Paper", examples: [{ jp: "紙に 書く。", en: "Write on paper.", romaji: "Kami ni kaku." }, { jp: "紙 飛行機。", en: "Paper airplane.", romaji: "Kami hikouki." }] },
      { japanese: "黒板", romaji: "kokuban", english: "Blackboard", examples: [{ jp: "黒板を 見る。", en: "Look at blackboard.", romaji: "Kokuban wo miru." }, { jp: "黒板消し。", en: "Blackboard eraser.", romaji: "Kokubankeshi." }] },
      { japanese: "質問", romaji: "shitsumon", english: "Question", examples: [{ jp: "質問が あります。", en: "I have a question.", romaji: "Shitsumon ga arimasu." }, { jp: "質問に 答える。", en: "Answer question.", romaji: "Shitsumon ni kotaeru." }] },
      { japanese: "答え", romaji: "kotae", english: "Answer", examples: [{ jp: "正しい 答え。", en: "Correct answer.", romaji: "Tadashii kotae." }, { jp: "答えを 書く。", en: "Write the answer.", romaji: "Kotae wo kaku." }] },
      { japanese: "練習", romaji: "renshuu", english: "Practice", examples: [{ jp: "会話の 練習。", en: "Conversation practice.", romaji: "Kaiwa no renshuu." }, { jp: "毎日 練習する。", en: "Practice every day.", romaji: "Mainichi renshuu suru." }] },
      { japanese: "作文", romaji: "sakubun", english: "Essay/Composition", examples: [{ jp: "作文を 書く。", en: "Write an essay.", romaji: "Sakubun wo kaku." }, { jp: "長い 作文。", en: "Long essay.", romaji: "Nagai sakubun." }] },
      { japanese: "漢字", romaji: "kanji", english: "Kanji", examples: [{ jp: "漢字を 覚える。", en: "Memorize Kanji.", romaji: "Kanji wo oboeru." }, { jp: "漢字 テスト。", en: "Kanji test.", romaji: "Kanji tesuto." }] },
      { japanese: "ひらがな", romaji: "hiragana", english: "Hiragana", examples: [{ jp: "ひらがなで 書く。", en: "Write in Hiragana.", romaji: "Hiragana de kaku." }, { jp: "ひらがな 表。", en: "Hiragana chart.", romaji: "Hiragana hyou." }] },
      { japanese: "カタカナ", romaji: "katakana", english: "Katakana", examples: [{ jp: "カタカナ 語。", en: "Katakana word.", romaji: "Katakana go." }, { jp: "カタカナで 書く。", en: "Write in Katakana.", romaji: "Katakana de kaku." }] },
      { japanese: "英語", romaji: "eigo", english: "English", examples: [{ jp: "英語を 話す。", en: "Speak English.", romaji: "Eigo wo hanasu." }, { jp: "英語の 先生。", en: "English teacher.", romaji: "Eigo no sensei." }] },
      { japanese: "日本語", romaji: "nihongo", english: "Japanese", examples: [{ jp: "日本語を 勉強する。", en: "Study Japanese.", romaji: "Nihongo wo benkyou suru." }, { jp: "日本語が 上手。", en: "Good at Japanese.", romaji: "Nihongo ga jouzu." }] },
      { japanese: "難しい", romaji: "muzukashii", english: "Difficult", examples: [{ jp: "難しい 問題。", en: "Difficult problem.", romaji: "Muzukashii mondai." }, { jp: "日本語は 難しい。", en: "Japanese is hard.", romaji: "Nihongo wa muzukashii." }] },
      { japanese: "易しい", romaji: "yasashii", english: "Easy", examples: [{ jp: "易しい 本。", en: "Easy book.", romaji: "Yasashii hon." }, { jp: "易しい 問題。", en: "Easy problem.", romaji: "Yasashii mondai." }] },
      { japanese: "覚える", romaji: "oboeru", english: "Memorize/Remember", examples: [{ jp: "単語を 覚える。", en: "Memorize words.", romaji: "Tango wo oboeru." }, { jp: "覚えていますか。", en: "Do you remember?", romaji: "Oboete imasu ka." }] }
    ]
  },
  {
    id: 13,
    title: "Work & Office",
    description: "Office, work tasks, and business terms",
    words: [
      { japanese: "仕事", romaji: "shigoto", english: "Work/Job", examples: [{ jp: "仕事を 探す。", en: "Look for a job.", romaji: "Shigoto wo sagasu." }, { jp: "仕事に 行く。", en: "Go to work.", romaji: "Shigoto ni iku." }] },
      { japanese: "会社", romaji: "kaisha", english: "Company", examples: [{ jp: "会社を 辞める。", en: "Quit company.", romaji: "Kaisha wo yameru." }, { jp: "会社まで バス。", en: "Bus to company.", romaji: "Kaisha made basu." }] },
      { japanese: "社員", romaji: "shain", english: "Employee", examples: [{ jp: "正社員。", en: "Full-time employee.", romaji: "Seishain." }, { jp: "会社の 社員。", en: "Company employee.", romaji: "Kaisha no shain." }] },
      { japanese: "事務所", romaji: "jimusho", english: "Office", examples: [{ jp: "事務所に いる。", en: "Be in office.", romaji: "Jimusho ni iru." }, { jp: "事務所の 掃除。", en: "Office cleaning.", romaji: "Jimusho no souji." }] },
      { japanese: "会議", romaji: "kaigi", english: "Meeting", examples: [{ jp: "会議室。", en: "Meeting room.", romaji: "Kaigishitsu." }, { jp: "会議を 始める。", en: "Start meeting.", romaji: "Kaigi wo hajimeru." }] },
      { japanese: "電話", romaji: "denwa", english: "Telephone", examples: [{ jp: "電話に 出る。", en: "Answer phone.", romaji: "Denwa ni deru." }, { jp: "電話番号。", en: "Phone number.", romaji: "Denwa bangou." }] },
      { japanese: "パソコン", romaji: "pasokon", english: "PC", examples: [{ jp: "パソコンが 壊れた。", en: "PC broke.", romaji: "Pasokon ga kowareta." }, { jp: "ノート パソコン。", en: "Laptop.", romaji: "Nooto pasokon." }] },
      { japanese: "手紙", romaji: "tegami", english: "Letter", examples: [{ jp: "手紙を 書く。", en: "Write a letter.", romaji: "Tegami wo kaku." }, { jp: "手紙を 出す。", en: "Send a letter.", romaji: "Tegami wo dasu." }] },
      { japanese: "メール", romaji: "meeru", english: "E-mail", examples: [{ jp: "メールを 送る。", en: "Send email.", romaji: "Meeru wo okuru." }, { jp: "メール アドレス。", en: "Email address.", romaji: "Meeru adoresu." }] },
      { japanese: "コピー", romaji: "kopii", english: "Copy", examples: [{ jp: "コピーを とる。", en: "Make a copy.", romaji: "Kopii wo toru." }, { jp: "コピー機。", en: "Copier.", romaji: "Kopiiki." }] },
      { japanese: "ファックス", romaji: "fakkusu", english: "Fax", examples: [{ jp: "ファックスを 送る。", en: "Send fax.", romaji: "Fakkusu wo okuru." }, { jp: "ファックス番号。", en: "Fax number.", romaji: "Fakkusu bangou." }] },
      { japanese: "名刺", romaji: "meishi", english: "Business card", examples: [{ jp: "名刺 交換。", en: "Exchange cards.", romaji: "Meishi koukan." }, { jp: "名刺入れ。", en: "Card holder.", romaji: "Meishiire." }] },
      { japanese: "休み", romaji: "yasumi", english: "Break/Holiday", examples: [{ jp: "昼休み。", en: "Lunch break.", romaji: "Hiruyasumi." }, { jp: "夏休み。", en: "Summer holiday.", romaji: "Natsuyasumi." }] },
      { japanese: "給料", romaji: "kyuuryou", english: "Salary", examples: [{ jp: "給料日。", en: "Payday.", romaji: "Kyuuryoubi." }, { jp: "高い 給料。", en: "High salary.", romaji: "Takai kyuuryou." }] },
      { japanese: "ボーナス", romaji: "boonasu", english: "Bonus", examples: [{ jp: "ボーナスが 出る。", en: "Get bonus.", romaji: "Boonasu ga deru." }, { jp: "ボーナスで 買う。", en: "Buy with bonus.", romaji: "Boonasu de kau." }] },
      { japanese: "残業", romaji: "zangyou", english: "Overtime", examples: [{ jp: "今日は 残業です。", en: "Overtime today.", romaji: "Kyou wa zangyou desu." }, { jp: "残業 手当。", en: "Overtime pay.", romaji: "Zangyou teate." }] },
      { japanese: "出張", romaji: "shucchou", english: "Business trip", examples: [{ jp: "大阪へ 出張。", en: "Trip to Osaka.", romaji: "Oosaka e shucchou." }, { jp: "海外 出張。", en: "Overseas trip.", romaji: "Kaigai shucchou." }] },
      { japanese: "働く", romaji: "hataraku", english: "To work", examples: [{ jp: "毎日 働く。", en: "Work every day.", romaji: "Mainichi hataraku." }, { jp: "一緒 に働く。", en: "Work together.", romaji: "Issho ni hataraku." }] },
      { japanese: "休む", romaji: "yasumu", english: "To rest/take off", examples: [{ jp: "会社を 休む。", en: "Take day off.", romaji: "Kaisha wo yasumu." }, { jp: "少し 休む。", en: "Rest a bit.", romaji: "Sukoshi yasumu." }] },
      { japanese: "終わる", romaji: "owaru", english: "To finish", examples: [{ jp: "仕事が 終わる。", en: "Work finishes.", romaji: "Shigoto ga owaru." }, { jp: "夏が 終わる。", en: "Summer ends.", romaji: "Natsu ga owaru." }] },
      { japanese: "始める", romaji: "hajimeru", english: "To start", examples: [{ jp: "仕事を 始める。", en: "Start work.", romaji: "Shigoto wo hajimeru." }, { jp: "会議を 始める。", en: "Start meeting.", romaji: "Kaigi wo hajimeru." }] },
      { japanese: "手伝う", romaji: "tetsudau", english: "To help", examples: [{ jp: "仕事を 手伝う。", en: "Help with work.", romaji: "Shigoto wo tetsudau." }, { jp: "母を 手伝う。", en: "Help mother.", romaji: "Haha wo tetsudau." }] },
      { japanese: "作る", romaji: "tsukuru", english: "To make", examples: [{ jp: "資料を 作る。", en: "Make documents.", romaji: "Shiryou wo tsukuru." }, { jp: "料理を 作る。", en: "Cook.", romaji: "Ryouri wo tsukuru." }] },
      { japanese: "使う", romaji: "tsukau", english: "To use", examples: [{ jp: "パソコンを 使う。", en: "Use PC.", romaji: "Pasokon wo tsukau." }, { jp: "お金を 使う。", en: "Use money.", romaji: "Okane wo tsukau." }] },
      { japanese: "送る", romaji: "okuru", english: "To send", examples: [{ jp: "メールを 送る。", en: "Send email.", romaji: "Meeru wo okuru." }, { jp: "荷物を 送る。", en: "Send luggage.", romaji: "Nimotsu wo okuru." }] },
      { japanese: "もらう", romaji: "morau", english: "To receive", examples: [{ jp: "プレゼントを もらう。", en: "Receive gift.", romaji: "Purezento wo morau." }, { jp: "メールを もらう。", en: "Receive email.", romaji: "Meeru wo morau." }] },
      { japanese: "忙しい", romaji: "isogashii", english: "Busy", examples: [{ jp: "仕事が 忙しい。", en: "Busy with work.", romaji: "Shigoto ga isogashii." }, { jp: "忙しい 日。", en: "Busy day.", romaji: "Isogashii hi." }] },
      { japanese: "暇", romaji: "hima", english: "Free time", examples: [{ jp: "暇な 時間。", en: "Free time.", romaji: "Hima na jikan." }, { jp: "今日は 暇です。", en: "Free today.", romaji: "Kyou wa hima desu." }] },
      { japanese: "大変", romaji: "taihen", english: "Tough/Hard", examples: [{ jp: "仕事が 大変。", en: "Work is tough.", romaji: "Shigoto ga taihen." }, { jp: "それは 大変ですね。", en: "That is tough.", romaji: "Sore wa taihen desu ne." }] },
      { japanese: "簡単", romaji: "kantan", english: "Easy/Simple", examples: [{ jp: "簡単な 仕事。", en: "Easy job.", romaji: "Kantan na shigoto." }, { jp: "簡単な 料理。", en: "Simple cooking.", romaji: "Kantan na ryouri." }] }
    ]
  },
  {
    id: 14,
    title: "Nature & Seasons",
    description: "Weather, natural elements, and seasons",
    words: [
      { japanese: "山", romaji: "yama", english: " Mountain", examples: [{ jp: "山に登る。", en: "Climb mountain.", romaji: "Yama ni noboru." }, { jp: "高い 山。", en: "Tall mountain.", romaji: "Takai yama." }] },
      { japanese: "川", romaji: "kawa", english: "River", examples: [{ jp: "川で 泳ぐ。", en: "Swim in river.", romaji: "Kawa de oyogu." }, { jp: "きれいな 川。", en: "Clean river.", romaji: "Kirei na kawa." }] },
      { japanese: "海", romaji: "umi", english: "Sea/Ocean", examples: [{ jp: "海へ 行く。", en: "Go to sea.", romaji: "Umi e iku." }, { jp: "海の 家。", en: "Beach house.", romaji: "Umi no ie." }] },
      { japanese: "空", romaji: "sora", english: "Sky", examples: [{ jp: "青い 空。", en: "Blue sky.", romaji: "Aoi sora." }, { jp: "空を 見る。", en: "Look at sky.", romaji: "Sora wo miru." }] },
      { japanese: "雨", romaji: "ame", english: "Rain", examples: [{ jp: "雨が 降る。", en: "It rains.", romaji: "Ame ga furu." }, { jp: "大雨。", en: "Heavy rain.", romaji: "Ooame." }] },
      { japanese: "雪", romaji: "yuki", english: "Snow", examples: [{ jp: "雪が 降る。", en: "It snows.", romaji: "Yuki ga furu." }, { jp: "雪だるま。", en: "Snowman.", romaji: "Yukidaruma." }] },
      { japanese: "曇り", romaji: "kumori", english: "Cloudy", examples: [{ jp: "明日は 曇り。", en: "Cloudy tomorrow.", romaji: "Ashita wa kumori." }, { jp: "曇り空。", en: "Cloudy sky.", romaji: "Kumorizora." }] },
      { japanese: "晴れ", romaji: "hare", english: "Sunny", examples: [{ jp: "今日は 晴れ。", en: "Sunny today.", romaji: "Kyou wa hare." }, { jp: "晴れの日。", en: "Sunny day.", romaji: "Hare no hi." }] },
      { japanese: "風", romaji: "kaze", english: "Wind", examples: [{ jp: "風が 吹く。", en: "Wind blows.", romaji: "Kaze ga fuku." }, { jp: "強い 風。", en: "Strong wind.", romaji: "Tsuyoi kaze." }] },
      { japanese: "花", romaji: "hana", english: "Flower", examples: [{ jp: "花が 咲く。", en: "Flower blooms.", romaji: "Hana ga saku." }, { jp: "花屋。", en: "Flower shop.", romaji: "Hanaya." }] },
      { japanese: "木", romaji: "ki", english: "Tree/Wood", examples: [{ jp: "木に 登る。", en: "Climb tree.", romaji: "Ki ni noboru." }, { jp: "木の下。", en: "Under tree.", romaji: "Ki no shita." }] },
      { japanese: "天気", romaji: "tenki", english: "Weather", examples: [{ jp: "いい 天気。", en: "Good weather.", romaji: "Ii tenki." }, { jp: "天気 予報。", en: "Weather forecast.", romaji: "Tenki yohou." }] },
      { japanese: "春", romaji: "haru", english: "Spring", examples: [{ jp: "春が 来た。", en: "Spring has come.", romaji: "Haru ga kita." }, { jp: "春休み。", en: "Spring break.", romaji: "Haruyasumi." }] },
      { japanese: "夏", romaji: "natsu", english: "Summer", examples: [{ jp: "暑い 夏。", en: "Hot summer.", romaji: "Atsui natsu." }, { jp: "夏休み。", en: "Summer vacation.", romaji: "Natsuyasumi." }] },
      { japanese: "秋", romaji: "aki", english: "Autumn", examples: [{ jp: "秋の 紅葉。", en: "Autumn leaves.", romaji: "Aki no kouyou." }, { jp: "食欲の 秋。", en: "Autumn appetite.", romaji: "Shokuyoku no aki." }] },
      { japanese: "冬", romaji: "fuyu", english: "Winter", examples: [{ jp: "寒い 冬。", en: "Cold winter.", romaji: "Samui fuyu." }, { jp: "冬休み。", en: "Winter break.", romaji: "Fuyuyasumi." }] },
      { japanese: "暑い", romaji: "atsui", english: "Hot (weather)", examples: [{ jp: "今日は 暑い。", en: "Hot today.", romaji: "Kyou wa atsui." }, { jp: "蒸し暑い。", en: "Humid.", romaji: "Mushiatsui." }] },
      { japanese: "寒い", romaji: "samui", english: "Cold (weather)", examples: [{ jp: "外は 寒い。", en: "Outside is cold.", romaji: "Soto wa samui." }, { jp: "寒い 日。", en: "Cold day.", romaji: "Samui hi." }] },
      { japanese: "涼しい", romaji: "suzushii", english: "Cool", examples: [{ jp: "涼しい 風。", en: "Cool breeze.", romaji: "Suzushii kaze." }, { jp: "ここは 涼しい。", en: "Cool here.", romaji: "Koko wa suzushii." }] },
      { japanese: "暖かい", romaji: "atatakai", english: "Warm", examples: [{ jp: "暖かい 日。", en: "Warm day.", romaji: "Atatakai hi." }, { jp: "暖かい 服。", en: "Warm clothes.", romaji: "Atatakai fuku." }] },
      { japanese: "公園", romaji: "kouen", english: "Park", examples: [{ jp: "公園を 散歩。", en: "Walk in park.", romaji: "Kouen wo sanpo." }, { jp: "近くの 公園。", en: "Nearby park.", romaji: "Chikaku no kouen." }] },
      { japanese: "池", romaji: "ike", english: "Pond", examples: [{ jp: "池の 鯉。", en: "Koi in pond.", romaji: "Ike no koi." }, { jp: "池に 落ちる。", en: "Fall in pond.", romaji: "Ike ni ochiru." }] },
      { japanese: "星", romaji: "hoshi", english: "Star", examples: [{ jp: "星が きれい。", en: "Stars are pretty.", romaji: "Hoshi ga kirei." }, { jp: "流れ星。", en: "Shooting star.", romaji: "Nagareboshi." }] },
      { japanese: "月", romaji: "tsuki", english: "Moon", examples: [{ jp: "満月。", en: "Full moon.", romaji: "Mangetsu." }, { jp: "月を見る。", en: "Moon viewing.", romaji: "Tsuki wo miru." }] },
      { japanese: "太陽", romaji: "taiyou", english: "Sun", examples: [{ jp: "太陽が 昇る。", en: "Sun rises.", romaji: "Taiyou ga noboru." }, { jp: "太陽の 光。", en: "Sunlight.", romaji: "Taiyou no hikari." }] },
      { japanese: "雲", romaji: "kumo", english: "Cloud", examples: [{ jp: "白い 雲。", en: "White cloud.", romaji: "Shiroi kumo." }, { jp: "雨雲。", en: "Rain cloud.", romaji: "Amagumo." }] },
      { japanese: "石", romaji: "ishi", english: "Stone", examples: [{ jp: "石を 投げる。", en: "Throw stone.", romaji: "Ishi wo nageru." }, { jp: "重い 石。", en: "Heavy stone.", romaji: "Omoi ishi." }] },
      { japanese: "森", romaji: "mori", english: "Forest", examples: [{ jp: "森の 中。", en: "In the forest.", romaji: "Mori no naka." }, { jp: "森の くまさん。", en: "Forest bear.", romaji: "Mori no kumasan." }] },
      { japanese: "林", romaji: "hayashi", english: "Woods/Grove", examples: [{ jp: "林を 歩く。", en: "Walk in woods.", romaji: "Hayashi wo aruku." }, { jp: "雑木林。", en: "Thicket.", romaji: "Zoukibayashi." }] },
      { japanese: "島", romaji: "shima", english: "Island", examples: [{ jp: "島国。", en: "Island nation.", romaji: "Shimaguni." }, { jp: "無人島。", en: "Uninhabited island.", romaji: "Mujintou." }] }
    ]
  },
  {
    id: 15,
    title: "Animals",
    description: "Common animals, pets, and insects",
    words: [
      { japanese: "犬", romaji: "inu", english: "Dog", examples: [{ jp: "犬を 飼う。", en: "Keep a dog.", romaji: "Inu wo kau." }, { jp: "犬の 散歩。", en: "Dog walk.", romaji: "Inu no sanpo." }] },
      { japanese: "猫", romaji: "neko", english: "Cat", examples: [{ jp: "猫が 好き。", en: "Like cats.", romaji: "Neko ga suki." }, { jp: "黒猫。", en: "Black cat.", romaji: "Kuroneko." }] },
      { japanese: "鳥", romaji: "tori", english: "Bird", examples: [{ jp: "鳥が 飛ぶ。", en: "Bird flies.", romaji: "Tori ga tobu." }, { jp: "小鳥。", en: "Small bird.", romaji: "Kotori." }] },
      { japanese: "魚", romaji: "sakana", english: "Fish", examples: [{ jp: "魚を 釣る。", en: "Catch fish.", romaji: "Sakana wo tsuru." }, { jp: "金魚。", en: "Goldfish.", romaji: "Kingyo." }] },
      { japanese: "牛", romaji: "ushi", english: "Cow", examples: [{ jp: "牛の 乳。", en: "Cow milk.", romaji: "Ushi no chichi." }, { jp: "和牛。", en: "Wagyu.", romaji: "Wagyuu." }] },
      { japanese: "豚", romaji: "buta", english: "Pig", examples: [{ jp: "豚肉。", en: "Pork.", romaji: "Butaniku." }, { jp: "豚カツ。", en: "Pork cutlet.", romaji: "Tonkatsu." }] },
      { japanese: "馬", romaji: "uma", english: "Horse", examples: [{ jp: "馬に 乗る。", en: "Ride a horse.", romaji: "Uma ni noru." }, { jp: "乗馬。", en: "Horse riding.", romaji: "Jouba." }] },
      { japanese: "羊", romaji: "hitsuji", english: "Sheep", examples: [{ jp: "羊の 毛。", en: "Sheep wool.", romaji: "Hitsuji no ke." }, { jp: "羊を 数える。", en: "Count sheep.", romaji: "Hitsuji wo kazoeru." }] },
      { japanese: "兎", romaji: "usagi", english: "Rabbit", examples: [{ jp: "兎が 跳ねる。", en: "Rabbit hops.", romaji: "Usagi ga haneru." }, { jp: "白兎。", en: "White rabbit.", romaji: "Shirousagi." }] },
      { japanese: "猿", romaji: "saru", english: "Monkey", examples: [{ jp: "猿も木から落ちる。", en: "Even monkeys fall from trees.", romaji: "Saru mo ki kara ochiru." }, { jp: "動物園の 猿。", en: "Zoo monkey.", romaji: "Doubutsuen no saru." }] },
      { japanese: "パンダ", romaji: "panda", english: "Panda", examples: [{ jp: "パンダを 見る。", en: "See panda.", romaji: "Panda wo miru." }, { jp: "パンダの 赤ちゃん。", en: "Panda baby.", romaji: "Panda no akachan." }] },
      { japanese: "象", romaji: "zou", english: "Elephant", examples: [{ jp: "象は 大きい。", en: "Elephant is big.", romaji: "Zou wa ookii." }, { jp: "象の 鼻。", en: "Elephant trunk.", romaji: "Zou no hana." }] },
      { japanese: "熊", romaji: "kuma", english: "Bear", examples: [{ jp: "熊に 注意。", en: "Beware of bears.", romaji: "Kuma ni chuui." }, { jp: "テディベア。", en: "Teddy bear.", romaji: "Tediibea." }] },
      { japanese: "ネズミ", romaji: "nezumi", english: "Mouse/Rat", examples: [{ jp: "ネズミを 捕る。", en: "Catch mouse.", romaji: "Nezumi wo toru." }, { jp: "ハツカネズミ。", en: "House mouse.", romaji: "Hatsukanezumi." }] },
      { japanese: "蛇", romaji: "hebi", english: "Snake", examples: [{ jp: "蛇が 怖い。", en: "Scared of snakes.", romaji: "Hebi ga kowai." }, { jp: "長い 蛇。", en: "Long snake.", romaji: "Nagai hebi." }] },
      { japanese: "虫", romaji: "mushi", english: "Insect/Bug", examples: [{ jp: "虫の 声。", en: "Sound of insects.", romaji: "Mushi no koe." }, { jp: "虫歯。", en: "Cavity (tooth bug).", romaji: "Mushiba." }] },
      { japanese: "蜂", romaji: "hachi", english: "Bee", examples: [{ jp: "蜂が 飛ぶ。", en: "Bee flies.", romaji: "Hachi ga tobu." }, { jp: "蜂蜜。", en: "Honey.", romaji: "Hachimitsu." }] },
      { japanese: "蜘蛛", romaji: "kumo", english: "Spider", examples: [{ jp: "蜘蛛の 巣。", en: "Spider web.", romaji: "Kumo no su." }, { jp: "蜘蛛が いる。", en: "There is a spider.", romaji: "Kumo ga iru." }] },
      { japanese: "動物", romaji: "doubutsu", english: "Animal", examples: [{ jp: "動物園。", en: "Zoo.", romaji: "Doubutsuen." }, { jp: "野生 動物。", en: "Wild animal.", romaji: "Yasei doubutsu." }] },
      { japanese: "ペット", romaji: "petto", english: "Pet", examples: [{ jp: "ペットホ テル。", en: "Pet hotel.", romaji: "Petto hoteru." }, { jp: "ペットを 買う。", en: "Buy a pet.", romaji: "Petto wo kau." }] },
      { japanese: "亀", romaji: "kame", english: "Turtle", examples: [{ jp: "亀は 遅い。", en: "Turtle is slow.", romaji: "Kame wa osoi." }, { jp: "海亀。", en: "Sea turtle.", romaji: "Umigame." }] },
      { japanese: "鶏", romaji: "niwatori", english: "Chicken", examples: [{ jp: "鶏肉。", en: "Chicken meat.", romaji: "Toriniku." }, { jp: "鶏が 鳴く。", en: "Rooster crows.", romaji: "Niwatori ga naku." }] },
      { japanese: "狐", romaji: "kitsune", english: "Fox", examples: [{ jp: "狐の 嫁入り。", en: "Fox wedding (sun shower).", romaji: "Kitsune no yomeiri." }, { jp: "きつねうどん。", en: "Kitsune udon.", romaji: "Kitsune udon." }] },
      { japanese: "狸", romaji: "tanuki", english: "Raccoon dog", examples: [{ jp: "狸寝入り。", en: "Feigning sleep.", romaji: "Tanukineiri." }, { jp: "化け狸。", en: "Shape-shifting tanuki.", romaji: "Bakedanuki." }] },
      { japanese: "ライオン", romaji: "raion", english: "Lion", examples: [{ jp: "ライオンは 強い。", en: "Lion is strong.", romaji: "Raion wa tsuyoi." }, { jp: "百獣の王。", en: "King of beasts.", romaji: "Hyakujuu no ou." }] },
      { japanese: "虎", romaji: "tora", english: "Tiger", examples: [{ jp: "虎の巻。", en: "Cheat sheet/Manual.", romaji: "Toranomaki." }, { jp: "虎穴。", en: "Tiger's den.", romaji: "Koketsu." }] },
      { japanese: "イルカ", romaji: "iruka", english: "Dolphin", examples: [{ jp: "イルカ ショー。", en: "Dolphin show.", romaji: "Iruka shoo." }, { jp: "イルカと 泳ぐ。", en: "Swim with dolphins.", romaji: "Iruka to oyogu." }] },
      { japanese: "鯨", romaji: "kujira", english: "Whale", examples: [{ jp: "鯨を 見る。", en: "Watch whales.", romaji: "Kujira wo miru." }, { jp: "大きな 鯨。", en: "Big whale.", romaji: "Ookina kujira." }] },
      { japanese: "蚊", romaji: "ka", english: "Mosquito", examples: [{ jp: "蚊に 刺される。", en: "Bitten by mosquito.", romaji: "Ka ni sasareru." }, { jp: "蚊取り線香。", en: "Mosquito coil.", romaji: "Katorisenkou." }] },
      { japanese: "蝶", romaji: "chou", english: "Butterfly", examples: [{ jp: "きれいな 蝶。", en: "Beautiful butterfly.", romaji: "Kirei na chou." }, { jp: "蝶々。", en: "Butterfly (childish).", romaji: "Choucho." }] }
    ]
  }
];
