export const chunk14 = [
  {
    id: 66,
    level: "N3",
    title: "Science & Discovery",
    description: "Vocabulary for scientific methods, findings, and cosmic phenomena",
    words: [
      { japanese: "科学", romaji: "kagaku", english: "Science", examples: [{ jp: "科学の 発展。", en: "Development of science.", romaji: "Kagaku no hatten." }, { jp: "科学者。", en: "Scientist.", romaji: "Kagakusha." }] },
      { japanese: "理論", romaji: "riron", english: "Theory", examples: [{ jp: "相対性 理論。", en: "Theory of Relativity.", romaji: "Soutaisei riron." }, { jp: "理論的な 根拠。", en: "Theoretical basis.", romaji: "Riron teki na konkyo." }] },
      { japanese: "実験", romaji: "jikken", english: "Experiment", examples: [{ jp: "実験に 成功する。", en: "Succeed in an experiment.", romaji: "Jikken ni seikousuru." }, { jp: "実験 道具。", en: "Experimental tools.", romaji: "Jikken dougu." }] },
      { japanese: "観察", romaji: "kansatsu", english: "Observation", examples: [{ jp: "天体を 観察する。", en: "Observe celestial bodies.", romaji: "Tentai wo kansatsu suru." }, { jp: "観察が 鋭い。", en: "Sharp observation.", romaji: "Kansatsu ga surudoi." }] },
      { japanese: "発見", romaji: "hakken", english: "Discovery", examples: [{ jp: "新種の 発見。", en: "Discovery of a new species.", romaji: "Shinshu no hakken." }, { jp: "世紀の 大発見。", en: "The discovery of the century.", romaji: "Seiki no daihakken." }] },
      { japanese: "分析", romaji: "bunseki", english: "Analysis", examples: [{ jp: "成分を 分析する。", en: "Analyze the components.", romaji: "Seibun wo bunseki suru." }, { jp: "分析 結果を検討する。", en: "Examine the analysis results.", romaji: "Bunseki kekka wo kentou suru." }] },
      { japanese: "証明", romaji: "shoumei", english: "Proof/Demonstration", examples: [{ jp: "正しさを 証明する。", en: "Prove the correctness.", romaji: "Tadashisa wo shoumei suru." }, { jp: "身分 証明書。", en: "ID card.", romaji: "Mibun shoumeisho." }] },
      { japanese: "仮説", romaji: "kasetsu", english: "Hypothesis", examples: [{ jp: "仮説を 立てる。", en: "Formulate a hypothesis.", romaji: "Kasetsu wo tateru." }, { jp: "仮説を 検証する。", en: "Verify a hypothesis.", romaji: "Kasetsu wo kenshou suru." }] },
      { japanese: "検証", romaji: "kenshou", english: "Verification", examples: [{ jp: "事実を 検証する。", en: "Verify the facts.", romaji: "Jijitsu wo kenshou suru." }, { jp: "検証 作業。", en: "Verification work.", romaji: "Kenshou sagyou." }] },
      { japanese: "法則", romaji: "housoku", english: "Law (Science)", examples: [{ jp: "自然の 法則。", en: "Law of nature.", romaji: "Shizen no housoku." }, { jp: "万有引力の法則。", en: "Law of universal gravitation.", romaji: "Ban'yuu inryoku no housoku." }] },
      { japanese: "要素", romaji: "youso", english: "Element/Component", examples: [{ jp: "重要な 要素。", en: "Important element.", romaji: "Juuyou na youso." }, { jp: "三 要素。", en: "Three elements.", romaji: "San youso." }] },
      { japanese: "現象", romaji: "genshou", english: "Phenomenon", examples: [{ jp: "物理 現象。", en: "Physical phenomenon.", romaji: "Butsuri genshou." }, { jp: "不思議な 現象。", en: "Mysterious phenomenon.", romaji: "Fushigi na genshou." }] },
      { japanese: "宇宙", romaji: "uchuu", english: "Universe/Space", examples: [{ jp: "宇宙に 行く。", en: "Go to space.", romaji: "Uchuu ni iku." }, { jp: "宇宙 飛行士。", en: "Astronaut.", romaji: "Uchuu hikoushi." }] },
      { japanese: "惑星", romaji: "wakusei", english: "Planet", examples: [{ jp: "未知の 惑星。", en: "Unknown planet.", romaji: "Michi no wakusei." }, { jp: "惑星 探査。", en: "Planetary exploration.", romaji: "Wakusei tansa." }] },
      { japanese: "衛星", romaji: "eisei", english: "Satellite", examples: [{ jp: "人工 衛星。", en: "Artificial satellite.", romaji: "Jinkou eisei." }, { jp: "地球の 衛星。", en: "Earth's satellite.", romaji: "Chikyuu no eisei." }] },
      { japanese: "成分", romaji: "seibun", english: "Ingredient/Component", examples: [{ jp: "有効 成分。", en: "Active ingredient.", romaji: "Yuukou seibun." }, { jp: "成分 表示。", en: "Ingredient labeling.", romaji: "Seibun hyouji." }] },
      { japanese: "反応", romaji: "hannou", english: "Reaction", examples: [{ jp: "化学 反応。", en: "Chemical reaction.", romaji: "Kagaku hannou." }, { jp: "素早い 反応。", en: "Quick reaction.", romaji: "Subayai hannou." }] },
      { japanese: "吸収", romaji: "kyuushuu", english: "Absorption", examples: [{ jp: "水分を 吸収する。", en: "Absorb moisture.", romaji: "Suibun wo kyuushuu suru." }, { jp: "知識の 吸収。", en: "Absorption of knowledge.", romaji: "Chishiki no kyuushuu." }] },
      { japanese: "放出", romaji: "houshutsu", english: "Emission", examples: [{ jp: "熱を 放出する。", en: "Emit heat.", romaji: "Netsu wo houshutsu suru." }, { jp: "放出 されるガス。", en: "Gas that is emitted.", romaji: "Houshutsu sareru gasu." }] },
      { japanese: "変化", romaji: "henka", english: "Change/Transformation", examples: [{ jp: "劇的な 変化。", en: "Dramatic change.", romaji: "Gekiteki na henka." }, { jp: "変化を 観察する。", en: "Observe the change.", romaji: "Henka wo kansatsu suru." }] },
      { japanese: "状態", romaji: "joutai", english: "State/Condition", examples: [{ jp: "液体の 状態。", en: "Liquid state.", romaji: "Ekitai no joutai." }, { jp: "安定 状態。", en: "Stable condition.", romaji: "Antei joutai." }] },
      { japanese: "物質", romaji: "busshitsu", english: "Substance/Matter", examples: [{ jp: "未知の 物質。", en: "Unknown substance.", romaji: "Michi no busshitsu." }, { jp: "有害 物質。", en: "Harmful substance.", romaji: "Yuugai busshitsu." }] },
      { japanese: "原子", romaji: "genshi", english: "Atom", examples: [{ jp: "原子の 構造。", en: "Structure of the atom.", romaji: "Genshi no kouzou." }, { jp: "原子 力。", en: "Atomic/Nuclear power.", romaji: "Genshiryoku." }] },
      { japanese: "分子", romaji: "bunshi", english: "Molecule", examples: [{ jp: "水の 分子。", en: "Water molecule.", romaji: "Mizu no bunshi." }, { jp: "分子 構造。", en: "Molecular structure.", romaji: "Bunshi kouzou." }] },
      { japanese: "高度な", romaji: "koudona", english: "Advanced/High-level", examples: [{ jp: "高度な 技術。", en: "Advanced technology.", romaji: "Koudona gijutsu." }, { jp: "高度に 発達する。", en: "Develop highly.", romaji: "Koudoni hattatsu suru." }] },
      { japanese: "精密な", romaji: "seimitsuna", english: "Precise/Detailed", examples: [{ jp: "精密な 測定。", en: "Precise measurement.", romaji: "Seimitsuna sokutei." }, { jp: "精密 機械。", en: "Precision machinery.", romaji: "Seimitsu kikai." }] },
      { japanese: "有効な", romaji: "yuukouna", english: "Effective/Valid", examples: [{ jp: "有効な 手段。", en: "Effective means.", romaji: "Yuukouna shudan." }, { jp: "期限内は 有効だ。", en: "It's valid within the limit.", romaji: "Kigennai wa yuukou da." }] },
      { japanese: "効率的", romaji: "kouritsuteki", english: "Efficient", examples: [{ jp: "効率的に 進める。", en: "Proceed efficiently.", romaji: "Kouritsuteki ni susumeru." }, { jp: "効率の 良い方法。", en: "An efficient way.", romaji: "Kouritsu no yoi houhou." }] },
      { japanese: "客観的", romaji: "kyakkanteki", english: "Objective", examples: [{ jp: "客観的な 視点。", en: "Objective viewpoint.", romaji: "Kyakkanteki na shiten." }, { jp: "客観的に 判断する。", en: "Judge objectively.", romaji: "Kyakkanteki ni handan suru." }] },
      { japanese: "論理的", romaji: "ronriteki", english: "Logical", examples: [{ jp: "論理的な 説明。", en: "Logical explanation.", romaji: "Ronriteki na setsumei." }, { jp: "筋道が 通っている。", en: "It's logical/coherent.", romaji: "Sujimichi ga tootteiru." }] }
    ]
  },
  {
    id: 67,
    level: "N3",
    title: "Competition & Performance",
    description: "Vocabulary for sports, arts, and competitive activities",
    words: [
      { japanese: "競技", romaji: "kyougi", english: "Competition", examples: [{ jp: "新しい 競技。", en: "A new competition.", romaji: "Atarashii kyougi." }, { jp: "競技 規則。", en: "Competition rules.", romaji: "Kyougi kisoku." }] },
      { japanese: "記録", romaji: "kiroku", english: "Record", examples: [{ jp: "新 記録を樹立する。", en: "Establish a new record.", romaji: "Shin kiroku wo juritsu suru." }, { jp: "毎日の 記録。", en: "Daily record.", romaji: "Mainichi no kiroku." }] },
      { japanese: "優勝", romaji: "yuushou", english: "Victory/Championship", examples: [{ jp: "大会で 優勝する。", en: "Win the tournament.", romaji: "Taikai de yuushou suru." }, { jp: "優勝 カップ。", en: "Championship cup.", romaji: "Yuushou kappu." }] },
      { japanese: "相手", romaji: "aite", english: "Opponent/Partner", examples: [{ jp: "強い 相手。", en: "Strong opponent.", romaji: "Tsuyoi aite." }, { jp: "話の 相手。", en: "Conversation partner.", romaji: "Hanashi no aite." }] },
      { japanese: "応援", romaji: "ouen", english: "Support/Cheering", examples: [{ jp: "声を 限りに応援する。", en: "Cheer as loud as one can.", romaji: "Koe wo kagiri ni ouen suru." }, { jp: "応援 メッセージ。", en: "Support message.", romaji: "Ouen messeeji." }] },
      { japanese: "実力", romaji: "jitsuryoku", english: "Actual ability", examples: [{ jp: "実力を 出し切る。", en: "Give one's all/full ability.", romaji: "Jitsuryoku wo dashikiru." }, { jp: "実力 伯仲だ。", en: "Abilities are evenly matched.", romaji: "Jitsuryoku hakuchuu da." }] },
      { japanese: "勝敗", romaji: "shouhai", english: "Victory or defeat", examples: [{ jp: "勝敗が 決する。", en: "Victory/defeat is decided.", romaji: "Shouhai ga kessuru." }, { jp: "勝敗の 行方。", en: "The outcome of the match.", romaji: "Shouhai no yukue." }] },
      { japanese: "技術", romaji: "gijutsu", english: "Skill/Technique", examples: [{ jp: "見事な 技術。", en: "Splendid technique.", romaji: "Migotona gijutsu." }, { jp: "技術を 磨く。", en: "Polish one's skill.", romaji: "Gijutsu wo migaku." }] },
      { japanese: "活躍", romaji: "katsuyaku", english: "Active role/Success", examples: [{ jp: "プロの世界で活躍する。", en: "Succeed in the pro world.", romaji: "Pro no sekai de katsuyaku suru." }, { jp: "期待以上の 活躍。", en: "Success beyond expectation.", romaji: "Kitai ijou no katsuyaku." }] },
      { japanese: "興奮", romaji: "koufun", english: "Excitement", examples: [{ jp: "観客が 興奮する。", en: "The audience is excited.", romaji: "Kankyaku ga koufun suru." }, { jp: "興奮 気味だ。", en: "A bit excited.", romaji: "Koufun gimida." }] },
      { japanese: "冷静な", romaji: "reiseina", english: "Calm/Cool-headed", examples: [{ jp: "冷静な 判断。", en: "Calm judgment.", romaji: "Reiseina handan." }, { jp: "冷静に なる。", en: "Calm down.", romaji: "Reiseini naru." }] },
      { japanese: "激しい", romaji: "hashii", english: "Intense/Violent", examples: [{ jp: "激しい 競争。", en: "Intense competition.", romaji: "Hashii kyousou." }, { jp: "激しく 揺れる。", en: "Shake violently.", romaji: "Hashiku yureru." }] },
      { japanese: "厳しい", romaji: "kibishii", english: "Strict/Severe", examples: [{ jp: "厳しい 練習。", en: "Strict training.", romaji: "Kibishii renshuu." }, { jp: "厳しい 審査。", en: "Severe/strict screening.", romaji: "Kibishii shinsa." }] },
      { japanese: "成功", romaji: "seikou", english: "Success", examples: [{ jp: "成功を 祈る。", en: "Pray for success.", romaji: "Seikou wo inoru." }, { jp: "大 成功を収める。", en: "Achieve a great success.", romaji: "Dai seikou wo osameru." }] },
      { japanese: "失敗", romaji: "shippai", english: "Failure", examples: [{ jp: "失敗を 恐れない。", en: "Don't fear failure.", romaji: "Shippai wo osorenai." }, { jp: "失敗を バネにする。", en: "Use failure as a springboard.", romaji: "Shippai wo bane ni suru." }] },
      { japanese: "克服", romaji: "kokufuku", english: "Overcoming", examples: [{ jp: "弱点を 克服する。", en: "Overcome weaknesses.", romaji: "Jakuten wo kokufuku suru." }, { jp: "恐怖を 克服。", en: "Conquering fear.", romaji: "Kyoufu wo kokufuku." }] },
      { japanese: "目標", romaji: "mokuhyou", english: "Goal/Target", examples: [{ jp: "高い 目標。", en: "High goal.", romaji: "Takai mokuhyou." }, { jp: "目標を 達成する。", en: "Achieve the goal.", romaji: "Mokuhyou wo tassei suru." }] },
      { japanese: "達成", romaji: "tassei", english: "Achievement", examples: [{ jp: "目的を 達成する。", en: "Achieve the purpose.", romaji: "Mokuteyou wo tassei suru." }, { jp: "達成感が ある。", en: "Have a sense of achievement.", romaji: "Tasseikan ga aru." }] },
      { japanese: "自信", romaji: "jishin", english: "Confidence", examples: [{ jp: "自信に 満ちている。", en: "Full of confidence.", romaji: "Jishin ni michiteiru." }, { jp: "自信を 深める。", en: "Deepen one's confidence.", romaji: "Jishin wo fukameru." }] },
      { japanese: "勇気", romaji: "yuuki", english: "Courage", examples: [{ jp: "勇気を 持つ。", en: "Have courage.", romaji: "Yuuki wo motsu." }, { jp: "勇気を 奪う。", en: "Take away courage.", romaji: "Yuuki wo ubau." }] },
      { japanese: "協力", romaji: "kyouryoku", english: "Cooperation", examples: [{ jp: "チームで 協力する。", en: "Cooperate as a team.", romaji: "Chiimu de kyouryoku suru." }, { jp: "全面 協力。", en: "Full cooperation.", romaji: "Zenmen kyouryoku." }] },
      { japanese: "信頼", romaji: "shinrai", english: "Trust", examples: [{ jp: "仲間を 信頼する。", en: "Trust one's comrades.", romaji: "Nakama wo shinrai suru." }, { jp: "信頼に 応える。", en: "Live up to the trust.", romaji: "Shinrai ni kotaeru." }] },
      { japanese: "責任", romaji: "sekinin", english: "Responsibility", examples: [{ jp: "リーダーの 責任。", en: "Leader's responsibility.", romaji: "Riidaa no sekinin." }, { jp: "責任を 全うする。", en: "Fulfill one's responsibility.", romaji: "Sekinin wo mattou suru." }] },
      { japanese: "練習", romaji: "renshuu", english: "Practice", examples: [{ jp: "猛 練習。", en: "Intense practice.", romaji: "Mou renshuu." }, { jp: "練習が 実を結ぶ。", en: "Practice bears fruit.", romaji: "Renshuu ga mi wo musubu." }] },
      { japanese: "工夫", romaji: "kufuu", english: "Ingenuity/Device", examples: [{ jp: "一 工夫する。", en: "Add some ingenuity.", romaji: "Hito kufuu suru." }, { jp: "工夫を 凝らす。", en: "Exercise ingenuity.", romaji: "Kufuu wo korasu." }] },
      { japanese: "検討", romaji: "kentou", english: "Consideration/Examination", examples: [{ jp: "再 検討する。", en: "Re-examine.", romaji: "Sai kentou suru." }, { jp: "検討中だ。", en: "Under consideration.", romaji: "Kentouchuu da." }] },
      { japanese: "評価", romaji: "hyouka", english: "Evaluation", examples: [{ jp: "高い 評価を受ける。", en: "Receive high evaluation.", romaji: "Takai hyouka wo ukeru." }, { jp: "自己 評価。", en: "Self-evaluation.", romaji: "Jiko hyouka." }] },
      { japanese: "披露", romaji: "hirou", english: "Performance/Show", examples: [{ jp: "妙技を 披露する。", en: "Show off a superb skill.", romaji: "Myougi wo hirou suru." }, { jp: "完成 披露。", en: "Unveiling completion.", romaji: "Kansei hirou." }] },
      { japanese: "本格的", romaji: "honkakuteki", english: "Genuine/Full-scale", examples: [{ jp: "本格的に 始める。", en: "Start full-scale.", romaji: "Honkakuteki ni hajimeru." }, { jp: "本格派の 選手。", en: "Genuine/serious player.", romaji: "Honkakuha no senshu." }] },
      { japanese: "注目", romaji: "chuumoku", english: "Attention", examples: [{ jp: "世界が 注目する。", en: "The world pays attention.", romaji: "Sekai ga chuumoku suru." }, { jp: "注目の 的。", en: "Center of attention.", romaji: "Chuumoku no mato." }] }
    ]
  },
  {
    id: 68,
    level: "N3",
    title: "Arts & Humanities",
    description: "Vocabulary for literary works, fine arts, and mental disciplines",
    words: [
      { japanese: "文学", romaji: "bungaku", english: "Literature", examples: [{ jp: "日本 文学。", en: "Japanese literature.", romaji: "Nihon bungaku." }, { jp: "文学 賞。", en: "Literary prize.", romaji: "Bungaku shou." }] },
      { japanese: "小説", romaji: "shousetsu", english: "Novel", examples: [{ jp: "短編 小説。", en: "Short story/novel.", romaji: "Tanpen shousetsu." }, { jp: "小説を 書く。", en: "Write a novel.", romaji: "Shousetsu wo kaku." }] },
      { japanese: "物語", romaji: "monogatari", english: "Story/Tale", examples: [{ jp: "源氏 物語。", en: "Tale of Genji.", romaji: "Genji monogatari." }, { jp: "不思議な 物語。", en: "Mysterious tale.", romaji: "Fushigi na monogatari." }] },
      { japanese: "著者", romaji: "chosha", english: "Author", examples: [{ jp: "著者に 会う。", en: "Meet the author.", romaji: "Chosha ni au." }, { jp: "有名な 著者。", en: "Famous author.", romaji: "Yuumeina chosha." }] },
      { japanese: "出版", romaji: "shuppan", english: "Publishing", examples: [{ jp: "本を 出版する。", en: "Publish a book.", romaji: "Hon wo shuppan suru." }, { jp: "出版社。", en: "Publisher.", romaji: "Shuppansha." }] },
      { japanese: "編集", romaji: "henshuu", english: "Editing", examples: [{ jp: "映像を 編集する。", en: "Edit video.", romaji: "Eizou wo henshuu suru." }, { jp: "編集者。", en: "Editor.", romaji: "Henshuusha." }] },
      { japanese: "表現", romaji: "hyougen", english: "Expression", examples: [{ jp: "豊かな 表現。", en: "Rich expression.", romaji: "Yutakana hyougen." }, { jp: "自己 表現。", en: "Self-expression.", romaji: "Jiko hyougen." }] },
      { japanese: "芸術", romaji: "geijutsu", english: "Art", examples: [{ jp: "芸術的な 作品。", en: "Artistic work.", romaji: "Geijutsuteki na sakuhin." }, { jp: "芸術の 秋。", en: "Autumn, the season for art.", romaji: "Geijutsu no aki." }] },
      { japanese: "絵画", romaji: "kaiga", english: "Painting", examples: [{ jp: "西洋 絵画。", en: "Western painting.", romaji: "Seiyou kaiga." }, { jp: "絵画 展。", en: "Painting exhibition.", romaji: "Kaiga ten." }] },
      { japanese: "彫刻", romaji: "choukoku", english: "Sculpture", examples: [{ jp: "彫刻を 制作する。", en: "Produce a sculpture.", romaji: "Choukoku wo seisaku suru." }, { jp: "木 彫。", en: "Wood carving.", romaji: "Mokuchou." }] },
      { japanese: "音楽", romaji: "ongaku", english: "Music", examples: [{ jp: "クラシック 音楽。", en: "Classical music.", romaji: "Kurashikku ongaku." }, { jp: "音楽家。", en: "Musician.", romaji: "Ongakuka." }] },
      { japanese: "楽器", romaji: "gakki", english: "Instrument", examples: [{ jp: "楽器を 演奏する。", en: "Play an instrument.", romaji: "Gakki wo ensou suru." }, { jp: "和 楽器。", en: "Japanese instrument.", romaji: "Wa gakki." }] },
      { japanese: "劇", romaji: "geki", english: "Drama/Play", examples: [{ jp: "劇を 見る。", en: "Watch a play.", romaji: "Geki wo miru." }, { jp: "人形 劇。", en: "Puppet show.", romaji: "Ningyou geki." }] },
      { japanese: "俳優", romaji: "haiyuu", english: "Actor", examples: [{ jp: "有名な 俳優。", en: "Famous actor.", romaji: "Yuumeina haiyuu." }, { jp: "主演 俳優。", en: "Leading actor.", romaji: "Shuen haiyuu." }] },
      { japanese: "演劇", romaji: "engeki", english: "Theatrical play", examples: [{ jp: "演劇を 鑑賞する。", en: "Appreciate a play.", romaji: "Engeki wo kanshou suru." }, { jp: "演劇 部。", en: "Drama club.", romaji: "Engeki bu." }] },
      { japanese: "文化", romaji: "bunka", english: "Culture", examples: [{ jp: "日本 文化の紹介。", en: "Introduction of Japanese culture.", romaji: "Nihon bunka no shoukai." }, { jp: "多 文化共生。", en: "Multicultural coexistence.", romaji: "Ta bunka kyousei." }] },
      { japanese: "歴史", romaji: "rekishi", english: "History", examples: [{ jp: "歴史を 刻む。", en: "Carve history/Make history.", romaji: "Rekishi wo kizamu." }, { jp: "歴史 小説。", en: "Historical novel.", romaji: "Rekishi shousetsu." }] },
      { japanese: "思想", romaji: "shisou", english: "Thought/Ideology", examples: [{ jp: "自由 思想。", en: "Liberal thought.", romaji: "Jiyuu shisou." }, { jp: "政治 思想。", en: "Political ideology.", romaji: "Seiji shisou." }] },
      { japanese: "哲学", romaji: "tetsugaku", english: "Philosophy", examples: [{ jp: "哲学を 学ぶ。", en: "Study philosophy.", romaji: "Tetsugaku wo manabu." }, { jp: "自分の 哲学をもつ。", en: "Have one's own philosophy.", romaji: "Jibun no tetsugaku wo motsu." }] },
      { japanese: "宗教", romaji: "shuukyou", english: "Religion", examples: [{ jp: "宗教 儀式。", en: "Religious ceremony.", romaji: "Shuukyou gishiki." }, { jp: "新 宗教。", en: "New religion.", romaji: "Shin shuukyou." }] },
      { japanese: "価値観", romaji: "kachikan", english: "Values", examples: [{ jp: "価値観を 共有する。", en: "Share values.", romaji: "Kachikan wo kyouyuu suru." }, { jp: "価値観の 多様化。", en: "Diversification of values.", romaji: "Kachikan no tayouka." }] },
      { japanese: "伝統", romaji: "dentou", english: "Tradition", examples: [{ jp: "伝統を 継承する。", en: "Inherit tradition.", romaji: "Dentou wo keishou suru." }, { jp: "伝統 工芸。", en: "Traditional craft.", romaji: "Dentou kougei." }] },
      { japanese: "創造", romaji: "souzou", english: "Creation", examples: [{ jp: "新しい価値を創造する。", en: "Create new value.", romaji: "Atarashii kachi wo souzou suru." }, { jp: "創造性。", en: "Creativity.", romaji: "Souzousei." }] },
      { japanese: "作品", romaji: "sakuhin", english: "Work/Masterpiece", examples: [{ jp: "代表的な 作品。", en: "Representative work.", romaji: "Daihyouteki na sakuhin." }, { jp: "作品を 応募する。", en: "Apply/submit a work.", romaji: "Sakuhin wo oubo suru." }] },
      { japanese: "感性", romaji: "kansei", english: "Sensitivity", examples: [{ jp: "豊かな 感性。", en: "Rich sensitivity.", romaji: "Yutakana kansei." }, { jp: "感性を 磨く。", en: "Refine one's sensitivity.", romaji: "Kansei wo migaku." }] },
      { japanese: "描写", romaji: "byousha", english: "Description/Depiction", examples: [{ jp: "心理 描写。", en: "Psychological depiction.", romaji: "Shinri byousha." }, { jp: "リアルな 描写。", en: "Realstic description.", romaji: "Riaru na byousha." }] },
      { japanese: "評価", romaji: "hyouka", english: "Evaluation/Appreciation", examples: [{ jp: "過小 評価だ。", en: "It is undervalued.", romaji: "Kashou hyouka da." }, { jp: "高い 評価を受ける。", en: "Be highly evaluated.", romaji: "Takai hyouka wo ukeru." }] },
      { japanese: "批判", romaji: "hihan", english: "Criticism", examples: [{ jp: "文芸 批判。", en: "Literary criticism.", romaji: "Bungei hihan." }, { jp: "建設的な 批判。", en: "Constructive criticism.", romaji: "Kensetsuteki na hihan." }] },
      { japanese: "教養", romaji: "kyouyou", english: "Culture/Education", examples: [{ jp: "教養を 身につける。", en: "Acquire culture/education.", romaji: "Kyouyou wo mi ni tsukeru." }, { jp: "教養が ある人。", en: "Cultured person.", romaji: "Kyouyou ga aru hito." }] },
      { japanese: "理解", romaji: "rikai", english: "Understanding", examples: [{ jp: "他者の 理解。", en: "Understanding of others.", romaji: "Tasha no rikai." }, { jp: "相互 理解。", en: "Mutual understanding.", romaji: "Sougo rikai." }] }
    ]
  },
  {
    id: 69,
    level: "N3",
    title: "Government & International Relations",
    description: "Vocabulary for deep political structures and global affairs",
    words: [
      { japanese: "政府", romaji: "seifu", english: "Government", examples: [{ jp: "日本 政府。", en: "Japanese government.", romaji: "Nihon seifu." }, { jp: "政府 発表。", en: "Government announcement.", romaji: "Seifu happyou." }] },
      { japanese: "政治", romaji: "seiji", english: "Politics", examples: [{ jp: "政治に 関心をもつ。", en: "Have interest in politics.", romaji: "Seiji ni kanshin wo motsu." }, { jp: "政治家。", en: "Politician.", romaji: "Seijika." }] },
      { japanese: "外交", romaji: "gaikou", english: "Diplomacy", examples: [{ jp: "外交 関係。", en: "Diplomatic relations.", romaji: "Gaikou kankei." }, { jp: "外交 交渉。", en: "Diplomatic negotiations.", romaji: "Gaikou koushou." }] },
      { japanese: "国際", romaji: "kokusai", english: "International", examples: [{ jp: "国際 連盟。", en: "League of Nations.", romaji: "Kokusai renmei." }, { jp: "国際 社会。", en: "International society.", romaji: "Kokusai shakai." }] },
      { japanese: "条約", romaji: "jouyaku", english: "Treaty", examples: [{ jp: "条約を 結ぶ。", en: "Sign a treaty.", romaji: "Jouyaku wo musubu." }, { jp: "平和 条約。", en: "Peace treaty.", romaji: "Heiwa jouyaku." }] },
      { japanese: "組織", romaji: "soshiki", english: "Organization", examples: [{ jp: "国連の 組織。", en: "Organization of the UN.", romaji: "Kokuren no soshiki." }, { jp: "組織を 編成する。", en: "Form an organization.", romaji: "Soshiki wo hensei suru." }] },
      { japanese: "協力", romaji: "kyouryoku", english: "Cooperation", examples: [{ jp: "全面的な 協力。", en: "Full cooperation.", romaji: "Zenmenteki na kyouryoku." }, { jp: "経済 協力。", en: "Economic cooperation.", romaji: "Keizai kyouryoku." }] },
      { japanese: "支援", romaji: "shien", english: "Support/Aid", examples: [{ jp: "海外 支援。", en: "Overseas support/aid.", romaji: "Kaigai shien." }, { jp: "資金を 支援する。", en: "Support with funds.", romaji: "Shikin wo shien suru." }] },
      { japanese: "紛争", romaji: "funsou", english: "Conflict", examples: [{ jp: "紛争を 解決する。", en: "Resolve a conflict.", romaji: "Funsou wo kaiketsu suru." }, { jp: "内 紛。", en: "Internal strife.", romaji: "Naifun." }] },
      { japanese: "解決", romaji: "kaiketsu", english: "Solution", examples: [{ jp: "平和的に 解決する。", en: "Solve peacefully.", romaji: "Heiwateki ni kaiketsu suru." }, { jp: "解決の 糸口。", en: "Clue to a solution.", romaji: "Kaiketsu no itoguchi." }] },
      { japanese: "合意", romaji: "goui", english: "Agreement/Consensus", examples: [{ jp: "合意に 達する。", en: "Reach an agreement.", romaji: "Goui ni tassuru." }, { jp: "基本 合意。", en: "Agreement in principle.", romaji: "Kihon goui." }] },
      { japanese: "決定", romaji: "kettei", english: "Decision", examples: [{ jp: "重大な 決定。", en: "Serious decision.", romaji: "Juudai na kettei." }, { jp: "最終的な 決定。", en: "Final decision.", romaji: "Saishuuteki na kettei." }] },
      { japanese: "改革", romaji: "kaikaku", english: "Reform", examples: [{ jp: "社会 改革。", en: "Social reform.", romaji: "Shakai kaikaku." }, { jp: "政治の 改革。", en: "Political reform.", romaji: "Seiji no kaikaku." }] },
      { japanese: "進歩", romaji: "shinpo", english: "Progress", examples: [{ jp: "社会が 進歩する。", en: "Society progresses.", romaji: "Shakai ga shinpo suru." }, { jp: "進歩的な 考え。", en: "Progressive thinking.", romaji: "Shinpoteki na kangae." }] },
      { japanese: "変化", romaji: "henka", english: "Change", examples: [{ jp: "劇的な 変化。", en: "Dramatic change.", romaji: "Gekiteki na henka." }, { jp: "変化に 対応する。", en: "Adapt to change.", romaji: "Henka ni taiou suru." }] },
      { japanese: "対応", romaji: "taiou", english: "Response/Adaptation", examples: [{ jp: "緊急 対応。", en: "Emergency response.", romaji: "Kinkyuu taiou." }, { jp: "柔軟な 対応。", en: "Flexible response.", romaji: "Juunanna taiou." }] },
      { japanese: "対策", romaji: "taisaku", english: "Countermeasure", examples: [{ jp: "国の 対策。", en: "National measures.", romaji: "Kuni no taisaku." }, { jp: "経済 対策。", en: "Economic measures.", romaji: "Keizai taisaku." }] },
      { japanese: "責任", romaji: "sekinin", english: "Responsibility", examples: [{ jp: "重大な 責任。", en: "Serious responsibility.", romaji: "Juudai na sekinin." }, { jp: "責任を 追求する。", en: "Pursue responsibility.", romaji: "Sekinin wo tsuikyuu suru." }] },
      { japanese: "成果", romaji: "seika", english: "Result/Fruit", examples: [{ jp: "交渉の 成果。", en: "Resut of negotiations.", romaji: "Koushou no seika." }, { jp: "大きな 成果を上げる。", en: "Achieve a great result.", romaji: "Ookina seika wo ageru." }] },
      { japanese: "注目", romaji: "chuumoku", english: "Attention", examples: [{ jp: "世界が 注目している。", en: "The world is watching.", romaji: "Sekai ga chuumoku shiteiru." }, { jp: "注目の 閣僚。", en: "Cabinet minister in spotlight.", romaji: "Chuumoku no kakuryou." }] },
      { japanese: "批判", romaji: "hihan", english: "Criticism", examples: [{ jp: "野党の 批判。", en: "Opposition's criticism.", romaji: "Yatou no hihan." }, { jp: "厳しい 批判を浴びる。", en: "Be subjected to harsh criticism.", romaji: "Kibishii hihan wo abiru." }] },
      { japanese: "支持", romaji: "shiji", english: "Support/backing", examples: [{ jp: "国民の 支持を得る。", en: "Gain public support.", romaji: "Kokumin no shiji wo eru." }, { jp: "支持率の 低下。", en: "Drop in support rate.", romaji: "Shijiritsu no teika." }] },
      { japanese: "影響", romaji: "eikyou", english: "Influence", examples: [{ jp: "国際的な 影響力。", en: "International influence.", romaji: "Kokusaiteki na eikyouryoku." }, { jp: "影響を 受ける。", en: "Be influenced.", romaji: "Eikyou wo ukeru." }] },
      { japanese: "目標", romaji: "mokuhyou", english: "Target/Goal", examples: [{ jp: "温室効果ガス削減の目標。", en: "Goal for CO2 reduction.", romaji: "Onshitsukoka gasu sakugen no mokuhyou." }, { jp: "目標を 掲げる。", en: "Set up a goal.", romaji: "Mokuhyou wo kakageru." }] },
      { japanese: "計画", romaji: "keikaku", english: "Plan", examples: [{ jp: "長期 計画。", en: "Long-term plan.", romaji: "Chouki keikaku." }, { jp: "計画を 実行する。", en: "Execute a plan.", romaji: "Keikaku wo jikkou suru." }] },
      { japanese: "現状", romaji: "genjou", english: "Present state", examples: [{ jp: "現状を 打破する。", en: "Overcome the current state.", romaji: "Genjou wo daha suru." }, { jp: "日本の 現状。", en: "Current state of Japan.", romaji: "Nihon no genjou." }] },
      { japanese: "未来", romaji: "mirai", english: "Future", examples: [{ jp: "より良い 未来。", en: "A better future.", romaji: "Yori yoi mirai." }, { jp: "未来へ つなぐ。", en: "Connect to the future.", romaji: "Mirai e tsunagu." }] },
      { japanese: "希望", romaji: "kibou", english: "Hope", examples: [{ jp: "唯一の 希望。", en: "The only hope.", romaji: "Yuiitsu no kibou." }, { jp: "希望を 捨てない。", en: "Don't discard hope.", romaji: "Kibou wo sutenai." }] },
      { japanese: "持続", romaji: "jizoku", english: "Sustainability/Continuance", examples: [{ jp: "持続的な 発展。", en: "Sustainable development.", romaji: "Jizokuteki na hatten." }, { jp: "持続 可能性。", en: "Sustainability.", romaji: "Jizoku kanousei." }] },
      { japanese: "世界", romaji: "sekai", english: "World", examples: [{ jp: "世界 規模。", en: "World scale.", romaji: "Sekai kibo." }, { jp: "世界 平和の実現。", en: "Realization of world peace.", romaji: "Sekai heiwa no jitsugen." }] }
    ]
  },
  {
    id: 70,
    level: "N3",
    title: "Modern Life & Trends",
    description: "Vocabulary for lifestyle, internet trends, and urban convenience",
    words: [
      { japanese: "生活", romaji: "seikatsu", english: "Life/Lifestyle", examples: [{ jp: "不自由な 生活。", en: "Restricted life.", romaji: "Fujiyuuna seikatsu." }, { jp: "自給自足の 生活。", en: "Self-sufficient life.", romaji: "Jikyuujizoku no seikatsu." }] },
      { japanese: "日常", romaji: "nichijou", english: "Daily routine", examples: [{ jp: "日常の 生活。", en: "Daily life.", romaji: "Nichijou no seikatsu." }, { jp: "日常 業務。", en: "Daily routine duties.", romaji: "Nichijou gyoumu." }] },
      { japanese: "流行", romaji: "ryuukou", english: "Fashion/Trend", examples: [{ jp: "流行を 追う。", en: "Follow trends.", romaji: "Ryuukou wo ou." }, { jp: "流行の バッグ。", en: "Trendy bag.", romaji: "Ryuukou no baggu." }] },
      { japanese: "話題", romaji: "wadai", english: "Topic/Conversation", examples: [{ jp: "共通の 話題。", en: "Common topic.", romaji: "Kyoutsuu no wadai." }, { jp: "話題に 乏しい。", en: "Short of topics.", romaji: "Wadai ni toboushii." }] },
      { japanese: "人気", romaji: "ninki", english: "Popularity", examples: [{ jp: "人気が 急上昇。", en: "Popularity surges.", romaji: "Ninki ga kyuujoushou." }, { jp: "若者に 人気だ。", en: "Popular among youth.", romaji: "Wakamononi ninki da." }] },
      { japanese: "変化", romaji: "henka", english: "Change", examples: [{ jp: "時代の 変化。", en: "Changes of times.", romaji: "Jidai no henka." }, { jp: "自分自身の 変化。", en: "Changes in oneself.", romaji: "Jibunjishin no henka." }] },
      { japanese: "進歩", romaji: "shinpo", english: "Progress", examples: [{ jp: "医学の 進歩。", en: "Medicine's progress.", romaji: "Igaku no shinpo." }, { jp: "日進月歩の 社会。", en: "Society that advances daily/monthly.", romaji: "Nisshingeppo no shakai." }] },
      { japanese: "普及", romaji: "fukyuu", english: "Spread/普及", examples: [{ jp: "キャッシュレスが 普及。", en: "Cashless spreads.", romaji: "Kyasshu-resu ga fukyuu." }, { jp: "急速に 普及する。", en: "Spread rapidly.", romaji: "Kyuusokuni fukyuu suru." }] },
      { japanese: "便利", romaji: "benri", english: "Convenient", examples: [{ jp: "ネットは 便利だ。", en: "Internet is convenient.", romaji: "Netto wa benri da." }, { jp: "便利な アプリ。", en: "Convenient app.", romaji: "Benri na apuri." }] },
      { japanese: "不便", romaji: "fuben", english: "Inconvenient", examples: [{ jp: "交通が 不便だ。", en: "Transport is inconvenient.", romaji: "Koutsuu ga fuben da." }, { jp: "不便を 解消する。", en: "Liquidate/Resolve inconvenience.", romaji: "Fuben wo kaishou suru." }] },
      { japanese: "快適", romaji: "kaiteki", english: "Comfortable", examples: [{ jp: "快適な 空間。", en: "Comfortable space.", romaji: "Kaiteki na kuukan." }, { jp: "快適な ドライブ。", en: "Comfortable drive.", romaji: "Kaiteki na doraibu." }] },
      { japanese: "満足", romaji: "manzoku", english: "Satisfaction", examples: [{ jp: "現状に 満足する。", en: "Satisfied with status quo.", romaji: "Genjou ni manzoku suru." }, { jp: "満足 度は高い。", en: "Satisfaction level is high.", romaji: "Manzoku do wa takai." }] },
      { japanese: "ストレス", romaji: "sutoresu", english: "Stress", examples: [{ jp: "ストレスが 溜まる。", en: "Stress piles up.", romaji: "Sutoresu ga tamaru." }, { jp: "ストレスの 発散。", en: "Releasing stress.", romaji: "Sutoresu no hassan." }] },
      { japanese: "健康", romaji: "kenkou", english: "Health", examples: [{ jp: "健康に 気を使う。", en: "Care for health.", romaji: "Kenkou ni ki wo tsukau." }, { jp: "健康 管理。", en: "Health management.", romaji: "Kenkou kanri." }] },
      { japanese: "美容", romaji: "biyou", english: "Beauty", examples: [{ jp: "美容の ため寝る。", en: "Sleep for beauty.", romaji: "Biyou no tame neru." }, { jp: "美容院。", en: "Beauty salon.", romaji: "Biyouin." }] },
      { japanese: "環境", romaji: "kankyou", english: "Environment", examples: [{ jp: "オフィス 環境。", en: "Office environment.", romaji: "Ofisu kankyou." }, { jp: "住 環境。", en: "Living environment.", romaji: "Juukankyou." }] },
      { japanese: "情報", romaji: "jouhou", english: "Information", examples: [{ jp: "新鮮な 情報。", en: "Fresh information.", romaji: "Shinsenna jouhou." }, { jp: "情報を 共有する。", en: "Share information.", romaji: "Jouhou wo kyouyuu suru." }] },
      { japanese: "通信", romaji: "tsuushin", english: "Communication", examples: [{ jp: "５Ｇ 通信。", en: "5G communication.", romaji: "Go-jee tsuushin." }, { jp: "通信 費用。", en: "Communication costs.", romaji: "Tsuushin hiyou." }] },
      { japanese: "デジタル", romaji: "dejitaru", english: "Digital", examples: [{ jp: "デジタル化の 推進。", en: "Promotion of digitizing.", romaji: "Dejitaruka no suishin." }, { jp: "デジタルデバイド。", en: "Digital divide.", romaji: "Dejitaru debaido." }] },
      { japanese: "サービス", romaji: "saabisu", english: "Service", examples: [{ jp: "充実した サービス。", en: "Plentiful service.", romaji: "Juujitsu shita saabisu." }, { jp: "無料 サービス。", en: "Free service.", romaji: "Muryou saabisu." }] },
      { japanese: "買い物", romaji: "kaimono", english: "Shopping", examples: [{ jp: "まとめ 買いをする。", en: "Buying in bulk.", romaji: "Matome gaki wo suru." }, { jp: "ネット ショッピング。", en: "Online shopping.", romaji: "Netto shoppingu." }] },
      { japanese: "外食", romaji: "gaishoku", english: "Eating out", examples: [{ jp: "外食が 多い。", en: "Eat out a lot.", romaji: "Gaishoku ga ooi." }, { jp: "外食 産業。", en: "Food industry.", romaji: "Gaishoku sangyou." }] },
      { japanese: "趣味", romaji: "shumi", english: "Hobby", examples: [{ jp: "多 趣味な人。", en: "Person with many hobbies.", romaji: "Ta shumuna hito." }, { jp: "趣味を 楽しむ。", en: "Enjoy a hobby.", romaji: "Shumi wo tanoshimu." }] },
      { japanese: "娯楽", romaji: "goraku", english: "Entertainment", examples: [{ jp: "多彩な 娯楽。", en: "Diverse entertainments.", romaji: "Tasaina goraku." }, { jp: "娯楽が 少ない。", en: "Little entertainment.", romaji: "Goraku ga sukunai." }] },
      { japanese: "休暇", romaji: "kyuuka", english: "Vacation", examples: [{ jp: "長期 休暇。", en: "Long vacation.", romaji: "Chouki kyuuka." }, { jp: "休暇を 満喫する。", en: "Enjoy vacation fully.", romaji: "Kyuuka wo mankitsu suru." }] },
      { japanese: "旅行", romaji: "ryokou", english: "Travel", examples: [{ jp: "一人 旅。", en: "Solo travel.", romaji: "Hitori tabi." }, { jp: "海外 旅行。", en: "Overseas travel.", romaji: "Kaigai ryokou." }] },
      { japanese: "平和", romaji: "heiwa", english: "Peace", examples: [{ jp: "平和な 日々。", en: "Peaceful days.", romaji: "Heiwa na hibi." }, { jp: "心の 平和。", en: "Peace of mind.", romaji: "Kokoro no heiwa." }] },
      { japanese: "安全", romaji: "anzen", english: "Safety", examples: [{ jp: "安全を 確保する。", en: "Ensure safety.", romaji: "Anzen wo kakuhosuru." }, { jp: "食品 安全。", en: "Food safety.", romaji: "Shokuhin anzen." }] },
      { japanese: "希望", romaji: "kibou", english: "Hope", examples: [{ jp: "希望を 持つ。", en: "Have hope.", romaji: "Kibou wo motsu." }, { jp: "希望に 燃える。", en: "Be burning with hope.", romaji: "Kibou ni moeru." }] },
      { japanese: "将来", romaji: "shourai", english: "Future", examples: [{ jp: "将来を 見据える。", en: "Look into the future.", romaji: "Shourai wo misueru." }, { jp: "理想の 将来。", en: "Ideal future.", romaji: "Risou no shourai." }] }
    ]
  }
];
