export const chunk15 = [
  {
    id: 71,
    level: "N3",
    title: "Psychology & Mental States",
    description: "Vocabulary for deep psychological insights and mental well-being",
    words: [
      { japanese: "心理", romaji: "shinri", english: "Psychology/Mentality", examples: [{ jp: "犯罪 心理学。", en: "Criminal psychology.", romaji: "Hanzai shinrigaku." }, { jp: "心理的な 面。", en: "Psychological aspect.", romaji: "Shinriteki na men." }] },
      { japanese: "意識", romaji: "ishiki", english: "Consciousness/Awareness", examples: [{ jp: "自覚 意識。", en: "Self-awareness.", romaji: "Jikaku ishiki." }, { jp: "意識が 高まる。", en: "Awareness increases.", romaji: "Ishiki ga takamaru." }] },
      { japanese: "無意識", romaji: "muishiki", english: "Unconsciousness", examples: [{ jp: "無意識に 手が動く。", en: "Hands move unconsciously.", romaji: "Muishiki ni te ga ugoku." }, { jp: "無意識の うちに。", en: "Unconsciously.", romaji: "Muishiki no uchi ni." }] },
      { japanese: "反応", romaji: "hannou", english: "Reaction/Response", examples: [{ jp: "拒絶 反応。", en: "Rejection reaction.", romaji: "Kyozetsu hannou." }, { jp: "即座の 反応。", en: "Immediate response.", romaji: "Sokuza no hannou." }] },
      { japanese: "感情", romaji: "kanjou", english: "Emotion", examples: [{ jp: "感情を 表に出す。", en: "Show one's emotions.", romaji: "Kanjou wo omote ni dasu." }, { jp: "感情の 起伏。", en: "Emotional ups and downs.", romaji: "Kanjou no kifuku." }] },
      { japanese: "衝動", romaji: "shoudou", english: "Impulse", examples: [{ jp: "衝動 買いをする。", en: "Impulse buying.", romaji: "Shoudou gaki wo suru." }, { jp: "衝動を 抑えられない。", en: "Cannot suppress the impulse.", romaji: "Shoudou wo osaerarenai." }] },
      { japanese: "欲望", romaji: "yokubou", english: "Desire", examples: [{ jp: "知識の 欲望。", en: "Desire for knowledge.", romaji: "Chishiki no yokubou." }, { jp: "強欲な 人。", en: "Greedy person.", romaji: "Gouyoku na hito." }] },
      { japanese: "満足", romaji: "manzoku", english: "Satisfaction", examples: [{ jp: "自己 満足に陥る。", en: "Fall into self-satisfaction.", romaji: "Jiko manzoku ni ochiru." }, { jp: "満足感を 味わう。", en: "Experience a sense of satisfaction.", romaji: "Manzokukan wo ajwau." }] },
      { japanese: "不安", romaji: "fuan", english: "Anxiety/Unease", examples: [{ jp: "不安を 煽る。", en: "Stir up anxiety.", romaji: "Fuan wo aoru." }, { jp: "不安を 抱える。", en: "Harbor/carry anxiety.", romaji: "Fuan wo kakaeru." }] },
      { japanese: "恐怖", romaji: "kyoufu", english: "Fear/Terror", examples: [{ jp: "恐怖を 克服する。", en: "Overcome fear.", romaji: "Kyoufu wo kokufuku suru." }, { jp: "恐怖の あまり動けない。", en: "Too scared to move.", romaji: "Kyoufu no amari ugokenai." }] },
      { japanese: "葛藤", romaji: "kattou", english: "Conflict (Mental/Inner)", examples: [{ jp: "心の中の 葛藤。", en: "Conflict within one's heart.", romaji: "Kokoro no naka no kattou." }, { jp: "葛藤が 続く。", en: "Conflict continues.", romaji: "Kattou ga tsuzuku." }] },
      { japanese: "絶望", romaji: "zetsubou", english: "Despair", examples: [{ jp: "何に 絶望したのか。", en: "What did you despair over?", romaji: "Nani ni zetsubou shita no ka." }, { jp: "絶望的な 状況。", en: "A hopeless situation.", romaji: "Zetsubouteki na joukyou." }] },
      { japanese: "希望", romaji: "kibou", english: "Hope", examples: [{ jp: "未来に 希望を抱く。", en: "Harbor hope in future.", romaji: "Mirai ni kibou wo idaku." }, { jp: "一縷の 希望。", en: "A ray of hope.", romaji: "Ichiru no kibou." }] },
      { japanese: "安定", romaji: "antei", english: "Stability", examples: [{ jp: "精神の 安定。", en: "Mental stability.", romaji: "Seishin no antei." }, { jp: "安定した 生活。", en: "Stable life.", romaji: "Antei shita seikatsu." }] },
      { japanese: "混乱", romaji: "konran", english: "Confusion/Chaos", examples: [{ jp: "頭が 混乱する。", en: "The head is confused.", romaji: "Atama ga konran suru." }, { jp: "混乱を 招く。", en: "Lead to/cause confusion.", romaji: "Konran wo maneku." }] },
      { japanese: "興奮", romaji: "koufun", english: "Excitement", examples: [{ jp: "興奮して 声が上ずる。", en: "Voice gets high from excitement.", romaji: "Koufunshite koe ga uwazuru." }, { jp: "興奮 状態。", en: "State of excitement.", romaji: "Koufun joutai." }] },
      { japanese: "緊張", romaji: "kinjou", english: "Tension/Nervousness", examples: [{ jp: "緊張を ほぐす。", en: "Unwind/ease the tension.", romaji: "Kinjou wo hogusu." }, { jp: "緊張感が 漂う。", en: "Tension hangs (in the air).", romaji: "Kinjoukan ga tadayou." }] },
      { japanese: "冷静", romaji: "reisei", english: "Calmness", examples: [{ jp: "冷静を 保つ。", en: "Maintain composure.", romaji: "Reisei wo tamotsu." }, { jp: "冷静 沈着だ。", en: "Be perfectly calm/composed.", romaji: "Reisei chinchaku da." }] },
      { japanese: "勇気", romaji: "yuuki", english: "Courage", examples: [{ jp: "勇気を 振り絞る。", en: "Summon up one's courage.", romaji: "Yuuki wo furishiboru." }, { jp: "勇気ある 決断。", en: "Courageous decision.", romaji: "Yuuki aru ketsudan." }] },
      { japanese: "自信", romaji: "jishin", english: "Confidence", examples: [{ jp: "自信を 取り戻す。", en: "Regain confidence.", romaji: "Jishin wo torimodosu." }, { jp: "自信を 喪失する。", en: "Lose confidence.", romaji: "Jishin wo soushitsu suru." }] },
      { japanese: "錯覚", romaji: "sakkaku", english: "Illusion/Hallucination", examples: [{ jp: "錯覚を 起こす。", en: "Experience an illusion.", romaji: "Sakkaku wo okosu." }, { jp: "目の 錯覚。", en: "Optical illusion.", romaji: "Me no sakkaku." }] },
      { japanese: "記憶", romaji: "kioku", english: "Memory", examples: [{ jp: "記憶が 曖昧だ。", en: "The memory is vague.", romaji: "Kioku ga aimai da." }, { jp: "記憶に 残る。", en: "Remain in memory.", romaji: "Kioku ni nokoru." }] },
      { japanese: "執着", romaji: "shuuchaku", english: "Attachment/Obsession", examples: [{ jp: "過去に 執着する。", en: "Cling to the past.", romaji: "Kako ni shuuchaku suru." }, { jp: "執着心を 捨てる。", en: "Discard one's obsession.", romaji: "Shuuchakushin wo suteru." }] },
      { japanese: "寛大", romaji: "kandai", english: "Generous/Magnanimous", examples: [{ jp: "寛大な 心。", en: "Generous heart.", romaji: "Kandai na kokoro." }, { jp: "寛大な 処置。", en: "Leniency.", romaji: "Kandai na shochi." }] },
      { japanese: "誠実", romaji: "seijitsu", english: "Sincerity", examples: [{ jp: "誠実な 人柄。", en: "Sincere personality.", romaji: "Seijitsu na hitogara." }, { jp: "誠実さに 欠ける。", en: "Lack sincerity.", romaji: "Seijitsusa ni kakeru." }] },
      { japanese: "狡猾", romaji: "koukatsu", english: "Cunning/Crafty", examples: [{ jp: "狡猾な 罠。", en: "Cunning trap.", romaji: "Koukatsu na wana." }, { jp: "狡猾に 立ち回る。", en: "Act craftily.", romaji: "Koukatsuni tachimawaru." }] },
      { japanese: "素直", romaji: "sunao", english: "Obedient/Honest", examples: [{ jp: "素直な 気持ちで言う。", en: "Say with honest feelings.", romaji: "Sunao na kimochi de iu." }, { jp: "素直に 認める。", en: "Admit honestly.", romaji: "Sunao ni mitomeru." }] },
      { japanese: "傲慢", romaji: "gouman", english: "Arrogant", examples: [{ jp: "傲慢な 態度。", en: "Arrogant attitude.", romaji: "Gouman na taido." }, { jp: "傲慢 不遜だ。", en: "Be arrogant and insolent.", romaji: "Gouman fuson da." }] },
      { japanese: "卑屈", romaji: "hikutsu", english: "Servile/Obsequious", examples: [{ jp: "卑屈な 笑い。", en: "A servile laugh.", romaji: "Hikutsu na warai." }, { jp: "卑屈に なるな。", en: "Don't be self-deprecating/servile.", romaji: "Hikutsu ni naru na." }] },
      { japanese: "感性", romaji: "kansei", english: "Sensitivity", examples: [{ jp: "鋭い 感性。", en: "Sharp sensitivity.", romaji: "Surudoi kansei." }, { jp: "独特な 感性。", en: "Unique sensitivity.", romaji: "Dokutoku na kansei." }] }
    ]
  },
  {
    id: 72,
    level: "N3",
    title: "Community & Mutual Aid",
    description: "Vocabulary for local activities and supportive societies",
    words: [
      { japanese: "地域", romaji: "chiiki", english: "Region/Community", examples: [{ jp: "地域の 行事。", en: "Local event.", romaji: "Chiiki no gyouji." }, { jp: "地域 社会。", en: "Regional society.", romaji: "Chiiki shakai." }] },
      { japanese: "住民", romaji: "juumin", english: "Residents", examples: [{ jp: "近隣 住民。", en: "Neighboring residents.", romaji: "Kinrin juumin." }, { jp: "住民 票。", en: "Resident record.", romaji: "Juumin hyou." }] },
      { japanese: "協力", romaji: "kyouryoku", english: "Cooperation", examples: [{ jp: "相互に 協力する。", en: "Cooperate mutually.", romaji: "Sougo ni kyouryoku suru." }, { jp: "協力 体制。", en: "Cooperative system.", romaji: "Kyouryoku taisei." }] },
      { japanese: "支援", romaji: "shien", english: "Support/Aid", examples: [{ jp: "被災地を 支援する。", en: "Support the disaster area.", romaji: "Hisaichi wo shisensuru." }, { jp: "支援 物資。", en: "Relief supplies.", romaji: "Shien busshi." }] },
      { japanese: "ボランティア", romaji: "borantia", english: "Volunteer", examples: [{ jp: "ボランティアを 募集する。", en: "Recruit volunteers.", romaji: "Borantia wo boushuu suru." }, { jp: "自主的な ボランティア。", en: "Voluntary volunteering.", romaji: "Jishu teki na borantia." }] },
      { japanese: "活動", romaji: "katsudou", english: "Activity", examples: [{ jp: "政治 活動。", en: "Political activities.", romaji: "Seiji katsudou." }, { jp: "ボランティア 活動。", en: "Volunteer work.", romaji: "Borantia katsudou." }] },
      { japanese: "高齢者", romaji: "koureisha", english: "Elderly person", examples: [{ jp: "高齢者 施設。", en: "Facility for elderly.", romaji: "Koureisha shisetsu." }, { jp: "高齢者への 支援。", en: "Support for the elderly.", romaji: "Koureisha e no shien." }] },
      { japanese: "福祉", romaji: "fukushi", english: "Welfare", examples: [{ jp: "社会 福祉。", en: "Social welfare.", romaji: "Shakai fukushi." }, { jp: "福祉の 仕事。", en: "Welfare work.", romaji: "Fukushi no shigoto." }] },
      { japanese: "貢献", romaji: "kouken", english: "Contribution", examples: [{ jp: "社会に 貢献する。", en: "Contribute to society.", romaji: "Shakai ni kouken suru." }, { jp: "大きな 貢献。", en: "Large contribution.", romaji: "Ookina kouken." }] },
      { japanese: "寄付", romaji: "kifu", english: "Donation", examples: [{ jp: "お金を 寄付する。", en: "Donate money.", romaji: "Okane wo kifu suru." }, { jp: "寄付金を 募る。", en: "Collect donations.", romaji: "Kifukin wo tsunoru." }] },
      { japanese: "交流", romaji: "kouryuu", english: "Interchange/Socializing", examples: [{ jp: "異世代との 交流。", en: "Interaction across generations.", romaji: "I-sedai to no kouryuu." }, { jp: "交流の 場。", en: "Place for interaction.", romaji: "Kouryuu no ba." }] },
      { japanese: "環境", romaji: "kankyou", english: "Environment", examples: [{ jp: "良好な 生活環境。", en: "Good living environment.", romaji: "Ryoukou na seikatsu kankyou." }, { jp: "環境 整備。", en: "Improving the environment.", romaji: "Kankyou seibi." }] },
      { japanese: "美化", romaji: "bika", english: "Beautification", examples: [{ jp: "地域の 美化活動。", en: "Community beautification.", romaji: "Chiiki no bika katsudou." }, { jp: "環境 美化。", en: "Environmental beautification.", romaji: "Kankyou bika." }] },
      { japanese: "清掃", romaji: "seisou", english: "Cleaning", examples: [{ jp: "一斉 清掃。", en: "General cleanup.", romaji: "Issei seisou." }, { jp: "清掃 業者。", en: "Cleaning company.", romaji: "Seisou gyousha." }] },
      { japanese: "防犯", romaji: "bouhan", english: "Crime prevention", examples: [{ jp: "防犯 パトロール。", en: "Security patrol.", romaji: "Bouhan patorooru." }, { jp: "防犯に 努める。", en: "Strive for safety.", romaji: "Bouhan ni tsutomeru." }] },
      { japanese: "防火", romaji: "bouka", english: "Fire prevention", examples: [{ jp: "防火 訓練。", en: "Fire drill.", romaji: "Bouka kunren." }, { jp: "防火 設備。", en: "Fire prevent equipment.", romaji: "Bouka setsubi." }] },
      { japanese: "自治会", romaji: "jichikai", english: "Residents' association", examples: [{ jp: "自治会に 入る。", en: "Join the residents' association.", romaji: "Jichikai ni hairu." }, { jp: "自治会 長。", en: "Head of residents' assoc.", romaji: "Jichikaichou." }] },
      { japanese: "協力", romaji: "kyouryoku", english: "Cooperation", examples: [{ jp: "近隣との 協力。", en: "Cooperation with neighbors.", romaji: "Kinrin to no kyouryoku." }, { jp: "全面 協力する。", en: "Offer full cooperation.", romaji: "Zenmen kyouryoku suru." }] },
      { japanese: "役割", romaji: "yakuwari", english: "Role/Duty", examples: [{ jp: "役割を 分担する。", en: "Share/divide roles.", romaji: "Yakuwari wo buntan suru." }, { jp: "重要な 役割。", en: "Important role.", romaji: "Juuyou na yakuwari." }] },
      { japanese: "分担", romaji: "buntan", english: "Apportionment/Sharing", examples: [{ jp: "費用の 分担。", en: "Sharing of costs.", romaji: "Hiyou no buntan." }, { jp: "仕事を 分担する。", en: "Share the work.", romaji: "Shigoto wo buntan suru." }] },
      { japanese: "参加", romaji: "sanka", english: "Participation", examples: [{ jp: "イベントに 参加する。", en: "Join the event.", romaji: "Ibento ni sanka suru." }, { jp: "全員 参加。", en: "Universal participation.", romaji: "Zenin sanka." }] },
      { japanese: "募集", romaji: "boushuu", english: "Recruitment", examples: [{ jp: "メンバーを 募集する。", en: "Recruit members.", romaji: "Menbaa wo boushuu suru." }, { jp: "公募。", en: "Public appeal/recruit.", romaji: "Koubo." }] },
      { japanese: "信頼", romaji: "shinrai", english: "Trust", examples: [{ jp: "信頼 関係を築く。", en: "Build a trust relationship.", romaji: "Shinrai kankei wo kizuku." }, { jp: "厚い 信頼。", en: "Heavy trust.", romaji: "Atsui shinrai." }] },
      { japanese: "和解", romaji: "wakai", english: "Reconciliation/Settlement", examples: [{ jp: "裁判で 和解する。", en: "Reconcile in court.", romaji: "Saiban de wakai suru." }, { jp: "和解の 道。", en: "The way to reconciliation.", romaji: "Wakai no michi." }] },
      { japanese: "公平", romaji: "kouhei", english: "Fairness", examples: [{ jp: "公平な 扱い。", en: "Fair treatment.", romaji: "Kouhei na atsukau." }, { jp: "不公平だ。", en: "It's unfair.", romaji: "Fukouhei da." }] },
      { japanese: "平等", romaji: "byoudou", english: "Equality", examples: [{ jp: "教育の 平等。", en: "Equality of education.", romaji: "Kyouiku no byoudou." }, { jp: "平等に 分ける。", en: "Divide equally.", romaji: "Byoudou ni wakeru." }] },
      { japanese: "自覚", romaji: "jikaku", english: "Self-awareness/Responsibility", examples: [{ jp: "プロとしての自覚。", en: "Professional sense/awareness.", romaji: "Pro to shite no jikaku." }, { jp: "自覚が 足りない。", en: "Lack awareness/sense.", romaji: "Jikaku ga tarinai." }] },
      { japanese: "義務", romaji: "gimu", english: "Obligation", examples: [{ jp: "教育の 義務。", en: "Duty of education.", romaji: "Kyouiku no gimu." }, { jp: "法律上の 義務。", en: "Legal obligation.", romaji: "Houritsu-jou no gimu." }] },
      { japanese: "平和", romaji: "heiwa", english: "Peace", examples: [{ jp: "街の 平和を守る。", en: "Protect the peace of town.", romaji: "Machi no heiwa wo mamoru." }, { jp: "平和的に 共存する。", en: "Coexist peacefully.", romaji: "Heiwatekini kyouzon suru." }] },
      { japanese: "団結", romaji: "danketsu", english: "Unity/Union", examples: [{ jp: "みんなで 団結する。", en: "Unite together.", romaji: "Minna de danketsu suru." }, { jp: "団結力が 強い。", en: "Strong unity.", romaji: "Danketsuryoku ga tsuyoi." }] }
    ]
  },
  {
    id: 73,
    level: "N3",
    title: "Leisure & Outdoors",
    description: "Vocabulary for high-level travel, recreation, and vacationing",
    words: [
      { japanese: "余暇", romaji: "yoka", english: "Leisure time", examples: [{ jp: "余暇を 楽しむ。", en: "Enjoy leisure time.", romaji: "Yoka wo tanoshimu." }, { jp: "有意義な 余暇。", en: "Meaningful leisure.", romaji: "Yuui-gijna yoka." }] },
      { japanese: "休暇", romaji: "kyuuka", english: "Vacation/Break", examples: [{ jp: "長期 休暇を取る。", en: "Take long vacation.", romaji: "Chouki kyuuka wo toru." }, { jp: "休暇を 満喫する。", en: "Enjoy vacation fully.", romaji: "Kyuuka wo mankitsu suru." }] },
      { japanese: "滞在", romaji: "taizai", english: "Stay/Sojourn", examples: [{ jp: "ホテルに 滞在する。", en: "Stay at a hotel.", romaji: "Hoteru ni taizai suru." }, { jp: "滞在 期間。", en: "Duration of stay.", romaji: "Taizai kikan." }] },
      { japanese: "宿泊", romaji: "shukuhaku", english: "Lodging", examples: [{ jp: "温泉に 宿泊する。", en: "Stay at hot spring inn.", romaji: "Onsen ni shukuhaku suru." }, { jp: "宿泊 施設。", en: "Lodging facility.", romaji: "Shukuhaku shisetsu." }] },
      { japanese: "観光", romaji: "kankou", english: "Sightseeing", examples: [{ jp: "京都の 観光地。", en: "Tourist spots in Kyoto.", romaji: "Kyouto no kankouchi." }, { jp: "観光客が 溢れる。", en: "Tourists overflow.", romaji: "Kankoukyaku ga afureru." }] },
      { japanese: "案内", romaji: "annai", english: "Guide/Information", examples: [{ jp: "案内所は あちらだ。", en: "Info office is over there.", romaji: "Annaijo wa achira da." }, { jp: "町を 案内してもらう。", en: "Have someone guide you around town.", romaji: "Machi wo annaishite morau." }] },
      { japanese: "予約", romaji: "yoyaku", english: "Reservation", examples: [{ jp: "チケットを 予約する。", en: "Book a ticket.", romaji: "Tiketto wo yoyaku suru." }, { jp: "完全 予約制。", en: "By appointment only.", romaji: "Kanzen yoyakusei." }] },
      { japanese: "変更", romaji: "henkou", english: "Change/Modification", examples: [{ jp: "予定を 変更する。", en: "Change the schedule.", romaji: "Yotei wo henkou suru." }, { jp: "変更点。", en: "Point of change.", romaji: "Henkouten." }] },
      { japanese: "取消", romaji: "torikeshi", english: "Cancellation", examples: [{ jp: "予約を 取り消す。", en: "Cancel reservation.", romaji: "Yoyaku wo torikesu." }, { jp: "取消し 料金。", en: "Cancellation fee.", romaji: "Torikeshi ryoukin." }] },
      { japanese: "準備", romaji: "junbi", english: "Preparation", examples: [{ jp: "万全の 準備。", en: "Thorough preparation.", romaji: "Banzen no junbi." }, { jp: "旅行の 準備をする。", en: "Prepare for a trip.", romaji: "Ryokou no junbi wo suru." }] },
      { japanese: "設備", romaji: "setsubi", english: "Facilities/Equipment", examples: [{ jp: "ホテルの 設備。", en: "Hotel facilities.", romaji: "Hoteru no setsubi." }, { jp: "最新の 設備。", en: "Latest equipment.", romaji: "Saishin no setsubi." }] },
      { japanese: "満喫", romaji: "mankitsu", english: "Full enjoyment", examples: [{ jp: "バカンスを 満喫する。", en: "Enjoy vacation fully.", romaji: "Bakansu wo mankitsu suru." }, { jp: "グルメを 満喫。", en: "Enjoying gourmet food.", romaji: "Gurume wo mankitsu." }] },
      { japanese: "散策", romaji: "sansaku", english: "Stroll/Rambling", examples: [{ jp: "旧市街を 散策する。", en: "Stroll in old town.", romaji: "Kyuushigai wo sansaku suru." }, { jp: "朝の 散策。", en: "Morning stroll.", romaji: "Asa no sansaku." }] },
      { japanese: "冒険", romaji: "bouken", english: "Adventure", examples: [{ jp: "冒険に 出る。", en: "Go on an adventure.", romaji: "Bouken ni deru." }, { jp: "冒険 心。", en: "Spirit of adventure.", romaji: "Boukenshin." }] },
      { japanese: "絶景", romaji: "zekkei", english: "Superb view", examples: [{ jp: "山頂の 絶景。", en: "Superb view from summit.", romaji: "Sanchou no zekkei." }, { jp: "絶景 ポイント。", en: "Viewpoint/scenic spot.", romaji: "Zekkei pointo." }] },
      { japanese: "秘境", romaji: "hikyou", english: "Unexplored region", examples: [{ jp: "秘境を 訪ねる。", en: "Visit an unexplored region.", romaji: "Hikyou wo tazuneru." }, { jp: "日本の 秘境。", en: "Japan's hidden spots.", romaji: "Nihon no hikyou." }] },
      { japanese: "快適", romaji: "kaiteki", english: "Comfortable", examples: [{ jp: "快適な 旅。", en: "Comfortable journey.", romaji: "Kaiteki na tabi." }, { jp: "快適に 過ごす。", en: "Spend time comfortably.", romaji: "Kaiteki ni sugosu." }] },
      { japanese: "充実", romaji: "juujitsu", english: "Fulfillment", examples: [{ jp: "充実した 休暇。", en: "Fulfilling vacation.", romaji: "Juujitsu shita kyuuka." }, { jp: "内容が 充実している。", en: "Content is substantial.", romaji: "Naiyou ga juujitsu shiteiru." }] },
      { japanese: "体験", romaji: "taiken", english: "Experience", examples: [{ jp: "貴重な 体験。", en: "Precious experience.", romaji: "Kichou na taiken." }, { jp: "農業を 体験する。", en: "Experience farming.", romaji: "Nougyou wo taiken suru." }] },
      { japanese: "発見", romaji: "hakken", english: "Discovery", examples: [{ jp: "新しい 魅力を発見する。", en: "Discover new charm.", romaji: "Atarashii miryoku wo hakken suru." }, { jp: "驚きの 発見。", en: "Surprising discovery.", romaji: "Odoroki no hakken." }] },
      { japanese: "名産", romaji: "meisan", english: "Local specialty", examples: [{ jp: "土地の 名産品。", en: "Local special product.", romaji: "Tochi no meisanhin." }, { jp: "名産を 食べる。", en: "Eat the local specialty.", romaji: "Meisan wo taberu." }] },
      { japanese: "交流", romaji: "kouryuu", english: "Interaction", examples: [{ jp: "地元の人との交流。", en: "Interaction with locals.", romaji: "Jimoto no hito to no kouryuu." }, { jp: "学生の 交流旅行。", en: "Student exchange trip.", romaji: "Gakusei no kouryuu ryokou." }] },
      { japanese: "刺激", romaji: "shigeki", english: "Stimulus/Excitement", examples: [{ jp: "新しい 刺激を受ける。", en: "Receive new stimuli.", romaji: "Atarashii shigeki wo ukeru." }, { jp: "刺激的な 旅。", en: "Exciting/stimulating trip.", romaji: "Shigekiteki na tabi." }] },
      { japanese: "感銘", romaji: "kanmei", english: "Impression", examples: [{ jp: "美しい景色に感銘を受ける。", en: "Deeply impressed by beauty.", romaji: "Utsukushii keshiki ni kanmei wo ukeru." }, { jp: "感銘を 与える旅行。", en: "A trip that gives impression.", romaji: "Kanmei wo ataeru ryokou." }] },
      { japanese: "休息", romaji: "kyuuseki", english: "Rest", examples: [{ jp: "心身の 休息。", en: "Rest of mind and body.", romaji: "Shinshin no kyuuseki." }, { jp: "休息を 取る。", en: "Take a rest.", romaji: "Kyuuseki wo toru." }] },
      { japanese: "リフレッシュ", romaji: "rifuresshu", english: "Refresh", examples: [{ jp: "気分を リフレッシュする。", en: "Refresh one's mood.", romaji: "Kibun wo rifuresshu suru." }, { jp: "リフレッシュ 休暇。", en: "Refreshment leave.", romaji: "Rifuresshu kyuuka." }] },
      { japanese: "再発見", romaji: "saihakken", english: "Rediscovery", examples: [{ jp: "日本の魅力を再発見する。", en: "Rediscover Japan's charm.", romaji: "Nihon no miryoku wo saihakken suru." }, { jp: "自分を 再発見する。", en: "Rediscover oneself.", romaji: "Jibun wo saihakken suru." }] },
      { japanese: "期待", romaji: "kitai", english: "Expectation", examples: [{ jp: "旅行に 期待を寄せる。", en: "Pin hopes/expectations on trip.", romaji: "Ryokou ni kitai wo yoseru." }, { jp: "期待 通りだ。", en: "As expected.", romaji: "Kitai douri da." }] },
      { japanese: "記録", romaji: "kiroku", english: "Record/Log", examples: [{ jp: "旅の 記録を残す。", en: "Leave a record of travel.", romaji: "Tabi no kiroku wo nokosu." }, { jp: "写真で 記録する。", en: "Record by photos.", romaji: "Shashin de kiroku suru." }] },
      { japanese: "共有", romaji: "kyouyuu", english: "Sharing", examples: [{ jp: "感動を 共有する。", en: "Share the deep emotion.", romaji: "Kandou wo kyouyuu suru." }, { jp: "情報を 共有する。", en: "Share information.", romaji: "Jouhou wo kyouyuu suru." }] }
    ]
  },
  {
    id: 74,
    level: "N3",
    title: "Information Society",
    description: "Vocabulary for internet culture, digital media, and networking",
    words: [
      { japanese: "情報", romaji: "jouhou", english: "Information", examples: [{ jp: "情報を 発信する。", en: "Despatch/Send information.", romaji: "Jouhou wo hasshin suru." }, { jp: "情報 源。", en: "Information source.", romaji: "Jouhou gen." }] },
      { japanese: "発信", romaji: "hasshin", english: "Transmission/Posting", examples: [{ jp: "世界に 情報を発信する。", en: "Transmit info to the world.", romaji: "Sekai ni jouhou wo hasshin suru." }, { jp: "発信 基地。", en: "Transmission base.", romaji: "Hasshin kichi." }] },
      { japanese: "受信", romaji: "jushin", english: "Reception", examples: [{ jp: "電波を 受信する。", en: "Receive signal.", romaji: "Denpa wo jushin suru." }, { jp: "受信 設定。", en: "Reception settings.", romaji: "Jushin setteii." }] },
      { japanese: "公開", romaji: "koukai", english: "Opening to public", examples: [{ jp: "情報を 公開する。", en: "Open information to public.", romaji: "Jouhou wo koukai suru." }, { jp: "一般 公開。", en: "Public opening.", romaji: "Ippan koukai." }] },
      { japanese: "共有", romaji: "kyouyuu", english: "Sharing", examples: [{ jp: "画面を 共有する。", en: "Share the screen.", romaji: "Gamen wo kyouyuu suru." }, { jp: "知識の 共有。", en: "Sharing of knowledge.", romaji: "Chishiki no kyouyuu." }] },
      { japanese: "活用", romaji: "katsuyou", english: "Effective use", examples: [{ jp: "ＩＴを 活用する。", en: "Utilize IT.", romaji: "Ai-tee wo katsuyou suru." }, { jp: "有効 活用。", en: "Effective utilization.", romaji: "Yuukou katsuyou." }] },
      { japanese: "普及", romaji: "fukyuu", english: "Diffusion/Spread", examples: [{ jp: "ネットが 急速に普及。", en: "Internet spreads rapidly.", romaji: "Netto ga kyuusokuni fukyuu." }, { jp: "普及率の 向上。", en: "Improvement of diffusion rate.", romaji: "Fukyuuritsu no koujou." }] },
      { japanese: "接続", romaji: "setsuzoku", english: "Connection", examples: [{ jp: "ネットに 接続不能だ。", en: "Cannot connect to the net.", romaji: "Netto ni setsuzoku funou da." }, { jp: "接続 状況。", en: "Connection status.", romaji: "Setsuzoku joutai." }] },
      { japanese: "検索", romaji: "kensaku", english: "Search", examples: [{ jp: "単語で 検索をかける。", en: "Run a search with word.", romaji: "Tango de kensaku wo kakeru." }, { jp: "検索 エンジン。", en: "Search engine.", romaji: "Kensaku enjin." }] },
      { japanese: "更新", romaji: "koushin", english: "Update", examples: [{ jp: "ブログを 更新する。", en: "Update a blog.", romaji: "Burogu wo koushin suru." }, { jp: "データの 更新。", en: "Update of data.", romaji: "Deeta no koushin." }] },
      { japanese: "登録", romaji: "touroku", english: "Registration", examples: [{ jp: "ユーザー 登録。", en: "User registration.", romaji: "Yuuzaa touroku." }, { jp: "登録を 抹消する。", en: "Erase registration.", romaji: "Touroku wo masshou suru." }] },
      { japanese: "削除", romaji: "sakujo", english: "Deletion", examples: [{ jp: "過去の記事を削除する。", en: "Delete past articles.", romaji: "Kako no kiji wo sakujo suru." }, { jp: "一括 削除。", en: "Batch delete.", romaji: "Ikkatsu sakujo." }] },
      { japanese: "保存", romaji: "hozon", english: "Saving", examples: [{ jp: "バックアップを保存する。", en: "Save a backup.", romaji: "Bakkuappu wo hozon suru." }, { jp: "保存版。", en: "Collector's/keeping edition.", romaji: "Hozon-ban." }] },
      { japanese: "管理", romaji: "kanri", english: "Management", examples: [{ jp: "情報の 厳重な管理。", en: "Strict management of info.", romaji: "Jouhou no genjuu na kanri." }, { jp: "管理 人。", en: "Manager/Caretaker.", romaji: "Kanri nin." }] },
      { japanese: "セキュリティ", romaji: "sekyuriti", english: "Security", examples: [{ jp: "セキュリティを 高める。", en: "Raise security.", romaji: "Sekyuriti wo takameru." }, { jp: "情報 セキュリティ。", en: "Information security.", romaji: "Jouhou sekyuriti." }] },
      { japanese: "個人情報", romaji: "kojin jouhou", english: "Personal information", examples: [{ jp: "個人情報を 守る。", en: "Protect personal information.", romaji: "Kojin jouhou wo mamoru." }, { jp: "個人 情報流出。", en: "Information leak.", romaji: "Kojin jouhou ryuushutsu." }] },
      { japanese: "漏洩", romaji: "rouei", english: "Leakage", examples: [{ jp: "情報の 漏洩を防ぐ。", en: "Prevent information leak.", romaji: "Jouhou no rouei wo fusegu." }, { jp: "機密 漏洩。", en: "Confidential leak.", romaji: "Kimitsu rouei." }] },
      { japanese: "拡散", romaji: "kakusan", english: "Diffusion/Going viral", examples: [{ jp: "情報が ネットで拡散。", en: "Information spreads on net.", romaji: "Jouhou ga netto de kakusan." }, { jp: "拡散 希望。", en: "Please share/RT.", romaji: "Kakusan kibou." }] },
      { japanese: "炎上", romaji: "enjou", english: "Flaming (Internet)", examples: [{ jp: "ＳＮＳが 炎上する。", en: "SNS gets flamed.", romaji: "Esu-enu-esu ga enjou suru." }, { jp: "不適切発言で 炎上。", en: "Flamed for improper remark.", romaji: "Futekisetsu hatsugen de enjou." }] },
      { japanese: "批判", romaji: "hihan", english: "Criticism", examples: [{ jp: "ネット上の 批判。", en: "Criticism on the net.", romaji: "Netto-jou no hihan." }, { jp: "批判的な コメント。", en: "Critical comment.", romaji: "Hihanteki na komento." }] },
      { japanese: "誹謗中傷", romaji: "hibou chuushou", english: "Slander/Libel", examples: [{ jp: "誹謗中傷を やめる。", en: "Stop slandering.", romaji: "Hibou chuushou wo yameru." }, { jp: "名誉 毀損。", en: "Defamation.", romaji: "Meiyo kison." }] },
      { japanese: "交流", romaji: "kouryuu", english: "Interaction/Networking", examples: [{ jp: "ＳＮＳでの 交流。", en: "Interaction on SNS.", romaji: "Esu-enu-esu de no kouryuu." }, { jp: "幅広い 交流。", en: "Wide interaction.", romaji: "Habahiroi kouryuu." }] },
      { japanese: "信頼", romaji: "shinrai", english: "Trust", examples: [{ jp: "情報の 信頼性。", en: "Reliability of info.", romaji: "Jouhou no shinraisei." }, { jp: "信頼できる ソース。", en: "Reliable source.", romaji: "Shinrai dekiru soosu." }] },
      { japanese: "確認", romaji: "kakunin", english: "Verification", examples: [{ jp: "事実を 確認する。", en: "Confirm the facts.", romaji: "Jijitsu wo kakunin suru." }, { jp: "本人 確認。", en: "Identity verification.", romaji: "Honnin kakunin." }] },
      { japanese: "広告", romaji: "koukoku", english: "Advertisement", examples: [{ jp: "ネット 広告。", en: "Online ad.", romaji: "Netto koukoku." }, { jp: "広告 ブロック。", en: "Ad block.", romaji: "Koukoku burokku." }] },
      { japanese: "分析", romaji: "bunseki", english: "Analysis", examples: [{ jp: "アクセスを 分析する。", en: "Analyze access/traffic.", romaji: "Akusesu wo bunseki suru." }, { jp: "データ 分析。", en: "Data analysis.", romaji: "Deeta bunseki." }] },
      { japanese: "効率", romaji: "kouritsu", english: "Efficiency", examples: [{ jp: "効率的な 情報収集。", en: "Efficient info gathering.", romaji: "Kouritsuteki na jouhou shuushuu." }, { jp: "効率が 悪い。", en: "Inefficient.", romaji: "Kouritsu ga warui." }] },
      { japanese: "変化", romaji: "henka", english: "Change", examples: [{ jp: "急速な 変化。", en: "Rapid change.", romaji: "Kyuusoku na henka." }, { jp: "変化に ついていく。", en: "Keep up with change.", romaji: "Henka ni tsuiteiku." }] },
      { japanese: "影響", romaji: "eikyou", english: "Influence", examples: [{ jp: "社会的な 影響力。", en: "Social influence.", romaji: "Shakaiteki na eikyouryoku." }, { jp: "悪 影響を及ぼす。", en: "Have a bad influence.", romaji: "Akueilkyou wo oyobosu." }] },
      { japanese: "未来", romaji: "mirai", english: "Future", examples: [{ jp: "デジタルな 未来。", en: "Digital future.", romaji: "Dejitaru na mirai." }, { jp: "未来を 予測する。", en: "Predict the future.", romaji: "Mirai wo yosokusuru." }] }
    ]
  },
  {
    id: 75,
    level: "N3",
    title: "Final Review & Mastery",
    description: "A collection of advanced miscellaneous terms and summary vocabulary",
    words: [
      { japanese: "達成", romaji: "tassei", english: "Achievement", examples: [{ jp: "目標を 達成する。", en: "Achieve the goal.", romaji: "Mokuhyou wo tassei suru." }, { jp: "達成感に 浸る。", en: "Soak in a sense of achievement.", romaji: "Tasseikan ni hitaru." }] },
      { japanese: "克服", romaji: "kokufuku", english: "Overcoming", examples: [{ jp: "苦手なことを克服する。", en: "Overcome things one is bad at.", romaji: "Nigete na koto wo kokufuku suru." }, { jp: "困難を 克服。", en: "Overcoming difficulties.", romaji: "Konnan wo kokufuku." }] },
      { japanese: "上達", romaji: "joutatsu", english: "Improvement", examples: [{ jp: "スキルが 上達した。", en: "Skills improved.", romaji: "Sukiru ga joutatsu shita." }, { jp: "着実に 上達する。", en: "Improve steadily.", romaji: "Chakujitsu ni joutatsu suru." }] },
      { japanese: "成果", romaji: "seika", english: "Result/Fruit", examples: [{ jp: "努力の 成果。", en: "The fruit of effort.", romaji: "Doryoku no seika." }, { jp: "成果を 発揮する。", en: "Show results.", romaji: "Seika wo hakki suru." }] },
      { japanese: "向上", romaji: "koujou", english: "Elevation/Improvement", examples: [{ jp: "質の 向上。", en: "Improvement of quality.", romaji: "Shitsu no koujou." }, { jp: "向上心が ある。", en: "Be ambitious/strive for improvement.", romaji: "Koujoushin ga aru." }] },
      { japanese: "進歩", romaji: "shinpo", english: "Progress", examples: [{ jp: "飛躍的な 進歩。", en: "Leap forward in progress.", romaji: "Hiyakuteki na shinpo." }, { jp: "時代と 共に進歩する。", en: "Progress with the times.", romaji: "Jidai to tomo ni shinpo suru." }] },
      { japanese: "改善", romaji: "kaizen", english: "Improvement/Reform", examples: [{ jp: "不備を 改善する。", en: "Improve/fix flaws.", romaji: "Fubi wo kaizen suru." }, { jp: "環境の 改善。", en: "Betterment of environment.", romaji: "Kankyou no kaizen." }] },
      { japanese: "改革", romaji: "kaikaku", english: "Reform", examples: [{ jp: "抜本的な 改革。", en: "Drastic reform.", romaji: "Bapponteki na kaikaku." }, { jp: "意識の 改革。", en: "Reform of awareness.", romaji: "Ishiki no kaikaku." }] },
      { japanese: "挑戦", romaji: "chousen", english: "Challenge", examples: [{ jp: "高い壁に 挑戦する。", en: "Challenge a high wall.", romaji: "Takai kabe ni chousen suru." }, { jp: "さらなる 挑戦。", en: "Further challenge.", romaji: "Saranaru chousen." }] },
      { japanese: "意欲", romaji: "iyoku", english: "Will/Motivation", examples: [{ jp: "学習の 意欲。", en: "Will to study.", romaji: "Gakushuu no iyoku." }, { jp: "意欲が 湧く。", en: "Motivation springs up.", romaji: "Iyoku ga waku." }] },
      { japanese: "自信", romaji: "jishin", english: "Confidence", examples: [{ jp: "根拠のない 自信。", en: "Groundless confidence.", romaji: "Konkyo no nai jishin." }, { jp: "自分に 自信をもつ。", en: "Have confidence in oneself.", romaji: "Jibun ni jishin wo motsu." }] },
      { japanese: "勇気", romaji: "yuuki", english: "Courage", examples: [{ jp: "前に進む 勇気。", en: "Courage to move forward.", romaji: "Mae ni susumu yuuki." }, { jp: "勇気が 湧いてくる。", en: "Courage wells up.", romaji: "Yuuki ga waite kuru." }] },
      { japanese: "忍耐", romaji: "nintai", english: "Patience/Endurance", examples: [{ jp: "忍耐が 必要だ。", en: "Patience is necessary.", romaji: "Nintai ga hitsuyou da." }, { jp: "忍耐 強い人。", en: "Patient person.", romaji: "Nintaizuyoi hito." }] },
      { japanese: "努力", romaji: "doryoku", english: "Effort", examples: [{ jp: "陰の 努力。", en: "Hidden effort/Behind scenes.", romaji: "Kage no doryoku." }, { jp: "努力に 勝る天才なし。", en: "Effort beats genius.", romaji: "Doryoku ni masaru tensai nashi." }] },
      { japanese: "継続", romaji: "keizoku", english: "Continuation", examples: [{ jp: "継続は 力なり。", en: "Persistence is power.", romaji: "Keizoku wa chikara nari." }, { jp: "努力を 継続する。", en: "Continue making effort.", romaji: "Doryoku wo keizoku suru." }] },
      { japanese: "集中", romaji: "shuuchuu", english: "Concentration", examples: [{ jp: "一 点に集中する。", en: "Concentrate on one point.", romaji: "Itten ni shuuchuu suru." }, { jp: "驚異的な 集中力。", en: "Amazing concentration.", romaji: "Kyouiteki na shuuchuuryoku." }] },
      { japanese: "効率", romaji: "kouritsu", english: "Efficiency", examples: [{ jp: "時間 効率を上げる。", en: "Raise time efficiency.", romaji: "Jikan kouritsu wo ageru." }, { jp: "効率の 追求。", en: "Pursuit of efficiency.", romaji: "Kouritsu no tsuikyuu." }] },
      { japanese: "充実", romaji: "juujitsu", english: "Fulfillment", examples: [{ jp: "毎日の 充実。", en: "Fulfillment of every day.", romaji: "Mainichi no juujitsu." }, { jp: "内容の 充実を図る。", en: "Strive for substantial content.", romaji: "Naiyou no juujitsu wo hakaru." }] },
      { japanese: "満足", romaji: "manzoku", english: "Satisfaction", examples: [{ jp: "心から 満足する。", en: "Satisfied from the heart.", romaji: "Kokoro kara manzoku suru." }, { jp: "十分な 満足。", en: "Full satisfaction.", romaji: "Juubun na manzoku." }] },
      { japanese: "確信", romaji: "kakushin", english: "Conviction", examples: [{ jp: "勝利を 確信する。", en: "Be convinced of victory.", romaji: "Shouri wo kakushin suru." }, { jp: "強い 確信をもつ。", en: "Have a strong conviction.", romaji: "Tsuyoi kakushin wo motsu." }] },
      { japanese: "理想", romaji: "risou", english: "Ideal", examples: [{ jp: "高い 理想を掲げる。", en: "Set up high ideals.", romaji: "Takai risou wo kakageru." }, { jp: "理想と 現実のギャップ。", en: "Gap between ideal and reality.", romaji: "Risou to genjitsu no gyappu." }] },
      { japanese: "目的", romaji: "mokuteki", english: "Purpose", examples: [{ jp: "本来の 目的。", en: "The original purpose.", romaji: "Honrai no mokuteki." }, { jp: "目的に 向かって進む。", en: "Move towards the purpose.", romaji: "Mokuteki ni mukatte susumu." }] },
      { japanese: "展望", romaji: "tenbou", english: "Prospect/View", examples: [{ jp: "未来への 展望。", en: "Prospect for the future.", romaji: "Mirai e no tenbou." }, { jp: "明るい 展望を開く。", en: "Open up a bright prospect.", romaji: "Akarui tenbou wo hiraku." }] },
      { japanese: "確実", romaji: "kakujitsu", english: "Certainty", examples: [{ jp: "確実に 一歩ずつ。", en: "Suredly, step by step.", romaji: "Kakujitsu ni ippo zutsu." }, { jp: "確実な 方法。", en: "A certain/sure method.", romaji: "Kakujitsu na houhou." }] },
      { japanese: "平和", romaji: "heiwa", english: "Peace", examples: [{ jp: "末永い 平和。", en: "Lasting peace.", romaji: "Suenagai heiwa." }, { jp: "心の 平和を保つ。", en: "Maintain peace of mind.", romaji: "Kokoro no heiwa wo tamotsu." }] },
      { japanese: "尊重", romaji: "sonchou", english: "Respect/Esteem", examples: [{ jp: "多様性を 尊重する。", en: "Respect diversity.", romaji: "Tayousei wo sonchou suru." }, { jp: "他人の意見を尊重する。", en: "Respect others' opinions.", romaji: "Tanin no iken wo sonchou suru." }] },
      { japanese: "感謝", romaji: "kansha", english: "Gratitude", examples: [{ jp: "深い 感謝の気持ち。", en: "Deep feeling of gratitude.", romaji: "Fukai kansha no kimochi." }, { jp: "感謝を 込めて。", en: "With thanks.", romaji: "Kansha wo komete." }] },
      { japanese: "共感", romaji: "kyoukan", english: "Empathy", examples: [{ jp: "広く 共感を呼ぶ。", en: "Glean broad empathy.", romaji: "Hiroku kyoukan wo yobu." }, { jp: "心からの 共感。", en: "Heartfelt empathy.", romaji: "Kokoro kara no kyoukan." }] },
      { japanese: "発展", romaji: "hatten", english: "Development/Evolution", examples: [{ jp: "さらなる 発展を願う。", en: "Wish for further development.", romaji: "Saranaru hatten wo negau." }, { jp: "飛躍的な 発展。", en: "Leap forward development.", romaji: "Hiyakuteki na hatten." }] },
      { japanese: "世界", romaji: "sekai", english: "World", examples: [{ jp: "一つに なった世界。", en: "A world become one.", romaji: "Hitotsu ni natta sekai." }, { jp: "世界の 多様性を学ぶ。", en: "Learn world's diversity.", romaji: "Sekai no tayousei wo manabu." }] }
    ]
  }
];
