export const chunk11 = [
  {
    id: 51,
    level: "N3",
    title: "Abstract Logic & Philosophy",
    description: "Vocabulary for deep thoughts and logical reasoning",
    words: [
      { japanese: "理論", romaji: "riron", english: "Theory", examples: [{ jp: "理論的に 説明する。", en: "Explain theoretically.", romaji: "Riron teki ni setsumei suru." }, { jp: "新しい 理論を立てる。", en: "Establish a new theory.", romaji: "Atarashii riron wo tateru." }] },
      { japanese: "実際", romaji: "jissai", english: "Reality/Actually", examples: [{ jp: "実際は 違った。", en: "In reality, it was different.", romaji: "Jissai wa chigatta." }, { jp: "実際に やってみる。", en: "Try it in practice.", romaji: "Jissai ni yatte miru." }] },
      { japanese: "確認", romaji: "kakunin", english: "Confirmation", examples: [{ jp: "内容を 確認する。", en: "Confirm the contents.", romaji: "Naiyou wo kakunin suru." }, { jp: "最終 確認。", en: "Final check.", romaji: "Saishuu kakunin." }] },
      { japanese: "証拠", romaji: "shouko", english: "Evidence", examples: [{ jp: "証拠を 提示する。", en: "Present evidence.", romaji: "Shouko wo teiji suru." }, { jp: "決定的な 証拠。", en: "Decisive evidence.", romaji: "Ketteiteki na shouko." }] },
      { japanese: "原因", romaji: "gen'in", english: "Cause", examples: [{ jp: "事故の 原因を調べる。", en: "Investigate the cause of accident.", romaji: "Jiko no gen'in wo shiraberu." }, { jp: "原因は 不明です。", en: "The cause is unknown.", romaji: "Gen'in wa fumei desu." }] },
      { japanese: "結果", romaji: "kekka", english: "Result", examples: [{ jp: "試験の 結果。", en: "Exam results.", romaji: "Shiken no kekka." }, { jp: "努力の 結果。", en: "Result of effort.", romaji: "Doryoku no kekka." }] },
      { japanese: "解決", romaji: "kaiketsu", english: "Solution", examples: [{ jp: "問題を 解決する。", en: "Solve the problem.", romaji: "Mondai wo kaiketsu suru." }, { jp: "解決策を 探す。", en: "Look for a solution.", romaji: "Kaiketsusaku wo sagasu." }] },
      { japanese: "判断", romaji: "handan", english: "Judgment", examples: [{ jp: "正しい 判断。", en: "Correct judgment.", romaji: "Tadashii handan." }, { jp: "自分で 判断する。", en: "Judge for oneself.", romaji: "Jibun de handan suru." }] },
      { japanese: "分析", romaji: "bunseki", english: "Analysis", examples: [{ jp: "データを 分析する。", en: "Analyze data.", romaji: "Deeta wo bunseki suru." }, { jp: "分析 結果。", en: "Analysis results.", romaji: "Bunseki kekka." }] },
      { japanese: "対象", romaji: "taishou", english: "Target/Subject", examples: [{ jp: "調査の 対象。", en: "Subject of survey.", romaji: "Chousa no taishou." }, { jp: "子供が 対象の番組。", en: "Program aimed at kids.", romaji: "Kodomo ga taishou no bangumi." }] },
      { japanese: "目的", romaji: "mokuteki", english: "Purpose", examples: [{ jp: "来日の 目的。", en: "Purpose of visit to Japan.", romaji: "Rainichi no mokuteki." }, { jp: "目的を 達成する。", en: "Achieve the purpose.", romaji: "Mokuteki wo tassei suru." }] },
      { japanese: "目印", romaji: "mejirushi", english: "Landmark/Sign", examples: [{ jp: "あの木を目印にする。", en: "Use that tree as a mark.", romaji: "Ano ki wo mejirushi ni suru." }, { jp: "目印に 旗を立てる。", en: "Set a flag as a mark.", romaji: "Mejirushi ni hata wo tateru." }] },
      { japanese: "共通", romaji: "kyoutsuu", english: "Common", examples: [{ jp: "二人の 共通点。", en: "Commonality between two.", romaji: "Futari no kyoutsuuten." }, { jp: "共通の 趣味。", en: "Common hobby.", romaji: "Kyoutsuu no shumi." }] },
      { japanese: "特徴", romaji: "tokuchou", english: "Characteristic", examples: [{ jp: "彼の 特徴を言う。", en: "Describe his features.", romaji: "Kare no tokuchou wo iu." }, { jp: "大きな 特徴。", en: "Main characteristic.", romaji: "Ookina tokuchou." }] },
      { japanese: "変化", romaji: "henka", english: "Change", examples: [{ jp: "時代の 変化。", en: "Change of era.", romaji: "Jidai no henka." }, { jp: "変化に 乏しい。", en: "Lack of change.", romaji: "Henka ni toboushii." }] },
      { japanese: "意識", romaji: "ishiki", english: "Consciousness", examples: [{ jp: "意識が 高い。", en: "Highly aware.", romaji: "Ishiki ga takai." }, { jp: "意識を 失う。", en: "Lose consciousness.", romaji: "Ishiki wo ushinau." }] },
      { japanese: "価値", romaji: "kachi", english: "Value", examples: [{ jp: "価値が ある。", en: "It has value.", romaji: "Kachi ga aru." }, { jp: "価値観の 違い。", en: "Difference in values.", romaji: "Kachikan no chigai." }] },
      { japanese: "重要", romaji: "juuyou", english: "Important", examples: [{ jp: "重要な 書類。", en: "Important document.", romaji: "Juuyou na shorui." }, { jp: "最も 重要だ。", en: "It is most important.", romaji: "Mottomo juuyou da." }] },
      { japanese: "基本的", romaji: "kihonteki", english: "Basic", examples: [{ jp: "基本的な ルール。", en: "Basic rules.", romaji: "Kihonteki na ruuru." }, { jp: "基本的には 反対だ。", en: "Basically, I'm against it.", romaji: "Kihonteki ni wa hantai da." }] },
      { japanese: "程度", romaji: "teido", english: "Degree/Extent", examples: [{ jp: "ある程度の 知識。", en: "Knowledge to some extent.", romaji: "Aru teido no chishiki." }, { jp: "どの程度 ですか。", en: "To what degree?", romaji: "Dono teido desu ka." }] },
      { japanese: "内容", romaji: "naiyou", english: "Content", examples: [{ jp: "話の 内容。", en: "Content of the talk.", romaji: "Hanashi no naiyou." }, { jp: "内容が 濃い。", en: "Substantial content.", romaji: "Naiyou ga koi." }] },
      { japanese: "表面", romaji: "hyoumen", english: "Surface", examples: [{ jp: "表面を 滑らかにする。", en: "Smooth the surface.", romaji: "Hyoumen wo nameraka ni suru." }, { jp: "表面的な 理解。", en: "Superficial understanding.", romaji: "Hyoumen-teki na rikai." }] },
      { japanese: "反対", romaji: "hantai", english: "Opposition/Opposite", examples: [{ jp: "意見に 反対する。", en: "Oppose an opinion.", romaji: "Iken ni hantai suru." }, { jp: "反対 側。", en: "The opposite side.", romaji: "Hantai gawa." }] },
      { japanese: "賛成", romaji: "sansei", english: "Agreement", examples: [{ jp: "案に 賛成する。", en: "Agree with the plan.", romaji: "An ni sansei suru." }, { jp: "みんな 賛成だ。", en: "Everyone is in agreement.", romaji: "Minna sansei da." }] },
      { japanese: "論理", romaji: "ronri", english: "Logic", examples: [{ jp: "論理的な 思考。", en: "Logical thinking.", romaji: "Ronriteki na shikou." }, { jp: "論理が 飛躍する。", en: "Logic skips a step.", romaji: "Ronri ga hiyaku suru." }] },
      { japanese: "事実", romaji: "jijitsu", english: "Fact", examples: [{ jp: "事実を 認める。", en: "Acknowledge the fact.", romaji: "Jijitsu wo mitomeru." }, { jp: "衝撃的な 事実。", en: "Shocking fact.", romaji: "Shougekteki na jijitsu." }] },
      { japanese: "影響", romaji: "eikyou", english: "Influence/Effect", examples: [{ jp: "悪い 影響を受ける。", en: "Be negatively influenced.", romaji: "Warui eikyou wo ukeru." }, { jp: "影響力が ある。", en: "Has influence.", romaji: "Eikyouryoku ga aru." }] },
      { japanese: "関係", romaji: "kankei", english: "Relationship", examples: [{ jp: "良好な 関係。", en: "Good relationship.", romaji: "Ryoukou na kankei." }, { jp: "無 関係だ。", en: "It's unrelated.", romaji: "Mu kankei da." }] },
      { japanese: "絶対", romaji: "zettai", english: "Absolute/Definitely", examples: [{ jp: "絶対 秘密だ。", en: "Absolute secret.", romaji: "Zettai himitsu da." }, { jp: "絶対に 行く。", en: "Will definitely go.", romaji: "Zettai ni iku." }] },
      { japanese: "当然", romaji: "touzen", english: "Natural/Of course", examples: [{ jp: "当然の 結果だ。", en: "It's a natural result.", romaji: "Touzen no kekka da." }, { jp: "当然 知っている。", en: "Of course I know.", romaji: "Touzen shitteiru." }] }
    ]
  },
  {
    id: 52,
    level: "N3",
    title: "Environment & Ecology",
    description: "Vocabulary for nature and global environmental issues",
    words: [
      { japanese: "環境", romaji: "kankyou", english: "Environment", examples: [{ jp: "地球 環境を考える。", en: "Think of global environment.", romaji: "Chikyuu kankyou wo kangaeru." }, { jp: "環境に 優しい。", en: "Eco-friendly.", romaji: "Kankyou ni yasashii." }] },
      { japanese: "汚染", romaji: "osen", english: "Pollution", examples: [{ jp: "海洋 汚染。", en: "Marine pollution.", romaji: "Kaiyou osen." }, { jp: "空気が 汚染される。", en: "Air gets polluted.", romaji: "Kuuki ga osensareru." }] },
      { japanese: "破壊", romaji: "hakai", english: "Destruction", examples: [{ jp: "自然 破壊。", en: "Destruction of nature.", romaji: "Shizen hakai." }, { jp: "森林を 破壊する。", en: "Destroy forests.", romaji: "Shinrin wo hakai suru." }] },
      { japanese: "保護", romaji: "hogo", english: "Protection/Conservation", examples: [{ jp: "野生動物を 保護する。", en: "Protect wild animals.", romaji: "Yaseidoubutsu wo hogo suru." }, { jp: "環境 保護。", en: "Environmental conservation.", romaji: "Kankyou hogo." }] },
      { japanese: "資源", romaji: "shigen", english: "Resources", examples: [{ jp: "天然 資源。", en: "Natural resources.", romaji: "Tennen shigen." }, { jp: "資源を 節約する。", en: "Save resources.", romaji: "Shigen wo setsuyaku suru." }] },
      { japanese: "節約", romaji: "setsuyaku", english: "Economy/Saving", examples: [{ jp: "電気を 節約する。", en: "Save electricity.", romaji: "Denki wo setsuyaku suru." }, { jp: "家計の 節約。", en: "Saving in household budget.", romaji: "Kakei no setsuyaku." }] },
      { japanese: "再利用", romaji: "sairiyou", english: "Reuse", examples: [{ jp: "プラスチックを再利用する。", en: "Reuse plastic.", romaji: "Purasuchikku wo sairiyou suru." }, { jp: "水の 再利用。", en: "Water reuse.", romaji: "Mizu no sairiyou." }] },
      { japanese: "リサイクル", romaji: "risaikuru", english: "Recycle", examples: [{ jp: "ゴミを リサイクルする。", en: "Recycle trash.", romaji: "Gomi wo risaikuru suru." }, { jp: "リサイクル ショップ。", en: "Recycle shop.", romaji: "Risaikuru shoppu." }] },
      { japanese: "温暖化", romaji: "ondanka", english: "Global warming", examples: [{ jp: "地球 温暖化が進む。", en: "Global warming progresses.", romaji: "Chikyuu ondanka ga susumu." }, { jp: "温暖化 対策。", en: "Countermeasures for warming.", romaji: "Ondanka taisaku." }] },
      { japanese: "平均", romaji: "heikun", english: "Average", examples: [{ jp: "平均 気温。", en: "Average temperature.", romaji: "Heikun kion." }, { jp: "平均点より 高い。", en: "Higher than average score.", romaji: "Heikunten yori takai." }] },
      { japanese: "異常", romaji: "ijou", english: "Abnormal", examples: [{ jp: "異常な 暑さ。", en: "Abnormal heat.", romaji: "Ijou na atsusa." }, { jp: "異常を 感知する。", en: "Sense an abnormality.", romaji: "Ijou wo kanchi suru." }] },
      { japanese: "現象", romaji: "genshou", english: "Phenomenon", examples: [{ jp: "自然 現象。", en: "Natural phenomenon.", romaji: "Shizen genshou." }, { jp: "新しい 現象。", en: "A new phenomenon.", romaji: "Atarashii genshou." }] },
      { japanese: "発生", romaji: "hassei", english: "Outbreak/Occurrence", examples: [{ jp: "事故が 発生した。", en: "An accident occurred.", romaji: "Jiko ga hassei shita." }, { jp: "熱が 発生する。", en: "Heat is generated.", romaji: "Netsu ga hassei suru." }] },
      { japanese: "観察", romaji: "kansatsu", english: "Observation", examples: [{ jp: "鳥を 観察する。", en: "Observe birds.", romaji: "Tori wo kansatsu suru." }, { jp: "観察 日記。", en: "Observation diary.", romaji: "Kansatsu nikki." }] },
      { japanese: "記録", romaji: "kiroku", english: "Record", examples: [{ jp: "世界 記録。", en: "World record.", romaji: "Sekai kiroku." }, { jp: "毎日の 記録をつける。", en: "Keep a daily record.", romaji: "Mainichi no kiroku wo tsukeru." }] },
      { japanese: "被害", romaji: "higai", english: "Damage/Harm", examples: [{ jp: "台風の 被害。", en: "Typhoon damage.", romaji: "Taifuu no higai." }, { jp: "被害を 受ける。", en: "Suffer damage.", romaji: "Higai wo ukeru." }] },
      { japanese: "影響", romaji: "eikyou", english: "Influence", examples: [{ jp: "環境に 悪影響を与える。", en: "Negatively affect the environment.", romaji: "Kankyou ni akueikyou wo ataeru." }, { jp: "親の 影響。", en: "Influence of parents.", romaji: "Oya no eikyou." }] },
      { japanese: "対策", romaji: "taisaku", english: "Measure/Countermeasure", examples: [{ jp: "地震の 対策。", en: "Earthquake measures.", romaji: "Jishin no taisaku." }, { jp: "緊急 対策。", en: "Emergency measures.", romaji: "Kinkyuu taisaku." }] },
      { japanese: "改善", romaji: "kaizen", english: "Improvement", examples: [{ jp: "状況を 改善する。", en: "Improve the situation.", romaji: "Joukyou wo kaizen suru." }, { jp: "品質 改善。", en: "Quality improvement.", romaji: "Hinshitsu kaizen." }] },
      { japanese: "意識", romaji: "ishiki", english: "Awareness", examples: [{ jp: "環境 意識を高める。", en: "Raise environmental awareness.", romaji: "Kankyou ishiki wo takameru." }, { jp: "自覚 意識。", en: "Self-awareness.", romaji: "Jikaku ishiki." }] },
      { japanese: "自然", romaji: "shizen", english: "Nature", examples: [{ jp: "自然に 触れる。", en: "Be in touch with nature.", romaji: "Shizen ni fureru." }, { jp: "大 自然。", en: "The great outdoors.", romaji: "Dai shizen." }] },
      { japanese: "森林", romaji: "shinrin", english: "Forest", examples: [{ jp: "森林 浴をする。", en: "Do forest bathing.", romaji: "Shinrinyoku wo suru." }, { jp: "広大な 森林。", en: "Vast forest.", romaji: "Koudai na shinrin." }] },
      { japanese: "海洋", romaji: "kaiyou", english: "Ocean", examples: [{ jp: "海洋 生物。", en: "Marine life.", romaji: "Kaiyou seibutsu." }, { jp: "海洋 深層水。", en: "Deep sea water.", romaji: "Kaiyou shinsousui." }] },
      { japanese: "生物", romaji: "seibutsu", english: "Living creature", examples: [{ jp: "生物の 進化。", en: "Evolution of creatures.", romaji: "Seibutsu no shinka." }, { jp: "不思議な 生物。", en: "Mysterious creature.", romaji: "Fushigi na seibutsu." }] },
      { japanese: "エネルギー", romaji: "enerugii", english: "Energy", examples: [{ jp: "クリーン エネルギー。", en: "Clean energy.", romaji: "Kuriin enerugii." }, { jp: "エネルギーを 消費する。", en: "Consume energy.", romaji: "Enerugii wo shouhi suru." }] },
      { japanese: "節電", romaji: "setsuden", english: "Saving electricity", examples: [{ jp: "節電に 協力する。", en: "Cooperate in saving electricity.", romaji: "Setsuden ni kyouryoku suru." }, { jp: "節電 モード。", en: "Power-saving mode.", romaji: "Setsuden moodo." }] },
      { japanese: "削減", romaji: "sakugen", english: "Reduction/Cut", examples: [{ jp: "コストを 削減する。", en: "Reduce costs.", romaji: "Kosuto wo sakugen suru." }, { jp: "二酸化炭素の削減。", en: "CO2 reduction.", romaji: "Nisankatanso no sakugen." }] },
      { japanese: "放出", romaji: "houshutsu", english: "Emission/Release", examples: [{ jp: "ガスを 放出する。", en: "Emit gas.", romaji: "Gasu wo houshutsu suru." }, { jp: "熱を 放出する。", en: "Release heat.", romaji: "Netsu wo houshutsu suru." }] },
      { japanese: "持続可能", romaji: "jizokukanou", english: "Sustainable", examples: [{ jp: "持続可能な 社会。", en: "Sustainable society.", romaji: "Jizokukanou na shakai." }, { jp: "ＳＤＧｓ。", en: "Sustainable Development Goals.", romaji: "SDGs." }] },
      { japanese: "責任", romaji: "sekinin", english: "Responsibility", examples: [{ jp: "企業の 責任。", en: "Corporate responsibility.", romaji: "Kigyou no sekinin." }, { jp: "個人の 責任。", en: "Individual responsibility.", romaji: "Kojin no sekinin." }] }
    ]
  },
  {
    id: 53,
    level: "N3",
    title: "Society & Mass Media",
    description: "Vocabulary for news, journalism, and modern society",
    words: [
      { japanese: "社会", romaji: "shakai", english: "Society", examples: [{ jp: "現代 社会。", en: "Modern society.", romaji: "Gendai shakai." }, { jp: "社会 進出。", en: "Entering society.", romaji: "Shakai shinshutsu." }] },
      { japanese: "情報", romaji: "jouhou", english: "Information", examples: [{ jp: "情報を 集める。", en: "Collect information.", romaji: "Jouhou wo atsumeru." }, { jp: "個人 情報。", en: "Personal information.", romaji: "Kojin jouhou." }] },
      { japanese: "提供", romaji: "teikyou", english: "Provision/Offer", examples: [{ jp: "サービスを 提供する。", en: "Provide a service.", romaji: "Saabisu wo teikyou suru." }, { jp: "場所の 提供。", en: "Offering a space.", romaji: "Basho no teikyou." }] },
      { japanese: "普及", romaji: "fukyuu", english: "Spread/普及", examples: [{ jp: "スマホが 普及する。", en: "Smartphones spread.", romaji: "Sumaho ga fukyuu suru." }, { jp: "普及率。", en: "Spread/diffusion rate.", romaji: "Fukyuuritsu." }] },
      { japanese: "放送", romaji: "housou", english: "Broadcast", examples: [{ jp: "テレビ 放送。", en: "TV broadcast.", romaji: "Terebi housou." }, { jp: "生 放送。", en: "Live broadcast.", romaji: "Nama housou." }] },
      { japanese: "中継", romaji: "chuukei", english: "Relay (Broadcast)", examples: [{ jp: "スポーツ 中継。", en: "Sports relay/broadcast.", romaji: "Supootsu chuukei." }, { jp: "衛星 中継。", en: "Satellite relay.", romaji: "Eisei chuukei." }] },
      { japanese: "記事", romaji: "kiji", english: "Article", examples: [{ jp: "新聞の 記事。", en: "Newspaper article.", romaji: "Shinbun no kiji." }, { jp: "面白い 記事。", en: "Interesting article.", romaji: "Omoshiroi kiji." }] },
      { japanese: "雑誌", romaji: "zasshi", english: "Magazine", examples: [{ jp: "週刊 雑誌。", en: "Weekly magazine.", romaji: "Shuukan zasshi." }, { jp: "雑誌の 特集。", en: "Magazine feature.", romaji: "Zasshi no tokushuu." }] },
      { japanese: "新聞", romaji: "shinbun", english: "Newspaper", examples: [{ jp: "新聞を 読む。", en: "Read the newspaper.", romaji: "Shinbun wo yomu." }, { jp: "英字 新聞。", en: "English newspaper.", romaji: "Eiji shinbun." }] },
      { japanese: "広告", romaji: "koukoku", english: "Advertisement", examples: [{ jp: "テレビの 広告。", en: "TV ad.", romaji: "Terebi no koukoku." }, { jp: "広告を 出す。", en: "Put out an ad.", romaji: "Koukoku wo dasu." }] },
      { japanese: "宣伝", romaji: "senden", english: "Publicity/Advertising", examples: [{ jp: "新製品を 宣伝する。", en: "Advertise a new product.", romaji: "Shinseihin wo senden suru." }, { jp: "宣伝 活動。", en: "Publicity activities.", romaji: "Senden koudou." }] },
      { japanese: "注目", romaji: "chuumoku", english: "Attention", examples: [{ jp: "注目を 浴びる。", en: "Glean attention.", romaji: "Chuumoku wo abiru." }, { jp: "注目 すべき点。", en: "Point worth noting.", romaji: "Chuumoku subeki ten." }] },
      { japanese: "話題", romaji: "wadai", english: "Topic", examples: [{ jp: "最新の 話題。", en: "Latest topic.", romaji: "Saishin no wadai." }, { jp: "話題に なる。", en: "Become a topic of conversation.", romaji: "Wadai ni naru." }] },
      { japanese: "噂", romaji: "uwasa", english: "Rumor", examples: [{ jp: "変な 噂。", en: "Strange rumor.", romaji: "Hen na uwasa." }, { jp: "噂を 広める。", en: "Spread a rumor.", romaji: "Uwasa wo hiromeru." }] },
      { japanese: "真相", romaji: "shinsou", english: "Truth (of a matter)", examples: [{ jp: "事件の 真相。", en: "Truth of the case.", romaji: "Jiken no shinsou." }, { jp: "真相を 究明する。", en: "Investigate the truth.", romaji: "Shinsou wo kyuumei suru." }] },
      { japanese: "事実", romaji: "jijitsu", english: "Fact", examples: [{ jp: "事実を 隠す。", en: "Hide the fact.", romaji: "Jijitsu wo kakusu." }, { jp: "事実を 認める。", en: "Acknowledge the fact.", romaji: "Jijitsu wo mitomeru." }] },
      { japanese: "嘘", romaji: "uso", english: "Lie", examples: [{ jp: "嘘を つく。", en: "Tell a lie.", romaji: "Uso wo tsuku." }, { jp: "真っ赤な 嘘。", en: "A complete/downright lie.", romaji: "Makka na uso." }] },
      { japanese: "批判", romaji: "hihan", english: "Criticism", examples: [{ jp: "政府を 批判する。", en: "Criticize the government.", romaji: "Seifu wo hihan suru." }, { jp: "厳しい 批判。", en: "Harsh criticism.", romaji: "Kibishii hihan." }] },
      { japanese: "支持", romaji: "shiji", english: "Support", examples: [{ jp: "彼を 支持する。", en: "Support him.", romaji: "Kare wo shiji suru." }, { jp: "支持を 得る。", en: "Gain support.", romaji: "Shiji wo eru." }] },
      { japanese: "選挙", romaji: "senkyo", english: "Election", examples: [{ jp: "選挙に 行く。", en: "Go to vote in election.", romaji: "Senkyo ni iku." }, { jp: "選挙 活動。", en: "Election activities.", romaji: "Senkyo koudou." }] },
      { japanese: "投票", romaji: "touhyou", english: "Voting", examples: [{ jp: "清き一票を 投票する。", en: "Cast an honest vote.", romaji: "Kiyoki ippyou wo touhyou suru." }, { jp: "投票日。", en: "Voting day.", romaji: "Touhyoubi." }] },
      { japanese: "権利", romaji: "kenri", english: "Right", examples: [{ jp: "投票の 権利。", en: "Right to vote.", romaji: "Touhyou no kenri." }, { jp: "基本的 人権。", en: "Basic human rights.", romaji: "Kihonteki jinken." }] },
      { japanese: "義務", romaji: "gimu", english: "Duty", examples: [{ jp: "納税の 義務。", en: "Duty of paying taxes.", romaji: "Nouzei no gimu." }, { jp: "義務を 果たす。", en: "Fulfill a duty.", romaji: "Gimu wo hatasu." }] },
      { japanese: "法律", romaji: "houritsu", english: "Law", examples: [{ jp: "法律を 守る。", en: "Obey the law.", romaji: "Houritsu wo mamoru." }, { jp: "新しい 法律。", en: "A new law.", romaji: "Atarashii houritsu." }] },
      { japanese: "制度", romaji: "seido", english: "System", examples: [{ jp: "教育 制度。", en: "Education system.", romaji: "Kyouiku seido." }, { jp: "新しい 制度を導入する。", en: "Introduce a new system.", romaji: "Atarashii seido wo dounyuu suru." }] },
      { japanese: "反映", romaji: "han'ei", english: "Reflection", examples: [{ jp: "民意を 反映する。", en: "Reflect public opinion.", romaji: "Min'ei wo han'ei suru." }, { jp: "鏡に 反映する。", en: "Reflect in mirror.", romaji: "Kagami ni han'ei suru." }] },
      { japanese: "影響", romaji: "eikyou", english: "Influence", examples: [{ jp: "社会に 影響を与える。", en: "Give influence to society.", romaji: "Shakai ni eikyou wo ataeru." }, { jp: "影響を 受ける。", en: "Be influenced.", romaji: "Eikyou wo ukeru." }] },
      { japanese: "格差", romaji: "kakusa", english: "Disparity/Gap", examples: [{ jp: "貧富の 格差。", en: "Gap between rich and poor.", romaji: "Hinpu no kakusa." }, { jp: "格差を なくす。", en: "Elminate disparity.", romaji: "Kakusa wo nakusu." }] },
      { japanese: "問題", romaji: "mondai", english: "Problem/Issue", examples: [{ jp: "深刻な 社会問題。", en: "Serious social issue.", romaji: "Shinkoku na shakaimondai." }, { jp: "問題を 提示する。", en: "Present a problem.", romaji: "Mondai wo teiji suru." }] },
      { japanese: "解決", romaji: "kaiketsu", english: "Solution", examples: [{ jp: "平和的に 解決する。", en: "Solve peacefully.", romaji: "Heiwateki ni kaiketsu suru." }, { jp: "解決の 糸口。", en: "Clue to a solution.", romaji: "Kaiketsu no itoguchi." }] }
    ]
  },
  {
    id: 54,
    level: "N3",
    title: "Technology & Communications",
    description: "Vocabulary for computing, IT, and digital world",
    words: [
      { japanese: "技術", romaji: "gijutsu", english: "Technology", examples: [{ jp: "高度な 技術。", en: "Advanced technology.", romaji: "Koudou na gijutsu." }, { jp: "技術を 習得する。", en: "Acquire a skill/tech.", romaji: "Gijutsu wo shuutoku suru." }] },
      { japanese: "開発", romaji: "kaihatsu", english: "Development", examples: [{ jp: "システムを 開発する。", en: "Develop a system.", romaji: "Shisutemu wo kaihatsu suru." }, { jp: "新製品の開発。", en: "New product development.", romaji: "Shinseihin no kaihatsu." }] },
      { japanese: "機能", romaji: "kinou", english: "Function", examples: [{ jp: "最新の 機能。", en: "The latest functions.", romaji: "Saishin no kinou." }, { jp: "機能が 停止する。", en: "Functions stop.", romaji: "Kinou ga teishi suru." }] },
      { japanese: "性能", romaji: "seinou", english: "Performance", examples: [{ jp: "高い 性能。", en: "High performance.", romaji: "Takai seinou." }, { jp: "性能を 比較する。", en: "Compare performance.", romaji: "Seinou wo hikaku suru." }] },
      { japanese: "操作", romaji: "sousa", english: "Operation", examples: [{ jp: "機械を 操作する。", en: "Operate a machine.", romaji: "Kikai wo sousa suru." }, { jp: "操作 方法。", en: "Operating method.", romaji: "Sousa houhou." }] },
      { japanese: "変換", romaji: "henkan", english: "Conversion", examples: [{ jp: "漢字に 変換する。", en: "Convert into Kanji.", romaji: "Kanji ni henkan suru." }, { jp: "エネルギーの 変換。", en: "Energy conversion.", romaji: "Enerugii no henkan." }] },
      { japanese: "更新", romaji: "koushin", english: "Update/Renewal", examples: [{ jp: "ホームページを 更新する。", en: "Update a homepage.", romaji: "Hoomupeeji wo koushin suru." }, { jp: "免許の 更新。", en: "License renewal.", romaji: "Menkyo no koushin." }] },
      { japanese: "削除", romaji: "sakujo", english: "Deletion", examples: [{ jp: "データを 削除する。", en: "Delete data.", romaji: "Deeta wo sakujo suru." }, { jp: "名簿から 削除。", en: "Remove from list.", romaji: "Meibo kara sakujo." }] },
      { japanese: "保存", romaji: "hozon", english: "Save/Preservation", examples: [{ jp: "ファイルを 保存する。", en: "Save a file.", romaji: "Fairu wo hozon suru." }, { jp: "伝統の 保存。", en: "Preservation of tradition.", romaji: "Dentou no hozon." }] },
      { japanese: "接続", romaji: "setsuzoku", english: "Connection", examples: [{ jp: "ネットに 接続する。", en: "Connect to the net.", romaji: "Netto ni setsuzoku suru." }, { jp: "接続が 悪い。", en: "The connection is bad.", romaji: "Setsuzoku ga warui." }] },
      { japanese: "検索", romaji: "kensaku", english: "Search", examples: [{ jp: "キーワードで 検索する。", en: "Search with keywords.", romaji: "Kiiwaado de kensaku suru." }, { jp: "検索 サイト。", en: "Search site.", romaji: "Kensaku saito." }] },
      { japanese: "管理", romaji: "kanri", english: "Management", examples: [{ jp: "パスワードを 管理する。", en: "Manage passwords.", romaji: "Pasuwaado wo kanri suru." }, { jp: "自己 管理。", en: "Self-management.", romaji: "Jiko kanri." }] },
      { japanese: "通信", romaji: "tsuushin", english: "Communication", examples: [{ jp: "通信 速度。", en: "Communication speed.", romaji: "Tsuushin sokudo." }, { jp: "メールで 通信する。", en: "Communicate via mail.", romaji: "Meeru de tsuushin suru." }] },
      { japanese: "転送", romaji: "tensou", english: "Forwarding/Transfer", examples: [{ jp: "メールを 転送する。", en: "Forward an email.", romaji: "Meeru wo tensou suru." }, { jp: "データの 転送。", en: "Data transfer.", romaji: "Deeta no tensou." }] },
      { japanese: "設定", romaji: "settei", english: "Setting", examples: [{ jp: "初期 設定。", en: "Initial settings.", romaji: "Shoki settei." }, { jp: "温度を 設定する。", en: "Set the temperature.", romaji: "Ondou wo settei suru." }] },
      { japanese: "受信", romaji: "jushin", english: "Reception (Electronic)", examples: [{ jp: "メールを 受信する。", en: "Receive an email.", romaji: "Meeru wo jushin suru." }, { jp: "電波の 受信。", en: "Reception of signal.", romaji: "Denpa no jushin." }] },
      { japanese: "送信", romaji: "soushin", english: "Transmission (Electronic)", examples: [{ jp: "ファイルを 送信する。", en: "Send a file.", romaji: "Fairu wo soushin suru." }, { jp: "送信 完了。", en: "Transmission complete.", romaji: "Soushin kanryou." }] },
      { japanese: "暗号", romaji: "angou", english: "Cipher/Encryption", examples: [{ jp: "暗号を 解く。", en: "Decipher a code.", romaji: "Angou wo toku." }, { jp: "暗号化 されたデータ。", en: "Encrypted data.", romaji: "Angouka sareta deeta." }] },
      { japanese: "ウイルス", romaji: "uirusu", english: "Virus", examples: [{ jp: "コンピューター ウイルス。", en: "Computer virus.", romaji: "Konpyuuta uirusu." }, { jp: "ウイルスに 感染する。", en: "Be infected with virus.", romaji: "Uirusu ni kansen suru." }] },
      { japanese: "画面", romaji: "gamen", english: "Screen", examples: [{ jp: "画面を タップする。", en: "Tap the screen.", romaji: "Gamen wo tappu suru." }, { jp: "大 画面。", en: "Large screen.", romaji: "Oo gamen." }] },
      { japanese: "入力", romaji: "nyuuryoku", english: "Input", examples: [{ jp: "文字を 入力する。", en: "Input characters.", romaji: "Moji wo nyuuryoku suru." }, { jp: "入力ミス。", en: "Input error.", romaji: "Nyuuryoku misu." }] },
      { japanese: "出力", romaji: "shutsuryoku", english: "Output", examples: [{ jp: "データを 出力する。", en: "Output data.", romaji: "Deeta wo shutsuryoku suru." }, { jp: "プリンターの 出力。", en: "Printer output.", romaji: "Purintaa no shutsuryoku." }] },
      { japanese: "故障", romaji: "koshou", english: "Failure/Breakdown", examples: [{ jp: "パソコンが 故障した。", en: "PC broke down.", romaji: "Pasokon ga koshou shita." }, { jp: "故障中。", en: "Out of order.", romaji: "Koshouchuu." }] },
      { japanese: "修理", romaji: "shuuri", english: "Repair", examples: [{ jp: "スマホを 修理に出す。", en: "Send smartphone for repair.", romaji: "Sumaho wo shuuri ni dasu." }, { jp: "修理費。", en: "Repair cost.", romaji: "Shuuri hi." }] },
      { japanese: "予備", romaji: "yobi", english: "Spare/Reserve", examples: [{ jp: "予備の 電池。", en: "Spare batteries.", romaji: "Yobi no denchi." }, { jp: "予備 知識。", en: "Preliminary knowledge.", romaji: "Yobi chishiki." }] },
      { japanese: "効率", romaji: "kouritsu", english: "Efficiency", examples: [{ jp: "仕事の 効率を上げる。", en: "Raise work efficiency.", romaji: "Shigoto no kouritsu wo ageru." }, { jp: "効率的だ。", en: "It's efficient.", romaji: "Kouritsuteki da." }] },
      { japanese: "進歩", romaji: "shinpo", english: "Progress", examples: [{ jp: "技術が 進歩した。", en: "Technology progressed.", romaji: "Gijutsu ga shinpo shita." }, { jp: "日進月歩。", en: "Steady progress.", romaji: "Nisshingeppo." }] },
      { japanese: "未来", romaji: "mirai", english: "Future", examples: [{ jp: "明るい 未来。", en: "Bright future.", romaji: "Akarui mirai." }, { jp: "未来 都市。", en: "Futuristic city.", romaji: "Mirai toshi." }] },
      { japanese: "便利", romaji: "benri", english: "Convenient", examples: [{ jp: "便利な 道具。", en: "Convenient tool.", romaji: "Benri na dougu." }, { jp: "不便を 解消する。", en: "Resolve inconvenience.", romaji: "Fuben wo kaishou suru." }] },
      { japanese: "活用", romaji: "katsuyou", english: "Practical use/Application", examples: [{ jp: "知識を 活用する。", en: "Utilize knowledge.", romaji: "Chishiki wo katsuyou suru." }, { jp: "有効 活用。", en: "Effective utilization.", romaji: "Yuukou katsuyou." }] }
    ]
  },
  {
    id: 55,
    level: "N3",
    title: "Emotions & Psychology",
    description: "Vocabulary for deep feelings and mental states",
    words: [
      { japanese: "感情", romaji: "kanjou", english: "Emotion/Feeling", examples: [{ jp: "感情を 抑える。", en: "Suppress emotions.", romaji: "Kanjou wo osaeru." }, { jp: "感情的な 人。", en: "Emotional person.", romaji: "Kanjouteki na hito." }] },
      { japanese: "気分", romaji: "kibun", english: "Mood/Feeling", examples: [{ jp: "気分が 悪い。", en: "Feel sick/In a bad mood.", romaji: "Kibun ga warui." }, { jp: "気分を 変える。", en: "Change one's mood.", romaji: "Kibun wo kaeru." }] },
      { japanese: "状態", romaji: "joutai", english: "State/Condition", examples: [{ jp: "健康 状態。", en: "Health condition.", romaji: "Kenkou joutai." }, { jp: "興奮 状態。", en: "State of excitement.", romaji: "Koufun joutai." }] },
      { japanese: "興奮", romaji: "koufun", english: "Excitement", examples: [{ jp: "興奮して 眠れない。", en: "Too excited to sleep.", romaji: "Koufunshite nemurenai." }, { jp: "興奮を 抑える。", en: "Calm down excitement.", romaji: "Koufun wo osaeru." }] },
      { japanese: "期待", romaji: "kitai", english: "Expectation", examples: [{ jp: "将来に 期待する。", en: "Expect (much) for future.", romaji: "Shourai ni kitai suru." }, { jp: "期待を 裏切る。", en: "Betray expectations.", romaji: "Kitai wo uragiru." }] },
      { japanese: "不安", romaji: "fuan", english: "Anxiety", examples: [{ jp: "将来が 不安だ。", en: "Uncertain about future.", romaji: "Shourai ga fuan da." }, { jp: "不安を 解消する。", en: "Resolve anxiety.", romaji: "Fuan wo kaishou suru." }] },
      { japanese: "心配", romaji: "shinpai", english: "Worry", examples: [{ jp: "家族を 心配する。", en: "Worry about family.", romaji: "Kazoku wo shinpai suru." }, { jp: "心配 ごと。", en: "A worry/concern.", romaji: "Shinpai goto." }] },
      { japanese: "恐怖", romaji: "kyoufu", english: "Fear/Terror", examples: [{ jp: "恐怖を 感じる。", en: "Feel fear.", romaji: "Kyoufu wo kanjiru." }, { jp: "恐怖 映画。", en: "Horror movie.", romaji: "Kyoufu eiga." }] },
      { japanese: "緊張", romaji: "kinjou", english: "Nervousness/Tension", examples: [{ jp: "スピーチで 緊張する。", en: "Be nervous at speech.", romaji: "Supiichi de kinjou suru." }, { jp: "緊張感が ある。", en: "There is tension.", romaji: "Kinjoukan ga aru." }] },
      { japanese: "驚き", romaji: "odoroki", english: "Surprise", examples: [{ jp: "驚きの ニュース。", en: "Surprising news.", romaji: "Odoroki no nyuusu." }, { jp: "驚きを 隠せない。", en: "Can't hide surprise.", romaji: "Odoroki wo kakusenai." }] },
      { japanese: "満足", romaji: "manzoku", english: "Satisfaction", examples: [{ jp: "結果に 満足する。", en: "Satisfied with result.", romaji: "Kekka ni manzoku suru." }, { jp: "自己 満足。", en: "Self-satisfaction.", romaji: "Jiko manzoku." }] },
      { japanese: "後悔", romaji: "koukai", english: "Regret", examples: [{ jp: "過去を 後悔する。", en: "Regret the past.", romaji: "Kako wo koukai suru." }, { jp: "後悔先に立たず。", en: "No use crying over spilled milk.", romaji: "Koukai saki ni tatazu." }] },
      { japanese: "勇気", romaji: "yuuki", english: "Courage", examples: [{ jp: "勇気を 出す。", en: "Muster courage.", romaji: "Yuuki wo dasu." }, { jp: "勇気ある 行動。", en: "Courageous action.", romaji: "Yuuki aru koudou." }] },
      { japanese: "自信", romaji: "jishin", english: "Confidence", examples: [{ jp: "自信が ある。", en: "Have confidence.", romaji: "Jishin ga aru." }, { jp: "自信を 失う。", en: "Lose confidence.", romaji: "Jishin wo ushinau." }] },
      { japanese: "絶望", romaji: "zetsubou", english: "Despair", examples: [{ jp: "絶望の 淵に立つ。", en: "Stand on brink of despair.", romaji: "Zetsubou no fuchi ni tatsu." }, { jp: "絶望的な 状況。", en: "Desperate situation.", romaji: "Zetsubouteki na joukyou." }] },
      { japanese: "希望", romaji: "kibou", english: "Hope", examples: [{ jp: "未来に 希望を持つ。", en: "Have hope in future.", romaji: "Mirai ni kibou wo motsu." }, { jp: "第一 希望。", en: "First choice/hope.", romaji: "Daiichi kibou." }] },
      { japanese: "感銘", romaji: "kanmei", english: "Impression/Moved", examples: [{ jp: "話に 感銘を受けた。", en: "Was deeply moved by the talk.", romaji: "Hanashi ni kanmei wo uketa." }, { jp: "感銘を 与える。", en: "Give a deep impression.", romaji: "Kanmei wo ataeru." }] },
      { japanese: "感動", romaji: "kandou", english: "Being moved", examples: [{ jp: "美しい景色に感動する。", en: "Moved by beautiful view.", romaji: "Utsukushii keshiki ni kandou suru." }, { jp: "感動的な 映画。", en: "Touching movie.", romaji: "Kandouteki na eiga." }] },
      { japanese: "同情", romaji: "doujou", english: "Sympathy", examples: [{ jp: "彼に 同情する。", en: "Sympathize with him.", romaji: "Kare ni doujou suru." }, { jp: "同情心。", en: "Sympathy/Compassion.", romaji: "Doujoushin." }] },
      { japanese: "共感", romaji: "kyoukan", english: "Empathy", examples: [{ jp: "歌詞に 共感する。", en: "Empathize with lyrics.", romaji: "Kashi ni kyoukan suru." }, { jp: "共感を 得る。", en: "Gain empathy.", romaji: "Kyoukan wo eru." }] },
      { japanese: "焦る", romaji: "aseru", english: "To be in a hurry/panic", examples: [{ jp: "時間がなくて 焦る。", en: "Panic because no time.", romaji: "Jikan ga nakute aseru." }, { jp: "焦らないで。", en: "Don't panic/hurry.", romaji: "Aseranaide." }] },
      { japanese: "落ち込む", romaji: "ochikomu", english: "To be depressed", examples: [{ jp: "失敗して 落ち込む。", en: "Get depressed after failure.", romaji: "Shippaishite ochikomu." }, { jp: "落ち込まないで。", en: "Don't be down.", romaji: "Ochikomanaide." }] },
      { japanese: "悩む", romaji: "nyamu", english: "To worry/troubled", examples: [{ jp: "進路に 悩む。", en: "Worry about future path.", romaji: "Shinro ni nayamu." }, { jp: "悩みごとを 相談する。", en: "Discuss worries.", romaji: "Nayamigoto wo soudan suru." }] },
      { japanese: "迷う", romaji: "mayou", english: "To be lost/hesitate", examples: [{ jp: "道に 迷う。", en: "Get lost.", romaji: "Michi ni mayou." }, { jp: "どれにしようか迷う。", en: "Hesitate which to pick.", romaji: "Dore ni shiyou ka mayou." }] },
      { japanese: "恨む", romaji: "uramu", english: "To resent", examples: [{ jp: "人を 恨む。", en: "Resent someone.", romaji: "Hito wo uramu." }, { jp: "恨みっこなし。", en: "No hard feelings.", romaji: "Uramikkoshi." }] },
      { japanese: "羨む", romaji: "urayamu", english: "To envy", examples: [{ jp: "成功を 羨む。", en: "Envy success.", romaji: "Seikou wo urayamu." }, { jp: "羨ましい 限りだ。", en: "I'm so envious.", romaji: "Urayamashii kagiri da." }] },
      { japanese: "憐れむ", romaji: "awaremu", english: "To pity", examples: [{ jp: "恵まれない人を憐れむ。", en: "Pity the unfortunate.", romaji: "Megumarenai hito wo awaremu." }, { jp: "憐れな 姿。", en: "Pitiable sight.", romaji: "Aware na sugata." }] },
      { japanese: "惜しむ", romaji: "oshimu", english: "To regret/value", examples: [{ jp: "別れを 惜しむ。", en: "Regret the parting.", romaji: "Wakare wo oshimu." }, { jp: "努力を 惜しまない。", en: "Spare no effort.", romaji: "Doryoku wo oshimani." }] },
      { japanese: "信頼", romaji: "shinrai", english: "Trust", examples: [{ jp: "友人を 信頼する。", en: "Trust a friend.", romaji: "Yuujin wo shinrai suru." }, { jp: "厚い 信頼。", en: "Deep trust.", romaji: "Atsui shinrai." }] },
      { japanese: "尊敬", romaji: "sonkei", english: "Respect", examples: [{ jp: "先生を 尊敬する。", en: "Respect the teacher.", romaji: "Sensei wo sonkei suru." }, { jp: "尊敬の 念。", en: "Feeling of respect.", romaji: "Sonkei no nen." }] }
    ]
  }
];
