export const chunk1 = [
  {
    id: 1,
    level: "N5",
    title: "Greetings & Basics",
    description: "Essential daily greetings and polite expressions",
    words: [
      { japanese: "おはよう", romaji: "ohayou", hinglish: "Shubh Prabhat", english: "Good morning", examples: [{ jp: "おはよう ございます。", en: "Good morning (polite).", romaji: "Ohayou gozaimasu." }, { jp: "おはよう、みんな。", en: "Good morning, everyone.", romaji: "Ohayou, minna." }] },
      { japanese: "こんにちは", romaji: "konnichiwa", hinglish: "Namaste / Hello", english: "Hello", examples: [{ jp: "こんにちは、元気？", en: "Hello, how are you?", romaji: "Konnichiwa, genki?" }, { jp: "先生、こんにちは。", en: "Hello, teacher.", romaji: "Sensei, konnichiwa." }] },
      { japanese: "こんばんは", romaji: "konbanwa", hinglish: "Shubh Sandhya", english: "Good evening", examples: [{ jp: "こんばんは、月がきれいですね。", en: "Good evening, the moon is beautiful.", romaji: "Konbanwa, tsuki ga kirei desu ne." }, { jp: "みなさん、こんばんは。", en: "Good evening, everyone.", romaji: "Minasan, konbanwa." }] },
      { japanese: "さようなら", romaji: "sayounara", hinglish: "Alvida", english: "Goodbye", examples: [{ jp: "さようなら、また明日。", en: "Goodbye, see you tomorrow.", romaji: "Sayounara, mata ashita." }, { jp: "先生、さようなら。", en: "Goodbye, teacher.", romaji: "Sensei, sayounara." }] },
      { japanese: "ありがとう", romaji: "arigatou", hinglish: "Dhanyawaad", english: "Thank you", examples: [{ jp: "ありがとう ございます。", en: "Thank you very much.", romaji: "Arigatou gozaimasu." }, { jp: "いろいろ ありがとう。", en: "Thank you for everything.", romaji: "Iroiro arigatou." }] },
      { japanese: "すみません", romaji: "sumimasen", hinglish: "Maaf kijiye", english: "Excuse me/Sorry", examples: [{ jp: "すみません、トイレはどこですか。", en: "Excuse me, where is the toilet?", romaji: "Sumimasen, toire wa doko desu ka." }, { jp: "遅れて すみません。", en: "Sorry for being late.", romaji: "Okurete sumimasen." }] },
      { japanese: "はい", romaji: "hai", hinglish: "Haan", english: "Yes", examples: [{ jp: "はい、そうです。", en: "Yes, that's right.", romaji: "Hai, sou desu." }, { jp: "はい、元気です。", en: "Yes, I am fine.", romaji: "Hai, genki desu." }] },
      { japanese: "いいえ", romaji: "iie", hinglish: "Nahi", english: "No", examples: [{ jp: "いいえ、違います。", en: "No, that's wrong.", romaji: "Iie, chigaimasu." }, { jp: "いいえ、結構です。", en: "No, thank you.", romaji: "Iie, kekkou desu." }] },
      { japanese: "お願いします", romaji: "onegaishimasu", english: "Please", examples: [{ jp: "これを お願いします。", en: "This one, please.", romaji: "Kore wo onegaishimasu." }, { jp: "よろしく お願いします。", en: "Nice to meet you.", romaji: "Yoroshiku onegaishimasu." }] },
      { japanese: "いただきます", romaji: "itadakimasu", english: "Bon appétit", examples: [{ jp: "では、いただきます。", en: "Well then, let's eat.", romaji: "Dewa, itadakimasu." }, { jp: "みんなで いただきます。", en: "Let's eat together.", romaji: "Minna de itadakimasu." }] },
      { japanese: "ごちそうさま", romaji: "gochisousama", english: "Thanks for the meal", examples: [{ jp: "ごちそうさまでした。", en: "Thank you for the meal.", romaji: "Gochisousama deshita." }, { jp: "美味しかった、ごちそうさま。", en: "It was delicious, thanks.", romaji: "Oishikatta, gochisousama." }] },
      { japanese: "いってきます", romaji: "ittekimasu", english: "I'm leaving", examples: [{ jp: "学校に いってきます。", en: "I'm going to school.", romaji: "Gakkou ni ittekimasu." }, { jp: "じゃあ、いってきます。", en: "Well, I'm off.", romaji: "Jaa, ittekimasu." }] },
      { japanese: "いってらっしゃい", romaji: "itterasshai", english: "Take care", examples: [{ jp: "気をつけて いってらっしゃい。", en: "Be careful, take care.", romaji: "Ki wo tsukete itterasshai." }, { jp: "はい、いってらっしゃい。", en: "Okay, see you.", romaji: "Hai, itterasshai." }] },
      { japanese: "ただいま", romaji: "tadaima", english: "I'm home", examples: [{ jp: "ただいま、帰りました。", en: "I'm home, I'm back.", romaji: "Tadaima, kaerimashita." }, { jp: "お母さん、ただいま。", en: "Mom, I'm home.", romaji: "Okaasan, tadaima." }] },
      { japanese: "おかえり", romaji: "okaeri", english: "Welcome back", examples: [{ jp: "おかえりなさい。", en: "Welcome back (polite).", romaji: "Okaerinasai." }, { jp: "おかえり、早かったね。", en: "Welcome back, you're early.", romaji: "Okaeri, hayakatta ne." }] },
      { japanese: "おやすみ", romaji: "oyasumi", english: "Good night", examples: [{ jp: "おやすみなさい。", en: "Good night (polite).", romaji: "Oyasuminasai." }, { jp: "また明日、おやすみ。", en: "See you tomorrow, good night.", romaji: "Mata ashita, oyasumi." }] },
      { japanese: "初めまして", romaji: "hajimemashite", english: "Nice to meet you", examples: [{ jp: "初めまして、田中です。", en: "Nice to meet you, I'm Tanaka.", romaji: "Hajimemashite, Tanaka desu." }, { jp: "初めまして、よろしく。", en: "Nice to meet you, regards.", romaji: "Hajimemashite, yoroshiku." }] },
      { japanese: "ようこそ", romaji: "youkoso", english: "Welcome", examples: [{ jp: "日本へ ようこそ。", en: "Welcome to Japan.", romaji: "Nihon e youkoso." }, { jp: "私の家へ ようこそ。", en: "Welcome to my home.", romaji: "Watashi no ie e youkoso." }] },
      { japanese: "元気", romaji: "genki", english: "Healthy/Fine", examples: [{ jp: "お元気ですか。", en: "How are you?", romaji: "Ogenki desu ka." }, { jp: "はい、元気です。", en: "Yes, I'm fine.", romaji: "Hai, genki desu." }] },
      { japanese: "名前", romaji: "namae", english: "Name", examples: [{ jp: "お名前は 何ですか。", en: "What is your name?", romaji: "Onamae wa nan desu ka." }, { jp: "名前を 書いてください。", en: "Please write your name.", romaji: "Namae wo kaite kudasai." }] },
      { japanese: "私", romaji: "watashi", english: "I / Me", examples: [{ jp: "私は 学生です。", en: "I am a student.", romaji: "Watashi wa gakusei desu." }, { jp: "これは 私の本です。", en: "This is my book.", romaji: "Kore wa watashi no hon desu." }] },
      { japanese: "あなた", romaji: "anata", english: "You", examples: [{ jp: "あなたは 誰ですか。", en: "Who are you?", romaji: "Anata wa dare desu ka." }, { jp: "これは あなたのですか。", en: "Is this yours?", romaji: "Kore wa anata no desu ka." }] },
      { japanese: "これ", romaji: "kore", english: "This", examples: [{ jp: "これは ペンです。", en: "This is a pen.", romaji: "Kore wa pen desu." }, { jp: "これを ください。", en: "Please give me this.", romaji: "Kore wo kudasai." }] },
      { japanese: "それ", romaji: "sore", english: "That", examples: [{ jp: "それは 何ですか。", en: "What is that?", romaji: "Sore wa nan desu ka." }, { jp: "それも いいですね。", en: "That is also good.", romaji: "Sore mo ii desu ne." }] },
      { japanese: "あれ", romaji: "are", english: "That (over there)", examples: [{ jp: "あれは 富士山です。", en: "That is Mt. Fuji.", romaji: "Are wa Fujisan desu." }, { jp: "あれを 見てください。", en: "Please look at that.", romaji: "Are wo mite kudasai." }] },
      { japanese: "どれ", romaji: "dore", english: "Which", examples: [{ jp: "あなたの傘は どれですか。", en: "Which one is your umbrella?", romaji: "Anata no kasa wa dore desu ka." }, { jp: "どれが 好きですか。", en: "Which one do you like?", romaji: "Dore ga suki desu ka." }] },
      { japanese: "ここ", romaji: "koko", english: "Here", examples: [{ jp: "ここは 教室です。", en: "Here is the classroom.", romaji: "Koko wa kyoushitsu desu." }, { jp: "ここに座ってください。", en: "Please sit here.", romaji: "Koko ni suwatte kudasai." }] },
      { japanese: "そこ", romaji: "soko", english: "There", examples: [{ jp: "そこは 危ないです。", en: "It is dangerous there.", romaji: "Soko wa abunai desu." }, { jp: "そこに 置いてください。", en: "Please put it there.", romaji: "Soko ni oite kudasai." }] },
      { japanese: "あそこ", romaji: "asoko", english: "Over there", examples: [{ jp: "あそこに 犬がいます。", en: "There is a dog over there.", romaji: "Asoko ni inu ga imasu." }, { jp: "トイレは あそこです。", en: "The toilet is over there.", romaji: "Toire wa asoko desu." }] },
      { japanese: "どこ", romaji: "doko", english: "Where", examples: [{ jp: "出身は どこですか。", en: "Where are you from?", romaji: "Shusshin wa doko desu ka." }, { jp: "ここは どこですか。", en: "Where is this place?", romaji: "Koko wa doko desu ka." }] }
    ]
  },
  {
    id: 2,
    level: "N5",
    title: "Numbers & Counting",
    description: "Numbers 1-10000 and basic counters",
    words: [
      { japanese: "一", romaji: "ichi", english: "One", examples: [{ jp: "一つ ください。", en: "Please give me one.", romaji: "Hitotsu kudasai." }, { jp: "一番です。", en: "It's number one.", romaji: "Ichiban desu." }] },
      { japanese: "二", romaji: "ni", english: "Two", examples: [{ jp: "二つ あります。", en: "There are two.", romaji: "Futatsu arimasu." }, { jp: "二人で 行きます。", en: "Going with two people.", romaji: "Futari de ikimasu." }] },
      { japanese: "三", romaji: "san", english: "Three", examples: [{ jp: "三日 かかります。", en: "It takes three days.", romaji: "Mikka kakarimasu." }, { jp: "三つ 買いました。", en: "I bought three.", romaji: "Mittsu kaimashita." }] },
      { japanese: "四", romaji: "yon", english: "Four", examples: [{ jp: "四人 います。", en: "There are four people.", romaji: "Yonin imasu." }, { jp: "四時です。", en: "It's 4 o'clock.", romaji: "Yoji desu." }] },
      { japanese: "五", romaji: "go", english: "Five", examples: [{ jp: "五つ お願いします。", en: "Five please.", romaji: "Itsutsu onegaishimasu." }, { jp: "五月五日。", en: "May 5th.", romaji: "Gogatsu itsuka." }] },
      { japanese: "六", romaji: "roku", english: "Six", examples: [{ jp: "六個 あります。", en: "There are six pieces.", romaji: "Rokko arimasu." }, { jp: "六階に あります。", en: "It's on the 6th floor.", romaji: "Rokkai ni arimasu." }] },
      { japanese: "七", romaji: "nana", english: "Seven", examples: [{ jp: "七時 半です。", en: "It's 7:30.", romaji: "Shichiji han desu." }, { jp: "七つ あります。", en: "There are seven.", romaji: "Nanatsu arimasu." }] },
      { japanese: "八", romaji: "hachi", english: "Eight", examples: [{ jp: "八百屋。", en: "Vegetable shop.", romaji: "Yaoya." }, { jp: "八つ 食べました。", en: "I ate eight.", romaji: "Yattsu tabemashita." }] },
      { japanese: "九", romaji: "kyuu", english: "Nine", examples: [{ jp: "九時 集合です。", en: "Meeting at 9.", romaji: "Kuji shuugou desu." }, { jp: "九つ あります。", en: "There are nine.", romaji: "Kokonotsu arimasu." }] },
      { japanese: "十", romaji: "juu", english: "Ten", examples: [{ jp: "十回 やりました。", en: "I did it 10 times.", romaji: "Jukkai yarimashita." }, { jp: "十個 ください。", en: "Ten pieces please.", romaji: "Jukko kudasai." }] },
      { japanese: "百", romaji: "hyaku", english: "Hundred", examples: [{ jp: "百円です。", en: "It's 100 yen.", romaji: "Hyaku en desu." }, { jp: "三百人。", en: "300 people.", romaji: "Sanbyaku nin." }] },
      { japanese: "千", romaji: "sen", english: "Thousand", examples: [{ jp: "千円札。", en: "1000 yen bill.", romaji: "Sen en satsu." }, { jp: "三千円です。", en: "It's 3000 yen.", romaji: "Sanzen en desu." }] },
      { japanese: "万", romaji: "man", english: "Ten Thousand", examples: [{ jp: "一万円。", en: "10,000 yen.", romaji: "Ichiman en." }, { jp: "百万人。", en: "One million people.", romaji: "Hyakuman nin." }] },
      { japanese: "円", romaji: "en", english: "Yen", examples: [{ jp: "これ、何円ですか。", en: "How many yen is this?", romaji: "Kore, nanen desu ka." }, { jp: "五千円。", en: "5000 yen.", romaji: "Gosen en." }] },
      { japanese: "個", romaji: "ko", english: "Piece (counter)", examples: [{ jp: "一個だけ。", en: "Just one piece.", romaji: "Ikko dake." }, { jp: "何個 ほしい？", en: "How many do you want?", romaji: "Nanko hoshii?" }] },
      { japanese: "回", romaji: "kai", english: "Times (counter)", examples: [{ jp: "一回 行きました。", en: "I went once.", romaji: "Ikkai ikimashita." }, { jp: "もう一回。", en: "One more time.", romaji: "Mou ikkai." }] },
      { japanese: "枚", romaji: "mai", english: "Flat object counter", examples: [{ jp: "シャツ二枚。", en: "Two shirts.", romaji: "Shatsu nimai." }, { jp: "紙 一枚。", en: "One sheet of paper.", romaji: "Kami ichimai." }] },
      { japanese: "台", romaji: "dai", english: "Machine counter", examples: [{ jp: "車 一台。", en: "One car.", romaji: "Kuruma ichidai." }, { jp: "パソコン二台。", en: "Two computers.", romaji: "Pasokon nidai." }] },
      { japanese: "歳", romaji: "sai", english: "Age counter", examples: [{ jp: "何歳ですか。", en: "How old are you?", romaji: "Nansai desu ka." }, { jp: "二十歳です。", en: "I'm 20 years old.", romaji: "Hatachi desu." }] },
      { japanese: "人", romaji: "nin", english: "People counter", examples: [{ jp: "何人ですか。", en: "How many people?", romaji: "Nannin desu ka." }, { jp: "外国人。", en: "Foreigner.", romaji: "Gaikokujin." }] },
      { japanese: "番", romaji: "ban", english: "Number/Order", examples: [{ jp: "一番線。", en: "Line 1.", romaji: "Ichibansen." }, { jp: "電話番号。", en: "Phone number.", romaji: "Denwa bangou." }] },
      { japanese: "半分", romaji: "hanbun", english: "Half", examples: [{ jp: "半分 食べる。", en: "Eat half.", romaji: "Hanbun taberu." }, { jp: "半分こ。", en: "Split in half.", romaji: "Hanbunko." }] },
      { japanese: "全部", romaji: "zenbu", english: "All", examples: [{ jp: "全部で いくら？", en: "How much in total?", romaji: "Zenbu de ikura?" }, { jp: "全部 好き。", en: "I like them all.", romaji: "Zenbu suki." }] },
      { japanese: "たくさん", romaji: "takusan", english: "Many/A lot", examples: [{ jp: "人が たくさん。", en: "Lots of people.", romaji: "Hito ga takusan." }, { jp: "たくさん 食べた。", en: "Ate a lot.", romaji: "Takusan tabeta." }] },
      { japanese: "少し", romaji: "sukoshi", english: "A little", examples: [{ jp: "少し 寒い。", en: "A little cold.", romaji: "Sukoshi samui." }, { jp: "お腹が 少し空いた。", en: "Little hungry.", romaji: "Onaka ga sukoshi suita." }] },
      { japanese: "いくつ", romaji: "ikutsu", english: "How many", examples: [{ jp: "いくつ ありますか。", en: "How many are there?", romaji: "Ikutsu arimasu ka." }, { jp: "おいくつですか。", en: "How old are you?", romaji: "Oikutsu desu ka." }] },
      { japanese: "いくら", romaji: "ikura", english: "How much", examples: [{ jp: "これは いくらですか。", en: "How much is this?", romaji: "Kore wa ikura desu ka." }, { jp: "全部で いくら。", en: "How much total.", romaji: "Zenbu de ikura." }] },
      { japanese: "大勢", romaji: "oozei", english: "Crowd of people", examples: [{ jp: "大勢の 人。", en: "Many people.", romaji: "Oozei no hito." }, { jp: "客が 大勢来た。", en: "Many guests came.", romaji: "Kyaku ga oozei kita." }] },
      { japanese: "少々", romaji: "shoushou", english: "A little (polite)", examples: [{ jp: "少々 お待ちください。", en: "Wait a moment please.", romaji: "Shoushou omachi kudasai." }, { jp: "塩を 少々入れる。", en: "Add a little salt.", romaji: "Shio wo shoushou ireru." }] },
      { japanese: "ゼロ", romaji: "zero", english: "Zero", examples: [{ jp: "ゼロから 始める。", en: "Start from zero.", romaji: "Zero kara hajimeru." }, { jp: "気温 ゼロ度。", en: "Zero degrees.", romaji: "Kion zero do." }] }
    ]
  },
  {
    id: 3,
    level: "N5",
    title: "Time & Calendar",
    description: "Days, months, time expressions, and duration",
    words: [
      { japanese: "今", romaji: "ima", english: "Now", examples: [{ jp: "今、何時ですか。", en: "What time is it now?", romaji: "Ima, nanji desu ka." }, { jp: "今 行きます。", en: "I'm coming now.", romaji: "Ima ikimasu." }] },
      { japanese: "今日", romaji: "kyou", english: "Today", examples: [{ jp: "今日は 暑いですね。", en: "It's hot today.", romaji: "Kyou wa atsui desu ne." }, { jp: "今日の 予定。", en: "Today's schedule.", romaji: "Kyou no yotei." }] },
      { japanese: "明日", romaji: "ashita", english: "Tomorrow", examples: [{ jp: "また 明日。", en: "See you tomorrow.", romaji: "Mata ashita." }, { jp: "明日は 雨です。", en: "Tomorrow will be rain.", romaji: "Ashita wa ame desu." }] },
      { japanese: "昨日", romaji: "kinou", english: "Yesterday", examples: [{ jp: "昨日は 日曜日でした。", en: "Yesterday was Sunday.", romaji: "Kinou wa nichiyoubi deshita." }, { jp: "昨日会いましたね。", en: "We met yesterday.", romaji: "Kinou aimashita ne." }] },
      { japanese: "毎日", romaji: "mainichi", english: "Every day", examples: [{ jp: "毎日 勉強します。", en: "I study every day.", romaji: "Mainichi benkyou shimasu." }, { jp: "毎日の 生活。", en: "Daily life.", romaji: "Mainichi no seikatsu." }] },
      { japanese: "朝", romaji: "asa", english: "Morning", examples: [{ jp: "朝 ご飯。", en: "Breakfast.", romaji: "Asa gohan." }, { jp: "朝 早いです。", en: "Morning is early.", romaji: "Asa hayai desu." }] },
      { japanese: "昼", romaji: "hiru", english: "Noon/Daytime", examples: [{ jp: "お昼 ご飯。", en: "Lunch.", romaji: "Ohiru gohan." }, { jp: "昼休み。", en: "Lunch break.", romaji: "Hiruyasumi." }] },
      { japanese: "夜", romaji: "yoru", english: "Night", examples: [{ jp: "夜 遅くまで。", en: "Until late at night.", romaji: "Yoru osuku made." }, { jp: "夜ご飯。", en: "Dinner.", romaji: "Yoru gohan." }] },
      { japanese: "朝ごはん", romaji: "asagohan", english: "Breakfast", examples: [{ jp: "朝ごはんを 食べる。", en: "Eat breakfast.", romaji: "Asagohan wo taberu." }, { jp: "朝ごはんは パンです。", en: "Breakfast is bread.", romaji: "Asagohan wa pan desu." }] },
      { japanese: "昼ごはん", romaji: "hirugohan", english: "Lunch", examples: [{ jp: "昼ごはんを 食べに行こう。", en: "Let's go eat lunch.", romaji: "Hirugohan wo tabe ni ikou." }, { jp: "おいしい 昼ごはん。", en: "Delicious lunch.", romaji: "Oishii hirugohan." }] },
      { japanese: "晩ごはん", romaji: "bangohan", english: "Dinner", examples: [{ jp: "晩ごはんは カレーです。", en: "Dinner is curry.", romaji: "Bangohan wa karee desu." }, { jp: "晩ごはんを 作る。", en: "Make dinner.", romaji: "Bangohan wo tsukuru." }] },
      { japanese: "午前", romaji: "gozen", english: "A.M.", examples: [{ jp: "午前 九時。", en: "9:00 AM.", romaji: "Gozen kuji." }, { jp: "午前中に。", en: "In the morning.", romaji: "Gozenchuu ni." }] },
      { japanese: "午後", romaji: "gogo", english: "P.M.", examples: [{ jp: "午後 二時。", en: "2:00 PM.", romaji: "Gogo niji." }, { jp: "午後から 雨。", en: "Rain from the afternoon.", romaji: "Gogo kara ame." }] },
      { japanese: "時", romaji: "ji", english: "Hour/Time", examples: [{ jp: "何時ですか。", en: "What time is it?", romaji: "Nanji desu ka." }, { jp: "時間。", en: "Time.", romaji: "Jikan." }] },
      { japanese: "分", romaji: "fun/pun", english: "Minute", examples: [{ jp: "五分 待って。", en: "Wait 5 minutes.", romaji: "Gofun matte." }, { jp: "十分。", en: "10 minutes.", romaji: "Juppun." }] },
      { japanese: "半", romaji: "han", english: "Half", examples: [{ jp: "三時 半。", en: "3:30.", romaji: "Sanji han." }, { jp: "半分。", en: "Half.", romaji: "Hanbun." }] },
      { japanese: "週", romaji: "shuu", english: "Week", examples: [{ jp: "今週。", en: "This week.", romaji: "Konshuu." }, { jp: "来週。", en: "Next week.", romaji: "Raishuu." }] },
      { japanese: "月", romaji: "tsuki/getsu", english: "Month/Moon", examples: [{ jp: "今月。", en: "This month.", romaji: "Kongetsu." }, { jp: "一か月。", en: "One month.", romaji: "Ikkagetsu." }] },
      { japanese: "年", romaji: "toshi/nen", english: "Year", examples: [{ jp: "今年。", en: "This year.", romaji: "Kotoshi." }, { jp: "来年。", en: "Next year.", romaji: "Rainen." }] },
      { japanese: "日曜日", romaji: "nichiyoubi", english: "Sunday", examples: [{ jp: "日曜日は 休みです。", en: "Sunday is a holiday.", romaji: "Nichiyoubi wa yasumi desu." }, { jp: "日曜大工。", en: "Weekend carpentry.", romaji: "Nichiyou daiku." }] },
      { japanese: "月曜日", romaji: "getsuyoubi", english: "Monday", examples: [{ jp: "月曜日から 仕事。", en: "Work from Monday.", romaji: "Getsuyoubi kara shigoto." }, { jp: "憂鬱な 月曜日。", en: "Blue Monday.", romaji: "Yuuutsu na getsuyoubi." }] },
      { japanese: "火曜日", romaji: "kayoubi", english: "Tuesday", examples: [{ jp: "火曜日は 燃えるゴミ。", en: "Tuesday is burnable trash.", romaji: "Kayoubi wa moeru gomi." }, { jp: "次の 火曜日。", en: "Next Tuesday.", romaji: "Tsugi no kayoubi." }] },
      { japanese: "水曜日", romaji: "suiyoubi", english: "Wednesday", examples: [{ jp: "水曜日は 早帰り。", en: "Leave early on Wednesday.", romaji: "Suiyoubi wa hayagaeri." }, { jp: "水曜の 午後。", en: "Wednesday afternoon.", romaji: "Suiyou no gogo." }] },
      { japanese: "木曜日", romaji: "mokuyoubi", english: "Thursday", examples: [{ jp: "木曜日は 会議。", en: "Meeting on Thursday.", romaji: "Mokuyoubi wa kaigi." }, { jp: "木曜の 朝。", en: "Thursday morning.", romaji: "Mokuyou no asa." }] },
      { japanese: "金曜日", romaji: "kinyoubi", english: "Friday", examples: [{ jp: "花金の 金曜日。", en: "TGIF Friday.", romaji: "Hanakin no kinyoubi." }, { jp: "金曜の 夜。", en: "Friday night.", romaji: "Kinyou no yoru." }] },
      { japanese: "土曜日", romaji: "doyoubi", english: "Saturday", examples: [{ jp: "土曜日は デート。", en: "Date on Saturday.", romaji: "Doyoubi wa deeto." }, { jp: "土曜の 昼。", en: "Saturday afternoon.", romaji: "Doyou no hiru." }] },
      { japanese: "誕生日", romaji: "tanjoubi", english: "Birthday", examples: [{ jp: "誕生日は いつ？", en: "When is your birthday?", romaji: "Tanjoubi wa itsu?" }, { jp: "誕生日 おめでとう。", en: "Happy Birthday.", romaji: "Tanjoubi omedetou." }] },
      { japanese: "休み", romaji: "yasumi", english: "Rest/Holiday", examples: [{ jp: "明日は 休みです。", en: "Tomorrow is a holiday.", romaji: "Ashita wa yasumi desu." }, { jp: "お休み なさい。", en: "Good night.", romaji: "Oyasumi nasai." }] },
      { japanese: "いつ", romaji: "itsu", english: "When", examples: [{ jp: "いつ 来ますか。", en: "When will you come?", romaji: "Itsu kimasu ka." }, { jp: "いつが良いですか。", en: "When is good?", romaji: "Itsu ga ii desu ka." }] },
      { japanese: "時計", romaji: "tokei", english: "Clock/Watch", examples: [{ jp: "時計を 見る。", en: "Look at the watch.", romaji: "Tokei wo miru." }, { jp: "新しい 時計。", en: "New watch.", romaji: "Atarashii tokei." }] }
    ]
  },
  {
    id: 4,
    level: "N5",
    title: "Family & People",
    description: "Terms for family members and people",
    words: [
      { japanese: "私", romaji: "watashi", english: "I", examples: [{ jp: "私は 田中です。", en: "I am Tanaka.", romaji: "Watashi wa Tanaka desu." }, { jp: "私の 家族。", en: "My family.", romaji: "Watashi no kazoku." }] },
      { japanese: "家族", romaji: "kazoku", english: "Family", examples: [{ jp: "家族は 四人です。", en: "Family of four.", romaji: "Kazoku wa yonin desu." }, { jp: "家族 写真。", en: "Family photo.", romaji: "Kazoku shashin." }] },
      { japanese: "父", romaji: "chichi", english: "Father (mine)", examples: [{ jp: "父は 会社員です。", en: "My father is an office worker.", romaji: "Chichi wa kaishain desu." }, { jp: "私の 父。", en: "My father.", romaji: "Watashi no chichi." }] },
      { japanese: "母", romaji: "haha", english: "Mother (mine)", examples: [{ jp: "母は 優しいです。", en: "My mother is kind.", romaji: "Haha wa yasashii desu." }, { jp: "母の 料理。", en: "Mother's cooking.", romaji: "Haha no ryouri." }] },
      { japanese: "お父さん", romaji: "otousan", english: "Father (others/polite)", examples: [{ jp: "お父さんは 元気？", en: "Is your father well?", romaji: "Otousan wa genki?" }, { jp: "お父さんと呼ぶ。", en: "Call him dad.", romaji: "Otousan to yobu." }] },
      { japanese: "お母さん", romaji: "okaasan", english: "Mother (others/polite)", examples: [{ jp: "お母さんに 聞く。", en: "Ask mother.", romaji: "Okaasan ni kiku." }, { jp: "お母さんの日。", en: "Mother's Day.", romaji: "Okaasan no hi." }] },
      { japanese: "兄", romaji: "ani", english: "Older brother (mine)", examples: [{ jp: "兄が 一人います。", en: "I have one older brother.", romaji: "Ani ga hitori imasu." }, { jp: "兄の 車。", en: "Brother's car.", romaji: "Ani no kuruma." }] },
      { japanese: "姉", romaji: "ane", english: "Older sister (mine)", examples: [{ jp: "姉は 結婚しています。", en: "My sister is married.", romaji: "Ane wa kekkon shite imasu." }, { jp: "姉と 買い物。", en: "Shopping with sister.", romaji: "Ane to kaimono." }] },
      { japanese: "弟", romaji: "otouto", english: "Younger brother", examples: [{ jp: "弟と 遊ぶ。", en: "Play with younger brother.", romaji: "Otouto to asobu." }, { jp: "可愛い 弟。", en: "Cute little brother.", romaji: "Kawaii otouto." }] },
      { japanese: "妹", romaji: "imouto", english: "Younger sister", examples: [{ jp: "妹は 学生です。", en: "My younger sister is a student.", romaji: "Imouto wa gakusei desu." }, { jp: "妹の 宿題。", en: "Sister's homework.", romaji: "Imouto no shukudai." }] },
      { japanese: "兄弟", romaji: "kyoudai", english: "Siblings", examples: [{ jp: "兄弟は いますか。", en: "Do you have siblings?", romaji: "Kyoudai wa imasu ka." }, { jp: "仲良い 兄弟。", en: "Close siblings.", romaji: "Nakayoi kyoudai." }] },
      { japanese: "男", romaji: "otoko", english: "Man/Male", examples: [{ jp: "男の 人。", en: "Man.", romaji: "Otoko no hito." }, { jp: "男の子。", en: "Boy.", romaji: "Otokonoko." }] },
      { japanese: "女", romaji: "onna", english: "Woman/Female", examples: [{ jp: "女の 人。", en: "Woman.", romaji: "Onna no hito." }, { jp: "女の子。", en: "Girl.", romaji: "Onnanoko." }] },
      { japanese: "人", romaji: "hito", english: "Person", examples: [{ jp: "あの 人は誰？", en: "Who is that person?", romaji: "Ano hito wa dare?" }, { jp: "いい 人。", en: "Good person.", romaji: "Ii hito." }] },
      { japanese: "子供", romaji: "kodomo", english: "Child", examples: [{ jp: "子供が 遊んでいる。", en: "Children are playing.", romaji: "Kodomo ga asonde iru." }, { jp: "子供の時。", en: "When I was a child.", romaji: "Kodomo no toki." }] },
      { japanese: "友達", romaji: "tomodachi", english: "Friend", examples: [{ jp: "友達と 会う。", en: "Meet a friend.", romaji: "Tomodachi to au." }, { jp: "親友。", en: "Best friend.", romaji: "Shinyuu." }] },
      { japanese: "大人", romaji: "otona", english: "Adult", examples: [{ jp: "大人に なる。", en: "Become an adult.", romaji: "Otona ni naru." }, { jp: "大人しい。", en: "Quiet/Mature.", romaji: "Otonashii." }] },
      { japanese: "彼", romaji: "kare", english: "He/Boyfriend", examples: [{ jp: "彼は 学生です。", en: "He is a student.", romaji: "Kare wa gakusei desu." }, { jp: "私の 彼。", en: "My boyfriend.", romaji: "Watashi no kare." }] },
      { japanese: "彼女", romaji: "kanojo", english: "She/Girlfriend", examples: [{ jp: "彼女は 綺麗です。", en: "She is beautiful.", romaji: "Kanojo wa kirei desu." }, { jp: "僕の 彼女。", en: "My girlfriend.", romaji: "Boku no kanojo." }] },
      { japanese: "誰", romaji: "dare", english: "Who", examples: [{ jp: "あれは 誰ですか。", en: "Who is that?", romaji: "Are wa dare desu ka." }, { jp: "誰か いますか。", en: "Is anyone there?", romaji: "Dareka imasu ka." }] },
      { japanese: "皆さん", romaji: "minasan", english: "Everyone", examples: [{ jp: "皆さん、こんにちは。", en: "Hello everyone.", romaji: "Minasan, konnichiwa." }, { jp: "皆さん 元気？", en: "Is everyone well?", romaji: "Minasan genki?" }] },
      { japanese: "名前", romaji: "namae", english: "Name", examples: [{ jp: "名前を 書く。", en: "Write name.", romaji: "Namae wo kaku." }, { jp: "名前を 呼ぶ。", en: "Call name.", romaji: "Namae wo yobu." }] },
      { japanese: "おじいさん", romaji: "ojiisan", english: "Grandfather", examples: [{ jp: "おじいさんは 元気。", en: "Grandpa is fine.", romaji: "Ojiisan wa genki." }, { jp: "優しい おじいさん。", en: "Kind grandfather.", romaji: "Yasashii ojiisan." }] },
      { japanese: "おばあさん", romaji: "obaasan", english: "Grandmother", examples: [{ jp: "おばあさんの 家。", en: "Grandma's house.", romaji: "Obaasan no ie." }, { jp: "おばあさんと話す。", en: "Talk to grandma.", romaji: "Obaasan to hanasu." }] },
      { japanese: "おじさん", romaji: "ojisan", english: "Uncle/Man", examples: [{ jp: "親切な おじさん。", en: "Kind uncle/man.", romaji: "Shinsetsu na ojisan." }, { jp: "おじさんの 車。", en: "Uncle's car.", romaji: "Ojisan no kuruma." }] },
      { japanese: "おばさん", romaji: "obasan", english: "Aunt/Woman", examples: [{ jp: "近所の おばさん。", en: "Neighbor aunt.", romaji: "Kinjo no obasan." }, { jp: "おばさんに 会う。", en: "Meet aunt.", romaji: "Obasan ni au." }] },
      { japanese: "結婚", romaji: "kekkon", english: "Marriage", examples: [{ jp: "結婚 しています。", en: "I am married.", romaji: "Kekkon shite imasu." }, { jp: "結婚式。", en: "Wedding ceremony.", romaji: "Kekkonshiki." }] },
      { japanese: "独身", romaji: "dokushin", english: "Single", examples: [{ jp: "まだ 独身です。", en: "Still single.", romaji: "Mada dokushin desu." }, { jp: "独身 生活。", en: "Single life.", romaji: "Dokushin seikatsu." }] },
      { japanese: "奥さん", romaji: "okusan", english: "Wife (polite)", examples: [{ jp: "田中さんの 奥さん。", en: "Mr. Tanaka's wife.", romaji: "Tanaka-san no okusan." }, { jp: "綺麗な 奥さん。", en: "Beautiful wife.", romaji: "Kirei na okusan." }] },
      { japanese: "ご主人", romaji: "goshujin", english: "Husband (polite)", examples: [{ jp: "ご主人は お仕事？", en: "Is your husband working?", romaji: "Goshujin wa oshigoto?" }, { jp: "ご主人も 一緒。", en: "Husband is together too.", romaji: "Goshujin mo issho." }] }
    ]
  },
  {
    id: 5,
    level: "N5",
    title: "Food & Drinks",
    description: "Common foods, drinks, and dining terms",
    words: [
      { japanese: "食べ物", romaji: "tabemono", english: "Food", examples: [{ jp: "好きな 食べ物。", en: "Favorite food.", romaji: "Suki na tabemono." }, { jp: "食べ物を 買う。", en: "Buy food.", romaji: "Tabemono wo kau." }] },
      { japanese: "飲み物", romaji: "nomimono", english: "Drink", examples: [{ jp: "飲み物は 何？", en: "What's the drink?", romaji: "Nomimono wa nani?" }, { jp: "冷たい 飲み物。", en: "Cold drink.", romaji: "Tsumetai nomimono." }] },
      { japanese: "ご飯", romaji: "gohan", english: "Rice/Meal", examples: [{ jp: "ご飯を 食べる。", en: "Eat rice/meal.", romaji: "Gohan wo taberu." }, { jp: "朝 ご飯。", en: "Breakfast.", romaji: "Asa gohan." }] },
      { japanese: "パン", romaji: "pan", english: "Bread", examples: [{ jp: "パンを 焼く。", en: "Toast bread.", romaji: "Pan wo yaku." }, { jp: "パン屋。", en: "Bakery.", romaji: "Pan ya." }] },
      { japanese: "魚", romaji: "sakana", english: "Fish", examples: [{ jp: "魚が 好きです。", en: "I like fish.", romaji: "Sakana ga suki desu." }, { jp: "魚 料理。", en: "Fish dish.", romaji: "Sakana ryouri." }] },
      { japanese: "肉", romaji: "niku", english: "Meat", examples: [{ jp: "肉を 食べる。", en: "Eat meat.", romaji: "Niku wo taberu." }, { jp: "牛肉。", en: "Beef.", romaji: "Gyuuniku." }] },
      { japanese: "卵", romaji: "tamago", english: "Egg", examples: [{ jp: "卵 焼き。", en: "Fried egg.", romaji: "Tamago yaki." }, { jp: "生卵。", en: "Raw egg.", romaji: "Namatamago." }] },
      { japanese: "野菜", romaji: "yasai", english: "Vegetable", examples: [{ jp: "野菜 サラダ。", en: "Vegetable salad.", romaji: "Yasai sarada." }, { jp: "野菜を 切る。", en: "Cut vegetables.", romaji: "Yasai wo kiru." }] },
      { japanese: "果物", romaji: "kudamono", english: "Fruit", examples: [{ jp: "果物が 美味しい。", en: "Fruit is delicious.", romaji: "Kudamono ga oishii." }, { jp: "季節の 果物。", en: "Seasonal fruit.", romaji: "Kisetsu no kudamono." }] },
      { japanese: "水", romaji: "mizu", english: "Water", examples: [{ jp: "水を ください。", en: "Water please.", romaji: "Mizu wo kudasai." }, { jp: "冷たい 水。", en: "Cold water.", romaji: "Tsumetai mizu." }] },
      { japanese: "お茶", romaji: "ocha", english: "Tea/Green Tea", examples: [{ jp: "お茶を 飲みますか。", en: "Will you drink tea?", romaji: "Ocha wo nomimasu ka." }, { jp: "温かい お茶。", en: "Warm tea.", romaji: "Atatakai ocha." }] },
      { japanese: "紅茶", romaji: "koucha", english: "Black tea", examples: [{ jp: "紅茶に ミルク。", en: "Milk in tea.", romaji: "Koucha ni miruku." }, { jp: "紅茶が 好き。", en: "I like black tea.", romaji: "Koucha ga suki." }] },
      { japanese: "牛乳", romaji: "gyuunyuu", english: "Milk", examples: [{ jp: "牛乳を 飲む。", en: "Drink milk.", romaji: "Gyuunyuu wo nomu." }, { jp: "牛乳パック。", en: "Milk carton.", romaji: "Gyuunyuu pakku." }] },
      { japanese: "ジュース", romaji: "juusu", english: "Juice", examples: [{ jp: "オレンジジュース。", en: "Orange juice.", romaji: "Orenji juusu." }, { jp: "ジュースを 買う。", en: "Buy juice.", romaji: "Juusu wo kau." }] },
      { japanese: "ビール", romaji: "biiru", english: "Beer", examples: [{ jp: "ビールで 乾杯。", en: "Cheers with beer.", romaji: "Biiru de kanpai." }, { jp: "冷えた ビール。", en: "Chilled beer.", romaji: "Hieta biiru." }] },
      { japanese: "お酒", romaji: "osake", english: "Alcohol/Sake", examples: [{ jp: "お酒は 飲みません。", en: "I don't drink alcohol.", romaji: "Osake wa nomimasen." }, { jp: "お酒が 強い。", en: "Strong with alcohol.", romaji: "Osake ga tsuyoi." }] },
      { japanese: "料理", romaji: "ryouri", english: "Cooking/Cuisine", examples: [{ jp: "日本 料理。", en: "Japanese cuisine.", romaji: "Nihon ryouri." }, { jp: "料理を 作る。", en: "Cook.", romaji: "Ryouri wo tsukuru." }] },
      { japanese: "レストラン", romaji: "resutoran", english: "Restaurant", examples: [{ jp: "レストランへ 行く。", en: "Go to restaurant.", romaji: "Resutoran e iku." }, { jp: "いい レストラン。", en: "Good restaurant.", romaji: "Ii resutoran." }] },
      { japanese: "甘い", romaji: "amai", english: "Sweet", examples: [{ jp: "甘い ケーキ。", en: "Sweet cake.", romaji: "Amai keeki." }, { jp: "このみかんは 甘い。", en: "This mandarin is sweet.", romaji: "Kono mikan wa amai." }] },
      { japanese: "辛い", romaji: "karai", english: "Spicy", examples: [{ jp: "辛い カレー。", en: "Spicy curry.", romaji: "Karai karee." }, { jp: "辛いのが 苦手。", en: "Not good with spicy.", romaji: "Karai no ga nigate." }] },
      { japanese: "塩", romaji: "shio", english: "Salt", examples: [{ jp: "塩を 取って。", en: "Pass the salt.", romaji: "Shio wo totte." }, { jp: "塩味。", en: "Salty taste.", romaji: "Shioaji." }] },
      { japanese: "砂糖", romaji: "satou", english: "Sugar", examples: [{ jp: "砂糖を 入れる。", en: "Put user.", romaji: "Satou wo ireru." }, { jp: "砂糖なし。", en: "Without sugar.", romaji: "Satou nashi." }] },
      { japanese: "醤油", romaji: "shouyu", english: "Soy sauce", examples: [{ jp: "醤油を かける。", en: "Pour soy sauce.", romaji: "Shouyu wo kakeru." }, { jp: "醤油ラーメン。", en: "Soy sauce ramen.", romaji: "Shouyu raamen." }] },
      { japanese: "美味しい", romaji: "oishii", english: "Delicious", examples: [{ jp: "とても 美味しい。", en: "Very delicious.", romaji: "Totemo oishii." }, { jp: "美味しい 店。", en: "Delicious shop.", romaji: "Oishii mise." }] },
      { japanese: "まずい", romaji: "mazui", english: "Bad tasting", examples: [{ jp: "これは まずい。", en: "This tastes bad.", romaji: "Kore wa mazui." }, { jp: "まずい 料理。", en: "Bad cooking.", romaji: "Mazui ryouri." }] },
      { japanese: "喫茶店", romaji: "kissaten", english: "Cafe/Coffee shop", examples: [{ jp: "喫茶店で 休む。", en: "Rest at a cafe.", romaji: "Kissaten de yasumu." }, { jp: "静かな 喫茶店。", en: "Quiet cafe.", romaji: "Shizuka na kissaten." }] },
      { japanese: "メニュー", romaji: "menyuu", english: "Menu", examples: [{ jp: "メニューを ください。", en: "Menu please.", romaji: "Menyuu wo kudasai." }, { jp: "メニューを 見る。", en: "Look at menu.", romaji: "Menyuu wo miru." }] },
      { japanese: "注文", romaji: "chuumon", english: "Order", examples: [{ jp: "注文 お願いします。", en: "Order please.", romaji: "Chuumon onegaishimasu." }, { jp: "注文が決まる。", en: "Decide order.", romaji: "Chuumon ga kimaru." }] },
      { japanese: "箸", romaji: "hashi", english: "Chopsticks", examples: [{ jp: "箸を 使う。", en: "Use chopsticks.", romaji: "Hashi wo tsukau." }, { jp: "割り箸。", en: "Disposable chopsticks.", romaji: "Waribashi." }] },
      { japanese: "皿", romaji: "sara", english: "Plate/Dish", examples: [{ jp: "皿を 洗う。", en: "Wash dishes.", romaji: "Sara wo arau." }, { jp: "皿に盛る。", en: "Serve on plate.", romaji: "Sara ni moru." }] }
    ]
  }
];
