// JLPT N1 Kanji Dataset (~160 kanji)
export const N1_KANJI_DATA = {
  classical: [
    { char: '儀', meaning: 'Ceremony / Rite', onyomi: 'gi', kunyomi: '-' },
    { char: '礼', meaning: 'Bow / Courtesy', onyomi: 'rei/rai', kunyomi: '-' },
    { char: '拝', meaning: 'Worship / Pray', onyomi: 'hai', kunyomi: 'oga' },
    { char: '奉', meaning: 'Dedicate / Offer', onyomi: 'hou/bu', kunyomi: 'tatematsu' },
    { char: '献', meaning: 'Offer / Dedicate', onyomi: 'ken/kon', kunyomi: '-' },
    { char: '恭', meaning: 'Respectful', onyomi: 'kyou', kunyomi: 'uyauya' },
    { char: '謙', meaning: 'Humble / Modest', onyomi: 'ken', kunyomi: 'herikuda' },
    { char: '譲', meaning: 'Yield / Defer', onyomi: 'jou', kunyomi: 'yuzu' },
    { char: '粛', meaning: 'Solemn / Quiet', onyomi: 'shuku', kunyomi: '-' },
    { char: '厳', meaning: 'Strict / Solemn', onyomi: 'gen/gon', kunyomi: 'kibi/ogo' },
    { char: '威', meaning: 'Majesty / Authority', onyomi: 'i', kunyomi: 'odo' },
    { char: '尊', meaning: 'Respect / Honor', onyomi: 'son', kunyomi: 'tatto/touto' },
    { char: '崇', meaning: 'Adore / Sublime', onyomi: 'suu', kunyomi: 'aga' },
    { char: '敬', meaning: 'Respect', onyomi: 'kei', kunyomi: 'uyama' },
    { char: '慕', meaning: 'Yearn / Admire', onyomi: 'bo', kunyomi: 'shita' },
    { char: '賓', meaning: 'Guest / Visitor', onyomi: 'hin', kunyomi: '-' },
    { char: '雅', meaning: 'Elegance / Grace', onyomi: 'ga', kunyomi: 'miyabi' },
    { char: '趣', meaning: 'Taste / Elegance', onyomi: 'shu', kunyomi: 'omomuki' },
    { char: '風', meaning: 'Wind / Style', onyomi: 'fuu', kunyomi: 'kaze' },
    { char: '粋', meaning: 'Chic / Essence', onyomi: 'sui', kunyomi: 'iki' }
  ],
  rare: [
    { char: '畏', meaning: 'Awe / Fear', onyomi: 'i', kunyomi: 'osore/kashiko' },
    { char: '朕', meaning: 'Imperial We', onyomi: 'chin', kunyomi: '-' },
    { char: '璽', meaning: 'Imperial Seal', onyomi: 'ji', kunyomi: '-' },
    { char: '勅', meaning: 'Imperial Decree', onyomi: 'choku', kunyomi: '-' },
    { char: '詔', meaning: 'Imperial Edict', onyomi: 'shou', kunyomi: 'mikotonori' },
    { char: '爵', meaning: 'Title / Rank', onyomi: 'shaku', kunyomi: '-' },
    { char: '侯', meaning: 'Marquis / Lord', onyomi: 'kou', kunyomi: '-' },
    { char: '伯', meaning: 'Count / Earl', onyomi: 'haku', kunyomi: '-' },
    { char: '卿', meaning: 'Minister / Sir', onyomi: 'kyou/kei', kunyomi: '-' },
    { char: '臣', meaning: 'Retainer / Subject', onyomi: 'shin/jin', kunyomi: '-' },
    { char: '摂', meaning: 'Absorb / Regent', onyomi: 'setsu', kunyomi: 'to' },
    { char: '顧', meaning: 'Look back / Consider', onyomi: 'ko', kunyomi: 'kaeri' },
    { char: '遂', meaning: 'Accomplish / Finally', onyomi: 'sui', kunyomi: 'to/tsu' },
    { char: '遷', meaning: 'Transition / Move', onyomi: 'sen', kunyomi: 'utsu' },
    { char: '遮', meaning: 'Block / Intercept', onyomi: 'sha', kunyomi: 'saegi' },
    { char: '遡', meaning: 'Trace back', onyomi: 'so', kunyomi: 'sakanobo' },
    { char: '遥', meaning: 'Far / Distant', onyomi: 'you', kunyomi: 'haru' },
    { char: '邂', meaning: 'Unexpected meeting', onyomi: 'kai', kunyomi: '-' },
    { char: '逅', meaning: 'Meeting', onyomi: 'kou', kunyomi: '-' },
    { char: '邁', meaning: 'Go forward', onyomi: 'mai', kunyomi: '-' }
  ],
  formal_legal: [
    { char: '勧', meaning: 'Recommend / Advise', onyomi: 'kan', kunyomi: 'susu' },
    { char: '誓', meaning: 'Swear / Vow', onyomi: 'sei', kunyomi: 'chika' },
    { char: '誘', meaning: 'Invite / Lure', onyomi: 'yuu', kunyomi: 'saso' },
    { char: '諮', meaning: 'Consult', onyomi: 'shi', kunyomi: 'haka' },
    { char: '諭', meaning: 'Admonish / Counsel', onyomi: 'yu', kunyomi: 'sato' },
    { char: '諾', meaning: 'Consent / Agree', onyomi: 'daku', kunyomi: '-' },
    { char: '謀', meaning: 'Plot / Strategy', onyomi: 'bou/mu', kunyomi: 'hakari' },
    { char: '謡', meaning: 'Chant / Noh Song', onyomi: 'you', kunyomi: 'utai' },
    { char: '譜', meaning: 'Musical score / Record', onyomi: 'fu', kunyomi: '-' },
    { char: '購', meaning: 'Purchase', onyomi: 'kou', kunyomi: '-' },
    { char: '贈', meaning: 'Give / Present', onyomi: 'zou/sou', kunyomi: 'oku' },
    { char: '賠', meaning: 'Compensate', onyomi: 'bai', kunyomi: '-' },
    { char: '賢', meaning: 'Wise / Clever', onyomi: 'ken', kunyomi: 'kashiko' },
    { char: '賜', meaning: 'Bestow / Grant', onyomi: 'shi', kunyomi: 'tamawa' },
    { char: '賦', meaning: 'Levy / Tribute', onyomi: 'fu', kunyomi: '-' },
    { char: '赦', meaning: 'Pardon / Forgive', onyomi: 'sha', kunyomi: '-' },
    { char: '赴', meaning: 'Proceed / Go to', onyomi: 'fu', kunyomi: 'omomu' },
    { char: '超', meaning: 'Exceed / Ultra', onyomi: 'chou', kunyomi: 'ko' },
    { char: '越', meaning: 'Surpass / Cross', onyomi: 'etsu', kunyomi: 'ko' },
    { char: '践', meaning: 'Practice / Step on', onyomi: 'sen', kunyomi: 'fu' }
  ],
  academic: [
    { char: '暫', meaning: 'Temporary / Brief', onyomi: 'zan', kunyomi: 'shibaraku' },
    { char: '漸', meaning: 'Gradually', onyomi: 'zen', kunyomi: '-' },
    { char: '濫', meaning: 'Overflow / Abuse', onyomi: 'ran', kunyomi: 'mida' },
    { char: '濃', meaning: 'Thick / Dense', onyomi: 'nou', kunyomi: 'ko' },
    { char: '潤', meaning: 'Moist / Enrich', onyomi: 'jun', kunyomi: 'uruo/uru' },
    { char: '澄', meaning: 'Clear / Pure', onyomi: 'chou', kunyomi: 'su' },
    { char: '瀬', meaning: 'Rapids / Shallows', onyomi: 'rai', kunyomi: 'se' },
    { char: '弊', meaning: 'Evil / Harm', onyomi: 'hei', kunyomi: '-' },
    { char: '懇', meaning: 'Sincere / Familiar', onyomi: 'kon', kunyomi: 'nengoro' },
    { char: '懲', meaning: 'Punish / Chasten', onyomi: 'chou', kunyomi: 'ko/kori' },
    { char: '憂', meaning: 'Grief / Anxiety', onyomi: 'yuu', kunyomi: 'ure/u' },
    { char: '憤', meaning: 'Indignation / Anger', onyomi: 'fun', kunyomi: 'ikidoo' },
    { char: '慰', meaning: 'Console / Comfort', onyomi: 'i', kunyomi: 'nagusa' },
    { char: '慎', meaning: 'Prudent / Careful', onyomi: 'shin', kunyomi: 'tsutsushi' },
    { char: '慨', meaning: 'Lament / Deplore', onyomi: 'gai', kunyomi: '-' },
    { char: '惰', meaning: 'Lazy / Inert', onyomi: 'da', kunyomi: '-' },
    { char: '愚', meaning: 'Foolish / Stupid', onyomi: 'gu', kunyomi: 'oro' },
    { char: '搾', meaning: 'Squeeze / Extract', onyomi: 'saku', kunyomi: 'shibo' },
    { char: '摘', meaning: 'Pick / Point out', onyomi: 'teki', kunyomi: 'tsu' },
    { char: '撤', meaning: 'Withdraw / Remove', onyomi: 'tetsu', kunyomi: '-' }
  ],
  literary: [
    { char: '叙', meaning: 'Narrate / Describe', onyomi: 'jo', kunyomi: '-' },
    { char: '唆', meaning: 'Incite / Abet', onyomi: 'sa', kunyomi: 'sosonoka' },
    { char: '喚', meaning: 'Summon / Call', onyomi: 'kan', kunyomi: 'wame' },
    { char: '嘆', meaning: 'Sigh / Lament', onyomi: 'tan', kunyomi: 'nage/naga' },
    { char: '噴', meaning: 'Erupt / Spout', onyomi: 'fun', kunyomi: 'fu' },
    { char: '嚇', meaning: 'Threaten / Intimidate', onyomi: 'kaku', kunyomi: 'odo' },
    { char: '囚', meaning: 'Prisoner / Captive', onyomi: 'shuu', kunyomi: 'tora' },
    { char: '塑', meaning: 'Model / Mold', onyomi: 'so', kunyomi: '-' },
    { char: '壇', meaning: 'Platform / Podium', onyomi: 'dan/tan', kunyomi: '-' },
    { char: '奔', meaning: 'Run fast / Dash', onyomi: 'hon', kunyomi: 'hashi' },
    { char: '妄', meaning: 'Delusion / Reckless', onyomi: 'mou/bou', kunyomi: '-' },
    { char: '妨', meaning: 'Hinder / Obstruct', onyomi: 'bou', kunyomi: 'samata' },
    { char: '嫉', meaning: 'Envy / Jealousy', onyomi: 'shitsu', kunyomi: 'sonemu' },
    { char: '嬉', meaning: 'Happy / Joy', onyomi: 'ki', kunyomi: 'ureshii' },
    { char: '寡', meaning: 'Few / Widow', onyomi: 'ka', kunyomi: '-' },
    { char: '寧', meaning: 'Rather / Tranquil', onyomi: 'nei', kunyomi: 'mushi' },
    { char: '屈', meaning: 'Bend / Yield', onyomi: 'kutsu', kunyomi: 'kaga' },
    { char: '峡', meaning: 'Gorge / Strait', onyomi: 'kyou', kunyomi: '-' },
    { char: '巧', meaning: 'Skillful / Clever', onyomi: 'kou', kunyomi: 'taku/uma' },
    { char: '幻', meaning: 'Illusion / Phantom', onyomi: 'gen', kunyomi: 'maboroshi' }
  ],
  nature_rare: [
    { char: '壌', meaning: 'Soil / Earth', onyomi: 'jou', kunyomi: 'tsuchi' },
    { char: '嵐', meaning: 'Storm', onyomi: 'ran', kunyomi: 'arashi' },
    { char: '崖', meaning: 'Cliff', onyomi: 'gai', kunyomi: 'gake' },
    { char: '窟', meaning: 'Cave / Cavern', onyomi: 'kutsu', kunyomi: 'iwaya' },
    { char: '渓', meaning: 'Mountain stream', onyomi: 'kei', kunyomi: 'tani' },
    { char: '瀑', meaning: 'Waterfall', onyomi: 'baku', kunyomi: '-' },
    { char: '霧', meaning: 'Fog / Mist', onyomi: 'mu', kunyomi: 'kiri' },
    { char: '霜', meaning: 'Frost', onyomi: 'sou', kunyomi: 'shimo' },
    { char: '露', meaning: 'Dew / Expose', onyomi: 'ro/rou', kunyomi: 'tsuyu' },
    { char: '雷', meaning: 'Thunder', onyomi: 'rai', kunyomi: 'kaminari' },
    { char: '稲', meaning: 'Rice plant', onyomi: 'tou', kunyomi: 'ine/ina' },
    { char: '穂', meaning: 'Ear of grain', onyomi: 'sui', kunyomi: 'ho' },
    { char: '繭', meaning: 'Cocoon', onyomi: 'ken', kunyomi: 'mayu' },
    { char: '蚕', meaning: 'Silkworm', onyomi: 'san', kunyomi: 'kaiko' },
    { char: '蛍', meaning: 'Firefly', onyomi: 'kei', kunyomi: 'hotaru' },
    { char: '蝶', meaning: 'Butterfly', onyomi: 'chou', kunyomi: '-' },
    { char: '鶴', meaning: 'Crane (bird)', onyomi: 'kaku', kunyomi: 'tsuru' },
    { char: '鷹', meaning: 'Hawk', onyomi: 'you', kunyomi: 'taka' },
    { char: '鯨', meaning: 'Whale', onyomi: 'gei', kunyomi: 'kujira' },
    { char: '麗', meaning: 'Beautiful / Lovely', onyomi: 'rei', kunyomi: 'ureeru/utsuku' }
  ],
  abstract_complex: [
    { char: '弥', meaning: 'All the more / Widely', onyomi: 'mi/bi', kunyomi: 'iya' },
    { char: '彙', meaning: 'Category / Collect', onyomi: 'i', kunyomi: '-' },
    { char: '循', meaning: 'Circulate / Follow', onyomi: 'jun', kunyomi: '-' },
    { char: '徹', meaning: 'Penetrate / Thorough', onyomi: 'tetsu', kunyomi: '-' },
    { char: '恣', meaning: 'Selfish / Arbitrary', onyomi: 'shi', kunyomi: 'hoshiimama' },
    { char: '悼', meaning: 'Mourn / Grieve', onyomi: 'tou', kunyomi: 'ita' },
    { char: '惜', meaning: 'Regret / Precious', onyomi: 'seki', kunyomi: 'o' },
    { char: '慈', meaning: 'Mercy / Kindness', onyomi: 'ji', kunyomi: 'itsuku' },
    { char: '憬', meaning: 'Yearn / Aspire', onyomi: 'kei', kunyomi: 'akoga' },
    { char: '戴', meaning: 'Receive / Crown', onyomi: 'tai', kunyomi: 'itada' },
    { char: '挫', meaning: 'Crush / Discourage', onyomi: 'za', kunyomi: 'kuji' },
    { char: '措', meaning: 'Dispose / Set aside', onyomi: 'so', kunyomi: 'o' },
    { char: '抄', meaning: 'Copy / Abstract', onyomi: 'shou', kunyomi: '-' },
    { char: '拓', meaning: 'Pioneer / Open up', onyomi: 'taku', kunyomi: 'hira' },
    { char: '拘', meaning: 'Arrest / Adhere to', onyomi: 'kou', kunyomi: 'kakawa' },
    { char: '拙', meaning: 'Clumsy / Unskilled', onyomi: 'setsu', kunyomi: 'tsutana' },
    { char: '括', meaning: 'Bundle / Include', onyomi: 'katsu', kunyomi: 'kuiku' },
    { char: '拷', meaning: 'Torture / Beat', onyomi: 'gou', kunyomi: '-' },
    { char: '抹', meaning: 'Erase / Wipe', onyomi: 'matsu', kunyomi: '-' },
    { char: '披', meaning: 'Open / Reveal', onyomi: 'hi', kunyomi: '-' }
  ],
  politics_war: [
    { char: '征', meaning: 'Conquer / Subjugate', onyomi: 'sei', kunyomi: '-' },
    { char: '伐', meaning: 'Fell / Attack', onyomi: 'batsu', kunyomi: 'ki/u' },
    { char: '討', meaning: 'Attack / Discuss', onyomi: 'tou', kunyomi: 'u' },
    { char: '衝', meaning: 'Collide / Clash', onyomi: 'shou', kunyomi: 'tsu' },
    { char: '撃', meaning: 'Attack / Strike', onyomi: 'geki', kunyomi: 'u' },
    { char: '陥', meaning: 'Fall / Collapse', onyomi: 'kan', kunyomi: 'ochii/otoshii' },
    { char: '陣', meaning: 'Battle formation', onyomi: 'jin', kunyomi: '-' },
    { char: '隊', meaning: 'Unit / Troop', onyomi: 'tai', kunyomi: '-' },
    { char: '兵', meaning: 'Soldier', onyomi: 'hei/hyou', kunyomi: '-' },
    { char: '衛', meaning: 'Defense / Guard', onyomi: 'ei', kunyomi: '-' },
    { char: '奪', meaning: 'Seize / Rob', onyomi: 'datsu', kunyomi: 'uba' },
    { char: '侵', meaning: 'Invade', onyomi: 'shin', kunyomi: 'oka' },
    { char: '略', meaning: 'Strategy / Abbreviate', onyomi: 'ryaku', kunyomi: '-' },
    { char: '覇', meaning: 'Hegemony / Champion', onyomi: 'ha', kunyomi: '-' },
    { char: '鎮', meaning: 'Suppress / Calm', onyomi: 'chin', kunyomi: 'shizu' },
    { char: '捕', meaning: 'Capture / Catch', onyomi: 'ho', kunyomi: 'to/tsuka' },
    { char: '縛', meaning: 'Bind / Restrain', onyomi: 'baku', kunyomi: 'shiba' },
    { char: '束', meaning: 'Bundle / Bind', onyomi: 'soku', kunyomi: 'taba' },
    { char: '紛', meaning: 'Confuse / Dispute', onyomi: 'fun', kunyomi: 'magi' },
    { char: '粛', meaning: 'Solemn / Purge', onyomi: 'shuku', kunyomi: '-' }
  ]
};

export const N1_EXAM_DATA = {
  easy: [
    { sentence: "*れいぎ*ただしい ひとです。", target: "礼", reading: "れい", options: ["礼", "儀", "敬", "謙"], translation: "They are a well-mannered person." },
    { sentence: "*あらし*が ちかづいて います。", target: "嵐", reading: "あらし", options: ["嵐", "霧", "雷", "霜"], translation: "A storm is approaching." },
    { sentence: "*つる*が とんで います。", target: "鶴", reading: "つる", options: ["鶴", "鷹", "蝶", "蛍"], translation: "A crane is flying." },
    { sentence: "かれは *けんそん*な ひとです。", target: "謙", reading: "けん", options: ["謙", "譲", "恭", "尊"], translation: "He is a humble person." },
    { sentence: "*まぼろし*を みました。", target: "幻", reading: "まぼろし", options: ["幻", "妄", "夢", "影"], translation: "I saw an illusion." }
  ],
  mid: [
    { sentence: "*ぜんじん*を たたえました。", target: "善", reading: "ぜん", options: ["善", "徳", "義", "賢"], translation: "We praised the virtuous person." },
    { sentence: "かれの *たくみ*な わざに おどろいた。", target: "巧", reading: "たくみ", options: ["巧", "拙", "粋", "雅"], translation: "I was amazed by his skillful technique." },
    { sentence: "*こうばい*した えいがの チケット。", target: "購", reading: "こう", options: ["購", "贈", "賠", "賜"], translation: "The movie ticket I purchased." },
    { sentence: "*しばらく* おまち ください。", target: "暫", reading: "しばらく", options: ["暫", "漸", "暮", "暗"], translation: "Please wait for a moment." },
    { sentence: "*くじら*を みに いきました。", target: "鯨", reading: "くじら", options: ["鯨", "鶴", "鷹", "蝶"], translation: "We went to see whales." }
  ],
  hard: [
    { sentence: "*こんしん*かいが ひらかれました。", target: "懇", reading: "こん", options: ["懇", "慰", "慎", "慨"], translation: "A social gathering was held." },
    { sentence: "てきを *せいふく* しました。", target: "征", reading: "せい", options: ["征", "伐", "討", "撃"], translation: "They conquered the enemy." },
    { sentence: "*ちか*って まもります。", target: "誓", reading: "ちか", options: ["誓", "諾", "誘", "諭"], translation: "I swear to protect." },
    { sentence: "*いゆう*を いたみます。", target: "悼", reading: "いた", options: ["悼", "惜", "慈", "憬"], translation: "We mourn the deceased." },
    { sentence: "この ほうりつは *てってい*されて います。", target: "徹", reading: "てつ", options: ["徹", "循", "撤", "貫"], translation: "This law is thoroughly enforced." }
  ],
  top_hard: [
    { sentence: "*ちん*ぷんかんぷんの しょうちょくです。", target: "詔", reading: "しょう", options: ["詔", "勅", "朕", "璽"], translation: "It is an incomprehensible imperial edict." },
    { sentence: "*はけん*を にぎる くにが あらわれた。", target: "覇", reading: "は", options: ["覇", "征", "略", "陥"], translation: "A hegemonic nation appeared." },
    { sentence: "ひとびとの *いきどお*りが たかまった。", target: "憤", reading: "いきどお", options: ["憤", "憂", "慨", "怒"], translation: "People's indignation grew." },
    { sentence: "*いなびかり*が はしった。", target: "雷", reading: "いなびかり", options: ["雷", "嵐", "霧", "露"], translation: "Lightning flashed across the sky." },
    { sentence: "*あいまい*な ひょうげんは さけましょう。", target: "曖", reading: "あいまい", options: ["曖", "昧", "朧", "暫"], translation: "Let's avoid ambiguous expressions." }
  ]
};
