// JLPT N1 Kanji Dataset (~160 kanji)
export const N1_KANJI_DATA = {
  abstract_psychological: [
    { char: '哀', meaning: 'Pathetic/Sorrow', onyomi: 'ai', kunyomi: 'awa' },
    { char: '曖', meaning: 'Ambiguous', onyomi: 'ai', kunyomi: '-' },
    { char: '畏', meaning: 'Fear/Awe', onyomi: 'i', kunyomi: 'oso/kashiko' },
    { char: '萎', meaning: 'Wither', onyomi: 'i', kunyomi: 'na' },
    { char: '僅', meaning: 'A wee bit', onyomi: 'kin', kunyomi: 'wazu' },
    { char: '慶', meaning: 'Jubilation', onyomi: 'kei', kunyomi: '-' },
    { char: '倹', meaning: 'Frugal', onyomi: 'ken', kunyomi: '-' },
    { char: '賢', meaning: 'Wise', onyomi: 'ken', kunyomi: 'kasiko' },
    { char: '憶', meaning: 'Recollect', onyomi: 'oku', kunyomi: '-' },
    { char: '慮', meaning: 'Consideration', onyomi: 'ryo', kunyomi: 'omonpaka' },
    { char: '敢', meaning: 'Daring', onyomi: 'kan', kunyomi: 'ae' },
    { char: '棄', meaning: 'Abandon', onyomi: 'ki', kunyomi: 'su' },
    { char: '忌', meaning: 'Mourning/Abhor', onyomi: 'ki', kunyomi: 'i' },
    { char: '疑', meaning: 'Doubt', onyomi: 'gi', kunyomi: 'uta' },
    { char: '義', meaning: 'Righteousness', onyomi: 'gi', kunyomi: '-' },
    { char: '議', meaning: 'Deliberation', onyomi: 'gi', kunyomi: '-' },
    { char: '虐', meaning: 'Tyrannize', onyomi: 'gyaku', kunyomi: 'shiita' },
    { char: '窮', meaning: 'Extremity/Distress', onyomi: 'kyuu', kunyomi: 'kiwa' },
    { char: '拒', meaning: 'Refuse', onyomi: 'kyo', kunyomi: 'koba' },
    { char: '虚', meaning: 'Void', onyomi: 'kyo/ko', kunyomi: 'muna' },
    { char: '叫', meaning: 'Shout', onyomi: 'kyou', kunyomi: 'sake' },
    { char: '狂', meaning: 'Lunacy', onyomi: 'kyou', kunyomi: 'kuru' },
    { char: '脅', meaning: 'Threaten', onyomi: 'kyou', kunyomi: 'obi' },
    { char: '恐', meaning: 'Fear', onyomi: 'kyou', kunyomi: 'oso' },
    { char: '愚', meaning: 'Foolish', onyomi: 'gu', kunyomi: 'oro' },
    { char: '屈', meaning: 'Yield/Bend', onyomi: 'kutsu', kunyomi: '-' },
    { char: '懇', meaning: 'Sincere/Familiar', onyomi: 'kon', kunyomi: 'nengoro' },
    { char: '挫', meaning: 'Crush/Discourage', onyomi: 'za', kunyomi: 'kuji' },
    { char: '催', meaning: 'Sponsor/Hold', onyomi: 'sai', kunyomi: 'moyo' },
    { char: '塞', meaning: 'Close/Block', onyomi: 'sai/soku', kunyomi: 'fusa' },
    { char: '索', meaning: 'Search/Cable', onyomi: 'saku', kunyomi: '-' },
    { char: '暫', meaning: 'Temporary', onyomi: 'zan', kunyomi: 'shibaraku' },
    { char: '諮', meaning: 'Consult', onyomi: 'shi', kunyomi: 'haka' },
    { char: '疾', meaning: 'Disease/Fast', onyomi: 'shitsu', kunyomi: '-' },
    { char: '嫉', meaning: 'Envy', onyomi: 'shitsu', kunyomi: 'sonemu' },
    { char: '釈', meaning: 'Explanation/Release', onyomi: 'shaku', kunyomi: '-' },
    { char: '儒', meaning: 'Confucian', onyomi: 'ju', kunyomi: '-' },
    { char: '需', meaning: 'Demand', onyomi: 'ju', kunyomi: '-' }
  ],
  actions_physical: [
    { char: '握', meaning: 'Grip', onyomi: 'aku', kunyomi: 'nigi' },
    { char: '扱', meaning: 'Handle', onyomi: 'sou/shuu', kunyomi: 'atuka' },
    { char: '祈', meaning: 'Pray', onyomi: 'ki', kunyomi: 'ino' },
    { char: '墾', meaning: 'Ground-breaking', onyomi: 'kon', kunyomi: '-' },
    { char: '拷', meaning: 'Torture', onyomi: 'gou', kunyomi: '-' },
    { char: '劫', meaning: 'Long time/Threat', onyomi: 'gou/kyou', kunyomi: '-' },
    { char: '拘', meaning: 'Arrest/Adhere', onyomi: 'kou', kunyomi: 'kaka' },
    { char: '控', meaning: 'Withdraw/Note', onyomi: 'kou', kunyomi: 'hika' },
    { char: '墜', meaning: 'Crash/Fall', onyomi: 'tsui', kunyomi: '-' },
    { char: '詣', meaning: 'Visit temple', onyomi: 'kei', kunyomi: 'mai' },
    { char: '喧', meaning: 'Noisy', onyomi: 'ken', kunyomi: 'yakama' },
    { char: '懸', meaning: 'Suspend/Hang', onyomi: 'ken/ke', kunyomi: 'ka' },
    { char: '雇', meaning: 'Employ', onyomi: 'ko', kunyomi: 'yato' },
    { char: '傲', meaning: 'Be proud', onyomi: 'gou', kunyomi: '-' },
    { char: '勧', meaning: 'Recommend', onyomi: 'kan', kunyomi: 'susu' },
    { char: '貫', meaning: 'Pierce', onyomi: 'kan', kunyomi: 'turana' },
    { char: '換', meaning: 'Exchange', onyomi: 'kan', kunyomi: 'ka' },
    { char: '毀', meaning: 'Break/Destroy', onyomi: 'ki', kunyomi: 'kowa' },
    { char: '輝', meaning: 'Radiance', onyomi: 'ki', kunyomi: 'kagaya' },
    { char: '騎', meaning: 'Equestrian', onyomi: 'ki', kunyomi: '-' },
    { char: '戯', meaning: 'Frolic/Play', onyomi: 'gi', kunyomi: 'tawa' },
    { char: '擬', meaning: 'Mimic', onyomi: 'gi', kunyomi: '-' },
    { char: '欺', meaning: 'Deceive', onyomi: 'gi', kunyomi: 'azu' },
    { char: '犠', meaning: 'Sacrifice', onyomi: 'gi', kunyomi: '-' },
    { char: '喫', meaning: 'Consume', onyomi: 'kitsu', kunyomi: '-' },
    { char: '詰', meaning: 'Stuffed/Packed', onyomi: 'kitsu', kunyomi: 'tsu' },
    { char: '却', meaning: 'Instead/Reject', onyomi: 'kyaku', kunyomi: 'kae' },
    { char: '脚', meaning: 'Leg/Counter', onyomi: 'kyaku/kaku', kunyomi: 'ashi' },
    { char: '掘', meaning: 'Dig', onyomi: 'kutsu', kunyomi: 'ho' },
    { char: '繰', meaning: 'Spin/Wind', onyomi: 'sou', kunyomi: 'ku' },
    { char: '契', meaning: 'Pledge/Contract', onyomi: 'kei', kunyomi: 'chigi' },
    { char: '掲', meaning: 'Display', onyomi: 'kei', kunyomi: 'kaga' },
    { char: '携', meaning: 'Carry/Portable', onyomi: 'kei', kunyomi: 'tazu' },
    { char: '継', meaning: 'Inherit/Succeed', onyomi: 'kei', kunyomi: 'tsu' },
    { char: '劇', meaning: 'Drama/Play', onyomi: 'geki', kunyomi: '-' },
    { char: '撃', meaning: 'Attack', onyomi: 'geki', kunyomi: 'u' },
    { char: '詐', meaning: 'Lie/Fraud', onyomi: 'sa', kunyomi: '-' },
    { char: '砕', meaning: 'Smash', onyomi: 'sai', kunyomi: 'kuda' },
    { char: '栽', meaning: 'Planting', onyomi: 'sai', kunyomi: '-' },
    { char: '採', meaning: 'Pick/Collect', onyomi: 'sai', kunyomi: 'to' },
    { char: '債', meaning: 'Debt', onyomi: 'sai', kunyomi: '-' },
    { char: '載', meaning: 'Load/Record', onyomi: 'sai', kunyomi: 'no' },
    { char: '削', meaning: 'Whittle/Delete', onyomi: 'saku', kunyomi: 'kezu' },
    { char: '搾', meaning: 'Squeeze', onyomi: 'saku', kunyomi: 'shibo' },
    { char: '錯', meaning: 'Confused/Mix', onyomi: 'saku', kunyomi: '-' },
    { char: '刷', meaning: 'Print', onyomi: 'satsu', kunyomi: 'su' },
    { char: '擦', meaning: 'Grate/Rub', onyomi: 'satsu', kunyomi: 'su' },
    { char: '撮', meaning: 'Snapshot', onyomi: 'satsu', kunyomi: 'to' },
    { char: '拶', meaning: 'Greet', onyomi: 'satsu', kunyomi: '-' },
    { char: '殺', meaning: 'Kill', onyomi: 'satsu/sai', kunyomi: 'koro' },
    { char: '斬', meaning: 'Behead/Kill', onyomi: 'zan', kunyomi: 'ki' },
    { char: '執', meaning: 'Take/Execute', onyomi: 'shitsu/shuu', kunyomi: 'to' },
    { char: '遮', meaning: 'Block', onyomi: 'sha', kunyomi: 'saegi' },
    { char: '借', meaning: 'Borrow', onyomi: 'shaku', kunyomi: 'ka' },
    { char: '酌', meaning: 'Pour sake', onyomi: 'shaku', kunyomi: 'ku' }
  ],
  nature_objects: [
    { char: '椅', meaning: 'Chair', onyomi: 'i', kunyomi: '-' },
    { char: '畿', meaning: 'Capital outskirts', onyomi: 'ki', kunyomi: '-' },
    { char: '坑', meaning: 'Pit/Mine', onyomi: 'kou', kunyomi: '-' },
    { char: '甲', meaning: 'Shell/Armor', onyomi: 'kou/kan', kunyomi: 'kinonoe' },
    { char: '昆', meaning: 'Descendants/Insect', onyomi: 'kon', kunyomi: '-' },
    { char: '薫', meaning: 'Fragrant', onyomi: 'kun', kunyomi: 'ka' },
    { char: '繭', meaning: 'Cocoon', onyomi: 'ken', kunyomi: 'mayu' },
    { char: '弦', meaning: 'Bowstring', onyomi: 'gen', kunyomi: 'turu' },
    { char: '虞', meaning: 'Fear/Anxiety', onyomi: 'gu', kunyomi: 'osore' },
    { char: '棺', meaning: 'Coffin', onyomi: 'kan', kunyomi: '-' },
    { char: '軌', meaning: 'Track/Rut', onyomi: 'ki', kunyomi: '-' },
    { char: '亀', meaning: 'Turtle', onyomi: 'ki', kunyomi: 'kame' },
    { char: '菊', meaning: 'Chrysanthemum', onyomi: 'kiku', kunyomi: '-' },
    { char: '丘', meaning: 'Hill', onyomi: 'kyuu', kunyomi: 'oka' },
    { char: '朽', meaning: 'Decay', onyomi: 'kyuu', kunyomi: 'kuta' },
    { char: '嗅', meaning: 'Sniff', onyomi: 'kyuu', kunyomi: 'ka' },
    { char: '距', meaning: 'Distance', onyomi: 'kyo', kunyomi: '-' },
    { char: '暁', meaning: 'Dawn', onyomi: 'gyou', kunyomi: 'akatuki' },
    { char: '襟', meaning: 'Collar', onyomi: 'kin', kunyomi: 'eri' },
    { char: '靴', meaning: 'Shoes', onyomi: 'ka', kunyomi: 'kutu' },
    { char: '茎', meaning: 'Stalk/Stem', onyomi: 'kei', kunyomi: 'kuki' },
    { char: '渓', meaning: 'Mountain stream', onyomi: 'kei', kunyomi: 'tani' },
    { char: '鶏', meaning: 'Chicken', onyomi: 'kei', kunyomi: 'niwatori' },
    { char: '沙', meaning: 'Sand', onyomi: 'sa/sha', kunyomi: 'isago' },
    { char: '鎖', meaning: 'Chain', onyomi: 'sa', kunyomi: 'kusari' },
    { char: '采', meaning: 'Dice/Pick', onyomi: 'sai', kunyomi: 'to' },
    { char: '彩', meaning: 'Coloring', onyomi: 'sai', kunyomi: 'irodo' },
    { char: '剤', meaning: 'Agent/Medicine', onyomi: 'zai', kunyomi: '-' },
    { char: '蚕', meaning: 'Silkworm', onyomi: 'san', kunyomi: 'kaiko' },
    { char: '漆', meaning: 'Lacquer', onyomi: 'shitsu', kunyomi: 'urushi' },
    { char: '芝', meaning: 'Turf/Lawn', onyomi: 'shi', kunyomi: 'shiba' },
    { char: '蛇', meaning: 'Snake', onyomi: 'ja/da', kunyomi: 'hebi' },
    { char: '朱', meaning: 'Vermillion', onyomi: 'shu', kunyomi: '-' },
    { char: '珠', meaning: 'Pearl', onyomi: 'shu', kunyomi: 'tama' },
    { char: '株', meaning: 'Stock/Stump', onyomi: 'shu', kunyomi: 'kabu' },
    { char: '腫', meaning: 'Tumor/Swell', onyomi: 'shu', kunyomi: 'hare' },
    { char: '樹', meaning: 'Tree', onyomi: 'ju', kunyomi: 'ki' }
  ],
  society_formal: [
    { char: '偽', meaning: 'Falsehood', onyomi: 'gi', kunyomi: 'itu' },
    { char: '嗣', meaning: 'Heir', onyomi: 'shi', kunyomi: '-' },
    { char: '侯', meaning: 'Marquis', onyomi: 'kou', kunyomi: '-' },
    { char: '勲', meaning: 'Merit', onyomi: 'kun', kunyomi: '-' },
    { char: '桁', meaning: 'Beam/Digit', onyomi: 'kou', kunyomi: 'keta' },
    { char: '顕', meaning: 'Manifest', onyomi: 'ken', kunyomi: '-' },
    { char: '呉', meaning: 'Give/China', onyomi: 'go', kunyomi: 'ku' },
    { char: '碁', meaning: 'Go (game)', onyomi: 'go', kunyomi: '-' },
    { char: '御', meaning: 'Honorable', onyomi: 'go/gyo', kunyomi: 'on' },
    { char: '虜', meaning: 'Captive', onyomi: 'ryo', kunyomi: '-' },
    { char: '寛', meaning: 'Tolerant', onyomi: 'kan', kunyomi: 'kutsuro' },
    { char: '患', meaning: 'Afflicted', onyomi: 'kan', kunyomi: 'wazura' },
    { char: '既', meaning: 'Already', onyomi: 'ki', kunyomi: 'sude' },
    { char: '儀', meaning: 'Ceremony', onyomi: 'gi', kunyomi: '-' },
    { char: '吉', meaning: 'Good luck', onyomi: 'kitsu/yoshi', kunyomi: '-' },
    { char: '及', meaning: 'Attain', onyomi: 'kyuu', kunyomi: 'oyo' },
    { char: '糾', meaning: 'Twist/Investigate', onyomi: 'kyuu', kunyomi: '-' },
    { char: '巨', meaning: 'Gigantic', onyomi: 'kyo', kunyomi: '-' },
    { char: '況', meaning: 'Condition/Situation', onyomi: 'kyou', kunyomi: '-' },
    { char: '勤', meaning: 'Diligence', onyomi: 'kin/gon', kunyomi: 'tsuto' },
    { char: '謹', meaning: 'Discreet', onyomi: 'kin', kunyomi: 'tsutsushi' },
    { char: '吟', meaning: 'Chant', onyomi: 'gin', kunyomi: '-' },
    { char: '愚', meaning: 'Stupid/Foolish', onyomi: 'gu', kunyomi: 'oro' },
    { char: '刑', meaning: 'Penalty', onyomi: 'kei', kunyomi: '-' },
    { char: '宰', meaning: 'Manager/Rule', onyomi: 'sai', kunyomi: '-' },
    { char: '歳', meaning: 'Age/Year', onyomi: 'sai/sei', kunyomi: '-' },
    { char: '刹', meaning: 'Temple/Instant', onyomi: 'satsu/setsu', kunyomi: '-' },
    { char: '雑', meaning: 'Miscellaneous', onyomi: 'zatsu/zou', kunyomi: 'ma' },
    { char: '惨', meaning: 'Wretched', onyomi: 'san', kunyomi: 'muta' },
    { char: '桟', meaning: 'Scaffold/Cleat', onyomi: 'san', kunyomi: '-' },
    { char: '伺', meaning: 'Pay respects', onyomi: 'shi', kunyomi: '伺' },
    { char: '施', meaning: 'Alms/Execute', onyomi: 'shi/se', kunyomi: 'hodo' },
    { char: '獅', meaning: 'Lion', onyomi: 'shi', kunyomi: '-' },
    { char: '賜', meaning: 'Bestow', onyomi: 'shi', kunyomi: 'tamawa' },
    { char: '侍', meaning: 'Samurai', onyomi: 'ji', kunyomi: 'samurai' },
    { char: '璽', meaning: 'Imperial Seal', onyomi: 'ji', kunyomi: '-' },
    { char: '軸', meaning: 'Axis/Pivot', onyomi: 'jiku', kunyomi: '-' },
    { char: '赦', meaning: 'Pardon', onyomi: 'sha', kunyomi: '-' },
    { char: '斜', meaning: 'Diagonal', onyomi: 'sha', kunyomi: 'naname' },
    { char: '邪', meaning: 'Wicked', onyomi: 'ja', kunyomi: '-' },
    { char: '爵', meaning: 'Title/Rank', onyomi: 'shaku', kunyomi: '-' },
    { char: '寂', meaning: 'Loneliness', onyomi: 'jaku/seki', kunyomi: 'sabi' },
    { char: '殊', meaning: 'Particular', onyomi: 'shu', kunyomi: 'koto' },
    { char: '趣', meaning: 'Gist/Taste', onyomi: 'shu', kunyomi: 'omomuki' },
    { char: '寿', meaning: 'Longevity', onyomi: 'ju', kunyomi: 'kotobuki' },
    { char: '呪', meaning: 'Spell/Curse', onyomi: 'ju', kunyomi: 'noro' },
    { char: '囚', meaning: 'Prisoner', onyomi: 'shuu', kunyomi: 'tora' },
    { char: '舟', meaning: 'Boat', onyomi: 'shuu', kunyomi: 'fune' },
    { char: '秀', meaning: 'Excel', onyomi: 'shuu', kunyomi: 'hide' },
    { char: '臭', meaning: 'Stinking', onyomi: 'shuu', kunyomi: 'kusa' },
    { char: '袖', meaning: 'Sleeve', onyomi: 'shuu', kunyomi: 'sode' },
    { char: '羞', meaning: 'Shyness', onyomi: 'shuu', kunyomi: '-' },
    { char: '酬', meaning: 'Reward', onyomi: 'shuu', kunyomi: '-' },
    { char: '充', meaning: 'Fill up', onyomi: 'juu', kunyomi: 'a' },
    { char: '柔', meaning: 'Soft', onyomi: 'juu/nyuu', kunyomi: 'yawa' },
    { char: '汁', meaning: 'Soup/Juice', onyomi: 'juu', kunyomi: 'shiru' },
    { char: '渋', meaning: 'Astringent', onyomi: 'juu', kunyomi: 'shibu' },
    { char: '獣', meaning: 'Beast', onyomi: 'juu', kunyomi: 'kemono' },
    { char: '銃', meaning: 'Gun', onyomi: 'juu', kunyomi: '-' },
    { char: '叔', meaning: 'Uncle', onyomi: 'shuku', kunyomi: '-' },
    { char: '淑', meaning: 'Graceful', onyomi: 'shuku', kunyomi: 'shito' },
    { char: '塾', meaning: 'Private school', onyomi: 'juku', kunyomi: '-' },
    { char: '俊', meaning: 'Sagacious', onyomi: 'shun', kunyomi: '-' },
    { char: '瞬', meaning: 'Blink/Instant', onyomi: 'shun', kunyomi: 'matata' },
    { char: '准', meaning: 'Quasi/Semi', onyomi: 'jun', kunyomi: '-' },
    { char: '旬', meaning: 'Season/Decade', onyomi: 'jun', kunyomi: '-' },
    { char: '殉', meaning: 'Martyrdom', onyomi: 'jun', kunyomi: '-' },
    { char: '淳', meaning: 'Pure', onyomi: 'jun', kunyomi: '-' },
    { char: '潤', meaning: 'Wet/Enrich', onyomi: 'jun', kunyomi: 'uru' },
    { char: '遵', meaning: 'Abide by', onyomi: 'jun', kunyomi: '-' },
    { char: '庶', meaning: 'Commoner', onyomi: 'sho', kunyomi: '-' },
    { char: '緒', meaning: 'Thong/Beginning', onyomi: 'sho/cho', kunyomi: 'o' },
    { char: '徐', meaning: 'Gradually', onyomi: 'jo', kunyomi: 'omomuro' },
    { char: '償', meaning: 'Reparation', onyomi: 'shou', kunyomi: 'tsuguna' },
    { char: '匠', meaning: 'Artisan', onyomi: 'shou', kunyomi: 'takumi' },
    { char: '升', meaning: 'Measuring box', onyomi: 'shou', kunyomi: 'masu' },
    { char: '哨', meaning: 'Sentry', onyomi: 'shou', kunyomi: '-' },
    { char: '宵', meaning: 'Evening', onyomi: 'shou', kunyomi: 'yo' },
    { char: '尚', meaning: 'Furthermore', onyomi: 'shou', kunyomi: 'nao' },
    { char: '彰', meaning: 'Patent/Clear', onyomi: 'shou', kunyomi: '-' },
    { char: '承', meaning: 'Acquiesce', onyomi: 'shou', kunyomi: 'uketama' },
    { char: '抄', meaning: 'Extract/Copy', onyomi: 'shou', kunyomi: '-' },
    { char: '掌', meaning: 'Palm', onyomi: 'shou', kunyomi: 'tanagokoro' },
    { char: '捷', meaning: 'Victory/Fast', onyomi: 'shou', kunyomi: '-' },
    { char: '昇', meaning: 'Ascend', onyomi: 'shou', kunyomi: 'nobo' },
    { char: '昌', meaning: 'Prosperous', onyomi: 'shou', kunyomi: '-' },
    { char: '沼', meaning: 'Swamp', onyomi: 'shou', kunyomi: 'numa' },
    { char: '晶', meaning: 'Sparkle/Crystal', onyomi: 'shou', kunyomi: '-' },
    { char: '梢', meaning: 'Treetop', onyomi: 'shou', kunyomi: 'kozue' },
    { char: '樟', meaning: 'Camphor', onyomi: 'shou', kunyomi: 'kusu' },
    { char: '渉', meaning: 'Fording/Ferry', onyomi: 'shou', kunyomi: 'wata' },
    { char: '焦', meaning: 'Scorch/Singing', onyomi: 'shou', kunyomi: 'ko' },
    { char: '症', meaning: 'Symptoms', onyomi: 'shou', kunyomi: '-' },
    { char: '硝', meaning: 'Nitrate/Saltpeter', onyomi: 'shou', kunyomi: '-' },
    { char: '礁', meaning: 'Reef', onyomi: 'shou', kunyomi: '-' },
    { char: '祥', meaning: 'Auspicious', onyomi: 'shou', kunyomi: '-' },
    { char: '称', meaning: 'Appellation', onyomi: 'shou', kunyomi: 'tata' },
    { char: '粧', meaning: 'Cosmetics', onyomi: 'shou', kunyomi: '-' },
    { char: '肖', meaning: 'Resemblance', onyomi: 'shou', kunyomi: '-' },
    { char: '荘', meaning: 'Villa/Inn', onyomi: 'shou/sou', kunyomi: '-' },
    { char: '蒋', meaning: 'Reed', onyomi: 'shou', kunyomi: '-' },
    { char: '訟', meaning: 'Lawsuit', onyomi: 'shou', kunyomi: '-' },
    { char: '詔', meaning: 'Imperial edict', onyomi: 'shou', kunyomi: 'mikotonori' },
    { char: '詳', meaning: 'Detailed', onyomi: 'shou', kunyomi: 'kua' },
    { char: '象', meaning: 'Elephant/Phenomenon', onyomi: 'shou/zou', kunyomi: '-' },
    { char: '賞', meaning: 'Prize', onyomi: 'shou', kunyomi: 'home' },
    { char: '醤', meaning: 'Soy sauce/Miso', onyomi: 'shou', kunyomi: '-' },
    { char: '鐘', meaning: 'Bell', onyomi: 'shou', kunyomi: 'kane' },
    { char: '障', meaning: 'Hinder', onyomi: 'shou', kunyomi: 'sawa' },
    { char: '蹟', meaning: 'Traces/Ruins', onyomi: 'seki', kunyomi: 'ato' },
    { char: '碩', meaning: 'Great/Large', onyomi: 'seki', kunyomi: '-' },
    { char: '拙', meaning: 'Clumsy', onyomi: 'setsu', kunyomi: 'tsutana' },
    { char: '摂', meaning: 'Vicarious', onyomi: 'setsu', kunyomi: 'to' },
    { char: '窃', meaning: 'Steal', onyomi: 'setsu', kunyomi: 'nusu' },
    { char: '穿', meaning: 'Pierce/Drill', onyomi: 'sen', kunyomi: '穿' },
    { char: '箭', meaning: 'Arrow', onyomi: 'sen', kunyomi: 'ya' },
    { char: '繊', meaning: 'Slender/Fine', onyomi: 'sen', kunyomi: '-' },
    { char: '羨', meaning: 'Envy', onyomi: 'sen', kunyomi: 'uraya' },
    { char: '腺', meaning: 'Gland', onyomi: 'sen', kunyomi: '-' },
    { char: '舛', meaning: 'Opposite/Err', onyomi: 'sen', kunyomi: '-' },
    { char: '詮', meaning: 'Elucidate', onyomi: 'sen', kunyomi: '-' },
    { char: '賎', meaning: 'Cheap/Lowly', onyomi: 'sen', kunyomi: 'iya' },
    { char: '銑', meaning: 'Pig iron', onyomi: 'sen', kunyomi: '-' },
    { char: '漸', meaning: 'Gradually', onyomi: 'zen', kunyomi: '-' },
    { char: '繕', meaning: 'Repair', onyomi: 'zen', kunyomi: 'tsukuro' },
    { char: '糎', meaning: 'Centimeter', onyomi: '-', kunyomi: 'sentimeetoru' },
    { char: '曾', meaning: 'Formerly/Ever', onyomi: 'sou/zo', kunyomi: 'katsu' },
    { char: '楚', meaning: 'Whip/Clean', onyomi: 'so', kunyomi: '-' },
    { char: '狙', meaning: 'Aim at', onyomi: 'so', kunyomi: 'nera' },
    { char: '疏', meaning: 'Sparse/Shun', onyomi: 'so', kunyomi: 'uton' },
    { char: '疎', meaning: 'Alienate', onyomi: 'so', kunyomi: 'uton' },
    { char: '礎', meaning: 'Foundation', onyomi: 'so', kunyomi: 'ishizue' },
    { char: '蘇', meaning: 'Revive', onyomi: 'so', kunyomi: 'yomigae' },
    { char: '遡', meaning: 'Go upstream', onyomi: 'so', kunyomi: 'sakanobo' },
    { char: '鼠', meaning: 'Rat/Mouse', onyomi: 'so', kunyomi: 'nezumi' },
    { char: '僧', meaning: 'Monk', onyomi: 'sou', kunyomi: '-' },
    { char: '爽', meaning: 'Refreshing', onyomi: 'sou', kunyomi: 'sawayaka' },
    { char: '宋', meaning: 'Song dynasty', onyomi: 'sou', kunyomi: '-' },
    { char: '漕', meaning: 'Row/Oar', onyomi: 'sou', kunyomi: 'ko' },
    { char: '燥', meaning: 'Dry', onyomi: 'sou', kunyomi: 'kawa' },
    { char: '痩', meaning: 'Thin', onyomi: 'sou', kunyomi: 'ya' },
    { char: '綜', meaning: 'Rule/Synthesize', onyomi: 'sou', kunyomi: '-' },
    { char: '聡', meaning: 'Wise', onyomi: 'sou', kunyomi: '-' },
    { char: '遭', meaning: 'Encounter', onyomi: 'sou', kunyomi: 'a' },
    { char: '霜', meaning: 'Frost', onyomi: 'sou', kunyomi: 'shimo' },
    { char: '騒', meaning: 'Boisterous', onyomi: 'sou', kunyomi: 'sawa' },
    { char: '贈', meaning: 'Give/Present', onyomi: 'zou/sou', kunyomi: 'oku' },
    { char: '賊', meaning: 'Robber/Rebel', onyomi: 'zoku', kunyomi: '-' },
    { char: '遜', meaning: 'Humble', onyomi: 'son', kunyomi: '-' },
    { char: '汰', meaning: 'Select/Luxury', onyomi: 'ta', kunyomi: '-' },
    { char: '唾', meaning: 'Saliva', onyomi: 'ta', kunyomi: 'tsubaki' },
    { char: '堕', meaning: 'Fall/Degenerate', onyomi: 'da', kunyomi: '-' },
    { char: '妥', meaning: 'Gentle/Peace', onyomi: 'da', kunyomi: '-' },
    { char: '惰', meaning: 'Laziness', onyomi: 'da', kunyomi: '-' },
    { char: '泰', meaning: 'Peaceful/Calm', onyomi: 'tai', kunyomi: '-' },
    { char: '滞', meaning: 'Stagnate', onyomi: 'tai', kunyomi: 'todoko' },
    { char: '胎', meaning: 'Womb', onyomi: 'tai', kunyomi: '-' },
    { char: '逮', meaning: 'Apprehend', onyomi: 'tai', kunyomi: '-' },
    { char: '隊', meaning: 'Unit/Troop', onyomi: 'tai', kunyomi: '-' },
    { char: '黛', meaning: 'Eyebrow black', onyomi: 'tai', kunyomi: 'mayuzumi' },
    { char: '拓', meaning: 'Pioneer', onyomi: 'taku', kunyomi: 'hira' },
    { char: '託', meaning: 'Consign', onyomi: 'taku', kunyomi: 'koto' },
    { char: '濁', meaning: 'Muddy/Impure', onyomi: 'daku', kunyomi: 'nigo' },
    { char: '諾', meaning: 'Consent', onyomi: 'daku', kunyomi: '-' },
    { char: '只', meaning: 'Free/Only', onyomi: 'shi', kunyomi: 'tada' },
    { char: '辰', meaning: 'Dragon (zodiac)', onyomi: 'shin', kunyomi: 'tatsu' },
    { char: '奪', meaning: 'Seize', onyomi: 'datsu', kunyomi: 'uba' },
    { char: '脱', meaning: 'Undress/Escape', onyomi: 'datsu', kunyomi: 'nu' },
    { char: '巽', meaning: 'Southeast', onyomi: 'son', kunyomi: 'tatsumi' },
    { char: '竪', meaning: 'Vertical', onyomi: 'ju', kunyomi: 'tate' },
    { char: '韮', meaning: 'Leek', onyomi: 'kyuu', kunyomi: 'nira' },
    { char: '寧', meaning: 'Rather/Tranquil', onyomi: 'nei', kunyomi: 'mushi' },
    { char: '捻', meaning: 'Twist', onyomi: 'nen', kunyomi: 'hine' },
    { char: '膿', meaning: 'Pus', onyomi: 'nou', kunyomi: 'umi' },
    { char: '覇', meaning: 'Hegemony/Champion', onyomi: 'ha', kunyomi: '-' },
    { char: '把', meaning: 'Grasp', onyomi: 'ha', kunyomi: '-' },
    { char: '播', meaning: 'Sow/Broadcast', onyomi: 'ha', kunyomi: 'ma' },
    { char: '杷', meaning: 'Loquat/Rake', onyomi: 'ha', kunyomi: '-' },
    { char: '琶', meaning: 'Lute', onyomi: 'ha', kunyomi: '-' },
    { char: '婆', meaning: 'Old woman', onyomi: 'ba', kunyomi: '-' },
    { char: '罵', meaning: 'Abuse/Insult', onyomi: 'ba', kunyomi: 'no' },
    { char: '芭', meaning: 'Banana/Plantain', onyomi: 'ba', kunyomi: '-' },
    { char: '俳', meaning: 'Actor/Haiku', onyomi: 'hai', kunyomi: '-' },
    { char: '廃', meaning: 'Abolish', onyomi: 'hai', kunyomi: 'suta' },
    { char: '盃', meaning: 'Sake cup', onyomi: 'hai', kunyomi: 'sakazuki' },
    { char: '牌', meaning: 'Tile/Tablet', onyomi: 'hai', kunyomi: '-' },
    { char: '輩', meaning: 'Comrades/Fellows', onyomi: 'hai', kunyomi: 'yakara' },
    { char: '賠', meaning: 'Compensate', onyomi: 'bai', kunyomi: '-' },
    { char: '陪', meaning: 'Accompany', onyomi: 'bai', kunyomi: '-' },
    { char: '箔', meaning: 'Foil/Leaf', onyomi: 'haku', kunyomi: '-' },
    { char: '粕', meaning: 'Dregs', onyomi: 'haku', kunyomi: 'kasu' },
    { char: '舶', meaning: 'Liner/Ship', onyomi: 'haku', kunyomi: '-' },
    { char: '漠', meaning: 'Desert/Vague', onyomi: 'baku', kunyomi: '-' },
    { char: '爆', meaning: 'Explode', onyomi: 'baku', kunyomi: '-' },
    { char: '縛', meaning: 'Bind', onyomi: 'baku', kunyomi: 'shiba' },
    { char: '莫', meaning: 'Must not/Not', onyomi: 'baku/ma', kunyomi: '-' },
    { char: '駁', meaning: 'Refute', onyomi: 'baku', kunyomi: '-' },
    { char: '硲', meaning: 'Valley', onyomi: '-', kunyomi: 'hazama' },
    { char: '伐', meaning: 'Attack/Fell', onyomi: 'batsu', kunyomi: '-' },
    { char: '筏', meaning: 'Raft', onyomi: 'batsu', kunyomi: 'ikada' },
    { char: '閥', meaning: 'Clique/Clan', onyomi: 'batsu', kunyomi: '-' },
    { char: '塙', meaning: 'Projecting part', onyomi: 'kaku', kunyomi: 'hanawa' },
    { char: '蛤', meaning: 'Clam', onyomi: 'kou', kunyomi: 'hamaguri' },
    { char: '隼', meaning: 'Falcon', onyomi: 'shun', kunyomi: 'hayabusa' },
    { char: '叛', meaning: 'Rebel', onyomi: 'han', kunyomi: '-' },
    { char: '斑', meaning: 'Spot/Mottle', onyomi: 'han', kunyomi: 'madara' },
    { char: '氾', meaning: 'Overflow', onyomi: 'han', kunyomi: '-' },
    { char: '汎', meaning: 'Pan-/General', onyomi: 'han', kunyomi: '-' },
    { char: '畔', meaning: 'Paddy ridge', onyomi: 'han', kunyomi: 'aze' },
    { char: '繁', meaning: 'Lush/Prosperous', onyomi: 'han', kunyomi: 'shige' },
    { char: '藩', meaning: 'Clan/Fief', onyomi: 'han', kunyomi: '-' },
    { char: '頒', meaning: 'Distribute', onyomi: 'han', kunyomi: '-' },
    { char: '挽', meaning: 'Saw/Grind', onyomi: 'ban', kunyomi: 'hi' },
    { char: '盤', meaning: 'Tray/Board', onyomi: 'ban', kunyomi: '-' },
    { char: '磐', meaning: 'Rock', onyomi: 'ban', kunyomi: 'iwa' },
    { char: '蕃', meaning: 'Foreign/Grow', onyomi: 'ban', kunyomi: '-' },
    { char: '蛮', meaning: 'Barbarian', onyomi: 'ban', kunyomi: '-' },
    { char: '卑', meaning: 'Lowly/Mean', onyomi: 'hi', kunyomi: 'iya' },
    { char: '妃', meaning: 'Queen/Princess', onyomi: 'hi', kunyomi: 'kisaki' },
    { char: '庇', meaning: 'Protect/Shield', onyomi: 'hi', kunyomi: 'hizashi' },
    { char: '扉', meaning: 'Door', onyomi: 'hi', kunyomi: 'tobira' },
    { char: '批', meaning: 'Criticize', onyomi: 'hi', kunyomi: '-' },
    { char: '披', meaning: 'Expose', onyomi: 'hi', kunyomi: '-' },
    { char: '斐', meaning: 'Patterned', onyomi: 'hi', kunyomi: '-' },
    { char: '泌', meaning: 'Secrete', onyomi: 'hi/hitsu', kunyomi: '-' },
    { char: '緋', meaning: 'Scarlet', onyomi: 'hi', kunyomi: 'ake' },
    { char: '罷', meaning: 'Stop/Dismiss', onyomi: 'hi', kunyomi: 'ma' },
    { char: '誹', meaning: 'Slander', onyomi: 'hi', kunyomi: 'sosori' },
    { char: '避', meaning: 'Avoid', onyomi: 'hi', kunyomi: 'yo' },
    { char: '樋', meaning: 'Gutter/Conduit', onyomi: 'tou', kunyomi: 'toi' },
    { char: '簸', meaning: 'Winnow/Fan', onyomi: 'hi', kunyomi: 'hi' },
    { char: '毘', meaning: 'Assist/Buddhist', onyomi: 'bi', kunyomi: '-' },
    { char: '琵', meaning: 'Lute', onyomi: 'bi', kunyomi: '-' },
    { char: '眉', meaning: 'Eyebrow', onyomi: 'bi/mi', kunyomi: 'mayu' },
    { char: '柊', meaning: 'Holly', onyomi: '-', kunyomi: 'hiiragi' },
    { char: '稗', meaning: 'Barnyard grass', onyomi: 'hai', kunyomi: 'hie' },
    { char: '髭', meaning: 'Beard/Mustache', onyomi: 'shi', kunyomi: 'hige' },
    { char: '膝', meaning: 'Knee', onyomi: 'shitsu', kunyomi: 'hiza' },
    { char: '弼', meaning: 'Help/Auxiliary', onyomi: 'hitsu', kunyomi: '-' },
    { char: '瓢', meaning: 'Gourd', onyomi: 'hyou', kunyomi: 'hisago' },
    { char: '豹', meaning: 'Leopard', onyomi: 'hyou', kunyomi: '-' },
    { char: '廟', meaning: 'Mausoleum', onyomi: 'byou', kunyomi: '-' },
    { char: '鋲', meaning: 'Rivet/Tack', onyomi: 'byou', kunyomi: '-' },
    { char: '蒜', meaning: 'Garlic', onyomi: 'san', kunyomi: 'hiru' },
    { char: '頻', meaning: 'Frequent', onyomi: 'hin', kunyomi: '-' },
    { char: '扶', meaning: 'Aid/Help', onyomi: 'fu', kunyomi: '-' },
    { char: '阜', meaning: 'Hill/Mound', onyomi: 'fu', kunyomi: '-' },
    { char: '訃', meaning: 'Obituary', onyomi: 'fu', kunyomi: '-' },
    { char: '赴', meaning: 'Proceed', onyomi: 'fu', kunyomi: 'omomu' },
    { char: '腐', meaning: 'Rot/Decay', onyomi: 'fu', kunyomi: 'kusa' },
    { char: '敷', meaning: 'Spread/Lay', onyomi: 'fu', kunyomi: 'shi' },
    { char: '賦', meaning: 'Levy/Tribute', onyomi: 'fu', kunyomi: '-' },
    { char: '譜', meaning: 'Score/Genealogy', onyomi: 'fu', kunyomi: '-' },
    { char: '侮', meaning: 'Despise', onyomi: 'bu', kunyomi: 'anado' },
    { char: '撫', meaning: 'Stroke/抚', onyomi: 'bu', kunyomi: 'nade' },
    { char: '葡', meaning: 'Grape', onyomi: 'bu', kunyomi: '-' },
    { char: '蕪', meaning: 'Turnip', onyomi: 'bu', kunyomi: 'kabu' },
    { char: '楓', meaning: 'Maple', onyomi: 'fuu', kunyomi: 'kaede' },
    { char: '葺', meaning: 'Thatch', onyomi: 'shuu', kunyomi: 'fu' },
    { char: '蕗', meaning: 'Butterbur', onyomi: 'ro', kunyomi: 'fuki' },
    { char: '覆', meaning: 'Cover', onyomi: 'fuku', kunyomi: 'ou' },
    { char: '弗', meaning: 'Dollar', onyomi: 'futsu', kunyomi: '-' },
    { char: '憤', meaning: 'Resentment', onyomi: 'fun', kunyomi: 'ikidoo' },
    { char: '丙', meaning: 'Third/C', onyomi: 'hei', kunyomi: '-' },
    { char: '併', meaning: 'Join/Annex', onyomi: 'hei', kunyomi: 'awa' },
    { char: '塀', meaning: 'Wall/Fence', onyomi: 'hei', kunyomi: '-' },
    { char: '幣', meaning: 'Currency/Offer', onyomi: 'hei', kunyomi: 'nusa' },
    { char: '蔽', meaning: 'Cover/Hide', onyomi: 'hei', kunyomi: '-' },
    { char: '閉', meaning: 'Close', onyomi: 'hei', kunyomi: 'to/shi' },
    { char: '蔑', meaning: 'Contempt', onyomi: 'betsu', kunyomi: 'sagesu' },
    { char: '偏', meaning: 'Partial/Leaning', onyomi: 'hen', kunyomi: 'kata' },
    { char: '遍', meaning: 'Everywhere', onyomi: 'hen', kunyomi: 'amane' },
    { char: '圃', meaning: 'Garden/Field', onyomi: 'ho', kunyomi: '-' },
    { char: '甫', meaning: 'Begin/Just', onyomi: 'ho', kunyomi: 'haji' },
    { char: '輔', meaning: 'Assist', onyomi: 'ho', kunyomi: 'tasu' },
    { char: '慕', meaning: 'Yearn', onyomi: 'bo', kunyomi: 'shita' },
    { char: '戊', meaning: 'Fifth/E', onyomi: 'bo', kunyomi: 'tsuchinoe' },
    { char: '耗', meaning: 'Consume', onyomi: 'mou/kou', kunyomi: '-' },
    { char: '菩', meaning: 'Bodhisattva', onyomi: 'bo', kunyomi: '-' },
    { char: '倣', meaning: 'Emulate', onyomi: 'hou', kunyomi: 'nara' },
    { char: '俸', meaning: 'Salary', onyomi: 'hou', kunyomi: '-' },
    { char: '呆', meaning: 'Amazed/Stupid', onyomi: 'hou', kunyomi: 'aki' },
    { char: '峯', meaning: 'Peak', onyomi: 'hou', kunyomi: 'mine' },
    { char: '崩', meaning: 'Crumble', onyomi: 'hou', kunyomi: 'kuzu' },
    { char: '庖', meaning: 'Kitchen', onyomi: 'hou', kunyomi: '-' },
    { char: '捧', meaning: 'Offer/Lift', onyomi: 'hou', kunyomi: 'sasa' },
    { char: '烹', meaning: 'Cook', onyomi: 'hou', kunyomi: '-' },
    { char: '砲', meaning: 'Cannon', onyomi: 'hou', kunyomi: '-' },
    { char: '縫', meaning: 'Sew', onyomi: 'hou', kunyomi: 'nu' },
    { char: '胞', meaning: 'Cell/Placenta', onyomi: 'hou', kunyomi: '-' },
    { char: '萌', meaning: 'Sprout', onyomi: 'hou', kunyomi: 'mo' },
    { char: '蓬', meaning: 'Mugwort', onyomi: 'hou', kunyomi: 'yomogi' },
    { char: '蜂', meaning: 'Bee/Wasp', onyomi: 'hou', kunyomi: 'hachi' },
    { char: '褒', meaning: 'Praise', onyomi: 'hou', kunyomi: 'home' },
    { char: '鋒', meaning: 'Sword point', onyomi: 'hou', kunyomi: 'kissa' },
    { char: '鳳', meaning: 'Phoenix', onyomi: 'hou', kunyomi: '-' },
    { char: '鵬', meaning: 'Phoenix', onyomi: 'hou', kunyomi: 'ootori' },
    { char: '乏', meaning: 'Scarcity', onyomi: 'bou', kunyomi: 'tobo' },
    { char: '傍', meaning: 'Beside', onyomi: 'bou', kunyomi: 'kata' },
    { char: '剖', meaning: 'Dissect', onyomi: 'bou', kunyomi: '-' },
    { char: '某', meaning: 'Certain person', onyomi: 'bou', kunyomi: 'nanigashi' },
    { char: '冒', meaning: 'Risk/Dare', onyomi: 'bou', kunyomi: 'oka' },
    { char: '紡', meaning: 'Spinning', onyomi: 'bou', kunyomi: 'tumu' },
    { char: '肪', meaning: 'Fat/Lard', onyomi: 'bou', kunyomi: '-' },
    { char: '膨', meaning: 'Swell', onyomi: 'bou', kunyomi: 'fuku' },
    { char: '貌', meaning: 'Appearance', onyomi: 'bou', kunyomi: 'katata' },
    { char: '鉾', meaning: 'Halberd', onyomi: 'hou', kunyomi: 'hoko' },
    { char: '吠', meaning: 'Bark/Howl', onyomi: 'fuku', kunyomi: 'ho' },
    { char: '撲', meaning: 'Strike/Beating', onyomi: 'boku', kunyomi: '-' },
    { char: '睦', meaning: 'Harmonious', onyomi: 'boku', kunyomi: 'mutsu' },
    { char: '穆', meaning: 'Gentle/Pure', onyomi: 'boku', kunyomi: '-' },
    { char: '釦', meaning: 'Button', onyomi: 'kou', kunyomi: 'botan' },
    { char: '勃', meaning: 'Sudden/Erect', onyomi: 'botsu', kunyomi: '-' },
    { char: '没', meaning: 'Sink/Death', onyomi: 'botsu', kunyomi: '-' },
    { char: '殆', meaning: 'Almost/Nearly', onyomi: 'tai', kunyomi: 'hoto' },
    { char: '摩', meaning: 'Chafe/Rub', onyomi: 'ma', kunyomi: '-' },
    { char: '昧', meaning: 'Obscure', onyomi: 'mai', kunyomi: '-' },
    { char: '槙', meaning: 'Twig/Evergreen', onyomi: 'shin', kunyomi: 'maki' },
    { char: '漫', meaning: 'Cartoon/Involuntary', onyomi: 'man', kunyomi: '-' },
    { char: '魅', meaning: 'Fascination', onyomi: 'mi', kunyomi: '-' },
    { char: '巳', meaning: 'Snake (zodiac)', onyomi: 'shi', kunyomi: 'mi' },
    { char: '箕', meaning: 'Winnowing fan', onyomi: 'ki', kunyomi: 'mi' },
    { char: '湊', meaning: 'Harbor', onyomi: 'sou', kunyomi: 'minato' },
    { char: '冥', meaning: 'Dark/Hades', onyomi: 'mei/myou', kunyomi: '-' },
    { char: '盟', meaning: 'Alliance', onyomi: 'mei', kunyomi: '-' },
    { char: '姪', meaning: 'Niece', onyomi: 'tetsu', kunyomi: 'meigo' },
    { char: '牟', meaning: 'Moo/Pupil', onyomi: 'mu/bou', kunyomi: '-' },
    { char: '厶', meaning: 'Private', onyomi: 'shi', kunyomi: '-' },
    { char: '鵡', meaning: 'Cockatoo', onyomi: 'mu', kunyomi: '-' },
    { char: '椋', meaning: 'Grey starling', onyomi: 'ryou', kunyomi: 'muku' },
    { char: '緬', meaning: 'Fine thread', onyomi: 'men', kunyomi: '-' },
    { char: '摸', meaning: 'Imitation', onyomi: 'mo/bo', kunyomi: '-' },
    { char: '孟', meaning: 'Chief/Beginning', onyomi: 'mou', kunyomi: '-' },
    { char: '耗', meaning: 'Waste/Spend', onyomi: 'mou/kou', kunyomi: '-' },
    { char: '蒙', meaning: 'Ignorance', onyomi: 'mou/bou', kunyomi: '-' },
    { char: '儲', meaning: 'Profitable', onyomi: 'cho', kunyomi: 'mou' },
    { char: '杢', meaning: 'Woodworking', onyomi: '-', kunyomi: 'moku' },
    { char: '尤', meaning: 'Reasonable', onyomi: 'yuu', kunyomi: 'motto' },
    { char: '悶', meaning: 'Agony', onyomi: 'mon', kunyomi: 'moda' },
    { char: '匁', meaning: 'Monme (unit)', onyomi: '-', kunyomi: 'monme' },
    { char: '也', meaning: 'To be (classical)', onyomi: 'ya', kunyomi: 'nari' },
    { char: '冶', meaning: 'Melting/Smelting', onyomi: 'ya', kunyomi: '-' },
    { char: '爺', meaning: 'Old man', onyomi: 'ya', kunyomi: 'jii' },
    { char: '耶', meaning: 'Question mark?', onyomi: 'ya', kunyomi: '-' },
    { char: '弥', meaning: 'Increasingly', onyomi: 'mi/bi', kunyomi: 'ya' },
    { char: '厄', meaning: 'Misfortune', onyomi: 'yaku', kunyomi: '-' },
    { char: '躍', meaning: 'Leap', onyomi: 'yaku', kunyomi: 'odo' },
    { char: '靖', meaning: 'Peaceful', onyomi: 'sei', kunyomi: 'yasu' },
    { char: '薮', meaning: 'Thicket', onyomi: 'sou', kunyomi: 'yabu' },
    { char: '鑓', meaning: 'Spear', onyomi: '-', kunyomi: 'yari' },
    { char: '愉', meaning: 'Pleasure', onyomi: 'yu', kunyomi: '-' },
    { char: '愈', meaning: 'More and more', onyomi: 'yu', kunyomi: 'iyo' },
    { char: '癒', meaning: 'Healing', onyomi: 'yu', kunyomi: 'ie' },
    { char: '諭', meaning: 'Admonish', onyomi: 'yu', kunyomi: 'sato' },
    { char: '輸', meaning: 'Transport', onyomi: 'shu/yu', kunyomi: '-' },
    { char: '唯', meaning: 'Solely', onyomi: 'yui/i', kunyomi: 'tada' },
    { char: '佑', meaning: 'Help/Assist', onyomi: 'yu', kunyomi: 'tasu' },
    { char: '宥', meaning: 'Soothe/Pardon', onyomi: 'yu', kunyomi: 'nadam' },
    { char: '幽', mystery: 'Secluded', onyomi: 'yuu', kunyomi: '-' },
    { char: '悠', meaning: 'Quiet/Eternal', onyomi: 'yuu', kunyomi: '-' },
    { char: '憂', meaning: 'Anxiety', onyomi: 'yuu', kunyomi: 'ure/uto' },
    { char: '揖', meaning: 'Bowing', onyomi: 'yuu/shuu', kunyomi: '-' },
    { char: '柚', meaning: 'Citron', onyomi: 'yu/yuu', kunyomi: 'yuzu' },
    { char: '猶', meaning: 'Furthermore', onyomi: 'yuu', kunyomi: 'nao' },
    { char: '猷', meaning: 'Plan/Scheme', onyomi: 'yuu', kunyomi: '-' },
    { char: '祐', meaning: 'Help/Assist', onyomi: 'yuu', kunyomi: 'tasu' },
    { char: '裕', meaning: 'Abundant', onyomi: 'yuu', kunyomi: '-' },
    { char: '誘', meaning: 'Entice', onyomi: 'yuu', kunyomi: '誘' },
    { char: '遊', meaning: 'Play', onyomi: 'yuu/yu', kunyomi: 'aso' },
    { char: '邑', meaning: 'Village/Town', onyomi: 'yuu', kunyomi: 'mura' },
    { char: '融', meaning: 'Dissolve', onyomi: 'yuu', kunyomi: 'to' },
    { char: '輿', meaning: 'Palanquin', onyomi: 'yo', kunyomi: 'koshi' },
    { char: '傭', meaning: 'Employ', onyomi: 'you', kunyomi: '-' },
    { char: '妖', meaning: 'Bewitching', onyomi: 'you', kunyomi: 'aya' },
    { char: '庸', meaning: 'Commonplace', onyomi: 'you', kunyomi: '-' },
    { char: '擁', meaning: 'Embrace/Protect', onyomi: 'you', kunyomi: '-' },
    { char: '曜', meaning: 'Weekday', onyomi: 'you', kunyomi: '-' },
    { char: '楊', meaning: 'Willow', onyomi: 'you', kunyomi: 'yanagi' },
    { char: '熔', meaning: 'Melting/Fusing', onyomi: 'you', kunyomi: 'to' },
    { char: '窯', meaning: 'Kiln', onyomi: 'you', kunyomi: 'kama' },
    { char: '耀', meaning: 'Shine/Sparkle', onyomi: 'you', kunyomi: 'kaga' },
    { char: '蓉', meaning: 'Lotus', onyomi: 'you', kunyomi: '-' },
    { char: '遥', meaning: 'Far off', onyomi: 'you', kunyomi: 'haruka' },
    { char: '慾', meaning: 'Greed/Lust', onyomi: 'yoku', kunyomi: '-' },
    { char: '抑', meaning: 'Suppress', onyomi: 'yoku', kunyomi: 'osa' },
    { char: '沃', meaning: 'Fertile', onyomi: 'yoku', kunyomi: '-' },
    { char: '翌', meaning: 'The following', onyomi: 'yoku', kunyomi: '-' },
    { char: '翼', meaning: 'Wing', onyomi: 'yoku', kunyomi: 'tsubasa' },
    { char: '淀', meaning: 'Pool/Stagnate', onyomi: 'ten', kunyomi: 'yodo' },
    { char: '羅', meaning: 'Gauze/Net', onyomi: 'ra', kunyomi: '-' },
    { char: '螺', meaning: 'Spiral/Screw', onyomi: 'ra', kunyomi: 'nishigai' },
    { char: '莱', meaning: 'Chenopodium', onyomi: 'rai', kunyomi: '-' },
    { char: '酪', meaning: 'Dairy', onyomi: 'raku', kunyomi: '-' },
    { char: '濫', meaning: 'Excessive', onyomi: 'ran', kunyomi: '-' },
    { char: '藍', meaning: 'Indigo', onyomi: 'ran', kunyomi: 'ai' },
    { char: '欄', meaning: 'Column', onyomi: 'ran', kunyomi: 'fuchi' },
    { char: '璃', meaning: 'Lapis lazuli', onyomi: 'ri', kunyomi: '-' },
    { char: '痢', meaning: 'Diarrhea', onyomi: 'ri', kunyomi: '-' }
  ]
};

export const N1_EXAM_DATA = {
  easy: [
    { sentence: "*れいぎ*ただしい ひとです。", target: "礼", reading: "れい", options: ["礼", "儀", "敬", "謙"], translation: "They are a well-mannered person." },
    { sentence: "かれは *けんそん*な ひとです。", target: "謙", reading: "けん", options: ["謙", "譲", "恭", "尊"], translation: "He is a humble person." },
    { sentence: "*まぼろし*を みました。", target: "幻", reading: "まぼろし", options: ["幻", "妄", "夢", "影"], translation: "I saw an illusion." },
    { sentence: "この *けいやく*は ゆうこうです。", target: "契", reading: "けい", options: ["契", "約", "誓", "諾"], translation: "This contract is valid." },
    { sentence: "*ななめ*に おいて ください。", target: "斜", reading: "ななめ", options: ["斜", "隔", "遮", "疎"], translation: "Please place it diagonally." }
  ],
  mid: [
    { sentence: "*ぜんじん*を たたえました。", target: "善", reading: "ぜん", options: ["善", "徳", "義", "賢"], translation: "We praised the virtuous person." },
    { sentence: "かれの *たくみ*な わざに おどろいた。", target: "巧", reading: "たくみ", options: ["巧", "拙", "粋", "雅"], translation: "I was amazed by his skillful technique." },
    { sentence: "*こうばい*した えいがの チケット。", target: "購", reading: "こう", options: ["購", "贈", "賠", "賜"], translation: "The movie ticket I purchased." },
    { sentence: "*せいぎ*の ために たたかう。", target: "義", reading: "ぎ", options: ["義", "儀", "議", "犠"], translation: "Fighting for justice." },
    { sentence: "この きじは *せんさい*な はだざわりだ。", target: "繊", reading: "せん", options: ["繊", "織", "粘", "滑"], translation: "This fabric has a delicate feel." }
  ],
  hard: [
    { sentence: "*いっぱん*の ひとには わかりにくい。", target: "般", reading: "はん", options: ["般", "盤", "搬", "販"], translation: "It's hard for general people to understand." },
    { sentence: "こころが *どうよう*した。", target: "揺", reading: "よう", options: ["揺", "揺", "謡", "擁"], translation: "My heart was shaken." },
    { sentence: "その けいかくは *ざせん*した。", target: "挫", reading: "ざ", options: ["挫", "阻", "滞", "拒"], translation: "That plan fell through (was discouraged)." },
    { sentence: "*はけん*を あらそう。", target: "覇", reading: "は", options: ["覇", "競", "争", "奪"], translation: "Competing for hegemony." },
    { sentence: "この ほうりつは *てってい*されて います。", target: "徹", reading: "てつ", options: ["徹", "循", "撤", "貫"], translation: "This law is thoroughly enforced." }
  ],
  top_hard: [
    { sentence: "*ちん*ぷんかんぷんの しょうちょくです。", target: "詔", reading: "しょう", options: ["詔", "勅", "朕", "璽"], translation: "It is an incomprehensible imperial edict." },
    { sentence: "*はけん*を にぎる くにが あらわれた。", target: "覇", reading: "は", options: ["覇", "征", "略", "陥"], translation: "A hegemonic nation appeared." },
    { sentence: "ひとびとの *いきどお*りが たかまった。", target: "憤", reading: "いきどお", options: ["憤", "憂", "慨", "怒"], translation: "People's indignation grew." },
    { sentence: "*いなびかり*が はしった。", target: "雷", reading: "いなびかり", options: ["雷", "嵐", "霧", "露"], translation: "Lightning flashed across the sky." },
    { sentence: "*あいまい*な ひょうげんは さけましょう。", target: "曖", reading: "あいまい", options: ["曖", "昧", "朧", "暫"], translation: "Let's avoid ambiguous expressions." }
  ]
};
