// JLPT N2 Kanji Dataset (~180 kanji)
export const N2_KANJI_DATA = {
  economics: [
    { char: '貿', meaning: 'Trade', onyomi: 'bou', kunyomi: '-' },
    { char: '易', meaning: 'Easy / Exchange', onyomi: 'eki/i', kunyomi: 'yasa' },
    { char: '輸', meaning: 'Transport', onyomi: 'yu', kunyomi: '-' },
    { char: '導', meaning: 'Guide / Lead', onyomi: 'dou', kunyomi: 'michibi' },
    { char: '資', meaning: 'Resources / Capital', onyomi: 'shi', kunyomi: '-' },
    { char: '財', meaning: 'Wealth / Property', onyomi: 'zai/sai', kunyomi: '-' },
    { char: '貯', meaning: 'Save / Store', onyomi: 'cho', kunyomi: 'ta' },
    { char: '蓄', meaning: 'Accumulate', onyomi: 'chiku', kunyomi: 'takuwa' },
    { char: '株', meaning: 'Stock / Share', onyomi: 'kabu', kunyomi: '-' },
    { char: '投', meaning: 'Throw / Invest', onyomi: 'tou', kunyomi: 'na' },
    { char: '融', meaning: 'Fuse / Finance', onyomi: 'yuu', kunyomi: 'to' },
    { char: '銀', meaning: 'Silver / Bank', onyomi: 'gin', kunyomi: 'shirogane' },
    { char: '預', meaning: 'Deposit', onyomi: 'yo', kunyomi: 'azu' },
    { char: '債', meaning: 'Debt / Bond', onyomi: 'sai', kunyomi: '-' },
    { char: '券', meaning: 'Ticket / Bond', onyomi: 'ken', kunyomi: '-' },
    { char: '為', meaning: 'Purpose / Sake', onyomi: 'i', kunyomi: 'tame/na' },
    { char: '替', meaning: 'Exchange / Replace', onyomi: 'tai', kunyomi: 'ka' },
    { char: '基', meaning: 'Base / Foundation', onyomi: 'ki', kunyomi: 'moto' },
    { char: '準', meaning: 'Standard / Level', onyomi: 'jun', kunyomi: '-' },
    { char: '額', meaning: 'Amount / Forehead', onyomi: 'gaku', kunyomi: 'hitai' }
  ],
  politics: [
    { char: '憲', meaning: 'Constitution', onyomi: 'ken', kunyomi: '-' },
    { char: '閣', meaning: 'Cabinet / Tower', onyomi: 'kaku', kunyomi: '-' },
    { char: '裁', meaning: 'Judge / Cut', onyomi: 'sai', kunyomi: 'ta/saba' },
    { char: '判', meaning: 'Judge / Decide', onyomi: 'han/ban', kunyomi: 'waka' },
    { char: '罪', meaning: 'Crime / Sin', onyomi: 'zai', kunyomi: 'tsumi' },
    { char: '罰', meaning: 'Punishment', onyomi: 'batsu/bachi', kunyomi: '-' },
    { char: '刑', meaning: 'Penalty / Punishment', onyomi: 'kei', kunyomi: '-' },
    { char: '証', meaning: 'Evidence / Proof', onyomi: 'shou', kunyomi: 'akashi' },
    { char: '認', meaning: 'Recognize / Approve', onyomi: 'nin', kunyomi: 'mito' },
    { char: '許', meaning: 'Permit / Allow', onyomi: 'kyo', kunyomi: 'yuru' },
    { char: '否', meaning: 'Deny / Negate', onyomi: 'hi', kunyomi: 'ina' },
    { char: '賛', meaning: 'Approve / Agree', onyomi: 'san', kunyomi: '-' },
    { char: '反', meaning: 'Oppose / Anti-', onyomi: 'han/hon/tan', kunyomi: 'so' },
    { char: '対', meaning: 'Opposite / Against', onyomi: 'tai/tsui', kunyomi: '-' },
    { char: '策', meaning: 'Plan / Measure', onyomi: 'saku', kunyomi: '-' },
    { char: '案', meaning: 'Plan / Proposal', onyomi: 'an', kunyomi: '-' },
    { char: '革', meaning: 'Reform / Leather', onyomi: 'kaku', kunyomi: 'kawa' },
    { char: '改', meaning: 'Reform / Improve', onyomi: 'kai', kunyomi: 'arata' },
    { char: '構', meaning: 'Structure / Build', onyomi: 'kou', kunyomi: 'kama' },
    { char: '造', meaning: 'Create / Build', onyomi: 'zou', kunyomi: 'tsuku' }
  ],
  philosophy: [
    { char: '哲', meaning: 'Philosophy', onyomi: 'tetsu', kunyomi: '-' },
    { char: '思', meaning: 'Think / Consider', onyomi: 'shi', kunyomi: 'omo' },
    { char: '想', meaning: 'Imagination / Idea', onyomi: 'sou', kunyomi: '-' },
    { char: '概', meaning: 'Outline / General', onyomi: 'gai', kunyomi: 'oumune' },
    { char: '念', meaning: 'Sense / Idea', onyomi: 'nen', kunyomi: '-' },
    { char: '観', meaning: 'View / Observe', onyomi: 'kan', kunyomi: 'mi' },
    { char: '察', meaning: 'Guess / Inspect', onyomi: 'satsu', kunyomi: '-' },
    { char: '省', meaning: 'Reflect / Ministry', onyomi: 'sei/shou', kunyomi: 'kaeri/habuku' },
    { char: '識', meaning: 'Recognize / Knowledge', onyomi: 'shiki', kunyomi: '-' },
    { char: '意', meaning: 'Meaning / Intention', onyomi: 'i', kunyomi: '-' },
    { char: '志', meaning: 'Will / Ambition', onyomi: 'shi', kunyomi: 'kokorozashi' },
    { char: '精', meaning: 'Spirit / Refined', onyomi: 'sei/shou', kunyomi: '-' },
    { char: '神', meaning: 'God / Spirit', onyomi: 'shin/jin', kunyomi: 'kami/kanzashi' },
    { char: '魂', meaning: 'Soul', onyomi: 'kon', kunyomi: 'tamashii' },
    { char: '宗', meaning: 'Religion / Sect', onyomi: 'shuu/sou', kunyomi: 'mune' },
    { char: '教', meaning: 'Teach / Religion', onyomi: 'kyou', kunyomi: 'oshi' },
    { char: '徳', meaning: 'Virtue / Morality', onyomi: 'toku', kunyomi: '-' },
    { char: '善', meaning: 'Goodness / Virtue', onyomi: 'zen', kunyomi: 'yo' },
    { char: '悪', meaning: 'Evil / Bad', onyomi: 'aku/o', kunyomi: 'waru' },
    { char: '義', meaning: 'Righteousness', onyomi: 'gi', kunyomi: '-' }
  ],
  literature: [
    { char: '詞', meaning: 'Word / Part of Speech', onyomi: 'shi', kunyomi: 'kotoba' },
    { char: '句', meaning: 'Phrase / Clause', onyomi: 'ku', kunyomi: '-' },
    { char: '節', meaning: 'Verse / Section', onyomi: 'setsu/sechi', kunyomi: 'fushi' },
    { char: '章', meaning: 'Chapter / Badge', onyomi: 'shou', kunyomi: '-' },
    { char: '段', meaning: 'Paragraph / Step', onyomi: 'dan', kunyomi: '-' },
    { char: '巻', meaning: 'Volume / Scroll', onyomi: 'kan', kunyomi: 'ma' },
    { char: '著', meaning: 'Author / Publish', onyomi: 'cho', kunyomi: 'arawasu/ichijiru' },
    { char: '編', meaning: 'Edit / Compile', onyomi: 'hen', kunyomi: 'a' },
    { char: '訳', meaning: 'Translate / Reason', onyomi: 'yaku', kunyomi: 'wake' },
    { char: '批', meaning: 'Criticize', onyomi: 'hi', kunyomi: '-' },
    { char: '評', meaning: 'Evaluate / Critique', onyomi: 'hyou', kunyomi: '-' },
    { char: '価', meaning: 'Value / Price', onyomi: 'ka/ke', kunyomi: 'atai' },
    { char: '描', meaning: 'Sketch / Depict', onyomi: 'byou', kunyomi: 'ega/ka' },
    { char: '表', meaning: 'Express / Surface', onyomi: 'hyou', kunyomi: 'omote/arawa' },
    { char: '現', meaning: 'Appear / Present', onyomi: 'gen', kunyomi: 'arawa' },
    { char: '象', meaning: 'Phenomenon / Elephant', onyomi: 'shou/zou', kunyomi: '-' },
    { char: '抽', meaning: 'Abstract / Draw', onyomi: 'chuu', kunyomi: '-' },
    { char: '複', meaning: 'Duplicate / Complex', onyomi: 'fuku', kunyomi: '-' },
    { char: '雑', meaning: 'Miscellaneous / Mixed', onyomi: 'zatsu/zou', kunyomi: '-' },
    { char: '創', meaning: 'Create / Original', onyomi: 'sou', kunyomi: 'tsuku/haji' }
  ],
  advanced_abstract: [
    { char: '影', meaning: 'Shadow / Influence', onyomi: 'ei', kunyomi: 'kage' },
    { char: '響', meaning: 'Echo / Influence', onyomi: 'kyou', kunyomi: 'hibi' },
    { char: '効', meaning: 'Effect / Efficacy', onyomi: 'kou', kunyomi: 'ki' },
    { char: '果', meaning: 'Result / Fruit', onyomi: 'ka', kunyomi: 'ha/kuda' },
    { char: '因', meaning: 'Cause / Factor', onyomi: 'in', kunyomi: 'yo' },
    { char: '素', meaning: 'Element / Simple', onyomi: 'so/su', kunyomi: 'moto' },
    { char: '件', meaning: 'Matter / Case', onyomi: 'ken', kunyomi: '-' },
    { char: '状', meaning: 'Condition / Letter', onyomi: 'jou', kunyomi: '-' },
    { char: '態', meaning: 'Attitude / State', onyomi: 'tai', kunyomi: 'waza' },
    { char: '況', meaning: 'Condition / Situation', onyomi: 'kyou', kunyomi: '-' },
    { char: '際', meaning: 'Occasion / Edge', onyomi: 'sai', kunyomi: 'kiwa' },
    { char: '限', meaning: 'Limit', onyomi: 'gen', kunyomi: 'kagi' },
    { char: '極', meaning: 'Extreme / Pole', onyomi: 'kyoku/goku', kunyomi: 'kiwa' },
    { char: '端', meaning: 'End / Edge', onyomi: 'tan', kunyomi: 'hashi/ha/hata' },
    { char: '均', meaning: 'Average / Equal', onyomi: 'kin', kunyomi: '-' },
    { char: '衡', meaning: 'Balance / Scale', onyomi: 'kou', kunyomi: '-' },
    { char: '比', meaning: 'Compare / Ratio', onyomi: 'hi', kunyomi: 'kura' },
    { char: '較', meaning: 'Compare', onyomi: 'kaku', kunyomi: '-' },
    { char: '差', meaning: 'Difference / Gap', onyomi: 'sa', kunyomi: 'sa' },
    { char: '異', meaning: 'Different / Strange', onyomi: 'i', kunyomi: 'koto' }
  ],
  technology: [
    { char: '機', meaning: 'Machine / Opportunity', onyomi: 'ki', kunyomi: 'hata' },
    { char: '器', meaning: 'Tool / Device', onyomi: 'ki', kunyomi: 'utsuwa' },
    { char: '装', meaning: 'Equip / Install', onyomi: 'sou/shou', kunyomi: 'yosoo' },
    { char: '置', meaning: 'Put / Set up', onyomi: 'chi', kunyomi: 'o' },
    { char: '操', meaning: 'Operate / Manipulate', onyomi: 'sou', kunyomi: 'misao/ayatsu' },
    { char: '作', meaning: 'Make / Produce', onyomi: 'saku/sa', kunyomi: 'tsuku' },
    { char: '組', meaning: 'Assemble / Group', onyomi: 'so', kunyomi: 'ku/kumi' },
    { char: '設', meaning: 'Establish / Set up', onyomi: 'setsu', kunyomi: 'mou' },
    { char: '備', meaning: 'Equip / Prepare', onyomi: 'bi', kunyomi: 'sona' },
    { char: '供', meaning: 'Offer / Provide', onyomi: 'kyou/ku', kunyomi: 'sona/tomo' },
    { char: '接', meaning: 'Contact / Connect', onyomi: 'setsu', kunyomi: 'tsu' },
    { char: '続', meaning: 'Continue / Connect', onyomi: 'zoku', kunyomi: 'tsuzu' },
    { char: '断', meaning: 'Cut / Refuse', onyomi: 'dan', kunyomi: 'ta/koto' },
    { char: '絶', meaning: 'Sever / Cease', onyomi: 'zetsu', kunyomi: 'ta' },
    { char: '替', meaning: 'Exchange / Replace', onyomi: 'tai', kunyomi: 'ka' },
    { char: '換', meaning: 'Exchange / Substitute', onyomi: 'kan', kunyomi: 'ka' },
    { char: '修', meaning: 'Repair / Study', onyomi: 'shuu/shu', kunyomi: 'osa' },
    { char: '復', meaning: 'Restore / Repeat', onyomi: 'fuku', kunyomi: '-' },
    { char: '更', meaning: 'Renew / Change', onyomi: 'kou', kunyomi: 'sara/fu' },
    { char: '新', meaning: 'New', onyomi: 'shin', kunyomi: 'atara/arata' }
  ],
  sociology: [
    { char: '職', meaning: 'Job / Occupation', onyomi: 'shoku', kunyomi: '-' },
    { char: '労', meaning: 'Labor / Effort', onyomi: 'rou', kunyomi: '-' },
    { char: '努', meaning: 'Effort / Strive', onyomi: 'do', kunyomi: 'tsuto' },
    { char: '任', meaning: 'Responsibility', onyomi: 'nin', kunyomi: 'maka' },
    { char: '務', meaning: 'Duty / Service', onyomi: 'mu', kunyomi: 'tsuto' },
    { char: '責', meaning: 'Blame / Responsibility', onyomi: 'seki', kunyomi: 'se' },
    { char: '担', meaning: 'Bear / Carry', onyomi: 'tan', kunyomi: 'nina/katu' },
    { char: '能', meaning: 'Ability / Talent', onyomi: 'nou', kunyomi: '-' },
    { char: '率', meaning: 'Rate / Lead', onyomi: 'ritsu/sotsu', kunyomi: 'hikii' },
    { char: '値', meaning: 'Value / Price', onyomi: 'chi', kunyomi: 'ne/atai' },
    { char: '適', meaning: 'Suitable / Proper', onyomi: 'teki', kunyomi: '-' },
    { char: '応', meaning: 'Respond / Apply', onyomi: 'ou', kunyomi: '-' },
    { char: '依', meaning: 'Rely on / Based on', onyomi: 'i/e', kunyomi: '-' },
    { char: '存', meaning: 'Exist / Know', onyomi: 'son/zon', kunyomi: '-' },
    { char: '在', meaning: 'Exist / Located', onyomi: 'zai', kunyomi: 'a' },
    { char: '属', meaning: 'Belong', onyomi: 'zoku', kunyomi: '-' },
    { char: '系', meaning: 'System / Line', onyomi: 'kei', kunyomi: '-' },
    { char: '統', meaning: 'Tradition / System', onyomi: 'tou', kunyomi: 'su' },
    { char: '示', meaning: 'Show / Display', onyomi: 'ji/shi', kunyomi: 'shime' },
    { char: '占', meaning: 'Fortune / Occupy', onyomi: 'sen', kunyomi: 'urana/shi' }
  ],
  body_medicine: [
    { char: '脳', meaning: 'Brain', onyomi: 'nou', kunyomi: '-' },
    { char: '肺', meaning: 'Lung', onyomi: 'hai', kunyomi: '-' },
    { char: '胃', meaning: 'Stomach', onyomi: 'i', kunyomi: '-' },
    { char: '腸', meaning: 'Intestine', onyomi: 'chou', kunyomi: '-' },
    { char: '骨', meaning: 'Bone', onyomi: 'kotsu', kunyomi: 'hone' },
    { char: '筋', meaning: 'Muscle / Tendon', onyomi: 'kin', kunyomi: 'suji' },
    { char: '血', meaning: 'Blood', onyomi: 'ketsu', kunyomi: 'chi' },
    { char: '皮', meaning: 'Skin / Leather', onyomi: 'hi', kunyomi: 'kawa' },
    { char: '毛', meaning: 'Hair / Fur', onyomi: 'mou', kunyomi: 'ke' },
    { char: '爪', meaning: 'Nail / Claw', onyomi: 'sou', kunyomi: 'tsume' },
    { char: '症', meaning: 'Symptoms', onyomi: 'shou', kunyomi: '-' },
    { char: '療', meaning: 'Treatment / Cure', onyomi: 'ryou', kunyomi: '-' },
    { char: '診', meaning: 'Examine / Diagnose', onyomi: 'shin', kunyomi: 'mi' },
    { char: '処', meaning: 'Treat / Handle', onyomi: 'sho', kunyomi: '-' },
    { char: '方', meaning: 'Direction / Method', onyomi: 'hou', kunyomi: 'kata' },
    { char: '染', meaning: 'Dye / Infect', onyomi: 'sen', kunyomi: 'so/shi' },
    { char: '菌', meaning: 'Germ / Bacteria', onyomi: 'kin', kunyomi: '-' },
    { char: '毒', meaning: 'Poison / Virus', onyomi: 'doku', kunyomi: '-' },
    { char: '免', meaning: 'Exempt / Immunity', onyomi: 'men', kunyomi: 'manuka' },
    { char: '疫', meaning: 'Epidemic', onyomi: 'eki/yaku', kunyomi: '-' }
  ]
};

export const N2_EXAM_DATA = {
  easy: [
    { sentence: "*ぼうえき*の しごとを して います。", target: "貿", reading: "ぼう", options: ["貿", "易", "売", "買"], translation: "I work in trade." },
    { sentence: "ぎんこうに おかねを *あず*けます。", target: "預", reading: "あず", options: ["預", "貯", "蓄", "財"], translation: "I deposit money at the bank." },
    { sentence: "この *きかい*は とても べんりです。", target: "機", reading: "き", options: ["機", "器", "械", "装"], translation: "This machine is very convenient." },
    { sentence: "*しょくぎょう*は なんですか。", target: "職", reading: "しょく", options: ["職", "労", "務", "任"], translation: "What is your occupation?" },
    { sentence: "*のう*の はたらきを けんきゅうします。", target: "脳", reading: "のう", options: ["脳", "肺", "胃", "腸"], translation: "I study brain function." }
  ],
  mid: [
    { sentence: "*けんぽう*は くにの きほんほうです。", target: "憲", reading: "けん", options: ["憲", "法", "律", "制"], translation: "The constitution is the fundamental law of the nation." },
    { sentence: "この もんだいの *げんいん*は なんですか。", target: "因", reading: "いん", options: ["因", "果", "素", "件"], translation: "What is the cause of this problem?" },
    { sentence: "*ひかく*する ことが だいじです。", target: "較", reading: "かく", options: ["較", "比", "差", "異"], translation: "It is important to compare." },
    { sentence: "しゃかいに *こうけん*する。", target: "貢", reading: "こう", options: ["貢", "献", "任", "務"], translation: "Contribute to society." },
    { sentence: "*てつがく*は おもしろい がくもんです。", target: "哲", reading: "てつ", options: ["哲", "思", "想", "念"], translation: "Philosophy is an interesting subject." }
  ],
  hard: [
    { sentence: "*さいばん*で はんけつが でました。", target: "裁", reading: "さい", options: ["裁", "判", "罪", "罰"], translation: "The judgment was given at trial." },
    { sentence: "かいしゃの *こうぞう*を かえます。", target: "構", reading: "こう", options: ["構", "造", "設", "備"], translation: "We will change the company structure." },
    { sentence: "この ちりょうほうは *こうか*が あります。", target: "効", reading: "こう", options: ["効", "果", "影", "響"], translation: "This treatment is effective." },
    { char: '著', sentence: "この *ちょしゃ*は ゆうめいです。", target: "著", reading: "ちょ", options: ["著", "編", "訳", "版"], translation: "This author is famous." },
    { sentence: "わたしは *めんえき*を べんきょうして います。", target: "免", reading: "めん", options: ["免", "疫", "菌", "毒"], translation: "I am studying immunology." }
  ],
  top_hard: [
    { sentence: "*かくめい*てきな ぎじゅつが うまれた。", target: "革", reading: "かく", options: ["革", "改", "造", "創"], translation: "A revolutionary technology was born." },
    { sentence: "さまざまな *しゅうきょう*が あります。", target: "宗", reading: "しゅう", options: ["宗", "教", "神", "魂"], translation: "There are various religions." },
    { sentence: "かれの *えいきょうりょく*は おおきい。", target: "響", reading: "きょう", options: ["響", "影", "効", "果"], translation: "His influence is large." },
    { sentence: "*ちゅうしょう*てきな がいねんです。", target: "抽", reading: "ちゅう", options: ["抽", "象", "複", "雑"], translation: "It is an abstract concept." },
    { sentence: "*ぎむ*を はたさなければ なりません。", target: "義", reading: "ぎ", options: ["義", "善", "徳", "務"], translation: "You must fulfill your duty." }
  ]
};
