// JLPT N2 Kanji Dataset (~180 kanji)
export const N2_KANJI_DATA = {
  abstract: [
    { char: '亜', meaning: 'Sub-', onyomi: 'a', kunyomi: '-' },
    { char: '哀', meaning: 'Pathetic', onyomi: 'ai', kunyomi: 'awa' },
    { char: '依', meaning: 'Reliant', onyomi: 'i/e', kunyomi: '-' },
    { char: '偉', meaning: 'Great', onyomi: 'i', kunyomi: 'era' },
    { char: '威', meaning: 'Majesty', onyomi: 'i', kunyomi: '-' },
    { char: '尉', meaning: 'Officer', onyomi: 'i', kunyomi: '-' },
    { char: '慰', meaning: 'Console', onyomi: 'i', kunyomi: 'nasa' },
    { char: '為', meaning: 'Sake/Do', onyomi: 'i', kunyomi: 'tame' },
    { char: '維', meaning: 'Maintenance', onyomi: 'i', kunyomi: '-' },
    { char: '緯', meaning: 'Latitude', onyomi: 'i', kunyomi: '-' },
    { char: '遺', meaning: 'Bequeath', onyomi: 'i/yui', kunyomi: '-' },
    { char: '壱', meaning: 'One', onyomi: 'ichi', kunyomi: '-' },
    { char: '逸', meaning: 'Deviate', onyomi: 'itsu', kunyomi: '-' },
    { char: '韻', meaning: 'Rhyme', onyomi: 'in', kunyomi: '-' },
    { char: '永', meaning: 'Eternal', onyomi: 'ei', kunyomi: 'naga' },
    { char: '延', meaning: 'Prolong', onyomi: 'en', kunyomi: 'no' },
    { char: '縁', meaning: 'Fate/Edge', onyomi: 'en', kunyomi: 'fuchi' },
    { char: '艶', meaning: 'Glossy', onyomi: 'en', kunyomi: 'tsuya' },
    { char: '億', meaning: '100 Million', onyomi: 'oku', kunyomi: '-' },
    { char: '憶', meaning: 'Recollect', onyomi: 'oku', kunyomi: '-' },
    { char: '臆', meaning: 'Timid', onyomi: 'oku', kunyomi: '-' },
    { char: '乙', meaning: 'Second', onyomi: 'otsu', kunyomi: 'oto' },
    { char: '恩', meaning: 'Grace', onyomi: 'on', kunyomi: '-' },
    { char: '穏', meaning: 'Calm', onyomi: 'on', kunyomi: 'oda' },
    { char: '佳', meaning: 'Excellent', onyomi: 'ka', kunyomi: '-' },
    { char: '仮', meaning: 'Temporary', onyomi: 'ka/ke', kunyomi: 'kari' },
    { char: '何', meaning: 'What', onyomi: 'ka', kunyomi: 'nani/nan' },
    { char: '苛', meaning: 'Torment', onyomi: 'ka', kunyomi: '-' },
    { char: '架', meaning: 'Rack/Bridge', onyomi: 'ka', kunyomi: 'ka' },
    { char: '華', meaning: 'Flower/Splendor', onyomi: 'ka/ge', kunyomi: 'hana' },
    { char: '禍', meaning: 'Calamity', onyomi: 'ka', kunyomi: '-' },
    { char: '快', meaning: 'Pleasant/Fast', onyomi: 'kai', kunyomi: 'kokoro' },
    { char: '戒', meaning: 'Commandment', onyomi: 'kai', kunyomi: 'imasame' },
    { char: '怪', meaning: 'Strange', onyomi: 'kai', kunyomi: 'aya' },
    { char: '皆', meaning: 'All/Everyone', onyomi: 'kai', kunyomi: 'mina' },
    { char: '楷', meaning: 'Square Style', onyomi: 'kai', kunyomi: '-' },
    { char: '諧', meaning: 'Harmony', onyomi: 'kai', kunyomi: '-' },
    { char: '劾', meaning: 'Censure', onyomi: 'gai', kunyomi: '-' },
    { char: '慨', meaning: 'Lament/Deplore', onyomi: 'gai', kunyomi: '-' },
    { char: '該', meaning: 'Above-stated', onyomi: 'gai', kunyomi: '-' },
    { char: '概', meaning: 'Outline', onyomi: 'gai', kunyomi: 'oumune' },
    { char: '較', meaning: 'Compare', onyomi: 'kaku', kunyomi: '-' },
    { char: '郭', meaning: 'Enclosure', onyomi: 'kaku', kunyomi: '-' },
    { char: '嚇', meaning: 'Threaten', onyomi: 'kaku', kunyomi: 'odo' },
    { char: '且', meaning: 'Moreover', onyomi: 'sho', kunyomi: 'ka' },
    { char: '勘', meaning: 'Intuition/Check', onyomi: 'kan', kunyomi: '-' },
    { char: '敢', meaning: 'Daring', onyomi: 'kan', kunyomi: 'ae' },
    { char: '歓', meaning: 'Delight', onyomi: 'kan', kunyomi: '-' },
    { char: '及', meaning: 'Reach/Attain', onyomi: 'kyuu', kunyomi: 'oyo' },
    { char: '去', meaning: 'Past/Leave', onyomi: 'kyo/ko', kunyomi: 'sa' },
    { char: '巨', meaning: 'Gigantic', onyomi: 'kyo', kunyomi: '-' },
    { char: '虚', meaning: 'Void', onyomi: 'kyo/ko', kunyomi: 'muna' },
    { char: '許', meaning: 'Permit', onyomi: 'kyo', kunyomi: 'yuru' },
    { char: '凶', meaning: 'Evil/Misfortune', onyomi: 'kyou', kunyomi: '-' },
    { char: '況', meaning: 'Condition', onyomi: 'kyou', kunyomi: '-' },
    { char: '共', meaning: 'Together', onyomi: 'kyou', kunyomi: 'tomo' },
    { char: '凶', meaning: 'Evil/Misfortune', onyomi: 'kyou', kunyomi: '-' },
    { char: '協', meaning: 'Cooperate', onyomi: 'kyou', kunyomi: '-' },
    { char: '恭', meaning: 'Respectful', onyomi: 'kyou', kunyomi: 'uyauya' },
    { char: '郷', meaning: 'Home town', onyomi: 'kyou/gou', kunyomi: 'sato' },
    { char: '暁', meaning: 'Dawn', onyomi: 'gyou', kunyomi: 'akatuki' },
    { char: '凝', meaning: 'Congeal/Freeze', onyomi: 'gyou', kunyomi: 'ko' },
    { char: '屈', meaning: 'Yield/Bend', onyomi: 'kutsu', kunyomi: '-' },
    { char: '勲', meaning: 'Merit/Order', onyomi: 'kun', kunyomi: '-' },
    { char: '啓', meaning: 'Reveal/Enlighten', onyomi: 'kei', kunyomi: '-' },
    { char: '憩', meaning: 'Rest', onyomi: 'kei', kunyomi: 'iko' },
    { char: '潔', meaning: 'Pure/Clean', onyomi: 'ketsu', kunyomi: 'isagiyo' },
    { char: '嫌', meaning: 'Dislike', onyomi: 'ken', kunyomi: 'kira/ira' },
    { char: '献', meaning: 'Offering', onyomi: 'ken/kon', kunyomi: 'sasa' },
    { char: '賢', meaning: 'Wise', onyomi: 'ken', kunyomi: 'kasiko' },
    { char: '謙', meaning: 'Humble', onyomi: 'ken', kunyomi: '-' },
    { char: '顕', meaning: 'Manifest', onyomi: 'ken', kunyomi: '-' },
    { char: '懸', meaning: 'Suspend/Hang', onyomi: 'ken/ke', kunyomi: 'ka' },
    { char: '幻', meaning: 'Phantasm/Vision', onyomi: 'gen', kunyomi: 'maboroshi' },
    { char: '玄', meaning: 'Mysterious/Black', onyomi: 'gen', kunyomi: '-' },
    { char: '厳', meaning: 'Strict/Severe', onyomi: 'gen/gon', kunyomi: 'kibi' },
    { char: '弧', meaning: 'Arc/Arch', onyomi: 'ko', kunyomi: '-' },
    { char: '固', meaning: 'Hard/Solid', onyomi: 'ko', kunyomi: 'kata' },
    { char: '孤', meaning: 'Orphan/Alone', onyomi: 'ko', kunyomi: '-' },
    { char: '個', meaning: 'Individual', onyomi: 'ko', kunyomi: '-' },
    { char: '悟', meaning: 'Enlightenment', onyomi: 'go', kunyomi: 'sato' },
    { char: '誤', meaning: 'Mistake', onyomi: 'go', kunyomi: 'ayama' }
  ],
  actions: [
    { char: '握', meaning: 'Grip', onyomi: 'aku', kunyomi: 'nigi' },
    { char: '扱', meaning: 'Handle', onyomi: 'sou', kunyomi: 'atuka' },
    { char: '違', meaning: 'Differ', onyomi: 'i', kunyomi: 'tiga' },
    { char: '隠', meaning: 'Hide', onyomi: 'in', kunyomi: 'kaku' },
    { char: '営', meaning: 'Manage', onyomi: 'ei', kunyomi: 'itona' },
    { char: '映', meaning: 'Reflect', onyomi: 'ei', kunyomi: 'utsu' },
    { char: '演', meaning: 'Perform', onyomi: 'en', kunyomi: '-' },
    { char: '汚', meaning: 'Dirty', onyomi: 'o', kunyomi: 'kega/yo' },
    { char: '殴', meaning: 'Hit', onyomi: 'ou', kunyomi: 'nagu' },
    { char: '嫁', meaning: 'Bride/Marry', onyomi: 'ka', kunyomi: 'yome/totu' },
    { char: '過', meaning: 'Exceed', onyomi: 'ka', kunyomi: 'su' },
    { char: '歌', meaning: 'Song/Sing', onyomi: 'ka', kunyomi: 'uta' },
    { char: '稼', meaning: 'Earn', onyomi: 'ka', kunyomi: 'kase' },
    { char: '画', meaning: 'Stroke/Plan', onyomi: 'ga/kaku', kunyomi: 'ega' },
    { char: '賀', meaning: 'Congratulate', onyomi: 'ga', kunyomi: '-' },
    { char: '介', meaning: 'Mediate', onyomi: 'kai', kunyomi: '-' },
    { char: '回', meaning: 'Times/Round', onyomi: 'kai', kunyomi: 'mawa' },
    { char: '改', meaning: 'Reform/Update', onyomi: 'kai', kunyomi: 'arata' },
    { char: '拐', meaning: 'Kidnap', onyomi: 'kai', kunyomi: '-' },
    { char: '悔', meaning: 'Regret', onyomi: 'kai', kunyomi: 'ku' },
    { char: '開', meaning: 'Open', onyomi: 'kai', kunyomi: 'a/hira' },
    { char: '解', meaning: 'Untie/Solution', onyomi: 'kai/ge', kunyomi: 'to' },
    { char: '潰', meaning: 'Crush', onyomi: 'kai', kunyomi: 'tsubu' },
    { char: '壊', meaning: 'Break', onyomi: 'kai', kunyomi: 'kowa' },
    { char: '懐', meaning: 'Pocket/Yearn', onyomi: 'kai', kunyomi: 'futo/natsu' },
    { char: '拡', meaning: 'Expand', onyomi: 'kaku', kunyomi: 'hiro' },
    { char: '格', meaning: 'Status/Rank', onyomi: 'kaku/kou', kunyomi: '-' },
    { char: '覚', meaning: 'Memorize/Wake', onyomi: 'kaku', kunyomi: 'obo/sa' },
    { char: '確', meaning: 'Certain', onyomi: 'kaku', kunyomi: 'tashi' },
    { char: '獲', meaning: 'Capture', onyomi: 'kaku', kunyomi: 'e' },
    { char: '穫', meaning: 'Harvest', onyomi: 'kaku', kunyomi: '-' },
    { char: '掛', meaning: 'Hang', onyomi: 'kai', kunyomi: 'ka' },
    { char: '括', meaning: 'Fasten/Tie', onyomi: 'katsu', kunyomi: 'kuku' },
    { char: '活', meaning: 'Lively', onyomi: 'katsu', kunyomi: 'i' },
    { char: '割', meaning: 'Divide/Split', onyomi: 'katsu', kunyomi: 'wa' },
    { char: '滑', meaning: 'Slide/Slip', onyomi: 'katsu/kotu', kunyomi: 'sube/name' },
    { char: '刈', meaning: 'Mow/Reap', onyomi: 'gai', kunyomi: 'ka' },
    { char: '幹', meaning: 'Trunk/Main', onyomi: 'kan', kunyomi: 'miki' },
    { char: '巻', meaning: 'Roll/Volume', onyomi: 'kan', kunyomi: 'ma' },
    { char: '看', meaning: 'Watch/See', onyomi: 'kan', kunyomi: '-' },
    { char: '陥', meaning: 'Collapse', onyomi: 'kan', kunyomi: 'ochi' },
    { char: '乾', meaning: 'Dry', onyomi: 'kan', kunyomi: 'kawa' },
    { char: '換', meaning: 'Exchange', onyomi: 'kan', kunyomi: 'ka' },
    { char: '汲', meaning: 'Scoop water', onyomi: 'kyuu', kunyomi: 'ku' },
    { char: '吸', meaning: 'Suck/Inhale', onyomi: 'kyuu', kunyomi: 'su' },
    { char: '糾', meaning: 'Twist/Investigate', onyomi: 'kyuu', kunyomi: '-' },
    { char: '居', meaning: 'Reside', onyomi: 'kyo', kunyomi: 'i' },
    { char: '拒', meaning: 'Refuse', onyomi: 'kyo', kunyomi: 'koba' },
    { char: '拠', meaning: 'Basis/Base', onyomi: 'kyo/ko', kunyomi: 'yo' },
    { char: '挙', meaning: 'Raise/Election', onyomi: 'kyo', kunyomi: 'a' },
    { char: '競', meaning: 'Compete', onyomi: 'kyou/kei', kunyomi: 'kiso' },
    { char: '狭', meaning: 'Narrow', onyomi: 'kyou', kunyomi: 'sema' },
    { char: '挟', meaning: 'Pinch/Sandwich', onyomi: 'kyou', kunyomi: 'hasa' },
    { char: '矯', meaning: 'Correct', onyomi: 'kyou', kunyomi: 'ta' },
    { char: '仰', meaning: 'Look up/Respect', onyomi: 'gyou/kou', kunyomi: 'ao' },
    { char: '掘', meaning: 'Dig', onyomi: 'kutsu', kunyomi: 'ho' },
    { char: '繰', meaning: 'Spin/Winding', onyomi: 'sou', kunyomi: 'ku' },
    { char: '係', meaning: 'Charge/Relation', onyomi: 'kei', kunyomi: 'kaka' },
    { char: '契', meaning: 'Pledge/Contract', onyomi: 'kei', kunyomi: 'chigi' },
    { char: '掲', meaning: 'Display/Put up', onyomi: 'kei', kunyomi: 'kaga' },
    { char: '敬', meaning: 'Respect', onyomi: 'kei', kunyomi: 'uyama' },
    { char: '傾', meaning: 'Lean/Incline', onyomi: 'kei', kunyomi: 'katamu' },
    { char: '携', meaning: 'Carry/Handheld', onyomi: 'kei', kunyomi: 'tazu' },
    { char: '継', meaning: 'Inherit/Succeed', onyomi: 'kei', kunyomi: 'tsu' },
    { char: '稽', meaning: 'Practice/Study', onyomi: 'kei', kunyomi: '-' },
    { char: '警', meaning: 'Guard/Warn', onyomi: 'kei', kunyomi: '-' },
    { char: '迎', meaning: 'Welcome/Meet', onyomi: 'gei', kunyomi: 'muka' },
    { char: '劇', meaning: 'Drama/Play', onyomi: 'geki', kunyomi: '-' },
    { char: '撃', meaning: 'Attack', onyomi: 'geki', kunyomi: 'u' },
    { char: '激', meaning: 'Violent/Intense', onyomi: 'geki', kunyomi: 'hage' },
    { char: '決', meaning: 'Decide', onyomi: 'ketsu', kunyomi: 'ki' },
    { char: '結', meaning: 'Tie/Join', onyomi: 'ketsu', kunyomi: 'mu/yu' },
    { char: '建', meaning: 'Build', onyomi: 'ken', kunyomi: 'ta' },
    { char: '研', meaning: 'Polish/Study', onyomi: 'ken', kunyomi: 'to' },
    { char: '兼', meaning: 'Concurrently', onyomi: 'ken', kunyomi: 'ka' },
    { char: '検', meaning: 'Examine', onyomi: 'ken', kunyomi: '-' },
    { char: '遣', meaning: 'Dispatch', onyomi: 'ken', kunyomi: 'tsuka' },
    { char: '験', meaning: 'Test', onyomi: 'ken', kunyomi: '-' },
    { char: '言', meaning: 'Say/Word', onyomi: 'gen/gon', kunyomi: 'i/koto' },
    { char: '限', meaning: 'Limit', onyomi: 'gen', kunyomi: 'kagi' },
    { char: '呼', meaning: 'Call', onyomi: 'ko', kunyomi: 'yo' },
    { char: '雇', meaning: 'Employ', onyomi: 'ko', kunyomi: 'yato' },
    { char: '誇', meaning: 'Boast', onyomi: 'ko', kunyomi: 'ho' },
    { char: '顧', meaning: 'Look back/Customer', onyomi: 'ko', kunyomi: 'kaeri' },
    { char: '語', meaning: 'Language/Talk', onyomi: 'go', kunyomi: 'kata' }
  ],
  nature_society: [
    { char: '圧', meaning: 'Pressure', onyomi: 'atsu', kunyomi: '-' },
    { char: '宛', meaning: 'Address', onyomi: 'en', kunyomi: 'ate' },
    { char: '嵐', meaning: 'Storm', onyomi: 'ran', kunyomi: 'arashi' },
    { char: '域', meaning: 'Region', onyomi: 'iki', kunyomi: '-' },
    { char: '芋', meaning: 'Potato', onyomi: 'u', kunyomi: 'imo' },
    { char: '陰', meaning: 'Shadow/Secret', onyomi: 'in', kunyomi: 'kage' },
    { char: '宇', meaning: 'Universe', onyomi: 'u', kunyomi: '-' },
    { char: '渦', meaning: 'Whirlpool', onyomi: 'ka', kunyomi: 'uzu' },
    { char: '浦', meaning: 'Bay', onyomi: 'ho', kunyomi: 'ura' },
    { char: '衛', meaning: 'Defense', onyomi: 'ei', kunyomi: '-' },
    { char: '沿', meaning: 'Along', onyomi: 'en', kunyomi: 'so' },
    { char: '煙', meaning: 'Smoke', onyomi: 'en', kunyomi: 'kemuri' },
    { char: '鉛', meaning: 'Lead (metal)', onyomi: 'en', kunyomi: 'namari' },
    { char: '欧', meaning: 'Europe', onyomi: 'ou', kunyomi: '-' },
    { char: '翁', meaning: 'Old Man', onyomi: 'ou', kunyomi: '-' },
    { char: '奥', meaning: 'Inside/Back', onyomi: 'ou', kunyomi: 'oku' },
    { char: '卸', meaning: 'Wholesale', onyomi: 'sha', kunyomi: 'oro' },
    { char: '価', meaning: 'Value', onyomi: 'ka', kunyomi: 'atai' },
    { char: '河', meaning: 'River', onyomi: 'ka', kunyomi: 'kawa' },
    { char: '荷', meaning: 'Luggage', onyomi: 'ka', kunyomi: 'ni' },
    { char: '菓', meaning: 'Candy', onyomi: 'ka', kunyomi: '-' },
    { char: '貨', meaning: 'Freight', onyomi: 'ka', kunyomi: '-' },
    { char: '靴', meaning: 'Shoes', onyomi: 'ka', kunyomi: 'kutu' },
    { char: '箇', meaning: 'Counter', onyomi: 'ka', kunyomi: '-' },
    { char: '蚊', meaning: 'Mosquito', onyomi: 'bun', kunyomi: 'ka' },
    { char: '牙', meaning: 'Fang', onyomi: 'ga', kunyomi: 'kiba' },
    { char: '瓦', meaning: 'Tile', onyomi: 'ga', kunyomi: 'kawara' },
    { char: '雅', meaning: 'Elegant', onyomi: 'ga', kunyomi: '-' },
    { char: '餓', meaning: 'Starve', onyomi: 'ga', kunyomi: 'u' },
    { char: '灰', meaning: 'Ash', onyomi: 'kai', kunyomi: 'hai' },
    { char: '海', meaning: 'Sea/Ocean', onyomi: 'kai', kunyomi: 'umi' },
    { char: '界', meaning: 'World/Boundary', onyomi: 'kai', kunyomi: '-' },
    { char: '械', meaning: 'Machine', onyomi: 'kai', kunyomi: '-' },
    { char: '絵', meaning: 'Picture/Painting', onyomi: 'kai/e', kunyomi: '-' },
    { char: '階', meaning: 'Floor/Stair', onyomi: 'kai', kunyomi: '-' },
    { char: '塊', meaning: 'Lump/Mass', onyomi: 'kai', kunyomi: 'katama' },
    { char: '貝', meaning: 'Shell/Shellfish', onyomi: 'bai', kunyomi: 'kai' },
    { char: '外', meaning: 'Outside', onyomi: 'gai/ge', kunyomi: 'soto/hazu' },
    { char: '害', meaning: 'Harm', onyomi: 'gai', kunyomi: '-' },
    { char: '崖', meaning: 'Cliff', onyomi: 'gai', kunyomi: 'gake' },
    { char: '涯', meaning: 'Horizon', onyomi: 'gai', kunyomi: '-' },
    { char: '街', meaning: 'Street/City', onyomi: 'gai/kai', kunyomi: 'machi' },
    { char: '蓋', meaning: 'Cover/Lid', onyomi: 'gai', kunyomi: 'futa' },
    { char: '骸', meaning: 'Skeleton', onyomi: 'gai', kunyomi: '-' },
    { char: '垣', meaning: 'Fence/Hedge', onyomi: 'en', kunyomi: 'kaki' },
    { char: '各', meaning: 'Each', onyomi: 'kaku', kunyomi: 'ono' },
    { char: '角', meaning: 'Corner/Angle', onyomi: 'kaku', kunyomi: 'kado/tsuno' },
    { char: '革', meaning: 'Leather/Reform', onyomi: 'kaku', kunyomi: 'kawa' },
    { char: '核', meaning: 'Core/Nuclear', onyomi: 'kaku', kunyomi: '-' },
    { char: '殻', meaning: 'Shell/Husk', onyomi: 'kaku', kunyomi: 'kara' },
    { char: '隔', meaning: 'Separate', onyomi: 'kaku', kunyomi: 'heda' },
    { char: '閣', meaning: 'Cabinet/Tower', onyomi: 'kaku', kunyomi: '-' },
    { char: '学', meaning: 'Study/Science', onyomi: 'gaku', kunyomi: 'mana' },
    { char: '岳', meaning: 'Peak/Mountain', onyomi: 'gaku', kunyomi: 'take' },
    { char: '楽', meaning: 'Music/Easy', onyomi: 'gaku/raku', kunyomi: 'tano' },
    { char: '額', meaning: 'Amount/Forehead', onyomi: 'gaku', kunyomi: 'hitai' },
    { char: '潟', meaning: 'Lagoon', onyomi: 'seki', kunyomi: 'kata' },
    { char: '喝', meaning: 'Scold/Shout', onyomi: 'katsu', kunyomi: '-' },
    { char: '渇', meaning: 'Thirst', onyomi: 'katsu', kunyomi: 'kawa' },
    { char: '葛', meaning: 'Kudzu', onyomi: 'katsu', kunyomi: 'kuzu' },
    { char: '褐', meaning: 'Brown', onyomi: 'katsu', kunyomi: '-' },
    { char: '轄', meaning: 'Control/Rule', onyomi: 'katsu', kunyomi: '-' },
    { char: '株', meaning: 'Stock/Stump', onyomi: 'chu', kunyomi: 'kabu' },
    { char: '釜', meaning: 'Kettle', onyomi: 'fu', kunyomi: 'kama' },
    { char: '鎌', meaning: 'Sickle', onyomi: 'ren', kunyomi: 'kama' },
    { char: '干', meaning: 'Dry', onyomi: 'kan', kunyomi: 'ho' },
    { char: '刊', meaning: 'Publish', onyomi: 'kan', kunyomi: '-' },
    { char: '甘', meaning: 'Sweet', onyomi: 'kan', kunyomi: 'ama' },
    { char: '汗', meaning: 'Sweat', onyomi: 'kan', kunyomi: 'ase' },
    { char: '缶', meaning: 'Can/Tin', onyomi: 'kan', kunyomi: '-' },
    { char: '完', meaning: 'Complete/Perfect', onyomi: 'kan', kunyomi: '-' },
    { char: '肝', meaning: 'Liver', onyomi: 'kan', kunyomi: 'kimo' },
    { char: '官', meaning: 'Official', onyomi: 'kan', kunyomi: '-' },
    { char: '冠', meaning: 'Crown', onyomi: 'kan', kunyomi: 'kanmuri' },
    { char: '貫', meaning: 'Pierce', onyomi: 'kan', kunyomi: 'turana' },
    { char: '喚', meaning: 'Recall/Summon', onyomi: 'kan', kunyomi: 'yo' },
    { char: '堪', meaning: 'Endure', onyomi: 'kan', kunyomi: 'tame' },
    { char: '棺', meaning: 'Coffin', onyomi: 'kan', kunyomi: '-' },
    { char: '款', meaning: 'Article/Article', onyomi: 'kan', kunyomi: '-' },
    { char: '患', meaning: 'Afflicted', onyomi: 'kan', kunyomi: 'wazura' },
    { char: '丘', meaning: 'Hill', onyomi: 'kyuu', kunyomi: 'oka' },
    { char: '朽', meaning: 'Decay', onyomi: 'kyuu', kunyomi: 'kuta' },
    { char: '旧', meaning: 'Old/Former', onyomi: 'kyuu', kunyomi: '-' },
    { char: '距', meaning: 'Distance', onyomi: 'kyo', kunyomi: '-' },
    { char: '享', meaning: 'Enjoy', onyomi: 'kyou', kunyomi: '-' },
    { char: '供', meaning: 'Provide/Companion', onyomi: 'kyou/ku', kunyomi: 'tomo/sona' },
    { char: '峡', meaning: 'Gorge/Ravine', onyomi: 'kyou', kunyomi: '-' },
    { char: '境', meaning: 'Boundary/Region', onyomi: 'kyou', kunyomi: 'sakai' },
    { char: '鏡', meaning: 'Mirror', onyomi: 'kyou', kunyomi: 'kagami' },
    { char: '響', meaning: 'Echo', onyomi: 'kyou', kunyomi: 'hibi' },
    { char: '驚', meaning: 'Surprise', onyomi: 'kyou', kunyomi: 'odoro' },
    { char: '業', meaning: 'Industry/Business', onyomi: 'gyou/gou', kunyomi: 'waza' },
    { char: '牛', meaning: 'Cow', onyomi: 'gyuu', kunyomi: 'ushi' },
    { char: '魚', meaning: 'Fish', onyomi: 'gyo', kunyomi: 'sakana' },
    { char: '漁', meaning: 'Fishing', onyomi: 'gyo/ryou', kunyomi: '-' },
    { char: '京', meaning: 'Capital', onyomi: 'kyou/kei', kunyomi: 'miyako' },
    { char: '橋', meaning: 'Bridge', onyomi: 'kyou', kunyomi: 'hashi' },
    { char: '教', meaning: 'Teach', onyomi: 'kyou', kunyomi: 'oshi' },
    { char: '胸', meaning: 'Chest', onyomi: 'kyou', kunyomi: 'mune' },
    { char: '脅', meaning: 'Threaten', onyomi: 'kyou', kunyomi: '脅' },
    { char: '強', meaning: 'Strong', onyomi: 'kyou/gou', kunyomi: 'tuyo' },
    { char: '恐', meaning: 'Fear', onyomi: 'kyou', kunyomi: 'oso' },
    { char: '状', meaning: 'Status/Letter', onyomi: 'jou', kunyomi: '-' },
    { char: '窟', meaning: 'Cave/Cavern', onyomi: 'kutsu', kunyomi: '-' },
    { char: '熊', meaning: 'Bear', onyomi: 'yuu', kunyomi: 'kuma' },
    { char: '君', meaning: 'You/Ruler', onyomi: 'kun', kunyomi: 'kimi' },
    { char: '訓', meaning: 'Instruction', onyomi: 'kun', kunyomi: '-' },
    { char: '薫', meaning: 'Fragrant', onyomi: 'kun', kunyomi: 'kao' },
    { char: '軍', meaning: 'Army/Military', onyomi: 'gun', kunyomi: '-' },
    { char: '郡', meaning: 'County/District', onyomi: 'gun', kunyomi: '-' },
    { char: '群', meaning: 'Flock/Group', onyomi: 'gun', kunyomi: 'mu' },
    { char: '兄', meaning: 'Elder brother', onyomi: 'kyou/kei', kunyomi: 'ani' },
    { char: '刑', meaning: 'Penalty/Punishment', onyomi: 'kei', kunyomi: '-' },
    { char: '形', meaning: 'Shape/Form', onyomi: 'kei/gyou', kunyomi: 'katati' },
    { char: '系', meaning: 'System/Lineage', onyomi: 'kei', kunyomi: '-' },
    { char: '径', meaning: 'Diameter/Path', onyomi: 'kei', kunyomi: '-' },
    { char: '茎', meaning: 'Stalk/Stem', onyomi: 'kei', kunyomi: 'kuki' },
    { char: '型', meaning: 'Model/Type', onyomi: 'kei', kunyomi: 'kata' },
    { char: '計', meaning: 'Plan/Measure', onyomi: 'kei', kunyomi: 'haka' },
    { char: '恵', meaning: 'Blessing/Grace', onyomi: 'kei/e', kunyomi: 'megu' },
    { char: '渓', meaning: 'Valley', onyomi: 'kei', kunyomi: 'tani' },
    { char: '経', meaning: 'Pass/Sutra', onyomi: 'kei/kyou', kunyomi: 'he' },
    { char: '蛍', meaning: 'Firefly', onyomi: 'kei', kunyomi: 'hotaru' },
    { char: '景', meaning: 'Scene/View', onyomi: 'kei', kunyomi: '-' },
    { char: '軽', meaning: 'Lightweight', onyomi: 'kei', kunyomi: 'karu' },
    { char: '詣', meaning: 'Visit a temple', onyomi: 'kei', kunyomi: 'mai' },
    { char: '慶', meaning: 'Jubilation', onyomi: 'kei', kunyomi: '-' },
    { char: '憬', meaning: 'Yearn', onyomi: 'kei', kunyomi: '-' },
    { char: '鶏', meaning: 'Chicken', onyomi: 'kei', kunyomi: 'niwatori' },
    { char: '芸', meaning: 'Art/Performance', onyomi: 'gei', kunyomi: '-' },
    { char: '鯨', meaning: 'Whale', onyomi: 'gei', kunyomi: 'kujira' },
    { char: '隙', meaning: 'Gap/Chink', onyomi: 'geki', kunyomi: 'suki' },
    { char: '桁', meaning: 'Digit/Beam', onyomi: 'kou', kunyomi: 'keta' },
    { char: '欠', meaning: 'Lack/Deficit', onyomi: 'ketsu', kunyomi: 'ka' },
    { char: '穴', meaning: 'Hole', onyomi: 'ketsu', kunyomi: 'ana' },
    { char: '血', meaning: 'Blood', onyomi: 'ketsu', kunyomi: 'chi' },
    { char: '傑', meaning: 'Greatness', onyomi: 'ketsu', kunyomi: '-' },
    { char: '月', meaning: 'Moon/Month', onyomi: 'getsu/gatsu', kunyomi: 'tsuki' },
    { char: '犬', meaning: 'Dog', onyomi: 'ken', kunyomi: 'inu' },
    { char: '件', meaning: 'Matter/Case', onyomi: 'ken', kunyomi: '-' },
    { char: '見', meaning: 'See', onyomi: 'ken', kunyomi: 'mi' },
    { char: '券', meaning: 'Ticket', onyomi: 'ken', kunyomi: '-' },
    { char: '肩', meaning: 'Shoulder', onyomi: 'ken', kunyomi: 'kata' },
    { char: '県', meaning: 'Prefecture', onyomi: 'ken', kunyomi: '-' },
    { char: '倹', meaning: 'Frugal', onyomi: 'ken', kunyomi: '-' },
    { char: '剣', meaning: 'Sword', onyomi: 'ken', kunyomi: 'tsurugi' },
    { char: '拳', meaning: 'Fist', onyomi: 'ken', kunyomi: 'kobushi' },
    { char: '軒', meaning: 'House Counter', onyomi: 'ken', kunyomi: 'noki' },
    { char: '健', meaning: 'Health', onyomi: 'ken', kunyomi: 'suko' },
    { char: '険', meaning: 'Steep/Risky', onyomi: 'ken', kunyomi: 'kewa' },
    { char: '圏', meaning: 'Sphere/Range', onyomi: 'ken', kunyomi: '-' },
    { char: '堅', meaning: 'Hard/Solid', onyomi: 'ken', kunyomi: 'kata' },
    { char: '絹', meaning: 'Silk', onyomi: 'ken', kunyomi: 'kinu' },
    { char: '権', meaning: 'Authority', onyomi: 'ken/gon', kunyomi: '-' },
    { char: '憲', meaning: 'Constitution', onyomi: 'ken', kunyomi: '-' },
    { char: '鍵', meaning: 'Key', onyomi: 'ken', kunyomi: 'kagi' },
    { char: '繭', meaning: 'Cocoon', onyomi: 'ken', kunyomi: 'mayu' },
    { char: '元', meaning: 'Source/Origin', onyomi: 'gen/gan', kunyomi: 'moto' },
    { char: '弦', meaning: 'String/Chord', onyomi: 'gen', kunyomi: 'turu' },
    { char: '原', meaning: 'Original/Plain', onyomi: 'gen', kunyomi: 'hara' },
    { char: '現', meaning: 'Present/Appear', onyomi: 'gen', kunyomi: 'arawa' },
    { char: '舷', meaning: 'Gunwale', onyomi: 'gen', kunyomi: '-' },
    { char: '減', meaning: 'Decrease', onyomi: 'gen', kunyomi: 'he' },
    { char: '源', meaning: 'Source/Origin', onyomi: 'gen', kunyomi: 'minamoto' },
    { char: '己', meaning: 'Self', onyomi: 'ko/ki', kunyomi: 'onore' },
    { char: '戸', meaning: 'Door', onyomi: 'ko', kunyomi: 'to' },
    { char: '古', meaning: 'Old', onyomi: 'ko', kunyomi: 'furu' },
    { char: '故', meaning: 'Late/Reason', onyomi: 'ko', kunyomi: 'yue' },
    { char: '枯', meaning: 'Wither', onyomi: 'ko', kunyomi: 'ka' },
    { char: '庫', meaning: 'Warehouse', onyomi: 'ko/ku', kunyomi: 'kura' },
    { char: '湖', meaning: 'Lake', onyomi: 'ko', kunyomi: 'mizuumi' },
    { char: '鼓', meaning: 'Drum', onyomi: 'ko', kunyomi: 'tsuzumi' },
    { char: '錮', meaning: 'Imprison/Tie', onyomi: 'ko', kunyomi: '-' },
    { char: '五', meaning: 'Five', onyomi: 'go', kunyomi: 'itu' },
    { char: '互', meaning: 'Mutual', onyomi: 'go', kunyomi: 'taga' },
    { char: '午', meaning: 'Noon', onyomi: 'go', kunyomi: 'uma' },
    { char: '呉', meaning: 'Give/China-related', onyomi: 'go', kunyomi: 'ku' },
    { char: '後', meaning: 'After/Behind', onyomi: 'go/kou', kunyomi: 'nochi/usi' },
    { char: '娯', meaning: 'Entertainment', onyomi: 'go', kunyomi: '-' },
    { char: '碁', meaning: 'Go game', onyomi: 'go', kunyomi: '-' }
  ]
};

export const N2_EXAM_DATA = {
  easy: [
    { sentence: "*ぼうえき*の しごとを して います。", target: "貿", reading: "ぼう", options: ["貿", "易", "売", "買"], translation: "I work in trade." },
    { sentence: "ぎんこうに おかねを *あず*けます。", target: "預", reading: "あず", options: ["預", "貯", "蓄", "財"], translation: "I deposit money at the bank." },
    { sentence: "この *きかい*は とても べんりです。", target: "機", reading: "き", options: ["機", "器", "械", "装"], translation: "This machine is very convenient." },
    { sentence: "*しょくぎょう*は なんですか。", target: "職", reading: "しょく", options: ["職", "労", "務", "任"], translation: "What is your occupation?" },
    { sentence: "*のう*の はたらきを けんきゅうします。", target: "脳", reading: "のう", options: ["脳", "肺", "胃", "腸"], translation: "I study brain function." }
  ],
  mid: [
    { sentence: "*けんぽう*は くにの きほんほうです。", target: "憲", reading: "けん", options: ["憲", "法", "律", "制"], translation: "The constitution is the fundamental law of the nation." },
    { sentence: "この もんだいの *げんいん*は なんですか。", target: "因", reading: "いん", options: ["因", "果", "素", "件"], translation: "What is the cause of this problem?" },
    { sentence: "*ひかく*する ことが だいじです。", target: "較", reading: "かく", options: ["較", "比", "差", "異"], translation: "It is important to compare." },
    { sentence: "しゃかいに *こうけん*する。", target: "貢", reading: "こう", options: ["貢", "献", "任", "務"], translation: "Contribute to society." },
    { sentence: "*てつがく*は おもしろい がくもんです。", target: "哲", reading: "てつ", options: ["哲", "思", "想", "念"], translation: "Philosophy is an interesting subject." }
  ],
  hard: [
    { sentence: "*さいばん*で はんけつが でました。", target: "裁", reading: "さい", options: ["裁", "判", "罪", "罰"], translation: "The judgment was given at trial." },
    { sentence: "かいしゃの *こうぞう*を かえます。", target: "構", reading: "こう", options: ["構", "造", "設", "備"], translation: "We will change the company structure." },
    { sentence: "この ちりょうほうは *こうか*が あります。", target: "効", reading: "こう", options: ["効", "果", "影", "響"], translation: "This treatment is effective." },
    { char: '著', sentence: "この *ちょしゃ*は ゆうめいです。", target: "著", reading: "ちょ", options: ["著", "編", "訳", "版"], translation: "This author is famous." },
    { sentence: "わたしは *めんえき*を べんきょうして います。", target: "免", reading: "めん", options: ["免", "疫", "菌", "毒"], translation: "I am studying immunology." }
  ],
  top_hard: [
    { sentence: "*かくめい*てきな ぎじゅつが うまれた。", target: "革", reading: "かく", options: ["革", "改", "造", "創"], translation: "A revolutionary technology was born." },
    { sentence: "さまざまな *しゅうきょう*が あります。", target: "宗", reading: "しゅう", options: ["宗", "教", "神", "魂"], translation: "There are various religions." },
    { sentence: "かれの *えいきょうりょく*は おおきい。", target: "響", reading: "きょう", options: ["響", "影", "効", "果"], translation: "His influence is large." },
    { sentence: "*ちゅうしょう*てきな がいねんです。", target: "抽", reading: "ちゅう", options: ["抽", "象", "複", "雑"], translation: "It is an abstract concept." },
    { sentence: "*ぎむ*を はたさなければ なりません。", target: "義", reading: "ぎ", options: ["義", "善", "徳", "務"], translation: "You must fulfill your duty." }
  ]
};
