// JLPT N3 Kanji Dataset (~200 kanji)
export const N3_KANJI_DATA = {
  abstract: [
    { char: '以', meaning: 'With/By', onyomi: 'i', kunyomi: '-' },
    { char: '位', meaning: 'Rank/Place', onyomi: 'i', kunyomi: 'kurai' },
    { char: '各', meaning: 'Each', onyomi: 'kaku', kunyomi: 'ono' },
    { char: '覚', meaning: 'Memorize/Wake', onyomi: 'kaku', kunyomi: 'obo/sa' },
    { char: '完', meaning: 'Perfect/Complete', onyomi: 'kan', kunyomi: '-' },
    { char: '願', meaning: 'Request/Wish', onyomi: 'gan', kunyomi: 'nega' },
    { char: '希', meaning: 'Hope/Rare', onyomi: 'ki', kunyomi: 'mare' },
    { char: '季', meaning: 'Season', onyomi: 'ki', kunyomi: '-' },
    { char: '紀', meaning: 'Era/Record', onyomi: 'ki', kunyomi: '-' },
    { char: '喜', meaning: 'Rejoice', onyomi: 'ki', kunyomi: 'yoroko' },
    { char: '機', meaning: 'Machine/Opportunity', onyomi: 'ki', kunyomi: 'hata' },
    { char: '極', meaning: 'Extreme', onyomi: 'kyoku/goku', kunyomi: 'kiwa' },
    { char: '訓', meaning: 'Instruction', onyomi: 'kun', kunyomi: '-' },
    { char: '欠', meaning: 'Lack/Gap', onyomi: 'ketsu', kunyomi: 'ka' },
    { char: '結', meaning: 'Tie/Bind', onyomi: 'ketsu', kunyomi: 'mu/yu' },
    { char: '固', meaning: 'Hard/Solid', onyomi: 'ko', kunyomi: 'kata' },
    { char: '好', meaning: 'Like/Favorite', onyomi: 'kou', kunyomi: 'kono/su' },
    { char: '候', meaning: 'Climate/Wait', onyomi: 'kou', kunyomi: '-' },
    { char: '最', meaning: 'Most', onyomi: 'sai', kunyomi: 'mo' },
    { char: '材', meaning: 'Material/Talent', onyomi: 'zai', kunyomi: '-' },
    { char: '昨', meaning: 'Previous/Yesterday', onyomi: 'saku', kunyomi: '-' },
    { char: '札', meaning: 'Tag/Bill', onyomi: 'satsu', kunyomi: 'fuda' },
    { char: '察', meaning: 'Inspect/Guess', onyomi: 'satsu', kunyomi: '-' },
    { char: '残', meaning: 'Remainder', onyomi: 'zan', kunyomi: 'noko' },
    { char: '順', meaning: 'Order/Sequence', onyomi: 'jun', kunyomi: '-' },
    { char: '初', meaning: 'First', onyomi: 'sho', kunyomi: 'haji/u' },
    { char: '成', meaning: 'Become/Achieve', onyomi: 'sei/jou', kunyomi: 'na' },
    { char: '然', meaning: 'Nature/So', onyomi: 'zen/nen', kunyomi: 'shika' },
    { char: '側', meaning: 'Side', onyomi: 'soku', kunyomi: 'gawa' },
    { char: '単', meaning: 'Simple/Single', onyomi: 'tan', kunyomi: '-' },
    { char: '的', meaning: 'Target/Mark', onyomi: 'teki', kunyomi: 'mato' },
    { char: '由', meaning: 'Reason', onyomi: 'yu/yui', kunyomi: 'yoshi' },
    { char: '要', meaning: 'Need/Vital', onyomi: 'you', kunyomi: 'i' },
    { char: '類', meaning: 'Kind/Type', onyomi: 'rui', kunyomi: 'tagui' }
  ],
  actions: [
    { char: '改', meaning: 'Reform/Renew', onyomi: 'kai', kunyomi: 'arata' },
    { char: '給', meaning: 'Supply/Pay', onyomi: 'kyuu', kunyomi: 'tama' },
    { char: '試', meaning: 'Try/Test', onyomi: 'shi', kunyomi: 'kokoro/tame' },
    { char: '辞', meaning: 'Word/Resign', onyomi: 'ji', kunyomi: 'ya' },
    { char: '手', meaning: 'Hand', onyomi: 'shu', kunyomi: 'te' },
    { char: '笑', meaning: 'Laugh', onyomi: 'shou', kunyomi: 'wara' },
    { char: '唱', meaning: 'Chant', onyomi: 'shou', kunyomi: 'tona' },
    { char: '焼', meaning: 'Burn/Bake', onyomi: 'shou', kunyomi: 'ya' },
    { char: '照', meaning: 'Illuminate', onyomi: 'shou', kunyomi: 'te' },
    { char: '折', meaning: 'Fold/Break', onyomi: 'setsu', kunyomi: 'o' },
    { char: '説', meaning: 'Explain', onyomi: 'setsu', kunyomi: 'to' },
    { char: '戦', meaning: 'War/Fight', onyomi: 'sen', kunyomi: 'tataka' },
    { char: '選', meaning: 'Choose', onyomi: 'sen', kunyomi: 'era' },
    { char: '争', meaning: 'Contention', onyomi: 'sou', kunyomi: 'araso' },
    { char: '束', meaning: 'Bundle', onyomi: 'soku', kunyomi: 'taba' },
    { char: '続', meaning: 'Continue', onyomi: 'zoku', kunyomi: 'tsuzu' },
    { char: '置', meaning: 'Put/Place', onyomi: 'chi', kunyomi: 'o' },
    { char: '停', meaning: 'Halt/Stop', onyomi: 'tei', kunyomi: '-' },
    { char: '伝', meaning: 'Transmit', onyomi: 'den', kunyomi: 'tsuta' },
    { char: '努', meaning: 'Effort', onyomi: 'do', kunyomi: 'tsuto' },
    { char: '働', meaning: 'Work', onyomi: 'dou', kunyomi: 'hatara(ku)' },
    { char: '飛', meaning: 'Fly', onyomi: 'hi', kunyomi: 'to' },
    { char: '敗', meaning: 'Fail/Defeat', onyomi: 'bai', kunyomi: 'yabu' },
    { char: '望', meaning: 'Hope', onyomi: 'bou/mou', kunyomi: 'nozo' },
    { char: '勇', meaning: 'Brave/Cheer', onyomi: 'yuu', kunyomi: 'isa' },
    { char: '養', meaning: 'Nurture', onyomi: 'you', kunyomi: 'yashina' },
    { char: '浴', meaning: 'Bathe', onyomi: 'yoku', kunyomi: 'a' },
    { char: '連', meaning: 'Lead/Connect', onyomi: 'ren', kunyomi: 'tsu' },
    { char: '労', meaning: 'Labor/Effort', onyomi: 'rou', kunyomi: 'tsuka' },
    { char: '録', meaning: 'Record', onyomi: 'roku', kunyomi: '-' },
    { char: '達', meaning: 'Reach/Plural', onyomi: 'tatsu', kunyomi: 'tachi' }
  ],
  society_economy: [
    { char: '案', meaning: 'Plan/Idea', onyomi: 'an', kunyomi: '-' },
    { char: '官', meaning: 'Official', onyomi: 'kan', kunyomi: '-' },
    { char: '管', meaning: 'Pipe/Control', onyomi: 'kan', kunyomi: 'kuda' },
    { char: '関', meaning: 'Connect/Barrier', onyomi: 'kan', kunyomi: 'seki' },
    { char: '観', meaning: 'Observe/View', onyomi: 'kan', kunyomi: '-' },
    { char: '議', meaning: 'Discuss', onyomi: 'gi', kunyomi: '-' },
    { char: '軍', meaning: 'Army/Troops', onyomi: 'gun', kunyomi: '-' },
    { char: '郡', meaning: 'County/District', onyomi: 'gun', kunyomi: '-' },
    { char: '功', meaning: 'Achievement/Merit', onyomi: 'kou/ku', kunyomi: '-' },
    { char: '航', meaning: 'Navigation', onyomi: 'kou', kunyomi: '-' },
    { char: '告', meaning: 'Inform/State', onyomi: 'koku', kunyomi: 'tsu' },
    { char: '材', meaning: 'Material/Talent', onyomi: 'zai', kunyomi: '-' },
    { char: '刷', meaning: 'Print', onyomi: 'satsu', kunyomi: 'su' },
    { char: '察', meaning: 'Inspect/Guess', onyomi: 'satsu', kunyomi: '-' },
    { char: '士', meaning: 'Gentleman/Samurai', onyomi: 'shi', kunyomi: '-' },
    { char: '氏', meaning: 'Surname/Clan', onyomi: 'shi', kunyomi: 'uji' },
    { char: '史', meaning: 'History/Chronicle', onyomi: 'shi', kunyomi: '-' },
    { char: '司', meaning: 'Administer', onyomi: 'shi', kunyomi: 'tsukasa' },
    { char: '臣', meaning: 'Retainer/Subject', onyomi: 'shin/jin', kunyomi: '-' },
    { char: '信', meaning: 'Trust/Believe', onyomi: 'shin', kunyomi: '-' },
    { char: '卒', meaning: 'Graduate', onyomi: 'sotsu', kunyomi: '-' },
    { char: '隊', meaning: 'Squad/Regiment', onyomi: 'tai', kunyomi: '-' },
    { char: '賃', meaning: 'Rent/Fee', onyomi: 'chin', kunyomi: '-' },
    { char: '貯', meaning: 'Savings', onyomi: 'cho', kunyomi: 'tama' },
    { char: '堂', meaning: 'Hall', onyomi: 'dou', kunyomi: '-' },
    { char: '得', meaning: 'Gain/Acquire', onyomi: 'toku', kunyomi: 'e' },
    { char: '特', meaning: 'Special', onyomi: 'toku', kunyomi: '-' },
    { char: '標', meaning: 'Mark/Sign', onyomi: 'hyou', kunyomi: '-' },
    { char: '府', meaning: 'Government Office', onyomi: 'fu', kunyomi: '-' },
    { char: '副', meaning: 'Assistant/Vice', onyomi: 'fuku', kunyomi: '-' },
    { char: '兵', meaning: 'Soldier/Army', onyomi: 'hei/hyou', kunyomi: 'tsuwamono' },
    { char: '民', meaning: 'People/Nation', onyomi: 'min', kunyomi: 'tami' },
    { char: '約', meaning: 'Promise/Approx', onyomi: 'yaku', kunyomi: '-' }
  ],
  nature_science: [
    { char: '衣', meaning: 'Clothes/Cloth', onyomi: 'i', kunyomi: 'koromo' },
    { char: '囲', meaning: 'Surround/Enclose', onyomi: 'i', kunyomi: 'kako' },
    { char: '胃', meaning: 'Stomach', onyomi: 'i', kunyomi: '-' },
    { char: '栄', meaning: 'Prosper/Flourish', onyomi: 'ei', kunyomi: 'saka' },
    { char: '塩', meaning: 'Salt', onyomi: 'en', kunyomi: 'shio' },
    { char: '億', meaning: '100 Million', onyomi: 'oku', kunyomi: '-' },
    { char: '芽', meaning: 'Bud/Sprout', onyomi: 'ga', kunyomi: 'me' },
    { char: '械', meaning: 'Machine/Tool', onyomi: 'kai', kunyomi: '-' },
    { char: '害', meaning: 'Harm/Damage', onyomi: 'gai', kunyomi: '-' },
    { char: '季', meaning: 'Season', onyomi: 'ki', kunyomi: '-' },
    { char: '紀', meaning: 'Era/Chronicle', onyomi: 'ki', kunyomi: '-' },
    { char: '器', meaning: 'Vessel/Utensil', onyomi: 'ki', kunyomi: 'utsuwa' },
    { char: '機', meaning: 'Machine/Opportunity', onyomi: 'ki', kunyomi: 'hata' },
    { char: '徑', meaning: 'Path/Diameter', onyomi: 'kei', kunyomi: '-' },
    { char: '型', meaning: 'Model/Pattern', onyomi: 'kei', kunyomi: 'kata' },
    { char: '景', meaning: 'View/Scene', onyomi: 'kei', kunyomi: '-' },
    { char: '健', meaning: 'Healthy', onyomi: 'ken', kunyomi: 'suko' },
    { char: '康', meaning: 'Health/Ease', onyomi: 'kou', kunyomi: '-' },
    { char: '菜', meaning: 'Vegetable', onyomi: 'sai', kunyomi: 'na' },
    { char: '種', meaning: 'Seed/Kind', onyomi: 'shu', kunyomi: 'tane' },
    { char: '腸', meaning: 'Intestines', onyomi: 'chou', kunyomi: 'harawata' },
    { char: '底', meaning: 'Bottom', onyomi: 'tei', kunyomi: 'soko' },
    { char: '灯', meaning: 'Light/Lamp', onyomi: 'tou', kunyomi: 'hi' },
    { char: '毒', meaning: 'Poison', onyomi: 'doku', kunyomi: '-' },
    { char: '熱', meaning: 'Heat/Fever', onyomi: 'netsu', kunyomi: 'atsu' },
    { char: '梅', meaning: 'Plum', onyomi: 'bai', kunyomi: 'ume' },
    { char: '飯', meaning: 'Meal/Rice', onyomi: 'han', kunyomi: 'meshi' },
    { char: '粉', meaning: 'Powder/Flour', onyomi: 'fun', kunyomi: 'ko/kona' },
    { char: '牧', meaning: 'Pasture/Breed', onyomi: 'moku', kunyomi: 'maki' },
    { char: '陸', meaning: 'Land/Shore', onyomi: 'riku', kunyomi: '-' },
    { char: '冷', meaning: 'Cold/Chilly', onyomi: 'rei', kunyomi: 'hi/tsume' },
    { char: '歴', meaning: 'History/Pass through', onyomi: 'reki', kunyomi: '-' }
  ],
  culture_people: [
    { char: '愛', meaning: 'Love', onyomi: 'ai', kunyomi: '-' },
    { char: '英', meaning: 'English/Brilliant', onyomi: 'ei', kunyomi: '-' },
    { char: '街', meaning: 'City/Street', onyomi: 'gai/kai', kunyomi: 'machi' },
    { char: '喜', meaning: 'Rejoice', onyomi: 'ki', kunyomi: 'yoroko' },
    { char: '旗', meaning: 'Flag', onyomi: 'ki', kunyomi: 'hata' },
    { char: '功', meaning: 'Achievement', onyomi: 'kou', kunyomi: '-' },
    { char: '松', meaning: 'Pine tree', onyomi: 'shou', kunyomi: 'matsu' },
    { char: '笑', meaning: 'Laugh', onyomi: 'shou', kunyomi: 'wara' },
    { char: '唱', meaning: 'Chant', onyomi: 'shou', kunyomi: 'tona' },
    { char: '象', meaning: 'Shape/Elephant', onyomi: 'shou/zou', kunyomi: '-' },
    { char: '賞', meaning: 'Prize', onyomi: 'shou', kunyomi: '-' },
    { char: '静', meaning: 'Quiet', onyomi: 'sei/jou', kunyomi: 'shizu' },
    { char: '席', meaning: 'Seat', onyomi: 'seki', kunyomi: '-' },
    { char: '積', meaning: 'Pile/Product', onyomi: 'seki', kunyomi: 'tsu' },
    { char: '節', meaning: 'Node/Season', onyomi: 'setsu/sechi', kunyomi: 'fushi' },
    { char: '浅', meaning: 'Shallow', onyomi: 'sen', kunyomi: 'asa' },
    { char: '倉', meaning: 'Storehouse', onyomi: 'sou', kunyomi: 'kura' },
    { char: '巣', meaning: 'Nest', onyomi: 'sou', kunyomi: 'su' },
    { char: '孫', meaning: 'Grandchild', onyomi: 'son', kunyomi: 'mago' },
    { char: '帯', meaning: 'Belt/Sash', onyomi: 'tai', kunyomi: 'obi' },
    { char: '仲', meaning: 'Relationship', onyomi: 'chuu', kunyomi: 'naka' },
    { char: '兆', meaning: 'Trillion/Omen', onyomi: 'chou', kunyomi: 'kiza' },
    { char: '勇', meaning: 'Brave', onyomi: 'yuu', kunyomi: 'isa' },
    { char: '良', meaning: 'Good', onyomi: 'ryou', kunyomi: 'yo' },
    { char: '料', meaning: 'Fee/Material', onyomi: 'ryou', kunyomi: '-' },
    { char: '量', meaning: 'Quantity', onyomi: 'ryou', kunyomi: 'haka' },
    { char: '輪', meaning: 'Wheel/Ring', onyomi: 'rin', kunyomi: 'wa' },
    { char: '類', meaning: 'Kind/Type', onyomi: 'rui', kunyomi: 'tagui' },
    { char: '令', meaning: 'Command', onyomi: 'rei', kunyomi: '-' },
    { char: '冷', meaning: 'Cold/Chilly', onyomi: 'rei', kunyomi: 'hi/tsume' },
    { char: '例', meaning: 'Example', onyomi: 'rei', kunyomi: 'tato' },
    { char: '歴', meaning: 'History', onyomi: 'reki', kunyomi: '-' },
    { char: '連', meaning: 'Lead/Connect', onyomi: 'ren', kunyomi: 'tsu' },
    { char: '老', meaning: 'Old', onyomi: 'rou', kunyomi: 'o' },
    { char: '労', meaning: 'Labor/Effort', onyomi: 'rou', kunyomi: 'tsuka' },
    { char: '録', meaning: 'Record', onyomi: 'roku', kunyomi: '-' }
  ]
};


export const N3_EXAM_DATA = {
  easy: [
    { sentence: "この *しな*ものは *う*りきれです。", target: "品", reading: "しな", options: ["品", "売", "商", "買"], translation: "This product is sold out." },
    { sentence: "*あい*する ひとに であいました。", target: "愛", reading: "あい", options: ["愛", "感", "情", "心"], translation: "I met the person I love." },
    { sentence: "*いし*の うえに すわりました。", target: "島", reading: "しま", options: ["島", "湖", "陸", "港"], translation: "I sat on the stone." },
    { sentence: "きょう の *てんき*は あたたかいです。", target: "温", reading: "あたた", options: ["温", "暖", "冷", "涼"], translation: "Today's weather is warm." },
    { sentence: "*いぬ*と さんぽに いきます。", target: "犬", reading: "いぬ", options: ["犬", "鳥", "魚", "虫"], translation: "I go for a walk with the dog." }
  ],
  mid: [
    { sentence: "*せい*じの もんだいは むずかしい。", target: "政", reading: "せい", options: ["政", "治", "法", "制"], translation: "Political problems are difficult." },
    { sentence: "*けんきゅう*を つづけて います。", target: "究", reading: "きゅう", options: ["究", "研", "調", "査"], translation: "I continue doing research." },
    { sentence: "しょうひ*ぜい*が あがりました。", target: "税", reading: "ぜい", options: ["税", "費", "値", "利"], translation: "The consumption tax went up." },
    { sentence: "*わら*って すごしましょう。", target: "笑", reading: "わら", options: ["笑", "泣", "怒", "喜"], translation: "Let's spend time laughing." },
    { sentence: "にほんの *れきし*を べんきょうします。", target: "歴", reading: "れき", options: ["歴", "史", "伝", "統"], translation: "I study Japanese history." }
  ],
  hard: [
    { sentence: "*ほうりつ*を まもらなければ なりません。", target: "律", reading: "りつ", options: ["律", "法", "則", "規"], translation: "You must obey the law." },
    { sentence: "*かんきょう*もんだいは じゅうようです。", target: "環", reading: "かん", options: ["環", "境", "陸", "島"], translation: "Environmental issues are important." },
    { sentence: "この *くすり*を のんでください。", target: "薬", reading: "くすり", options: ["薬", "医", "病", "痛"], translation: "Please take this medicine." },
    { sentence: "*ぎ*じゅつが はったつしました。", target: "芸", reading: "げい", options: ["芸", "術", "美", "演"], translation: "Technology has developed." },
    { sentence: "*けんこう*に きをつけて ください。", target: "健", reading: "けん", options: ["健", "康", "活", "命"], translation: "Please take care of your health." }
  ],
  top_hard: [
    { sentence: "*せんきょ*の けっかが はっぴょうされた。", target: "選", reading: "せん", options: ["選", "挙", "権", "議"], translation: "The election results were announced." },
    { sentence: "この *りろん*は ふくざつです。", target: "論", reading: "ろん", options: ["論", "説", "理", "科"], translation: "This theory is complex." },
    { sentence: "*きけん*な ばしょに ちかづかないで。", target: "険", reading: "けん", options: ["険", "危", "害", "防"], translation: "Don't go near dangerous places." },
    { sentence: "*しま*に わたる ふねが あります。", target: "島", reading: "しま", options: ["島", "陸", "港", "湖"], translation: "There is a boat to cross to the island." },
    { sentence: "この *えんげき*は すばらしかった。", target: "劇", reading: "げき", options: ["劇", "演", "映", "画"], translation: "This theatrical performance was wonderful." }
  ]
};
