// JLPT N3 Kanji Dataset (~200 kanji)
export const N3_KANJI_DATA = {
  business: [
    { char: '経', meaning: 'Sutra / Manage', onyomi: 'kei/kyou', kunyomi: 'he/ta' },
    { char: '済', meaning: 'Settle / Finish', onyomi: 'sai', kunyomi: 'su' },
    { char: '営', meaning: 'Operate / Run', onyomi: 'ei', kunyomi: 'itona' },
    { char: '業', meaning: 'Business / Industry', onyomi: 'gyou/gou', kunyomi: 'waza' },
    { char: '商', meaning: 'Merchandise', onyomi: 'shou', kunyomi: 'akina' },
    { char: '品', meaning: 'Goods /品', onyomi: 'hin', kunyomi: 'shina' },
    { char: '売', meaning: 'Sell', onyomi: 'bai', kunyomi: 'u' },
    { char: '産', meaning: 'Give birth / Produce', onyomi: 'san', kunyomi: 'u/umu' },
    { char: '届', meaning: 'Deliver / Report', onyomi: '-', kunyomi: 'todo' },
    { char: '預', meaning: 'Deposit', onyomi: 'yo', kunyomi: 'azu' },
    { char: '払', meaning: 'Pay', onyomi: '-', kunyomi: 'hara' },
    { char: '費', meaning: 'Expense', onyomi: 'hi', kunyomi: 'tsui' },
    { char: '税', meaning: 'Tax', onyomi: 'zei', kunyomi: '-' },
    { char: '値', meaning: 'Value / Price', onyomi: 'chi', kunyomi: 'ne/atai' },
    { char: '割', meaning: 'Divide / Ratio', onyomi: 'katsu', kunyomi: 'wa/sa' },
    { char: '増', meaning: 'Increase', onyomi: 'zou', kunyomi: 'fu/ma' },
    { char: '減', meaning: 'Decrease', onyomi: 'gen', kunyomi: 'he' },
    { char: '利', meaning: 'Profit / Benefit', onyomi: 'ri', kunyomi: 'ki' },
    { char: '益', meaning: 'Benefit / Gain', onyomi: 'eki/yaku', kunyomi: '-' },
    { char: '収', meaning: 'Obtain / Income', onyomi: 'shuu', kunyomi: 'osa' }
  ],
  government: [
    { char: '政', meaning: 'Politics', onyomi: 'sei/shou', kunyomi: 'matsurigoto' },
    { char: '治', meaning: 'Govern / Cure', onyomi: 'chi/ji', kunyomi: 'osa/nao' },
    { char: '法', meaning: 'Law / Method', onyomi: 'hou', kunyomi: '-' },
    { char: '律', meaning: 'Regulation', onyomi: 'ritsu', kunyomi: '-' },
    { char: '制', meaning: 'System / Control', onyomi: 'sei', kunyomi: '-' },
    { char: '度', meaning: 'Degree / System', onyomi: 'do/to', kunyomi: 'tabi' },
    { char: '規', meaning: 'Rule / Standard', onyomi: 'ki', kunyomi: '-' },
    { char: '則', meaning: 'Rule / Law', onyomi: 'soku', kunyomi: '-' },
    { char: '選', meaning: 'Choose / Elect', onyomi: 'sen', kunyomi: 'era' },
    { char: '挙', meaning: 'Raise / Elect', onyomi: 'kyo', kunyomi: 'a' },
    { char: '権', meaning: 'Authority / Right', onyomi: 'ken/gon', kunyomi: '-' },
    { char: '議', meaning: 'Discuss', onyomi: 'gi', kunyomi: '-' },
    { char: '民', meaning: 'People / Nation', onyomi: 'min', kunyomi: 'tami' },
    { char: '族', meaning: 'Tribe / Family', onyomi: 'zoku', kunyomi: '-' },
    { char: '連', meaning: 'Connect / Join', onyomi: 'ren', kunyomi: 'tsura/tsu' },
    { char: '合', meaning: 'Combine / Fit', onyomi: 'gou/gatsu', kunyomi: 'a' },
    { char: '共', meaning: 'Together / Shared', onyomi: 'kyou', kunyomi: 'tomo' },
    { char: '公', meaning: 'Public / Official', onyomi: 'kou', kunyomi: 'ooyake' },
    { char: '官', meaning: 'Government / Official', onyomi: 'kan', kunyomi: '-' },
    { char: '省', meaning: 'Ministry / Reflect', onyomi: 'shou/sei', kunyomi: 'habuku/kaeri' }
  ],
  emotion: [
    { char: '感', meaning: 'Feel / Emotion', onyomi: 'kan', kunyomi: '-' },
    { char: '情', meaning: 'Feeling / Emotion', onyomi: 'jou/sei', kunyomi: 'nasa' },
    { char: '愛', meaning: 'Love', onyomi: 'ai', kunyomi: '-' },
    { char: '憎', meaning: 'Hate', onyomi: 'zou', kunyomi: 'niku' },
    { char: '怒', meaning: 'Anger', onyomi: 'do', kunyomi: 'ika/oko' },
    { char: '泣', meaning: 'Cry', onyomi: 'kyuu', kunyomi: 'na' },
    { char: '笑', meaning: 'Laugh', onyomi: 'shou', kunyomi: 'wara/e' },
    { char: '喜', meaning: 'Rejoice', onyomi: 'ki', kunyomi: 'yoroko' },
    { char: '悲', meaning: 'Sadness', onyomi: 'hi', kunyomi: 'kana' },
    { char: '苦', meaning: 'Suffer / Bitter', onyomi: 'ku', kunyomi: 'kuru/niga' },
    { char: '楽', meaning: 'Fun / Music', onyomi: 'gaku/raku', kunyomi: 'tano' },
    { char: '望', meaning: 'Hope / Desire', onyomi: 'bou/mou', kunyomi: 'nozo' },
    { char: '願', meaning: 'Wish / Pray', onyomi: 'gan', kunyomi: 'nega' },
    { char: '信', meaning: 'Believe / Trust', onyomi: 'shin', kunyomi: '-' },
    { char: '忘', meaning: 'Forget', onyomi: 'bou', kunyomi: 'wasu' },
    { char: '覚', meaning: 'Remember / Wake', onyomi: 'kaku', kunyomi: 'obo/sa' },
    { char: '驚', meaning: 'Surprise', onyomi: 'kyou', kunyomi: 'odoro' },
    { char: '恐', meaning: 'Fear', onyomi: 'kyou', kunyomi: 'oso/kowa' },
    { char: '慣', meaning: 'Accustomed', onyomi: 'kan', kunyomi: 'na' },
    { char: '恥', meaning: 'Shame', onyomi: 'chi', kunyomi: 'ha/haji' }
  ],
  science: [
    { char: '理', meaning: 'Reason / Logic', onyomi: 'ri', kunyomi: '-' },
    { char: '科', meaning: 'Subject / Dept', onyomi: 'ka', kunyomi: '-' },
    { char: '数', meaning: 'Number', onyomi: 'suu/su', kunyomi: 'kazu/kazo' },
    { char: '算', meaning: 'Calculate', onyomi: 'san', kunyomi: '-' },
    { char: '式', meaning: 'Formula / Style', onyomi: 'shiki', kunyomi: '-' },
    { char: '形', meaning: 'Shape / Form', onyomi: 'kei/gyou', kunyomi: 'kata/katachi' },
    { char: '図', meaning: 'Diagram / Map', onyomi: 'zu/to', kunyomi: 'haka' },
    { char: '線', meaning: 'Line / Wire', onyomi: 'sen', kunyomi: '-' },
    { char: '点', meaning: 'Point / Spot', onyomi: 'ten', kunyomi: '-' },
    { char: '面', meaning: 'Surface / Face', onyomi: 'men', kunyomi: 'omo/tsura' },
    { char: '角', meaning: 'Angle / Corner', onyomi: 'kaku', kunyomi: 'kado/tsuno' },
    { char: '測', meaning: 'Measure', onyomi: 'soku', kunyomi: 'haka' },
    { char: '験', meaning: 'Examine / Test', onyomi: 'ken/gen', kunyomi: '-' },
    { char: '究', meaning: 'Research', onyomi: 'kyuu', kunyomi: 'kiwa' },
    { char: '調', meaning: 'Investigate / Tune', onyomi: 'chou', kunyomi: 'shira/totono' },
    { char: '査', meaning: 'Examine / Inspect', onyomi: 'sa', kunyomi: '-' },
    { char: '報', meaning: 'Report / Reward', onyomi: 'hou', kunyomi: 'muku' },
    { char: '告', meaning: 'Inform / Tell', onyomi: 'koku', kunyomi: 'tsu' },
    { char: '説', meaning: 'Theory / Explain', onyomi: 'setsu/zei', kunyomi: 'to' },
    { char: '論', meaning: 'Theory / Argue', onyomi: 'ron', kunyomi: '-' }
  ],
  culture: [
    { char: '文', meaning: 'Culture / Text', onyomi: 'bun/mon', kunyomi: 'fumi' },
    { char: '化', meaning: 'Change / Transform', onyomi: 'ka/ke', kunyomi: 'ba' },
    { char: '歴', meaning: 'History', onyomi: 'reki', kunyomi: '-' },
    { char: '史', meaning: 'History', onyomi: 'shi', kunyomi: '-' },
    { char: '伝', meaning: 'Transmit / Legend', onyomi: 'den', kunyomi: 'tsuta' },
    { char: '統', meaning: 'Tradition / Unite', onyomi: 'tou', kunyomi: 'su' },
    { char: '芸', meaning: 'Art / Skill', onyomi: 'gei', kunyomi: '-' },
    { char: '術', meaning: 'Art / Technique', onyomi: 'jutsu', kunyomi: '-' },
    { char: '美', meaning: 'Beauty', onyomi: 'bi', kunyomi: 'utsuku' },
    { char: '絵', meaning: 'Picture', onyomi: 'kai/e', kunyomi: '-' },
    { char: '詩', meaning: 'Poem', onyomi: 'shi', kunyomi: 'uta' },
    { char: '劇', meaning: 'Drama / Theater', onyomi: 'geki', kunyomi: '-' },
    { char: '演', meaning: 'Perform / Act', onyomi: 'en', kunyomi: '-' },
    { char: '祭', meaning: 'Festival', onyomi: 'sai', kunyomi: 'matsu' },
    { char: '祝', meaning: 'Celebrate', onyomi: 'shuku/shuu', kunyomi: 'iwa' },
    { char: '式', meaning: 'Ceremony / Style', onyomi: 'shiki', kunyomi: '-' },
    { char: '像', meaning: 'Statue / Image', onyomi: 'zou', kunyomi: '-' },
    { char: '博', meaning: 'Extensive / Museum', onyomi: 'haku/baku', kunyomi: '-' },
    { char: '館', meaning: 'Building / Hall', onyomi: 'kan', kunyomi: 'yakata' },
    { char: '寺', meaning: 'Temple', onyomi: 'ji', kunyomi: 'tera' }
  ],
  communication: [
    { char: '記', meaning: 'Record / Write', onyomi: 'ki', kunyomi: 'shiru' },
    { char: '録', meaning: 'Record', onyomi: 'roku', kunyomi: '-' },
    { char: '紙', meaning: 'Paper', onyomi: 'shi', kunyomi: 'kami' },
    { char: '誌', meaning: 'Magazine', onyomi: 'shi', kunyomi: '-' },
    { char: '刊', meaning: 'Publish', onyomi: 'kan', kunyomi: '-' },
    { char: '版', meaning: 'Edition / Print', onyomi: 'han/ban', kunyomi: '-' },
    { char: '届', meaning: 'Report / Deliver', onyomi: '-', kunyomi: 'todo' },
    { char: '届', meaning: 'Reach', onyomi: '-', kunyomi: 'todo' },
    { char: '返', meaning: 'Return', onyomi: 'hen', kunyomi: 'kae' },
    { char: '届', meaning: 'Apply', onyomi: '-', kunyomi: 'todo' },
    { char: '伝', meaning: 'Transmit', onyomi: 'den', kunyomi: 'tsuta' },
    { char: '放', meaning: 'Release / Broadcast', onyomi: 'hou', kunyomi: 'hana/hoo' },
    { char: '送', meaning: 'Send', onyomi: 'sou', kunyomi: 'oku' },
    { char: '届', meaning: 'Deliver', onyomi: '-', kunyomi: 'todo' },
    { char: '受', meaning: 'Receive', onyomi: 'ju', kunyomi: 'u' },
    { char: '届', meaning: 'Reach', onyomi: '-', kunyomi: 'todo' },
    { char: '届', meaning: 'Notification', onyomi: '-', kunyomi: 'todo' },
    { char: '届', meaning: 'Deliver', onyomi: '-', kunyomi: 'todo' }
  ],
  health: [
    { char: '医', meaning: 'Medicine / Doctor', onyomi: 'i', kunyomi: '-' },
    { char: '薬', meaning: 'Medicine / Drug', onyomi: 'yaku', kunyomi: 'kusuri' },
    { char: '病', meaning: 'Illness / Disease', onyomi: 'byou/hei', kunyomi: 'ya/yamai' },
    { char: '痛', meaning: 'Pain / Hurt', onyomi: 'tsuu', kunyomi: 'ita' },
    { char: '熱', meaning: 'Heat / Fever', onyomi: 'netsu', kunyomi: 'atsu' },
    { char: '疲', meaning: 'Fatigue', onyomi: 'hi', kunyomi: 'tsuka' },
    { char: '眠', meaning: 'Sleep', onyomi: 'min', kunyomi: 'nemu/nemu' },
    { char: '危', meaning: 'Dangerous', onyomi: 'ki', kunyomi: 'abu/aya' },
    { char: '険', meaning: 'Steep / Risk', onyomi: 'ken', kunyomi: 'kewa' },
    { char: '害', meaning: 'Harm / Damage', onyomi: 'gai', kunyomi: '-' },
    { char: '防', meaning: 'Prevent / Defend', onyomi: 'bou', kunyomi: 'fuse' },
    { char: '治', meaning: 'Cure / Heal', onyomi: 'chi/ji', kunyomi: 'nao' },
    { char: '健', meaning: 'Healthy', onyomi: 'ken', kunyomi: 'suko' },
    { char: '康', meaning: 'Health / Ease', onyomi: 'kou', kunyomi: '-' },
    { char: '命', meaning: 'Life / Fate', onyomi: 'mei/myou', kunyomi: 'inochi' },
    { char: '死', meaning: 'Death / Die', onyomi: 'shi', kunyomi: 'shi' },
    { char: '活', meaning: 'Life / Active', onyomi: 'katsu', kunyomi: 'i' },
    { char: '育', meaning: 'Raise / Grow', onyomi: 'iku', kunyomi: 'soda/hagu' },
    { char: '老', meaning: 'Old / Aged', onyomi: 'rou', kunyomi: 'o/fu' },
    { char: '若', meaning: 'Young', onyomi: 'jaku/nyaku', kunyomi: 'waka' }
  ],
  nature_advanced: [
    { char: '環', meaning: 'Ring / Environment', onyomi: 'kan', kunyomi: 'wa' },
    { char: '境', meaning: 'Boundary / Environment', onyomi: 'kyou/kei', kunyomi: 'sakai' },
    { char: '陸', meaning: 'Land', onyomi: 'riku', kunyomi: '-' },
    { char: '島', meaning: 'Island', onyomi: 'tou', kunyomi: 'shima' },
    { char: '湖', meaning: 'Lake', onyomi: 'ko', kunyomi: 'mizuumi' },
    { char: '港', meaning: 'Harbor', onyomi: 'kou', kunyomi: 'minato' },
    { char: '谷', meaning: 'Valley', onyomi: 'koku', kunyomi: 'tani' },
    { char: '岸', meaning: 'Shore / Bank', onyomi: 'gan', kunyomi: 'kishi' },
    { char: '波', meaning: 'Wave', onyomi: 'ha', kunyomi: 'nami' },
    { char: '氷', meaning: 'Ice', onyomi: 'hyou', kunyomi: 'koori/hi' },
    { char: '温', meaning: 'Warm / Hot', onyomi: 'on', kunyomi: 'atata/nuku' },
    { char: '暖', meaning: 'Warm', onyomi: 'dan', kunyomi: 'atata' },
    { char: '涼', meaning: 'Cool / Refreshing', onyomi: 'ryou', kunyomi: 'suzu' },
    { char: '冷', meaning: 'Cold', onyomi: 'rei', kunyomi: 'tsume/hi/sa' },
    { char: '煙', meaning: 'Smoke', onyomi: 'en', kunyomi: 'kemuri' },
    { char: '灰', meaning: 'Ash', onyomi: 'kai', kunyomi: 'hai' },
    { char: '虫', meaning: 'Insect / Bug', onyomi: 'chuu', kunyomi: 'mushi' },
    { char: '鳥', meaning: 'Bird', onyomi: 'chou', kunyomi: 'tori' },
    { char: '魚', meaning: 'Fish', onyomi: 'gyo', kunyomi: 'uo/sakana' },
    { char: '犬', meaning: 'Dog', onyomi: 'ken', kunyomi: 'inu' }
  ]
};

export const N3_EXAM_DATA = {
  easy: [
    { sentence: "この *しな*ものは *う*りきれです。", target: "品", reading: "しな", options: ["品", "売", "商", "買"], translation: "This product is sold out." },
    { sentence: "*あい*する ひとに であいました。", target: "愛", reading: "あい", options: ["愛", "感", "情", "心"], translation: "I met the person I love." },
    { sentence: "*いし*の うえに すわりました。", target: "島", reading: "しま", options: ["島", "湖", "陸", "港"], translation: "I sat on the stone." },
    { sentence: "きょう の *てんき*は あたたかいです。", target: "温", reading: "あたた", options: ["温", "暖", "冷", "涼"], translation: "Today's weather is warm." },
    { sentence: "*いぬ*と さんぽに いきます。", target: "犬", reading: "いぬ", options: ["犬", "鳥", "魚", "虫"], translation: "I go for a walk with the dog." }
  ],
  mid: [
    { sentence: "*せい*じの もんだいは むずかしい。", target: "政", reading: "せい", options: ["政", "治", "法", "制"], translation: "Political problems are difficult." },
    { sentence: "*けんきゅう*を つづけて います。", target: "究", reading: "きゅう", options: ["究", "研", "調", "査"], translation: "I continue doing research." },
    { sentence: "しょうひ*ぜい*が あがりました。", target: "税", reading: "ぜい", options: ["税", "費", "値", "利"], translation: "The consumption tax went up." },
    { sentence: "*わら*って すごしましょう。", target: "笑", reading: "わら", options: ["笑", "泣", "怒", "喜"], translation: "Let's spend time laughing." },
    { sentence: "にほんの *れきし*を べんきょうします。", target: "歴", reading: "れき", options: ["歴", "史", "伝", "統"], translation: "I study Japanese history." }
  ],
  hard: [
    { sentence: "*ほうりつ*を まもらなければ なりません。", target: "律", reading: "りつ", options: ["律", "法", "則", "規"], translation: "You must obey the law." },
    { sentence: "*かんきょう*もんだいは じゅうようです。", target: "環", reading: "かん", options: ["環", "境", "陸", "島"], translation: "Environmental issues are important." },
    { sentence: "この *くすり*を のんでください。", target: "薬", reading: "くすり", options: ["薬", "医", "病", "痛"], translation: "Please take this medicine." },
    { sentence: "*ぎ*じゅつが はったつしました。", target: "芸", reading: "げい", options: ["芸", "術", "美", "演"], translation: "Technology has developed." },
    { sentence: "*けんこう*に きをつけて ください。", target: "健", reading: "けん", options: ["健", "康", "活", "命"], translation: "Please take care of your health." }
  ],
  top_hard: [
    { sentence: "*せんきょ*の けっかが はっぴょうされた。", target: "選", reading: "せん", options: ["選", "挙", "権", "議"], translation: "The election results were announced." },
    { sentence: "この *りろん*は ふくざつです。", target: "論", reading: "ろん", options: ["論", "説", "理", "科"], translation: "This theory is complex." },
    { sentence: "*きけん*な ばしょに ちかづかないで。", target: "険", reading: "けん", options: ["険", "危", "害", "防"], translation: "Don't go near dangerous places." },
    { sentence: "*しま*に わたる ふねが あります。", target: "島", reading: "しま", options: ["島", "陸", "港", "湖"], translation: "There is a boat to cross to the island." },
    { sentence: "この *えんげき*は すばらしかった。", target: "劇", reading: "げき", options: ["劇", "演", "映", "画"], translation: "This theatrical performance was wonderful." }
  ]
};
