// JLPT N4 Kanji Dataset (~170 kanji)
export const N4_KANJI_DATA = {
  actions: [
    { char: '育', meaning: 'Raise/Grow', onyomi: 'iku', kunyomi: 'soda' },
    { char: '飲', meaning: 'Drink', onyomi: 'in', kunyomi: 'no' },
    { char: '運', meaning: 'Transport/Luck', onyomi: 'un', kunyomi: 'hako' },
    { char: '泳', meaning: 'Swim', onyomi: 'ei', kunyomi: 'oyo' },
    { char: '開', meaning: 'Open', onyomi: 'kai', kunyomi: 'a/hira' },
    { char: '起', meaning: 'Wake up', onyomi: 'ki', kunyomi: 'o' },
    { char: '去', meaning: 'Past/Leave', onyomi: 'kyo/ko', kunyomi: 'sa' },
    { char: '始', meaning: 'Begin', onyomi: 'shi', kunyomi: 'haji' },
    { char: '終', meaning: 'End', onyomi: 'shuu', kunyomi: 'o' },
    { char: '習', meaning: 'Learn', onyomi: 'shuu', kunyomi: 'nara' },
    { char: '集', meaning: 'Gather', onyomi: 'shuu', kunyomi: 'atsu' },
    { char: '乗', meaning: 'Ride', onyomi: 'jou', kunyomi: 'no' },
    { char: '進', meaning: 'Advance', onyomi: 'shin', kunyomi: 'susu' },
    { char: '送', meaning: 'Send', onyomi: 'sou', kunyomi: 'oku' },
    { char: '打', meaning: 'Hit', onyomi: 'da', kunyomi: 'u' },
    { char: '待', meaning: 'Wait', onyomi: 'tai', kunyomi: 'ma' },
    { char: '追', meaning: 'Chase', onyomi: 'tsui', kunyomi: 'o' },
    { char: '投', meaning: 'Throw', onyomi: 'tou', kunyomi: 'na' },
    { char: '登', meaning: 'Climb', onyomi: 'tou/to', kunyomi: 'nobo' },
    { char: '動', meaning: 'Move', onyomi: 'dou', kunyomi: 'ugo' },
    { char: '配', meaning: 'Distribute', onyomi: 'hai', kunyomi: 'kuba' },
    { char: '発', meaning: 'Depart/Emit', onyomi: 'hatsu/hotsu', kunyomi: '-' },
    { char: '返', meaning: 'Return', onyomi: 'hen', kunyomi: 'ka' },
    { char: '放', meaning: 'Release', onyomi: 'hou', kunyomi: 'hana' },
    { char: '遊', meaning: 'Play', onyomi: 'yuu/yu', kunyomi: 'aso' },
    { char: '流', meaning: 'Flow', onyomi: 'ryuu/ru', kunyomi: 'naga' },
    { char: '落', meaning: 'Fall', onyomi: 'raku', kunyomi: 'o' },
    { char: '練', meaning: 'Practice', onyomi: 'ren', kunyomi: 'ne' },
    { char: '取', meaning: 'Take', onyomi: 'shu', kunyomi: 'to' },
    { char: '受', meaning: 'Receive', onyomi: 'ju', kunyomi: 'u' },
    { char: '拾', meaning: 'Pick up', onyomi: 'shuu/juu', kunyomi: 'hiro' },
    { char: '申', meaning: 'Say/Declare', onyomi: 'shin', kunyomi: 'mou' },
    { char: '助', meaning: 'Help', onyomi: 'jo', kunyomi: 'tasu' },
    { char: '死', meaning: 'Death', onyomi: 'shi', kunyomi: 'si' },
    { char: '働', meaning: 'Work', onyomi: 'dou', kunyomi: 'hatara' },
    { char: '転', meaning: 'Turn', onyomi: 'ten', kunyomi: 'koro' },
    { char: '止', meaning: 'Stop', onyomi: 'shi', kunyomi: 'to' },
    { char: '走', meaning: 'Run', onyomi: 'sou', kunyomi: 'hashi' }
  ],
  places: [
    { char: '駅', meaning: 'Station', onyomi: 'eki', kunyomi: '-' },
    { char: '館', meaning: 'Public Building', onyomi: 'kan', kunyomi: 'yakata' },
    { char: '局', meaning: 'Bureau/Office', onyomi: 'kyoku', kunyomi: '-' },
    { char: '院', meaning: 'Institution', onyomi: 'in', kunyomi: '-' },
    { char: '所', meaning: 'Place', onyomi: 'sho', kunyomi: 'tokoro' },
    { char: '都', meaning: 'Capital', onyomi: 'to/tsu', kunyomi: 'miya' },
    { char: '県', meaning: 'Prefecture', onyomi: 'ken', kunyomi: '-' },
    { char: '州', meaning: 'State/Province', onyomi: 'shuu', kunyomi: 'su' },
    { char: '島', meaning: 'Island', onyomi: 'tou', kunyomi: 'shima' },
    { char: '港', meaning: 'Port', onyomi: 'kou', kunyomi: 'minato' },
    { char: '庫', meaning: 'Warehouse', onyomi: 'ko/ku', kunyomi: 'kura' },
    { char: '庭', meaning: 'Garden', onyomi: 'tei', kunyomi: 'niwa' },
    { char: '屋', meaning: 'Shop/Roof', onyomi: 'oku', kunyomi: 'ya' },
    { char: '区', meaning: 'Ward', onyomi: 'ku', kunyomi: '-' },
    { char: '宮', meaning: 'Palace', onyomi: 'kyuu/guu', kunyomi: 'miya' },
    { char: '宿', meaning: 'Inn', onyomi: 'shuku', kunyomi: 'yado' },
    { char: '階', meaning: 'Floor', onyomi: 'kai', kunyomi: 'kizaha' },
    { char: '路', meaning: 'Road', onyomi: 'ro', kunyomi: 'ji/michi' },
    { char: '岸', meaning: 'Coast', onyomi: 'gan', kunyomi: 'kishi' },
    { char: '湖', meaning: 'Lake', onyomi: 'ko', kunyomi: 'mizuumi' },
    { char: '畑', meaning: 'Field', onyomi: '-', kunyomi: 'hata' },
    { char: '坂', meaning: 'Slope', onyomi: 'han', kunyomi: 'saka' }
  ],
  society: [
    { char: '医', meaning: 'Doctor', onyomi: 'i', kunyomi: '-' },
    { char: '員', meaning: 'Member', onyomi: 'in', kunyomi: '-' },
    { char: '究', meaning: 'Research', onyomi: 'kyuu', kunyomi: 'kiwa' },
    { char: '業', meaning: 'Industry', onyomi: 'gyou/gou', kunyomi: 'waza' },
    { char: '銀', meaning: 'Silver', onyomi: 'gin', kunyomi: 'shirogane' },
    { char: '役', meaning: 'Role/Service', onyomi: 'yaku/eki', kunyomi: '-' },
    { char: '薬', meaning: 'Medicine', onyomi: 'yaku', kunyomi: 'kusuri' },
    { char: '問', meaning: 'Question', onyomi: 'mon', kunyomi: 'to' },
    { char: '題', meaning: 'Topic', onyomi: 'dai', kunyomi: '-' },
    { char: '勉', meaning: 'Exertion', onyomi: 'ben', kunyomi: 'tsuto' },
    { char: '商', meaning: 'Trade', onyomi: 'shou', kunyomi: 'akina' },
    { char: '礼', meaning: 'Rite/Bow', onyomi: 'rei/rai', kunyomi: '-' },
    { char: '和', meaning: 'Harmony/Japan', onyomi: 'wa/o', kunyomi: 'yawaragi' },
    { char: '社', meaning: 'Company', onyomi: 'sha', kunyomi: 'yashiro' },
    { char: '事', meaning: 'Thing', onyomi: 'ji', kunyomi: 'koto' },
    { char: '仕', meaning: 'Serve', onyomi: 'shi', kunyomi: 'tsuka' },
    { char: '職', meaning: 'Work', onyomi: 'shoku', kunyomi: '-' },
    { char: '案', meaning: 'Plan', onyomi: 'an', kunyomi: '-' },
    { char: '定', meaning: 'Determine', onyomi: 'tei/jou', kunyomi: 'sada' },
    { char: '主', meaning: 'Main/Lord', onyomi: 'shu', kunyomi: 'nushi' },
    { char: '者', meaning: 'Person', onyomi: 'sha', kunyomi: 'mono' },
    { char: '号', meaning: 'Number/Sign', onyomi: 'gou', kunyomi: 'sake' },
    { char: '係', meaning: 'Connection', onyomi: 'kei', kunyomi: 'kaka' },
    { char: '農', meaning: 'Agriculture', onyomi: 'nou', kunyomi: '-' }
  ],
  adjectives: [
    { char: '悪', meaning: 'Bad', onyomi: 'aku', kunyomi: 'waru' },
    { char: '安', meaning: 'Cheap/Ease', onyomi: 'an', kunyomi: 'yasu' },
    { char: '暗', meaning: 'Dark', onyomi: 'an', kunyomi: 'kura' },
    { char: '寒', meaning: 'Cold', onyomi: 'kan', kunyomi: 'samu' },
    { char: '暑', meaning: 'Hot', onyomi: 'sho', kunyomi: 'atsu' },
    { char: '軽', meaning: 'Light', onyomi: 'kei', kunyomi: 'karu' },
    { char: '重', meaning: 'Heavy', onyomi: 'juu/chou', kunyomi: 'omo/kasa' },
    { char: '短', meaning: 'Short', onyomi: 'tan', kunyomi: 'mika' },
    { char: '低', meaning: 'Low', onyomi: 'tei', kunyomi: 'hiku' },
    { char: '弱', meaning: 'Weak', onyomi: 'jaku', kunyomi: 'yowa' },
    { char: '強', meaning: 'Strong', onyomi: 'kyou/gou', kunyomi: 'tsuyo' },
    { char: '幸', meaning: 'Happiness', onyomi: 'kou', kunyomi: 'shiawa/sachi' },
    { char: '苦', meaning: 'Suffering', onyomi: 'ku', kunyomi: 'kuru/niga' },
    { char: '深', meaning: 'Deep', onyomi: 'shin', kunyomi: 'fuka' },
    { char: '美', meaning: 'Beautiful', onyomi: 'bi', kunyomi: 'utsuku' },
    { char: '悲', meaning: 'Sad', onyomi: 'hi', kunyomi: 'kana' },
    { char: '静', meaning: 'Quiet', onyomi: 'sei/jou', kunyomi: 'shizu' },
    { char: '急', meaning: 'Sudden', onyomi: 'kyuu', kunyomi: 'iso' },
    { char: '速', meaning: 'Fast', onyomi: 'soku', kunyomi: 'haya' },
    { char: '平', meaning: 'Flat/Peace', onyomi: 'hei/byou', kunyomi: 'tai/hira' },
    { char: '真', meaning: 'True', onyomi: 'shin', kunyomi: 'ma' },
    { char: '正', meaning: 'Correct', onyomi: 'sei', kunyomi: 'tada' }
  ],
  objects: [
    { char: '荷', meaning: 'Luggage', onyomi: 'ka', kunyomi: 'ni' },
    { char: '具', meaning: 'Tool', onyomi: 'gu', kunyomi: '-' },
    { char: '箱', meaning: 'Box', onyomi: 'sou', kunyomi: 'hako' },
    { char: '紙', meaning: 'Paper', onyomi: 'shi', kunyomi: 'kami' },
    { char: '皿', meaning: 'Plate', onyomi: 'bei', kunyomi: 'sara' },
    { char: '服', meaning: 'Clothes', onyomi: 'fuku', kunyomi: '-' },
    { char: '布', meaning: 'Cloth', onyomi: 'fu', kunyomi: 'nuno' },
    { char: '物', meaning: 'Thing', onyomi: 'butsu/motsu', kunyomi: 'mono' },
    { char: '品', meaning: 'Article', onyomi: 'hin', kunyomi: 'shina' },
    { char: '筆', meaning: 'Brush', onyomi: 'hitsu', kunyomi: 'fude' },
    { char: '笛', meaning: 'Flute', onyomi: 'teki', kunyomi: 'fue' },
    { char: '鉄', meaning: 'Iron', onyomi: 'tetsu', kunyomi: 'kurogane' },
    { char: '炭', meaning: 'Coal', onyomi: 'tan', kunyomi: 'sumi' },
    { char: '酒', meaning: 'Sake', onyomi: 'shu', kunyomi: 'sake' },
    { char: '湯', meaning: 'Hot Water', onyomi: 'tou', kunyomi: 'yu' },
    { char: '氷', meaning: 'Ice', onyomi: 'hyou', kunyomi: 'koori' },
    { char: '豆', meaning: 'Bean', onyomi: 'tou/zu', kunyomi: 'mame' },
    { char: '魚', meaning: 'Fish', onyomi: 'gyo', kunyomi: 'sakana' },
    { char: '肉', meaning: 'Meat', onyomi: 'niku', kunyomi: '-' },
    { char: '茶', meaning: 'Tea', onyomi: 'cha/sa', kunyomi: '-' }
  ],
  nature_time: [
    { char: '温', meaning: 'Warm', onyomi: 'on', kunyomi: 'atata' },
    { char: '界', meaning: 'World', onyomi: 'kai', kunyomi: '-' },
    { char: '陽', meaning: 'Sun', onyomi: 'you', kunyomi: '-' },
    { char: '星', meaning: 'Star', onyomi: 'sei/shou', kunyomi: 'hoshi' },
    { char: '光', meaning: 'Light', onyomi: 'kou', kunyomi: 'hika' },
    { char: '波', meaning: 'Wave', onyomi: 'ha', kunyomi: 'nami' },
    { char: '風', meaning: 'Wind', onyomi: 'fuu', kunyomi: 'kaze' },
    { char: '海', meaning: 'Sea', onyomi: 'kai', kunyomi: 'umi' },
    { char: '空', meaning: 'Sky', onyomi: 'kuu', kunyomi: 'sora' },
    { char: '雪', meaning: 'Snow', onyomi: 'setsu', kunyomi: 'yuki' },
    { char: '季', meaning: 'Season', onyomi: 'ki', kunyomi: '-' },
    { char: '春', meaning: 'Spring', onyomi: 'shun', kunyomi: 'haru' },
    { char: '夏', meaning: 'Summer', onyomi: 'ka', kunyomi: 'natsu' },
    { char: '秋', meaning: 'Autumn', onyomi: 'shuu', kunyomi: 'aki' },
    { char: '冬', meaning: 'Winter', onyomi: 'tou', kunyomi: 'fuyu' },
    { char: '昔', meaning: 'Ancient/Old Times', onyomi: 'seki/shaku', kunyomi: 'mukashi' },
    { char: '世', meaning: 'World/Generation', onyomi: 'sei/se', kunyomi: 'yo' },
    { char: '度', meaning: 'Degree/Time', onyomi: 'do', kunyomi: 'tabi' },
    { char: '秒', meaning: 'Second', onyomi: 'byou', kunyomi: '-' },
    { char: '期', meaning: 'Period', onyomi: 'ki', kunyomi: '-' }
  ],
  abstract_other: [
    { char: '意', meaning: 'Mind/Meaning', onyomi: 'i', kunyomi: '-' },
    { char: '感', meaning: 'Feel', onyomi: 'kan', kunyomi: '-' },
    { char: '想', meaning: 'Concept/Thought', onyomi: 'sou/so', kunyomi: '-' },
    { char: '申', meaning: 'Declare', onyomi: 'shin', kunyomi: 'mou' },
    { char: '神', meaning: 'God', onyomi: 'shin/jin', kunyomi: 'kami' },
    { char: '真', meaning: 'True/Exact', onyomi: 'shin', kunyomi: 'ma' },
    { char: '全', meaning: 'All', onyomi: 'zen', kunyomi: 'sube' },
    { char: '相', meaning: 'Mutual', onyomi: 'sou/shou', kunyomi: 'ai' },
    { char: '対', meaning: 'Opposite', onyomi: 'tai/tsui', kunyomi: '-' },
    { char: '代', meaning: 'Substitute', onyomi: 'dai/tai', kunyomi: 'ka' },
    { char: '最', meaning: 'Most', onyomi: 'sai', kunyomi: 'mo' },
    { char: '第', meaning: 'Ordinal Number', onyomi: 'dai', kunyomi: '-' },
    { char: '等', meaning: 'Equal', onyomi: 'tou', kunyomi: 'hito' },
    { char: '倍', meaning: 'Double', onyomi: 'bai', kunyomi: '-' },
    { char: '反', meaning: 'Anti/Opposite', onyomi: 'han/tan', kunyomi: 'so' },
    { char: '由', meaning: 'Reason', onyomi: 'yu/yui', kunyomi: 'yoshi' },
    { char: '予', meaning: 'Previously', onyomi: 'yo', kunyomi: 'ata' },
    { char: '様', meaning: 'Appearance/Mr.', onyomi: 'you', kunyomi: 'sama' },
    { char: '両', meaning: 'Both', onyomi: 'ryou', kunyomi: 'teru' },
    { char: '和', meaning: 'Harmony', onyomi: 'wa', kunyomi: 'yawaragi' },
    { char: '化', meaning: 'Change', onyomi: 'ka/ke', kunyomi: 'ba' },
    { char: '漢', meaning: 'China', onyomi: 'kan', kunyomi: '-' },
    { char: '字', meaning: 'Character', onyomi: 'ji', kunyomi: 'aza' }
  ],
  body: [
    { char: '鼻', meaning: 'Nose', onyomi: 'bi', kunyomi: 'hana' },
    { char: '歯', meaning: 'Tooth', onyomi: 'shi', kunyomi: 'ha' },
    { char: '耳', meaning: 'Ear', onyomi: 'ji', kunyomi: 'mimi' },
    { char: '目', meaning: 'Eye', onyomi: 'moku', kunyomi: 'me' },
    { char: '足', meaning: 'Foot', onyomi: 'soku', kunyomi: 'ashi' },
    { char: '手', meaning: 'Hand', onyomi: 'shu', kunyomi: 'te' },
    { char: '心', meaning: 'Heart', onyomi: 'shin', kunyomi: 'kokoro' },
    { char: '体', meaning: 'Body', onyomi: 'tai', kunyomi: 'karada' }
  ]
};

export const N4_EXAM_DATA = {
  easy: [
    { sentence: "きのうの *よる* ともだちに あいました。", target: "夜", reading: "よる", options: ["夜", "朝", "昼", "夕"], translation: "I met a friend last night." },
    { sentence: "この *まち*は とても きれいです。", target: "町", reading: "まち", options: ["町", "村", "市", "区"], translation: "This town is very beautiful." },
    { sentence: "*はし*って ください。", target: "走", reading: "はし", options: ["走", "歩", "止", "動"], translation: "Please run." },
    { sentence: "わたしは *うみ*が すきです。", target: "海", reading: "うみ", options: ["海", "池", "川", "湖"], translation: "I like the sea." },
    { sentence: "*つよ*い かぜが ふいて います。", target: "強", reading: "つよ", options: ["強", "弱", "太", "細"], translation: "A strong wind is blowing." }
  ],
  mid: [
    { sentence: "*かんが*えてから こたえて ください。", target: "考", reading: "かんが", options: ["考", "教", "答", "習"], translation: "Please think before answering." },
    { sentence: "あの *はし*を わたります。", target: "橋", reading: "はし", options: ["橋", "階", "門", "駅"], translation: "I will cross that bridge." },
    { sentence: "でんしゃに *の*ります。", target: "乗", reading: "の", options: ["乗", "運", "送", "届"], translation: "I will ride the train." },
    { sentence: "*あか*るい へやで べんきょう しましょう。", target: "明", reading: "あか", options: ["明", "暗", "光", "白"], translation: "Let's study in a bright room." },
    { sentence: "この もんだいの *こた*えは なんですか。", target: "答", reading: "こた", options: ["答", "問", "題", "考"], translation: "What is the answer to this problem?" }
  ],
  hard: [
    { sentence: "かいしゃに *つと*めて います。", target: "勤", reading: "つと", options: ["勤", "働", "仕", "務"], translation: "I work at a company." },
    { sentence: "この *しつもん*に こたえて ください。", target: "質", reading: "しつ", options: ["質", "問", "題", "答"], translation: "Please answer this question." },
    { sentence: "えいがを *み*に いきましょう。", target: "映", reading: "み", options: ["映", "画", "見", "視"], translation: "Let's go see a movie." },
    { sentence: "あの ひとは *わか*いです。", target: "若", reading: "わか", options: ["若", "少", "新", "早"], translation: "That person is young." },
    { sentence: "*あき*に こうようが きれいです。", target: "秋", reading: "あき", options: ["秋", "春", "夏", "冬"], translation: "The autumn leaves are beautiful in fall." }
  ],
  top_hard: [
    { sentence: "この *え*を かいた ひとは だれですか。", target: "画", reading: "え", options: ["画", "映", "絵", "写"], translation: "Who drew this picture?" },
    { sentence: "かれは *こころ*が やさしいです。", target: "心", reading: "こころ", options: ["心", "体", "頭", "首"], translation: "He has a kind heart." },
    { sentence: "この もんだいは *とく*べつ むずかしいです。", target: "特", reading: "とく", options: ["特", "別", "同", "正"], translation: "This problem is especially difficult." },
    { sentence: "*ひかり*が まぶしいです。", target: "光", reading: "ひかり", options: ["光", "明", "星", "空"], translation: "The light is bright/dazzling." },
    { sentence: "でんしゃが *きゅう*に とまりました。", target: "急", reading: "きゅう", options: ["急", "速", "早", "遅"], translation: "The train stopped suddenly." }
  ]
};
