// JLPT N4 Kanji Dataset (~170 kanji)
export const N4_KANJI_DATA = {
  actions: [
    { char: '思', meaning: 'Think', onyomi: 'shi', kunyomi: 'omo' },
    { char: '知', meaning: 'Know', onyomi: 'chi', kunyomi: 'shi' },
    { char: '言', meaning: 'Say', onyomi: 'gen/gon', kunyomi: 'i/koto' },
    { char: '使', meaning: 'Use', onyomi: 'shi', kunyomi: 'tsuka' },
    { char: '作', meaning: 'Make', onyomi: 'saku/sa', kunyomi: 'tsuku' },
    { char: '持', meaning: 'Hold', onyomi: 'ji', kunyomi: 'mo' },
    { char: '待', meaning: 'Wait', onyomi: 'tai', kunyomi: 'ma' },
    { char: '走', meaning: 'Run', onyomi: 'sou', kunyomi: 'hashi' },
    { char: '歩', meaning: 'Walk', onyomi: 'ho/bu', kunyomi: 'aru/ayu' },
    { char: '止', meaning: 'Stop', onyomi: 'shi', kunyomi: 'to/ya' },
    { char: '始', meaning: 'Begin', onyomi: 'shi', kunyomi: 'haji' },
    { char: '終', meaning: 'End', onyomi: 'shuu', kunyomi: 'o' },
    { char: '送', meaning: 'Send', onyomi: 'sou', kunyomi: 'oku' },
    { char: '届', meaning: 'Deliver', onyomi: '-', kunyomi: 'todo' },
    { char: '開', meaning: 'Open', onyomi: 'kai', kunyomi: 'a/hira' },
    { char: '閉', meaning: 'Close', onyomi: 'hei', kunyomi: 'shi/to' },
    { char: '教', meaning: 'Teach', onyomi: 'kyou', kunyomi: 'oshi' },
    { char: '習', meaning: 'Learn', onyomi: 'shuu', kunyomi: 'nara' },
    { char: '考', meaning: 'Consider', onyomi: 'kou', kunyomi: 'kanga' },
    { char: '答', meaning: 'Answer', onyomi: 'tou', kunyomi: 'kota' }
  ],
  body: [
    { char: '目', meaning: 'Eye', onyomi: 'moku', kunyomi: 'me' },
    { char: '耳', meaning: 'Ear', onyomi: 'ji', kunyomi: 'mimi' },
    { char: '口', meaning: 'Mouth', onyomi: 'kou/ku', kunyomi: 'kuchi' },
    { char: '手', meaning: 'Hand', onyomi: 'shu', kunyomi: 'te' },
    { char: '足', meaning: 'Foot / Leg', onyomi: 'soku', kunyomi: 'ashi/ta' },
    { char: '首', meaning: 'Neck', onyomi: 'shu', kunyomi: 'kubi' },
    { char: '声', meaning: 'Voice', onyomi: 'sei', kunyomi: 'koe' },
    { char: '顔', meaning: 'Face', onyomi: 'gan', kunyomi: 'kao' },
    { char: '頭', meaning: 'Head', onyomi: 'tou/zu', kunyomi: 'atama' },
    { char: '心', meaning: 'Heart / Mind', onyomi: 'shin', kunyomi: 'kokoro' },
    { char: '体', meaning: 'Body', onyomi: 'tai', kunyomi: 'karada' },
    { char: '力', meaning: 'Power / Strength', onyomi: 'ryoku/riki', kunyomi: 'chikara' }
  ],
  town: [
    { char: '町', meaning: 'Town', onyomi: 'chou', kunyomi: 'machi' },
    { char: '村', meaning: 'Village', onyomi: 'son', kunyomi: 'mura' },
    { char: '市', meaning: 'City / Market', onyomi: 'shi', kunyomi: 'ichi' },
    { char: '区', meaning: 'Ward / District', onyomi: 'ku', kunyomi: '-' },
    { char: '京', meaning: 'Capital', onyomi: 'kyou/kei', kunyomi: '-' },
    { char: '世', meaning: 'World / Generation', onyomi: 'sei/se', kunyomi: 'yo' },
    { char: '界', meaning: 'World / Boundary', onyomi: 'kai', kunyomi: '-' },
    { char: '場', meaning: 'Place', onyomi: 'jou', kunyomi: 'ba' },
    { char: '所', meaning: 'Place / Location', onyomi: 'sho', kunyomi: 'tokoro' },
    { char: '家', meaning: 'House / Home', onyomi: 'ka/ke', kunyomi: 'ie/ya' },
    { char: '室', meaning: 'Room', onyomi: 'shitsu', kunyomi: 'muro' },
    { char: '屋', meaning: 'Shop / Roof', onyomi: 'oku', kunyomi: 'ya' },
    { char: '堂', meaning: 'Hall / Temple', onyomi: 'dou', kunyomi: '-' },
    { char: '院', meaning: 'Institute', onyomi: 'in', kunyomi: '-' },
    { char: '駅', meaning: 'Station', onyomi: 'eki', kunyomi: '-' },
    { char: '門', meaning: 'Gate', onyomi: 'mon', kunyomi: 'kado' },
    { char: '橋', meaning: 'Bridge', onyomi: 'kyou', kunyomi: 'hashi' },
    { char: '池', meaning: 'Pond', onyomi: 'chi', kunyomi: 'ike' }
  ],
  transport: [
    { char: '乗', meaning: 'Ride', onyomi: 'jou', kunyomi: 'no' },
    { char: '運', meaning: 'Carry / Luck', onyomi: 'un', kunyomi: 'hako' },
    { char: '動', meaning: 'Move', onyomi: 'dou', kunyomi: 'ugo' },
    { char: '通', meaning: 'Pass / Through', onyomi: 'tsuu', kunyomi: 'too/kayo' },
    { char: '進', meaning: 'Advance', onyomi: 'shin', kunyomi: 'susu' },
    { char: '転', meaning: 'Turn / Roll', onyomi: 'ten', kunyomi: 'koro' },
    { char: '急', meaning: 'Hurry / Sudden', onyomi: 'kyuu', kunyomi: 'iso' },
    { char: '遅', meaning: 'Late / Slow', onyomi: 'chi', kunyomi: 'oso/oku' },
    { char: '届', meaning: 'Reach / Deliver', onyomi: '-', kunyomi: 'todo' },
    { char: '引', meaning: 'Pull', onyomi: 'in', kunyomi: 'hi' },
    { char: '押', meaning: 'Push', onyomi: 'ou', kunyomi: 'o' },
    { char: '飛', meaning: 'Fly', onyomi: 'hi', kunyomi: 'to' }
  ],
  adjectives: [
    { char: '早', meaning: 'Early / Fast', onyomi: 'sou/sa', kunyomi: 'haya' },
    { char: '近', meaning: 'Near', onyomi: 'kin', kunyomi: 'chika' },
    { char: '遠', meaning: 'Far', onyomi: 'en/on', kunyomi: 'too' },
    { char: '強', meaning: 'Strong', onyomi: 'kyou/gou', kunyomi: 'tsuyo' },
    { char: '弱', meaning: 'Weak', onyomi: 'jaku', kunyomi: 'yowa' },
    { char: '重', meaning: 'Heavy', onyomi: 'juu/chou', kunyomi: 'omo/kasa/e' },
    { char: '軽', meaning: 'Light (weight)', onyomi: 'kei', kunyomi: 'karu' },
    { char: '暗', meaning: 'Dark', onyomi: 'an', kunyomi: 'kura' },
    { char: '明', meaning: 'Bright / Light', onyomi: 'mei/myou', kunyomi: 'aka/ake/aki' },
    { char: '広', meaning: 'Wide', onyomi: 'kou', kunyomi: 'hiro' },
    { char: '狭', meaning: 'Narrow', onyomi: 'kyou', kunyomi: 'sema/seba' },
    { char: '太', meaning: 'Fat / Thick', onyomi: 'tai/ta', kunyomi: 'futo' },
    { char: '細', meaning: 'Thin / Narrow', onyomi: 'sai', kunyomi: 'hoso/koma' },
    { char: '忙', meaning: 'Busy', onyomi: 'bou', kunyomi: 'isoga' },
    { char: '若', meaning: 'Young', onyomi: 'jaku', kunyomi: 'waka' },
    { char: '悪', meaning: 'Bad / Evil', onyomi: 'aku/o', kunyomi: 'waru' },
    { char: '正', meaning: 'Correct / Right', onyomi: 'sei/shou', kunyomi: 'tada/masa' },
    { char: '特', meaning: 'Special', onyomi: 'toku', kunyomi: '-' },
    { char: '同', meaning: 'Same', onyomi: 'dou', kunyomi: 'ona/ono' },
    { char: '別', meaning: 'Different / Special', onyomi: 'betsu', kunyomi: 'waka' }
  ],
  nature_ext: [
    { char: '海', meaning: 'Sea', onyomi: 'kai', kunyomi: 'umi' },
    { char: '空', meaning: 'Sky / Empty', onyomi: 'kuu', kunyomi: 'sora/a/kara' },
    { char: '風', meaning: 'Wind', onyomi: 'fuu', kunyomi: 'kaze' },
    { char: '雪', meaning: 'Snow', onyomi: 'setsu', kunyomi: 'yuki' },
    { char: '林', meaning: 'Forest (small)', onyomi: 'rin', kunyomi: 'hayashi' },
    { char: '森', meaning: 'Forest (dense)', onyomi: 'shin', kunyomi: 'mori' },
    { char: '石', meaning: 'Stone', onyomi: 'seki/shaku', kunyomi: 'ishi' },
    { char: '地', meaning: 'Ground / Earth', onyomi: 'chi/ji', kunyomi: '-' },
    { char: '野', meaning: 'Field / Wild', onyomi: 'ya', kunyomi: 'no' },
    { char: '田', meaning: 'Rice Field', onyomi: 'den', kunyomi: 'ta' },
    { char: '春', meaning: 'Spring', onyomi: 'shun', kunyomi: 'haru' },
    { char: '夏', meaning: 'Summer', onyomi: 'ka', kunyomi: 'natsu' },
    { char: '秋', meaning: 'Autumn', onyomi: 'shuu', kunyomi: 'aki' },
    { char: '冬', meaning: 'Winter', onyomi: 'tou', kunyomi: 'fuyu' },
    { char: '光', meaning: 'Light', onyomi: 'kou', kunyomi: 'hikari' },
    { char: '星', meaning: 'Star', onyomi: 'sei', kunyomi: 'hoshi' }
  ],
  society: [
    { char: '会', meaning: 'Meet / Society', onyomi: 'kai/e', kunyomi: 'a' },
    { char: '社', meaning: 'Company / Shrine', onyomi: 'sha', kunyomi: 'yashiro' },
    { char: '工', meaning: 'Craft / Industry', onyomi: 'kou/ku', kunyomi: '-' },
    { char: '事', meaning: 'Thing / Matter', onyomi: 'ji/zu', kunyomi: 'koto' },
    { char: '仕', meaning: 'Serve / Do', onyomi: 'shi/ji', kunyomi: 'tsuka' },
    { char: '質', meaning: 'Quality / Question', onyomi: 'shitsu/shichi', kunyomi: '-' },
    { char: '問', meaning: 'Question', onyomi: 'mon', kunyomi: 'to' },
    { char: '題', meaning: 'Topic / Title', onyomi: 'dai', kunyomi: '-' },
    { char: '文', meaning: 'Text / Writing', onyomi: 'bun/mon', kunyomi: 'fumi' },
    { char: '字', meaning: 'Letter / Character', onyomi: 'ji', kunyomi: 'aza' },
    { char: '計', meaning: 'Count / Measure', onyomi: 'kei', kunyomi: 'haka' },
    { char: '音', meaning: 'Sound', onyomi: 'on/in', kunyomi: 'oto/ne' },
    { char: '色', meaning: 'Color', onyomi: 'shoku/shiki', kunyomi: 'iro' },
    { char: '映', meaning: 'Reflect / Movie', onyomi: 'ei', kunyomi: 'utsu/ha' },
    { char: '画', meaning: 'Picture / Plan', onyomi: 'ga/kaku', kunyomi: '-' },
    { char: '歌', meaning: 'Song / Sing', onyomi: 'ka', kunyomi: 'uta' },
    { char: '楽', meaning: 'Fun / Music', onyomi: 'gaku/raku', kunyomi: 'tano' },
    { char: '交', meaning: 'Mix / Associate', onyomi: 'kou', kunyomi: 'ma/kawa' }
  ],
  time_ext: [
    { char: '朝', meaning: 'Morning', onyomi: 'chou', kunyomi: 'asa' },
    { char: '昼', meaning: 'Daytime / Noon', onyomi: 'chuu', kunyomi: 'hiru' },
    { char: '夜', meaning: 'Night', onyomi: 'ya', kunyomi: 'yoru/yo' },
    { char: '夕', meaning: 'Evening', onyomi: 'seki', kunyomi: 'yuu' },
    { char: '午', meaning: 'Noon', onyomi: 'go', kunyomi: '-' },
    { char: '曜', meaning: 'Weekday', onyomi: 'you', kunyomi: '-' },
    { char: '週', meaning: 'Week', onyomi: 'shuu', kunyomi: '-' },
    { char: '去', meaning: 'Past / Leave', onyomi: 'kyo/ko', kunyomi: 'sa' },
    { char: '方', meaning: 'Direction / Way', onyomi: 'hou', kunyomi: 'kata' },
    { char: '回', meaning: 'Times / Turn', onyomi: 'kai/e', kunyomi: 'mawa' }
  ]
};

export const N4_EXAM_DATA = {
  easy: [
    { sentence: "きのうの *よる* ともだちに あいました。", target: "夜", reading: "よる", options: ["夜", "朝", "昼", "夕"], translation: "I met a friend last night." },
    { sentence: "この *まち*は とても きれいです。", target: "町", reading: "まち", options: ["町", "村", "市", "区"], translation: "This town is very beautiful." },
    { sentence: "*はし*って ください。", target: "走", reading: "はし", options: ["走", "歩", "止", "動"], translation: "Please run." },
    { sentence: "わたしは *うみ*が すきです。", target: "海", reading: "うみ", options: ["海", "池", "川", "湖"], translation: "I like the sea." },
    { sentence: "*つよ*い かぜが ふいて います。", target: "強", reading: "つよ", options: ["強", "弱", "太", "細"], translation: "A strong wind is blowing." }
  ],
  mid: [
    { sentence: "*かんが*えてから こたえて ください。", target: "考", reading: "かんが", options: ["考", "教", "答", "習"], translation: "Please think before answering." },
    { sentence: "あの *はし*を わたります。", target: "橋", reading: "はし", options: ["橋", "階", "門", "駅"], translation: "I will cross that bridge." },
    { sentence: "でんしゃに *の*ります。", target: "乗", reading: "の", options: ["乗", "運", "送", "届"], translation: "I will ride the train." },
    { sentence: "*あか*るい へやで べんきょう しましょう。", target: "明", reading: "あか", options: ["明", "暗", "光", "白"], translation: "Let's study in a bright room." },
    { sentence: "この もんだいの *こた*えは なんですか。", target: "答", reading: "こた", options: ["答", "問", "題", "考"], translation: "What is the answer to this problem?" }
  ],
  hard: [
    { sentence: "かいしゃに *つと*めて います。", target: "勤", reading: "つと", options: ["勤", "働", "仕", "務"], translation: "I work at a company." },
    { sentence: "この *しつもん*に こたえて ください。", target: "質", reading: "しつ", options: ["質", "問", "題", "答"], translation: "Please answer this question." },
    { sentence: "えいがを *み*に いきましょう。", target: "映", reading: "み", options: ["映", "画", "見", "視"], translation: "Let's go see a movie." },
    { sentence: "あの ひとは *わか*いです。", target: "若", reading: "わか", options: ["若", "少", "新", "早"], translation: "That person is young." },
    { sentence: "*あき*に こうようが きれいです。", target: "秋", reading: "あき", options: ["秋", "春", "夏", "冬"], translation: "The autumn leaves are beautiful in fall." }
  ],
  top_hard: [
    { sentence: "この *え*を かいた ひとは だれですか。", target: "画", reading: "え", options: ["画", "映", "絵", "写"], translation: "Who drew this picture?" },
    { sentence: "かれは *こころ*が やさしいです。", target: "心", reading: "こころ", options: ["心", "体", "頭", "首"], translation: "He has a kind heart." },
    { sentence: "この もんだいは *とく*べつ むずかしいです。", target: "特", reading: "とく", options: ["特", "別", "同", "正"], translation: "This problem is especially difficult." },
    { sentence: "*ひかり*が まぶしいです。", target: "光", reading: "ひかり", options: ["光", "明", "星", "空"], translation: "The light is bright/dazzling." },
    { sentence: "でんしゃが *きゅう*に とまりました。", target: "急", reading: "きゅう", options: ["急", "速", "早", "遅"], translation: "The train stopped suddenly." }
  ]
};
